### ISSUE TITLE
Edge button blocking mouse events

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#1149]
If you click and drag what you think is the background next to an edge's add-node button, the drag is blocked by the drop target on the edge button.

 This blocks any mouse interaction like primary/secondary clicks as well.

![bugbash-blocked_drag_target](<https://user-images.githubusercontent.com/25409734/197288584-ac207529-47c8-48ca-bb80-a69264def03e.gif>)

AB#15952523

**Comment by Ryanb58** [comment]
I experimented with making the following changes, but they reduce the target area of the drag and drop functionality, thus not pursuing.

+ libs\designer-ui\src\lib\actionbuttonv2\actionbuttonv2.less
```
.msla-action-button-v2 {
  ...
  pointer-events: auto; /* This ensures the button inside the drop zone is clickable */
}
```

+ libs/designer/src/lib/ui/styles.less
```
.edgebutton-foreignobject {
  ...
  pointer-events: none; /* This makes the drop zone "invisible" to mouse events */
}
```

**Comment by Ryanb58** [comment]
GIF to go along with previous comment.

![4BEF63AE-1701-47B5-BDF8-AAA36BCD78EF](https://github.com/Azure/LogicAppsUX/assets/3086302/3ea967a7-bfba-4d8e-bd53-d9b68e45f1f7)

**Comment by rllyy97** [comment]
Just tested locally and this has been resolved in our upcoming release
