### ISSUE TITLE
Incorrect node selection state

### ISSUE THREAD

**Issue by derek1ee** [Azure/LogicAppsUX#1176]
The node (action)'s selected state has a blue border, it should be the brand color instead per design.

AB#15994752

**Comment by Xiaowei-design** [comment]
After discussing with Ricki, let's follow the latest Fluent guidance: 
<img width="878" alt="Screenshot 2022-11-04 at 7 15 35 PM" src="https://user-images.githubusercontent.com/74429698/200096694-526a8c73-f7e9-4876-bd01-11d3dfb6ee6e.png">

**Comment by rllyy97** [comment]
Closing due to original report being a non-issue
