### ISSUE TITLE
Revamp storybook organization

### ISSUE THREAD

**Issue by rickixie** [Azure/LogicAppsUX#1186]
- Audit and align components that's shared across designers + data mapper
- Clean up documentations (e.g. what should be in storybook vs. not)
- Organize the components in ways that help dev to consume and test items
- Include design spec / usage guidance :)

AB#15999542

**Comment by NicL9923** [comment]
I think a good addition to this would be evaluating which components actually warrant a story - should specific implementations of components have stories? Does it depend on the component? Would it be more ideal to just do our abstracted components (i.e. Floating Panel from DM)? 

@rickixie Point being, I think it a very good idea to have a formal discussion that goes through and specifically identifies a formal list of components we want stories for as right now, at least in my mind, I think the above questions remain unanswered or at least un-agreed on
