### ISSUE TITLE
Can't add an action to merge parallel branches

### ISSUE THREAD

**Issue by derek1ee** [Azure/LogicAppsUX#1190]
In the GA designer, one can add an action to merge the parallel branches, but this is not possible with the new designer.

New:
![image](https://user-images.githubusercontent.com/6037220/197892172-14499c6a-ec33-4188-a29f-535decd63569.png)

Old:
![image](https://user-images.githubusercontent.com/6037220/197892285-8f215392-83d9-4e57-bf3b-0819ace6df69.png)

AB#15999888

**Comment by hartra344** [comment]
This is by design
