### ISSUE TITLE
Cannot find service bus connector when I search for "service bus"

### ISSUE THREAD

**Issue by shahparth-lab** [Azure/LogicAppsUX#1245]
Same behavior for search terms: 
1. "Cosmos DB"
2. "Http" or "Request"
3. "SQL" 

AB#16121547

**Comment by preetriti1** [comment]
@shahparth-lab - I am not able to repro this, are you trying this in private slot or staging slot?
Also if you have a video attached it will be helpful for investigation

**Comment by shahparth-lab** [comment]
This is portal.azure.com and not aka.ms/newdesigner
https://user-images.githubusercontent.com/80121421/199833347-d3531d49-8dfb-4811-818d-e32493960273.mov

**Comment by preetriti1** [comment]
> This is portal.azure.com and not aka.ms/newdesigner https://user-images.githubusercontent.com/80121421/199833347-d3531d49-8dfb-4811-818d-e32493960273.mov

Please wait until tomorrow to get release designer in Portal Prod and then you can double check. Currently there are old bits which you are hitting.

**Comment by preetriti1** [comment]
This should be fixed now in production.
