### ISSUE TITLE
Renaming the Card Title does not carry over with Dynamic Content (until save)

### ISSUE THREAD

**Issue by pixelmimic** [Azure/LogicAppsUX#1257]
### Describe the Bug

There seems to be an issue with the Dynamic Content. If you are blitzing through a new logic app, and you are renaming each trigger/action from the default to something meaningful, then try to use the output from any of these, the output content will appear, such as body, and allow you to select it. However, it's in a broken state. You will only find this out on Save. 

However, if you save your logic app after renaming but before using the output for the first time, it will work, if you rename something after using the output with the original name, it will fail to save. 

### Steps to Reproduce the Bug or Issue

1. Create a new logic app
2. Add a Request trigger
3. Allow a simple body like `{"bug":"True"}`
4. Add a Parse JSON action, configure to parse the above
5. Rename to Parse Request
6. Add a HTTP action and try to use the body from step 4. 
7. Hit save, it will error
8. Now remove the Body parameter in the HTTP action and hit save, it will work
9. Now re-add the Body from step 4. 
10. Hit save, it will work

Note, if you mouse over the Body parameter at each stage you will see the Card Title did not update at step 6 but has at step 9. Also when selecting the Body at step 6, the heading in the Dynamic Content list hasn't changed but at step 9 it has.

### Expected behavior

I would expect this to be Dynamic Content as it states and as the previous designer allowed. Instead, it's static. I found this bug the hard way, by creating about 25 actions before it failed.

### Screenshots or Videos

Failed Save
![image](https://user-images.githubusercontent.com/5486332/199960855-f8b72abf-3b6a-4623-8e3a-049a8ae811a6.png)

Not picking up the new Card Title
![chrome_qW1z4WpHvQ](https://user-images.githubusercontent.com/5486332/199960998-f95d623a-d256-4a90-9342-429269618707.png)

Tooltip showing the wrong Card Title used in the expression
![ApplicationFrameHost_f8VJzf5G0n](https://user-images.githubusercontent.com/5486332/199961095-edc0d49c-ecfe-4d58-a5c9-b6054e665a17.png)

After Save (removing the Body expression first)
![chrome_xofNk2MHTh](https://user-images.githubusercontent.com/5486332/199961169-4942db71-f153-46fa-855f-b7f2b9430678.png)

### Platform And Browser

- OS: Windows 11 21H2 22000.1098
- Browser: Chrome 
- Version: Version 106.0.5249.121 (Official Build) (64-bit)

AB#16141083

**Comment by hartra344** [comment]
Thanks for trying the preview and providing a very thorough bug report. This is definitely something we want to prioritize getting fixed ASAP.
