### ISSUE TITLE
New designer don't support connections.json parameterization

### ISSUE THREAD

**Issue by wsilveiranz** [Azure/LogicAppsUX#1266]
### Describe the Bug

Parameterizing logic apps connections.json for Azure Connections, which is now supported in the current designer and runtime, is not supported in the new designer.

When the connections.json is parameterized (using @appsettings('value') or @{appsettings('value')} the designer is not able to load (actions that are dependent on the Azure connections don't load and show a spinning wheel on an empty card).

### Steps to Reproduce the Bug or Issue

Using the new designer:

1. Create a new logic app using an Azure Connection (sample provided).
2. Confirm that the Logic App can run as expected.
3. Parameterize the connections.json file as per the [following steps](https://aka.ms/lastandard/parameterization), saving the file
4. Open the new designer.
5. Designer loads but actions dependent on the parameterized connections don't load.

Notice that the logic app still runs as expected.

### Workflow JSON

```json
-- Logic apps definition

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose": {
                "inputs": "@guid()",
                "runAfter": {},
                "type": "Compose"
            },
            "Get_messages_(V2)": {
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "azurequeues"
                        }
                    },
                    "method": "get",
                    "path": "/v2/storageAccounts/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}/queues/@{encodeURIComponent('integrationduqueue')}/messages"
                },
                "runAfter": {
                    "Compose": [
                        "Succeeded"
                    ]
                },
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_there_are_messages_in_a_queue_(V2)": {
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "azurequeues"
                        }
                    },
                    "method": "get",
                    "path": "/v2/storageAccounts/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}/queues/@{encodeURIComponent('integrationduqueue')}/message_trigger"
                },
                "recurrence": {
                    "frequency": "Second",
                    "interval": 15
                },
                "splitOn": "@triggerBody()?['QueueMessagesList']?['QueueMessage']",
                "type": "ApiConnection"
            }
        }
    },
    "kind": "Stateful"
}

-- Connections.json

{
    "managedApiConnections": {
        "azurequeues": {
            "api": {
                "id": "/subscriptions/@appsetting('WORKFLOWS_SUBSCRIPTION_ID')/providers/Microsoft.Web/locations/@appsetting('WORKFLOWS_LOCATION_NAME')/managedApis/azurequeues"
            },
            "authentication": "@parameters('azurequeues-Auth')",
            "connection": {
                "id": "/subscriptions/@appsetting('WORKFLOWS_SUBSCRIPTION_ID')/resourceGroups/@appsetting('WORKFLOWS_RESOURCE_GROUP_NAME')/providers/Microsoft.Web/connections/azurequeues"
            },
            "connectionRuntimeUrl": "@parameters('azurequeues-RuntimeUrl')"
        }
    },
    "serviceProviderConnections": {}
}
```

### Expected behavior

As a user, I am expected to edit a logic app in the visual designer, after I parameterize my connections.json file.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/13143907/200405362-67c9a2e5-79fb-4693-8160-451b2b127f9a.png)

### Platform And Browser

- OS: [Windows]
- Browser: [Edge]
- Version: [Version 107.0.1418.35 (Official build) (64-bit)]

### Additional context

Error found on Dev Tools console:

9:09:51 AM operation deserializer Unable to initialize operation details for swagger based operation - When_there_are_messages_in_a_queue_(V2). Error details - [object Object] 

AB#16174079

**Comment by hartra344** [comment]
This should be fixed with Carlos's internal PR here: https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/7095412
