### ISSUE TITLE
Inline Javascript Actions not Saved

### ISSUE THREAD

**Issue by mikeholdorf** [Azure/LogicAppsUX#1277]
### Describe the Bug

I created a new workflow with an HTTP Request Trigger and then a Compose Shape.  I added an Inline Code Action after the Compose.  When you select the Execute JavaScript, it allows you to specify Actions that can be included within the JavaScript.  I added the Compose, but the Action Items are never saved. They are missing and do not appear in the Designer or in the Code.  

I reviewed an existing workflow and it has the Action saved in the Code, but the new Designer does not include the Actions Item.

### Steps to Reproduce the Bug or Issue

1. Create a new Workflow
2. Add an HTTP Request Trigger
3. Add a Compose Shape and select the HTTP Body as input
4. Add and Inline Code Shape
5. Select Execute Javascript and then specify or enter an Action Item
6. Select another shape, such as Compose
7. Return to the Inline code and the Action Item has disappeared
8. Saving the workflow does not save the Action Item either

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose": {
                "inputs": "@triggerBody()",
                "runAfter": {},
                "type": "Compose"
            },
            "Execute_JavaScript_Code": {
                "inputs": {
                    "code": "return 0;"
                },
                "runAfter": {
                    "Compose": [
                        "SUCCEEDED"
                    ]
                },
                "type": "JavaScriptCode"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Expected behavior

As a user, I expected the Actions Item to be saved in the Execute Javascript Code Action when I selected another Action in the Designer

### Platform And Browser

- OS: macOS
- Browser: Microsoft Edge
- Version: 107.0.1418.28

AB#16189545

**Comment by mikeholdorf** [comment]
One additional note.  I have an existing Inline Code from the regular Designer.  When I bring it up in the new designer, it shows a bunch of boxes and when you hover, it states:  The character U+00a0 is invisible.  Code view is fine, but on the Parameters tab it shows this quite a bit.
<img width="619" alt="Screen Shot 2022-11-08 at 4 00 29 PM" src="https://user-images.githubusercontent.com/53225288/200685023-eec59b75-b593-4e4d-b392-5ce30e9de6e8.png">

**Comment by Eric-B-Wu** [comment]
This is happening because our Array Editor integration is still a work-in-progress. On the bright side, this will be fixed in my next PR with the support of Complex Object Array Items
