### ISSUE TITLE
Warn Users of Unsaved changes on New Workflows

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1286]
### Describe the Bug

We don't have the Modal to warn users of unsaved changes on new workflows when leaving a new workflow.

### Steps to Reproduce the Bug or Issue

1. Create a new workflow
2. Goto newly created workflow
3. Make some changes (ex. Add an HTTP trigger)
4. Leave the designer (ex. Click on Code) 
5. Will automatically bring us to the code of our empty workflow (without giving us a warning of leaving)

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateless"
}
```

### Expected behavior

As a user, leaving a newly created/ changed workflow, we'd still want some sort of warning that we don't lose our changes without saving.

### Screenshots or Videos

![empty_workflow](https://user-images.githubusercontent.com/95886809/200868810-24b6760b-236f-4b83-8173-6704a4d3802f.gif)

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

AB#16201111

**Comment by rickixie** [comment]
We made one for data mapper (used v8 dialog but @NicL9923 recently updated to v9), maybe something to consider reusing. 
https://purple-pebble-0e11de71e.1.azurestaticapps.net/?path=/story/data-mapper-components-modal-warning--standard

**Comment by hartra344** [comment]
Fix in: https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/7814788
