### ISSUE TITLE
Labels not visible in dark theme

### ISSUE THREAD

**Issue by vivek-bsn** [Azure/LogicAppsUX#1297]
### Describe the Bug

In the preview designer mode of the logic apps, we are not able to see the labels when using the dark theme of azure portal. 

### Steps to Reproduce the Bug or Issue

1. Switch to the dark theme in the Azure portal
2. Go to Designer of the logic app in preview mode
3. Start by creating a trigger
![image](https://user-images.githubusercontent.com/79462763/201416231-18cb7c5d-439e-4d64-ac41-bc5dfffb7cc1.png)

### Expected behavior

As a user, I should be able to view the labels clearly in all the themes.

### Platform And Browser

- OS: Windows
- Browser: Edge
- Version: 107.0.1418.42 (Official build) (64-bit)

**Comment by hartra344** [comment]
Hey @vivek-bsn, this was a miss on our part on the first release. We've have fixed it in #1239 which should be included in our next release in about a week.
