### ISSUE TITLE
MQ Connector unable to configure settings

### ISSUE THREAD

**Issue by mikeholdorf** [Azure/LogicAppsUX#1300]
### Describe the Bug

I am using the MQ Connector and am using When message is available in a queue.  I can configure the connection and then enter the Queue name and Wait interval.  I am unable to configure anything else.  It has How often do you want to check for items?  Clicking on this does nothing.  If you go to the Code View, you can see it is configured for every 3 minutes.  

In the Generally Available Designer, you can configure the time and the duration (minutes/seconds).

### Steps to Reproduce the Bug or Issue

1. Create a new Workflow
2. Search for mq
3. Select When messaging is available in a queue
4. Enter the connection information
5. Enter a Queue name
6. Select How often do you want to check for items?

### Expected behavior

As a user, I expected to have the ability to enter the time and duration from the designer rather than going to code view and making the modification

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by hartra344** [comment]
@Eric-B-Wu can you take a look? Might be a bad editor integration?

**Comment by Eric-B-Wu** [comment]
Talked with @preetriti1, should be fixed in one of her earlier PRs that hasn't made it to release - once she verifies we can close

**Comment by preetriti1** [comment]
The fix for this one should make it to production in 2 weeks
