### ISSUE TITLE
Doesn't prompt to save

### ISSUE THREAD

**Issue by chriswatsonaus** [Azure/LogicAppsUX#1312]
### Describe the Bug

Trialing the new workflow designer. I changed something in my workflow and accidentally hit the close X at the top-right. The designer closed and returned me to the workflows list. I wasn't warned or asked to save changes before closing. Re-opened the workflow and the changes were not there.

### Steps to Reproduce the Bug or Issue

1. Open a workflow
2. Click "Try the preview designer"
3. Select an action and make a change
4. Click close X button on top-right of the designer screen
5. Workflow designer closes without saving changes

### Expected behavior

As a user I expected the designer to prompt me to save the workflow before closing. Instead it closed without saving or prompting.

### Platform And Browser

- OS: Windows 10
- Browser: Chrome
- Version: 107.0.5304.106

**Comment by hartra344** [comment]
Hey, thanks for reporting. This is a know issue here: #1286 

Going to just close this one to track there.
