### ISSUE TITLE
No default parameters are showing up in card for request trigger

### ISSUE THREAD

**Issue by preetriti1** [Azure/LogicAppsUX#1320]
### Describe the Bug

On adding request trigger, the parameters tab just shows the "add new parameters" dropdown, even though there are non required and important visibility parameters
![image](https://user-images.githubusercontent.com/48265693/202319909-c7d3031e-b3a6-41be-8478-6ee0b4480161.png)

### Steps to Reproduce the Bug or Issue

1. Add new workflow.
2. Add request trigger.

### Expected behavior

We should see http post url and schema parameters as default and only method and relative path parameters in the dropdown

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Eric-B-Wu** [comment]
![smallbug_multiple_optional_params](https://user-images.githubusercontent.com/95886809/202521751-75f3be75-f60f-436a-852e-298edd1ace0f.gif)

also wanted to add another bug that I noticed where when deselecting a selected optional param, it would just add the already selected param to the list
