### ISSUE TITLE
Old designer and new Designer code is not in sync

### ISSUE THREAD

**Issue by GOURAVBISWAS** [Azure/LogicAppsUX#1350]
### Describe the Bug

After deploying using Azure Devops old designer and new designer code view is not in sync. Also in designer code view if we change anything that is not reflecting in the flow.

### Steps to Reproduce the Bug or Issue

1. go to code view of new designer
2. change any thing in json
3. try new transaction

### Expected behavior

As a user I expected after the changes in code view of new designer should reflect in workflow

### Platform And Browser

- OS:  Windows
- Browser: Chrome
- Version: 107.0.5304

AB#16410875

**Comment by hartra344** [comment]
Hey @GOURAVBISWAS , this is working as intended. The code view you open in the side panel is meant to be a snapshot of the workflow at that point. Keeping them in sync would take a ton of resources in any sizable workflow. I do think we can do more to communicate this though, code view for instance should probably be read only.
