### ISSUE TITLE
Logic app designer not in language of browser setting or account

### ISSUE THREAD

**Issue by Depechie** [Azure/LogicAppsUX#1352]
### Describe the Bug

Whe selecting a building block, you see a properties window to fill out needed configuration values.
For the Teams block, post a message, the values I can select are in French.
Although my browser is set to English and my own azure account is linked to Dutch.

### Plan Type

Pay as you go

### Steps to Reproduce the Bug or Issue

Add a logic app
Add a building block to post to teams

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/351693/203255429-ad37e1fa-6dac-475a-849f-307caaf2afce.png)

AB#16356872

AB#16414264

**Comment by hartra344** [comment]
@Depechie Just trying to figure out for sure what is happening here: It looks like everything is translated to english(I'm assuming this is correct functionality?) except the items in the Teams dropdown which are French but should also be English?

**Comment by Depechie** [comment]
@hartra344 yes! That is the correct assessment.

**Comment by hartra344** [comment]
@Depechie looks like the teams connector has a messed up localization cache, I'm able to repro through the API. I'm reaching out to someone over on that team to fix the issue and will let you know when I know anything more.
