### ISSUE TITLE
Not Showing Initialized Variables in Existing Workflows

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1412]
### Describe the Bug

When Viewing an existing workflow, I can see that we initialize variables but, when setting it later on with the "Set Variable" Action, the list of variable names does not appear in the dropdown. Similarily, I'm not seeing the variables within the token picker

### Steps to Reproduce the Bug or Issue

1. Goto https://ms.portal.azure.com/?clientOptimizations=false#view/Microsoft_Azure_EMA/WorkflowMenuBlade/~/designer/resourceId/%2Fsubscriptions%2F80d4fe69-c95b-4dd2-a938-9250f1c8ab03%2FresourceGroups%2FCSS-ISE-TEST%2Fproviders%2FMicrosoft.Web%2Fsites%2Fdetectorplaceholder%2Fworkflows%2FmobarqawDesigerTest/location/West%20US/isReadOnly~/false
2. Scroll down to a Set Variable Action
3. Under the name we have an Empty Dropdown even though we should be seeing the list of initialized Varaibles

### Expected behavior

We should be able to see the list of variables

### Screenshots or Videos

![missingSetVar](https://user-images.githubusercontent.com/95886809/206564131-b21db76b-08b6-4be8-af5b-4a6c36b2afbc.gif)

### Platform And Browser

- OS: Windows
- Browser: Edge

AB#16561793

**Comment by preetriti1** [comment]
This seems to be an issue with both IF and Switch cards where variables are not available for any actions in them. Looking at this and working on a fix.
