### ISSUE TITLE
"pathParameters" not displaying the query string parameter when a http requests receive

### ISSUE THREAD

**Issue by ni3net** [Azure/LogicAppsUX#1420]
### Describe the Bug

I have configured a workflow with a simple HTTP request and response with a query string parameter in app-logic.
When I run the app it is not receiving the query string parameter in the response action.
But when I update the "pathParameters" to "relativePathParameters" in the workflow JSON then it starts working.

### Steps to Reproduce the Bug or Issue

1. Create an app logic workflow
2. Add HTTP request "When an HTTP request is received" with method GET and relative param - "/{username}"
3. Add action HTTP response and add the text in the body "Hi [select the relative param from suggestion]"
4. Save the operation
5. Copy the HTTP URL and hit the browser with the query string param value
https://ni3rest.azurewebsites.net/api/ni3restapi/triggers/When_a_HTTP_request_is_received/invoke/Adam?api-version=2022-05-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=JUFm8qSznH53eDwNRvLAD2uZESGwIbajd2uJ8inGf2w
6. result - Hi 

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "inputs": {
                    "body": "Hi @{triggerOutputs()?['pathParameters']?['username']}",
                    "statusCode": 200
                },
                "kind": "Http",
                "runAfter": {},
                "type": "Response"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "inputs": {
                    "method": "GET",
                    "relativePath": "/{username}"
                },
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Expected behavior

Query string parameter should receive

### Screenshots or Videos

![request](https://user-images.githubusercontent.com/4230839/207001809-7d30a596-2489-4573-be28-f0a6c2a5d979.PNG)
![respose](https://user-images.githubusercontent.com/4230839/207001824-52b67031-2723-48a2-8147-32b37ddd9d2c.PNG)

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

AB#16580616

**Comment by hartra344** [comment]
@ni3net thanks for the bug report and helping test out our preview designer. I think I've found what's causing it and will have a PR to patch it up shortly.
