### ISSUE TITLE
Outdated Designer

### ISSUE THREAD

**Issue by dmpratt** [Azure/LogicAppsUX#1445]
### Describe the Bug

After saving and then running to test changes I made in the designer I returned to an outdated, old version of the workflow. The test was successful and did reflect the changes I made. I returned to the designer several times and finally hit my browser's refresh button to fix the problem.

### Steps to Reproduce the Bug or Issue

Open workflow in the new preview designer.
Make changes.
Save.
Run the trigger manually.
See that changes were executed.
Return to designer to see old version of the workflow.

### Expected behavior

As a user I expect when I return to the workflow designer to see the current, saved version of my workflow.

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

AB#16672378

**Comment by hartra344** [comment]
@dmpratt thanks for the report, I'm looking into this

**Comment by hartra344** [comment]
@dmpratt This is due to an overaggressive caching, made a fix that will be available in our next deployment. In the meantime it should be fine to hit refresh in this case.
