### ISSUE TITLE
Connection parameters missing during connection creation

### ISSUE THREAD

**Issue by anandgmenon** [Azure/LogicAppsUX#1489]
### Describe the Bug

When a new connection creation is attempted for any built-in connector, the connection aprameters seems to be missing and hence the `Create new` button is disabled
![Screenshot 2023-01-10 124239](https://user-images.githubusercontent.com/16523769/211485385-da2e7398-f2a4-4e39-9119-95df9653a2a2.png)

### Steps to Reproduce the Bug or Issue

1. Open designer. Select any Built-in connector
2. Create a new connection
3. In all the cases, some of the connection parameters seems to be misisng

### Expected behavior

Similar to the preview designer 
![Screenshot 2023-01-10 124645](https://user-images.githubusercontent.com/16523769/211486194-abbf6516-6f14-44b2-876f-b043d9d6b2ea.png)

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

AB#16752348

**Comment by rllyy97** [comment]
Thank you for reporting this bug @anandgmenon!  This is a big issue, we'll work on getting this fixed as soon as we can

**Comment by rllyy97** [comment]
It looks like this is an old bug that was already fixed, we will be deploying next week so it should be fixed in production soon!
