### ISSUE TITLE
"Sign In" option not available in Sharepoint action 

### ISSUE THREAD

**Issue by msplmansit98** [Azure/LogicAppsUX#1510]
### Describe the Bug

The button for sharepoint connection is freezed.

### Steps to Reproduce the Bug or Issue

1. Click the "+" icon in designer
2. "Add an action" and choose anything from sharepoint
3. It will ask you to create connection.

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Get_file_content": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": null
            }
          },
          "method": "get",
          "path": "/datasets/@{encodeURIComponent(encodeURIComponent(''))}/files/@{encodeURIComponent('')}/content",
          "queries": {
            "inferContentType": true
          }
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Expected behavior

It should be able to sign in.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/43098201/212763533-dcb1547a-ac34-4e6c-979b-20131acc9ae6.png)

### Platform And Browser

- Windows
- Chrome

AB#16808730

**Comment by rllyy97** [comment]
Thanks for the issue report @msplmansit98!  This is related to some other bugs/feature work we had recently, and was fixed in [this PR](https://github.com/Azure/LogicAppsUX/pull/1465), the changes should be public sometime soon

**Comment by msplmansit98** [comment]
Thanks
