### ISSUE TITLE
Outlook Trigger does not load in new designer view

### ISSUE THREAD

**Issue by danielbraswell** [Azure/LogicAppsUX#1554]
### Describe the Bug

When attempting to load the outlook trigger in the designer it stops on the loading screen and never populates the trigger

### Steps to Reproduce the Bug or Issue

1. Make a blank workflow in Logic App Standard.
2. Type in "Outlook" and search for "When an email arrives" 
3. After selecting trigger the trigger will start trying to load but will be unable to. 

### Expected behavior

As a user, I expect the trigger to load like it does in default designer view. 

### Screenshots or Videos

![Outlook Issue](https://user-images.githubusercontent.com/122548468/214390919-1810f48f-c4a1-4add-872f-7060cd4f6525.png)

### Platform And Browser

- OS: Windows
- Browser: [Edge]
- Version:109.0.1518.61

AB#16878475

**Comment by Eric-B-Wu** [comment]
Hi @danielbraswell, thanks for creating this issue. And this one is a known issue that we have fixed. The deployment for this will come EOD today (1/25)
