### ISSUE TITLE
Strange Error message when creating a service bus connection on the new designer preview

### ISSUE THREAD

**Issue by DennesTorres** [Azure/LogicAppsUX#1571]
### Describe the Bug

The message doesn't explain the reason of the error, neither has any relation with the filled fields

### Steps to Reproduce the Bug or Issue

1) Create a stateless logic app
2) select the trigger for service bus queue with auto complete
3) Fill the fields correctly. Use authentication type Logic App Managed Identity
4) Fill the Managed Identity Id
5) Click on create connection

### Expected behavior

The connection should be created

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/19700918/215123256-64c1f2c8-5896-47c7-8d59-ec2475432277.png)

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

AB#16927552

**Comment by rllyy97** [comment]
Hi @DennesTorres, thank you for reporting this issue!
This is a known issue and the fix for it will be rolling out through the week of Feb. 6th.
In the meantime if you encounter any errors like this I would recommend creating your connections in the non-preview Designer.
