### ISSUE TITLE
Workflow resubmit workflow run doesn't pass the same headers as original workflow run.

### ISSUE THREAD

**Issue by joerob-msft** [Azure/LogicAppsUX#1574]
### Describe the Bug

I tried to resubmit a successful workflow run and noticed that the headers didn't pass through all following actions. Here, we are using "x-ms-client-keywords" to pass through some data to all the actions. 

### Steps to Reproduce the Bug or Issue

1. Create a logic app with a request trigger
2. POST request trigger and include x-ms-client-keywords header with value
3. After run completes, go to Overview > Run history > Run details
4. Click resubmit

NOTE that the x-ms-client-keywords header values are not present on the resubmitted run

### Expected behavior

User should have the ability to resubmit with existing header values of their choice OR provide header values on resubmit

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/43352673/215182683-7ac8fdd5-1bab-4be5-8bfc-332c2c5b0aa3.png)

![image](https://user-images.githubusercontent.com/43352673/215182647-865dd6f1-6d7d-4ce8-857c-4b46baa88da1.png)

### Platform And Browser

- OS: Windows
- Browser: Edge
- Version: 109.0.1518.69

AB#16929912

**Comment by hartra344** [comment]
@ccastrotrejo , here is a bug in current monitoring view that would be good to fix in the new monitoring view

**Comment by hartra344** [comment]
turns out resubmit is done as a simple ARM API call, the UX does not define the headers or body that is attached.
