### ISSUE TITLE
Disable or make it possible to disable local language in IDE in new designer

### ISSUE THREAD

**Issue by mikaelsand** [Azure/LogicAppsUX#1615]
### Describe the Bug

When opening the new designer (preview) I was greeted with this:

![image](https://user-images.githubusercontent.com/20858407/217239554-3c00302f-f9f7-4bcc-859b-6d29460d30a2.png)

Please, please, please do not localize things like an IDE. It just makes is so much harder to search for answers or provide help.
If you _must_ then make it possible to disable it ... easliy.

### Steps to Reproduce the Bug or Issue

1. Open the new designer

### Expected behavior

Not a localized IDE/Designer (I mean, who asked for it?)

### Platform And Browser

- OS: Windows
- Browser: Edge

AB#17044916

**Comment by Eric-B-Wu** [comment]
Hello @mikaelsand thanks for filing this issue, unfortunately, localization is something that we support in the new designer as specified in the [portal docs](https://github.com/Azure/portaldocs/blob/main/portal-sdk/generated/portalfx-localization.md)

However, you should be able to change the localization language as follows:
![change_language](https://user-images.githubusercontent.com/95886809/222167821-c2e093c1-3ba4-4b48-8ae8-23ee38c2f063.gif)

**Comment by Eric-B-Wu** [comment]
reopening issue for investigation

**Comment by preetriti1** [comment]
@mikaelsand - The fix for this issue is in our current release, it should make it to all regions by 06/09 EOD. Please reopen it if you still face this issue after that.
