### ISSUE TITLE
Missing `file input` parameter type

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#1622]
### Describe the Bug

Actions with file input parameters are not rendered correctly

### Steps to Reproduce the Bug or Issue

1. In GA Designer, create a SFTP `Get file content` action
2. Input valid parameters, save
3. Change to Preview Designer and open the SFTP action
4. The `file` parameter will not be rendered properly

### Expected behavior

The file input field should show the correct file path.

#### Expected
![image](https://user-images.githubusercontent.com/25409734/217652787-29c4cf4c-9fa0-40b5-ab0f-09fe39830e22.png)
---
#### Current
![image](https://user-images.githubusercontent.com/25409734/217652797-2b644841-686a-4cfc-a8ef-3b0d1134cc35.png)

### Platform And Browser

- OS: Windows
- Browser: Chrome, Edge

AB#17078835

**Comment by Eric-B-Wu** [comment]
yep this is just a missing feature, we never got the file picker editor in, for public preview, I can take this

**Comment by hartra344** [comment]
Also should work against the onedrive file picker

**Comment by Eric-B-Wu** [comment]
Finished in #2165
