### ISSUE TITLE
Switch statement - Case never resolves

### ISSUE THREAD

**Issue by dbarnhs** [Azure/LogicAppsUX#1656]
### Describe the Bug

Whenever I add a switch statement after adding the trigger the first case statement shows the spinning gif attempting to resolve the renaming of the said case. Even after renaming the Case the gif keeps apinning and  never actually resolves.

### Steps to Reproduce the Bug or Issue

1. Create a logic app and trigger (in my case the new dataverse 'When a row is modified ')
2. Add a switch statement then add a Case
3. Attempt to rename the first Case to something else.

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Initialize_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "statusValue",
                            "type": "string",
                            "value": "New"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {
            "triggerBody": "Status Value"
        },
        "triggers": {
            "When_a_row_is_modified": {
                "inputs": {
                    "body": {
                        "AttributeFilters": [
                            "Status Value"
                        ],
                        "NotificationUrl": "@{listCallbackUrl()}"
                    },
                    "host": {
                        "connection": {
                            "referenceName": "commondataservice"
                        }
                    },
                    "path": "/datasets/@{encodeURIComponent(encodeURIComponent('https://nhsuk-moderation-dev.crm11.dynamics.com'))}/tables/@{encodeURIComponent(encodeURIComponent('incidents'))}/onupdateditemswebhook",
                    "queries": {
                        "scope": "Organization"
                    }
                },
                "outputs": {
                    "triggerbody": "Status Value"
                },
                "type": "ApiConnectionWebhook"
            }
        }
    },
    "kind": "Stateful"
}
```

### Expected behavior

I expect to see the rename resolve and stop the gif spinning so the Logic app can be saved.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/32927610/219621389-3a8c6bb0-d70b-4adb-893d-3edebc50296f.png)

### Platform And Browser

- OS: Windows
- Browser: Edge
- Version: Version 110.0.1587.46 (Official build) (64-bit)

AB#17223718

**Comment by dbarnhs** [comment]
Decide to upload another image with the variable set as this may have been misleading
![image](https://user-images.githubusercontent.com/32927610/219622383-991967bb-1890-4814-bb7d-7ec7251bd036.png)

**Comment by Eric-B-Wu** [comment]
Hi @dbarnhs, thanks for reporting this issue. It does indeed seem like our case icon is not properly being set - will update this in an upcoming release
