### ISSUE TITLE
item()?['status'] goes  missing in the publish logic app workflow - filter array action

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#1711]
### Describe the Bug

item()?['status'] goes  missing in the published logic app workflow - filter array action

![Screenshot_1](https://user-images.githubusercontent.com/40304643/223214702-08203467-d490-471d-acaf-f029756e818c.png)

### Steps to Reproduce the Bug or Issue

1. Create a Scope in VSCode Logic app workflow
2. Add a Filter Array action to filter Scope failures
3. publish the workflow to Azure 
4. open the workflow on the Portal

### Expected behavior

What I see on my VSCode designer should be visible on the Portal as well

### Platform And Browser

- OS: Windows
- Browser: Edge

AB#17441316

**Comment by hartra344** [comment]
@Eric-B-Wu can you take a look at this one?

**Comment by hartra344** [comment]
Should be fixed in the next version of the VS Code extension
