### ISSUE TITLE
About Tab Description Is displaying Connector Info Instead of Operation Info

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1716]
### Describe the Bug

Displaying wrong description in the About Tab

### Steps to Reproduce the Bug or Issue

All About Tab Descriptions Has the wrong description

### Expected behavior

Expected that we show the Operation Info instead of Connector Info

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

AB#17455786

**Comment by hartra344** [comment]
Is this still happening? I'm not able to repro this.

**Comment by hartra344** [comment]
Ah, it's only happening in portal...
