### ISSUE TITLE
Designer Crashing When Backend Requests Fail

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1742]
### Describe the Bug

New Designer seems to be crashing for customer:

https://portal.microsofticm.com/imp/v3/incidents/details/373898963/home

### Steps to Reproduce the Bug or Issue

See ICM

### Expected behavior

We can fail to load the connector, but avoid crashing the designer

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

AB#17504774

**Comment by rllyy97** [comment]
I'm reducing the severity of this issue.  Reading through the ICM does not explain what request is exactly is failing from the backend, and the original issue was due to a firewall problem for the user.

**Comment by hartra344** [comment]
I'm actually closing this. Firewall issue could have caused even the base neccessity apis to fail and designer may not have ever been opened fully int eh first place. without at least console logs there isn't much we can tell there.
