### ISSUE TITLE
Workflow Errors not displaying Error Notification on save

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#1745]
### Describe the Bug

When you save with invalid workflow / action settings or parameters, the workflow is not saved (working properly), but there is no Azure notification given as feedback currently.  Errors are thrown from within designer but nothing is shown on the Portal side of things.

### Steps to Reproduce the Bug or Issue

1. Make / open a workflow
2. Give an action invalid parameters
3. Try to save
4. It won't save, but it doesn't say anything in response

### Expected behavior

When you try to save with an invalid workflow, prevent the save but also say what's happening.
Give an error notification saying the save failed and why / where.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/25409734/224838327-20d7fefb-a955-4e86-bf61-90cef41a7a8d.png)

### Platform And Browser

- OS: Windows
- Browser: Chrome / Edge

AB#17530776

**Comment by ccastrotrejo** [comment]
Issue was solved with this [PR](https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/7849432). Save button is disabled when connectors have errors in parameters
<img width="1683" alt="Screenshot 2023-04-27 at 10 38 55 AM" src="https://user-images.githubusercontent.com/102700317/234959749-0decf8b2-1bb4-4429-8afa-08a57f2267ed.png">
