### ISSUE TITLE
Outlook connector

### ISSUE THREAD

**Issue by git-pranayshah** [Azure/LogicAppsUX#1746]
### Describe the Bug

Outlook connector always give Not Found error. Tried to sign in and create connection. However, every time after successfully sign in it says "Not Found"

### Steps to Reproduce the Bug or Issue

1. Drag Outlook V2 or V2 Connector
2. Click on sign in 
3. Enter credentials with successful sign in
4. It will say Not Found on pop up

### Expected behavior

It should create a successful connector

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Browser: Edge

AB#17532146

**Comment by rllyy97** [comment]
This has been fixed and we will be hotfixing our releases with this change later today
