### ISSUE TITLE
Difficult to understand the text

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/LogicAppsUX#1748]
### Describe the Bug

Part of the text in the preview designer is in Swedish with terrible translation. I have to think hard what is meant. 

Much better to have it all in English. Or an option to select language.

### Steps to Reproduce the Bug or Issue

Use the preview designer

### Expected behavior

Expected English or at least understandable Swedish text.

### Platform And Browser

- OS Windows 11- OS: [e.g. macOS, Windows, Linux]
- Browser: Edge

AB#17540530

**Comment by hartra344** [comment]
Sorry for the poor translation. I'll check with our localization team and give them the feedback. 

Other than that, we've heard feedback here #1615 that users would like to always have the designer expressed in english regardless of chosen portal language. I'll use that item to track adding something to do that.

**Comment by ErikMogensen** [comment]
Yes, I would very much like to have everything in English. It is common to use English as the team language and having the UI in the same language for everyone would help. Also, information received from the internet and presentations is almost exclusively in English even though I am Swedish.
