### ISSUE TITLE
Out of sync connection reference causes issues to logic apps saving/loading

### ISSUE THREAD

**Issue by AbodeSaafan** [Azure/LogicAppsUX#1750]
### Describe the Bug

The bug happens when the logic app workflow you have has a connection reference to a connection resource that was deleted. If this is the case, and you go into the workflow and try to change the connection and then save, it will appear fine but if you refresh the page, you will see that the action had not updated the connection and still has an error showing. The workaround is to go and delete the connection reference manually from the connections.json before deleting the action, and recreating it and adding a new connection. 

### Steps to Reproduce the Bug or Issue

1. create logic app standard with a managed api connection (sql for example)
2. save logic app and refresh designer to confirm it is fine
3. go to connections json and find the connection azure resource id
4. navigate to the connection resource and delete the connection
5. go back to logic app and load the workflow
6. you will notice that there is an error on the action that uses that connection
7. change the connection for that action and save the workflow
8. you should have a successful save, refresh the designer
9. you will see that the new connection is not being used and you still see the error 

### Workflow JSON

```json
N/A
```

### Expected behavior

Explained in scenario above

### Platform And Browser

- OS: Windows
- Browser: Chrome
- Version: Not sure but N/A

AB#17542099

**Comment by AbodeSaafan** [comment]
I believe this was happening on both designers @Eric-B-Wu

**Comment by rllyy97** [comment]
This has been fixed with Priti's recent error catching PR : #2254
