### ISSUE TITLE
Tokens sometimes do not have the correct display name

### ISSUE THREAD

**Issue by ek68794998** [Azure/LogicAppsUX#1764]
### Describe the Bug

Some actions, notably those using dictionaries, seem to display the key of a token rather than a human-readable display name.

![image](https://user-images.githubusercontent.com/1350074/225682558-2728bd5c-9d37-4050-baa7-a472f4487d43.png)

### Steps to Reproduce the Bug or Issue

1. Create a flow like so:
    <br/><br/>![image](https://user-images.githubusercontent.com/1350074/225682829-f3bae823-acd7-4b10-bf99-a09ebb0e9c07.png)
1. Add some tokens to the headers dictionary of the HTTP action, such as "Body" and "Queries" from the trigger.
    <br/><br/>![image](https://user-images.githubusercontent.com/1350074/225683035-550c7323-a428-4611-8830-55b7146b5e87.png)
1. Save the workflow and refresh the page. The tokens will no longer have a display name.
    <br/><br/>![image](https://user-images.githubusercontent.com/1350074/225683211-a0923b71-8aed-44ab-8707-22b6a49fc3c2.png)

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "HTTP": {
        "type": "Http",
        "inputs": {
          "uri": "@triggerOutputs()?['relativePathParameters']",
          "method": "GET",
          "headers": {
            "@{triggerBody()}": "@{triggerOutputs()?['queries']}"
          }
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Expected behavior

Even after save+refresh, the tokens should have a display name:

![image](https://user-images.githubusercontent.com/1350074/225683035-550c7323-a428-4611-8830-55b7146b5e87.png)

### Platform And Browser

- OS: Windows 11
- Browser: Edge
- Version: 111.0.1661.43

### Additional context

I believe this is where the fix would happen (`libs\designer\src\lib\ui\panel\panelTabs\parametersTab\index.tsx`):

![image](https://user-images.githubusercontent.com/1350074/225683771-71ab31d0-876b-4675-a492-929f7d5a3bbc.png)

AB#17571164

**Comment by Eric-B-Wu** [comment]
This one should be the same/similar issue to #1690
