### ISSUE TITLE
Settings Are Being Persisted Despite Clicking on a New Node

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1777]
### Describe the Bug

When Updating a setting in one node, instead of persisting for that specific node, it seems to be updating for all nodes

### Steps to Reproduce the Bug or Issue

1. Have 2 Actions with similar settings
2. Update settings of one node
3. Second Node Settings are being updated as well

### Expected behavior

We should expect all settings to be node-independent 

### Screenshots or Videos

![SettingsNotNodeIndependent](https://user-images.githubusercontent.com/95886809/226120958-2e82caa7-2487-4144-a5be-ad033f752372.gif)

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

AB#17596996

**Comment by Eric-B-Wu** [comment]
As far as I can tell this seems only to be a visual bug, when going into the code view immediately after clicking the second node, we see that the original settings are kept. We just need to make sure to rerender settings based on the node's original settings, alternatively we can switch over to the first tab when switching nodes, that way the settings are re-rendered when viewing

**Comment by hartra344** [comment]
Looks like the control isn't getting rerendered, might be some over eager memo caching
