### ISSUE TITLE
Replication Tasks and Peeklock : Failing below steps.

### ISSUE THREAD

**Issue by hartra344** [Azure/LogicAppsUX#1812]
### Describe the Bug

Prerequisites:
Create a service bus namespace with two queues.
Create an event hub instance with two hubs.

1. Create a new Stateless logic app in standard, open the designer.
2. Add a service bus "When messages are available in a queue (peek-lock)" trigger.
3. Expected: Add a For each action and select Messages from the dynamic content as its input parameter.
Actual: Not able to see the Messages from dynamic content .There is a change in view of this token in new preview designer.

4. Expected: Split on is in On state by default . Turn the Split on to off state and click on "Done"
Actual: 'Split on is in Off state by default

5. Expected: Within the for each loop add the action "Dead-letter the message/Abandon the message/Complete the message" from service bus. In the Message ID field select "Message ID" from the dynamic content popup. Only one foreach loop shoud be there.
Actual: After selecting the Message from dynamic content / Message ID field, 2 foreach loops are added automatically instead of 1.

6. Expected: Add a "When messages are available in a queue" trigger from service bus. Queues can be shown after connection is established.
Actual: Queues not shown after connection is established.

### Steps to Reproduce the Bug or Issue

above

### Expected behavior

above

### Screenshots or Videos

![Replication 3 General mode](https://user-images.githubusercontent.com/13208452/227832330-269feec6-fa22-4cad-a796-7b062c412733.png)
![Replication 3 ND](https://user-images.githubusercontent.com/13208452/227832334-c033507a-42c7-49a6-9b05-af83f9f285b9.png)
![Replication 2](https://user-images.githubusercontent.com/13208452/227832340-bda8fda3-84b8-4afc-a00f-54c56f0f874e.png)
![Replication 2 1 ND](https://user-images.githubusercontent.com/13208452/227832348-efdfe78a-b456-4abf-8302-90e0a47aaec1.png)
![Replication 1](https://user-images.githubusercontent.com/13208452/227832355-08cfa44d-6eb9-4001-a9a6-4eadd67d6ac5.png)

![Replication 2 General mode](https://user-images.githubusercontent.com/13208452/227832360-0579e5a1-9aa7-40e3-940d-29b07b0e53df.png)

### Platform And Browser

N/A

**Comment by vgouth** [comment]
All the above issues **not** repro in latest release. Closing this issue

**Environment Details:**
**URL:** https://aka.ms/emastaging-flowstip1
**Version:** 2.30508.1.2

Able to see messages from dynamic content.
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/bf65be89-4758-422f-badf-76553807ee61)

Spilt on is ON by default
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/01cd11da-6a2a-40cc-a885-84cb3636580a)

Only one for each loop is added after adding the "Dead-letter the message/Abandon the message/Complete the message" actions.
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/96887e08-07d5-43b0-a72b-6ddc0e8db510)

Queues also shown when the connection is established.
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/f8f24fcf-19e7-4e05-b88e-098596ce8883)
