### ISSUE TITLE
Decimal Types Not being respected (Sum Function)

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#1823]
### Describe the Bug 

When you have a decimal on left side, sum functions in the middle and decimal on destination you get a casting error

### Steps to Reproduce the Bug or Issue 

Decimal (Source) - Sum Function - Decimal (Destination

### Workflow JSON 

*No response*

### Expected behavior 

I expect to be able to map from function to destination

### Screenshots or Videos 

![image](<https://user-images.githubusercontent.com/83832436/228363847-3c1cb30e-08cb-4bac-9d20-9086821b69af.png>)

### Platform And Browser 

Windows/VS Code

### Additional context 

*No response*

**Comment by refortie** [comment]
A short term fix that we are adding in, is to move the type checking to be a warning instead of a error. We will be looking deeper at how we can improve our type checking especially on functions where we could hypothetically have multiple output types based on the inputs.
