### ISSUE TITLE
Map Integrity - Ordering (destination)

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#1827]
### Describe the Bug

When generating output, we need to ensure that the nodes appear in the order as we see in the designer.

### Steps to Reproduce the Bug or Issue

Have nodes represented in a different order in your source as your destination. Then execute the map. You will see the nodes represented in the way they are lined up in the Source

### Expected behavior

I expect the destination schema to drive the output of the nodes

### Screenshots or Videos

<img width="645" alt="image" src="https://user-images.githubusercontent.com/83832436/228371234-4bf7536f-d770-4547-bb60-cbeddb1c58f0.png">

### Platform And Browser

Windows/VS Code

### Additional context

See internal OneNote for more details

**Comment by refortie** [comment]
Still seems to persist, will be taking another look

**Comment by refortie** [comment]
Bigger issue. Properties are automatically sorted in javascript. Perhaps look into changing the MapDefinitionEntry into a dictionary?

**Comment by Elaina-Lee** [comment]
Confirmed with Reid that since JavaScript properties aren't sorted in any particular manner, brute force ordering in the serializer would be the only approach. Closing the issue.
