### ISSUE TITLE
HTML Editor

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1842]
### Describe the Bug

HTML editor

### Steps to Reproduce the Bug or Issue

todo

### Expected behavior

We should want an html editor (originally started, but had not been prioritized, so had but on the backlog)

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by hartra344** [comment]
What operation currently uses the HTML editor? I just looked through obvious ones and I couldn't find one...

**Comment by Eric-B-Wu** [comment]
I think the big ones are the send an email (v2) actions, example connector I follow is from Outlook.com. I have the UI half built out in another one of my branches but had put that work on hold, also serialization/deserialization of it is a little tricky because you have to keep the formatting of the editor state.
