### ISSUE TITLE
Monitoring view splitting string up and showing as an array

### ISSUE THREAD

**Issue by hartra344** [Azure/LogicAppsUX#1848]
### Describe the Bug with repro steps

1.Create a project and add stateful workflow in the VS Code.
2.Open the Designer, Add a trigger and a compose action.
3.Save it and debug it.
4.Run the workflow and open the monitoring view for your run from the overview page.
5.Verify the run details and action inputs and output

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/13208452/228619458-a820d1cd-abfa-4eb4-984e-203b0c8683ae.png)
![image](https://user-images.githubusercontent.com/13208452/228619481-cfc70a52-dc7b-4fbc-be71-56c793f64eff.png)

### Browser

VSCode

**Comment by ccastrotrejo** [comment]
Raw response from API call returns single string "abc" instead of a dictionary schema  { inputs: 'abc' }. This will be fixed once the proposal and implementation of the parsed inputs/outputs API
