### ISSUE TITLE
Folder picker connectors produce error [Parameter "undefined" cannot be found]

### ISSUE THREAD

**Issue by ek68794998** [Azure/LogicAppsUX#1853]
### Describe the Bug with repro steps

1. Open a workflow (any).
2. Add a new action.
3. Select "List files in folder" from OneDrive for Business.
4. Observe dropdown content.

I would expect a folder picker here, but instead an error appears.

### Workflow JSON

```json
N/A
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1350074/228645502-becb7605-56dc-4422-bc63-a837c70e8d35.png)

### Browser

Edge x64 111.0.1661.54, Windows 11.

**Comment by ek68794998** [comment]
Thanks for the reference. I searched "folder" and didn't find one.

**Comment by Eric-B-Wu** [comment]
Will have the undefined error fixed in: https://github.com/Azure/LogicAppsUX/pull/2020
however, still working on another PR to get the data for the picker. Use this for tracking:
https://github.com/Azure/LogicAppsUX/issues/1622
