### ISSUE TITLE
Validation failed when comma separated minutes are typed in 'At these minutes' param of Schedule Recurrence trigger

### ISSUE THREAD

**Issue by YOS0602** [Azure/LogicAppsUX#1859]
### Describe the Bug with repro steps

# bug detail

- Target: Schedule "Recurrence" Trigger
<img width="619" alt="image" src="https://user-images.githubusercontent.com/67084343/228823328-ed357986-2369-4051-8ebb-38cee2246dd2.png">

- when I type `0,15,30,45` into `At these minutes` parameter and click the save button, the notification says:

> Workflow saved successfully. Workflow validation failed for the workflow 'XXXXXXXX'. {"error":{"code":"InvalidTemplate","message":"The template validation failed: 'The template trigger 'recurrence' at line '1' and column '226' is not valid: \"Error converting value \"0,15,30,45\" to type 'System.Int32[]'. Path 'schedule.minutes'.\".'."}}

- but I type minutes in format of array like `[0,15,30,45]`, it will be validated correctly

# repro steps

- make a workflow
- set Schedule "Recurrence" Trigger
- add parameter `At these minutes`
- type comma separated minutes eg: `0,15,30,45`
- click the save button

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "recurrence": {
        "type": "Recurrence",
        "recurrence": {
          "frequency": "Week",
          "interval": 1,
          "timeZone": "Tokyo Standard Time",
          "schedule": {
            "hours": [
              "14",
              "15",
              "16"
            ],
            "minutes": "0,15,30,45",
            "weekDays": [
              "Sunday",
              "Saturday",
              "Friday",
              "Thursday",
              "Wednesday",
              "Tuesday",
              "Monday"
            ]
          }
        }
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Screenshots or Videos

<img src="https://user-images.githubusercontent.com/67084343/228843089-7d30f242-6964-4359-a9de-7e0e8687df10.png" width="600">

<img src="https://user-images.githubusercontent.com/67084343/228843516-dc457cd9-b99c-4b1d-a0a9-23d41535acb6.png" width="600">

### Browser

MacOS 13.1 M1
Chrome 111.0.5563.146（Official Build） （arm64）
Safari 16.2 (18614.3.7.1.5)

### Additional context

If this implementation is right and the docs are incorrect, I'll make a new issue for Logic App's documentation repo (https://github.com/Azure/logicapps)

docs: https://learn.microsoft.com/en-us/azure/logic-apps/tutorial-build-schedule-recurring-logic-app-workflow#add-the-recurrence-trigger

## workflow JSON in wrong format like `0,15,30,45`

```json
{
  "schedule": {
    "hours": ["14", "15", "16"],
    "minutes": "0,15,30,45",
    "weekDays": [
      "Sunday",
      "Saturday",
      "Friday",
      "Thursday",
      "Wednesday",
      "Tuesday",
      "Monday"
    ]
  }
}
```

## workflow JSON in correct format like `[0,15,30,45]`

```diff
{
  "schedule": {
    "hours": ["14", "15", "16"],
 -  "minutes": "0,15,30,45",
 +  "minutes": [0, 15, 30, 45],
    "weekDays": [
      "Sunday",
      "Saturday",
      "Friday",
      "Thursday",
      "Wednesday",
      "Tuesday",
      "Monday"
    ]
  }
}
```

**Comment by Eric-B-Wu** [comment]
Hello @YOS0602, thanks for reporting this issue! Currently looking into changing how we render the recurrence editor, and will include this change in my update
