### ISSUE TITLE
String token is not resolved when rendering upload complete notification sentence

### ISSUE THREAD

**Issue by daviburg** [Azure/LogicAppsUX#1886]
### Describe the Bug with repro steps

Navigate to standard SKU workflow app, under Artifacts select Maps and click + Add. Unload any map. The name given should render in the completion notification but the unreplaced placeholder token is shown instead:
<img width="389" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/12040431/229310444-ce0891d5-a5cf-439a-b6dd-ecd8b64f3d1a.png">

### Browser

Edge.

**Comment by hartra344** [comment]
Fixed by https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/7912873
