### ISSUE TITLE
Map upload size limit shows 2097152 bytes, likely should be 4 MB like assembly upload experience

### ISSUE THREAD

**Issue by daviburg** [Azure/LogicAppsUX#1887]
### Describe the Bug with repro steps

Newer (and cleaner) upload experience for assemblies shows a 4 MB limit:
<img width="276" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/12040431/229310617-50d44c8d-3fcc-4041-9ab2-e01f772c0be1.png">

But the older map upload experience shows a lower limit (likely the exacting count of bytes in 2 MB):
<img width="347" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/12040431/229310606-9b5c5976-d69e-40db-ae7c-e4a017f83c9d.png">

### Browser

Edge

**Comment by hartra344** [comment]
Fixed by https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/7912873
