### ISSUE TITLE
LogicApps Standard extension version 2.0.16 Designer issue and Naming convention 

### ISSUE THREAD

**Issue by amsullu** [Azure/LogicAppsUX#1889]
### Describe the Bug with repro steps

Create a new stateful workflow and select "Skip for Now" to skip the connectors from Azure. This means using only the Built-In connectors.
Once try to open the workflow in  Designer, it doesn't open and just stays blank. To fix this, the "Use connectors from Azure" option should be selected and the workflow should be reloaded
However, when the workflow is created with "Use connectors from Azure", the designer opens up.
Also, the naming standard for workflow is given error while using - on the name, but the error message says - and _ are allowed

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/129661524/229349153-06c4803b-2597-4d70-857d-68b80c777204.png)

### Browser

null

**Comment by ccastrotrejo** [comment]
Hi @amsullu thanks for raising this issue, as for today the latest version (v2.0.24) shouldn't have the first issue. Could you please update your extension version and see if this keeps happening? I will take a look at the second issue
