### ISSUE TITLE
Workflow Parameters not keeping parameter type

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1892]
### Describe the Bug with repro steps

1. Open Workflow Parameter Panel
2. Create a Workflow parameter
3. Give a name, set type to integer, set value to 123
4. Close panel
5. Reopen Panel, value of workflow panel is now "123"

### Browser

edge

**Comment by Eric-B-Wu** [comment]
https://msazure.visualstudio.com/One/_workitems/edit/17003088

**Comment by vgouth** [comment]
Issue repro in latest artifact.

1.	VS Code extension -    vscode-azurelogicapps-2.9.1.vsix
2.	NuGet package: https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyMDcxNTQ1L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.1.nupkg
3.	Extension Bundle (CDN URL): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting
4.	Extension Bundle (Direct Download): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.19.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.19.1_any-any.zip

**Comment by hartra344** [comment]
@ccastrotrejo can you take a look at this one?
