### ISSUE TITLE
Connection Creation Parameter Naming Convention is Different in Azure Automation Action

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1895]
### Describe the Bug with repro steps

1. Create an Azure Automation Create Job Action
2. In the Auth Type, there's 3 dropdown option of "Logic Apps Managed Identity" and "Service Principal Authentication" instead of the usual "Managed Identity"
3. There's a different Parameter option called "Logic Apps Managed Identity" which is now a required  parameter instead of the usual "Cloud Endpoint" Optional Parameter

### Screenshots or Videos

Actual
<img width="462" alt="azure automationActual" src="https://user-images.githubusercontent.com/95886809/229549391-dd1ddec6-1512-470a-8eb6-e4010b9cd6e6.PNG">
Expected
<img width="462" alt="azure automationActual" src="https://user-images.githubusercontent.com/95886809/229549536-4d71b0f8-d520-4255-867c-fad235db1832.PNG">

### Browser

edge

### Additional context

https://msazure.visualstudio.com/One/_workitems/edit/17436943

**Comment by preetriti1** [comment]
this should be fixed by #2149
