### ISSUE TITLE
HTTP Webhook Missing Token Picker

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1896]
### Describe the Bug with repro steps

1. Create HTTP webhook Trigger
2. Try to Enter a Parameter
3. Missing Token Picker with CallbackUrl

### Browser

Edge

**Comment by hartra344** [comment]
@eric-b-wu were you able to repro this? I'm not, webhook token picker seems to work on every field

**Comment by Eric-B-Wu** [comment]
Yeah I was able repro, this issue is happening because we filter out the token picker for triggers, but the HTTP webhook Trigger
actually has a token picker with a single token that being the callbackUrl

**Comment by Eric-B-Wu** [comment]
I can take this issue, as its related to the token picker
