### ISSUE TITLE
Setting Validation 

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1897]
### Describe the Bug with repro steps

1.Create a standard logic app
2.Create an empty stateless workflow
3.Add a request trigger and HTTP request action.
4.The request url to point to
(https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI)
5.Go to the settings tab and set Request options > request timeout to PT1S
6.In the settings tab disable "Asynchronous Pattern"
7. Save and run the workflow
Expected Result:  Open the workflow history. The HTTP request action should be marked as "Failed"
Actual Result :  The HTTP request action marked as "Success"
8. Expected Result:  Update request timeout to "PT24H".The workflow should show validation error "The provided request options timeout of '24:00:00' for action 'HTTP' must be less than '01:00:00'."
Actual Result :  The HTTP request action marked as "Success"

### Screenshots or Videos

Step 7
![image](https://user-images.githubusercontent.com/95886809/229561850-008623ec-e90a-4c21-bd6d-461915e1ecd1.png)
Step 8
![image](https://user-images.githubusercontent.com/95886809/229561972-5784688c-51e0-4392-9d05-9ff2dc1b6e83.png)

### Browser

Edge

**Comment by vgouth** [comment]
**Expected Result:**  Go to the settings tab and set Request options > request timeout to "InvalidString"
Actual Result :  The HTTP request action marked as "Success"

**Comment by preetriti1** [comment]
These issues cannot be reproed, also there are no designer client side validation errors that will show up for invalid values for timeouts, but while saving the working it will throw validation error and you can see them in the notification tab. In new designer we do not save until validation comes back positive.
So not an issue in new designer, and in old designer it does show there is validation error but unfortunately we save the workflow.json.
