### ISSUE TITLE
Some text illegible when using Azure dark theme

### ISSUE THREAD

**Issue by hamdrew** [Azure/LogicAppsUX#1900]
### Describe the Bug with repro steps

There are multiple places where I notice incompatibilities with the Azure dark theme. Here are some examples:

- Confirmation when deleting a step
- Configuration screen for the "Sends a message to the SQS queue" step

### Screenshots or Videos

![Screenshot 2023-04-03 at 12 14 20 PM](https://user-images.githubusercontent.com/4921666/229581038-4e9150d9-fbb1-41b9-9cdb-43ba259dd49b.png)

![Screenshot 2023-04-03 at 12 10 58 PM](https://user-images.githubusercontent.com/4921666/229581095-35f527c2-6890-4084-834e-3d716823cdee.png)

### Browser

Google Chrome Version 111.0.5563.146 (Official Build) (arm64)

**Comment by hartra344** [comment]
@rllyy97 did this fix not make it to production yet?

**Comment by Eric-B-Wu** [comment]
This was not part of the production hotfix, we're gonna be rolling it out in this weeks release

**Comment by hartra344** [comment]
@hamdrew this should be fixed with the release going out this week.
