### ISSUE TITLE
Run history randomly remains blank despite backend response

### ISSUE THREAD

**Issue by daviburg** [Azure/LogicAppsUX#1902]
### Describe the Bug with repro steps

Go to workflow overview, especially shortly after the app restarted. The run history remains blank. Taking a network trace and hitting refresh, we can see the backend has responded with some runs, but still the portal is not showing the run history.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/12040431/229594354-d7c19b16-6448-445b-b8bd-19e2e68296e2.png">

### Browser

Edge

### Additional context

Did not attach the network trace as it can contain sensitive security information.

**Comment by hartra344** [comment]
Internal PR here to completely rewrite this blade: https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/7923960?_a=files

Should really help with performance.

https://share.cleanshot.com/2RsxGgr7
