### ISSUE TITLE
Opening one workflow in the preview designer messed up all of the workflows in the Logic app

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/LogicAppsUX#1910]
### Describe the Bug with repro steps

1. I opened a simple workflow with one trigger and three actions and switched to the Preview designer. 
2. I didn't want to load properly so I switched back to the GA designer. 

Now the run history is gone and all of the workflows shows errors when opened in the designer.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/9644248/229844589-87fa558a-ee6c-4009-9ae8-fefe8daaf2f3.png)

### Browser

Edge

### Additional context

The other workflows were larger, between 10 - 30 actions each.

**Comment by hartra344** [comment]
Did you hit save while in preview designer? Just opening it shouldn't have been able to cause any problems outside of the designer itself. Can you send me an email with more information at travisharris@microsoft.com ? We're going to likely need a workflow definition in order to debug this.

**Comment by ErikMogensen** [comment]
We just discussed this and it was probably the GA designer that caused it. As far as I am concerned this may be closed.
