### ISSUE TITLE
Parameter for HTTP action's network timeout is called Request Options

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#1921]
### Describe the Bug with repro steps

1. Add action HTTP -> HTTP (in-app)
2. Go to Settings -> Network
3. Observe that "Request Options" example is a timeout, so implies the tool tip:

![image](https://user-images.githubusercontent.com/351644/229917539-739da807-92d2-432d-9e9c-d4a58d9bf9d8.png)

### Workflow JSON

```json
{
  "HTTP": {
        "type": "Http",
        "inputs": {
          "uri": "https://example.com/",
          "method": "GET",
          "body": "@outputs('Compose_Response')"
        },
        "runAfter": {
          "Compose_Response": [
            "Succeeded"
          ]
        },
        "trackedProperties": {}
      }
}
```

### Browser

Edge version 111.0.1661.54

AB#24256819

**Comment by preetriti1** [comment]
This was always present inside Request Options in old designer
![image](https://user-images.githubusercontent.com/48265693/235743420-5a4d8ce4-3218-4808-9af0-607fa59d2ae3.png)

the description content is moved inside the info bubble in new design.

**Comment by preetriti1** [comment]
@shahparth-lab - To give suggestions on this bug

**Comment by Eric-B-Wu** [comment]
Going to include this as part of the setting rewrite: https://github.com/Azure/LogicAppsUX/issues/2266
