### ISSUE TITLE
Save button not responding.

### ISSUE THREAD

**Issue by parasdesaicims** [Azure/LogicAppsUX#1927]
### Describe the Bug with repro steps

when I make chagnes to logic app the save button doesn't work - I have to move back to GA designer to make changes

### Browser

Edge

**Comment by rllyy97** [comment]
Hi @parasdesaicims, thank you for the report, could you give some more details on the issue you're experiencing so we can better look into this?

**Comment by hartra344** [comment]
This would likely be due to validation errors somewhere. This may be partially fixed in the designer update rolling out now, we should look into ways of upleveling errors even better though.
