### ISSUE TITLE
New designer issues with filter array action and execute sql stored procedure action

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#1932]
### Describe the Bug with repro steps

create two actions
1. execute SQL stored procedure which expects input parameters
2. filter array for scope failures and add item()['status']

"Unable to parse template language expression 'equals('item()?['status']','Failed')': expected token 'RightParenthesis' and actual 'Identifier'.".'', exception='Microsoft.Azure.Workflows.Templates.Exceptions.TemplateValidationException:

### Browser

edge
chrome

**Comment by preetriti1** [comment]
@mhireholi - Can you please specify what was the output you selected was that an array? there are no screenshots or the outputs info in your report and it is difficult to identify what is the issue.
Please include screenshots, definition snippets and expected values and also specify what outputs are you referring to in filter array action and what is missing there.

**Comment by Eric-B-Wu** [comment]
Closing because unable to repro, @mhireholi please reopen if this issue still happens/ once provided more information
