### ISSUE TITLE
VSCode 2.x Designer - Cursor almost invisible on dark themes when editing Action Values/Expressions

### ISSUE THREAD

**Issue by axiomitdavid** [Azure/LogicAppsUX#1939]
### Describe the Bug with repro steps

When using the default VSCode theme, which has a very dark background, the cursor in the Designer for editing action values/expressions is almost invisible.

Can you revert to the same colour/saturation settings as in V1.x ?

My old eyes can barely see the cursor and I really dislike a bright background.  Possibly against various accessibility guidelines as well for vision impaired.

See the attached screenshot.  Cursor is to the right of the D in TenantID

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/41350688/230542973-91ccb4b9-b5bb-4723-8566-16e6342b051b.png)

### Browser

-VS Code 
- Logic Apps Standard Extension 2.0.24

**Comment by hartra344** [comment]
I’ll make sure this gets fixed asap. You’re right this is an oversight on our accessibility standards. Thanks for the report.
