### ISSUE TITLE
conditional value removed when switching to preview designer

### ISSUE THREAD

**Issue by lmalgascg** [Azure/LogicAppsUX#1942]
### Describe the Bug with repro steps

1. Go to a workflow
2. 2. Click on 'designer'
3. Click on 'try preview designer'
4. Click on a condition action that validates true/false
5. Value on right after condition statement is missing
![image](https://user-images.githubusercontent.com/103117586/230566482-1e62d773-e12a-49bc-95e6-a9ad90e40001.png)

![image](https://user-images.githubusercontent.com/103117586/230566738-7f356d64-a41c-4779-90cb-1f70cc69af87.png)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/103117586/230566482-1e62d773-e12a-49bc-95e6-a9ad90e40001.png)

![image](https://user-images.githubusercontent.com/103117586/230566738-7f356d64-a41c-4779-90cb-1f70cc69af87.png)

### Browser

Chrome

**Comment by Eric-B-Wu** [comment]
Hi @lmalgascg thanks for reporting the issue, we've got this issue fixed in #1918, and will get this out in our next release
