### ISSUE TITLE
Outlook attachments should support complete name/bytes structure

### ISSUE THREAD

**Issue by mehaag** [Azure/LogicAppsUX#1948]
### Describe the Bug with repro steps

1. In GA designer, create a flow with the 'Send an email (V2)' action
2. Add the Attachments parameter and input random text into the Name and Content fields.
3. Save the flow
4. Open the same flow in the new designer
5. The attachments show as an invalid parameter ('Please enter a valid array')
6. If you delete that parameter and try to add attachments from the v3 designer, you can only add individual strings

### Screenshots or Videos

Old designer - can save this flow:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/29241410/230676849-8a335293-5073-4323-bf76-e62ba6144504.png">

Open same flow in new designer. Flow loads but shows attachments are invalid:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/29241410/230677124-6d961520-3319-4d22-82b6-80d7fc82093b.png">

If you delete that parameter and try to add attachments from the v3 designer, you can only add individual strings:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/29241410/230677576-beaab68b-9ac5-495f-b643-8cde55294fbf.png">

### Browser

Tested in Chrome

**Comment by hartra344** [comment]
@Eric-B-Wu

**Comment by hartra344** [comment]
tracked-by:"Azure/LogicAppsUX#1996"

**Comment by hartra344** [comment]
Closing since it's tracked by a more generic issue
