### ISSUE TITLE
Logic App Consumption cannot be saved after selecting and API Connection deployed from ARM and used in Data Factory action

### ISSUE THREAD

**Issue by jaimesampedrom** [Azure/LogicAppsUX#1953]
### Describe the Bug with repro steps

-	I deployed API connection for Data factory with Manage identity with ARM template. 
-	Logic App detected the API connection when adding and ADF Action. 
-	It looked that the LA was saved as successful as saved workflow appeared:
![image](https://user-images.githubusercontent.com/130341809/230840108-26b671a9-c85e-4f7f-aba5-5c3a335f3d0b.png)
- when I try to change the tab from designer to another tab like "Overview", I get a Pop-up indicating that 
"Your unsaved edits will be discarded". And when clicking ok I lose the ADF action chance. Not sure why this pop-up appears as in the previous message it said that the workflow was saved successfully.
![image](https://user-images.githubusercontent.com/130341809/230840381-2ca2764c-40af-4788-8bf8-35e6fd2c7eb4.png)

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Get_a_pipeline_run": {
                "inputs": {
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['undefined']['connectionId']"
                        }
                    },
                    "method": "get",
                    "path": "/subscriptions/@{encodeURIComponent('13ace21b-1131-4aa5-b99e-0423cd54955a')}/resourcegroups/@{encodeURIComponent('casesApril23')}/providers/Microsoft.DataFactory/factories/@{encodeURIComponent('datafactorytestjsm')}/pipelineRuns/@{encodeURIComponent('fbb82273-5195-44a8-9d51-4431f5354f97')}",
                    "queries": {
                        "x-ms-api-version": "2017-09-01-preview"
                    }
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {
            "Recurrence": {
                "evaluatedRecurrence": {
                    "frequency": "Minute",
                    "interval": 3
                },
                "recurrence": {
                    "frequency": "Minute",
                    "interval": 3
                },
                "type": "Recurrence"
            }
        }
    },
    "parameters": {}
}
```

### Browser

Microsoft Edge

### Additional context

ADF API Connection Json definition used:

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {       
        "logicAppApiVersion": {
            "defaultValue": "2018-03-01-preview",
            "type": "String",
            "metadata": {
                "description": "Name of the Logic App."
            }
        },
        "location": {
            "allowedValues": [
                "[resourceGroup().location]",
                "northeurope",
                "westeurope"
            ],
            "defaultValue": "westeurope",
            "type": "String",
            "metadata": {
                "description": "Location of the Logic App."
            }
        },
        "logicAppADFConnectionName": {
            "type": "String",
            "metadata": {
                "description": "The ADF API connection resource name"
            }
        },
        "logicAppADFConnectionDispalyName": {
            "type": "String",            
            "metadata": {
                "description": "The ADF API connection resource name"
            }
        },
        "deployLogicAppADFConnection": {
            "defaultValue": true,
            "type": "Bool",
            "metadata": {
                "description": "The switch to create ADF connection."
            }
        }
    },
    "variables": {        
    },
    "resources": [
         {
            "type": "Microsoft.Web/connections",
            "apiVersion": "[parameters('logicAppApiVersion')]",
            "name": "[parameters('logicAppADFConnectionName')]",
            "location": "[parameters('location')]",
            "properties": {
                "displayName": "[parameters('logicAppADFConnectionDispalyName')]",
                "parameterValueType": "Alternative",
                "customParameterValues": {},
                "api": {
                    "id": "[concat('subscriptions/', subscription().subscriptionId, '/providers/Microsoft.Web/locations/', parameters('location'), '/managedApis/azuredatafactory')]"
                }
            },
            "condition": "[parameters('deployLogicAppADFConnection')]"
        }
    ]
}

**Comment by rllyy97** [comment]
Hi @jaimesampedrom, I see from your screenshot you're using our new preview designer, do you still experience this issue if you switch back to the generally available designer?

**Comment by rllyy97** [comment]
This issue has been fixed and will be rolling out with our next release between May 29th and June 2nd
