### ISSUE TITLE
Support Inline XSLT Extensibility

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#1961]
### Describe the Bug with repro steps

Would like the ability to surface inline XSLT extensibility that allows customers to implement custom logic.

### Browser

VS Code/Windows

### Additional context

More details in internal OneNote

AB#24459023

**Comment by refortie** [comment]
Step 1) New function with manual entry
Step 2) File picker for xslt file

**Comment by kewear** [comment]
We want a new group called Custom Functions to house these
