### ISSUE TITLE
Code View Enhancements

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#1962]
### Describe the Bug with repro steps 

We want to expand on our code view experience. This includes being able to author/update yaml files and provide the ability to save/validate yaml before continuing.

Future Goal (out of scope): Side by side real time experience

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

VS Code/Windows

### Additional context 

Please see internal OneNote for more details

**Comment by refortie** [comment]
@kewear I'm not very clear on what this is in regards to?
