### ISSUE TITLE
The renderComponentIntoRoot component encountered an error while loading.

### ISSUE THREAD

**Issue by WCMV** [Azure/LogicAppsUX#1972]
### Describe the Bug with repro steps

Create a blank workflow, use the Preview Designer

Add an HTTP Request trigger
Attempt to add an in-app SQL Server Execute Query action

Interface crashes with error:

{  "shellProps": {    "sessionId": "fd03ba7e70d14bd6bab95c45772febfb",    "extName": "Microsoft_Azure_EMA",    "contentName": "DesignerEditor.ReactView"  },  "error": {    "message": "The renderComponentIntoRoot component encountered an error while loading.",    "metadata": {      "area": "renderComponentIntoRoot"    },    "error": {      "data": {        "message": "The renderComponentIntoRoot component encountered an error while loading.",        "metadata": {          "area": "renderComponentIntoRoot"        },        "capturedErrors": [          {            "message": "{\"message\":\"e.queryKey.some is not a function\",\"stack\":\"TypeError: e.queryKey.some is not a function\\n    at predicate (https://afd.hosting.portal.azure.net/ema/Content/Dynamic/kgMhxyx9QQkb.js:107:1023912)\\n    at g (https://afd.hosting.portal.azure.net/ema/Content/Dynamic/kgMhxyx9QQkb.js:2:1175488)\\n    at https://afd.hosting.portal.azure.net/ema/Content/Dynamic/kgMhxyx9QQkb.js:105:28108\\n    at Array.filter (<anonymous>)\\n    at n.findAll (https://afd.hosting.portal.azure.net/ema/Content/Dynamic/kgMhxyx9QQkb.js:105:28070)\\n    at t.isFetching (https://afd.hosting.portal.azure.net/ema/Content/Dynamic/kgMhxyx9QQkb.js:105:166081)\\n    at l (https://afd.hosting.portal.azure.net/ema/Content/Dynamic/kgMhxyx9QQkb.js:105:171964)\\n    at fP (https://afd.hosting.portal.azure.net/ema/Content/Dynamic/kgMhxyx9QQkb.js:107:1023825)\\n    at on (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:35636)\\n    at Fn (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:42359)\\n    at lc (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:110759)\\n    at Nr (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:69837)\\n    at Pr (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:69762)\\n    at wr (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:66778)\\n    at https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:23918\\n    at unstable_runWithPriority (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:42:8274)\\n    at Et (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:23627)\\n    at Tt (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:23863)\\n    at _t (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:23798)\\n    at e.kr [as batchNotifyFn] (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:43:67071)\\n    at https://afd.hosting.portal.azure.net/ema/Content/Dynamic/kgMhxyx9QQkb.js:2:1869420\",\"name\":\"TypeError\"}: {\"componentStack\":\"\\n    in fP\\n    in div\\n    in LN\\n    in FN\\n    in Z\\n    in IntlProvider\\n    in ee\\n    in l\\n    in te\\n    in l\\n    in mx\\n    in div\\n    in div\\n    in o\\n    in FluentProvider\\n    in div\\n    in o\\n    in ThemeProvider\\n    in PN\\n    in R\\n    in RN\\n    in div\\n    in M\\n    in l\\n    in Unknown\\n    in a\\n    in renderComponentIntoRoot\\n    in div\\n    in t\\n    in Styledt\\n    in i\\n    in div\\n    in ThemeProvider\\n    in Unknown\"}",            "metadata": {              "area": "renderComponentIntoRoot"            }          }        ]      }    },    "code": null  }}

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/110446881/231227956-32da924b-e396-4bb4-af7a-c415539bcbd2.png)

### Browser

Chrome Version 111.0.5563.147 (Official Build) (64-bit)

**Comment by hartra344** [comment]
Thank you for reporting this, it is now fixed in the current release. You can test if you'd like at https://aka.ms/emastaging
