### ISSUE TITLE
[Power Automate Bug Bash] Cannot figure out how to access the paths that should be created by the Condition action

### ISSUE THREAD

**Issue by edgarguoms** [Azure/LogicAppsUX#1982]
### Describe the Bug with repro steps

Condition branches(Yes No) not appearing on canvas.

In v1, when condition is added, "if yes" and "if no" are automatically added
![image](https://user-images.githubusercontent.com/71047036/231302279-3dcc4718-1bbe-42b8-bf08-9f9903e812ad.png)

In v3, don't know how to add yes/no branches
![image](https://user-images.githubusercontent.com/71047036/231302304-5f8757bc-beea-473f-9b3a-f237852b9305.png)

### Browser

Chrome

**Comment by hartra344** [comment]
@edgarguoms were you able to repro this in logic apps? I don’t think we’ve had this problem, but it looks like a potential manifest or ID problem?

**Comment by edgarguoms** [comment]
Closing for now. We have a bug in Power Automate and will look into this issue from our side.
