### ISSUE TITLE
Webhook testing _ Http webhook as a trigger and action.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#1987]
### Describe the Bug with repro steps

**Portal Workflow:**
1.Add standard LA and add stateful workflow into.
2.Add http trigger and add current time action.
3.Add http action : In method:Post, URI: Body token of the trigger, Body: Some random text and current time token.
4.Try to save the workflow.

**Actual:** Workflow is saving with a error.
![image](https://user-images.githubusercontent.com/92098490/231489604-ec96d5c4-17ac-4087-aad0-9e80fbd7fcd2.png)

**Expected:** Workflow should be saved without any error.

**VS Code workflow:**
1.Add a vs code project and stateful workflow into.
2.Add HTTP webhook as trigger.
3.Method: Post, URI: Portal workflow URL from above portal step 4.
4.In Body : Try to add callback URL token.

**Actual:** No option is present to add token.
![image](https://user-images.githubusercontent.com/92098490/231490656-30ba8786-4d46-4b86-8f4b-952a6edf461d.png)

**Expected:** Token should be present.

### Browser

Vs Code

### Additional context

**VS Code Artifacts :**

VS Code extension - ​vsix icon[ vscode-azurelogicapps-2.0.26.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEfJ4595SDX5EoA0o4opi1QUBK69sLNCgtG8wBkpG99Hc3w&data=05%7C01%7Cv-prakumar%40microsoft.com%7Cccf63d0afa4b4ca0ceab08db3b30d055%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638168853117665486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=i5yTIBtN8NwClNPqEBC1qKEMVuJT4mVXHHEc6fH84VU%3D&reserved=0)
NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcxMzU5ODUxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.17.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcxMzU5ODUxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.17.1.nupkg&data=05%7C01%7Cv-prakumar%40microsoft.com%7Cccf63d0afa4b4ca0ceab08db3b30d055%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638168853117665486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yHo7Ytd20pisBUXoCrACD3YfwsnPHl1Tjafj%2BjiyA5o%3D&reserved=0)
Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-prakumar%40microsoft.com%7Cccf63d0afa4b4ca0ceab08db3b30d055%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638168853117665486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mUlUBmuFGSa4uxmY9pXpLUHi7kvVs%2FQWDjzvUNUJ%2BVo%3D&reserved=0)
Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.17.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.17.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.17.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.17.1_any-any.zip&data=05%7C01%7Cv-prakumar%40microsoft.com%7Cccf63d0afa4b4ca0ceab08db3b30d055%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638168853117665486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0EB3fj0IVIeYeDedtSTKeTA%2FxQiUKVuDTCPB508EXzM%3D&reserved=0)

**Comment by Eric-B-Wu** [comment]
Part 2 of this issue should be fixed https://github.com/Azure/LogicAppsUX/pull/1974 in this PR

**Comment by v-prakumar** [comment]
Part 2 is repro in the standard workflow.
**Environmental Details:**

**URL:** [https://aka.ms/emastaging-flowsEurope](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowsEurope&data=05%7C01%7Cv-prakumar%40microsoft.com%7C6746917794314779b5e008db3f22c116%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638173190794091101%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=su9YUFd1EsF80Aq982vvRl5Y7HNveUYJqkLsEJ4foL8%3D&reserved=0)

**Version :** 2.30410.1.3

![image](https://user-images.githubusercontent.com/92098490/232445807-da291c9f-e7e9-4cf7-b8c0-1d4739867fca.png)

**Comment by Eric-B-Wu** [comment]
@v-prakumar please note that this PR was completed 4/12, and the release was a snapshot of the designer on 4/10, so this change is not reflected yet on the release branch

**Comment by v-prakumar** [comment]
@ccastrotrejo For VS Code (2.9.1) issue is fixed.
