### ISSUE TITLE
Array input for actions doesn't render detailed input view in new preview designer

### ISSUE THREAD

**Issue by ShreeDivyaMV** [Azure/LogicAppsUX#1996]
### Describe the Bug with repro steps

Choose event grid publish action in preview designer.
Click on "Switch to detailed inputs for array item"
Click on add new item. - It is blank
Expected behavior- Provide option to fill the detail for each item in the array(as it does in GA designer)
If we manually enter the data, it gives warning that "Please enter a valid array"
Same input works fine in GA designer.
Attaching the screenshots from GA and preview designer.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/30790938/231350661-8cb465c7-d2fa-4e19-86a4-bddf9a99b35d.png)
![image](https://user-images.githubusercontent.com/30790938/231350689-fb03faca-81e7-4f0e-8226-da2be3fe2420.png)

### Browser

Safari

**Comment by hartra344** [comment]
@Eric-B-Wu
