### ISSUE TITLE
Consumption_Edit blade : Unable to see New preview option

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2001]
### Describe the Bug with repro steps

1.Create a Logic app in consumption
2 Edit blade should have New preview designer option. 

**Expected :** Edit blade should have New preview designer option. 

**Actual:** Unable to see the New designer option in Edit blade for consumption , Able to see the new designer option under development tool -> logic apps blade , and when changed to general view mode in it, we are able to see the new designer in Edit blade but in the edit blade we are not able to change from general view mode to new designer mode.

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {}
    },
    "parameters": {}
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/113517384/231779755-34c40835-1922-4211-975b-cf340fb53493.png)
![image](https://user-images.githubusercontent.com/113517384/231780348-6709292e-3482-435f-9b4b-9bfcc867c368.png)
![image](https://user-images.githubusercontent.com/113517384/231780091-d25eda66-a796-4f14-acc4-724a92d8edb7.png)
![image](https://user-images.githubusercontent.com/113517384/231780179-40154ded-737b-4df8-854e-8bc20a15af46.png)

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C5dc1b66779e54ebfb20b08db3bf92e3f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638169713681866036%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ox8FGZYcViENAadUWbkyOt05VGv%2FAvR7SYpEG%2BGHVDI%3D&reserved=0)
**Version :** 2.30410.1.3

**Comment by rllyy97** [comment]
I've fixed this in our other repo, will be live in our next release.
