### ISSUE TITLE
Azure Function missing swagger actions.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2005]
### Describe the Bug with repro steps

1.Create a LA in consumption and add http trigger.
2.Add azure function action.

**Actual:** No Swagger action.
![image](https://user-images.githubusercontent.com/92098490/231815472-e2211a45-8cd2-4590-8c94-0cc3f678fa29.png)

**Expected:** Swagger action should be present as per old Designer.
![image](https://user-images.githubusercontent.com/92098490/231816210-fafe4fc0-4ee0-43e6-8142-dd5694361b74.png)

### Browser

Chrome

### Additional context

**Environmental Details:**

**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C5dc1b66779e54ebfb20b08db3bf92e3f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638169713681866036%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ox8FGZYcViENAadUWbkyOt05VGv%2FAvR7SYpEG%2BGHVDI%3D&reserved=0)

**Version :** 2.30410.1.3

**Comment by rllyy97** [comment]
Merged into main branch in designer and portal 👍
