### ISSUE TITLE
Overview Blade identifier up/down scroll should be align well.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2008]
### Describe the Bug with repro steps

1.Go to overview page of standard logic app.

**Actual:** Up/Down Scrollbar is not in fit view.
![image](https://user-images.githubusercontent.com/92098490/231834359-f7123e39-d5c6-4707-97a5-8f7d9517477e.png)

**Expected:** Should be fit as expected.

**Note:** Having only 1 identifier.

### Browser

Chrome

### Additional context

Environmental Details:

URL: [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C5dc1b66779e54ebfb20b08db3bf92e3f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638169713681866036%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ox8FGZYcViENAadUWbkyOt05VGv%2FAvR7SYpEG%2BGHVDI%3D&reserved=0)

Version : 2.30410.1.3

**Comment by hartra344** [comment]
It aligns with the scrollable space which includes the header. This will be solved if #2010 can be fixed.
