### ISSUE TITLE
VSCode designer - unable to select subscription for gateway with sql connector

### ISSUE THREAD

**Issue by ryansalt** [Azure/LogicAppsUX#2022]
### Describe the Bug with repro steps

We are unable to add a sql connection to our logic app via the VSCode designer as the Subscription dropdown is not populated.

1. Create new Logic App project with new workflow via Logic Apps Standard plugin.
2. Right click on workflow and choose Use Connections From Azure.
3. Open workflow in designer and dd a trigger.
4. Add a sql action like Execute SQL Stored procedure.
5. Enter the connection details.
6. Under the gateway section, the subscription dropdown is empty, so we can't choose the subscription. The gateway selection box remains disabled.
7. Click Create New without entering the gateway info results in an Unexpected error,

### Screenshots or Videos

![empty_subscription_dropdown](https://user-images.githubusercontent.com/2374133/232089596-6bac1360-c877-4f3b-b801-339e502c0241.png)

### Browser

n/a

### Additional context

VSCode version 1.77.3
Windows 10
Azure Logic Apps (Standard) plugin version v2.2.1 (2023-04-13)

**Comment by hartra344** [comment]
@rllyy97
