### ISSUE TITLE
Workflow Designer Very Very Slow - not able to work

### ISSUE THREAD

**Issue by smadhukar2000** [Azure/LogicAppsUX#2033]
### Describe the Bug with repro steps

Hi Team,
After last week Standard logic app workflow changes, Workflow is not loading at all in designer. Tried multiple times with Azure SQL Server Connector.

Earlier also designer/run history loading was slow. But used to load;  Now its very very slow and not loading at all.

Technology wise standard workflows designer it very slow compared to consumption logic apps.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/18157267/232352744-b29edc75-1746-4c2d-b3ee-f2626b43bfc2.png)

### Browser

Chrome is up to date
Version 112.0.5615.121 (Official Build) (64-bit)

**Comment by hartra344** [comment]
HI @smadhukar2000 Is the designer loading correctly in the Generally Available designer? Or is it unable to load in either version?

**Comment by smadhukar2000** [comment]
Hi @hartra344 ,

1) Yes its GA designer and Australia East is the region.
2) I am using Azure SQL Connector for on-premise DB (recently its category has changed in GA portal).

**Steps**
- First time i am able to add **sql get rows (v2)** action correctly and save it.
- Next time if i reload the designer, SQL SERVER GET ROWS action keep spinning though all other actions have loaded. And it keeps loading for several minute, until i loose my patience. Tried many times.


**Workaround**
As this action works on first time only, so only workaround for me is to delete the action and re-create it.
And it keeps spinning for all SQL SERVER connector actions.


![image](https://user-images.githubusercontent.com/18157267/232667825-b3719119-e81c-4e8f-9fd1-201310bdefa3.png)


Thanks,
Subhash

**Comment by hartra344** [comment]
Thank you for the extra information. We'll look into this.

**Comment by smadhukar2000** [comment]
Hi @hartra344 

got little more info, when i opened chrome developer tools; same issue in MS edge also.

I can see error details, which may help you guys to resolve the issue.

**Note:**
I am ABLE to load standard logic app designer through VSCODE successfully and VSCODE loading is faster than  brwoser.

**":40:18 AM operation deserializer Unable to initialize operation details for swagger based operation - Delete_row_(V2). "**

![image](https://user-images.githubusercontent.com/18157267/234437591-f5eec4e1-f23f-46d5-8ec5-16d084b40f13.png)

**Comment by preetriti1** [comment]
@smadhukar2000 - Do you mind sharing the console logs, i can see in your screenshot the bottom one has the error stack trace.
Currently when we cannot load the operation for any node, it goes into loading state, although it is in error state. We want to know why this action is correctly loaded in GA designer but not in preview.

**Comment by smadhukar2000** [comment]
Hello @preetriti1 

You are right in preview portal its loading perfectly BUT in GA its still not loading.

Feel free to message me, if need more info.


please find attached screenshot and console log for the operation.
[portal.azure.com-1683252603588.log](https://github.com/Azure/LogicAppsUX/files/11402854/portal.azure.com-1683252603588.log)


![image](https://user-images.githubusercontent.com/18157267/236364734-d9936c34-0375-4d67-8177-ff21d0bad6b7.png)
