### ISSUE TITLE
Standard_Custom Http Timeout Setting Per Request Action: The HTTP Request action showing as **Success**

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2038]
### Describe the Bug with repro steps

1.Create a standard logic app
2.Create an empty stateless workflow
3.Add a request trigger and HTTP request action.
4.The request url to point to
(https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI)
5.Go to settings tab and set Request options to PT1S
6.Disable the Asynchronous pattern.
7.Save and run the workflow.
8.**Expected Result:** The HTTP Request action should be marked as **failed**.
**Actual Result:** The HTTP Request action showing as **Success**.

**Note:** Looks like changing the Request options to PT1S is not saving successfully even after showing the success saving message.

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "HTTP": {
        "type": "Http",
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/113517384/232490251-c18f09cc-50e1-4a84-a034-64a860b65f6d.png)
![image](https://user-images.githubusercontent.com/113517384/232490918-2f7de0c9-7827-4e82-96ec-642700d6fc08.png)

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** https://aka.ms/emastaging-flowsEurope
**Version :** 2.30410.1.3

**Comment by vgouth** [comment]
Issue repro in latest artifact.

1.	VS Code extension -    vscode-azurelogicapps-2.9.1.vsix
2.	NuGet package: https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyMDcxNTQ1L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.1.nupkg
3.	Extension Bundle (CDN URL): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting
4.	Extension Bundle (Direct Download): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.19.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.19.1_any-any.zip

**Comment by preetriti1** [comment]
This is not an issue with correct timeout value and operationOptions. There is an issue with Http action settings where Asynchronous response is being shown instead of disable async pattern, so that is fixed by #2207 ,
Closing as failing http action for 1 second timeout is still working, please make sure your codeview ie workflow.json is correct before running the app.

**Comment by vgouth** [comment]
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/87835bd6-a063-4f3b-b94a-fece62def859)

**Comment by vgouth** [comment]
Issue repro in the latest request: 

**Environment Details:**
**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C31d00efa413749e2fcaf08db52c01071%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638194757160988184%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C4YPP00dkZYHfK1wuCRn2xH2NOgzqZ5lPaypxcMgEwM%3D&reserved=0)
**Version:** 2.30508.1.2
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/f0cfb970-c5bd-4faa-b9b6-8d0d51843198)

**Comment by vgouth** [comment]
**Note:** We are able to see Asynchronus pattern instead of Asynchronus response. This issue is resolved.

**Comment by vgouth** [comment]
**Issue repro in latest artifact.**

1,VS Code extension – vscode-azurelogicapps-2.15.15.vsix
2.NuGet package: https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczMDA5ODA5L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.21.3.nupkg
3.Extension Bundle (CDN URL): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting
4.Extension Bundle (Direct Download): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.21.3/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.21.3_any-any.zip
5.Resources vsix. vscode-azureresourcegroups-LA.vsix

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/14a408ef-23f9-4390-9df9-8786cd69355a)

**Note:** We are able to see Asynchronus pattern instead of Asynchronus response. This issue is resolved.

**Comment by vgouth** [comment]
**Issue repro in latest artifact.**

1.VS Code extension: vscode-azurelogicapps-2.18.0.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RAdRQgUdZRVaGVezHUCgOrk9dqDH%2FroCbmRi3G6qINE%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p4gGTn5fIyNqeVEkRK0OAoJKnFiRCvk%2BDcxOO2g%2BJck%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.23.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.23.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C1315cce631bf4e88b67a08db5b43d604%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638204119230399009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O9utopA3qZWwqlBv1b200p9ZE0vBZgPMR84gQlrP%2F%2Bc%3D&reserved=0)


![image](https://github.com/Azure/LogicAppsUX/assets/113517384/dd21b28e-d2a9-4126-b870-4703d7f23fe8)

**Comment by vgouth** [comment]
**Issue repro in the latest request:**

**Environment Details:**
**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cb13bdbce753c4d10e4d208db602642f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638209489719398144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ouKhkhxrFJJr2RCOpHP%2F3nqcaTagt7jkAg8FKOmhWRU%3D&reserved=0)
**Version:** 2.30529.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/ad91f379-263b-4007-b8c6-91f008cf14f5)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/94d967a8-58bc-44bc-88f7-0fa639628086)
