### ISSUE TITLE
Standard_Custom Http Timeout Setting Per Request Action: The HTTP Request action showing as Success without validation error

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2039]
### Describe the Bug with repro steps

1.Create a standard logic app
2.Create an empty stateless workflow
3.Add a request trigger and HTTP request action.
4.The request url to point to
([https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI](https://httptimeoutendpoint.azurewebsites.net/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI))
5.Go to settings tab and set Request options to PT24H
6.Disable the Asynchronous pattern.
7.Save and run the workflow.
8.**Expected Result:** The workflow should save and present a validation error "**The provided request options timeout of '24:00:00' for action 'HTTP' must be less than '01:00:00**'
**Actual Result:** The HTTP Request action showing as Success without validation error.

**Another Scenario**

9. Again change the Request options to InvalidString
10.**Expected Result:** The string **InvalidString** is not a valid timespan value.
**Actual Result:** The HTTP Request action showing as Success without validation error.

Note: Looks like changing the Request options to PT1S is not sa

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "HTTP": {
        "type": "Http",
        "inputs": {
          "uri": "https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI",
          "method": "POST"
        },
        "runAfter": {},
        "limit": {
          "timeout": "PT24H"
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}








Another Scenario JSON code

{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "HTTP": {
        "type": "Http",
        "inputs": {
          "uri": "https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI",
          "method": "POST"
        },
        "runAfter": {},
        "limit": {
          "timeout": "InvalidString"
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/113517384/232493234-c1b5ef84-3a35-4151-a4be-bb3391269bfa.png)
![image](https://user-images.githubusercontent.com/113517384/232494203-f2c73d05-e161-452d-b71d-1be7425a76b6.png)

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** https://aka.ms/emastaging-flowsEurope
**Version :** 2.30410.1.3

**Comment by preetriti1** [comment]
This cannot be reproduced now after fixing the setting for Http, it was incorrectly showing Asynchronus response instead of pattern and validation run by service would show the error for invalidstring and invalid timespan.
The fix for setting name should be present in our next release by end of May.

**Comment by vgouth** [comment]
**Issue repro in latest artifact.**

1.	VS Code extension -    vscode-azurelogicapps-2.15.10.vsix
2.	NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyNDMyOTY3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.4.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyNDMyOTY3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.4.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce16550a435744c5e7ee008db5132f638%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638193051620714027%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OORNaejGlAVEsJx5ryrvmT9wsQK7SskecXpaNtw9CW4%3D&reserved=0) 
3.	Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce16550a435744c5e7ee008db5132f638%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638193051620714027%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XXr2gcYmycEZwcszkAdPgmUBpj1YvRNSixcuQpxqDV4%3D&reserved=0) 
4.	Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.19.4/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.19.4_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.19.4%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.19.4_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce16550a435744c5e7ee008db5132f638%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638193051620714027%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uUpbZtdNzt%2FT2KOBFZBmUdrx3KnalLi8gX5fYMYLjxo%3D&reserved=0)
5. Resources vsix.  
  vscode-azureresourcegroups-LA.vsix

**Comment by vgouth** [comment]
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/8c506537-b90f-47ef-bbe9-d5350c9fd3e2)

**Comment by vgouth** [comment]
Issue repro in the latest request:

**Environment Details:**
**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C31d00efa413749e2fcaf08db52c01071%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638194757160988184%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C4YPP00dkZYHfK1wuCRn2xH2NOgzqZ5lPaypxcMgEwM%3D&reserved=0)
**Version:** 2.30508.1.2

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/c7f7c128-85f5-4b19-8e98-ba5c8f6e1f94)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/fceac4b6-2489-4303-8002-b004fa1f9aaf)

**Note:** We are able to see Asynchronus pattern instead of Asynchronus response. This issue is resolved.

**Comment by ccastrotrejo** [comment]
This issue works fine in portal, it's just repro in VSCode. Will fix it and update the issue thread once it is solved.

**Comment by vgouth** [comment]
**Issue repro in latest artifact.**

1.VS Code extension: vscode-azurelogicapps-2.18.0.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RAdRQgUdZRVaGVezHUCgOrk9dqDH%2FroCbmRi3G6qINE%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p4gGTn5fIyNqeVEkRK0OAoJKnFiRCvk%2BDcxOO2g%2BJck%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.23.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.23.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C1315cce631bf4e88b67a08db5b43d604%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638204119230399009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O9utopA3qZWwqlBv1b200p9ZE0vBZgPMR84gQlrP%2F%2Bc%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/e01eed30-abd9-44af-bd06-6592f53855a5)

**Comment by vgouth** [comment]
**Issue repro in the latest portal request as well:**

**Environment Details:**
**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cb13bdbce753c4d10e4d208db602642f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638209489719398144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ouKhkhxrFJJr2RCOpHP%2F3nqcaTagt7jkAg8FKOmhWRU%3D&reserved=0)
**Version:** 2.30529.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/e2ebe179-ca01-4ca6-81c6-4a30f097da00)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/1b7d430c-73d8-4725-bd45-445e545feffe)

**Comment by ccastrotrejo** [comment]
Hey @vgouth, the step 5 from the description says `Go to settings tab and set Request options to PT24H` and it seems from the screenshots that the `invalidString` and `PT24h` are written in the Action Timeout in the general area. Can we agree which one is the right one?  I tried in the Request Options and both show the error validation notification
<img width="300" alt="Screenshot 2023-05-31 at 11 56 25 AM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/5749efcd-7d86-4554-8b45-be7c97b5df26">

<img width="300" alt="Screenshot 2023-05-31 at 11 56 08 AM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/15812e70-f214-4a74-87c9-66cdeea32f1d">

**Comment by vgouth** [comment]
@ccastrotrejo  - Yes, now we are able to see the Request options tab under networking which is the right one. I tried to change the timeout to PT24H but the validation error we are getting not similar to previous one. But in invalidString case we are getting the same error.

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/d6453d0f-5880-4bc5-adf8-ca5636aa0693)

**Comment by ccastrotrejo** [comment]
> @ccastrotrejo - Yes, now we are able to see the Request options tab under networking which is the right one. I tried to change the timeout to PT24H but the validation error we are getting not similar to previous one. But in invalidString case we are getting the same error.
> 
> ![image](https://user-images.githubusercontent.com/113517384/242662618-d6453d0f-5880-4bc5-adf8-ca5636aa0693.png)

@vgouth this screenshot is fine since the `PT24h` it's not a valid timespan it should be `PT24H`,

**Comment by vgouth** [comment]
@ccastrotrejo , I have checked with **PT24H** timespan but the validation error, getting is different (The provided request options timeout of '1.00:00:00' for action 'HTTP' must be less '00:03:45'."}}) when compared to previous one ("The provided request options timeout of '24:00:00' for action 'HTTP' must be less than '01:00:00'). Is this the expected one for the new designer ?

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/724e5235-7e5b-441f-9f9f-9c461058e365)

**Comment by hartra344** [comment]
This new error is coming from the backend validation, not front end. It appears to be expected.
