### ISSUE TITLE
SFTP_Logic app is saving with workflow validation failed.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2040]
### Describe the Bug with repro steps

1. Create a LA in standard.
2. Add SFTP trigger and add connection.
3. Try to save the Logic app : 

**Actual :** Saving with workflow validation failed.
![image](https://user-images.githubusercontent.com/92098490/232507151-7e3232ea-d579-4725-9282-4d19236c43a2.png)

**Expected:** The workflow should be save without any error.

### Browser

Chrome

### Additional context

**Environmental Details:**

 

**URL:** [https://aka.ms/emastaging-flowsEurope](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowsEurope&data=05%7C01%7Cv-prakumar%40microsoft.com%7C6746917794314779b5e008db3f22c116%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638173190794091101%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=su9YUFd1EsF80Aq982vvRl5Y7HNveUYJqkLsEJ4foL8%3D&reserved=0)

**Version :** 2.30410.1.3

**Comment by rllyy97** [comment]
This looks like an issue with the recurrence parameter not being filled with default data.  Filling the Interval and Frequency fields before saving lets the validation pass and the workflow saves with no issues.
![image](https://user-images.githubusercontent.com/25409734/234919205-482c3224-5579-4e06-8aad-70de65eab16c.png)
