### ISSUE TITLE
[Power Automate] https://msazure.visualstudio.com/One/_workitems/edit/17627948 -Side panel should respect runtime result. Aka not show custom connector unless 'Custom' runtime is chosen.

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#2048]
### Describe the Bug with repro steps

https://msazure.visualstudio.com/One/_workitems/edit/17627948 

### Screenshots or Videos

https://msazure.visualstudio.com/One/_workitems/edit/17627948 

### Browser

Chrome

**Comment by ek68794998** [comment]
Think this is a dupe of #1811.
