### ISSUE TITLE
Adding a second trigger and deleting first trigger causes spin

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#2050]
deleting a trigger in the middle of a flow results in perpetual spinny. I added “when a new team member is added” to an existing flow, and then attempted to delete it, to get the following spinny and layout that I can’t get out of without exiting the designer:

![Image](https://user-images.githubusercontent.com/13208452/232846923-fe9c2072-01d7-4a8f-b802-b33fdff6e528.png)

More Info: https://msazure.visualstudio.com/One/_workitems/edit/17929110

**Comment by Eric-B-Wu** [comment]
#2145

**Comment by rllyy97** [comment]
This issue is fixed in our upcoming release, we will be rolling it out throughout next week (between May 8th-12th)
