### ISSUE TITLE
Save Button not functioning 

### ISSUE THREAD

**Issue by Mounesh1881** [Azure/LogicAppsUX#2054]
### Describe the Bug with repro steps

When we have done modification in logic app designer and save it, it is not getting save once page refresh it getting discard.

### Browser

Chrome and Microsoft edge

**Comment by hartra344** [comment]
Thanks for the report. We’re going to need more information though.

made you using consumption or standard sku logic apps?
Are you using preview or generally available designer?

**Comment by Mounesh1881** [comment]
Hi Team,

Please see my comments below.


Thanks & Regards,
Delivering Secure and Reliable IT Services and Operations across Shell.

***@***.***Mounesh Pattar(INMPFE)
Functional Specialist- HCA Global Operations | Energy Components second line support
Function Mail Box : ***@***.******@***.***>
24/7 Call Desk : ***@***.******@***.***>
Shell Upstream - Production Application Support | IBM-Shell Offshore | Bangalore, India

**Comment by hartra344** [comment]
This issue is being tracked by #2041
