### ISSUE TITLE
VSCode Logic App Icons Are Not Follwing VSCode Accessibility Guidelines

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#2056]
### Describe the Bug with repro steps 

1. Our Icons are not Accessibile 

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Vscode

### Additional context 

Follow up with our designers to make sure our icons are accessible.

List of some acceptable icons:

[https://microsoft.github.io/vscode-codicons/dist/codicon.html](<https://microsoft.github.io/vscode-codicons/dist/codicon.html>)

[https://iconcloud.design/browse/Fluent%20System%20Library/Fluent%20Regular](<https://iconcloud.design/browse/Fluent%20System%20Library/Fluent%20Regular>)

AB#24578649

**Comment by ccastrotrejo** [comment]
Had a talk with Nolan, he is working on mocking and syncing with the vscode team to sing off the icons. Once everything gets approved we will be able to make the change on the icon(s)
