### ISSUE TITLE
XSLT is not updated after testing

### ISSUE THREAD

**Issue by skastberg** [Azure/LogicAppsUX#2061]
### Describe the Bug with repro steps

After testing a map in Visual Studio Code the Xslt file is not updated. Any subsequent tests or execution will use an xslt that is not current. 

1. Create a new map
2. Start working with the map
3. Save
4. Review that the Xslt file and Yml files match each other
5. Do some update and save
6. Review that the Xslt file and Yml files match each other
7. Test the map
8. Do some update and save
9. Review that the Xslt file and Yml files and find that the files are not synchronized.

**Workaround**
Shut down Visual Studio Code and any instance of Microsoft.Azure.Workflows.Functions.NetFxWorker.exe. Restart VS Code and continue working. 

### Screenshots or Videos

Comparing the Yaml and Xslt files when not synchronized.

![image](https://user-images.githubusercontent.com/17530167/232916215-0768cfbf-6ec6-45ae-a6b0-250e70e58e38.png)

### Browser

**Extensions:** 

- Data Mapper v2.3.0
- Azure Logic Apps (Standard) v2.4.5

**Visual Studio Code** 

- Version: 1.77.3 (user setup)
- Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
- Date: 2023-04-12T09:16:02.548Z
- Electron: 19.1.11
- Chromium: 102.0.5005.196
- Node.js: 16.14.2
- V8: 10.2.154.26-electron.0
- OS: Windows_NT x64 10.0.22621
- Sandboxed: No

**Comment by refortie** [comment]
This is a known issue that has been fixed. It is pending a new Azure Functions Core Tools extension bundle release

**Comment by refortie** [comment]
This has been deployed.
