### ISSUE TITLE
Logic App Standard - Designer error - Multiple identities

### ISSUE THREAD

**Issue by verschaevesiebe** [Azure/LogicAppsUX#2076]
### Describe the Bug with repro steps

Hi All,

We decided to start adding multiple user assigned managed identities so that we could differentiate the rights/permissions they have across multiple Logic App Standard resources. However, in doing so when looking at workflows within such a logic app standard workflow the designer stops working on the Azure portal. (locally it works)

Below is a summary of the issue which I assume affect a lot of others as well.

1.	Add multiple user assigned identities to Logic App Standard

2.	When opening any workflow the designer doesn’t load but instead pushes traces onto the console stack.
"code":"InvalidNumberOfUserIdentities","message":"Multiple user identities are not supported. Please select only one user identity.","stack":"Core.AssertionException: Multiple user identities are not supported. Please select only one user identity.

An initial workaround, for now, is using the Preview Designer (it is supported there)
However, the preview designer messes up quite a lot for now and I assume that will be fixed in the future.

As an initial issue tracker for the preview designer, I can tell a few things.
•	The save button is always active even if there are no changes.
•	On save the designer “View Code” doesn’t effectively update in the side panel, it does on the code view though.

•	After doing a deployment (adding concurrency control)
If you use the preview designer and save the workflow the concurrency control is switched off again.
So, it essentially doesn’t keep the settings that were in the code prior to deployment.

If you need additional information, please also reach back out to me. I’m happy to help.

### Screenshots or Videos

Error uppon adding multiple managed identities.

![image](https://user-images.githubusercontent.com/22643503/233306350-812c0c35-b7d6-45d9-8db7-f21220d2a0dd.png)

### Browser

Brave browser, google chrome

**Comment by hartra344** [comment]
@verschaevesiebe Thanks for posting with the issues you've found. Some quick answers:
We have stopped adding features to GA designer so Multiple Identities is unlikely to get added, I'm thrilled to hear it's fixed for you in preview designer though. We're focusing now on getting the last touches on and trying too stabilize issues for a GA release.

- [ ] The save button is always active even if there are no changes: This is a known issue, we're working on change detection that will make this possible to not be the case.
- [ ] On save the designer “View Code” doesn’t effectively update in the side panel, it does on the code view though: This should be showing a snapshot of the code when you hit the button, but will not update on changes after. We do have future(no specifics planned though) to make this better though.
- [ ]   The concurrency control issue, this is an issue I haven't seen yet, thanks for bringing it up, we'll check it out!

Particularly for preview designer, please feel free to come here and post any more issues you find. We very very much appreciate it!

**Comment by rllyy97** [comment]
This issue has been fixed in a different repo, it will be live in our next release!
