### ISSUE TITLE
Export of certain Logic Apps fails

### ISSUE THREAD

**Issue by xalbrech** [Azure/LogicAppsUX#2078]
### Describe the Bug with repro steps

Unable to export certain Logic Apps definitions from an Azure subscription. 

1. Run the export wizard, select subscription, location, next
2. Select multiple logic apps to export, next
3. After approx 30 seconds, the export fails with error message that reads: "The export package URL experienced an unknown problem." No details about the error or its context given.

After that, I did several attempts to workaroundé the error. Eventually, I figured out there are two logic apps that cause this and if these two were not included, the export suceeded. The error message should include context (what is the workflow that failed) and an explanation (why it failed). 

Additional issue: though the export wizard provides a "Back" button, attempts to go back, change settings and trying again almost never work - the dialogs are stale, etc. To try again, there's a need to close the export completely and start over.

### Browser

Chrome

**Comment by ccastrotrejo** [comment]
Hi @xalbrech is there any chance you can share with use the workflow JSON from those two apps that you identified aren't working.
Which exact step is the one you are getting this issue?
In which exact step the "Back" button is changing the settings?

**Comment by AbodeSaafan** [comment]
Hey @xalbrech there are some bugs in the conversion logic causing a 500 which causes the scenario you are explaining. We are working on a few things to improve this: 
- Better UX surfacing of the error that will provide you tracking id to provide us 
- Fixes in the backend to prevent these failures 

For now, can you please provide either your subscription ID and we can check your failures to confirm they are the known issues.
