### ISSUE TITLE
Flat file support

### ISSUE THREAD

**Issue by refortie** [Azure/LogicAppsUX#2091]
### Describe the Bug with repro steps 

Will required creating a wizard to parse flat file along with all of the normal deserialization and serialization work that needs to be done to add a new format

### Screenshots or Videos 

*No response*

### Version 

v.2.3.0

### Additional context 

*No response*

**Comment by skastberg** [comment]
When it comes to Flat file support, ideally have an option to import a flat file schema generated for BizTalk.
