### ISSUE TITLE
Rearrange inputs in the function property panel

### ISSUE THREAD

**Issue by refortie** [Azure/LogicAppsUX#2092]
### Describe the Bug with repro steps 

Be able to click and drag the order of the inputs in the property pane

### Screenshots or Videos 

*No response*

### Version 

v.2.3.0

### Additional context 

*No response*

AB#24581409

**Comment by kewear** [comment]
@DanielleCogs here is the workaround we discussed in today's meeting: https://blog.sandro-pereira.com/2023/07/14/data-mapper-tricks-and-tips-workaround-to-organize-your-functions-video/
