### ISSUE TITLE
Text Wrapping

### ISSUE THREAD

**Issue by rguptar** [Azure/LogicAppsUX#2099]
### Describe the Bug with repro steps

Text wrapping for the logic app designer code-view increases developer happiness by avoiding the need for the developer to scroll back and forth. VSCode supports this with `alt-z`. This is a feature request but I could not find an option for feature requests so I selected bug.

### Browser

All browsers

**Comment by Eric-B-Wu** [comment]
we will now text-wrap by deafult on the Code View Tab for Standard Logic Apps
