### ISSUE TITLE
Action type filter dropdown in Add Action in New Designer does nothing

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#2101]
### Describe the Bug with repro steps

1. Create a new workflow using the New Designer
2. Click on Add a trigger
3. Click Action type
4. Observe nothing happens

![image](https://user-images.githubusercontent.com/351644/233716728-35bd59a6-19ca-4964-b96c-04607aca904b.png)

### Screenshots or Videos

n/a

### Browser

Microsoft Edge version 112.0.1722.39

**Comment by Eric-B-Wu** [comment]
@abatishchev thanks for reporting this issue, this is happening because we filter the options to only show triggers, however, we do not reflect it in the dropdown, I'll make the change so that this dropdown being disabled is more apparent.
