### ISSUE TITLE
Unable to add Azure Blob Storage trigger using New Designer

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#2102]
### Describe the Bug with repro steps

1. Create a new workflow using the New Designer
2. Click on Add a trigger
3. Select Azure Blob Storage (in-app), When a blob is added or updated

![image](https://user-images.githubusercontent.com/351644/233717518-54ffa78c-abc4-4614-abf1-7cffd7fb537a.png)

5. Observe an error:

![image](https://user-images.githubusercontent.com/351644/233717544-9b21fb5c-2bb4-467b-afac-a6dda3b650c2.png)

Session ID: cf91f9c88d5948e0a7ccf3fd103ba611

### Workflow JSON

```json
n/a
```

### Browser

Edge version 112.0.1722.39

**Comment by Eric-B-Wu** [comment]
@abatishchev This issue should be fixed in our latest release which will finish deploying all regions end-of-day today. Please reopen if by tomorrow this issue is not fixed.

**Comment by Eric-B-Wu** [comment]
There was a little delay in the release, should be finished by EOD Monday (4/24)
