### ISSUE TITLE
After all requests finishes still show Loading in the Recommendation Panel

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#2124]
### Describe the Bug with repro steps

1. Open a workflow
2. Wait for network requests to finish
3. Click to Add a new Node
4. Regardless of how long we wait, 'Loading More Results' will still show

### Screenshots or Videos

<img width="1255" alt="loading" src="https://user-images.githubusercontent.com/95886809/234344399-f4053bf7-8faa-45b9-8f3a-8c32bef8a77e.PNG">

### Browser

edge

**Comment by hartra344** [comment]
I think this is a result of us never preloading and it seems like preloading expectations were baked in. We may need to rework this a bit. Rama has changes in/going in too that will allow us to get way more operations per page. This will help with speed.

**Comment by rllyy97** [comment]
This issue is fixed in our upcoming release, we will be rolling it out throughout next week (between May 8th-12th)
