### ISSUE TITLE
 content IS not valid and could not be deserialized could not find member trackedproperties on object of type flowtemplatetrigger

### ISSUE THREAD

**Issue by metanpatel** [Azure/LogicAppsUX#2135]
### Describe the Bug with repro steps

When saving this.   But this works in PowerApps.  We want to use Logic Apps instead

### Workflow JSON

```json
{
  "type": "ServiceProvider",
  "inputs": {
    "parameters": {
      "tableName": "[dbo].[SR_Detail]"
    },
    "serviceProviderConfiguration": {
      "connectionName": "sql",
      "operationId": "whenARowIsInserted",
      "serviceProviderId": "/serviceProviders/sql"
    }
  },
  "conditions": [
    {
      "expression": "contains(SR_Detail_Notes, 'SentinelOne')"
    }
  ],
  "trackedProperties": {}
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/53191866/234414465-cd9ba3ab-0447-46cf-8975-8982386a1723.png)

### Browser

Chrome

**Comment by hartra344** [comment]
Are you using Consumption or Standard Logic Apps? Also are you doing this in designer or in the code view? Logic Apps and Power Automate are very close but are not a direct 1:1 mapping of each other.

**Comment by metanpatel** [comment]
I am doing this in the Designer because I dont see how the code view works - Limited documentation on syntax found online and code view says "Read Only" in many areas. 

Also, my goal was to get some data based on a Modified or Insert and Update trigger to get rows and use other tools, such as OpenAI or AI Builder or something to create entities for text in a certain column of that row, store it to another data table in another database and then call my API so I can do the rest through my API that has business logic that would consume that stored records.   But I cant even get the DB connected for some reason - Step 1 fails.  

I am using Power Automate and have no problem, I want to use Logic Apps but = Problem
