### ISSUE TITLE
save button in Logic App Designer not working.

### ISSUE THREAD

**Issue by emmanguiang** [Azure/LogicAppsUX#2140]
### Repro steps

1. Go to an existing logic app
2. Edit a step
3. Click "Save" 
4.  A notification will show: "Successfully saved workflow"
![image](https://user-images.githubusercontent.com/30649759/234448771-6febdb1e-00fa-414a-9241-c47fc0fe62a0.png)
6. Leaving the said page will trigger an alert as if you didn't save it
![image](https://user-images.githubusercontent.com/30649759/234448929-bf55080c-adc3-422f-9453-66d07748d5c9.png)

### Browser

Browser: Chrome

**Comment by chrisyang-callaway** [comment]
I face the same problem. Looking for some guidance.

**Comment by Eric-B-Wu** [comment]
This should be fixed in our next release which will complete on 5/12
