### ISSUE TITLE
For Loop action doesn't show concurrency settings in VS Code

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2141]
### Describe the Bug with repro steps

![ForEach-bug-concurrency](https://user-images.githubusercontent.com/40304643/234471704-0f856c84-65dc-46ce-b107-b2cf63d2442b.jpg)

### Browser

VS Code

**Comment by ccastrotrejo** [comment]
Hi @mhireholi thanks for raising this issue, I will work on fixing it!

**Comment by mhireholi** [comment]
I still don't see this in the VSCode editor
![for-each-bug-1](https://github.com/Azure/LogicAppsUX/assets/40304643/28ff05ab-bfaf-4ab7-90d4-8bad8ace0205)

**Comment by ccastrotrejo** [comment]
Hi @mhireholi, we haven't released a new extension version. We are planning to do this in the upcoming days. Once we release it, the fix will be there. Thanks!

**Comment by ccastrotrejo** [comment]
Hi @mhireholi, we haven't released a new extension version. We are planning to do this in the upcoming days. Once we release it, fix will be there. Thanks!
