### ISSUE TITLE
Preview designer / Save button has no effect

### ISSUE THREAD

**Issue by jephlu** [Azure/LogicAppsUX#2144]
### Describe the Bug with repro steps

When Editing an existing Logic App with the new "Preview designer", the save button does not work.

Example : I change the frequency of a trigger on a rss feed, or i change the importance on an email step, then i click the "save" button, it seems working, as the notification is displayed : 
![image](https://user-images.githubusercontent.com/47847668/234531321-d7085fde-1dec-4098-99dd-6e9737ad6a12.png)

When leaving the editor, there is a warning on unsaved settings : 
![image](https://user-images.githubusercontent.com/47847668/234532145-56a1fd46-7567-4602-9c60-d9c64642c054.png)
(but this message appears even if there no changes! So seems insignificant)

When returning on a previously saved logic app workflow, the "saved" modification was not really saved.

### Browser

Microsoft Edge
Version 112.0.1722.39 (Version officielle) (64 bits)

**Comment by rllyy97** [comment]
Hi @jephlu, thanks for the bug report, would you mind sharing the workflow JSON you're experiencing this bug with?  I tried following your repro steps and things seem to save as expected when using an rss trigger and an email action, I'm wondering if there's something else preventing save.

**Comment by hartra344** [comment]
I think this is jsut the issue with dirty state. It looks like the save itself is succeeding just fine.

**Comment by jephlu** [comment]
I will check with another computer, a direct internet access and keep you updated. 
Maybe a proxy / system configuration issue.
Seems strange as the actual editor works fine.

For info I tried to modify the rss trigger interval and the importance for the email step.

**Comment by hartra344** [comment]
@rllyy97 Looks like this is in consumption.

**Comment by jephlu** [comment]
it is a consumption :)

**Comment by hartra344** [comment]
We have a few of these issues related to saving in consumption. Closing this one in favor of tracking in #2041 . Don't worry though, this is still high priority and something that will get fixed. We just want to keep discussion in a single thread.
