### ISSUE TITLE
Creating a Trigger in incorrect location makes it not possible to delete

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#2145]
### Describe the Bug with repro steps

1. Open a workflow with an existing trigger
2. Add an action, filter to see only triggers
3. Add a trigger
4. Try to delete the trigger

### Screenshots or Videos

Clicking Okay does nothing
<img width="1067" alt="stuckDelete" src="https://user-images.githubusercontent.com/95886809/234609443-c31bb899-b74b-415c-9de3-f6ae700f32fe.PNG">

### Browser

Edge

**Comment by preetriti1** [comment]
@Eric-B-Wu - Firstly is this allowed in the GA designer, if not we should do the same, if it is allowed is it changed to apiconnectionwebhook action?
