### ISSUE TITLE
Token Picker `/` shortcut dismiss issues

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#2156]
### Describe the Bug with repro steps

When inputting a `/` character and the dynamic input shortcut menu appears, the only way to dismiss it is when you click one of the options like expected or you input a space.  If you are just typing a path like `/folder/path`, the popup does not disappear.
We should hide on blur at the least

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/25409734/234910042-5d54296b-4fa9-4a87-8809-3097054b0906.png)

### Browser

Chrome

**Comment by Eric-B-Wu** [comment]
@hartra344 can I just make it so the lookahead checks the last character to be a /, otherwise hide it?

**Comment by hartra344** [comment]
I think that would be fine
