### ISSUE TITLE
Designer_Action issue with 3 dot options.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2161]
### Describe the Bug with repro steps

1. Create a project in VS Code and add a stateful workflow.
2. Add http trigger and add compose action.
3. On Right hand above side, Click on 3 dots.
4. On Clicking, 2 options : Add a note AND Delete options, Click on Add a note.
5. Again having 3 dots, try to click on it.

Actual: At step5 , On clicking, The options are blinking.
![image](https://user-images.githubusercontent.com/92098490/234936174-0751e75e-1008-4b62-99c9-f56966f2abe2.png)

Expected: Options should be present or as per expected.

### Browser

VS Code

### Additional context

VS Code extension - ​[vscode-azurelogicapps-2.9.1.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEeCFf1muUWFPjhfP4LMQa0sBCPN6I19Z5AlVW4BoZ5zq0w%3Fe%3DtkIUNS&data=05%7C01%7Cv-prakumar%40microsoft.com%7C7f683b2c36ed4f7e939608db46f5d5b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638181793955221647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uKixZ974p1V2ptXXAySK7hnSHNoaYLaDZ4ZY7K6DLe0%3D&reserved=0)
NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyMDcxNTQ1L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyMDcxNTQ1L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.1.nupkg&data=05%7C01%7Cv-prakumar%40microsoft.com%7C7f683b2c36ed4f7e939608db46f5d5b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638181793955221647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=an1Tk9XNPo5eT2s75m%2Fsu67gCPLzXHt4Eu79YJqf3cU%3D&reserved=0)
Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-prakumar%40microsoft.com%7C7f683b2c36ed4f7e939608db46f5d5b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638181793955378668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xyxwDHzArITHehBkl1tTWPqluhTftWAaSuyGl7pxHSw%3D&reserved=0)
Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.19.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.19.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.19.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.19.1_any-any.zip&data=05%7C01%7Cv-prakumar%40microsoft.com%7C7f683b2c36ed4f7e939608db46f5d5b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638181793955378668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LrMVse%2F77xoqo3GrJv3AVOOtsh20KKB7rcKCYDkjaFY%3D&reserved=0)

**Comment by ccastrotrejo** [comment]
This also happens in general designer, not just in vscode. While the comment box is empty, tooltips show and immediately disappear. 

https://user-images.githubusercontent.com/102700317/235512034-f6ec4d86-7087-41f0-ac15-d5333cdac0bf.mov

**Comment by Eric-B-Wu** [comment]
This might be happening because of some ally changes so that when there is no comment there, it'll refocus on the commentbox (line 48) in panelheadercomment.tsx
