### ISSUE TITLE
VS Code_HTTP Webhook_Request callback URL is not generating after debug, i.e. NULL.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2163]
### Describe the Bug with repro steps 

**Workflow in Portal:**

 1\.Create a stateful workflow in standard LA.

 2\.Add Http trigger and compose action.

 3\.Add Http action: Method\_Post , URI\_Body token , Body\_compose token. Save it.

**VS Code workflow:**

 1\.Create a stateful workflow in VS Code.

 2\.Add HTTP webhook as a trigger and action also.

 3\.For both trigger and action at step2, Method\_Post , URI\_Portal url , Body\_Callback token , save it.

 4\.Debug it.

**Actual:** Workflow is not triggered.

**Expected:** Should be triggered after debugging.

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

VS Code

### Additional context 

AB#24190867

**Comment by preetriti1** [comment]
@v-prakumar - Can you please check if this is still an issue with production portal and production vsix extension?
If not please close this issue.

**Comment by v-prakumar** [comment]
@preetriti1 @ccastrotrejo Issue is same in Production vsix 2.18.3

**Comment by v-prakumar** [comment]
@ccastrotrejo issue repro in vsix 2.24.6

**Comment by v-prakumar** [comment]
@ccastrotrejo issue is repro in vsix 2.28.3

**Comment by v-prakumar** [comment]
@ccastrotrejo repro in vsix 2.45.3

**Comment by v-prakumar** [comment]
@ccastrotrejo issue is repro in vsix 2.55.1

**Comment by vgouth** [comment]
Issue repro in the latest request.

1.VS Code extension - vscode-azurelogicapps-2.58.0.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc4MzA5NDU2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.36.3.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc4MzA5NDU2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.36.3.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YbUQGX1JIg4zw8dJj3tXaSQ1UvYGHZoesH4PqdR3ir0%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iTF28R1F1CAdbvqFM1XoCLdADsc09X7HLH2v22QsIpc%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.36.3/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.36.3_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.36.3%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.36.3_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HnqMsrbHp0z5Arf04tfU0ktLF%2FIFr2p48GDG0%2FVDs6s%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/acba2460-b1b2-4426-9106-14beacd4c056)

**Comment by vgouth** [comment]
Issue repro in the latest VS code request

**1.VS Code extension** - [vscode-azurelogicapps-2.63.3.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/EZqLPbe1WcBImD7iTJtkJcUB2XzuY0npAYSBrz3t9VzjAg?e=JLTViK&xsdata=MDV8MDF8di1nb3Z1YmlsaXNoQG1pY3Jvc29mdC5jb218MzZjZGIyM2QzYWYwNDgyODgxZGIwOGRiYWY3ZDViYTN8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODI5NjcyNTI1Mzc3OTM0NnxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=cFFqeE9NdWxDYjlqelRuNTh0NDhUQUE2dDBkMmNGTWlPUFA4Z0dpWjlxZz0%3d)
**2.NuGet package:** [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc5MjQ0MDM5L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.38.2.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc5MjQ0MDM5L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.38.2.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7C98cd3820f24a4770f31208dbaf01c3ad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638296194454108856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GFclQ81vlVvol1jJN%2FOrQpXJQIh9UQsiD%2FBSqm0mwRE%3D&reserved=0)
**3.Extension Bundle (CDN URL):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7C98cd3820f24a4770f31208dbaf01c3ad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638296194454108856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t38EnCXtrvwpoMOdkKBpkUGcMssK%2B5JsTxCUiun62Ls%3D&reserved=0)
**4.Extension Bundle (Direct Download):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.38.2/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.38.2_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.38.2%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.38.2_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C98cd3820f24a4770f31208dbaf01c3ad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638296194454108856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bq4GFeOnQoVNkZazW%2BEzVnBOBTzjoLKqxfzlmBHj1D4%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/8f07e1b3-33d8-488e-8f42-e829c0e7b2cb)

**Comment by ramya894** [comment]
Issue repro in the latest VS code request
1. **VS Code extension** - ​vsix icon[ vscode-azurelogicapps-2.69.0.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/EeRUYYoqyrZPtK9ZvXk0xcQBG35zXPOj8q8xsyuAvEOuTw?e=H37L8f&xsdata=MDV8MDF8di1pdHJhbXlhQG1pY3Jvc29mdC5jb218NzcxMDUzYTlmNjlkNDdiNmY2NGYwOGRiYmU3NDc3ZWZ8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODMxMzE3OTc5NDc4MTkyOHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=dnkrNWRuVG5SeDdERzczKytmQndHT2dnYVoxL2pxSGNZdGN3N2l6U1Jtbz0%3d)
2. **NuGet package**:  [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgwMDY5MTEwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.41.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgwMDY5MTEwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.41.1.nupkg&data=05%7C01%7Cv-itramya%40microsoft.com%7C771053a9f69d47b6f64f08dbbe7477ef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313179794781928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ymj56rbMX%2F0vgVr8%2BDoKhjK0yx7v7hutYHCOLB46h2E%3D&reserved=0)

3. **Extension Bundle (CDN URL**): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-itramya%40microsoft.com%7C771053a9f69d47b6f64f08dbbe7477ef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313179794938189%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LN05tKhDhEugr5DVtNCh38Td%2F7YRlfTGWEn0hBZqCdg%3D&reserved=0)

4. **Extension Bundle (Direct Download):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.41.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.41.1_any-any.zip</p](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.41.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.41.1_any-any.zip%253c%2Fp&data=05%7C01%7Cv-itramya%40microsoft.com%7C771053a9f69d47b6f64f08dbbe7477ef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313179794938189%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4vRf8N9oT3SsNxkcZY%2B8STbftVvmaOcUYJWvknTUR3E%3D&reserved=0)>


![image](https://github.com/Azure/LogicAppsUX/assets/52390408/fb95b788-a3f5-446e-9e73-00ba148ee857)

**Comment by ramya894** [comment]
Issue repro in the latest request.

VS Code extension - ​​vsix icon[ vscode-azurelogicapps-2.72.1.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/EfKWqLA0W0ZEvopnY8wo_tkBY9WSkRtgWk-niBfAd47iPw?e=ohFYeL&xsdata=MDV8MDF8di1pdHJhbXlhQG1pY3Jvc29mdC5jb218MWY4ZWNjOWQwMTMwNGI2N2E0ZGYwOGRiY2YzN2ZhZGF8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODMzMTYxMTgxMjIxOTAyMnxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=VUxqbU9kQ1VKV2ZmbFgvbFhnMExMUHVnQlE4TE1mVHRmYjdmOXhGNG5tVT0%3d)

NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgxMTY0NTE3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.44.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgxMTY0NTE3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.44.1.nupkg&data=05%7C01%7Cv-itramya%40microsoft.com%7Cae053676d4a4467f085308dbcee1c051%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638331241613333478%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=whaLLdJIMjsic5AHmCk6Xb4GDEnNzQdbhbmd7AYE66o%3D&reserved=0)

Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-itramya%40microsoft.com%7Cae053676d4a4467f085308dbcee1c051%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638331241613343570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p0LTFBnMqK0OtC0tKtfn3DUiGfH9UT6wd0kzurKV1po%3D&reserved=0)

Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.44.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.44.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.44.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.44.1_any-any.zip&data=05%7C01%7Cv-itramya%40microsoft.com%7Cae053676d4a4467f085308dbcee1c051%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638331241613350230%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xir1h2Cqma1OrxIQHPS7EZ5mrVoth9%2BjUtVWPAH1auQ%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/0d7c6727-f5ed-4779-a89e-b7f9fac472a9)

**Comment by ramya894** [comment]
Issue repro in the latest request.

VS Code extension: 2.81.0

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/37ce355a-56f6-4d3f-ae33-b3f754e8448a)

**Comment by ramya894** [comment]
Issue repro in latest vsix version.
VS Code extension: 2.99.0

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/8aa839df-7544-460e-a233-0b73a1ba9411)

**Comment by ramya894** [comment]
Issue repro in latest vsix version.
Bundle version: 1.58.3

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/c622dff5-a7da-40e8-b039-5eef6d4761b3)

**Comment by ramya894** [comment]
Issue repro in the latest vscode version.

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/d5523be1-a15d-4a93-9021-d5f2755ab73b)

**Comment by ramya894** [comment]
Issue repro in the latest standard portal version.
Version: 2.40205.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/53c1a977-1b13-41aa-a78a-b744b23dac9c)

**Comment by ccastrotrejo** [comment]
Closing this issue as the new scenario doesn't expect the callback to be exposed. We will open this issue and update the test scenario if customers want the callback URL to be exposed.
