### ISSUE TITLE
Node layout sizing resets to defaults on workflow update

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#2175]
### Describe the Bug with repro steps

When a workflow is resubmitted to the designer after a flow has already been processed, the designer resets all node sizes back to their default values (only in our layout algorithm, not in the actual viewport).  
Normally this results in the spacing between nodes becoming much smaller.

___

![image](https://user-images.githubusercontent.com/25409734/235185085-11c5b84b-0bf6-4b08-89d1-bd12c8699196.png)

Turns into => 

![image](https://user-images.githubusercontent.com/25409734/235185020-8c6518d5-341d-4def-85eb-7be6ec7ac176.png)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

**Comment by preetriti1** [comment]
@rllyy97 - Will this help in our rendering in Portal as well or we have to come up with different mechanism to handle this bug.
Current PA team is going to pass an option on designer component on when to not recalculate.
