### ISSUE TITLE
Email addresses separated by comma should work (as suggested by tooltip)

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#2181]
### Describe the Bug with repro steps

Gmail/Outlook all email connectors face the same problem.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/91279975/235252433-671abfa7-f15b-46d5-97d9-fd915784ed4f.png)

### Browser

Chrome

**Comment by preetriti1** [comment]
@kisubedi - The outlook connector specifies it as semicolon and not as comma.

**Comment by preetriti1** [comment]
Closing this issue, as we didnt get any response from you.
