### ISSUE TITLE
Search does not understand more than a few words

### ISSUE THREAD

**Issue by ek68794998** [Azure/LogicAppsUX#2199]
### Describe the Bug with repro steps

1. Open a workflow, new or existing.
2. Click a + to open the search panel.
3. Ensure the connectors have loaded.
4. Type "sharepoint" and ensure that SharePoint connector loads.
5. Change query to "get a file from sharepoint" and observe result.

The search processor (Fuse, I suppose?) doesn't seem to understand the query and just returns back some semi-related results but not even one action from the SharePoint connector. This is just one example, but in general the search processor does not return good results for multi-word searches unless they are exact matches to connector/operation names.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![fuse](https://user-images.githubusercontent.com/1350074/235544828-d9c96a33-49ad-48e3-ba98-753956cd9987.gif)

### Browser

Edge v112.0.1722.58 (Official build) (64-bit), Windows 11 x64.

**Comment by hartra344** [comment]
Generally speaking, it IS searching for exact matches with some fuzzy logic applied. Compared to today where it only searches for exact matches with no fuzzy logic. There are currently no plans for a deeper search

**Comment by ek68794998** [comment]
@hartra344 It makes sense from the perspective of comparing it to exact matches. However, previously, the interface was such that the backend could handle it, which meant the server could do a very powerful fuzzy match on the input (dependent on the host's implementation).

We should perhaps have a sync on this topic next time we meet up, and see if perhaps there's some kind of customization capability we can give to the host to allow deeper control of the search processing. I'm not too familiar with Fuse, admittedly, but maybe there's some potential there.

**Comment by hartra344** [comment]
@ek68794998 There was already discussion previously to move the search functionality to the service post GA. I think that fixes the issue here since at least on our side, there is no powerful fuzzy searching happening on the backend.
