### ISSUE TITLE
Logic App Designer not setting AuthenticationType for Managed Identity connection

### ISSUE THREAD

**Issue by beedyg** [Azure/LogicAppsUX#2203]
### Describe the Bug with repro steps

1. Create new Logic App
2. Enable Managed Identity
3. Use template "When a resource event occurs"
4. Complete details of event (observed for Microsoft.Storage.BlobCreated)
5. Use Managed Identity as connection
6. Save

In Preview the UI presents a save successful message. However in network tab the API returns:
{"error":{"code":"WorkflowManagedIdentityConfigurationInvalid","message":"The workflow connection parameter 'azureeventgrid' is not valid. The API connection 'azureeventgrid' is configured to support managed identity but the connection parameter is either missing 'authentication' property in connection properties or authentication type is not 'ManagedServiceIdentity'."}}
And the changes were not saved

In GA the error message is displayed in the UI.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

Edge

**Comment by preetriti1** [comment]
This work is related to supporting managed identity in connectors which only support single auth, but multiple connection variations.
