### ISSUE TITLE
Cannot add "Call Azure Function" action in VS Code

### ISSUE THREAD

**Issue by gbelenky** [Azure/LogicAppsUX#2204]
Type: <b>Bug</b>

create a standard stateful logic app in VS Code. Add HTTP trigger in the designer with no payload. When adding a new action for calling Azure Function following error message appears:
{"message":"Request failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/gbelenky/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.8.0/webview/main.c78ecb95b324bc72.js:2:244192\n at XMLHttpRequest.u (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/gbelenky/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.8.0/webview/main.c78ecb95b324bc72.js:2:244340)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":""},"method":"get","uri":"/subscriptions/subscriptionId/providers/Microsoft.Web/sites","queryParameters":{"api-version":"2018-11-01"},"url":"undefined/subscriptions/subscriptionId/providers/Microsoft.Web/sites?api-version=2018-11-01"},"code":"ERR_BAD_REQUEST","status":404} 

Extension version: 2.8.0
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.60GB (17.31GB free)|
|Process Argv|--crash-reporter-id a2eacd0b-b43b-4ecc-8d3a-57bca62cf4cd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30730053
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742
fixhidewlkth:30730051

```

</details>

**Comment by ccastrotrejo** [comment]
Hi @gbelenky, I tried to repro your issue and the only way I was able to do it was by not signing in azure and not choosing a connector from azure when I opened the designer. After signing in and choosing a connector from azure I was able to add the `Call Azure Function` action. 

<img width="500" alt="Screenshot 2023-05-02 at 9 45 55 AM" src="https://user-images.githubusercontent.com/102700317/235733815-d6e2e80f-2820-4f57-9f5d-d4e9799cb880.png">

This are the steps you can follow to solve this issue

1. Remove `WORKFLOWS_SUBSCRIPTION_ID` from local.settings.json (if you have it).
2. Right click in the workflow.json and choose `Open Designer`.
3. Click in `Use connector from Azure` option from the wizard.
4. Sign in if needed. 

Please, let me know if you still face this issue after doing the steps and we can reopen the issue and take a further look.
