### ISSUE TITLE
LA STD: Unable to delete a map/schema if its name has a space

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#2209]
### Describe the Bug with repro steps

1. Upload a map which has a space char in its name and it uploads fine.
2. Now try to delete it, you will get 400 error.

Put works because the space is urlencoded

![image](https://user-images.githubusercontent.com/49498706/235810366-611cab1d-6de5-49a6-8f08-d87d7e0e1563.png)

But Delete does not encode the space.

![image](https://user-images.githubusercontent.com/49498706/235810501-56963c26-060d-49a3-b8bb-f515977d2b75.png)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

Chrome

AB#25416705

**Comment by hartra344** [comment]
Fix is in this PR: https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/9176027
