### ISSUE TITLE
Standard : Unable to see Inputs and outputs information/data

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2214]
### Describe the Bug with repro steps

1.Create a Logic apps in  standard add stateful or stateless workflow.
2.Create a workflow into it.
3.Try to save the workflow.
4.After saving the workflow, Run the workflow
5. Open Run history and select a run.
6. Click on any successful trigger or action.

Expected : We should be able to see Inputs and outputs information.

Actual : Unable to see Inputs and outputs data. But when we are clicking on show raw inputs and show raw outputs we are able to see the inputs and outputs.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http",
        "inputs": {
          "method": "POST",
          "relativePath": "/subscription/{subscriptionId}/name/{userName}/user/{userId}"
        }
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/113517384/235985851-a8c84c5c-1c42-43b3-80d9-22b25358286f.png)
![image](https://user-images.githubusercontent.com/113517384/235986250-e2efc6df-30e5-4081-a506-bb80c1256098.png)
![image](https://user-images.githubusercontent.com/113517384/235986164-e84336ac-3394-4463-adaf-8a5a18145ff0.png)

### Browser

Edge

### Additional context

**Environmental Details:**

**URL**: https://aka.ms/emastaging-flowstip1
Version : 2.20501.1.1

**Comment by Eric-B-Wu** [comment]
Hey @ccastrotrejo , this seems like an issue with the new monitoring view getting the inputs/outputs, seems like the call to get it is failing, do you think you can take a look? This will probably need to be cherry-picked to our release branch
