### ISSUE TITLE
Standard : Service provider(In-built) trigger/action testing : Unable to see workflow run after sending message in service bus queue

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2216]
### Describe the Bug with repro steps

1.Create a new Stateful Logic App(Standard) , select service bus trigger under the built-in connectors. 
2.Select "When messages are available in Service Bus queue"
3. Add connection string of service bus.
4. Enter the queuename(test3) in the Queue name parameter.
5. Turn the Split on to off state and click on "Done"
6. Add "Send message" action from the service bus built-in action as below and use the 2nd queue(test4) as the queue input parameter and content from the "messages content" from the trigger. It will automatically add a foreach loop as it’s a batch trigger.
7. Save the workflow .
8. Send a message to the "test3" queue, From the namespace go to the queue, click on queues -> test3 queue 
9. Select content type "Text/plain", add message details and hit send.

**Expected :** Check the workflow run, it should succeed.
**Actual :** Unable to see workflow run after sending message in service bus queue

**NOTE:** You should NOT use "Run Trigger" on the logic app workflow. The trigger used above is automatically triggered when a message is in the service bus queue, if you use the manual "Run Trigger", you will see a failed run because the workflow will not have message content.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "For_each": {
        "type": "foreach",
        "foreach": "@triggerBody()",
        "actions": {
          "Send_message": {
            "type": "ServiceProvider",
            "inputs": {
              "parameters": {
                "entityName": "test4"
              },
              "serviceProviderConfiguration": {
                "connectionName": "serviceBus",
                "operationId": "sendMessage",
                "serviceProviderId": "/serviceProviders/serviceBus"
              }
            }
          }
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_messages_are_available_in_a_queue": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "queueName": "test3",
            "isSessionsEnabled": false
          },
          "serviceProviderConfiguration": {
            "connectionName": "serviceBus",
            "operationId": "receiveQueueMessages",
            "serviceProviderId": "/serviceProviders/serviceBus"
          }
        },
        "splitOn": "@triggerOutputs()?['body']"
      }
    }
  },
  "connectionReferences": {
    "serviceBus": {
      "connection": {
        "id": "/serviceProviders/serviceBus/connections/serviceBus"
      },
      "connectionName": "abc",
      "api": {
        "id": "/serviceProviders/serviceBus"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/113517384/236001272-a85ec978-8ae4-4f11-935e-ffaa0fae5b30.png)

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** https://aka.ms/emastaging-flowstip1
**Version :** 2.20501.1.1

**Comment by vgouth** [comment]
Issue repro in the latest release.

**Environment Details:**
URL: https://aka.ms/emastaging-flowstip1
Version: 2.30508.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/43f47539-87e5-49ae-8fbb-62ca6d9878ba)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/78e4b5b4-463f-46ef-8d22-b2167639ba57)

**Comment by preetriti1** [comment]
@vgouth - Please check if it is present in latest staging, if yes then we will move this to backend.

**Comment by vgouth** [comment]
@preetriti1 . Issue **not repro** in the latest stating environment hence closing this issue.

**Environment Details:**
**URL:** [https://aka.ms/emastaging](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C3969f52d0c944a23d6d708db63335524%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638212844425552141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ycb%2F2p%2Fvf0TgoegxCPo%2FcLQJadqDgOEHOQkCPed5AfM%3D&reserved=0)
Version: 2.30529.1.4

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/30f80e17-c00f-4bf6-94f1-8f3ea8e31494)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/0a1b47ed-381f-403d-8dfe-1edeb8301134)
