### ISSUE TITLE
Standard_ Workflow parameters : Not able to see  the confirmation popup, it is directly closing the panel with parameters name as empty. 

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2223]
### Describe the Bug with repro steps

1. Create a new stateful logic app in standard, open the designer.
2. Validate if 'Parameters' command button shows
3.  **Expected:** Keep some parameter names empty and try closing the panel. You should see below UI with a popup stating the confirmation to close the panel. 
**Actual:** Not able to see the confirmation popup, it is directly closing the panel.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "connectionReferences": {},
  "parameters": {
    "a": {
      "type": "Array",
      "value": [
        1,
        2
      ]
    },
    "b": {
      "type": "Bool",
      "value": true
    },
    "": {
      "type": "Array"
    }
  }
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/113517384/236105781-bdcce233-a6e0-459b-a23b-08f85b0ddf62.png)

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** https://aka.ms/emastaging 
**Version :** 2.20501.1.1

**Comment by vgouth** [comment]
Issue repro in the latest request:

**Environment Details:**
**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C8688f3d5cccf402a38e708db51fe6235%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638193925280493316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BXBSqbVf%2FicM7ZJKIscX6dePWq%2ByCA%2F9nvsgOlU5Ptc%3D&reserved=0)
**Version:** 2.30508.1.1

**Comment by vgouth** [comment]
**Issue repro in latest artifact.**

1.	VS Code extension –   vscode-azurelogicapps-2.15.15.vsix
2.	NuGet package: https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczMDA5ODA5L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.21.3.nupkg
3.	Extension Bundle (CDN URL): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting
4.	Extension Bundle (Direct Download): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.21.3/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.21.3_any-any.zip
5. Resources vsix.   vscode-azureresourcegroups-LA.vsix

**Comment by rllyy97** [comment]
We have decided to not use the confirmation pop-up in new-designer, instead showing the red error dot on the command bar button when there are errors.  I have updated our testing case in accordance.
