### ISSUE TITLE
Standard_ Workflow parameters : After adding some new parameters save button is in disable state instead of enable

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2226]
### Describe the Bug with repro steps

1.Create a new stateful logic app in standard, open the designer.
2.Validate if 'Parameters' command button shows
3. Add some parameters , save and run the workflow.
4. **Expected:** Adding new parameters in parameters panel after running the workflow, Save button should be enabled.
**Actual:** After adding some new parameters save button is in disable state instead of enable.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Response": {
        "type": "Response",
        "kind": "Http",
        "inputs": {
          "statusCode": 200
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {
    "a": {
      "type": "Array",
      "value": [
        1,
        2
      ]
    },
    "b": {
      "type": "Bool",
      "value": true
    },
    "c": {
      "type": "Int",
      "value": 123
    },
    "d": {
      "type": "String",
      "value": "abcdef"
    }
  }
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/113517384/236110834-3d123c05-27db-4f60-b080-98afbfc841d1.png)

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** https://aka.ms/emastaging
**Version :** 2.20501.1.1

**Comment by vgouth** [comment]
**NOTE:** If we are making any changes in workflow save button is getting enable. But Save is not enabling if we are making changes in parameters panel(adding new parameters or editing the existing parameters).

**Comment by rllyy97** [comment]
Fixed outside of this repo, will be live with our next release
