### ISSUE TITLE
Standard_ Workflow parameters : There is change in view of parameters in read only mode and edit mode. Array parameters is not showing in brackets(in both edit and read only mode) and boolean value is not shown in read only mode.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2227]
### Describe the Bug with repro steps

1.Create a new stateful logic app in standard, open the designer.
2.Validate if 'Parameters' command button shows
3.Add some parameters, save and run it.
4.After creating some parameters, the parameters should continue to be shown in the parameters panel. Open up the parameters panel. The parameters should be in read-only mode. Click on the name of the parameter to expand.
**Expected:** Parameters should be in orginal mode.
**Actual:** There is change in view of parameters in read only mode and edit mode. Array parameters is not showing in brackets( both edit and read only mode) and boolean value is not shown in read only mode.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Response": {
        "type": "Response",
        "kind": "Http",
        "inputs": {
          "statusCode": 200,
          "body": "@parameters('a')"
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {
    "a": {
      "type": "Array",
      "value": [
        1,
        2
      ]
    },
    "b": {
      "type": "Bool",
      "value": true
    },
    "c": {
      "type": "Int",
      "value": 123
    },
    "d": {
      "type": "String",
      "value": "abcdef"
    }
  }
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/113517384/236111699-16d11a98-1b33-41eb-833f-3958f9059ea0.png)
![image](https://user-images.githubusercontent.com/113517384/236111798-78795b5f-00ed-4a40-be43-7784ea6cdfab.png)

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** https://aka.ms/emastaging
**Version :** 2.20501.1.1

**Comment by preetriti1** [comment]
Functionally it is not changing the value, this is just display issue.

**Comment by vgouth** [comment]
Issue repro in the latest request:

**Environment Details:**
**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C8688f3d5cccf402a38e708db51fe6235%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638193925280493316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BXBSqbVf%2FicM7ZJKIscX6dePWq%2ByCA%2F9nvsgOlU5Ptc%3D&reserved=0)
**Version:** 2.30508.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/032fde3d-d4d6-49d9-ac82-e6d40c13ed83)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/a2450453-2fd1-4502-9b88-adde8551930a)

**Comment by vgouth** [comment]
**Issue repro in latest artifact.**

1.	VS Code extension –   vscode-azurelogicapps-2.15.15.vsix
2.	NuGet package: https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczMDA5ODA5L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.21.3.nupkg
3.	Extension Bundle (CDN URL): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting
4.	Extension Bundle (Direct Download): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.21.3/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.21.3_any-any.zip
5. Resources vsix.   vscode-azureresourcegroups-LA.vsix
