### ISSUE TITLE
Standard_ Workflow parameters : Edit in JSON' link not found at the bottom of the parameters panel

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2228]
### Describe the Bug with repro steps

1.Create a new stateful logic app in standard, open the designer.
2.Validate if 'Parameters' command button shows
3.Add some parameters, save and run it.
4.**Expected:** Click on the link 'Edit in JSON', found at the bottom of the parameters panel.
**Actual:'** Edit in JSON' link not found at the bottom of the parameters panel

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Response": {
        "type": "Response",
        "kind": "Http",
        "inputs": {
          "statusCode": 200,
          "body": "@parameters('a')"
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {
    "a": {
      "type": "Array",
      "value": [
        1,
        2
      ]
    },
    "b": {
      "type": "Bool",
      "value": false
    },
    "c": {
      "type": "Int",
      "value": 123
    },
    "d": {
      "type": "String",
      "value": "abcdef"
    }
  }
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/113517384/236112432-f0154f6a-71cb-414d-a562-14d3214acd9f.png)

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** https://aka.ms/emastaging
**Version :** 2.20501.1.1

AB#24278647

**Comment by vgouth** [comment]
Issue repro in the latest request:

**Environment Details:**
URL: [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cb13bdbce753c4d10e4d208db602642f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638209489719398144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ouKhkhxrFJJr2RCOpHP%2F3nqcaTagt7jkAg8FKOmhWRU%3D&reserved=0)
**Version**: 2.30529.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/94dcb4ad-2bf6-4fce-83ab-133c38aa845d)

**Comment by vgouth** [comment]
Issue repro in the latest request:

**Environment Details:**
**URL:** https://aka.ms/emastaging-flowstip1
**Version:** "2.30613.1.2"

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/4851af49-589c-47f7-b495-b45de1e6e40e)

**Comment by vgouth** [comment]
Issue repro in the latest request:

**Environment Details:**
**URL:** https://aka.ms/emastaging-flowstip1
**Version:** "2.30701.1.1"

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/a1e9a391-83d5-464f-bf80-4d9d931099fb)

**Comment by vgouth** [comment]
Issue repro in the latest request:

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccaeede01bc6247df730608db899fa56e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638255091053826394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XkVfWg4QCG8m1pHWR2lnWsaUSDKt3WPkUseVXK7UwVY%3D&reserved=0)
**Version:** 2.30717.1.1

**Comment by vgouth** [comment]
Issue repro in the latest request:

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C25ee41df62d44438790c08db937727d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638265912263218130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ExdI18ub8D3V7ulDw4BDJPTB28t6zLoS8UczXvO%2FLFw%3D&reserved=0)
 
**Version:** 2.30731.1.4

**Comment by vgouth** [comment]
Issue repro in the latest request. Looks like the issue is not fixed in this request version.

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C08587520e7324008a23608db9d720c7f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638276885447380759%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=etlI5s6BaGn77nqLx5H9zxtbj797x8RnC1ZNmMz8rjQ%3D&reserved=0)
**Version:** 2.30814.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/bf853dfe-461f-4751-8cb6-ca7ae72f356b)

**Comment by Eric-B-Wu** [comment]
please wait until next release where this change will be included. If it still remains, we can reopen issue

**Comment by vgouth** [comment]
@Eric-B-Wu 
Issue **not** repro in the latest request. 

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C0d580ab2c89a42dc016008dba7ed8e66%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638288411002715886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fu55XoDuvHmk7oTqniTKCewpJdR%2Br5Qtx5EQN0rKShc%3D&reserved=0)
**Version:** 2.30828.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/0d61f28b-6d0b-4f32-8572-f6044d27b648)
