### ISSUE TITLE
Cannot select schemas as existing scource/target schema.

### ISSUE THREAD

**Issue by simonstender** [Azure/LogicAppsUX#2231]
### Describe the Bug with repro steps

When trying to select my schemas under Artifacts/Schemas/ when creating a new data mapper I cannot select the schemas that I have put in my schemas folder.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/37075113/236238412-647cdfe4-737c-4a28-9b40-957d6cb26ef8.png)

This is my folder structure
![image](https://user-images.githubusercontent.com/37075113/236238614-20049ffb-3ce0-4ab5-9a8f-9febca1d8477.png)

My local.settings.json
![image](https://user-images.githubusercontent.com/37075113/236238898-5476e2e6-bb79-4f7b-b033-51788d07bbc3.png)

### Version

2.3.0

### Additional context

I have Azure Functions Core Tools version 4, and Node v14.

**Comment by simonstender** [comment]
If I move the Artifacts folder to the root folder it works.
Is it possible to change the root folder for the mapper extension?

**Comment by DanielleCogs** [comment]
This is by design. All schemas need to be in 'root'/Artifacts/Schemas or 'root'/Artifacts/Schemas/{subfolder}. We can add some additional messaging around this to make it more clear.
