### ISSUE TITLE
Cannot configure the concurrency control for the for-each loop

### ISSUE THREAD

**Issue by alessandromoura** [Azure/LogicAppsUX#2240]
### Describe the Bug with repro steps

When working with the VS Code designer, we can't find in the for-each action, the setting to change the concurrency control anymore.

The version of the extension we used in VS Code that have this issue is 2.8.0. We rolled back to version 2.0.16 to have it working again.

1. Create a workflow
2. Add a for-each action
3. Go to settings and try to find the concurrency setting

See at the attached picture for what we see today in VS Code and what we see in the old designer or in the portal.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1376498/236350967-d3d25355-e477-4ac7-ac81-67768f2a9410.png)
![image](https://user-images.githubusercontent.com/1376498/236350995-db501262-9739-469b-a7ff-b576169fb2b9.png)

### Browser

Edge

**Comment by deepakdabbiru64** [comment]
Same issue happening with me as well. Latest extension version is not showing the Concurrency Control setting

**Comment by rllyy97** [comment]
Hi @alessandromoura, @deepakdabbiru64,
Thank you for reporting this issue, I just wanted to update you that this has been fixed and will be rolling out with our next release between May 8-12th.  If you are still running into any concurrency issues following our release please let us know!
