### ISSUE TITLE
Using @appsetting references fails validation

### ISSUE THREAD

**Issue by Viktorh89** [Azure/LogicAppsUX#2242]
### Describe the Bug

While using @appsetting references in scenarios such as Condition, Switch cases or Trigger settings (interval/frequency) causes validation to fail, but workflow is saved successfully, this can cause weird and unexpected behaviour.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Add @appsetting reference to switch case or trigger interval/frequency (probably more places)
2. Save Workflow and get validation failures

### Workflow JSON

```json
"triggers": {
      "When_one_or_more_messages_are_received_from_a_queue_(auto-complete)": {
        "inputs": {
          "parameters": {
            "includeInfo": true,
            "queueName": "@appsetting('int002bmqreceive')"
          },
          "serviceProviderConfiguration": {
            "connectionName": "mq",
            "operationId": "pollMessages",
            "serviceProviderId": "/serviceProviders/mq"
          }
        },
        "kind": "Polling",
        "recurrence": {
          "frequency": "@appsetting('int002b_mq_frequency')",
          "interval": "@appsetting('int002b_mq_interval')"
        },
        "splitOn": "@triggerOutputs()?['body']?['messages']",
        "type": "ServiceProvider"
      }
    }
```

AB#24832184

**Comment by preetriti1** [comment]
I dont think the designer (old) one also supported it or recognized such expressions. This will be a feature request.

**Comment by randiratnayake** [comment]
@preetriti1 I disagree. I have working workflows with parameterized queue names and switches, and conditions.

```json
"triggers": {
            "When_messages_are_available_in_a_queue": {
                "inputs": {
                    "parameters": {
                        "queueName": "@parameters('DemoQueueName')"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "azurequeues",
                        "operationId": "receiveQueueMessages",
                        "serviceProviderId": "/serviceProviders/azurequeues"
                    }
                },
                "type": "ServiceProvider"
            }
        }
```

However, as of this week, I can't edit the workflow using Designer because it complains of a validation error like the one below;
![image](https://github.com/Azure/LogicAppsUX/assets/25071773/67327e7b-6ba4-4224-8547-2a8de36e6803)

I can still edit the workflow using the code view, and it still confirms that my workflows are running. It's just the UI doesn't allow it to be saved because of this validation error.

**Comment by lowrey2142** [comment]
> @preetriti1 I disagree. I have working workflows with parameterized queue names and switches, and conditions.
> 
> ```json
> "triggers": {
>             "When_messages_are_available_in_a_queue": {
>                 "inputs": {
>                     "parameters": {
>                         "queueName": "@parameters('DemoQueueName')"
>                     },
>                     "serviceProviderConfiguration": {
>                         "connectionName": "azurequeues",
>                         "operationId": "receiveQueueMessages",
>                         "serviceProviderId": "/serviceProviders/azurequeues"
>                     }
>                 },
>                 "type": "ServiceProvider"
>             }
>         }
> ```
> 
> However, as of this week, I can't edit the workflow using Designer because it complains of a validation error like the one below; ![image](https://user-images.githubusercontent.com/25071773/260338870-67327e7b-6ba4-4224-8547-2a8de36e6803.png)
> 
> I can still edit the workflow using the code view, and it still confirms that my workflows are running. It's just the UI doesn't allow it to be saved because of this validation error.

I second @randiratnayake comments.

When I used the designer on Sunday 6th August, I didn’t have this issue. I tried to edit the same flow on Thursday 10th, and I am getting the same Operations error.

<img width="2347" alt="logic app issue" src="https://github.com/Azure/LogicAppsUX/assets/42722206/14922b2d-333f-416d-8e18-546e4dc6dd63">

```json
 "Switch": {
                "cases": {
                    "other": {
                        "actions": {},
                        "case": "Other"
                    },
                    "rbac": {
                        "actions": {},
                        "case": "RBAC"
                    },
                    "read": {
                        "actions": {},
                        "case": "Read"
                    }
                },
                "default": {
                    "actions": {}
                },
                "expression": "@variables('var-prem-prefix')",
                "runAfter": {
                    "create_var-prem-prefix": [
                        "SUCCEEDED"
                    ]
                },
                "type": "Switch"
            }

 ```
I’m also experiencing the same behaviour. I’m able to edit and save the flow using code. The workflow executes without issues. However, when I try and edit using the designer. I get the Operations error.

I may be worth noting that the error only starts after I have added the Switch and cases (using the designer) AND relaunch the designer. If add the switch and cases and continue to work within the same designer session, all subsequent saves work without the Operations error.

lastly, when I get the error and click “Open Operations” it fails to load.

Mike.
