### ISSUE TITLE
VS Code: Unable to find create a new logic app option while deploying a workflow.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2268]
### Describe the Bug with repro steps

1.Create a new workflow app using VS Code.
2.Create a stateful/stateless workflow
3.Open the workflow.json file in designer and author a new workflow. 
4.Save, debug and run it.
5.Deploy to azure
6. **Expected:** Should able to find create a new logic app option while deploying a workflow.
**Actual:** Unable to find create a new logic app option while deploying a workflow.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "Http",
                "inputs": {
                    "statusCode": 200
                },
                "runAfter": {
                    "Send_an_email_(V2)": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Compose": {
                "type": "Compose",
                "inputs": "Testing vs code bundle",
                "runAfter": {}
            },
            "Send_message": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "entityName": "test",
                        "message": {
                            "contentData": {
                                "a": "b"
                            }
                        }
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "serviceBus",
                        "operationId": "sendMessage",
                        "serviceProviderId": "/serviceProviders/serviceBus"
                    }
                },
                "runAfter": {
                    "Compose": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Send_an_email_(V2)": {
                "type": "ApiConnection",
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "office365-2"
                        }
                    },
                    "method": "post",
                    "body": {
                        "To": "v-govubilish@microsoft.com",
                        "Subject": "Testing vs code bundle",
                        "Body": "@{outputs('Compose')}",
                        "Importance": "Normal"
                    },
                    "path": "/v2/Mail"
                },
                "runAfter": {
                    "Send_message": [
                        "SUCCEEDED"
                    ]
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/113517384/236800002-95300072-7673-4d84-a1a3-bc1e6274bb0b.png)

### Browser

VS Code

### Additional context

**Artifacts Version:**

1.	VS Code extension -     vscode-azurelogicapps-2.15.10.vsix
2.	NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyNDMyOTY3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.4.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyNDMyOTY3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.4.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7C427bbf6f59c54bbe066a08db4f9cf9cb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638191307909866207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VngtqpWk73oX9kofV%2FWkP8sqQqmJzVur2tSXw6rEZ4Q%3D&reserved=0) 
3.	Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7C427bbf6f59c54bbe066a08db4f9cf9cb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638191307909866207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FJ2Gjo3gCTS%2BBXM08BqsFbpUJkpl%2Fp8pw0xqNDDKF5k%3D&reserved=0) 
4.	Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.19.4/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.19.4_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.19.4%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.19.4_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C427bbf6f59c54bbe066a08db4f9cf9cb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638191307909866207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XKle%2Bvguxwt%2FS%2BkvZ9HJvbI%2B1oGfrx4L%2BiHGYSX5Y9A%3D&reserved=0)
5. private Resources vsix.  
  vscode-azureresourcegroups-LA.vsix

**Comment by ccastrotrejo** [comment]
Going to close this since this is the behaviour for the new resources implementation, however I will look/track if this can be a feature in the [vscode-azuretools](https://github.com/microsoft/vscode-azuretools) repo
