### ISSUE TITLE
Logic Apps Preview Dataverse Connector

### ISSUE THREAD

**Issue by berellax** [Azure/LogicAppsUX#2283]
### Describe the Bug

When opening an existing workflow that contains Dataverse actions in the Preview Editor, any parameters that are included - such as setting fields in a create/update row action - are lost. When saving the workflow, the JSON is updated to remove the body.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create a workflow in GA Designer
2. Add a Dataverse action with a body (i.e. Add Row and set fields).
3. Set fields in the action and save.
4. Convert to Preview Designer
5. Open the Dataverse action - the field mappings are gone.
6. Save the workflow - the JSON updates without the mappings. 
7. The same occurs in VS Code using the preview designer

AB#21571634

**Comment by preetriti1** [comment]
@berellax - can you please put a screenshot on what you are viewing in Preview designer, which mappings are gone. It is not clear  if the input fields are not visible or there is a change in how the value in those fields are viewed.

Currently with our latest changes (not in production yet) we can see all fields to be present.

**Comment by berellax** [comment]
@preetriti1 

Here's a screenshot from VS Code which is using the preview designer. As you can see, there are no parameters on the dataverse connection anymore.

![image](https://github.com/Azure/LogicAppsUX/assets/3051136/78f3ba11-9c20-4fd8-9e29-68d0e71bfc4e)

Here's a before and after JSON where the entire body object is dropped. I'm seeing the exact same behavior on the portal.

**Before**
"Update_Lead": {
                                                "inputs": {
                                                    "body": {
                                                        "address1_city": "@outputs('Address_City')",
                                                        "address1_line1": "@outputs('Address_Street')",
                                                        "address1_postalcode": "@outputs('Address_Zip')",
                                                        "address1_stateorprovince": "@outputs('Address_State')",
                                                        "address1_telephone1": "@variables('homePhone')",
                                                        "address1_telephone2": "@variables('businessPhone')",
                                                        "emailaddress1": "@outputs('Email_Address')",
                                                        "firstname": "@outputs('First_Name')",
                                                        "lastname": "@outputs('Last_Name')",
                                                        "mobilephone": "@variables('mobilePhone')",
                                                        "subject": "@triggerBody()?['subject']",
                                                        "telephone1": "@variables('businessPhone')",
                                                        "telephone2": "@variables('homePhone')",
                                                        "waepa_agency@odata.bind": "@outputs('Agency_Lookup')",
                                                        "waepa_birthdate": "@outputs('Birthday')",
                                                        "waepa_employedsince": "@outputs('Employed_Since')",
                                                        "waepa_gendercode": "@outputs('Lead_Gender_Code')",
                                                        "waepa_interests": "@outputs('Interest_Categories')",
                                                        "waepa_leaddate": "@outputs('Lead_Date')",
                                                        "waepa_leadsource": "@outputs('Lead_Source')",
                                                        "waepa_productsubcategories": "@outputs('Products')",
                                                        "waepa_retired": "@outputs('Retired')"
                                                    },
                                                    "headers": {
                                                        "accept": "application/json;odata.metadata=full",
                                                        "organization": "https://waepa.crm.dynamics.com",
                                                        "prefer": "return=representation,odata.include-annotations=*"
                                                    },
                                                    "host": {
                                                        "connection": {
                                                            "referenceName": "commondataservice"
                                                        }
                                                    },
                                                    "method": "patch",
                                                    "path": "/api/data/v9.1/@{encodeURIComponent(encodeURIComponent('leads'))}(@{encodeURIComponent(encodeURIComponent(body('Lead_Lookup_JSON')?['recordId']))})"
                                                },
                                                "runAfter": {},
                                                "type": "ApiConnection"
                                            }

**After**

"Update_Lead": {
                                                "type": "ApiConnection",
                                                "inputs": {
                                                    "host": {
                                                        "connection": {
                                                            "referenceName": "commondataservice"
                                                        }
                                                    },
                                                    "method": "patch",
                                                    "headers": {
                                                        "prefer": "return=representation,odata.include-annotations=*",
                                                        "accept": "application/json;odata.metadata=full",
                                                        "organization": "https://waepa.crm.dynamics.com"
                                                    },
                                                    "path": "/api/data/v9.1/@{encodeURIComponent(encodeURIComponent('leads'))}(@{encodeURIComponent(encodeURIComponent(body('Lead_Lookup_JSON')?['recordId']))})"
                                                }
                                            }

**Comment by preetriti1** [comment]
@berellax - Can you once again try our scenario in Portal and confirm if this is still an issue, we are currently rolling out and it should complete by mid next week.

**Comment by preetriti1** [comment]
@ccastrotrejo - Please close this issue once extension is updated with latest designer.

**Comment by ccastrotrejo** [comment]
Hi @berellax could you please retry this in the newest vscode extension? Please let me know if this keeps happening and I can take a further look on this.
