### ISSUE TITLE
VS Code Azure Blob

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2294]
### Describe the Bug with repro steps

1.Create a project and add Stateful workflow in VS Code.
Add http trigger and add some actions of Azure Blob.
3.Fill all the mandatory details.
4.Save and Debug it.
5.Run the workflow, after run close the Debug and back to Designer.

**Expected:** The connection should be valid after going back to to Designer on step5.

**Actual:** Showing invalid connection.
![image](https://github.com/Azure/LogicAppsUX/assets/102700317/a7e8b6ba-60a0-4e88-812f-87b8a03118e0)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Browser

VS Code

### Additional context

**Vendor Testing**

VS Code extension - ​[vscode-azurelogicapps-2.15.10.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEfFwik7TWPhDt6mLfCHxuroB4sWsRX8rJ3eaB21le9f2oQ%3Fe%3DbqyntL&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ai5RL0TcKC%2FztWGWL57RDgQfsN%2FfvDXgGrzpY1THyWE%3D&reserved=0)
NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyNDMyOTY3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.4.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyNDMyOTY3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.4.nupkg&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8rOfv%2F1U8FoD4NAccsyyHJnvk6h6LcmWterenDfUM20%3D&reserved=0)
Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X68ajYSgK%2BNa2gqT4XCZZTy%2Bu1Oqlg8%2BFvD2OUamhmo%3D&reserved=0)
Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.19.4/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.19.4_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.19.4%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.19.4_any-any.zip&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lhzZGusR0OY2fFZq342r%2BiR8%2F6JBiGb0wvf2EI4yFdw%3D&reserved=0)

AB#24202596

**Comment by ccastrotrejo** [comment]
Was solved in this [PR](https://github.com/Azure/LogicAppsUX/pull/2306)

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue fixed. VSIX 2.15.15

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue is seen in the vsix : 2.24.3
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/299ee8f0-8e04-421b-bb92-bf2059aa5ffc)

**Comment by Eric-B-Wu** [comment]
reopening for investigation

**Comment by ccastrotrejo** [comment]
I will close this as I couldn't repro with above steps. I tried with Mac and Windows.

**Comment by ccastrotrejo** [comment]
I was able to repro the issue, the steps are the following 

1. Add the blob trigger.
2. Save.
3. Remove blob trigger, add request trigger and any other Blob action.
4. Save
5. Change to overview page (it doesn't matter if app is running), to change the tab
6. Go back to Designer

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue is repro in 2.24.3

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue is repro in vsix 2.28.3
