### ISSUE TITLE
Extra text in rendering of the dynamic properties

### ISSUE THREAD

**Issue by ccastrotrejo** [Azure/LogicAppsUX#2300]
### Describe the Bug with repro steps

1. Go to portal
2. Crete a standard logic app
3. Add any trigger
4. Add built-in Service bus-Create a topic subscription action
5. Create connection
6. Add required params. In filter type select 'Correlation'
7. Open parameters dropdown

<img width="1600" alt="Screenshot 2023-05-09 at 2 38 59 PM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/35a55c23-26e9-4e93-af89-1a122458b2a7">

Also, when the filter is 'None'

<img width="1060" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/63e5f325-eba1-48df-b85d-b153f6bd6404">

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

**Comment by preetriti1** [comment]
This is not extra text but the parent property name so it can distinguish between leaf nodes, I am wondering this should also be the case for static inputs that are nested, but can check on this
