### ISSUE TITLE
 Can't drag and drop an action to outside a condition

### ISSUE THREAD

**Issue by spanvalkar** [Azure/LogicAppsUX#2302]
### Describe the Bug with repro steps

1. Run LAUX locally. Instructions are here: https://purple-pebble-0e11de71e.1.azurestaticapps.net/
2. Load the workflow called 'conditionals (complex)'
3. Within the 'true' case of a conditional action in the newly loaded workflow, add any action.
4. Try to drag this action outside of the conditional. You will find that the newly-added action cannot be dragged outside of the conditional. 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/132942241/e04b4dbb-3b7b-4cdc-b478-65d6a188bcaf)

### Browser

Edge

**Comment by Eric-B-Wu** [comment]
This is a known issue, we're using this PR for tracking:
https://github.com/Azure/LogicAppsUX/issues/2126
