### ISSUE TITLE
[Feature request] Can resubmit, cannot cancel workflow run

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#2304]
### Describe the Bug with repro steps

1. Go to a workflow -> Overview
2. Select an active run
3. Observe there is a button to Resubmit but there is no button to Cancel it
4. In order to cancel, the user need to open the run details what takes SEVEN seconds:
 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/351644/1770daf1-f67f-47a8-b934-85390c8b295e)

![image](https://github.com/Azure/LogicAppsUX/assets/351644/41fa620b-9728-4116-913b-f431dfc796d0)

### Browser

Edge 112.0.1722.68

AB#24320390

**Comment by WarrenKinley** [comment]
Totally looking forward to this feature being added, I had hundreds of Running instances today that I wanted to cancel, but no way to do this without opening each run.
![image](https://github.com/Azure/LogicAppsUX/assets/95749950/5c033437-66ff-4df2-8442-3bdf9473075a)

**Comment by hartra344** [comment]
Merging with another issue where this is tracked: #2304
