### ISSUE TITLE
VS Code_Webhook testing_Office actions.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2311]
### Describe the Bug with repro steps

1.Open the cmd and run command ngrok http 7071.
2.Create a stateful workflow in your project of vs code.
3.Copy the ngrok value and paste in local.settings.json like this : "Workflows.WebhookRedirectHostUri": "https://f916-2401-4900-1c5b-6f38-8cd0-1d21-f471-c069.in.ngrok.io"
4.OPen the Designer and add office action : 1. When an email arrives OR 2. When an email mentioning me arrives.
5.Save and Debug the workflow.
6.Goto your office and send the mail to itself for excution.

**Expected:** The response is to be recorded on the ngrok cmd page with 200.And the workflow should be working fine.

**Actual:** Workflow is fine. But no response on Ngrok cmd page.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/f083aca2-2765-43ef-b7ee-dd3b45bd31d0)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Browser

VS Code

### Additional context

**Vendor Testing**

VS Code extension - ​[vscode-azurelogicapps-2.15.10.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEfFwik7TWPhDt6mLfCHxuroB4sWsRX8rJ3eaB21le9f2oQ%3Fe%3DbqyntL&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ai5RL0TcKC%2FztWGWL57RDgQfsN%2FfvDXgGrzpY1THyWE%3D&reserved=0)
NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyNDMyOTY3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.4.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyNDMyOTY3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.4.nupkg&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8rOfv%2F1U8FoD4NAccsyyHJnvk6h6LcmWterenDfUM20%3D&reserved=0)
Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X68ajYSgK%2BNa2gqT4XCZZTy%2Bu1Oqlg8%2BFvD2OUamhmo%3D&reserved=0)
Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.19.4/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.19.4_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.19.4%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.19.4_any-any.zip&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lhzZGusR0OY2fFZq342r%2BiR8%2F6JBiGb0wvf2EI4yFdw%3D&reserved=0)

**Comment by preetriti1** [comment]
@ccastrotrejo - Do we have a pop up from vscode to get user inputs for webhook url when webhook actions are added? Or an extension command to add the webhook url?

**Comment by ccastrotrejo** [comment]
@preetriti1 we have this command to configure the webhook endpoint
<img width="913" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/3da9ff42-c03f-41fd-aba8-3a7653622942">
