### ISSUE TITLE
Invalid Map content

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#2314]
### Describe the Bug with repro steps

If you have a json schema that has a node with a leading @ character, the new data mapper doesn't like it

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/83832436/d302f3a4-69c5-4070-8d2a-7160f585bce3)

### Version

2.15.15

### Additional context

More info available in internal OneNote

**Comment by refortie** [comment]
@pariksg This looks like it's a backend issue?

**Comment by DanielleCogs** [comment]
Tried to reproduce and was unable to- will confirm with backend team

**Comment by kewear** [comment]
I have logged an ADO item for backend: 26475697 We can close this out to keep front end's work items clean
