### ISSUE TITLE
No schema is listed after adding schemas to artifacts folder

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#2315]
### Describe the Bug with repro steps

Expected Behavior: 

Clicking on "Select a Source/destination schema" should show list of available schemas to be picked. 

Actual Behavior: 

No schema is listed to be picked. 

 

Repo steps: 
Click on "Create new data map" - opens up map designer 

Added 8 schemas into Artifacts\Schemas folder 

Try to select source/destination schema to start mapping. 

There is no schema listed. 

### Version

2.15.15

### Additional context

More info available in internal OneNote

AB#25473654

**Comment by DanielleCogs** [comment]
Unable to reproduce. This was probably fixed.
