### ISSUE TITLE
Dynamically added parameters are shown as raw ID values instead of friendly dropdowns

### ISSUE THREAD

**Issue by ek68794998** [Azure/LogicAppsUX#2324]
### Describe the Bug with repro steps

1. Create a Logic Apps workflow with any trigger.
2. Add an action: "Post message in a chat or channel" via MS Teams.
3. Fill in the fields:
    - Post as: Flowbot
    - Post in: Channel
    - Team: (choose any from the dropdown)
    - Channel: (choose any from the dropdown)
    - Message: (type any valid message)
4. Save the workflow.
5. Refresh the page.
6. Open the Teams action card and observe the parameters.

Expected: The "Team" and "Channel" parameters should show as dropdowns with user-friendly names.
Actual: The "Team" and "Channel" parameters show as text-input fields with unreadable IDs.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "HTTp": {
        "type": "Http",
        "inputs": {
          "uri": "",
          "method": ""
        },
        "runAfter": {}
      },
      "HTTP": {
        "type": "Http",
        "inputs": {
          "uri": "",
          "method": ""
        },
        "runAfter": {}
      },
      "Post_message_in_a_chat_or_channel": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "teams"
            }
          },
          "method": "post",
          "body": {
            "recipient": {
              "groupId": "b1[REDACTED]5d96",
              "channelId": "19:18f861d3[REDACTED]@thread.skype"
            },
            "messageBody": "test"
          },
          "path": "/beta/teams/conversation/message/poster/Flow bot/location/@{encodeURIComponent('Channel')}"
        },
        "runAfter": {
          "HTTp": [
            "SUCCEEDED"
          ]
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {
    "teams": {
      "connection": {
        "id": "/subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Web/connections/teams"
      },
      "connectionName": "teams",
      "api": {
        "id": "/subscriptions/[REDACTED]/providers/Microsoft.Web/locations/eastus/managedApis/teams"
      },
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/1350074/e1340804-686d-4f18-a04c-4c29149e936a)

### Browser

- Browser: Edge@113.0.1774.35 x64

**Comment by hartra344** [comment]
Is this specific to the teams connector?

**Comment by ek68794998** [comment]
I think it applies to any action with dynamically added dropdown parameters. However, I don't know of any other connector that does this. I can see if I can find out.
