### ISSUE TITLE
Azure Logic App Designer | Copy Paste | Mac OS

### ISSUE THREAD

**Issue by The-King-in-the-North** [Azure/LogicAppsUX#2326]
### Describe the Bug with repro steps

1. Setup VS Code for Logic Apps
2. Create a workflow project
3. Open workflow.json in designer view
4. Try to copy anything from outside designer and paste in any text box inside designer for any action

See that we cannot paste

Also, cannot copy anything from within the designer to the outside world.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
Any workflow
```

### Screenshots or Videos

<img width="1098" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/32009094/d44695f0-b2ad-4e71-a55d-a842cd8054cf">

### Browser

VS Code for Mac OS Ventura 13

**Comment by ccastrotrejo** [comment]
Hi, thanks for letting us know about this issue. I will work on it and will fix it

**Comment by The-King-in-the-North** [comment]
Are there any updates on this ? Local Development is blocked for people.


Thanks

**Comment by ccastrotrejo** [comment]
Hi, sorry I haven't found the reason for this issue, although I found a workaround to this. You can use the command bar base commands when selecting the text and when trying to paste it.  I will work to have the fix for this as soon as possible
<img width="885" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/4bac4def-b71f-496e-ba53-3a7713cdc7de">

**Comment by The-King-in-the-North** [comment]
Hi,
Has this now been fixed with 2653 ? Or we need to use the workaround ?

And when can we expect to see the changes ? Do we need to reinstall the Logic Apps Extension ?

**Comment by ccastrotrejo** [comment]
Hi, yes the issue was solved with 2653. We will release a new Logic Apps Extension version by the EOD today. You will only need to update the extension.

**Comment by ccastrotrejo** [comment]
Fix is now in version 2.18.3w
