### ISSUE TITLE
Expression not being able to edit

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#2327]
### Describe the Bug with repro steps

Add a weather Get forecast for today action and use Seattle. 
Add a compose action and write expression:
body('Get_forecast_for_today')['responses']['daily']['day']['cap'] 

it shows as an expression pill in the UX. 
![image](https://github.com/Azure/LogicAppsUX/assets/91279975/02f314a4-8c8a-4211-ac26-1275759a82f0)

Now, Save the logic app, back out of the page/tab and come back to designer. you are not able to edit the expression.
![image](https://github.com/Azure/LogicAppsUX/assets/91279975/3ba47dd2-07d6-46fb-ad8a-b14a7a65e75a)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

**Comment by hartra344** [comment]
That's by design. it's not an expression, it's a token. Once it's saved and we parsed it, we'll be parsing it as a token even if it's placed through the expression editor.

**Comment by kisubedi** [comment]
AH! Gotcha- I have seen this before where essentially there is no clear way to distinguish dynamic content and expression and an expression resolves into a token. MVPs complained that many times, tokens do not show up so they have to write an expression and it resolves into a token and it won't let them edit.

From customer perspective, If they wrote an expression to represent the token (because there is no workaround as the corresponding token is not present in token picker), they should be able to edit the expression I wrote. This makes

  1.  If I wrote an expression, regardless of whether there existed the corresponding token in token picker list or if it resolves into a token later, I should be able to come back and edit the expression.
  2.  If I scrolled and inserted a dynamic content, it always shows up as a dynamic content and I can not edit the token in expression box.

Is this technically feasible and how do you feel about this change?

Sincerely,
Kishor Subedi
