### ISSUE TITLE
Notifications grid doesn't support resizing columns, chops long messages

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#2330]
### Describe the Bug with repro steps

1. Go to a workflow -> Overview -> Notifications
2. Observe a notification which text is too long to fit the fixed width of the column
3. Observe the grid doesn't support resizing

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/351644/d71560a6-44be-4511-901b-73326a49d263)

### Browser

Edge 113.0.1774.35

**Comment by hartra344** [comment]
Closing this here because we don't own this UX but I will pass this along to the team who does.
