### ISSUE TITLE
Invoke Workflow dropdown uses incorrect casing

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#2331]
### Describe the Bug with repro steps

1. Create a workflow called Child1 (upper case)
2. Create a workflow called Parent1 (upper case)
3. Add action Invoke Workflow
4.Observe the dropdown to select the child workflow lists it as child1 (lower case)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/351644/f2b41f78-66bf-44cf-a840-a29a8c99c08f)

![image](https://github.com/Azure/LogicAppsUX/assets/351644/431db009-5315-452d-81f0-8c3598509922)

### Browser

Edge 113.0.1774.35

**Comment by hartra344** [comment]
@abatishchev is this just a cosmetic issue or is this actually causing potential runtime issues?

**Comment by abatishchev** [comment]
I think it's rather cosmetic, I haven't noticed any technical issues. 
But I think it produces a confusing user experience. The wf can be deployed using MSDeploy with correct casing and then when opened in the designer, the drop-down will blink changing the casing.
Also I don't know if workflow names are case-insensitive, is it possible to create Child1 and child1 the same time? Or it'll be the same workflow?

**Comment by hartra344** [comment]
They are case sensitive. They map an azure resource which is by default case sensitive so it may actually be returned to us that way. We'll look into it if we get a chance.
