### ISSUE TITLE
Standard_ Workflow parameters : Save and Discard buttons are in enable state when the parameters panel is in open.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2336]
### Describe the Bug with repro steps

1.Create a new stateful logic app in standard, open the designer.
2.Validate if 'Parameters' command button shows
3.Now click the parameters button and validate the empty parameters view which opens the panel from right hand side.
4.**Expected:** Validate 'Save' and 'Discard' buttons are disabled when panel is open, and button gets enabled when parameters have been created and panel is closed.
**Actual:** Save and Discard buttons are in enable state when the parameters panel is in open.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
-{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "connectionReferences": {},
  "parameters": {
    "a": {
      "type": "Array",
      "value": [
        1,
        2
      ]
    },
    "b": {
      "type": "Bool",
      "value": true
    },
    "": {
      "type": "Array"
    }
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/94164c4a-75eb-4adc-b336-244a84edec74)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/4dfd5ddd-e586-41c8-8191-a2939d061bbf)

### Browser

Edge

### Additional context

**Environment Details:**
**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C8688f3d5cccf402a38e708db51fe6235%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638193925280493316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BXBSqbVf%2FicM7ZJKIscX6dePWq%2ByCA%2F9nvsgOlU5Ptc%3D&reserved=0)
**Version:** 2.30508.1.1

**Comment by rllyy97** [comment]
This has been fixed and is currently rolling out

**Comment by vgouth** [comment]
Issue repro in the latest request:

**Environment Details:**
**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cb13bdbce753c4d10e4d208db602642f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638209489719398144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ouKhkhxrFJJr2RCOpHP%2F3nqcaTagt7jkAg8FKOmhWRU%3D&reserved=0)
**Version:** 2.30529.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/bcf6232c-c3b9-4683-b49c-ffd922b1ec28)

**Note:** When we add new parameters or edit the existing parameters, save and discard button is enabling even without closing the parameters panel.
