### ISSUE TITLE
Validation Warnings/Errors in Properties Panel Mismatch

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#2338]
### Describe the Bug with repro steps

Received from customer:

Customer was trying to map two decimal values into a decimal value and received an error in the properties panel. (See image below). Because the text was in red, it made them think that they were blocked. However, in Map Checker it shows up as a warning (yellow). Would be good to get a consistent view of issue. When using test map, the map did execute as needed/expected.

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/83832436/d6eb00a4-f1e7-4d73-9cb8-a129803d1be0)

### Version

2.15.15

**Comment by DanielleCogs** [comment]
this is fixed
