### ISSUE TITLE
VSCode designer - variable issue

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2352]
### Describe the Bug with repro steps

In VSCode designer, Initialize a variable and then try setting the value
![Variable-VSCode-1](https://github.com/Azure/LogicAppsUX/assets/40304643/ef80dc8f-17f0-40e8-b6c3-761cae41497f)
![Variable-VSCode-2](https://github.com/Azure/LogicAppsUX/assets/40304643/a340cd51-3cfc-49d4-899b-1ff626fb8f8c)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![Variable-VSCode-1](https://github.com/Azure/LogicAppsUX/assets/40304643/69159fe3-7f4b-4789-b3cd-a6fe75c0450b)
![Variable-VSCode-2](https://github.com/Azure/LogicAppsUX/assets/40304643/5267e2f3-426c-4c3d-bd08-fb2a777dc18a)

### Browser

VSCode

**Comment by Eric-B-Wu** [comment]
Hey @mhireholi thanks for reporting this, this is something we have fixed in #2217, but is just awaiting our next release ETA 5/17
