### ISSUE TITLE
O365 trigger bug - degree of parallelism can't be changed

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2353]
### Describe the Bug with repro steps

Create a workflow with Office365 trigger and go to settings
![las-vscode-bug-O365-trigger-1](https://github.com/Azure/LogicAppsUX/assets/40304643/0d4ad0ca-6b89-4836-8b02-0f9d113154f6)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

Edge - bad for logic apps + crashes all the time
Chrome - good for logic apps
![las-vscode-bug-O365-trigger-1](https://github.com/Azure/LogicAppsUX/assets/40304643/97547bc6-f357-48dd-a471-9f7ecb1bd206)

**Comment by Eric-B-Wu** [comment]
Hi @mhireholi this item should be fixed in #2247, which will be released onto portal to all stations by end of day today
