### ISSUE TITLE
Overview Blade_Trigger History_No option of searchbox to view trigger identifier directly.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2357]
### Describe the Bug with repro steps

1.Create a LA in standard and make some runs.
2.Open logic app overview blade and click on trigger history.

**Expected:** A search box is to be present as same as Run history.

![image](https://github.com/Azure/LogicAppsUX/assets/92098490/84efdc5c-fbaa-4982-8b45-634438392f0a)

**Actual:** No option of the search box.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/863b4cae-2b4f-4929-a161-c1b066b926fb)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Edge

### Additional context

**Environment Details:**

URL: [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-prakumar%40microsoft.com%7C31d00efa413749e2fcaf08db52c01071%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638194757163021674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3mBPFxOBodjLF3OYC3vGEbqU4zegodSbNyCo2xVMyQs%3D&reserved=0)

Version: 2.30508.1.2

**Comment by hartra344** [comment]
There was never a search box here and there are no current plans to add one
