### ISSUE TITLE
Http Webhook_Http webhook option is not present as trigger and action.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2358]
### Describe the Bug with repro steps

1.Create a LA in standard portal and add http webhook as a trigger and option.

**Expected:** Http webhook option should be present.

**Actual:** Http webhook option is not present.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/ab7ed9be-058e-468d-9942-fa8ea39b7122)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Edge

### Additional context

**Environment Details:**

URL: [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-prakumar%40microsoft.com%7C31d00efa413749e2fcaf08db52c01071%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638194757163021674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3mBPFxOBodjLF3OYC3vGEbqU4zegodSbNyCo2xVMyQs%3D&reserved=0)

Version: 2.30508.1.2

**Comment by v-prakumar** [comment]
@ccastrotrejo duplicate of @https://github.com/Azure/LogicAppsUX/issues/2230 i.e. Closed.

**Comment by Eric-B-Wu** [comment]
Talked with Prashant, and it seems to only happen with his Logic App

**Comment by preetriti1** [comment]
There was a timing issue here and it is taken care of now, should make it to prod by EOD next week

**Comment by v-prakumar** [comment]
@Eric-B-Wu @preetriti1 Issue resolved. Version :  2.30529.1.1
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/85bff8a9-51a7-4d49-b8b0-47acbe399c64)
