### ISSUE TITLE
New Logic App flow view not letting me look at previous runs 

### ISSUE THREAD

**Issue by JamesPlatt99** [Azure/LogicAppsUX#2359]
### Describe the Bug with repro steps

Since the new UI was released I'm seeing the following error when looking at a standard tier stateful logic app flow in this case with a service bus trigger but we are also seeing it with Amazon SQS triggers, though ones with http triggers appear to be working as expected.

![image](https://github.com/Azure/LogicAppsUX/assets/32194221/b0a46d50-8930-42a1-8e40-04b3f6a237ae)

When I try to look at a http request I get the following error:

![image](https://github.com/Azure/LogicAppsUX/assets/32194221/9b9f8e30-924e-4962-9070-b12b19a885a8)

The logic app is still running correctly, but since the new UI was released these errors have appeared - some of my coworkers are still getting the old UI and they can see these details without any errors.

Is there a way for users to revert back to the old ui until this is fixed?

I also get the same 'The renderComponentIntoRoot component encountered an error while loading' error when trying to use the Preview Designer to edit the logic app but it works fine on the current designer.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Edge Version 113.0.1774.35 (Official build) (64-bit)

**Comment by ccastrotrejo** [comment]
Hi @JamesPlatt99 thank you very much for raising this issue. We have been working on fixing this issue and its going to be fixed in the next release.

**Comment by ccastrotrejo** [comment]
Hi @JamesPlatt99 this issue should be fixed in azure portal. Please, let me know if you continue facing this.
