### ISSUE TITLE
Shapes/Actions out of whack - see screenshot

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2373]
### Describe the Bug with repro steps

in Azure portal designer (GA designer) 
create a foreach and add a variable followed by a condition

![for-each-bug-2](https://github.com/Azure/LogicAppsUX/assets/40304643/6d1990ff-eabb-4b88-b6ef-c7e5e3bcf25d)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Screenshots or Videos

![for-each-bug-2](https://github.com/Azure/LogicAppsUX/assets/40304643/d165e315-abf5-4083-b416-ed1989bd5ab5)

### Browser

Chrome

**Comment by preetriti1** [comment]
Since this is in old designer and kind of known where multiple roots inside scope might not be correctly rendered. The preview designer should show it correctly
