### ISSUE TITLE
Until exit condition expression adds extra @

### ISSUE THREAD

**Issue by maakku** [Azure/LogicAppsUX#2377]
### Describe the Bug with repro steps

1. Add until loop in designer
2. Add dynamic content on left side of "Loop until" exit condition (e.g. variable named "done")
3. Add expression on right side of "Loop until" exit condition (e.g. "true")

The code representation of the exit condition becomes:
"expression": "@equals(@variables('done'),@true)",

Workflow can be saved in vscode, but it does not load in Azure. Function host log contains an error:
"The template language expression 'equals(@variables('done'),@true)' is not valid: the string character '@' at position '7' is not expected."

The generated code representation should be:
"expression": "@equals(variables('done'),true)",

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Generally Available

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/29248042/bff75206-cac7-4077-b65b-7ef516f7b954)

### Browser

N/A

**Comment by Eric-B-Wu** [comment]
HI @maakku, thanks for reporting this issue, this is something we've fixed in #2270. This will be in our vscode release expected to complete by 5/17
