### ISSUE TITLE
VS code: Project conversion popup issue, unable to get popup stating " Already converted project into SQL artifact".

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2378]
### Describe the Bug with repro steps

1.Create a new project app in bundle using VS Code.
2.Create a stateful / stateless workflow.
3.Convert the project app in bundle to SQL artifact.
4.Converting is getting successful.
5.**Expected:** After converting the project app in bundle to SQL artifact if we try to convert it again we should get a notification popup stating " Already converted project into SQL artifact".
**Actual:** We are not getting any popup stating " Already converted project into SQL artifact".

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "kind": "Stateful"
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/e75489c7-254d-48b7-b90d-49df859ab8c6)

### Browser

VS Code

### Additional context

**Artifact Details:**

1,VS Code extension – vscode-azurelogicapps-2.15.15.vsix
2.NuGet package: https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczMDA5ODA5L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.21.3.nupkg
3.Extension Bundle (CDN URL): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting
4.Extension Bundle (Direct Download): https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.21.3/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.21.3_any-any.zip
5.Resources vsix. vscode-azureresourcegroups-LA.vsix

**Comment by ccastrotrejo** [comment]
Feature request is the following (need to triage and check all scenarios:
Once the user sets the SQL string to use for storage, we should get a notification if user executes the command again, or else we can add a popup stating "The project is already in SQL do you want to change the connection string " by giving the options as yes or no

Need to check the scenario in which the user wants to change the SQL connection string. We can execute the command again and update the string.

**Comment by ccastrotrejo** [comment]
I don't think we are going to add this feature request for now
