### ISSUE TITLE
Service Bus trigger displaying incorrect Split On setting

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#2380]
### Describe the Bug with repro steps

1. Add a service bus trigger to a workflow
2. Disable the Split On setting
3. Click the Save button
4. Refresh the page
5. Open the trigger settings, Split On will appear as enabled with no array value
6. Open the code view, the Split On setting will be absent 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

**Comment by preetriti1** [comment]
@rllyy97 - Is this a servicebus azure trigger or inApp trigger?

**Comment by rllyy97** [comment]
@preetriti1 - I saw it on the In-App trigger
