### ISSUE TITLE
Save doesn't really save

### ISSUE THREAD

**Issue by fitzyjoe** [Azure/LogicAppsUX#2382]
### Describe the Bug with repro steps

Click on Edit to edit an existing logic app.
Make a change (for me the change is in the SQL Server Execute Stored Procedure (V2) component).
Click on Save
Notice the toastr for "saving workflow" and "successfully saved workflow"
Click on either the "X" in the top right corner or the name of the logic app in the breadcrumbs to return to the main view for a logic app.  The system presents me with a warning "Your unsaved edits will be discarded" - but I just saved!
Agree by clicking OK.
Go back to Edit and notice that the changes were never actually saved!  I expected my changes to have been saved.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Execute_stored_procedure_(V2)": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "sql"
            }
          },
          "method": "post",
          "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('claridge-datawarehouse.database.windows.net'))},@{encodeURIComponent(encodeURIComponent('claridge-datawarehouse'))}/procedures/@{encodeURIComponent(encodeURIComponent('[dbo].[SaveBacklog]'))}"
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "Recurrence": {
        "type": "Recurrence",
        "recurrence": {
          "frequency": "Day",
          "interval": 1,
          "schedule": {
            "hours": [
              "5"
            ]
          },
          "timeZone": "Eastern Standard Time"
        }
      }
    }
  },
  "connectionReferences": {
    "sql": {
      "connectionName": "sql",
      "connectionProperties": {
        "authentication": {
          "type": "ManagedServiceIdentity"
        }
      },
      "connection": {
        "id": "/subscriptions/23d4221c-7030-4ab8-9daa-835be3ddf922/resourceGroups/DataWarehouse/providers/Microsoft.Web/connections/sql"
      },
      "api": {
        "id": "/subscriptions/23d4221c-7030-4ab8-9daa-835be3ddf922/providers/Microsoft.Web/locations/southcentralus/managedApis/sql"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/6208666/051cc6f2-9a9c-4188-aea7-f28c79eabb33

### Browser

Chrome (MacOS)

**Comment by hartra344** [comment]
Thank you for the detailed report :) Closing for now and linking to our known issue here: #2382

**Comment by fitzyjoe** [comment]
@hartra344 My problem does not seem to be specific to the preview version of the UI.  I have reproduced the problem with the GA version of the UI.  Please see attached.

https://github.com/Azure/LogicAppsUX/assets/6208666/c77e4b47-9125-4e6b-a22d-e42eafd228be
