### ISSUE TITLE
Changing the Trigger in an Existing Workflow breaks the Run After

### ISSUE THREAD

**Issue by WarrenKinley** [Azure/LogicAppsUX#2384]
### Describe the Bug with repro steps

1. Amend an existing workflow with a trigger
2. Choose and configure a new trigger action
3. The Action after the trigger will be broken and you cannot remove the old trigger action from the Run After list

I do have a workaround for this but it is a pain.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/95749950/ed7440f0-3e6f-47be-8649-d618a218f9e7)

### Browser

Edge

**Comment by WarrenKinley** [comment]
Sorry not Consumption but Logic App Std preview designer in the portal

**Comment by rllyy97** [comment]
Hi Warren!  Thank you for the bug report, thankfully this is a known issue and our fix should be rolling out throughout this week
