### ISSUE TITLE
Can't move created steps inside of switch loops

### ISSUE THREAD

**Issue by tyki21** [Azure/LogicAppsUX#2387]
### Describe the Bug with repro steps

1. select the " create an item" sharepoint step
2. Create a switch case 
3. ![image](https://github.com/Azure/LogicAppsUX/assets/19767881/6170aa65-515a-47e7-a269-890d5e0f1da1)
4. Try to put the ceate an item inside the switch loop

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

**Comment by hartra344** [comment]
Hey @tyki21, Thanks for the report. This one is a known issue and we'll have a better drag-drop solution out in our next release. About 2 weeks. Sorry for the inconvenience currently.
