### ISSUE TITLE
Consumption Logic Apps silent save failures

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#2388]
## What was the issue?
Previously the preview version of designer, **specifically for Consumption**, was failing to save logic apps.
These failures were sometimes silent and would give no notification.

Progress on this issue will be updated on this ticket as new information comes available.

AB#24207355

**Comment by natereprogle** [comment]
> // We are investigating other situations

In my situation, changing the "Run After" settings within an action caused this behavior. I'm not sure if that is covered within the two situations you already mentioned, but I wanted to bring it up. I rarely use Logic Apps so I'm not familiar with the terminology and full feature set. Thank you all for tracking this!

**Comment by nesith** [comment]
If you clicked save and it gives you the successful message, you will see that the save button and discard buttons are still active, at this point if you click the discard button and when the popup message comes up about your edits been lost, say no and it will save all the changes. This has been my workaround, hopefully fixes coming soon will rectify this.

**Comment by alnandr** [comment]
> If you clicked save and it gives you the successful message, you will see that the save button and discard buttons are still active, at this point if you click the discard button and when the popup message comes up about your edits been lost, say no and it will save all the changes. This has been my workaround, hopefully fixes coming soon will rectify this.

I tried doing this on my consumption logic app in the preview designer and it didn't actually save anything. Would love for this to be resolved soon because I'm not able to edit HTML in the body of Gmail's send email action on the current designer, but I can on the new designer.

**Comment by rllyy97** [comment]
Hi @natereprogle, @nesith, @alnandr,
Thanks for communicating your saving issues to us, we recently finished rolling out our new build with many saving / validation / error communication fixes on June 9th.  If you are able could you try your use-cases again on this new build and let me know if saving works/doesn't? 
If you are still experiencing issues please create a new issue thread with any relevant details like your workflow file or any related errors / logs.  Also it would be very helpful to us if you could send a network log file as well, you can send those directly to me at rileyevans@microsoft.com.
If you need assistance with any of the error-reporting steps we've created a TSG you can find [here](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg) that goes into details

**Comment by rllyy97** [comment]
Closing as we have not received any reports of further saving issues
