### ISSUE TITLE
Item Tokens Not being Generated on Initialization

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#2389]
### Describe the Bug with repro steps

1. Create a Service Bus connection
2. Create an action below service bus (When messages are available in a topic)
3. Use an item token from service bus
4. Save
5. Refresh Page
6. View Workflow again
7. Go into action below service bus
8. See token has gone missing, also open token picker and see that there are not outputs being generated from servicebus action

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

On Add
![7a4b5f2b-6992-4a74-8f28-d574c9732700](https://github.com/Azure/LogicAppsUX/assets/95886809/33ab1800-3767-44de-bb01-06d750ff75e1)

On Initialize
![714f7b59-0496-4d6b-9cae-b28e14b1c186](https://github.com/Azure/LogicAppsUX/assets/95886809/1139fe80-61f8-4782-9813-dcd21cfe77dd)

### Browser

Edge

**Comment by preetriti1** [comment]
@Eric-B-Wu this seems to be dynamic outputs issue with the trigger, does this trigger requires dynamic outputs or is this split on issue?

**Comment by Eric-B-Wu** [comment]
I'm referring to the output from the trigger, it seems like we aren't splitting the output in initialization, which causes a loss of tokens

**Comment by preetriti1** [comment]
So this is a split On issue which is not processing splitOn during deserialization
