### ISSUE TITLE
No way to access previous steps variables - other than immediate predecessor, and that only works sporadically

### ISSUE THREAD

**Issue by fw-mgerow** [Azure/LogicAppsUX#2399]
### Describe the Bug with repro steps

Go to workflow that was editable before new editor rolled out.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

Chrome

**Comment by fw-mgerow** [comment]
Hi Travis. It appears that in the last day or two the UI of the Azure Logic Apps standard designer has changed, and there's no way to reference variables or output properties of prior steps. In the previous designer UI this was easy. This makes the new UI almost unusable.

Is there some way to revert to the old UI?

Thanks

Mark

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hartra344** [comment]
Hey Mark, yes we've made the new preview UI GA and it's now fully replaced the old UI which is being deprecated. Can you give us more information about what you're workflow looks like though. The issue you're describing is not something we're able to repro. Here is my attempt. 

<img width="1361" alt="CleanShot 2023-05-16 at 22 45 36@2x" src="https://github.com/Azure/LogicAppsUX/assets/13208452/ef4e4457-e62d-4158-a214-b67cbae0b433">

**Comment by fw-mgerow** [comment]
Hi Travis,

The problem may be related to your handling of SQL connector. When I created a very simple flow similar to yours, I could see step variables, but many of our flows start with a SQL trigger. I've attached a representative example. What I've observed is that the SQL trigger is inconsistent in displaying parameters (which we use for server and database name), will not resolve the tables in the table property so I need to manually enter the table name. Also, when I use a SQL step to get a row, no data from that step is available in future steps.

I spot-checked some other flows, and outputs from the Teams connector likewise does not seem to be available in later steps.

I have not tested with other kinds of connectors.

This is a HUGE problem for us, as we have hundreds of flows like this, which we now cannot edit through the designer.

Mark

[cid:39d1fd72-0f83-4942-9ce9-50ab6a6064db]

[cid:6a85284e-45cf-4e90-8eb6-21f3f05bda38]

[cid:c4223e68-9e84-4adb-aa9b-a60e92bf529c]

[cid:8f2ed426-e19d-449e-9c90-6e779da128a8]
________________________________

**Comment by fw-mgerow** [comment]
I would also point out that this problem is occurring for other developers on my team. As I said, this is a HUGE problem for us. If you could give us access to the old UI until it can be fixed I would greatly appreciate it. If you need to get on a call to see what we're seeing, I will gladly do so.
________________________________

**Comment by hartra344** [comment]
please send me an email at travisharris@microsoft.com and I'll give you a link to the old designer while we work to fix the issue you mentioned.

**Comment by fw-mgerow** [comment]
@preetriti1 - All databases are Azure SQL-hosted. Also fails for Teams connectors

Travis - I did send you screenshots earlier this morning, did you not get those?
________________________________

**Comment by hartra344** [comment]
@fw-mgerow just went back and checked to make sure, no screenshots made it to me
