### ISSUE TITLE
Split on errors in the designer

### ISSUE THREAD

**Issue by pim-simons** [Azure/LogicAppsUX#2404]
### Describe the Bug with repro steps

Since this morning my Logic App Standard workflows are showing errors in the designer. It seems like the designer has switched to a newer version.
The error occurs on all my receive shapes where I have split on configured. This is the error: `Unable to initialize operation details for operation - When_a_HTTP_request_is_received. Error details - Core.AssertionException: Invalid type on split on value '@triggerBody()', split on not in array.`

![image](https://github.com/Azure/LogicAppsUX/assets/32359437/93bbc3a1-249d-4419-b52c-686bef73fcd9)

This happens when I add the following spliton configuration:
``` json
"splitOn": "@triggerBody()",
"splitOnConfiguration": {
    "correlation": {
        "clientTrackingId": "@triggerBody()?['Context']?['x-ms-client-tracking-id']"
    }
}
```

This configuration worked fine in the old designer and never gave any kind of issues.
Why is this suddenly an issue in the designer? 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "splitOn": "@triggerBody()",
                "splitOnConfiguration": {
                    "correlation": {
                        "clientTrackingId": "@triggerBody()?['Context']?['x-ms-client-tracking-id']"
                    }
                },
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Browser

Chrome

**Comment by hartra344** [comment]
@Eric-B-Wu can you take a look at this issue?

**Comment by preetriti1** [comment]
It's mainly because it is expecting a schema here and without schema it wouldn't know if triggerbody() is an array
