### ISSUE TITLE
JavaScriptCode Run Output not Displaying

### ISSUE THREAD

**Issue by WarrenKinley** [Azure/LogicAppsUX#2407]
### Describe the Bug with repro steps

1. View a run with a JavaScriptCode action that returns a value
2. Preview shows Outputs displays "No output" 
3. Click "Show raw outputs" and there is a returned value

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/95749950/84fa5eca-7eed-4555-8938-3adebc8f2dda)
![image](https://github.com/Azure/LogicAppsUX/assets/95749950/e0169a9f-71cd-4bbd-814c-75fb8ba18a8f)

### Browser

Edge

**Comment by ccastrotrejo** [comment]
Hi @WarrenKinley, thanks for raising this issue. This is now fixed in the latest portal release. Please, let me know if this keeps happening and I will take a further look at it.
