### ISSUE TITLE
Token picker should have collapse/expand (^) button right by action names. 

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#2416]
### Describe the Bug with repro steps

![image](https://github.com/Azure/LogicAppsUX/assets/91279975/6284b254-7487-4dbf-a1e4-760a35f39f37)
In the absence of collapse button, I have to scroll mindlessly to get to the subsequent action's tokens. In the case of env variables, I see ~200 env variables, so getting to the second action is too cumbersome. 
Here is the design we have for experimental token picker, we can follow:

<img width="455" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/91279975/1fae6e44-2e07-4ae7-83a4-eb5cc4795b45">

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

AB#24270047

**Comment by Eric-B-Wu** [comment]
Adding as item of https://github.com/Azure/LogicAppsUX/issues/2416
