### ISSUE TITLE
Save is not working on the Preview designer!  

### ISSUE THREAD

**Issue by seeavosh** [Azure/LogicAppsUX#2418]
### Describe the Bug with repro steps

After saving, if you leave the page and come back you will be presented with the old one and not the new design 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Edge

**Comment by hartra344** [comment]
Thank you for reporting. Closing however since this is already listed in known issues. A fix will be out very soon.
