### ISSUE TITLE
Can't save change

### ISSUE THREAD

**Issue by cparker4486** [Azure/LogicAppsUX#2422]
### Describe the Bug with repro steps

1. Open my App
2. See there's a new UI (glad to see it's finally happening but wasn't this announced a very long time ago?)
3. Delete an action and click Save
4. See Save confirmation toast at top-right corner
5. See Save button become active immediately as if nothing were saved
6. Try again and get same result
7. Switch to old UI
8. Successfully save

Thanks!

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Edge

**Comment by hartra344** [comment]
This is in the known issues list. We'll have a fix out for it soon.
