### ISSUE TITLE
workflow validation errors are shown on the portal after hitting save but not on the VSCode

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2423]
### Describe the Bug with repro steps

workflow validation errors are shown on the portal after hitting save but not on the VSCode

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

**Comment by ccastrotrejo** [comment]
Hi @mhireholi thank you so much for raising this issue. Is there a specific workflow/scenario/steps you are noticing the validation errors are not showing? That info would be really much appreciate it in order to repro the issue

**Comment by ccastrotrejo** [comment]
Just as an update on this. I looked at the validation process and it isn't hitting the validate api. I am working right now to make it work and once it is fixed I will update the issue.

**Comment by ccastrotrejo** [comment]
This has been fixed in the FE side, BE side is pending. Was fixed in #2649
