### ISSUE TITLE
LA Standard Designer issue - Blob Storage Connector fails to create connection due to API issue

### ISSUE THREAD

**Issue by PedroAlmeidaMS** [Azure/LogicAppsUX#2424]
### Describe the Bug with repro steps

Reporting another Bug on the Preview Designer that needs attention.
With Azure Blob connector, trigger "When a blob is added or modified (properties only) (V2)", it is not possible to create a new connection, as the API request it makes is invalid.

Repro steps:
•	Select Preview Designer
•	Select Azure Blob Storage Connector
•	select "When a blob is added or modified (properties only) (V2)" trigger
•	try to add a new connection with Access key
Result:
 

API request:
{ 
      "properties": {
            "api": {
                  "id": "/subscriptions/XXXXXXXXXXXXX/providers/Microsoft.Web/locations/francecentral/managedApis/azureblob"
            },
            "parameterValueSet": {
                  "name": "keyBasedAuth",
                  "values": {
                        "accountName": {
                              "value": "defaultresourcegroub8aa"
                        },
                        "accessKey": {
                              "value": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
                        },
                        "authType": {},
                        "gateway": {},
                        "privacySetting": {}
                  }
            },
            "displayName": "cn-blob2"
      },
      "kind": "V2",
      "location": "francecentral"
} 

API Request from Generally Available Designer:
•	there is no presence of the authType, gateway or privacySettings properties.
{
      "properties": {
            "api": {
                  "id": "/subscriptions/XXXXXXXXXXXXXXXX/providers/Microsoft.Web/locations/centralus/managedApis/azureblob"
            },
            "parameterValueSet": {
                  "name": "keyBasedAuth",
                  "values": {
                        "accountName": {
                              "value": "defaultresourcegroub8aa"
                        },
                        "accessKey": {
                              "value": "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
                        }
                  }
            },
            "displayName": "blob-gendesigner"
      },
      "kind": "V2",
      "location": "centralus"
}

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/112867201/1a621522-11cb-441a-a029-575868b46b65)

### Browser

Edge

**Comment by hartra344** [comment]
This is being hotfixed in tonight
