### ISSUE TITLE
Invoke workflow does not show the input parameter fields in VSCode

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2426]
### Describe the Bug with repro steps

In VSCode - create:
workflow1 with HTTP Trigger accepting input fields
workflow2 --> invoke workflow one. It does not show the text boxes to input values into these input parameter fields

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Browser

VSCode
Chrome

**Comment by ccastrotrejo** [comment]
Pasting this as a reference of what is expected
<img width="1410" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/699c268e-1208-4b03-b42e-3b5f5446dd4e">
