### ISSUE TITLE
Cannot bulk terminate running instances

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2429]
### Describe the Bug with repro steps

![image](https://github.com/Azure/LogicAppsUX/assets/40304643/78a2d015-0f6d-4f73-9061-8daeb538dac2)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/40304643/0ee23137-0596-48b2-86b0-89c5c30bc891)

### Browser

Chrome

**Comment by hartra344** [comment]
Fixed in closed source PR: https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/9216125
