### ISSUE TITLE
Saving logic app with invalid parameter indicates save was successful but then indicates Unsaved Changes Will be Discarded upon closing editor

### ISSUE THREAD

**Issue by shoemakerm** [Azure/LogicAppsUX#2430]
### Describe the Bug with repro steps

Create LA with "When an Email Arrives" trigger and set valid parameters for From Address, Subject, etc...
Save LA
Edit LA and try to add invalid value for Start Time
Save LA - System indicates Save was successful.
Close LA - System warns that Unsaved Changes will be Discarded
Edit LA - Confirm that changes were not saved despite prior successful Save message

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Edge

**Comment by hartra344** [comment]
This is in the known issues.
