### ISSUE TITLE
For Loop action - spinning for eternity. How do I know what's going on?

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2431]
### Describe the Bug with repro steps

![image](https://github.com/Azure/LogicAppsUX/assets/40304643/003b2cae-81b8-4609-b31c-9d6950c54304)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/40304643/2e0eb728-e532-4250-bcd3-78ee8ec0e6c3)

### Browser

Chrome

**Comment by preetriti1** [comment]
@mhireholi - Please provide some context on when are you seeing this. It will be helpful for us to investigate when repro steps are provided like if it happens on adding this action or loading an existing one. Just with screenshot we wont be able to investigate on which scenario this is breaking.

**Comment by preetriti1** [comment]
@mhireholi - Since no information on this was provided, we are going to close this issue. If you still face this issue please reopen the issue and provide details or repro steps.
If it requires you to share network traces we can share our email id where you can send us.
