### ISSUE TITLE
Create Csv + Send Email v2 error adding csv attachment

### ISSUE THREAD

**Issue by zacharydweiss** [Azure/LogicAppsUX#2443]
### Describe the Bug with repro steps

Workflow validation failed for the workflow 'DailyReporter'. {"error":{"code":"InvalidTemplate","message":"The template validation failed: 'The template action 'Send_an_email_(V2)' at line '1' and column '1447' is not valid: \"Unable to parse template language expression 'base64('@{body('Create_CSV_table')}')': expected token 'RightParenthesis' and actual 'Identifier'.\".'."}}

I have a logic app that is returning query results from Kusto, then using that to create a csv, and finally email v2 step. I receive the above error when trying to save the template with the output from the csv step as an attachment in the send email v2 step. It's worth mentioning that this same configuration worked previously.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

Chrome and Edge

**Comment by Eric-B-Wu** [comment]
@zacharydweiss thanks for reporting this issue, seems like its a bug happening when adding a token while casting, will get this fixed asap
