### ISSUE TITLE
Updating the VS Code Logic Apps (Standard) extension to 2.15.15 removes Logic App (standard) tab from Azure Resources

### ISSUE THREAD

**Issue by John-Bosch** [Azure/LogicAppsUX#2448]
### Describe the Bug with repro steps

1. Update the Azure Logic Apps (Standard) VS Code extension to 2.15.15
2. Restart VS Code
3. Go to the Azure Resources pane and the Logic App (Standard) tab no longer displays.
4. Roll the Azure Logic Apps (Standard) VS Code extension back to 2.8.0
5. Restart VS Code
6. Go to the Azure Resources pane and the Logic App (Standard) tab displays again.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Browser

No browser. It's VS Code

**Comment by tiagoacosta17** [comment]
+1 Got the same issue, had to rollback to the previous version.

**Comment by bryanhd** [comment]
Bump had to roll back as well

**Comment by ccastrotrejo** [comment]
Hi everyone, thank you so much for raising this issue and letting us know about this. From version 2.15.15 onwards we are following the same architecture pattern that the rest of the azure extensions are following; this implies removing our extension tab and move the remote logic apps tree structure into the resources tab in the azure panel. You will be able to see your remote apps when opening the `Logic App` dropdown. This also applies to the ribbon buttons that we used to have in our tab title, those were migrated to the workspace tab. We will work on updating the documentation regarding these recent changes. 

Please take a look at the following screenshot and make sure you have installed the resources tab extension version 0.7.3 or bigger

<img width="542" alt="Screenshot 2023-05-19 at 1 51 55 PM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/3c9c00bb-920d-401c-8949-20087bb17478">
