### ISSUE TITLE
There is no "Current item" token for "For each" actions

### ISSUE THREAD

**Issue by wifun** [Azure/LogicAppsUX#2451]
### Describe the Bug with repro steps

1. Create a workflow with the "for each" action
2. Token is missing, something like: "@items('For_each')"

Expected:
![image](https://github.com/Azure/LogicAppsUX/assets/55114634/56d5bc66-8ce0-4c0a-8aa0-c50f22d0b62f)

Actual:
![image](https://github.com/Azure/LogicAppsUX/assets/55114634/eedea5f1-a188-4c60-ae86-9b623362af9a)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

AB#24186089

**Comment by satyajithvaidyamanthani** [comment]
Not Just for Consumption Logic App's but also for Standard Logic App's
