### ISSUE TITLE
Logic App Set Variable - unable to enter text into Name field in Edge on iOS

### ISSUE THREAD

**Issue by goldjg** [Azure/LogicAppsUX#2477]
### Describe the Bug with repro steps

1. Go to a logic App designer view in Edge browser on iPhone
2. Add a Set Variable task/connector
3. Tap in “Name” field
4. UI opens a blade popup with no contents and no keyboard dialog.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Screenshots or Videos

![IMG_8020](https://github.com/Azure/LogicAppsUX/assets/43296126/c71f5eef-c318-402b-b517-38f766eb820b)

### Browser

- Browser: Edge (iOS 16.5)

**Comment by ccastrotrejo** [comment]
Hi @goldjg thank you so much for raising this issue. The blank blade popup that you see over there is used to select the variable you want to set the value to. Please first use the `Initialize variable` action to initialize the variable you want to set the value to. 
It seems that you missed that step according to the repro steps. I tried to repro and by initializing the variable first you can see the variable over there when trying to set a value. Please let me know if you still see the issue after the change an I will open it and take a further look.

**Comment by goldjg** [comment]
That worked, thanks!
I didn’t raise you had to declare variables before use!

Regards,
Graham
