### ISSUE TITLE
Trying to trigger Logic App but getting error - msportalfx.errors.ajax error msportalfx.errors.error

### ISSUE THREAD

**Issue by jordan-mulvaney-pwc-afca** [Azure/LogicAppsUX#2486]
### Describe the Bug with repro steps

1. Add new row to table
2. Logic App trigger is when a new row is added
3. Run history is blank
4. Trigger history has succeeded triggers but when I go into inputs I see an error
`{
    "type": "MsPortalFx.Errors.AjaxError",
    "baseTypes": [
        "MsPortalFx.Errors.AjaxError",
        "MsPortalFx.Errors.Error"
    ],
    "data": {
        "uri": "https://sp-xxx-la-cms-smsnotification.azurewebsites.net:443/runtime/webhooks/workflow/scaleUnits/prod-00/workflows/9a566e22673645c69ebf4ad3e6ec56e6/triggers/When_a_row_is_added_to_SMS_Transactions_table/histories/08585168029002022672219718397CU00/contents/TriggerInputs?api-version=2018-11-01&code=EZLWMpt_cJYGXf9E7cJM58PfAIVJiCikT8TyjWrExOoqAzFumyu9Cw%3d%3d&se=2023-05-23T05%3A00%3A00.0000000Z&sp=%2Ftriggers%2FWhen_a_row_is_added_to_SMS_Transactions_table%2Fhistories%2F08585168029002022672219718397CU00%2Fcontents%2FTriggerInputs%2Fread&sv=1.0&sig=_REDACTED_SAS_TOKEN_SIG_",
        "type": "GET",
        "pathAndQuery": "",
        "requestId": "88be3cdd-3aa4-45ce-8a9a-d2612aead04f",
        "failureCause": "",
        "sessionId": "d6a20f419db94e288c76558d1b6ad3e0",
        "status": 0,
        "statusText": "error",
        "duration": 1757.699999999255
    },
    "extension": "Microsoft_Azure_EMA",
    "errorLevel": 0,
    "timestamp": 432779.5999999996,
    "name": "AjaxError",
    "innerErrors": [],
    "textStatus": "error",
    "errorThrown": "",
    "jqXHR": {
        "readyState": 0,
        "status": 0,
        "statusText": "error"
    }
}`
5. Not sure where to go with that error

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Workflow JSON

`{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Condition_-_If_State_QLD_NSW_VIC_TAS": {
                "actions": {
                    "Set_TimeZone_to_AEST": {
                        "inputs": {
                            "name": "TimeZone",
                            "value": "AUS Eastern Standard Time"
                        },
                        "type": "SetVariable"
                    }
                },
                "else": {
                    "actions": {
                        "Condition_-_If_State_SA_NT": {
                            "actions": {
                                "Set_TimeZone_to_ACST": {
                                    "inputs": {
                                        "name": "TimeZone",
                                        "value": "AUS Central Standard Time"
                                    },
                                    "type": "SetVariable"
                                }
                            },
                            "else": {
                                "actions": {}
                            },
                            "expression": {
                                "and": [
                                    {
                                        "equals": [
                                            "@body('Get_recipient_state_from_RecipientID')?['address1_stateorprovince']",
                                            "SA"
                                        ]
                                    },
                                    {
                                        "equals": [
                                            "@body('Get_recipient_state_from_RecipientID')?['address1_stateorprovince']",
                                            "NT"
                                        ]
                                    }
                                ]
                            },
                            "type": "If"
                        }
                    }
                },
                "expression": {
                    "and": [
                        {
                            "equals": [
                                "@body('Get_recipient_state_from_RecipientID')?['address1_stateorprovince']",
                                "QLD"
                            ]
                        },
                        {
                            "equals": [
                                "@body('Get_recipient_state_from_RecipientID')?['address1_stateorprovince']",
                                "NSW"
                            ]
                        },
                        {
                            "equals": [
                                "@body('Get_recipient_state_from_RecipientID')?['address1_stateorprovince']",
                                "VIC"
                            ]
                        },
                        {
                            "equals": [
                                "@body('Get_recipient_state_from_RecipientID')?['address1_stateorprovince']",
                                "TAS"
                            ]
                        }
                    ]
                },
                "runAfter": {
                    "Get_recipient_state_from_RecipientID": [
                        "Succeeded"
                    ]
                },
                "type": "If"
            },
            "Condition_-_If_later_than_5pm": {
                "actions": {
                    "Convert_time_to_9am_next_day": {
                        "inputs": {
                            "baseTime": "@{addDays(body('Convert_time_to_recipient_TimeZone'), 1, 'yyyy-MM-dd')} 09:00:00",
                            "destinationTimeZone": "UTC",
                            "formatString": "u",
                            "sourceTimeZone": "@variables('TimeZone')"
                        },
                        "kind": "ConvertTimeZone",
                        "type": "Expression"
                    },
                    "Set_Scheduled_Time_variable_1": {
                        "inputs": {
                            "name": "ScheduleTime",
                            "value": "@body('Convert_time_to_9am_next_day')"
                        },
                        "runAfter": {
                            "Convert_time_to_9am_next_day": [
                                "Succeeded"
                            ]
                        },
                        "type": "SetVariable"
                    }
                },
                "else": {
                    "actions": {
                        "Condition_-_If_earlier_than_9am": {
                            "actions": {
                                "Convert_time_zone_to_9am_today": {
                                    "inputs": {
                                        "baseTime": "@{formatDateTime(body('Convert_time_to_recipient_TimeZone'), 'yyyy-MM-dd')} 09:00:00",
                                        "destinationTimeZone": "UTC",
                                        "formatString": "u",
                                        "sourceTimeZone": "@variables('TimeZone')"
                                    },
                                    "kind": "ConvertTimeZone",
                                    "type": "Expression"
                                },
                                "Set_Scheduled_Time_variable_2": {
                                    "inputs": {
                                        "name": "ScheduleTime",
                                        "value": "@body('Convert_time_zone_to_9am_today')"
                                    },
                                    "runAfter": {
                                        "Convert_time_zone_to_9am_today": [
                                            "Succeeded"
                                        ]
                                    },
                                    "type": "SetVariable"
                                }
                            },
                            "else": {
                                "actions": {
                                    "Set_Scheduled_Time_variable_3": {
                                        "inputs": {
                                            "name": "ScheduleTime",
                                            "value": "@{utcNow()}"
                                        },
                                        "type": "SetVariable"
                                    }
                                }
                            },
                            "expression": {
                                "and": [
                                    {
                                        "less": [
                                            "@formatDateTime(body('Convert_time_to_recipient_TimeZone'), 'HH:mm:ss')",
                                            "09:00:00"
                                        ]
                                    }
                                ]
                            },
                            "type": "If"
                        }
                    }
                },
                "expression": {
                    "and": [
                        {
                            "greater": [
                                "@formatDateTime(body('Convert_time_to_recipient_TimeZone'), 'HH:mm:ss')",
                                "17:00:00"
                            ]
                        }
                    ]
                },
                "runAfter": {
                    "Convert_time_to_recipient_TimeZone": [
                        "Succeeded"
                    ]
                },
                "type": "If"
            },
            "Convert_time_to_recipient_TimeZone": {
                "inputs": {
                    "baseTime": "@{utcNow()}",
                    "destinationTimeZone": "@variables('TimeZone')",
                    "formatString": "u",
                    "sourceTimeZone": "UTC"
                },
                "kind": "ConvertTimeZone",
                "runAfter": {
                    "Condition_-_If_State_QLD_NSW_VIC_TAS": [
                        "Succeeded"
                    ]
                },
                "type": "Expression"
            },
            "Get_SMS_row_using_ID": {
                "inputs": {
                    "headers": {
                        "accept": "application/json;odata.metadata=full",
                        "organization": "https://pwcau-xxx-dev.crm6.dynamics.com",
                        "prefer": "odata.include-annotations=*"
                    },
                    "host": {
                        "connection": {
                            "referenceName": "commondataservice_1"
                        }
                    },
                    "method": "get",
                    "path": "/api/data/v9.1/@{encodeURIComponent(encodeURIComponent('xxx_smses'))}(@{encodeURIComponent(encodeURIComponent(triggerBody()?['_xxx_smsid_value']))})"
                },
                "runAfter": {},
                "type": "ApiConnection"
            },
            "Get_recipient_state_from_RecipientID": {
                "inputs": {
                    "headers": {
                        "accept": "application/json;odata.metadata=full",
                        "organization": "https://pwcau-xxx-dev.crm6.dynamics.com",
                        "prefer": "odata.include-annotations=*"
                    },
                    "host": {
                        "connection": {
                            "referenceName": "commondataservice_1"
                        }
                    },
                    "method": "get",
                    "path": "/api/data/v9.1/@{encodeURIComponent(encodeURIComponent('contacts'))}(@{encodeURIComponent(encodeURIComponent(variables('RecipientID')))})",
                    "queries": {
                        "$select": "address1_stateorprovince"
                    }
                },
                "runAfter": {
                    "Initialize_TimeZone_variable_to_AWST": [
                        "Succeeded"
                    ]
                },
                "type": "ApiConnection"
            },
            "Initialize_BusinessOpen_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "BusinessOpen",
                            "type": "boolean",
                            "value": "@false"
                        }
                    ]
                },
                "runAfter": {
                    "Condition_-_If_later_than_5pm": [
                        "Succeeded"
                    ]
                },
                "type": "InitializeVariable"
            },
            "Initialize_RecipientID_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "RecipientID",
                            "type": "string",
                            "value": "@triggerBody()?['_xxx_recipientid_value']"
                        }
                    ]
                },
                "runAfter": {
                    "Initialize_ScheduleTime_variable": [
                        "Succeeded"
                    ]
                },
                "type": "InitializeVariable"
            },
            "Initialize_ScheduleTime_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "ScheduleTime",
                            "type": "string"
                        }
                    ]
                },
                "runAfter": {
                    "Get_SMS_row_using_ID": [
                        "Succeeded"
                    ]
                },
                "type": "InitializeVariable"
            },
            "Initialize_TimeZone_variable_to_AWST": {
                "inputs": {
                    "variables": [
                        {
                            "name": "TimeZone",
                            "type": "string",
                            "value": "W. Australia Standard Time"
                        }
                    ]
                },
                "runAfter": {
                    "Initialize_RecipientID_variable": [
                        "Succeeded"
                    ]
                },
                "type": "InitializeVariable"
            },
            "Send_message": {
                "inputs": {
                    "parameters": {
                        "entityName": "schedule-sms-messages-queue",
                        "message": {
                            "contentData": {
                                "Message": "@body('Get_SMS_row_using_ID')?['description']",
                                "SMS Transaction ID": "@triggerBody()?['xxx_smstransactionid']",
                                "To": "@triggerBody()?['xxx_mobilenumber']"
                            },
                            "scheduledEnqueueTimeUtc": "@variables('ScheduleTime')"
                        }
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "serviceBus",
                        "operationId": "sendMessage",
                        "serviceProviderId": "/serviceProviders/serviceBus"
                    }
                },
                "runAfter": {
                    "Until": [
                        "Succeeded"
                    ]
                },
                "type": "ServiceProvider"
            },
            "Until": {
                "actions": {
                    "Condition_-_Is_business_open": {
                        "actions": {
                            "Convert_time_to_9am_next_day_-_For_business_closure": {
                                "inputs": {
                                    "baseTime": "@{addDays(variables('ScheduleTime'), 1, 'yyyy-MM-dd')} 09:00:00",
                                    "destinationTimeZone": "UTC",
                                    "formatString": "u",
                                    "sourceTimeZone": "@variables('TimeZone')"
                                },
                                "kind": "ConvertTimezone",
                                "type": "Expression"
                            },
                            "Set_Scheduled_Time_variable_4": {
                                "inputs": {
                                    "name": "ScheduleTime",
                                    "value": "@body('Convert_time_to_9am_next_day_-_For_business_closure')"
                                },
                                "runAfter": {
                                    "Convert_time_to_9am_next_day_-_For_business_closure": [
                                        "SUCCEEDED"
                                    ]
                                },
                                "type": "SetVariable"
                            }
                        },
                        "else": {
                            "actions": {
                                "Set_BusinessOpen_to_True": {
                                    "inputs": {
                                        "name": "BusinessOpen",
                                        "value": true
                                    },
                                    "type": "SetVariable"
                                }
                            }
                        },
                        "expression": {
                            "and": [
                                {
                                    "or": [
                                        {
                                            "equals": [
                                                "@dayOfWeek(variables('ScheduleTime'))",
                                                0
                                            ]
                                        },
                                        {
                                            "equals": [
                                                "@dayOfWeek(variables('ScheduleTime'))",
                                                6
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "greater": [
                                        "@count(body('List_rows_(preview)')?['value'])",
                                        0
                                    ]
                                }
                            ]
                        },
                        "runAfter": {
                            "List_rows_(preview)": [
                                "Succeeded"
                            ]
                        },
                        "type": "If"
                    },
                    "List_rows_(preview)": {
                        "inputs": {
                            "headers": {
                                "accept": "application/json;odata.metadata=full",
                                "organization": "https://pwcau-xxx-dev.crm6.dynamics.com",
                                "prefer": "odata.include-annotations=*"
                            },
                            "host": {
                                "connection": {
                                    "referenceName": "commondataservice_1"
                                }
                            },
                            "method": "get",
                            "path": "/api/data/v9.1/@{encodeURIComponent(encodeURIComponent('msdyn_businessclosures'))}",
                            "queries": {
                                "$filter": "msdyn_starttime eq @{formatDateTime(variables('ScheduleTime'), 'yyyy-MM-dd')}",
                                "$select": "msdyn_starttime"
                            }
                        },
                        "trackedProperties": {},
                        "type": "ApiConnection"
                    }
                },
                "expression": "@equals(variables('BusinessOpen'), true)",
                "limit": {
                    "count": 60,
                    "timeout": "PT1H"
                },
                "runAfter": {
                    "Initialize_BusinessOpen_variable": [
                        "Succeeded"
                    ]
                },
                "type": "Until"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_row_is_added_to_SMS_Transactions_table": {
                "inputs": {
                    "body": {
                        "NotificationUrl": "@{listCallbackUrl()}"
                    },
                    "host": {
                        "connection": {
                            "referenceName": "commondataservice_1"
                        }
                    },
                    "path": "/datasets/@{encodeURIComponent(encodeURIComponent('https://pwcau-xxx-dev.crm6.dynamics.com'))}/tables/@{encodeURIComponent(encodeURIComponent('xxx_smstransactions'))}/onnewitemswebhook",
                    "queries": {
                        "scope": "Organization"
                    }
                },
                "type": "ApiConnectionWebhook"
            }
        }
    },
    "kind": "Stateful"
}`

### Browser

Chrome

### Additional context

Worked previously in a non-prod environment, recreated in sandpit environment and now it won't trigger. It still triggers in the pervious environment but not in sandpit even though the triggers are the exact same. 
I have since, disabled the Logic App in the other environment and recreated the trigger in sandpit but still no luck.
I saw online that it may be browser related but opened the logic app in ie and no luck.

**Comment by preetriti1** [comment]
@jordan-mulvaney-pwc-afca - Could you please share your network logs when you try to open the overview view and navigate to triggers list to view the successful triggers? You can send it to me through email psamband@microsoft.com .

Also please confirm if the issue is you see successful triggers but no runs and hence when you tried to investigate you ran into this error in portal?
