### ISSUE TITLE
All the service bus connector shapes errors in the new designer

### ISSUE THREAD

**Issue by numericscloud** [Azure/LogicAppsUX#2488]
### Describe the Bug with repro steps

All the service bus connector shapes errors in the new designer

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Screenshots or Videos

<img width="555" alt="2023-05-23 07_50_31-" src="https://github.com/Azure/LogicAppsUX/assets/19992454/0a78b1d9-2bf0-4b64-b786-f2110e7a2847">

### Browser

Any browser

**Comment by numericscloud** [comment]
Azure connector. Every thing used to work as usual in the old designer. The new designer suddenly has broken all these. So i do not belive there is any issue with how the connectors are created or configured. 
Is there a way to fall back to old designer some how. The issue has just stalled all development work on our side.

**Comment by preetriti1** [comment]
@numericscloud - PLease share your network logs and console logs from portal to my email - psamband@microsoft.com
And also workflow.json.. Also do let me know what type of connection you are using so we can try to investigate on our side.

To unblock your scenario you can use our temporary link - https://aka.ms/lafallback to use the old designer, but this will be removed soon, so we do want to see what issue is happening in your workflow with new designer.

**Comment by preetriti1** [comment]
This is the similar issue mentioned in #2490

**Comment by numericscloud** [comment]
Hi,
How do I collect the network and console logs ?

**Comment by rllyy97** [comment]
Hi @numericscloud, to get to the network and console logs you can open the DevTools with Crtl+Shift+I, then there are tabs at the top of the new panel for `Network` and `Console`.

**To get console logs**, open the `Console` tab and see if there are any red errors that appear either on loading your workflow + actions, or when you try to save.
**To get the network logs**, open the `Network` tab, then refresh the page and do your normal actions like loading and saving.  You should see a lot of entries start to appear.  When you finish trying to save, click the button shown in the screenshot attached to download the network logs into a `.har` file.

When you have the logs go ahead and email them to both [psamband@microsoft.com](mailto:psamband@microsoft.com) and myself at [rileyevans@microsoft.com](mailto:rileyevans@microsoft.com) and we can take a deeper look!

![image](https://github.com/Azure/LogicAppsUX/assets/25409734/33d514fc-003d-4cb0-a7d6-61a5329e566a)

**Comment by numericscloud** [comment]
> Hi @numericscloud, to get to the network and console logs you can open the DevTools with Crtl+Shift+I, then there are tabs at the top of the new panel for `Network` and `Console`.
> 
> **To get console logs**, open the `Console` tab and see if there are any red errors that appear either on loading your workflow + actions, or when you try to save. **To get the network logs**, open the `Network` tab, then refresh the page and do your normal actions like loading and saving. You should see a lot of entries start to appear. When you finish trying to save, click the button shown in the screenshot attached to download the network logs into a `.har` file.
> 
> When you have the logs go ahead and email them to both [psamband@microsoft.com](mailto:psamband@microsoft.com) and myself at [rileyevans@microsoft.com](mailto:rileyevans@microsoft.com) and we can take a deeper look!
> 
> ![image](https://user-images.githubusercontent.com/25409734/240403802-33d514fc-003d-4cb0-a7d6-61a5329e566a.png)

Thanks. I have shared them.

**Comment by preetriti1** [comment]
Summary on the investigation -
The connectionId referenced in the actions is on a resource group - "NL-FNLIT-INTEGRATION-SHARED-TST-WESTEUROPE-RG", while the resource group of the app itself is - "NL-FNLIT-Integration-IFS-TST-WestEurope-RG"

Today we only load connections from the resource group of the app and do not make individual calls to list the different connection ids referenced ,and since designer doesnt find the connectionid referenced in its current list it gives a invalid connection error.

In older designer we recently added this support and we can do the same in new designer. Please wait for the next release in 2 weeks when we make this update as this is not a hotfix candidate.

@rllyy97 - we will use this issue to track the connection issue and the other to show the serialization error in UI notification.

**Comment by numericscloud** [comment]
Two weeks is fine. Please ensure that the older one keeps working till this is added to the new designer else it stops our integration work completely. We extensively use referenced connections for reusability purpose and easy devops.
