### ISSUE TITLE
VSCode - Export failure

### ISSUE THREAD

**Issue by Drac-Zhang** [Azure/LogicAppsUX#2489]
### Describe the Bug with repro steps 

1. Create a Logic App Consumption as per provided workflow definition, it need to have "Azure Storage Table - Get Entities" action and a "Foreach" action. The Foreach action's input need to be entities list. 

![image](<https://github.com/Azure/LogicAppsUX/assets/72241569/81fb50eb-8d54-4b9f-91e1-ff8189e0ea59>)

2. Use VS Code Export tool to export the workflow, then we will experience the exception:

The export package URL experienced an unknown problem.

Encountered internal server error. The tracking Id is '0700895d-db2b-4755-b1e1-f8375cbcdf59'.

 

![image](<https://github.com/Azure/LogicAppsUX/assets/72241569/9cdc67a2-5035-4868-aa17-01c551b34fcb>)

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using Preview Designer or GA Designer 

Generally Available

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "For_each": {
                "actions": {},
                "foreach": "@body('Get_entities_(V2)')?['value']",
                "runAfter": {
                    "Get_entities_(V2)": [
                        "Succeeded"
                    ]
                },
                "type": "Foreach"
            },
            "Get_entities_(V2)": {
                "inputs": {
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['azuretables']['connectionId']"
                        }
                    },
                    "method": "get",
                    "path": "/v2/storageAccounts/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}/tables/@{encodeURIComponent('testtb')}/entities"
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {
            "$connections": {
                "defaultValue": {},
                "type": "Object"
            }
        },
        "triggers": {
            "manual": {
                "inputs": {
                    "schema": {}
                },
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "parameters": {
        "$connections": {
            "value": {
            }
        }
    }
}
```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

AB#24578330

**Comment by ccastrotrejo** [comment]
Hi @Drac-Zhang sorry for not replying earlier. Is this issue still happening?

**Comment by ccastrotrejo** [comment]
Closing the issue as there was no answer, if this keeps happening I will be opening the issue and take a further look on it.

**Comment by amshivraj** [comment]
Can anyone please tell, what might be the solution for this? I have been getting this error too. THe logic app has child flows and also blob and d365 related connectors..

**Comment by ccastrotrejo** [comment]
Hi @amshivraj thanks for letting us know I will take another look at this issue

**Comment by priyaamali** [comment]
Hi, I am also getting the same error like above
![git](https://github.com/Azure/LogicAppsUX/assets/69247915/935a8a1b-ff5f-46c1-8794-1a0bfd9dfee9)

**Comment by amalipriya** [comment]
Hi, I am also getting the same error like above, I am trying to export the logic app consumption to Standard using VS code, the error is not very descriptive.
![git](https://github.com/Azure/LogicAppsUX/assets/73598557/8a700bf1-c41a-4fa7-a5a7-3541a5378029)

**Comment by sona2024** [comment]
Hi, I am also getting the same error like above, I am trying to export the logic app consumption to Standard using VS code, the error is not very descriptive.
![git](https://github.com/Azure/LogicAppsUX/assets/73598557/8fd159c3-ba8b-4ee1-a03e-30c1a641413a)

**Comment by ccastrotrejo** [comment]
Hi @sonasona2024 thank you so much for sharing the screenshot. I am working to get the right exception/error from the tracking id and provide a fix or workaround to export it correctly

**Comment by sonasona2024** [comment]
**@ccastrotrejo** did you get chance to look into the issue.

**Comment by ccastrotrejo** [comment]
Hi @sonasona2024 yes I was able to trace back the issue and there is an ongoing issue with the message queue while exporting it. I will reach out to once this gets solved or the BE engineers reach out to me.
I would say that not showing the actions types in the list should matter. There is a step in the export experience which we review/validate the operations and connections and we makes sure those are exportable.

**Comment by sonasona2024** [comment]
@ccastrotrejo  Thank you very much, please let me know if there is any updates.

**Comment by BiancaOliveiraGit** [comment]
@ccastrotrejo Is there an update on the issue with exporting the message queue connector?

**Comment by ccastrotrejo** [comment]
Hi @BiancaOliveiraGit there isn't an update yet. I just revisited the issue with our backend team, and they will triage it.

**Comment by anshmathur** [comment]
@ccastrotrejo We are facing the export failure for some more logic apps that include Azure Queue and SMTP connector. Tracking ids below for reference.
![image](https://github.com/Azure/LogicAppsUX/assets/51272564/86039b0b-f931-4b27-a609-92f0ef525776)

**Comment by BiancaOliveiraGit** [comment]
@anshmathur @ccastrotrejo @sonasona2024 
I found a workaround to allow the queue connector to migrate. I discovered that the error with the queue connector was only happening on V1 of the queue connector.

**Workaround:**
In the portal, in the ‘Logic app code view’ amend all queue trigger and actions
amend all “path” properties. the main difference is the prefix /v2/storageAccounts/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}

**example:**
    "path": "/v2/storageAccounts/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}/queues/@{encodeURIComponent(concat(parameters('env'),parameters('active_queue_prefix'),parameters('queue_contactus')))}/message_trigger"
 
Save the workflow & now will be able to migrate using the VS Code extension tools.

**Comment by BiancaOliveiraGit** [comment]
@anshmathur  my only suggestion is to ensure that you also have 'queues' apart of that append string. if that still doesn't work then yes "replace with another action/trigger" to spot the difference
![image](https://github.com/Azure/LogicAppsUX/assets/34118796/72ed759a-2337-4bba-9d25-176ccd60c6c7)

**Comment by anshmathur** [comment]
Thanks @BiancaOliveiraGit. I was a bit ignorant when I tried it initially, I didn't look at the entire "path" format. Yes your suggestion on path is spot on, it resolved the issue with export.

`/v2/storageAccounts/<StorageAccount Name>/queues/<Queue Name>/message*`

**Comment by ccastrotrejo** [comment]
Hi all, can anyone verify if this issue is still going on?

**Comment by ccastrotrejo** [comment]
I will close this issue, if this keeps happening I will take a further look and re open it

**Comment by Sabejjam** [comment]
> I will close this issue, if this keeps happening I will take a further look and re open it

Hi @ccastrotrejo, Do we have an update on the issue with exporting the message queue connector?

**Comment by Sabejjam** [comment]
I'm facing the same issue, the workaround didn't worked for me unfortunately!
I do have different connectors in my logic apps so not sure which is actually causing the issue, validation of the operations and connections are all successfull.
![image](https://github.com/user-attachments/assets/53a9a8be-4b01-432a-9c88-9514577e6adf)

**Comment by TimoKarhu** [comment]
Hi yes, I have it happening on "Exec SQL Query V2" which was not healthy on the source lga. If possible, the error message on the exporter might be more informative. Perhaps not in your hands.
Now that we know it, one should always check for connectors in case of "exception" in the exporter.

Thanks!
