### ISSUE TITLE
Save option not working after updating the designer

### ISSUE THREAD

**Issue by numericscloud** [Azure/LogicAppsUX#2490]
### Describe the Bug with repro steps

1. Open designer
2. Designer load shows errored out connector
3. When selecting another queue or topic the listing from SB works
4. Update the param in connector ex- another queue or topic.
5. Try saving the design
6. Save does not do any thing

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Screenshots or Videos

<img width="732" alt="2023-05-23 08_10_42-holidaycalendar-copies-fetch - Microsoft Azure" src="https://github.com/Azure/LogicAppsUX/assets/19992454/2e2fcc82-a44c-41b1-9c3f-9cbce46e92e0">

### Browser

All

**Comment by numericscloud** [comment]
The connection is shown invalid at design time but at runtime it works.
This was working in the old designer.
The connection is an api connection type in shared rg. Logic app connection refers this shared api connection.
I belive the new designer is not yet ripe enough for such referential connection.

If I create another connection that gets created inside the la itself which is not desired as we are reusing the connection across many logic apps..

**Comment by numericscloud** [comment]
No feedback at all. I do see number of errors in js runs in the logs. I have shared network and console logs for further analysis.

**Comment by SharpLava** [comment]
Seeing a similar issue as @numericscloud 

Context:
- Was working in Old Designer
- New service bus task cannot be saved
- Old service bus tasks if unedited still work in the workflow. 
- Using Logic App Standard 
- Using Azure Service Bus Connector

Error Message:
- Workflow validation failed for the workflow 'wf-floc-to-intellipermit-subscriber'. {"error":{"code":"InvalidTemplate","message":"The template validation failed: 'The template action 'Send_failed_message_to_MonitorLogger_Queue' at line '1' and column '5475' is not valid: \"Unable to parse template language expression 'base64(concat({Redacted JSON}))': expected token 'RightParenthesis' and actual 'Identifier'.\".'."}}

**Comment by preetriti1** [comment]
@numericscloud - We have the fix for silent failures where it will show as notifications, this should be available in production in about 2 weeks as part of our normal release.
