### ISSUE TITLE
Unable to Scroll Horizontally Using Shift and Scroll Button in Logic App Designer canvas and in executed runs' canvas

### ISSUE THREAD

**Issue by AkshayAmbekar26** [Azure/LogicAppsUX#2491]
### Describe the Bug with repro steps

1. Go to logic apps.
2. Open any standard logic app's Designer or latest executed run.
3. Try scrolling horizontally using Shift and the scroll wheel.

After the recent update to the Azure Portal's Logic App UI, the ability to scroll horizontally using the Shift key and mouse scroll button seems to be non-functional. 
Previously, we could navigate horizontally within the Logic App designer canvas, making it easier to work with wider workflows. However, the functionality appears to have been affected by the UI update.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

Microsoft Edge

**Comment by rllyy97** [comment]
This is currently not working in the node library we use (ReactFlow), I've created a bug report on their repo https://github.com/wbkd/react-flow/issues/3099
Once they have it enabled on their side we will be able to implement in Designer 👍
