### ISSUE TITLE
Unable to revert back to GA Designer

### ISSUE THREAD

**Issue by john-long2** [Azure/LogicAppsUX#2493]
### Describe the Bug with repro steps

Hi,

I logged the issue below which I believe will be fixed in 2 weeks.  
https://github.com/Azure/LogicAppsUX/issues/2481

There does not seem to be a way to revert to the GA designer in the mean time.  

The bug 2481 makes the designer to slow to use in production. So I need to revert back to GA please.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Edge

**Comment by john-long2** [comment]
Hi Riley,

That's brilliant thank you.  I will keep using the preview designer then use your URL if I need to refactor.  

I have to say I really like the new designer (except the issue) it is a lot easier to use and feels more modern.

Many Thanks
John

**Comment by sladeyman** [comment]
this URL works a treat - thanks
when you say  "temporary fallback" - what do you mean ? Weeks, months....or worse, hours.

**Comment by Eric-B-Wu** [comment]
> this URL works a treat - thanks when you say "temporary fallback" - what do you mean ? Weeks, months....or worse, hours.

There's no current date, but we do plan to remove it once all the known blockers of new designer is resolved

**Comment by hartra344** [comment]
I am closing this since there are no action items left on this issue. As for the temporary fallback, like Eric said above, it will be there until we're confident that the customer issues we've found are fully resolved in production.
