### ISSUE TITLE
Logic App Standard - Designer error - Multiple identities

### ISSUE THREAD

**Issue by JefSeys** [Azure/LogicAppsUX#2496]
### Describe the Bug with repro steps

Hi all,
We have been working with multiple managed identities in Logic App Standard to increase our security. The past 2 weeks, we have the issue that when we open a run or the designer, we receive the error: Invalid Number Of User Identities (see screenshot below).
The workflows still work, we are just not able to view them which is a big problem when we have issues and/or need to debug a run.
To reproduce:
1. Add multiple User Assigned Managed Identities to a Logic App Standard.
2. Open the designer or a run of a workflow.

We do not have a workaround at the moment.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/47564347/be45bad7-b37c-4ad5-a379-b8279befad28)

### Browser

Brave, google chrome

**Comment by preetriti1** [comment]
@JefSeys We have deployed hotfix for this issue, so it should be fixed now. Please reopen the issue if it still exists
