### ISSUE TITLE
LA Standard New Designer breaks when changing an action name created in legacy designer

### ISSUE THREAD

**Issue by PedroAlmeidaMS** [Azure/LogicAppsUX#2497]
### Describe the Bug with repro steps

Go to Logic App Workflows
- open Designer
- Change the default name for an action created in legacy designer
- UI breaks.
- If name is rolled back, UI is restored.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/112867201/d4373922-edb1-4fac-b6f1-456055d76303)

### Browser

Edge, Chrome

**Comment by preetriti1** [comment]
@PedroAlmeidaMS - Please share the workflow.json and what action name has been changed to what?

**Comment by PedroAlmeidaMS** [comment]
@preetriti1 Cannot share full JSON, due to confidential information. Please reach out internally to me.

Default name of "Set Variable 1" was changed to "When Failed" and UI crashed.

**Comment by Eric-B-Wu** [comment]
There's an ICM on this, with the workflow, took a look seems like react flow is stuck in a loop, and the error ends up being Maximum Call Stack Exceeded

**Comment by rllyy97** [comment]
This has been fixed with https://github.com/Azure/LogicAppsUX/pull/2565
We will be releasing a hotfix today that will include this fix!
