### ISSUE TITLE
Invalid error message on failing action

### ISSUE THREAD

**Issue by ViggoL** [Azure/LogicAppsUX#2498]
### Describe the Bug with repro steps

1. Have a compose action that references multiple properties of an object
2. Pass an undefined object

The action will show the error message "undefined, undefined" instead of an aggregate exception.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

**Comment by preetriti1** [comment]
@ViggoL - can you please attach some.screenshits on where you are seeing this? Is this monitoring?

If yes, can you share some network logs when load the view. You can send them to me psamband@microsoft.com

**Comment by preetriti1** [comment]
@ViggoL - Since there has been no update on getting the info, we are closing this issue. Please reopen if you still face this and then you can provide detais.
