### ISSUE TITLE
Run History not showing Actions Inputs/Outputs

### ISSUE THREAD

**Issue by shboulatom83** [Azure/LogicAppsUX#2499]
### Describe the Bug with repro steps

1. Go to Workflow Runs History
2. Open any Run
3. Try to view any Actions Inputs/Outputs
4. It fails with "Error to Load" error

Checking HAR Traces, it shows Bad Request calling the ActionsInputs
Checking Console Traces, it shows CORS errors

Adding https://portal.azure.com to LA CORS settings resolved the issue

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome
Edge

**Comment by preetriti1** [comment]
@shboulatom83 - If this is resolved now i am closing this issue, please reopen if something needs to be worked at.

**Comment by hartra344** [comment]
Temporary Workaround: Add https://portal.azure.com to your apps CORS rules.

Fix next release: We will provide the option to do this automatically when we detect this error. This is a bigger fix than we would ike to include in a hotfix though.

**Comment by hartra344** [comment]
We have added a dialog with instructions to fix this in a hot fix. In the next release or 2 (depending how complicated it ends up being to do) we will have an option to have this done on your behalf to fix the issue.
