### ISSUE TITLE
Non-unique switch cases and child actions causes crash

### ISSUE THREAD

**Issue by sladeyman** [Azure/LogicAppsUX#2500]
### Describe the Bug with repro steps

1 : go to Workflow
2 : Click Code view : no issues
3 : click DESIGNER 
4 : Error message "The renderComponentIntoRoot component encountered an error while loading." and the Designer fails to load. 
5 : NO OPTION to use GA Designer or PREVIEW 

the Designer is now the PREVIEW one and no option to use the old one, 

Causing MAJOR ISSUES  - happening in ALL environments. 

Cleared cache, mutliple Devs reporting the same issue. 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
Will not let me ADD - too long

it has some SWITCHEs and HTML in - worked perfectly on the old designer.
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/84184326/486d3a2b-0b65-4ab1-b8c1-3047af73ddc4)

### Browser

All tried

**Comment by rllyy97** [comment]
Hi @sladeyman, this appears to be a standard workflow from the screenshot you attached, would you mind sharing the HAR / network trace from when you load designer so we can troubleshoot where the error is coming from?

**Comment by sladeyman** [comment]
seems to be to big - "message": "Maximum call stack size exceeded", "name": "RangeError" }, "errorInfo": { "componentStack": "\n at d$

however, it worked a treat n the old designer.

**Comment by sladeyman** [comment]
it will also now longer load in VS code

**Comment by sladeyman** [comment]
hey guys  - this is RESOLVED

We have just fixed this by Renaming the CASES and ACITONS to have unique names. And this has fixed the issue. 

In case any one else has this - The Case( switch name ) and any subsequent actions must be unique for the that case. i.e - if the CASE is SEND EMAIL - then none of the actions should be called SEND EMAIL. 

Remember to HARD RESET (cntl + f5 ) broswer - and hey presto - it works.

**Comment by rllyy97** [comment]
I'm glad you got it resolved!  I will keep this open since other's might experience the same issue for now, we're working on a fix and will close this ticket once we're confident this will not crash in new-desinger

**Comment by rllyy97** [comment]
This has been fixed with https://github.com/Azure/LogicAppsUX/pull/2565
We will be releasing a hotfix today that will include this fix!
