### ISSUE TITLE
Excel Business object - No Files

### ISSUE THREAD

**Issue by agonzalezroyal** [Azure/LogicAppsUX#2501]
### Describe the Bug with repro steps

1- Go to Logic Apps
2- Create any Excel Business object that needs a File (Path)
3- Select a valid location, valid Document Library
4- Try to look for a File.

Result: It will no show files, nor folders.

![image](https://github.com/Azure/LogicAppsUX/assets/134408554/1f652865-6920-42bc-b17e-4747461d0a25)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Edge

**Comment by preetriti1** [comment]
@agonzalezroyal - This is only supposed to show excel sheets so files with .xlsx extensions, if your folder does not have any then it will show No Items

![image](https://github.com/Azure/LogicAppsUX/assets/48265693/057c7154-4df4-4c5e-88f8-8123930973c8)

**Comment by agonzalezroyal** [comment]
@preetriti1 Yes, for me it is working on Power Automate, however this specific flow on Logic apps stopped working yesterday out of nowhere.
Now I can't select files, and there are files, they show up on Power Automate with the same object, and they were showing up on Logic Apps 2 weeks ago.

**Comment by preetriti1** [comment]
@agonzalezroyal - Since no data has been provided for 2 weeks now, we are going to close this issue. If you are still facing this please reopen this and provide the details as asked above.

**Comment by Eric-B-Wu** [comment]
this issue was happening because we were not using folders in file picker, should have been fixed in https://github.com/Azure/LogicAppsUX/pull/2603
