### ISSUE TITLE
VS Code : Unable to deploy workflow from VS code to logic app.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2504]
### Describe the Bug with repro steps

1. Create a new Logic App Project
2. Add a workflow to your local project
3. Open the workflow.json file in designer and author a new workflow
	a. Add http request Trigger
	b. Add a compose action here with custom text
	c. Add a ServiceBus action. From the add new paramter dropdown add content and add random text in JSON format like {"a":"b"}
	d. Add a send email action with the body being the output of the compose action (step b)
	e. Add a new connection to your email action
	f. Add http response action
4. Press F5 to build and run your project
5. Run the workflow
	a. Open overview page. Right + Click on workflow.json file and "Overview"
	b. Copy call back URL from the overview page
	c. Send the http request POST via Postman and wait for the response
6. Refresh the overview page and your should see your local run
7. Open the monitoring view for your run from the overview page
8. Verify the run details and action inputs and output
9. Deploy to Azure
10. Enter the deploying logic app name
11. We need to get the next page to enter other details after entering the name.
12. Enter name of deploying logic app and details of logic app, deployment should be success. 

**Expected :** Enter name of deploying logic app and details of logic app, deployment should be success. 
**Actual :** Unable to deploy workflow from VS code to logic app getting this error
" 5:07:41 PM: Error: Error in creating access policy for connection in reference - 'office365-2'. Error: Error in getting connection - /subscriptions/@appsetting('WORKFLOWS_SUBSCRIPTION_ID')/resourceGroups/@appsetting('WORKFLOWS_RESOURCE_GROUP_NAME')/providers/Microsoft.Web/connections/office365-8. Error: The provided subscription identifier '@appsetting('WORKFLOWS_SUBSCRIPTION_ID')' is malformed or invalid.".

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/595a3251-30db-40f5-87c0-ba3f4c8cb84c)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/fea34a66-5b16-4080-b046-c240f0e5aafa)

### Browser

VS Code

### Additional context

**Artifacts details:**

1.	VS Code extension:   vscode-azurelogicapps-2.18.0.vsix
2.	NuGet package:  [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RAdRQgUdZRVaGVezHUCgOrk9dqDH%2FroCbmRi3G6qINE%3D&reserved=0)
3.	Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p4gGTn5fIyNqeVEkRK0OAoJKnFiRCvk%2BDcxOO2g%2BJck%3D&reserved=0)
4. Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.23.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.23.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C1315cce631bf4e88b67a08db5b43d604%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638204119230399009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O9utopA3qZWwqlBv1b200p9ZE0vBZgPMR84gQlrP%2F%2Bc%3D&reserved=0)

AB#24341318

**Comment by vgouth** [comment]
Issue Repro in the latest request
**Artifacts details:**

1.VS Code extension:   vscode-azurelogicapps-2.18.1.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RAdRQgUdZRVaGVezHUCgOrk9dqDH%2FroCbmRi3G6qINE%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p4gGTn5fIyNqeVEkRK0OAoJKnFiRCvk%2BDcxOO2g%2BJck%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.23.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.23.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C1315cce631bf4e88b67a08db5b43d604%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638204119230399009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O9utopA3qZWwqlBv1b200p9ZE0vBZgPMR84gQlrP%2F%2Bc%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/0bdc7001-f8c0-4d9f-b870-7a0f076c3a4a)

**Comment by ccastrotrejo** [comment]
I was able to repro this issue, I will update it once I fix it
