### ISSUE TITLE
VS code: Taking longer time to load logic apps in resources blade and creating the logic apps from it.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2505]
### Describe the Bug with repro steps

1.Create a new workflow app using VS Code.
2.Create a stateful/stateless workflow
3.Open the workflow.json file in designer and author a new workflow.
4.Save, debug and run it.
5.Create a logic app from logic apps tree in resources blade.
6.**Expected:** Should able to load create the logic app page in less than 5 minutes.
**Actual:** It is taking more than 20-25 minutes to load the inbuilt logic apps and when we try to create the logic app from the  logic apps tree in resources blade it is taking much longer time to load the options.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/1f814ba6-85ef-448f-b290-10a1c13ae351)

### Browser

VS Code

### Additional context

**Artifacts details:**

1.	VS Code extension:   vscode-azurelogicapps-2.18.0.vsix
2.	NuGet package:  [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RAdRQgUdZRVaGVezHUCgOrk9dqDH%2FroCbmRi3G6qINE%3D&reserved=0)
3.	Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p4gGTn5fIyNqeVEkRK0OAoJKnFiRCvk%2BDcxOO2g%2BJck%3D&reserved=0)
4. Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.23.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.23.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C1315cce631bf4e88b67a08db5b43d604%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638204119230399009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O9utopA3qZWwqlBv1b200p9ZE0vBZgPMR84gQlrP%2F%2Bc%3D&reserved=0)

**Comment by vgouth** [comment]
**Issue repro in latest request:** 
1.VS Code extension: vscode-azurelogicapps-2.18.1.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RAdRQgUdZRVaGVezHUCgOrk9dqDH%2FroCbmRi3G6qINE%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p4gGTn5fIyNqeVEkRK0OAoJKnFiRCvk%2BDcxOO2g%2BJck%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.23.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.23.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C1315cce631bf4e88b67a08db5b43d604%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638204119230399009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O9utopA3qZWwqlBv1b200p9ZE0vBZgPMR84gQlrP%2F%2Bc%3D&reserved=0)

**Comment by vgouth** [comment]
Issue repro in the latest request

**Artifacts details:**

1.**VS Code extension:** [vscode-azurelogicapps-2.24.3.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEUtS0SJECrFDgEfY_BSfFlsBSqFEmGM2jMuz1uN88uqHrQ%3Fe%3D62D7LG&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OVYmk3G26RGfYDI3aar3hdiReVK%2FawmoHwg5OiWHcCQ%3D&reserved=0)
2.**NuGet package:** [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MTk5ODA4L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.25.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MTk5ODA4L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.25.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=upITg%2FkMqauS7sUHSrAVwYfm0O4KeY65yeH%2BBqsjjUY%3D&reserved=0)
3.**Extension Bundle (CDN URL):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iXPu8J3jR6BDSNcAoxbr2aDU%2BZvRu6kj0Anmv11HhoA%3D&reserved=0)
4.**Extension Bundle (Direct Download):** [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MjAxMjgxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.25.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MjAxMjgxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.25.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BfSH60Z%2BMvx93kjvByWQcds3yW4KDimY9naPq2e23oc%3D&reserved=0)

**Comment by ccastrotrejo** [comment]
Hi, I am going to close this issue as the times are proportional to the amount of logic apps the cx has. It is expected to improve performance when changing the inner architecture to Azure Resources API v2. Here is a github task to keep track of the work https://github.com/Azure/LogicAppsUX/issues/2219
