### ISSUE TITLE
Logic App Standard - Portal - Microsoft Dataverse (legacy) Connector -  New designer deletes the "body" attribute

### ISSUE THREAD

**Issue by JonMarr** [Azure/LogicAppsUX#2509]
### Describe the Bug with repro steps

Open any existing Logic App with a Microsoft Dataverse (legacy) Connector in it and save. The "body" is deleted from the API JSON for that connector.

There are no errors in the console. I see this issue Edge and Chrome.

May be same as Issue #2475 that I previously reported.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
"Add_Row": {
	"inputs": {
		"body": "@item()",
		"headers": {
			"organization": "@parameters('CRMEnvironment')",
			"prefer": "return=representation,odata.include-annotations=*"
		},
		"host": {
			"connection": {
				"referenceName": "commondataservice_1"
			}
		},
		"method": "post",
		"path": "/api/data/v9.1/@{encodeURIComponent(encodeURIComponent(triggerBody()['EntityApiName']))}"
	},
	"type": "ApiConnection"
}
```

### Browser

Edge and Chrome

**Comment by preetriti1** [comment]
@JonMarr - Are you seeing same error in teh UI that dynamic content call failure?

**Comment by JonMarr** [comment]
No. There is no error message in the designed properties blade and no errors in the browser console. The designer properties window just doesn't show the body attribute even though it is in the code. Then when you save the body attribute is missing in the code view.
________________________________
