### ISSUE TITLE
Dataverse Connector: Error in Bound Action "AddMemberList" for Table "Marketing List" 

### ISSUE THREAD

**Issue by berellax** [Azure/LogicAppsUX#2512]
### Describe the Bug with repro steps

When following the steps below, get an error that the parameter is not valid. However, when manually manipulating the JSON to rename the parameter "EntityId" instead of "body/EntityId" the action is successful. This needs to be updated in the connector action so that the call can work correctly.

**Steps**
1. Create a Logic App
2. Add an action for Dataverse > Bound Action.
3. Table = Marketing List, Action = AddMemberToList
4. Row Id = Marketing List Id
5. body/EntityId = Record to Add

**Error**
"Error identified in Payload provided by the user for Entity :'', For more information on this error please follow this help link https://go.microsoft.com/fwlink/?linkid=2195293  ---->  InnerException : Microsoft.OData.ODataException: The parameter 'body/EntityId' in the request payload is not a valid parameter for the operation 'AddMemberList'.\r\n   at Microsoft.OData.ODataParameterReaderCore.GetParameterTypeReference(String parameterName)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightParameterDeserializer.<>c__DisplayClass3_0.<ReadNextParameter>b__0(PropertyParsingResult propertyParsingResult, String parameterName)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightParameterDeserializer.ReadNextParameter(PropertyAndAnnotationCollector propertyAndAnnotationCollector)\r\n   at Microsoft.OData.ODataParameterReaderCore.ReadImplementation()\r\n   at Microsoft.OData.ODataParameterReaderCore.InterceptException[T](Func`1 action)\r\n   at Microsoft.Crm.Extensibility.ODataV4.CrmODataActionPayloadDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)."

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Edge

**Comment by berellax** [comment]
I’m able to save the workflow just fine and it fails on the run. It runs fine when I manually update the parameter to EntityId instead of body/EntityId.  Sent from my iPhoneOn May 23, 2023, at 7:55 PM, preetriti1 ***@***.***> wrote:﻿
@berellax - It is not clear on what is not working here, Are you able to save the workflow with your changes and workflow run fails?
Or the workflow save itself is failing?

**Comment by preetriti1** [comment]
@berellax - Can you please share network logs in your scenario so we know from where body/EntityId if coming from? We will need that info to see why those parameters were returned from connector.

You can share the logs to me on my email psamband@microsoft.com
