### ISSUE TITLE
Azure Function Integration with Logic App

### ISSUE THREAD

**Issue by mukulgpt17** [Azure/LogicAppsUX#2514]
### Describe the Bug with repro steps

I am adding Azure Function Connector in Preview Designer. 
When I try to add new Connection , there is no option to select a function App 
While in General Available I do get the Option to add new Connection with all available function APP .

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

1. Trying to connect to Function App 
<img width="413" alt="Function_Page" src="https://github.com/Azure/LogicAppsUX/assets/54761322/36a0ff98-2282-45ed-957a-9c3c486bbb3c">
2. Shows no possible options even when multiple function app exists in same subscrption and resource group 
<img width="490" alt="Data_Preprocessing_img" src="https://github.com/Azure/LogicAppsUX/assets/54761322/c343b92a-21a3-47a9-8fb9-64032f448267">
3. Multiple Function exists in same resource group and subscription 
<img width="912" alt="Function_options_2" src="https://github.com/Azure/LogicAppsUX/assets/54761322/ea0f8dc3-2290-43ca-9b5b-779df8aad623">

_No response_

### Browser

Edge

**Comment by preetriti1** [comment]
@mukulgpt17 - Is this LA standard? I do see the option to change connection to select an app
![image](https://github.com/Azure/LogicAppsUX/assets/48265693/580930bf-c292-4f38-bc81-787c15fff156)

Are you not seeing the link in the parameters like below ?
![image](https://github.com/Azure/LogicAppsUX/assets/48265693/ba101582-1712-469c-8f62-00c8e0bf8f26)

Please provide some screenshots

**Comment by mukulgpt17** [comment]
1.  In Logic App (Standard) I try to use the Function App 

<img width="413" alt="Function_Page" src="https://github.com/Azure/LogicAppsUX/assets/54761322/4df2881c-e06a-492c-9680-21a44a544938">

2. But Once I try to create new connection it is not showing any possible Function App which i have created in the same subscription . 

<img width="490" alt="Data_Preprocessing_img" src="https://github.com/Azure/LogicAppsUX/assets/54761322/5e8e99e7-8c2c-4641-a716-932aa599bc71">


3 . There are multiple Function within Same subscription and resource group within which the Logic App (Standard) is created . 

<img width="912" alt="Function_options_2" src="https://github.com/Azure/LogicAppsUX/assets/54761322/a2ed23cb-51e1-4e7b-b2f7-926707e7dc11">

**Comment by preetriti1** [comment]
It seems this is related to the incident we have where some function app kinds were not listed in the dropdown. @mukulgpt17 - Can you confirm the app kind you have set in these functionApps are not just 'functionapp' and have something more in addition?

**Comment by mukulgpt17** [comment]
@preetriti1 the app kind of all the apps are of type function app only ! 
App Type : Function App
