### ISSUE TITLE
Preview tag is missing on actions for the Service Providers (SAP, Service Bus, Cosmos)

### ISSUE THREAD

**Issue by divyaswarnkar** [Azure/LogicAppsUX#2520]
### Describe the Bug with repro steps

Browse the Service Providers from Logic Apps Standard. 

Expected - Actions to me marked Preview
Observed - No Preview tag

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

**Comment by preetriti1** [comment]
@divyaswarnkar - are we only expecting the tag to show up while searching operations or even after selecting the operations in the panel view. The old designer did not have it in panel view so confirming.
