### ISSUE TITLE
Unable to see properties of cloudmersive connector

### ISSUE THREAD

**Issue by punjabisingh** [Azure/LogicAppsUX#2526]
### Describe the Bug with repro steps

In existing or new worklow click on + icon to add new Action then search cloudmersive and select any action. you will notice it does not load properties also existing workflow with cloudmersive also doesnt load any properties and shows its invalid connection. thank you.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

Edge, Chrome

**Comment by preetriti1** [comment]
@punjabisingh - Please share more details - There are multiple cloudmersive connectors, which connector you are using and which operation.
Also having a screenshot is helpful for our investigation else we cannot proceed.

Can you also confirm the following -
1. when new action is added, does it show any connection error or any erorr in the card saying dynamic inputs cannot be loaded?
2. When you load existing definition, what type of error it shows.

Screenshots in both the above points will help us to investigate further

**Comment by preetriti1** [comment]
@punjabisingh - Please reopen this issue when you can provide information. We are going to close on this since without the details we cannot investigate it yet.
