### ISSUE TITLE
JavaScript error in designer for Azure DevOps connector

### ISSUE THREAD

**Issue by markpjohnson** [Azure/LogicAppsUX#2532]
### Describe the Bug with repro steps

1. Go to a workflow with an Azure DevOps connector that uses the "Update a work item" action. 
2. Locate the connector and see that it shows a JavaScript error message: `Failed to retrieve dynamic inputs. Error details: 'e.charAt is not a function'`.
<img width="169" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/469737/d0bc7664-c5c1-4a49-bafe-eb19f2996d8e">

3. Open the action to edit the fields and see the error message again. 
<img width="464" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/469737/051e885f-3a45-4a2c-94c9-11ecf432e502">

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Workflow JSON

```json
Can provide the workflow JSON privately.
```

### Browser

Chrome and Edge

**Comment by preetriti1** [comment]
@markpjohnson - Do you mind sharing just the definition part of this failing action, we can know what might have failed if not failing the entire workflow.json. Also what type of connection are you using? Do you see any network call failures?

**Comment by preetriti1** [comment]
@markpjohnson - We are going to close on this issue since no details have been received on this yet. As mentioned above, the network traces or definition would help us to repro this issue, once you have it you can send it to psamband@microsoft.com and reopen this issue.
