### ISSUE TITLE
VS code: Taking longer time than expected to deploy workflow from VS code to logic app only in NuGet Artifact.  

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2533]
### Describe the Bug with repro steps

1.Create a new workflow app using VS Code.
2.Create a stateful/stateless workflow
3.Open the workflow.json file in designer and author a new workflow.
4.Add http request trigger.
5.Add Inline javascript action and add a Response action, where the body is the output from the Run in-line JavaScript action (Inline javascript test case)**or else** add some parameters with request and any action like response or compose(workflow parameters test case).
6..Save, debug and run it.
7..Create a logic app from logic apps tree in resources blade.
8.Deploy the workflow from VS code to logic app in NuGet Artifact. 
9..**Expected:** Should able to deploy the workflow from VS code to logic app in NuGet Artifact within less than 10min. 
**Actual:** It is taking more than 45-50 minutes to create a zip package and deploy the workflow from VS code to logic app **only in NuGet Artifact**.

**Note:** Issue repro only in nuget artifact, to create a zip package and deploy the workflow, but the deployment is getting success enough though it is taking longer time by getting the error as shown below.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/a5cac684-062c-47c6-af5b-58c746497919)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/a2c4998d-9fa1-49f0-9854-f0fe65728dea)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/6e473f5e-425d-4fbf-bf78-6c7fa1476b0b)

### Browser

VS Code

### Additional context

**Artifacts details:**

1.VS Code extension: vscode-azurelogicapps-2.18.0.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RAdRQgUdZRVaGVezHUCgOrk9dqDH%2FroCbmRi3G6qINE%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccf9ef638c13d4314ddd508db5b1ec41b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638203960055792316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p4gGTn5fIyNqeVEkRK0OAoJKnFiRCvk%2BDcxOO2g%2BJck%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.23.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.23.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C1315cce631bf4e88b67a08db5b43d604%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638204119230399009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O9utopA3qZWwqlBv1b200p9ZE0vBZgPMR84gQlrP%2F%2Bc%3D&reserved=0)

**Comment by ccastrotrejo** [comment]
That specific process of creating the zip package and uploading is done via the [VSCode Azure SDK for Node.js](https://github.com/Microsoft/vscode-azuretools/blob/main/appservice/README.md) package. After analyzing it, it might be taking so much time due to the internet upload speed.  I put a `known issue` label on this in the meantime we discuss on this with the team,

**Comment by vgouth** [comment]
Internet upload and download speed is 20MBPS.
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/3a305300-9f32-45cf-bd87-dd1bf8832193)

**Comment by ccastrotrejo** [comment]
I had a talk with one of the team members of App Service Tools. The amount of time will totally depend on the project size and the internet speed. As for now, they aren't sure how they can improve the performance of it. But I will keep this open as a known issue.
