### ISSUE TITLE
VS Code_Drag/Drop: Parent action can not be drop after dependent action.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2534]
### Describe the Bug with repro steps

1.Create a Stateful workflow and open the Designer.
2.Add Http trigger and add Dropbox and add compose.
3.Add Dropbox token into compose create a dependent action to compose.
4.Add some more compose action after step 2.
4.Try to Drag the Dropbox and drop in between step 4 compose actions.

**Expected:** Drag and drop can not happen in this above case with Dropbox.

**Actual:** It is happening, we can drop the Dropbox action after its dependent card.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/0b960bc5-ba31-4454-b69c-ce2367951787)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Browser

VS Code

### Additional context

VS Code extension: ​vsix icon[ vscode-azurelogicapps-2.18.0.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEc8yVWvWBQVMq9sIUdAMFI4BOqiDxKUuekGKLbBo8DqENw%3Fe%3D4g255G&data=05%7C01%7Cv-prakumar%40microsoft.com%7C67303909c6d346700de308db5c2beeec%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638205116034802806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CFsXykgjicPk278eFUNktEfN4cgmXRxv%2FnJyqZDmd1Y%3D&reserved=0)
NuGet package:  [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzczNTE1ODYzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.23.1.nupkg&data=05%7C01%7Cv-prakumar%40microsoft.com%7C67303909c6d346700de308db5c2beeec%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638205116034802806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VpAXOhMsJxQkiSnG%2FVfLGKgtXhwyxYdFypUNCeXpBpc%3D&reserved=0)
Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-prakumar%40microsoft.com%7C67303909c6d346700de308db5c2beeec%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638205116034802806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UEhP%2BaaUAWshDSkVCL0CEmDaTToH8z9MgoDARXYQObQ%3D&reserved=0)

Adding the Extension Bundle (Direct Download):

 

[https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.23.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.23.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.23.1_any-any.zip&data=05%7C01%7Cv-prakumar%40microsoft.com%7C67303909c6d346700de308db5c2beeec%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638205116034802806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZzoTBT0mvPd0FFh7cmBY5eOFZqYhxZIY%2FY4geWUzMmQ%3D&reserved=0)

**Comment by hartra344** [comment]
This is listed in known issues

**Comment by v-prakumar** [comment]
@Eric-B-Wu Issue is seen in the portal too.
Environment Details:

URL: [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-prakumar%40microsoft.com%7Cb13bdbce753c4d10e4d208db602642f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638209489716975513%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FswWQgvfri89yLEtw%2FlHDefgpxb00ZefQi38bh%2Bmn8s%3D&reserved=0)

Version: 2.30529.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/92098490/388368aa-1530-4937-8175-8be15ba3914a)

**Comment by v-prakumar** [comment]
@eric-azure Issue is repro in the version:  2.30701.1.1

**Comment by vgouth** [comment]
Issue is repro in the latest request

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccaeede01bc6247df730608db899fa56e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638255091053826394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XkVfWg4QCG8m1pHWR2lnWsaUSDKt3WPkUseVXK7UwVY%3D&reserved=0)
**Version:** 2.30717.1.1

**Comment by ramya894** [comment]
Issue repro in the latest request.

1. **VS Code extension** - ​vsix icon[ vscode-azurelogicapps-2.69.0.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/EeRUYYoqyrZPtK9ZvXk0xcQBG35zXPOj8q8xsyuAvEOuTw?e=H37L8f&xsdata=MDV8MDF8di1pdHJhbXlhQG1pY3Jvc29mdC5jb218MzgwZmFkN2FjODg1NDM5NWQ3NGMwOGRiYmViOWVjN2Z8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODMxMzQ3ODEwMjUwMjkwNHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=NDd4R0dNUWIwYkVvdS9yY0xpVkN0Q3BxZk5GbXlJcGVBTGxIelFaeEFCST0%3d)

2. NuGet package:  [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgwMDY5MTEwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.41.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgwMDY5MTEwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.41.1.nupkg&data=05%7C01%7Cv-itramya%40microsoft.com%7C380fad7ac8854395d74c08dbbeb9ec7f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313478102502904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o%2BlAsxRzTDKHRvX6lTsZq96Qh5YfHtWEao6ggJ9eGuU%3D&reserved=0)

3. Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-itramya%40microsoft.com%7C380fad7ac8854395d74c08dbbeb9ec7f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313478102502904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YCckocAD30k%2FEga%2FU5PB5yAMuAZcNUaotN3JHs6%2Fzfc%3D&reserved=0)

4. Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.41.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.41.1_any-any.zip</p](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.41.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.41.1_any-any.zip%253c%2Fp&data=05%7C01%7Cv-itramya%40microsoft.com%7C380fad7ac8854395d74c08dbbeb9ec7f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313478102502904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DuzEjg555AC5xNR1FR%2FsIdifpwmDQP1G%2FYE%2FsZkICk0%3D&reserved=0)>

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/ce74e05e-7632-45ca-b33d-3ae4470dc6fb)
