### ISSUE TITLE
Copy variables content with variables

### ISSUE THREAD

**Issue by garethterb** [Azure/LogicAppsUX#2541]
### Describe the Bug with repro steps

If I I have a variable that contains text plus variables in it I used to be able to copy the content and paste it into notepad and edit it in notepad. With the new design when I copy and past the content into notepad the variables are not stripped out.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome Version 113.0.5672.127 (Official Build) (64-bit)

AB#24188720

**Comment by preetriti1** [comment]
@garethterb - Is it possible for you to share the pasted content what you used to have in the old design and what you see in the new design?

**Comment by garethterb** [comment]
@preetriti1 - This is how it pastes now: <SubmittedBy></SubmittedBy>
and this is how it used to paste: <SubmittedBy>@{xpath(xml(variables('xml')),'string(//Name)')}</SubmittedBy>
