### ISSUE TITLE
Copy Paste action/shape doesn't work.

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2542]
### Describe the Bug with repro steps

Create a workflow with actions and try copying and pasting actions within a workflow.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome
Edge
VSCode

**Comment by hartra344** [comment]
THis is a feature we're considering in the future but this has never been supported, and we don't yet have an ETA for this.
