### ISSUE TITLE
Invoke workflow's input parameters don't appear in VSCode but they do appear on the portal

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2544]
### Describe the Bug with repro steps

Create workflow1 which expects input parameters.
Create workflow2 which invokes workflow1

do this in VSCode and on the Portal 

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Browser

VSCode
Edge
Chrome

**Comment by ccastrotrejo** [comment]
Closing this as duplicate of #2426

**Comment by ccastrotrejo** [comment]
Hi @mhireholi thank you so much for raising this issue, the fix for it was solved in this PR #2515. Fix will be present in the extension version later than 2.18.0
