### ISSUE TITLE
Not able to drag and drop an action into a condition pane with new UI

### ISSUE THREAD

**Issue by fumioogawa** [Azure/LogicAppsUX#2550]
### Describe the Bug with repro steps

Before UI changing, I can do drag and drop an action into a condition pane, but now I cannot do it with new Logic Apps UI.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Workflow JSON

```json
No JOSN is provided because the issue is not caused by the code.
```

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/134565255/026753a5-affb-4023-940b-06ce8ceec90f

### Browser

Microsoft Edge Ver. 113.0.1774.50 64bit

### Additional context

We need to improve the situation to keep development activities by efficient way on Logic Apps. If Logic Apps cannot provide efficient way, we have no reason to continue to use it. Please fix the issue quickly and do not destroy good things by update.

**Comment by hartra344** [comment]
This is a known issue that is listed in known issues and will be fixed in an update soon.
