### ISSUE TITLE
Cannot save the flow including Office 365 Outlook action

### ISSUE THREAD

**Issue by fumioogawa** [Azure/LogicAppsUX#2555]
### Describe the Bug with repro steps

1. Add a action: メールの送信 (V2) belogs to Office 365 Outlook
2. Set paramaters for Recipt address, Title and Mail body
3. Add new paramaters "添付ファイル" (Attachment file)
4. Set file name and contents
5. Save the flow -> error ocured, seet details for the error

Workflow validation failed for the workflow 'Send_Order_Status_Notice_by_FAX'. {"error":{"code":"InvalidTemplate","message":"The template validation failed: 'The template action 'メールの送信_(V2)' at line '1' and column '9767' is not valid: \"Unable to parse template language expression 'base64('@{variables('var_pdf_contents')}')': expected token 'RightParenthesis' and actual 'Identifier'.\".'."}}

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Workflow JSON

```json
no code is provided due to security
```

### Screenshots or Videos

No image or video

### Browser

Both tried: Edge and Chrome, same error ocured

### Additional context

After Logic Apps Designer Update on 17th May, I'm facing MANY,MANY,MANY,MANY,MANY,MANY such errors.
Please solve the issue VERY QUICKLY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Eric-B-Wu** [comment]
Hi @fumioogawa it seems this was fixed #2362, but was just never added to our hotfix release. I'll add it to our hotfix today so that it'll be fixed by today
