### ISSUE TITLE
email connector issue with new designer and save problem in new designer.

### ISSUE THREAD

**Issue by ShabsMS** [Azure/LogicAppsUX#2558]
### Describe the Bug with repro steps

We have identified the list of issues recently with new designer . 2 with Email connector and 2 in general view of designer.
**ISSUE 1 :**
Create a new email action using new designer . 
It gets delivered without break and spaces when I had typed it to be with spaces.

![image](https://github.com/Azure/LogicAppsUX/assets/95284014/b10834e9-e1fa-4ef3-b0ab-bc406110f705)

When I create the same action with old designer , the mail is structured as it should be . The new designer is not adding the spaces rightly.

![image](https://github.com/Azure/LogicAppsUX/assets/95284014/d175f2af-3d40-4aaf-a7a1-cd780cb0eab8)

Also we  see tags such as <br> and <p> in the send email action  in designer view . In old designer we don't see such tags (.Tags are only added when the action is created using old designer ;with proper spacing and when you view in new designer it loads them as <br> ,<p> etc.)

![image](https://github.com/Azure/LogicAppsUX/assets/95284014/9f0fded7-0b3c-452d-bf54-080dba171cb1)

Fallbackurl to old :

![image](https://github.com/Azure/LogicAppsUX/assets/95284014/cadddc0d-66e1-451a-8e48-dc80b7e27b86)

**ISSUE 2 :**
The runhistory of new designer makes it difficult to read in send email action .
![image](https://github.com/Azure/LogicAppsUX/assets/95284014/25cd33e0-ccc8-42ad-8d45-00f23d77e41f)

old designer has structured message:
![image](https://github.com/Azure/LogicAppsUX/assets/95284014/da37a910-9c4e-440b-86c6-d666878b3a0d)

**ISSUE 3 :**
I do a  double click anywhere inside the designer (any action ) , the save button gets enabled !! 

The workarounds for the above 3 issues are using fallback URL .
[Home - Microsoft Azure](https://ms.portal.azure.com/?microsoft_azure_ema_forceFallbackToOldDesigner=true#home)
**ISSUE 4 :**
We are unable to copy the run ID from Logic app Standard. -no workaround for this

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

edge

**Comment by Eric-B-Wu** [comment]
@shabMS thanks for reporting this issue, for the first 3 items this is a missing feature that we plan to get in our next release which can be tracked #1842, and as for the 4th issue, we can track the item with #2009
