### ISSUE TITLE
Parse properties doesn't refresh when checking files in foreachmessage after 3 iterations everytime. Any upgrade ??

### ISSUE THREAD

**Issue by rathna-apd** [Azure/LogicAppsUX#2571]
### Describe the Bug with repro steps

 We are using Logic Standard Application for our workflows for more than a year now. I see the UI is all updated today. 
I am iterating through ForEachmessage loop to see the file content in parse properties. The content doesnt update after I iterate 3 or 4 times and I need to refresh or close browser everytime. 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Screenshots or Videos

I see Azure upgraded the look and feel of Azure Standard logic application. But I see bugs while I try to iterate through foreachmessage loop since morning. The content doesn't update in Parse properties after 3 iterations. I rebooted and refreshed as well nothing works. All this was just fine before the upgrade. I am wasting so much time refreshing , closing browsers and rebooting. No code change from our side as this is happening in Production environment. Please look into this issue.

### Browser

Chrome

### Additional context

All this was working before the upgrade and there is no code change from our side. This is in Production environment. Please look into this urgently.

**Comment by ccastrotrejo** [comment]
Hi @rathna-apd, thank you for raising this issue. Could you please add screenshots with the current and expected behavior or the workflow.json example you are having trouble with? This would speed up the fixing time. You can also share with me the requested data here ccastrotrejo@microsoft.com

**Comment by ccastrotrejo** [comment]
Hi @rathna-apd, just commenting on this again to see if we can get more info about this issue. Otherwise, we will close it through the week.
