### ISSUE TITLE
Changed Parameter Vallues Not Saved

### ISSUE THREAD

**Issue by NRL-LEastham** [Azure/LogicAppsUX#2575]
### Describe the Bug with repro steps

1. Open exisiting logic app in preview designer
2. Open Parameters flyout
3. Click edit on a parameter
4. Update parameter value
5. Click Save in designer, successful save notification presented
6. Close designer
7. Repeat steps 1-3
8. Parameter still shows previous value

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/63475567/71c59401-8422-4767-a7d0-9e6bcb3d0b4a)

### Browser

Edge 113

### Additional context

All parameters have a default value and are valid

Updating the parameter in the code view is fine so this is easy enough to work around.  I did notice a new message in the Parameters flyout but it doesn't make sense as there's no separate 'parameter page' that I can find.

AB#24270320

**Comment by rllyy97** [comment]
Hi @NRL-LEastham, are you able to save other changes with your workflow on their own or is it just an issue with the workflow parameters?
I think this could be a side effect of our [larger saving issues](https://github.com/Azure/LogicAppsUX/issues/2388) that are yet to be fixed, but I want to make sure

**Comment by NRL-LEastham** [comment]
@rllyy97 I've just tried that and you're correct the LA itself didn't save. I hadn't seen the wider thread as I'd filtered open issues on 'parameter'. I'll revert to the GA editor and advise our team here to do the same until the issue is resolved.

**Comment by rllyy97** [comment]
@NRL-LEastham We recently finished rolling out our new build with many saving / validation / error communication fixes on June 9th. If you are able could you try your use-case again on this new build and let me know if saving works/doesn't?
If you are still experiencing issues please update this thread with any relevant details like your workflow file or any related errors / logs. Also it would be very helpful to us if you could send a network log file as well, you can send those directly to me at [rileyevans@microsoft.com](mailto:rileyevans@microsoft.com).
If you need assistance with any of the error-reporting steps we've created a TSG you can find [here](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg) that goes into details

**Comment by rllyy97** [comment]
No worries!  Glad everything seems to be working now!
