### ISSUE TITLE
VS Code unable to run recurrence trigger Logic Apps manually

### ISSUE THREAD

**Issue by AGamingS21** [Azure/LogicAppsUX#2580]
### Describe the Bug with repro steps

When I go to overview of the workflow that has a recurrence trigger the Run Manually option is not there but it is there with the HTTP triggers.

Also there is no way to prevent Recurrence Triggers from running in VS Code and in the Azure Portal at the same time.

This makes it hard to collaborate on logic apps through a git repo.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

VS Code

**Comment by preetriti1** [comment]
@AGamingS21 - Once you have your workflow deployed with recurrence it will follow the recurrence cadence to run. If you just want to share your app, better way to be keep the workflow disabled so runs wont be launched ad when you want to run you can just enable the workflow, disable again when testing is done.

**Comment by AGamingS21** [comment]
Is there a way to disable all recurrence triggers at once so they will not run without having to do this for each workflow?

**Comment by preetriti1** [comment]
From portal you can always do bulk enabling or disabling from the workflows list view in an app.
During your deployment or through CI-CD you can always do it by modifying the appSettings. If you want to enable any workflow this is what you will set in your settings -
key: 'Workflows.{workflowname}.FlowState'
value: Enabled

and for Disabling you set the value as Disabled

**Comment by AGamingS21** [comment]
@preetriti1  would you know if there are plans to make this easier in the future to just work on locally without the recurrence trigger firing locally and in Azure at the same time?

It will be difficult to have multiple people work locally if jobs have to re-run it will make things inconvenient.

**Comment by preetriti1** [comment]
I think you should post this question to our CSS and they connect you with PMs who can answer this.
Since this is not an issue now, so i am going to go ahead and close this.
