### ISSUE TITLE
New logic app designer is not saving a workflow when a change is made to a workflow in the old designer. 

### ISSUE THREAD

**Issue by Imelda-irby** [Azure/LogicAppsUX#2582]
### Describe the Bug with repro steps

Open a logic app that was created in the old designer and try to make a change in this case I have a recurrence trigger.  When I click on delete and click ok, then click on save.  nothing happens, but the trigger does not get deleted.  This happens for multiple different actions or triggers created in the old designer.
The new designer does not allow editing. 
![image](https://github.com/Azure/LogicAppsUX/assets/91350535/3a1cd217-f096-488b-947f-d5b212d4ccbd)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

Edge

### Additional context

above the questions asks if I am using the preview designer, I am using the newly GA designer. 

AB#24299508

**Comment by preetriti1** [comment]
@Imelda-irby - Can you check what error you are seeing in the console? Does this happen with any action deletion only after you try to delete the trigger? Is this only happening for deletion or even editing parameter values without trying the deletion first.
If you are totally unable to edit your LA then please file a case with CSS so you can share network and portal logs.

**Comment by Imelda-irby** [comment]
Hello, @Priti ***@***.***>,

I am from CSS, and this request is for a customer of mine.  I was not sure if we just open all the requests for the new designer issues in Github.
What I am sharing here is my repro, what do I need from the customer?
The customer is totally unable to edit for multiple actions.  Either edit or delete action that were created on the old designer.

**Comment by Imelda-irby** [comment]
Please share workflow.json, connection strings, network logs and portal console logs if you have the repro. We will need that for investigation because its something specific you guys are doing because we have been able to edit it.

Github issues are for quick turnaround time and to make it easier for customers. But they can't share the logs there so we ask then to open incident if it is customer or scenario specific.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Imelda Irby ***@***.***>
Sent: Friday, May 26, 2023 3:56:37 PM
To: Azure/LogicAppsUX ***@***.***>; Azure/LogicAppsUX ***@***.***>; Priti Sambandam ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/LogicAppsUX] New logic app designer is not saving a workflow when a change is made to a workflow in the old designer. (Issue #2582)


Hello, @Priti ***@***.***>,



I am from CSS, and this request is for a customer of mine.  I was not sure if we just open all the requests for the new designer issues in Github.

What I am sharing here is my repro, what do I need from the customer?

The customer is totally unable to edit for multiple actions.  Either edit or delete action that were created on the old designer.

**Comment by thenerdynerd** [comment]
I am getting the same issue - when you have an old flow and try the new designer.

Making a change and trying to save the change does not take, then trying to exit it prompts you about leaving before saving.

In mine the following steps:
1 - open old workflow
2 - try new preview
3 - make changes - delete an action and add an action - in this case a Start a VM action is being removed and another added.
![Screen Shot 2023-05-28 at 20 22 28](https://github.com/Azure/LogicAppsUX/assets/17202561/3aaf65c9-26c0-47bf-b19b-f7644fa05011)

4 - click save and prompt says all changes saved

Saving:
![Screen Shot 2023-05-28 at 20 21 07](https://github.com/Azure/LogicAppsUX/assets/17202561/d7fef59f-e792-4ac3-b570-4d55b8383278)

5 - try to navigate away, prompt asks to save before navigating away.

Navigate back:
![Screen Shot 2023-05-28 at 20 21 30](https://github.com/Azure/LogicAppsUX/assets/17202561/a0793225-abaf-4458-979e-7b79e2db83bb)

**Comment by Eric-B-Wu** [comment]
When you refer to "2 - try new preview", it makes me think that you still have the option to go back and forth between preview and old designer; can we check and see if this is in consumption or standard?

**Comment by Imelda-irby** [comment]
Hi Eric,

The issue I reported is in Standard Logic app.

**Comment by thenerdynerd** [comment]
> When you refer to "2 - try new preview", it makes me think that you still have the option to go back and forth between preview and old designer; can we check and see if this is in consumption or standard?

Hi @Eric-B-Wu - yes - consumption plan - 
![Screen Shot 2023-05-30 at 15 48 43](https://github.com/Azure/LogicAppsUX/assets/17202561/a3ee4880-e5c1-47e9-982c-b8ebc926f4d9)

I can go back and forth:
![Screen Shot 2023-05-30 at 15 49 23](https://github.com/Azure/LogicAppsUX/assets/17202561/22216694-4707-447a-9e8f-63ec914604b3)


![Screen Shot 2023-05-30 at 15 49 40](https://github.com/Azure/LogicAppsUX/assets/17202561/04783184-f5a5-46da-8ed3-c362bf1da5e4)

**Comment by Imelda-irby** [comment]
This issue has been resolved for my customer.

Thank you,
