### ISSUE TITLE
Parameter Node not created inside workflow code

### ISSUE THREAD

**Issue by billchesnut** [Azure/LogicAppsUX#2585]
### Describe the Bug with repro steps

Preview designer put parameters in the wrong location, they should be after output:{} inside of the workflow, not in the parameter outside the workflow.
1. create new workflow
2. add parameters
3. view codeThe preview

this seems to be based on the std designer location of the parameter, not the consumption designer location of the parameters.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "HTTP": {
        "type": "Http",
        "inputs": {
          "uri": "@{parameters('AppConfigURL')}/kv/testvalue",
          "method": "GET",
          "queries": {
            "api-version": "1.0",
            "label": "@{parameters('AppConfigEnvironment')}"
          },
          "authentication": {
            "audience": "@{parameters('AppConfigURL')}",
            "type": "ManagedServiceIdentity"
          }
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "manual": {
        "type": "Request",
        "kind": "Http",
        "inputs": {
          "schema": {}
        },
        "operationOptions": "SuppressWorkflowHeadersOnResponse"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {
    "AppConfigEnvironment": {
      "defaultValue": "Test",
      "type": "String"
    },
    "AppConfigURL": {
      "defaultValue": "https://test.azconfig.io",
      "type": "String"
    },
    "tester": {
      "defaultValue": "test",
      "type": "String"
    }
  }
}
```

### Screenshots or Videos

![2023-05-29_11-38-40](https://github.com/Azure/LogicAppsUX/assets/1853807/c98fa076-0f49-4edf-b037-7ca059f21e5d)
![2023-05-29_11-37-55](https://github.com/Azure/LogicAppsUX/assets/1853807/7f064409-8354-4b8a-8a60-9b24dbc5b16f)

### Browser

Edge

### Additional context

I typically design my workflows in the portal and then copy into my devops, the code view window in the preview design is making this harder.

**Comment by rllyy97** [comment]
Hi @Billchesnut, thank you for the error report!  Currently the designer serializes and exports the workflow the same between Consumption and Standard, then Portal itself does a few extra conversion steps before the save occurs like what you're mentioning with the parameters location.  If you're viewing the code preview from the designer page it currently shows the default export pre-consumption-modification.
For mitigation, if you edit your workflow, save, then open the code view blade you should see the parameters in the right place.
I'm going to look into getting that code preview to show proper serialization for consumption and get back to you

**Comment by rllyy97** [comment]
This issue has been fixed in a different repository and will be live with our next release
