### ISSUE TITLE
Standard _Service bus:   "Messages content" option is missing from service bus trigger.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2591]
### Describe the Bug with repro steps

1.Create a new Stateful Logic App(Standard) , select service bus trigger under the built-in connectors.
2.Select "When messages are available in Service Bus queue"
3. Add connection string of service bus.
4. Enter the queuename(test1) in the Queue name parameter.
5. Turn the Split on to off state and click on "Done"
6. Add "Send message" action from the service bus built-in action as below and use the 2nd queue(test2) as the queue input parameter and content from the "messages content" from the trigger. It will automatically add a foreach loop as it’s a batch trigger.
**Expected :** Content from "Messages content" option should be available from trigger.
**Actual :** Content from "Messages content" option is missing from trigger.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Send_message": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "entityName": "test2"
          },
          "serviceProviderConfiguration": {
            "connectionName": "serviceBus",
            "operationId": "sendMessage",
            "serviceProviderId": "/serviceProviders/serviceBus"
          }
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_messages_are_available_in_a_queue": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "queueName": "test1",
            "isSessionsEnabled": false
          },
          "serviceProviderConfiguration": {
            "connectionName": "serviceBus",
            "operationId": "receiveQueueMessages",
            "serviceProviderId": "/serviceProviders/serviceBus"
          }
        }
      }
    }
  },
  "connectionReferences": {
    "serviceBus": {
      "api": {
        "id": "/serviceProviders/serviceBus"
      },
      "connection": {
        "id": "/serviceProviders/serviceBus/connections/serviceBus"
      },
      "connectionName": "serviceBus",
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/6d0842c0-4db1-4c58-babe-1f34e3212c47)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/5c8688d6-8671-4ec1-999a-31c862b38bad)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/32ad6800-e102-4421-88ba-b26a3fd70559)

### Browser

Edge

### Additional context

**Environment Details:**
**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cb13bdbce753c4d10e4d208db602642f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638209489719398144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ouKhkhxrFJJr2RCOpHP%2F3nqcaTagt7jkAg8FKOmhWRU%3D&reserved=0)
**Version:** 2.30529.1.1

**Comment by preetriti1** [comment]
@vgouth - Content is messages content, did you try to add that and see if forloop is added?

**Comment by vgouth** [comment]
@preetriti1 - I tried to add **Content** option as well, Still unable to see foreach loop added.
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/199d725a-19aa-442c-aa24-52cc12900bf3)

**Comment by vgouth** [comment]
Issue not repro in stating environment. Closing this issue 

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/9e05815c-0377-4c54-bd37-a0c562e6d327)
