### ISSUE TITLE
Data definition not in output

### ISSUE THREAD

**Issue by floriandldlw** [Azure/LogicAppsUX#2592]
### Describe the Bug with repro steps

Created a small mapping JSON - JSON. 
One of my fields are integer but when mapping everything is string.
Looked into the generated xslt and everything is defined as string.
![image](https://github.com/Azure/LogicAppsUX/assets/82218711/b8fb5ac8-f028-4b32-beaf-b238454b2f81)

while in the designer you can see that i defined the following as integer:
![image](https://github.com/Azure/LogicAppsUX/assets/82218711/d3b57349-8b9f-471f-857d-d6f0f76c6e41)

When trying to brute force it, i get the error  FOJS0006  xml-to-json: unknown element <integer>

Is this still work in progress?

### Version

latest

AB#24187934

**Comment by refortie** [comment]
Back end has investigated and it appears to be an issue with the generation of JSON loops. When we create a loop, we are also making an array at the same time, which is incorrect.

![image](https://github.com/Azure/LogicAppsUX/assets/37600290/0d5c2688-5783-4508-83a9-01c546f7ab04)
