### ISSUE TITLE
Excel Online (Business) not allowing to select files in a subfolder

### ISSUE THREAD

**Issue by garethterb** [Azure/LogicAppsUX#2593]
### Describe the Bug with repro steps

I have added a add row to table for excel online for business and I an unable to navigate past the root folder to subfolders.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

Chrome and Edge

**Comment by Eric-B-Wu** [comment]
Hi @garethterb, thanks for reporting this issue, will look to fixing this in an upcoming release
