### ISSUE TITLE
topic trigger gets disconnected

### ISSUE THREAD

**Issue by Ramapreethi123** [Azure/LogicAppsUX#2595]
### Describe the Bug with repro steps

1. Go to Logic app Standard
2. Include a service bus built in trigger when messages are available in the topic
3. Trigger gets disconnected 
4. Error message : Unable to initialize operation details for operation - When_messages_are_available_in_a_topic. Error details - TypeError: Cannot read properties of undefined (reading 'properties')
5. Facing this error often since the UI update

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/134706982/7ca106aa-447f-484a-b50b-23dd24e0f88e)

### Browser

All

AB#24187932

**Comment by preetriti1** [comment]
@Ramapreethi123 - Do you mind sharing the stack trace in the console logs? You can just put the screenshot for it here which has this error.

**Comment by Ramapreethi123** [comment]
This is not an error in the runs @preetriti1 since the latest UX update, the connection of the service bus is getting disconnected in the workflow designer. And it comes back after few hours of wait and later working fine, this is happening more often.

**Comment by rllyy97** [comment]
Hi @Ramapreethi123, next time you experience this issue can you follow our [Trouble Shooting Guide](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-console-errors) to collect any console errors you see and paste them here?  And if you can collect the network logs as well that would be helpful with determining the root of your issue, you can send the network logs to me at rileyevans@microsoft.com

**Comment by preetriti1** [comment]
To add to what Riley mentioned, we will need your definition and connections to determine the load issue here, so network logs wil be helpful. It is not clear when you say "it gets disconnected in the workflow designer and then comes back after few hours" - Does that mean it loads fine when you first load it and just shows this error after few minutes/hours or keeping the blade open.
