### ISSUE TITLE
[VSCode] Summoning overview-page of workflow is giving unhelpful error message

### ISSUE THREAD

**Issue by earloc** [Azure/LogicAppsUX#2612]
### Describe the Bug with repro steps

1. Create a logic app for use in vs-code following the tutorial steps provided [here](https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#create-a-local-project)
2. Create a Workflow `Stateless1/workflow.json` with an incoming HTTP-Request-Trigger (as provided in issue-details)
3. Try to access the workflow´s URL by summoning the workflows' s `Overview`-page (via righ-click context-menu)
4. Observe the following:

![Workflow-Overview](https://github.com/Azure/LogicAppsUX/assets/8486862/282f1249-96dc-485a-aff5-98264c4f1d1c)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Generally Available

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateless"
}
```

### Screenshots or Videos

![Workflow-Overview](https://github.com/Azure/LogicAppsUX/assets/8486862/94c36a12-ce56-4e52-8589-4a08821e2281)

### Browser

- None

### Additional context

My goal is to get a callable URL to the actual workflow in order to smoketest some functionality.
However, the extension somehow isn´t able to manage to display the workflow's overview-page in order to let me collect the corresponding URL which I need to invoke said workflow (e.g via Postman), let alone the fact that I´m not able to view f.e. recent runs of workflow-invocations.

- Is this even a supported feature (local only)?
- Am I doing s.th. completely wrong?

### Versions used
- vs-code: 1.78.2
  - ms-azuretools.vscode-azurelogicapps: 2.18.1
  - Azurite.azurite: 3.23.0
- azure-functions-core-tools: 4.0.4915
- dotnet: 7.0.203
  - other SDKs installed, also:
    > 3.0.100 [C:\Program Files\dotnet\sdk]
    > 5.0.302 [C:\Program Files\dotnet\sdk]
    > 6.0.100 [C:\Program Files\dotnet\sdk]
    > 6.0.116 [C:\Program Files\dotnet\sdk]
    > 6.0.311 [C:\Program Files\dotnet\sdk]
    > 6.0.408 [C:\Program Files\dotnet\sdk]
    > 7.0.105 [C:\Program Files\dotnet\sdk]
    > 7.0.203 [C:\Program Files\dotnet\sdk]

**Comment by earloc** [comment]
vs-code`s developer tools are giving me the following console-error:
> Error: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at dQ.getRuns (main.5e99293e291b19dc.js:2:876260)
    
   
![image](https://github.com/Azure/LogicAppsUX/assets/8486862/712bcd59-3b31-4a80-9114-a34359f97fcf)
(ongoing...)

**Comment by ccastrotrejo** [comment]
Hi @earloc, thank you so much for raising this issue. According to the steps you described and the videos, you haven't started the local server when you are trying to get into the `Overview` page. Thats the reason the URL and the port of it doesn't work. 

Could you please check the steps of the [Run, test, and debug locally](https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#run-test-and-debug-locally) in our documentation and see if that works? Is this still doesn't work, let me know and I will take a further look.

**Comment by earloc** [comment]
Thx @ccastrotrejo for reaching out. I´ll try to follow those steps provided and might come back, if things do not turn out to be sufficient...
