### ISSUE TITLE
In Designer, selecting "Message ID" parameter from Office 365 Outlook connect is not saved correctly (reverts to a different parameter)

### ISSUE THREAD

**Issue by kaly-d** [Azure/LogicAppsUX#2615]
### Describe the Bug with repro steps

1. In the new designer, create a Logic App Standard + Workflow
2. Add any trigger
3. Add the Office 365 Outlook "Get Emails (V3)" action
4. Add a For Each loop and select the output as "value" from "Get Emails (V3)"
5. Add a nested For Each loop and select the output as "Attachments" from Get Emails V3)"
6. In the nested For Each loop, add the Office 365 Outlook "Get Attachment (V2)" action
7. Select the "Message ID" dynamic content in the Message ID field.
8. Save the workflow
9. Reload the page - the previously selected "Message ID" dynamic content from Step 7 is changed to "Attachments Attachment ID"

Issue does not reproduce in old designer

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "For_each": {
                "actions": {
                    "For_each_1": {
                        "actions": {
                            "Get_Attachment_(V2)": {
                                "inputs": {
                                    "host": {
                                        "connection": {
                                            "referenceName": "office365"
                                        }
                                    },
                                    "method": "get",
                                    "path": "/codeless/v1.0/me/messages/@{encodeURIComponent(item()?['id'])}/attachments/@{encodeURIComponent(item()?['id'])}"
                                },
                                "type": "ApiConnection"
                            }
                        },
                        "foreach": "@item()?['attachments']",
                        "type": "Foreach"
                    }
                },
                "foreach": "@body('Get_emails_(V3)')?['value']",
                "runAfter": {
                    "Get_emails_(V3)": [
                        "SUCCEEDED"
                    ]
                },
                "type": "Foreach"
            },
            "Get_emails_(V3)": {
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "office365"
                        }
                    },
                    "method": "get",
                    "path": "/v3/Mail",
                    "queries": {
                        "fetchOnlyFlagged": false,
                        "fetchOnlyUnread": true,
                        "fetchOnlyWithAttachment": false,
                        "folderPath": "Id::AAMkADdmZjNkODI5LWY0ZTctNDU3OC1hZjk0LTUxYTg4Yzg2MjM5OAAuAAAAAACy7AuNy1WLTLMA5wlJVOUEAQAGU_TqzSe0QIfvir9MzLEJAAACohOnAAA=",
                        "importance": "Any",
                        "includeAttachments": false,
                        "top": 10
                    }
                },
                "metadata": {
                    "Id::AAMkADdmZjNkODI5LWY0ZTctNDU3OC1hZjk0LTUxYTg4Yzg2MjM5OAAuAAAAAACy7AuNy1WLTLMA5wlJVOUEAQAGU_TqzSe0QIfvir9MzLEJAAACohOnAAA=": "FDR / Triage"
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

**New Designer** (unexpected)

Selecting Message ID dynamic content from the UI and saving the workflow

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/cf770e11-c94d-4bd0-a0e8-6c6e08d9e054)

Check the Code View after saving, doesn't look like the Message ID

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/95f48d5e-28e3-40f2-b93d-350473d0f39e)

Reload/refresh the page, and the dynamic content is now Attachments Attachment ID

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/79366aee-5b6a-44d1-896b-4603764662eb)

**Old Designer** (expected)

Selecting Message ID dynamic content from the UI and saving the workflow

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/60b6bfb0-0636-4481-be88-be7662d0b66c)

Check the Code View after saving, look like the Message ID got saved

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/58df9835-8e60-497d-bb38-1307e105b383)

Reload/refresh the page, and the dynamic content is retained as Message ID

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/8fe4c4d4-f1d3-4d42-a568-993d384c1cee)

### Browser

Edge

**Comment by preetriti1** [comment]
@kaly-d We will get the fix for this issue deployed in our next release and should be available in production by end of next week.
Thanks for reporting this bug.
