### ISSUE TITLE
Pagination is getting disabled in Get Entities action for Azure table storage connector

### ISSUE THREAD

**Issue by Venkateshdodda-MSFT** [Azure/LogicAppsUX#2618]
### Describe the Bug with repro steps

1.  Created a workflow with recurrence as trigger 
2. added Get entities(V2) of azure table storage connector and enabled the pagination with threshold limit as 5000
3. click on save the workflow
4. workflow got saved but when we go to designer of the workflow we still see the pagination is not set..

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Get_entities_(V2)": {
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "azuretables-2"
                        }
                    },
                    "method": "get",
                    "path": "/v2/storageAccounts/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}/tables/@{encodeURIComponent('datatabkle')}/entities"
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "Recurrence": {
                "recurrence": {
                    "frequency": "Month",
                    "interval": 3
                },
                "type": "Recurrence"
            }
        }
    },
    "kind": "Stateful"
}
--------
also we tried add the below block of code in the code view of the workflow but no luck.

                "runtimeConfiguration": {
                    "paginationPolicy": {
                        "minimumItemCount": 5000
                    }
                },
```

### Screenshots or Videos

I have attached the gif for your reference. 
![getentites_action](https://github.com/Azure/LogicAppsUX/assets/103091186/0526c98f-afbd-400d-afc3-5f846a5ec832)

### Browser

Google Chrome, Edge.

**Comment by DeanD84** [comment]
I have the same problem for Consumption Logic Apps.

When paging is turned on, then no paging information is returned

When paging is turned off then the following paging information is returned
Response Payload-> nextLink
Response Header -> x-ms-continuation-NextPartitionKey
Response Header -> x-ms-continuation-NextRowKey
