### ISSUE TITLE
Logic App Foreach bug

### ISSUE THREAD

**Issue by KingMpunga** [Azure/LogicAppsUX#2620]
### Describe the Bug with repro steps

1. Get a list row from Dataverse
2. When adding dynamic content from list rows action, a foreach is created for each item

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![LogicAppBugs](https://github.com/Azure/LogicAppsUX/assets/125601490/ccf8dda7-7acb-4fb8-be90-4940c2c39632)

### Browser

Microsoft Edge

**Comment by Eric-B-Wu** [comment]
@preetriti1, was this fixed in https://github.com/Azure/LogicAppsUX/pull/2616?

**Comment by preetriti1** [comment]
> @preetriti1, was this fixed in #2616?

Can you try this out from latest main?

@KingMpunga - do you mind sharing what content you are adding so we can try a repro on our end?

**Comment by KingMpunga** [comment]
Hi @preetriti1 due to some data security i can't share the content.
However, you can replicate this issue by creating a get list rows from Dataverse  and try to use the output in the HTTP 
I ain't sure if this issue is old but i only picked it today and i saw that some update has been released.
Thanks.
