### ISSUE TITLE
New Designer regression for creating built-in connection with parameters dependency

### ISSUE THREAD

**Issue by daviburg** [Azure/LogicAppsUX#2633]
### Describe the Bug with repro steps

'Old designer honors the connection parameters dependencies, e.g. when Authentication Type is Basic then fields SAP Username and Password are shown:

![image](https://github.com/Azure/LogicAppsUX/assets/12040431/1201ecf0-c4dc-4b7a-9185-52fca28f7bf2)

This does not work in new Designer both portal and VS Code:

![image](https://github.com/Azure/LogicAppsUX/assets/12040431/7b697e11-e581-4bd4-9972-d324f6640205)

![image](https://github.com/Azure/LogicAppsUX/assets/12040431/bf988cd9-9a08-448e-96fc-f33cfe052207)

![image](https://github.com/Azure/LogicAppsUX/assets/12040431/66bcdf63-dfff-4f05-92e6-8e412942d975)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

**Comment by hartra344** [comment]
@rllyy97 can you place take a look at this tomorrow with urgency? Might be hotfix material.

**Comment by rllyy97** [comment]
Just from a quick investigation I'm only seeing this behavior on the SAP in-app connector, all the other connectors I've tried so far are conditionally showing the correct parameters with respect to the auth type selected

**Comment by rllyy97** [comment]
The issue is that the SAP connector is using dependent parameters for the conditionality instead of actual multi-auth, and the dependent parameter keys have a case mismatch, ex: `authenticationType` vs `AuthenticationType`
