### ISSUE TITLE
Editing api connection authentication type leads to failures 

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#2662]
When updating Azure Blob connector API connection to change the authentication type from “Access Key” to “Managed Identity”, the operation fails.

You can edit the api connection keeping the authentication type unchanged, but when authentication type changes the modification fails.  Possibly because the two different authentication types have different parameters.

When “Access key” based API connection is changed to have a different storage account, the request payload has following values.

```
"parameterValueSet": {
    "name": "keyBasedAuth",
    "values": {
        "accountName": {
            "value": "xxxx"
        },
        "accessKey": {
            "value": "xxxxxxx
        }
    }
},
```
![image](https://github.com/Azure/LogicAppsUX/assets/25409734/08f3fa4b-9ab2-4054-a414-a7ae8ef82cd0)

But when “Access key” based API connection is changed to managed Identity auth, the request pay load has following values

```
"parameterValueSet": {
    "name": "managedIdentityAuth",
    "values": {
        "accountName": {
            "value": "xxxxx"
        }
    }
},
```
![image](https://github.com/Azure/LogicAppsUX/assets/25409734/230aed9a-3243-4c6d-a29c-9d79c9242231)

This request will fail as there is `accountName` parameter is not required for managed identity auth. The error message is “Parameter  'accountName' is not allowed on the connection since it was not defined as a connection parameter when the API was registered”

Looks like during api connection update request, the request parameter should not contain accountName field as it is not needed.

AB#24187843

**Comment by rllyy97** [comment]
This fix has been completed and will be rolling out through the week of June 19th-23rd

**Comment by chuckz1321** [comment]
@rllyy97 May I know when the rollout will start on Mooncake? Will there be a little delay compared to Public Azure?

**Comment by rllyy97** [comment]
@chuckz1321 Mooncake should be rolling out within the same window
