### ISSUE TITLE
Error "Integration account callback URL not specified." from Liquid Transform JSON to JSON action

### ISSUE THREAD

**Issue by BrianCollet** [Azure/LogicAppsUX#2671]
### Describe the Bug with repro steps

1. Add WORKFLOW_INTEGRATION_ACCOUNT_CALLBACK_URL app setting.
2. Add Liquid Transform JSON to JSON action.
3. Set source to Integration Account.
4. Click dropdown for Map Name.
5. Error is displayed: "Integration account callback URL not specified."

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Transform_JSON_To_JSON": {
                "inputs": {
                    "content": "@triggerBody()",
                    "map": {
                        "name": "",
                        "source": "IntegrationAccount"
                    }
                },
                "kind": "JsonToJson",
                "runAfter": {},
                "type": "Liquid"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

Error in preview designer:
![image](https://github.com/Azure/LogicAppsUX/assets/50160870/5bfc703c-dedc-499d-9a77-aa2ccb86a189)

Callback URL app setting is configured:
![image](https://github.com/Azure/LogicAppsUX/assets/50160870/12897ef1-bfca-476d-8078-dfa90ea46a8e)

No error in fallback designer:
![image](https://github.com/Azure/LogicAppsUX/assets/50160870/edc8992a-4cb1-41fb-82bc-774b3703e7e2)

### Browser

Edge Version 114.0.1823.37

**Comment by preetriti1** [comment]
@BrianCollet - We have fixed this issue and the deployment in production is in progress and should be available in all regions by EOW 06/09
