### ISSUE TITLE
Inputs and outputs are not loading due to the CORS policy

### ISSUE THREAD

**Issue by timja** [Azure/LogicAppsUX#2674]
### Describe the Bug with repro steps

1. Go to Run history
2. Click a step
3. Receive popup:

![image](https://github.com/Azure/LogicAppsUX/assets/21194782/5ac12284-0475-40a2-86d8-e933c964181a)

CORS is enabled:
![image](https://github.com/Azure/LogicAppsUX/assets/21194782/eb715c27-65e9-45f1-b70a-5fc29acf12f4)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Initialize_variable": {
        "type": "InitializeVariable",
        "inputs": {
          "variables": [
            {
              "name": "payload",
              "type": "string",
              "value": "base64ToString(triggerBody()?['ContentData'])"
            }
          ]
        },
        "runAfter": {}
      },
      "HTTP": {
        "type": "Http",
        "inputs": {
          "uri": "https://sds-build.sandbox.platform.hmcts.net/github-webhook/",
          "method": "POST",
          "headers": {
            "content@{triggerBody()?['ContentType']}": "application/json"
          },
          "body": "@variables('payload')"
        },
        "runAfter": {
          "Initialize_variable": [
            "SUCCEEDED"
          ]
        },
        "runtimeConfiguration": {
          "contentTransfer": {
            "transferMode": "Chunked"
          }
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_message_is_received_in_a_topic_subscription_(auto-complete)": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "servicebus"
            }
          },
          "method": "get",
          "path": "/@{encodeURIComponent(encodeURIComponent('demotopic'))}/subscriptions/@{encodeURIComponent('demosubscription')}/messages/head",
          "queries": {
            "subscriptionType": "Main"
          }
        },
        "recurrence": {
          "interval": 3,
          "frequency": "Minute"
        }
      }
    }
  },
  "connectionReferences": {
    "servicebus": {
      "connection": {
        "id": "/subscriptions/****/resourceGroups/bluesquadpoc/providers/Microsoft.Web/connections/servicebus"
      },
      "connectionName": "servicebus",
      "api": {
        "id": "/subscriptions/***/providers/Microsoft.Web/locations/uksouth/managedApis/servicebus"
      },
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {}
}
```

### Browser

Chrome

AB#24199969

**Comment by hartra344** [comment]
@timja can you send a network trace to me at travisharris@microsoft.com. There are a few non CORS things that can also cause this but I can’t verify what that may be without a network trace.

**Comment by timja** [comment]
Emailed

**Comment by hartra344** [comment]
@timja you're getting the error because your app is behind a firewall or something that is rejecting your request causing the calls to return 403: 
![CleanShot 2023-06-07 at 08 51 45@2x](https://github.com/Azure/LogicAppsUX/assets/13208452/f6325d50-b716-4437-85b9-5c9ad49017ab)

We can clean up the error messaging here for this case but it'll still be an error unless you can hit the app endpoint.

**Comment by timja** [comment]
Ugh, thanks found it.

Someone had enabled access restrictions.

Networking -> Access restrictions -> Main site

Add rule

Added my IP

![image](https://github.com/Azure/LogicAppsUX/assets/21194782/ac1abf5b-07b7-4846-8b61-0cd5a4c1a91b)

and it works now.

Double-checked by setting my IP to deny, it went back to broken, allowed it again and it worked.

**Comment by timja** [comment]
some clearer error messaging would've solved that a lot easier 😄.
