### ISSUE TITLE
VS Code:  Workflow is not saving Successfully for deployed logic app from VS code.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2676]
### Describe the Bug with repro steps

1. Create a new Logic App Project
2. Add a workflow to your local project
3. Open the workflow.json file in designer and author a new workflow
	a. Add http request Trigger
	b. Add a compose action here with custom text
	c. Add a ServiceBus action. From the add new paramter dropdown add content and add random text in JSON format like {"a":"b"}
	d. Add a send email action with the body being the output of the compose action (step b)
	e. Add a new connection to your email action
	f. Add http response action
4. Press F5 to build and run your project
5. Run the workflow
	a. Open overview page. Right + Click on workflow.json file and "Overview"
	b. Copy call back URL from the overview page
	c. Send the http request POST via Postman and wait for the response
6. Refresh the overview page and your should see your local run
7. Open the monitoring view for your run from the overview page
8. Verify the run details and action inputs and output
9. Create a logic app and Deploy to Azure
10.After deployment is success, Open the deployed logic app in portal.
11.Open the workflow in designer .
12.Workflow should not show any error but showing an error in Office_365.
13.Deleting the Office_365 action or any other action or Add new actions and try to save the workflow.

**Expected:**Workflow should save Successfully for deployed logic app from VS code.
**Actual:** Workflow is not saving Successfully for deployed logic app from VS code.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Response": {
        "type": "Response",
        "kind": "Http",
        "inputs": {
          "statusCode": 200
        },
        "runAfter": {
          "Send_message": [
            "SUCCEEDED"
          ]
        }
      },
      "Compose": {
        "type": "Compose",
        "inputs": "vs code 0606",
        "runAfter": {}
      },
      "Send_message": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "entityName": "test",
            "message": {
              "contentData": {
                "a": "b"
              }
            }
          },
          "serviceProviderConfiguration": {
            "connectionName": "serviceBus",
            "operationId": "sendMessage",
            "serviceProviderId": "/serviceProviders/serviceBus"
          }
        },
        "runAfter": {
          "Compose": [
            "SUCCEEDED"
          ]
        },
        "trackedProperties": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {
    "serviceBus": {
      "connection": {
        "id": "/serviceProviders/serviceBus/connections/serviceBus"
      },
      "connectionName": "abc",
      "api": {
        "id": "/serviceProviders/serviceBus"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

[saving Console file.log](https://github.com/Azure/LogicAppsUX/files/11663586/saving.Console.file.log)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/d0eef5b2-21fd-4665-b028-e424042ebad1)

### Browser

VS Code

### Additional context

**Artifacts details:**

**VS Code extension:** [vscode-azurelogicapps-2.24.3.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEUtS0SJECrFDgEfY_BSfFlsBSqFEmGM2jMuz1uN88uqHrQ%3Fe%3D62D7LG&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OVYmk3G26RGfYDI3aar3hdiReVK%2FawmoHwg5OiWHcCQ%3D&reserved=0)
**NuGet package:** [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MTk5ODA4L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.25.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MTk5ODA4L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.25.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=upITg%2FkMqauS7sUHSrAVwYfm0O4KeY65yeH%2BBqsjjUY%3D&reserved=0)
**Extension Bundle (CDN URL):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iXPu8J3jR6BDSNcAoxbr2aDU%2BZvRu6kj0Anmv11HhoA%3D&reserved=0)
**Extension Bundle (Direct Download):** [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MjAxMjgxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.25.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MjAxMjgxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.25.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BfSH60Z%2BMvx93kjvByWQcds3yW4KDimY9naPq2e23oc%3D&reserved=0)

AB#24192716

**Comment by preetriti1** [comment]
@vgouth - If you open your resource in our portal staging link you should not see the invalid connections and also deleting that action would have led successful workflow save. This bug in portal is only in production and is fixed in our latest release which will complete by Friday EOD.
