### ISSUE TITLE
Workflow save button is active when an action is added and there is no user interaction inside the action.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2677]
## What is the issue?
Designer in portal and vscode doesn't disable the save button/allows to save when an action is added to the workflow and there is no user interaction in the action input fields.
Clicking in the inputs, not doing anything and clicking outside triggers the error text in the action and the disable of the save button.
Need to come up with an implementation to solve this.

### Describe the Bug with repro steps
1.Create a Stateful workflow in the VS Code project.
2.Open the Designer and add http trigger.
3.Add Office Send an email action.
4.Remain mandatory (*) fields empty without user interaction and try to save the workflow.

Expected: Workflow should not be saved.

Actual: Able to save the workflow.

### What type of Logic App Is this happening in?

Standard Portal and VSCode

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/92098490/6ac6f527-b6c4-42d5-810a-0337bc5afa86)

AB#24191431

**Comment by v-prakumar** [comment]
@ccastrotrejo @AbodeSaafan Issue is repro in vsix 2.24.6

**Comment by vgouth** [comment]
Issue repro in latest request

**Artifacts details:**

1.VS Code extension: [vscode-azurelogicapps-2.28.3.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/ERQvUcsm27ZDqAk8h0IZFCQBnKEudkPL03CVtbYt1v_VMA?e=t0HVLO&xsdata=MDV8MDF8di1nb3Z1YmlsaXNoQG1pY3Jvc29mdC5jb218ZmM2NDU5N2YxZDQxNGVlYmVlYTcwOGRiNzM4MjM4YmN8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODIzMDc3NTQ4NDkwNTEwOHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=TDhwSU14VSsyOVNxNkErMVIyY0QyZkd4TGZwQTIzYktQYWxxM2ZHNnNTOD0%3d)
2.Nuget package:
[https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc1MzA5MDMwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.28.2.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc1MzA5MDMwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.28.2.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cfc64597f1d414eebeea708db738238bc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638230775484905108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=g10UtlCyrfuCJ3xEYvwnFQPrl%2Bm6XQ2kcVQMsojBn4U%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BMcHLJsKeduA0dQVQ2CgOL5GzXjsVgOPWUrnxLtW%2Fnw%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.28.2/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.28.2_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.28.2%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.28.2_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cfc64597f1d414eebeea708db738238bc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638230775484905108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X3COeqQjGm9dM2gxR11Ry2QC76q7bwedZA1PmclN1jk%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/5685ca9b-6329-428d-9f64-cf4775671a17)

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue is repro in vsix 2.28.3

**Comment by v-prakumar** [comment]
@Eric-B-Wu Issue is repro in the Standard Portal too. **Version:  2.30701.1.1**
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/4d3c1dfc-050f-4cd0-ada2-1432a699d5cd)

**Comment by vgouth** [comment]
Issue repro in the latest portal request.

**Environmental Details:**

**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C7066ec0ac75448df5fdf08db7c66a813%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638240552627643792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wun6TTHejC2sQ1o4VXSUpvCr14gLclvGtpbAR0vj5XU%3D&reserved=0)
**Version:** 2.30701.1.1

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue is still repro in vsix : 2.45.2

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue is repro in the vsix: 2.45.3
