### ISSUE TITLE
Workflow when deployed to different location from VSCode will run into new connection creation issue

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2679]
### Describe the Bug

Getting invalid connection error for Office_365 connection after deploying the workflow from VS code. There is automatically change in location as per Workflow Json . Selected location in Vs code to create a logic app is East US. But in portal automatically Central US location is getting added as per Workflow JSON code. 
Added Workflow JSON code od VS code and portal in Workflow JSON tab.
Tried to add a new connection for deployed logic app in portal but it is not allowing to add the new connection as the location is different. Attached the screenshot for the same .

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create a new Logic App Project
2. Add a workflow to your local project
3. Open the workflow.json file in designer and author a new workflow
	a. Add http request Trigger
	b. Add a compose action here with custom text
	c. Add a ServiceBus action. From the add new paramter dropdown add content and add random text in JSON format like {"a":"b"}
	d. Add a send email action with the body being the output of the compose action (step b)
	e. Add a new connection to your email action
	f. Add http response action
4. Press F5 to build and run your project
5. Run the workflow
	a. Open overview page. Right + Click on workflow.json file and "Overview"
	b. Copy call back URL from the overview page
	c. Send the http request POST via Postman and wait for the response
6. Refresh the overview page and your should see your local run
7. Open the monitoring view for your run from the overview page
8. Verify the run details and action inputs and output
9. Create a logic app and Deploy to Azure
10.After deployment is success, Open the deployed logic app in portal. 
11. Open the workflow in designer . 
12. Workflow should not show any error.

**Expected:**Workflow should not show any error.
**Actual:** Getting invalid connection error for Office_365 connection after deploying the workflow from VS code

### Workflow JSON

```json
Portal Workflow JSON:

{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Response": {
        "type": "Response",
        "kind": "Http",
        "inputs": {
          "statusCode": 200
        },
        "runAfter": {
          "Send_an_email_(V2)": [
            "SUCCEEDED"
          ]
        }
      },
      "Compose": {
        "type": "Compose",
        "inputs": "vs code 0606",
        "runAfter": {}
      },
      "Send_message": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "entityName": "test",
            "message": {
              "contentData": {
                "a": "b"
              }
            }
          },
          "serviceProviderConfiguration": {
            "connectionName": "serviceBus",
            "operationId": "sendMessage",
            "serviceProviderId": "/serviceProviders/serviceBus"
          }
        },
        "runAfter": {
          "Compose": [
            "SUCCEEDED"
          ]
        },
        "trackedProperties": {}
      },
      "Send_an_email_(V2)": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "office365-2"
            }
          },
          "method": "post",
          "body": {
            "To": "v-govubilish@microsoft.com",
            "Subject": "Vs code 06/06/2023",
            "Body": "<p>@{outputs('Compose')}</p>",
            "Importance": "Normal"
          },
          "path": "/v2/Mail"
        },
        "runAfter": {
          "Send_message": [
            "SUCCEEDED"
          ]
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {
    "serviceBus": {
      "connection": {
        "id": "/serviceProviders/serviceBus/connections/serviceBus"
      },
      "connectionName": "abc",
      "api": {
        "id": "/serviceProviders/serviceBus"
      }
    },
    "office365-2": {
      "connection": {
        "id": "/subscriptions/53ce23c6-ff79-490b-a7fb-9590fe7a414a/resourceGroups/VSCode-v-govubilish/providers/Microsoft.Web/connections/office365-11"
      },
      "connectionName": "office365-11",
      "api": {
        "id": "/subscriptions/53ce23c6-ff79-490b-a7fb-9590fe7a414a/providers/Microsoft.Web/locations/centralus/managedApis/office365"
      },
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {}
}







VS code Workflow JSON: 

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "Http",
                "inputs": {
                    "statusCode": 200
                },
                "runAfter": {
                    "Send_an_email_(V2)": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Compose": {
                "type": "Compose",
                "inputs": "vs code 0606",
                "runAfter": {}
            },
            "Send_message": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "entityName": "test",
                        "message": {
                            "contentData": {
                                "a": "b"
                            }
                        }
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "serviceBus",
                        "operationId": "sendMessage",
                        "serviceProviderId": "/serviceProviders/serviceBus"
                    }
                },
                "runAfter": {
                    "Compose": [
                        "SUCCEEDED"
                    ]
                },
                "trackedProperties": {}
            },
            "Send_an_email_(V2)": {
                "type": "ApiConnection",
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "office365-2"
                        }
                    },
                    "method": "post",
                    "body": {
                        "To": "v-govubilish@microsoft.com",
                        "Subject": "Vs code 06/06/2023",
                        "Body": "<p>@{outputs('Compose')}</p>",
                        "Importance": "Normal"
                    },
                    "path": "/v2/Mail"
                },
                "runAfter": {
                    "Send_message": [
                        "SUCCEEDED"
                    ]
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![image](https://github.com/Azure/logicapps/assets/113517384/0875784d-8908-45f2-9377-6a0d3a33955b)
![image](https://github.com/Azure/logicapps/assets/113517384/726d1553-53b5-4a9d-bf16-8fe193f713a3)

### Additional context

**Artifacts details:**

1.	**VS Code extension:**  [ vscode-azurelogicapps-2.24.3.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEUtS0SJECrFDgEfY_BSfFlsBSqFEmGM2jMuz1uN88uqHrQ%3Fe%3D62D7LG&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OVYmk3G26RGfYDI3aar3hdiReVK%2FawmoHwg5OiWHcCQ%3D&reserved=0) 
2.	**NuGet package:**   [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MTk5ODA4L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.25.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MTk5ODA4L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.25.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=upITg%2FkMqauS7sUHSrAVwYfm0O4KeY65yeH%2BBqsjjUY%3D&reserved=0)
3.	**Extension Bundle (CDN URL):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iXPu8J3jR6BDSNcAoxbr2aDU%2BZvRu6kj0Anmv11HhoA%3D&reserved=0)
4.	**Extension Bundle (Direct Download):** [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MjAxMjgxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.25.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0MjAxMjgxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.25.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BfSH60Z%2BMvx93kjvByWQcds3yW4KDimY9naPq2e23oc%3D&reserved=0)

AB#24188832

AB#24192914

**Comment by preetriti1** [comment]
The invalid connection issue is now fixed in latest deployment, but the remaining and active issue from this is -
If LA is deployed to different region from what was selected in vscode local project then while creating new connection we should take location from apiId instead of location from workflow app, this would make sure we have successful connection creation.

**Comment by vgouth** [comment]
Intermittent Issue repro in the latest request in VS code run history with status code as 200.

**Artifacts details:**

1.VS Code extension: [vscode-azurelogicapps-2.24.3.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEUtS0SJECrFDgEfY_BSfFlsBSqFEmGM2jMuz1uN88uqHrQ%3Fe%3D62D7LG&data=05%7C01%7Cv-govubilish%40microsoft.com%7C843af085d8544276197108db666a165a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638216378094209315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OVYmk3G26RGfYDI3aar3hdiReVK%2FawmoHwg5OiWHcCQ%3D&reserved=0)
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0NTYyNjAxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.26.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0NTYyNjAxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.26.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K%2B%2B4glXp6A3WGCxvRE0ro6%2BdNMbQRyBp%2B144jxaM0pM%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BMcHLJsKeduA0dQVQ2CgOL5GzXjsVgOPWUrnxLtW%2Fnw%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.26.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.26.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.26.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.26.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kwKTaS0KreBjKZyjkGnafr6S%2BbLeB6sT6oMKgUiu288%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/3acadc54-5a18-49ca-8d05-c9b554778f01)

**Comment by vgouth** [comment]
Issue Repro in the new VSIX 

With new VSIX (2.24.6), Getting the same error message popup with 200 as status code only in VS code for office-365 after deploying the workflow and running it. In portal when we open the same run history we are not getting the error message popup

**Artifacts details:**

1.VS Code extension: vscode-azurelogicapps-2.24.6.vsix
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/ffbf6551-545e-4e35-8cef-1a9274187dd6)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/ded8a3f5-aeae-4143-ba36-fe8bda9ba8c1)
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0NTYyNjAxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.26.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0NTYyNjAxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.26.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K%2B%2B4glXp6A3WGCxvRE0ro6%2BdNMbQRyBp%2B144jxaM0pM%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BMcHLJsKeduA0dQVQ2CgOL5GzXjsVgOPWUrnxLtW%2Fnw%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.26.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.26.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.26.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.26.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kwKTaS0KreBjKZyjkGnafr6S%2BbLeB6sT6oMKgUiu288%3D&reserved=0)

**Comment by vgouth** [comment]
Issue repro in latest request

With new VSIX (2.28.3), Getting the same error message popup with 200 as status code only in VS code for office-365 after deploying the workflow and running it. In portal when we open the same run history we are not getting the error message popup

**Artifacts details:**

1.VS Code extension: [vscode-azurelogicapps-2.28.3.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/ERQvUcsm27ZDqAk8h0IZFCQBnKEudkPL03CVtbYt1v_VMA?e=t0HVLO&xsdata=MDV8MDF8di1nb3Z1YmlsaXNoQG1pY3Jvc29mdC5jb218ZmM2NDU5N2YxZDQxNGVlYmVlYTcwOGRiNzM4MjM4YmN8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODIzMDc3NTQ4NDkwNTEwOHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=TDhwSU14VSsyOVNxNkErMVIyY0QyZkd4TGZwQTIzYktQYWxxM2ZHNnNTOD0%3d)
2.Nuget package:
[https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc1MzA5MDMwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.28.2.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc1MzA5MDMwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.28.2.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cfc64597f1d414eebeea708db738238bc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638230775484905108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=g10UtlCyrfuCJ3xEYvwnFQPrl%2Bm6XQ2kcVQMsojBn4U%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BMcHLJsKeduA0dQVQ2CgOL5GzXjsVgOPWUrnxLtW%2Fnw%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.28.2/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.28.2_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.28.2%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.28.2_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cfc64597f1d414eebeea708db738238bc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638230775484905108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X3COeqQjGm9dM2gxR11Ry2QC76q7bwedZA1PmclN1jk%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/edc3b621-1fc4-440d-be5f-100a6f901e7d)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/1249d52e-7c1b-4485-bc02-f141b95d78e4)

**Comment by ccastrotrejo** [comment]
I was able to repro this, will make a fix and will update thread.
