### ISSUE TITLE
Standard_Custom Http Timeout Setting Per Request Action: Unable to debug the workflow, getting the below error with PT1S and PT24H request timeout.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2701]
### Describe the Bug with repro steps

1.Create a standard logic app
2.Create an empty stateless workflow
3.Add a request trigger and HTTP request action.
4.The request url to point to
([https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI](https://httptimeoutendpoint.azurewebsites.net/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI))
5.Go to settings tab and set Request options to PT1S or PT24H
6.Disable the Asynchronous pattern.
7.Save and run the workflow.
8.**Expected Result:** Debugging should run without any errors.
**Actual Result:** Unable to debug the workflow, getting the below error with PT1S and PT24H request timeout.

**Note:** While trying to open the overview page getting the 404 error.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
PT1S workflow JSON

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "HTTP": {
                "type": "Http",
                "inputs": {
                    "uri": "https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI",
                    "method": "POST"
                },
                "runAfter": {},
                "operationOptions": "DisableAsyncPattern",
                "runtimeConfiguration": {
                    "contentTransfer": {
                        "transferMode": "Chunked"
                    },
                    "requestOptions": {
                        "timeout": "PT1S"
                    }
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateless"
}

PT24H workflow JSON

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "HTTP": {
                "type": "Http",
                "inputs": {
                    "uri": "https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI",
                    "method": "POST"
                },
                "runAfter": {},
                "operationOptions": "DisableAsyncPattern",
                "runtimeConfiguration": {
                    "contentTransfer": {
                        "transferMode": "Chunked"
                    },
                    "requestOptions": {
                        "timeout": "PT24H"
                    }
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateless"
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/b548d2ae-3979-4131-974f-03fb05ec471d)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/033967d3-8a07-4844-b316-94edd5671329)

### Browser

VS Code

### Additional context

**Artifacts Details:**

1.VS Code extension: [vscode-azurelogicapps-2.24.3.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEUtS0SJECrFDgEfY_BSfFlsBSqFEmGM2jMuz1uN88uqHrQ%3Fe%3D62D7LG&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ca7d1bc0a237d488d10e108db672b1080%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638217206935590829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WlxG5bcq1ej761KNqQ%2BLtvAmRSTEgwvtejbZZlzSxZE%3D&reserved=0)
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0Mzk0ODczL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.25.4.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0Mzk0ODczL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.25.4.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ca7d1bc0a237d488d10e108db672b1080%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638217206935434622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=itFALTueZQxguLRJvKKiWJXDyumAl4DtSnkg82YmPt8%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ca7d1bc0a237d488d10e108db672b1080%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638217206935590829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EuLLscGjv5qqENJ91h2yYlsC9J3u0tqkraH9d%2BPhXVg%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.25.4/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.25.4_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.25.4%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.25.4_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ca7d1bc0a237d488d10e108db672b1080%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638217206935590829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hPPw%2FTXp%2BTF726NjsAQ3%2B4DxWdeLIih9%2Bc3J%2FwDxcSQ%3D&reserved=0)

**Comment by vgouth** [comment]
Issue repro in the new request

**Artifacts details:**

1.VS Code extension: vscode-azurelogicapps-2.24.6.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0NTYyNjAxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.26.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc0NTYyNjAxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.26.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K%2B%2B4glXp6A3WGCxvRE0ro6%2BdNMbQRyBp%2B144jxaM0pM%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BMcHLJsKeduA0dQVQ2CgOL5GzXjsVgOPWUrnxLtW%2Fnw%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.26.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.26.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.26.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.26.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kwKTaS0KreBjKZyjkGnafr6S%2BbLeB6sT6oMKgUiu288%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/70d0ad05-a0da-4b9e-8ff2-0368ec7ad313)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/24862150-bcae-40a2-aa6b-e23421581e60)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/2997b4d5-843c-4abd-8f3b-c01d0913740d)

**Comment by vgouth** [comment]
Issue repro in portal request as well 

**Environment Details:**
**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C392339cb587e4c43790908db6d71cb35%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638224107779018807%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=s7WSfUXHwF4dkudT6gzIP%2F%2FZYEERYmiDNQq%2FryasrPw%3D&reserved=0)
**Version:** "2.30613.1.2"

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/4d93a8a3-6b8d-46a9-bedb-ba55436bfe25)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/def30d19-e3b9-4158-8bac-69190b1b6064)


**Workflow.Json:**

{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "HTTP": {
        "type": "Http",
        "inputs": {
          "uri": "https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI",
          "method": "POST"
        },
        "runAfter": {},
        "operationOptions": "DisableAsyncPattern",
        "runtimeConfiguration": {
          "contentTransfer": {
            "transferMode": "Chunked"
          },
          "requestOptions": {
            "timeout": "PT24H"
          }
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {
    "a": {
      "type": "Array",
      "value": [
        1,
        2,
        3,
        4
      ]
    },
    "b": {
      "type": "Int",
      "value": 1
    }
  }
}

**Comment by vgouth** [comment]
Issue repro in new VS code request

**Artifacts details:**

1.VS Code extension: [vscode-azurelogicapps-2.28.3.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/ERQvUcsm27ZDqAk8h0IZFCQBnKEudkPL03CVtbYt1v_VMA?e=t0HVLO&xsdata=MDV8MDF8di1nb3Z1YmlsaXNoQG1pY3Jvc29mdC5jb218ZmM2NDU5N2YxZDQxNGVlYmVlYTcwOGRiNzM4MjM4YmN8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODIzMDc3NTQ4NDkwNTEwOHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=TDhwSU14VSsyOVNxNkErMVIyY0QyZkd4TGZwQTIzYktQYWxxM2ZHNnNTOD0%3d)
2.Nuget package:
[https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc1MzA5MDMwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.28.2.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc1MzA5MDMwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.28.2.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cfc64597f1d414eebeea708db738238bc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638230775484905108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=g10UtlCyrfuCJ3xEYvwnFQPrl%2Bm6XQ2kcVQMsojBn4U%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BMcHLJsKeduA0dQVQ2CgOL5GzXjsVgOPWUrnxLtW%2Fnw%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.28.2/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.28.2_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.28.2%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.28.2_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cfc64597f1d414eebeea708db738238bc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638230775484905108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X3COeqQjGm9dM2gxR11Ry2QC76q7bwedZA1PmclN1jk%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/20a19aef-8282-435e-945d-e04feda48715)

**Comment by vgouth** [comment]
Issue repro in the latest request 

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C7066ec0ac75448df5fdf08db7c66a813%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638240552627643792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wun6TTHejC2sQ1o4VXSUpvCr14gLclvGtpbAR0vj5XU%3D&reserved=0)
**Version:** 2.30701.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/031db0fd-d49b-4382-a3ee-5cd07583d704)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/4f75a56e-d162-4b83-ae22-a199fb100323)

**Comment by vgouth** [comment]
Issue repro in new VS code request

1. VS Code extension: vscode-azurelogicapps-2.45.3.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc2NDI0MDc0L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.31.2.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc2NDI0MDc0L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.31.2.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7C9b145287f20e418e2c1f08db87674b69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638252650006637632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kbPqYTij39ZqG9ht1rsLQe878QJn%2BWEbeNLJ9G92sNM%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7C9b145287f20e418e2c1f08db87674b69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638252650006637632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=q7lkzMt7ekttUTs3iCrawTbmF6yLVSMBKGqoohGhmcI%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.31.2/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.31.2_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.31.2%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.31.2_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C9b145287f20e418e2c1f08db87674b69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638252650006637632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S2OTcXG4aWL%2FqPEazIq1j%2FtrDc78UVKBig786EGGpcU%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/907245e4-b840-4a07-9171-4bcf179c4629)

**Comment by vgouth** [comment]
Issue repro in the latest request, looks like the fix is not reflected in the new request.

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C22eca00d05414450524c08db8c1dbdfd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638257831648260657%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Spc48TAD7oGuAs8oPmFAqnCllLZpAdhrd%2BkWGMT78Vo%3D&reserved=0)
**Version:** 2.30717.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/1023a55b-29e3-4b26-8f9c-9412b0fbb3aa)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/47d26739-2ae5-4b57-b3d7-5c9cc805cf44)

**Comment by Eric-B-Wu** [comment]
This was fixed in designer 2.50.0, which means it wasn't in the release. If this issue persists in the next release, then we can reopen

**Comment by vgouth** [comment]
Issue repro in the latest request only for **PT24H** timeout:

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C25ee41df62d44438790c08db937727d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638265912263218130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ExdI18ub8D3V7ulDw4BDJPTB28t6zLoS8UczXvO%2FLFw%3D&reserved=0)
**Version:** 2.30731.1.4

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/23226ff8-fbf5-42fc-ae61-a67dcdffb22d)

**Comment by vgouth** [comment]
Different error repro for PT24H timeout, logged a new bug for this issue.
