### ISSUE TITLE
[Teams - Post message in a chat or channel].    Message input fields are not able to refer to the set values.

### ISSUE THREAD

**Issue by tottokug** [Azure/LogicAppsUX#2702]
### Describe the Bug with repro steps

1. Display the designer of an existing workflow.
2. Select the existing Teams - Post message in a chat or channel action.
3. Make sure Message in Parameters is blank.
4. Click Code View.
5. Make sure that body.messageBody is set.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

<img width="948" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/1300270/645f4c18-604b-45b4-9b6a-9b4feb7de815">
<img width="983" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/1300270/63168b2a-c78d-4d9d-8ebb-df6dfff2a6ac">

### Browser

Microsoft Edge
Version 114.0.1823.41 (arm64)

AB#24211176

**Comment by preetriti1** [comment]
@tottokug - is the issue that even if you have message set in definition it is not showing up in the parameter field on reload?

**Comment by rllyy97** [comment]
From some initial testing it looks like this serializes fine if you don't change the parameter value, but loading the component loads empty if the value is wrapped in a <p> tag.  Also if you input a plain text value to the editor it wraps it in a <p> tag, and upon reload is empty.
