### ISSUE TITLE
Logic App function convertFromUtc() cannot be added to Content property of Shared Send message action

### ISSUE THREAD

**Issue by artbarrios** [Azure/LogicAppsUX#2720]
### Describe the Bug with repro steps

When adding the function convertFromUtc() to the Content property of a Shared Send message Service Bus action in a Standard Logic App, the following error is displayed when an attempt is made to save the Logic App:

Workflow validation failed
Workflow validation failed for the workflow 'TestWorkflowName'. {"error": {"code":"InvalidTemplate", "message":"The template validation failed: 'The template action 'Send_message' at line '1' and column '313' is not valid: \"Unable to parse template language expression 'base64(concat('DateTime:','convertfromUTC(utcNow(),'Central Standard Time','yyyy')',' '))': expected token 'RightParenthesis' and actual 'identifier',\".'."}}

Steps to reproduce:

1. Create a new Standard Logic App
2. Add an HTTP Request trigger
3. Add a Service Bus, Send message (Runtime: Shared) action
4. Set or add a valid service bus connection
5. In the Queue/Topic Name entry, specify a valid service bus queue
6. Click Add new parameters and check Content
7. In the content entry click the fx button to enter into the Function definition dialog
8. In the Function dialog type the following:     convertFromUtc(utcNow(),'Central Standard Time','yyyy')  
9. Click the Add button
10. Click the Logic App Save button
11.  The Workflow validation failed message will now appear and you will be unable to save the Logic App

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "inputs": {
                    "body": "@triggerBody()",
                    "statusCode": 200
                },
                "kind": "Http",
                "runAfter": {
                    "Send_message": [
                        "SUCCEEDED"
                    ]
                },
                "type": "Response"
            },
            "Send_message": {
                "inputs": {
                    "body": {
                        "ContentData": "@{base64(concat('DateTime: ','convertFromUtc(utcNow(),'Central Standard Time','yyyy')',' '))}"
                    },
                    "host": {
                        "connection": {
                            "referenceName": "servicebus_1"
                        }
                    },
                    "method": "post",
                    "path": "/@{encodeURIComponent(encodeURIComponent('testqueue'))}/messages",
                    "queries": {
                        "systemProperties": "None"
                    }
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![LA_SendMessage_Error_Image1](https://github.com/Azure/LogicAppsUX/assets/3615393/0ed187e4-f378-4f2f-b476-34c838f97a6e)

![LA_SendMessage_Error_Image2](https://github.com/Azure/LogicAppsUX/assets/3615393/2f81b92f-57b7-4760-ac06-36cb702c181b)

![LA_SendMessage_Error_Image3](https://github.com/Azure/LogicAppsUX/assets/3615393/3660f299-fd13-447f-91ce-3e4760054229)

### Browser

Microsoft Edge   Version 114.0.1823.37 (Official build) (64-bit)  on Windows

AB#24231410

**Comment by hartra344** [comment]
I'm not able to repro using the steps you provided but did have an error when using teh fx string you had in your screenshot. 

The reason for the parse error is that you're putting single quotes around your convert function 

```
base64(concat('DateTime: ','convertFromUtc(utcNow(),'Central Standard Time','yyyy')',' '))
```

would parse incorrectly because your function also contains single quotes inside of it. A correct version would look like 

```
base64(concat('DateTime: ',convertFromUtc(utcNow(),'Central Standard Time','yyyy'),' '))
```

And this saves/works just fine if you see the attached video.


https://github.com/Azure/LogicAppsUX/assets/13208452/4cda98be-90af-46ae-b47e-ec532d6d7ab2

**Comment by artbarrios** [comment]
Thank you for reviewing this issue. I see that the cause of the error message is the addition of the single quotes around the convert function. I realize now that this happens in the new portal designer only when there is some sort of prefix text before the convert function. 

See the example screenshots:
![ComvertErrorScreenshot1](https://github.com/Azure/LogicAppsUX/assets/3615393/2771de09-1074-40d9-a2c0-a3d125baa3a6)
![ComvertErrorScreenshot2](https://github.com/Azure/LogicAppsUX/assets/3615393/ac82fb95-e01a-4f4c-b109-c0887219d1ae)
![ComvertErrorScreenshot3](https://github.com/Azure/LogicAppsUX/assets/3615393/1471602e-7df1-4827-939b-e160fc49132e)
![ComvertErrorScreenshot4](https://github.com/Azure/LogicAppsUX/assets/3615393/d7ad6439-a4b3-4f89-82bc-db2cf89bc7fe)
![ComvertErrorScreenshot5](https://github.com/Azure/LogicAppsUX/assets/3615393/4c2e8f0b-2b7d-4d81-a6be-dc732d5ac2bf)

Can you reproduce this?

**Comment by artbarrios** [comment]
Hi Travis,

Sorry if I am not following procedures correctly, this is my first bug. Please advise if there is another way to continue to address this issue.

I think this is a bug in the new version of the Logic Apps portal designer and I discovered the key to reproducing it is including some text before the convert function. Here is a copy of my latest comment the issue: Logic App function convertFromUtc() cannot be added to Content property of Shared Send message action · Issue #2720 · Azure/LogicAppsUX (github.com)<https://github.com/Azure/LogicAppsUX/issues/2720>

Thanks again for your attention to this.

Art

====================
Thank you for reviewing this issue. I see that the cause of the error message is the addition of the single quotes around the convert function. I realize now that this happens in the new portal designer only when there is some sort of prefix text before the convert function.

See the example screenshots:
[ComvertErrorScreenshot1]<https://user-images.githubusercontent.com/3615393/245814270-2771de09-1074-40d9-a2c0-a3d125baa3a6.png>
[ComvertErrorScreenshot2]<https://user-images.githubusercontent.com/3615393/245814316-ac82fb95-e01a-4f4c-b109-c0887219d1ae.png>
[ComvertErrorScreenshot3]<https://user-images.githubusercontent.com/3615393/245814341-1471602e-7df1-4827-939b-e160fc49132e.png>
[ComvertErrorScreenshot4]<https://user-images.githubusercontent.com/3615393/245814355-d7ad6439-a4b3-4f89-82bc-db2cf89bc7fe.png>
[ComvertErrorScreenshot5]<https://user-images.githubusercontent.com/3615393/245814383-4c2e8f0b-2b7d-4d81-a6be-dc732d5ac2bf.png>

Can you reproduce this?


________________________________
