### ISSUE TITLE
Breadcrumbs and Run History Blade Disappear After Refreshing Page

### ISSUE THREAD

**Issue by BrianCollet** [Azure/LogicAppsUX#2728]
### Describe the Bug with repro steps

1. Select a Logic App Consumption resource
2. Navigate to Overview > Run history
3. Select any run ID
4. When the designer loads, notice the breadcrumbs and list of run IDs
![msedge_kVYxVxskyB](https://github.com/Azure/LogicAppsUX/assets/50160870/141e9859-4667-45a6-b406-732fac61ffd7)

5. Refresh the page
6. Breadcrumbs and list of run IDs disappear
![msedge_E63H9BPbEX](https://github.com/Azure/LogicAppsUX/assets/50160870/464a8561-775e-475b-8bf7-15df6cfc8cf5)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
N/A - Happens with all workflows
```

### Screenshots or Videos

![msedge_kVYxVxskyB](https://github.com/Azure/LogicAppsUX/assets/50160870/494f05d4-c419-4020-b43f-c683271e6384)
![msedge_E63H9BPbEX](https://github.com/Azure/LogicAppsUX/assets/50160870/e81a1fa3-85f4-4c8c-a9dd-96759589d827)

### Browser

Edge, Chrome

AB#24245984

**Comment by hartra344** [comment]
This is unfortunently a limitation to how Azure Portal works. When we move to the new designer in consumption and add run history list to it we can make sure it's all 1 blade so at least that doesn't disappear.
