### ISSUE TITLE
Deleting and re-adding a trigger causes it to not be added to workflow definition

### ISSUE THREAD

**Issue by Ram-G** [Azure/LogicAppsUX#2730]
### Describe the Bug with repro steps

The following steps can be performed in DesignerStandalone (`nx serve`) or Power Automate local portal

1. Create a flow with a Recurrence trigger and Initialize Variable action.
2. Observe Code view. It should contain the definition of the trigger.
3. Delete the trigger.
4. Re-add the Recurrence trigger.
5. Observe Code view. Note that although the Recurrence trigger has been visually added to the canvas, Code view does not contain the recurrence trigger.

**Expected:**
The trigger should get re-added correctly.

**Actual:**
Trigger is not added correctly. In practice, in Power Automate, this causes us to be unable to load the flow again.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

Initial (correct) workflow:
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/b80e92c4-329d-41b2-a954-863945c15152)

Workflow after re-adding Recurrence trigger:
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/91a7dc02-2210-4909-b934-a07cede3cf6b)

What is seen in the canvas:
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/4b04bf80-c28b-43ce-b270-ba800723377f)

### Browser

Edge

### Additional context

I verified locally in DesignerStandalone by reverting this commit that it fixes the issue: https://github.com/Azure/LogicAppsUX/pull/2685

AB#24249911

**Comment by preetriti1** [comment]
@Eric-B-Wu @rllyy97 - Can one of you debug to see if isAddingTrigger is correctly reset after readding the trigger from recommendation again.

@Ram-G - that commit should not be reverted to fix this issue, the issue might be in some state not getting set correctly.
