### ISSUE TITLE
trigger & actions in-app icons are missing in air-gapped clouds

### ISSUE THREAD

**Issue by ynauls** [Azure/LogicAppsUX#2736]
### Describe the Bug with repro steps 

The designer is now available in air-gapped clouds, the icons manifest defined in this repository have hardcoded icon URI hostname as "logicappsv2resources". This is not reachable in air-gap clouds. Logic Apps backend has been updated to return the service provider manifest with the cloud specific icon URI hostname. In air-gapped edge developer tools, we see icon failure request to the following:

- logicappsv2resources (reach out to logic apps service for cloud specific CDN) 
- cdnforlogicappsv2 (reach out to logic apps service for cloud specific CDN) 
- connectoricons-prod.azureedge.net (reach out to connectors service to cloud specific CDN) 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using Preview Designer or GA Designer 

Preview

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

n/a

### Browser 

edge

### Additional context 

*No response*

AB#24262977

**Comment by hartra344** [comment]
The manifests in this repository are meant to be temporary until the back end adopts them into the API. Rama should be the person to talk to on this.

**Comment by ynauls** [comment]
> The manifests in this repository are meant to be temporary until the back end adopts them into the API. Rama should be the person to talk to on this.

@hartra344, backend changes are complete, it will be deployed with release w24.
