### ISSUE TITLE
HTTP + Swagger Action BasePath working incorrectly

### ISSUE THREAD

**Issue by MatthewFitzsimmons** [Azure/LogicAppsUX#2741]
### Describe the Bug with repro steps

HTTP + Swagger is creating a uri that does not include the basePath

For example the following swagger file does not include /test/test2 in any of the uri generated.

{
    "swagger": "2.0",
    "info": {
        "title": "TestService",
        "version": "1.8"
    },
    "host": "example.azure-api.net",
    "basePath": "/test/test2",
    "schemes": [
        "https"
    ],

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

### Additional context

This was working correctly on the old designer.

AB#24267658

**Comment by preetriti1** [comment]
This issue is fixed now and should be available in production in 3 weeks ie by EOD of 07/08
