### ISSUE TITLE
Overview Blade_While copying identifier value, identifier not to be select.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2753]
### Describe the Bug with repro steps

1.Open a created standard LA having run identifier.
2.Try to copy the identifier value.

**Expected**: Only copy action should be work.

**Actual:** while copying the identifier value, only value is to be copied, here whole identifier is selected while using copy function.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/0edf6fbb-46ad-4dd7-a076-fea0f0143718)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Edge

### Additional context

**Environment Details:**

URL: [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-prakumar%40microsoft.com%7C392339cb587e4c43790908db6d71cb35%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638224107779179737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6w%2BhWG9isSDWIMwJJkAvuy9%2B7yvS8gdasyWs0y5yu9w%3D&reserved=0)

Version: "2.30613.1.2"

AB#24278155

**Comment by hartra344** [comment]
This is by design
