### ISSUE TITLE
Add workflow bundle version to overview blade

### ISSUE THREAD

**Issue by AbodeSaafan** [Azure/LogicAppsUX#2756]
### Describe the Bug with repro steps

Currently the overview blade shows the function host version but not the bundle version. The bundle version already comes in the same API call as the one that gets the host version.

![image](https://github.com/Azure/LogicAppsUX/assets/20479596/5495525e-746d-44f0-9d6a-edddf6e56fe6)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
N/A
```

### Browser

N/A

### Additional context

This is a feature request, speak with Abode or Travis for more information here if needed. 

AB#24286063

**Comment by hartra344** [comment]
https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/8284812
