### ISSUE TITLE
Link to release notes for LA standard 

### ISSUE THREAD

**Issue by AbodeSaafan** [Azure/LogicAppsUX#2758]
### Describe the Bug with repro steps

Currently the bundle release notes are hosted here https://github.com/Azure/logicapps/releases

Eventually they will be moved to a single markdown file but it would be nice to link to this in the portal so that they are easier to access

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
N/A
```

### Browser

N/A

AB#24286201

**Comment by hartra344** [comment]
[npx playwright show-report](https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/8284812)
