### ISSUE TITLE
Screen Hangs and locked when clicked on Outlook Send Email Connector

### ISSUE THREAD

**Issue by kipergil-wb** [Azure/LogicAppsUX#2764]
### Describe the Bug with repro steps

1- Open a crowded standart logic app workflow in designer mode.
2 - Click Outlook Send Email action to see the details
3 - Screen hangs and give an error after a while. (Page Unresponsive : Kill browser or Wait popup shown) 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome - Version 111.0.5563.111 (Official Build) (64-bit)

### Additional context

Session ID: 266ba8e6d7f74c5a904259e0f1f9861b
Version: 11.210.2.1 (v11.210.0.1#285ff1b64d.230607-0457) Signed
Composition time: 1.13s
Experiments: Toggle bread crumb
Experiments: Custom scrollbars
Accessibility: Toggle text spacing
Accessibility: Toggle tab highlighting
User settings: Dump | Save | Clear
Telemetry: Flush
Portal services: Dump
Enabled features: 187 | Details
Loaded extensions: 2 | Details
Loaded asset types: 835 | Open blade
Debug Hub: Open Debug Hub

HubsExtension: 84ms | Version: 11.210.2.111.210.0.1285164.230607-0457
Microsoft_Azure_EMA: 16ms | Version: 2.30529.1.8

AB#24289857

**Comment by hartra344** [comment]
Can you send me some more information about your workflow? If you'd rather keep it private you can send it to travisharris@microsoft.com. Without more info however, there isn't much I can do to debug this.

**Comment by kipergil-wb** [comment]
Hey @hartra344, tried to provide as much as information with the original post.
If you could guide me about the further information you need, happy to provide.

in the new designer, in a crowded logic app workflow, try to click "Send an email (V2)" action in order to replicate the scenario.
Browser and the mouse just hangs, it couldnt open the right hand pane for the connector properties screen.
Its just like running a js infinite loop, doesnt allow to do any action on the screen.
It forces me either refresh the page, or close the tab to reopen.

Our workflow contains a try-catch block, and the send email connector is under the catch block.
Please let me know what else do you need.

**Comment by hartra344** [comment]
@kipergil-wb we don't have a concept of try catch built into logic apps. What structure are you using to do this? If it's a switch node then I likely know what is causing this and we have a fix ready in our next deployment.
