### ISSUE TITLE
The new designer breaks with the error "The renderComponentIntoRoot component encountered an error while loading" when adding "Complete the message (In App)"

### ISSUE THREAD

**Issue by YingjieShi-MS** [Azure/LogicAppsUX#2770]
### Describe the Bug with repro steps

In the logic app designer, tried to add "Complete the message (In App)" action in a switch case, then the UI breaks with error "The renderComponentIntoRoot component encountered an error while loading"

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/5118022/017f77f8-7b45-44f4-a99d-ead1c90d62b9)

### Browser

Edge, Chrome

AB#24293438

**Comment by Eric-B-Wu** [comment]
Will be fixed in next release
