### ISSUE TITLE
Issue Creating an Azure MySQL Connection

### ISSUE THREAD

**Issue by berellax** [Azure/LogicAppsUX#2782]
### Describe the Bug with repro steps

Get the following error when attempting to create a connection fro Azure MySQL: 

Failed to create connection: {"error":{"code":"ApiConnectionIsInConflictState","message":"The api connection 'azuremysql' is being cleaned up. Please try again later or use different connection name."}}

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
NA
```

### Browser

Edge

AB#24314974

**Comment by rllyy97** [comment]
Hi @berellax thanks for the bug report, we should be recognizing that that name is taken and using a different name so I'm not sure quite what is happening here.  If you could, try to collect a network trace while creating the connection and that would help me determine what the issue might be.  You can find instructions on how to do that here: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file
Once you have the `.har` file you can send it to my email at rileyevans@microsoft.com

**Comment by berellax** [comment]
@rllyy97 I'm getting a different error now creating the same connection:

Failed to create connection: {"error":{"code":"ApiConnectionManagementServiceFailure","message":"The service is temporarily unable to service your request. The tracking Id is '13cc8d53-775f-462b-bc4a-411a96c2291f'."}}

**Comment by Eric-B-Wu** [comment]
@berellax this fix will take a little bit of time to go into production, generally around 2 weeks from when we close the issue. The next release we have planned for portal would complete to all regions by 7/7.
