### ISSUE TITLE
No "Run" button in the new UX Designer

### ISSUE THREAD

**Issue by Gareth064** [Azure/LogicAppsUX#2790]
### Describe the Bug with repro steps

When in the designer, you can no longer run the workflow to test it. The run button is missing

![image](https://github.com/Azure/LogicAppsUX/assets/22307223/124e53f8-dab2-4647-9f3e-5a1e9a59e39e)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/22307223/b0ab2584-b5e3-44c1-8e87-8eeaa0e96458)

### Browser

Edge or Chrome

AB#24320507

**Comment by hartra344** [comment]
This will be added before GA

**Comment by artemt-yavica** [comment]
new designed is useless without Run button

**Comment by yoshivda** [comment]
@valentina-vallalta How was this resolved? Should the button be there, or is there an alternative method? I still cannot see a run button, how can we manually test logic apps with in the designer?
