### ISSUE TITLE
Existing workflow can be saved after removing trigger, reloading page causes workflow to never show

### ISSUE THREAD

**Issue by wifun** [Azure/LogicAppsUX#2795]
### Describe the Bug with repro steps

1. go to an existing workflow
2. delete the trigger
3. save
4. reload the page

![image](https://github.com/Azure/LogicAppsUX/assets/55114634/6258dd7d-d788-4f85-9d65-e13fbcee9f30)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#24325128

**Comment by rllyy97** [comment]
This is just appearing in staging / our next release, will work on getting this hotfixed today
