### ISSUE TITLE
Connection Bad Request Designer VS Code

### ISSUE THREAD

**Issue by JorgeCadilloCalpine** [Azure/LogicAppsUX#2831]
### Describe the Bug with repro steps

Existing connection

1. On existing logic apps, when going to designer if a connection is needed for the action following message appears: Invalid connection, please update your connection to load complete details.
2. When clicking on Change Connection an error appears with Code 404 Bad request.

![image](https://github.com/Azure/LogicAppsUX/assets/134431816/173020ee-9dba-42ea-98f1-069f98b6e871)

Creating new connection.

1. Add trigger or action that uses a connection.
2. Stays on loading forever.
3. Clic on anything.
4. Clic on update connection.

![image](https://github.com/Azure/LogicAppsUX/assets/134431816/baad7f08-c7aa-499e-9ad9-5739f42916f7)

The error is only on designer, when running the Logic App the connection works.

![image](https://github.com/Azure/LogicAppsUX/assets/134431816/dae15a94-0c93-42e0-a961-fe201b0aab99)

The connections are authenticated using the authentication key that gets created on a different process using a BICEP file.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

All

AB#24354545

**Comment by ccastrotrejo** [comment]
Hi @JorgeCadilloCalpine which vscode extension version are you using? Is this happening also when creating the workflow from zero? Or is this when you update a workflow with actions on it?

**Comment by JorgeCadilloCalpine** [comment]
Hi @ccastrotrejo , first example is when updating an existing one. Second is when creating a new logic app and trying to add any action that uses a connection.

The version I'm using is: v2.24.7

**Comment by JorgeCadilloCalpine** [comment]
Hi @ccastrotrejo, could this be related to permission issues? 
We has a lot of things restricted for our accounts on Azure

**Comment by ccastrotrejo** [comment]
Hi @JorgeCadilloCalpine, it might be. It is an odd behavior as I have been trying but I haven't been able to repro. The error isn't a 403 so the resource isn't refusing the access, I feel that it is more about not been able to find the resource. If it is completely restricted that might be the case.

**Comment by JorgeCadilloCalpine** [comment]
I will close this issue, got access to a Sandbox environment where we have all permissions and it worked as expected.
The DevOps team is working on getting it fixed on the dev environment.

Thank you for the help @ccastrotrejo
