### ISSUE TITLE
Invalid Parameter in the Logic app designer

### ISSUE THREAD

**Issue by ShabsMS** [Azure/LogicAppsUX#2860]
### Describe the Bug with repro steps

The error invalid parameter pops up in new designer for SQL connector when there are no field for parameter .
I was able to repro this issue by having a Logic app in Vnet and forced a bundle version of 1.21.12.0 (AzureFunctionsJobHost__extensionBundle__version) which was used in Customer environment (The bundle version was default in app setting for customer but in backend I could see the above version used)
Workaround is to use Fallback URL to old designer.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/95284014/5c336561-c9df-4061-98e2-5d9b0cf8a193)

### Browser

Edge

AB#24386948

**Comment by rllyy97** [comment]
@ShabsMS I am unable to reproduce your issue, can you provide us with your workflow file so we can see what is being serialized?  Or just open the `Code view` panel tab and that should show the serialization for just that one operation.
Also is the `invalid parameters` error appearing on deserialization of your existing workflow or is it after you add and set up the operation?

**Comment by ShabsMS** [comment]
@rllyy97  My repro is deleted and I am unsure of serialization and de serialization values  to be checked.
Could you please enlighten me on it. There is an HAR trace collected from Customer environment on the case .do let me know if you need it .

**Comment by rllyy97** [comment]
@shabsMS Does the error appear right after loading the workflow (deserialization), or do you have to do some sort of edit to the workflow to make the error appear?  Without a repro I won't be able to find the actual issue.
I'll take a look at the HAR, but I'm not sure this issue will show anything relevant in the HAR.
If this is an ICM can you link me to it?

**Comment by ShabsMS** [comment]
@rllyy97  the issue appeared in my repro when i made change to the bundle version and when it loaded the workflow in designer page. Without the forcing of bundle version the issue didnt happen. 
i will ping the icm details to you on teams chat and HAR as well

**Comment by rllyy97** [comment]
@shabsMS, are you still experiencing this issue?
