### ISSUE TITLE
Blank canvas when creating a new map

### ISSUE THREAD

**Issue by christopherhouse** [Azure/LogicAppsUX#2872]
### Describe the Bug with repro steps

Creating a new map results in a new window with a blank canvas, no option to add source/target schema.  Attempting to save the new, blank map has no effect, no new file is created.

Repro steps:

1. Open VS Code
2. Open a Logic App (Standard) project with a source and a target schema in the Artifacts\Schemas directory
3. Go to the Azure tab in VS Code and click the "Create new data map" button
  3a. alternatively, press F1 and choose Data Mapper: Create new data map
4. Enter a name for the new map

A new window is opened with the map name entered in #4 above visible in the file tab but no content displayed on the canvas, no option to add source/target schemas.

Things I've tried with no success:

- Close/reopen VS Code
- Close/reopen Logic App project folder
- Uninstall/reinstall Data Mapper extension
- Setup a new VM in Azure, installed VS Code, Data Mapper extension and other dependencies.  Same result, blank canvas

Also worth noting that the first time I created a map, the canvas did render, I was able to choose source/target schemas.  At the time, I hadn't moved my schemas into the Artifacts\Schemas folder.  I added them but the extension didn't seem to pick them up, so I restarted VS Code.  Once I restarted VS Code, I started experiencing the issue described above.

### Screenshots or Videos

<img width="1193" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/748998/3660da51-579d-490c-a275-c91f54e3d34a">

### Version

- Extension version v2.37.0
- VS Code version 1.79.2

AB#24405052

**Comment by MS-Santi** [comment]
Same issue - running on a dev container. Output is:
![image](https://github.com/Azure/LogicAppsUX/assets/12851433/b8d3ba29-31dd-49a6-a6a7-800a68c60e3a)

.devcontainer.json:
{
	"name": "Logic App (Standard)",
	"dockerFile": "Dockerfile",
	"forwardPorts": [
		7071
	],
	"features": {
		"ghcr.io/devcontainers/features/node:1": {
			"version": "14"
		},
		"ghcr.io/devcontainers/features/azure-cli:1": {
			"version": "latest"
		},
		"ghcr.io/devcontainers/features/git:1": {},
		"ghcr.io/devcontainers/features/github-cli:1": {},
		"ghcr.io/stuartleeks/dev-container-features/azure-cli-persistence:0": {},
		"ghcr.io/stuartleeks/dev-container-features/shell-history:0": {}
	},
	"customizations": {
		"vscode": {
			"extensions": [
				"Azurite.azurite",
				"ms-azure-devops.azure-pipelines",
				"ms-azuretools.vscode-bicep",
				"ms-azuretools.vscode-azurelogicapps",
				"ms-azuretools.vscode-azurefunctions",
				"ms-dotnettools.csharp",
				"ms-dotnettools.vscode-dotnet-runtime",
				"ms-vscode.vscode-node-azure-pack",
				"davidanson.vscode-markdownlint"
			],
			"settings": {
				"files. Associations": {
					"**/.azuredevops/pipelines/*.yml": "azure-pipelines"
				}
			}
		}
	},
	"postCreateCommand": "cp ./.devcontainer/starter.settings.json ./source/workflow-designtime/local.settings.json",
	"remoteUser": "vscode"
}

Dockerfile:
FROM mcr.microsoft.com/azure-functions/dotnet:4-dotnet6-core-tools

**Comment by christopherhouse** [comment]
I just rolled back to v2.15.15 of the mapper extension and that seems to behave correctly.
