### ISSUE TITLE
[Azure Database for MySQL] "ApiConnectionManagementServiceFailure" and "ApiConnectionIsInConflictState"

### ISSUE THREAD

**Issue by PremPandeyyy** [Azure/LogicAppsUX#2875]
### Describe the Bug with repro steps

In a new designer, when trying to create new connection in Logic App Standard for 'Azure Database for MySQL Database', it is throwing below errors:

After adding "Azure Database for MySQL" connector for the first time, error:

{"error":{"code":"ApiConnectionManagementServiceFailure","message":"The service is temporarily unable to service your request. The tracking Id is 'd50661a0-579a-4deb-8fc8-77307b677f14'."}}

After trying to create the connection again, it will throw this error: 

{'error':{'code':'ApiConnectionIsInConflictState','message':'The api connection 'azuremysql' is being cleaned up. Please try again later or use different connection name.'}}

**This works well in the old designer**

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/138096970/58ff02f7-15fc-4949-a385-274242574eca)
![image](https://github.com/Azure/LogicAppsUX/assets/138096970/c6958dbd-2dcf-471e-b1d7-a973dec0fa4f)

### Browser

Chrome

AB#24410157

**Comment by rllyy97** [comment]
Hi @PremPandeyyy, thanks for the bug report, have you experienced this bug with other connectors or just the MySQL connector?  We recently fixed an issue where that connector was not showing all of the required connection parameters, which most likely caused your first connection failure, and the second was probably just residual.
Our fix for the MySQL connector will be releasing through next week and finishing on the 7th

**Comment by PremPandeyyy** [comment]
Hello @rllyy97
We experienced this with 'Azure Database for MySQL' connector alone. Thank you for the update on the fix.
