### ISSUE TITLE
Newly added connection not shown in "select connection" panel

### ISSUE THREAD

**Issue by wifun** [Azure/LogicAppsUX#2884]
### Describe the Bug with repro steps

I've pinpointed the issue to release v2.36.0, v2.35.0 does not appear to have this issue.
https://github.com/Azure/LogicAppsUX/compare/v2.35.0...v2.36.0

Suspecting it's due to this change:
https://github.com/Azure/LogicAppsUX/commit/52741e2415b5245b9b25bc72dcd855261b688d53 @rllyy9

1. Click "change connections" for an action
![image](https://github.com/Azure/LogicAppsUX/assets/55114634/fead2255-fe55-4f40-a027-d5001b25e2db)
3. Add a new connection
4. After connection is added the Parameters panel is shown
5. Click again on "change connections"
    * Note that the new connection is not shown in the "select connection" list (nothing is selected)
    * ![image](https://github.com/Azure/LogicAppsUX/assets/55114634/a35ce64c-4547-4b14-bcfb-ba91e1143527)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#24419912

**Comment by wifun** [comment]
@rllyy97 just considering options, how risky would you say it is to revert your commit in a hotfix release for v2.38?

**Comment by rllyy97** [comment]
I'd rather try to fix the issue first rather than hotfix, we probably just need to force a query refetch, I'll look into that today
