### ISSUE TITLE
Standard Logic App - ASB Content expressions Failing workflow validation

### ISSUE THREAD

**Issue by atroiano-glue** [Azure/LogicAppsUX#2886]
### Describe the Bug with repro steps

The Standard connector for ASB does not validate correctly objects.
We have been using the ASB connector to send out error payloads to ASB. All was fine with the previous designer, however since this new one went GA, we have seen that expressions within the Content property of Service Bus Connector fail the workflow validation.

Use the Template below to add an expression such as: `split(workflow()['id'], '/')[2]` or `result('Scope')` and the workflow validation will fail with the following error message:

```
Workflow validation failed for the workflow 'wf-test-Errors'. The template validation failed: 'The template action 'Send_message' at line '1' and column '243' is not valid: "Unable to parse template language expression 'base64(concat('{','
','  "Name": "','split(workflow()['id'], '/')[2]','",','
','  "ScopeResult": ','result('Scope')','
','}'))': expected token 'RightParenthesis' and actual 'Identifier'.".'.
```
We are not in control of the base64 function as that is automatically added as a requirement of using ASB Standard API connection.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose": {
                "inputs": {
                    "key": "Hello!"
                },
                "runAfter": {},
                "type": "Compose"
            },
            "Send_message": {
                "inputs": {
                    "body": {
                        "ContentData": "@{base64(concat('{','\n','  \"Name\": \"','split(workflow()['id'], '/')[2]','\",','\n','  \"ScopeResult\": ','result('Scope')','\n','}'))}"
                    },
                    "host": {
                        "connection": {
                            "referenceName": "servicebus-3"
                        }
                    },
                    "method": "post",
                    "path": "/@{encodeURIComponent(encodeURIComponent('queue_name'))}/messages",
                    "queries": {
                        "systemProperties": "None"
                    }
                },
                "runAfter": {
                    "Compose": [
                        "SUCCEEDED"
                    ]
                },
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Browser

Chrome.

AB#24422012

**Comment by Eric-B-Wu** [comment]
Thanks for reporting this issue, will take a look to see why this is happening

**Comment by atroiano-glue** [comment]
When can we expect a Release - as this has now been fixed? @Eric-B-Wu

**Comment by atroiano-glue** [comment]
> This was planned in our next release, which is expected to finish 7/7. That being said, we may have some delays that will push it to next week in some regions due to the holiday in the US

Thank you.

**Comment by atroiano-glue** [comment]
Hi @Eric-B-Wu this issue is now impacting all our Workflows in our PROD environment.  When saving the workflow, we are seeing the following validation error, making our workflows unusable.
The Shared connector for ASB has now become unusable for us.
Please escalate this.

![image](https://github.com/Azure/LogicAppsUX/assets/98324414/9f51db3d-f981-4f1d-b7da-fc16b159293f)
