### ISSUE TITLE
Trailing spaces at the end of the logic app workflow action name don't get trimmed.

### ISSUE THREAD

**Issue by AkshayAmbekar26** [Azure/LogicAppsUX#2896]
### Describe the Bug with repro steps

1. Open any standard logic app's workflow designer.
2. Add or rename any action and add an empty space at the end of the action name
3. Save the workflow.
4. Check the action name that is saved in code view or designer view.

- The action name is being saved with a trailing space, which causes significant issues during the automated testing of our logic apps. Testers rely on the displayed name in the designer and use the same name in automated tests. However, due to the trailing space left by the logic app developers, the tests frequently fail.
- During the development process, we can take precautions to avoid leaving trailing spaces behind. But it will be cool if the logic app itself automatically remove it upon saving the workflow.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/109142987/c9225815-905a-4cb0-b084-b000ee8b6d49)
![image](https://github.com/Azure/LogicAppsUX/assets/109142987/dc1d36c7-28e7-43e6-bd5e-b88e41530a5a)

- Automated test example
![image](https://github.com/Azure/LogicAppsUX/assets/109142987/91e22a2d-b925-4eb9-9b2c-c62858ccdde9)
### Browser

Microsoft Edge

AB#24434608

**Comment by preetriti1** [comment]
Designer will honor every character entered by user in the action name we replace space with underscore because of runtime behavior, we won't try to trim the values without user permission since it may be intentional by some other user. Please try to update your automation code to correctly pick the action names from definition for it to work.

Closing this issue as it won't be fixed.
