### ISSUE TITLE
HTTP swagger action/trigger broken - vscode

### ISSUE THREAD

**Issue by greenlipton744** [Azure/LogicAppsUX#2899]
### Describe the Bug with repro steps

1. In Visual Studio Code - Open a logic app project
2. Create a new Statefull workflow
3. Open Designer
4. Add a trigger/action of the type "HTTP + Swagger"
5. Provide a swagger endpoint (for example. https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/export?DocumentFormat=Swagger&ApiName=Face%20API%20-%20v1.0) and confirm
6. Under swagger operation, select the operation (unable to do)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "httpswaggertrigger": {
                "type": "Http",
                "inputs": {},
                "recurrence": {
                    "interval": 3,
                    "frequency": "Minute"
                },
                "metadata": {
                    "apiDefinitionUrl": "https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/export?DocumentFormat=Swagger&ApiName=Face%20API%20-%20v1.0",
                    "swaggerSource": "custom"
                }
            }
        },
        "parameters": {}
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![ssdfsdf](https://github.com/Azure/LogicAppsUX/assets/1218438/e47f017e-c31a-42ee-bdf6-7603783a5b51)

### Browser

VS code

### Additional context

I did a rollback to another version of the logic app standard plugin in VS code from a few months ago, and I'm now able to select an operation. This seems to be a bug in one of the recent versions of the plugin.

AB#24437758

**Comment by Kyoril** [comment]
Same issue for me. In the Azure Designer this action works, in vscode it doesnt. It also affects existing actions where it is then unable to load dynamic input parameters.

**Comment by Eric-B-Wu** [comment]
@ccastrotrejo are we retrieving from the same endpoint in vscode?

**Comment by ccastrotrejo** [comment]
Hi @greenlipton744, thanks for raising this issue. I was able to repro it. Which is the version you did the rollback to?
