### ISSUE TITLE
Delay in fetching the created connection.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2902]
### Describe the Bug with repro steps

1.Create a Standard Logic app and add stateful workflow into.
2.Add http trigger and add - API or Service provider or Function connection (any one).
3.Connection created successfully.
4.Try to see the established connection on same time.

**Expected:** The established connection should be present at the same time after created successfully connection.

**Actual:** Not able to see the established connection. After refreshing the portal it becomes visible.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/0e0f8ba9-217b-4f01-aee8-62c42df7175a)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-prakumar%40microsoft.com%7C8fba17541dec415bd2b308db7ba263b8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638239709652261160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2F4Dz7qewvxq8uJPqGJ0diYsyQ2IMx1B3g13tLK40CQQ%3D&reserved=0)

**Version: 2.30701.1.1**

AB#24438555

**Comment by vgouth** [comment]
Similar issue repro with service bus and IBM host file connectors. 

When a service bus/ IBM host file action/trigger is added when we try to add another action from service bus or IBM host file in same workflow encountering to create a new connection page. 

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/1e7afad6-f725-40a1-8bd7-ba1b2be2cdf9)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/187bc6af-95db-40e9-af50-f7b5aa769915)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/043f7cef-eaab-4017-9ded-bd76c06a65f1)

**Comment by Eric-B-Wu** [comment]
@rllyy97 is this a known issue that you had fixed before?

**Comment by rllyy97** [comment]
@Eric-B-Wu Yes this was fixed with this PR https://github.com/Azure/LogicAppsUX/pull/2890
This is not in any hotfix branch though at the moment

**Comment by vgouth** [comment]
Issue **not** repro in the latest portal request

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccaeede01bc6247df730608db899fa56e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638255091053826394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XkVfWg4QCG8m1pHWR2lnWsaUSDKt3WPkUseVXK7UwVY%3D&reserved=0)
**Version:** 2.30717.1.1
