### ISSUE TITLE
IBM host files action : Running trigger failed by showing server failure message and format of Input.Json contents copied in Rows parameters of the Action is getting changed

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#2904]
### Describe the Bug with repro steps

1.Create a new workflow app using VS Code.
2.Create a stateful workflow
3.Add a HTTP trigger to the workflow and save the workflow
4.Add a "Generate Host File Contents" (from the IBM Host File SP) Action after the trigger
5.The Connection Parameters can (should) be left unchanged - or, if you like: 37 and unchecked.
6.For the first 2 parameters of the Action, enter: redefines.hidx (for the HIDX Name), "CUSTOMER_FILE_ROW" (for the Schema Name).
7.Open the attachment named InputJson.txt, copy the contents. In VS Code - the third Parameter Rows, has a button on the right enabling you to fill out all Input as a single value, click this. Delete the contents of the text box ("[ null ]" or similar) and then paste in the copied Input.Json contents.
8.
Add a "Parse Host File Contents" Action, and fill out the first 2 Parameters as above (step 6). For the "Binary Contents" select the Dynamic content "Binary Contents" (which is the output of the previous step).
9.Add a response action as well - Http Response - for the Body, use the Dynamic content "Rows" (the output from the previous step).
10.Click on "Artifacts/Maps", right click - reveal in file explorer. Download the attachment "Redefines.hidx" into that directory.
11.Press F5/Run the Workflow
12. Get the trigger URL by going to the "overview" page for the workflow.
13. **Expected Result** : Run trigger should succeed and format of Input.Json contents copied in Rows parameters of the Action is should not change.
**Actual Result :** Run trigger getting failed by showing server failure message and the format of Input.Json contents copied in Rows parameters of the Action is getting changed.

**Input.Json contents.**
[
  {
    "CUSTOMER_TYPE": "B",
    "SIMPLE_REDEFINITION1": {
      "BUSINESS": {
        "NAME": "ABC"
      }
    }
  },
  {
    "CUSTOMER_TYPE": "P",
    "SIMPLE_REDEFINITION1": {
      "PERSONAL": {
        "NAME": {
          "FIRST_NAME": "Rob",
          "LAST_NAME": "BEA"
        }
      }
    }
  }
]

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Generate_Host_File_Contents": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "hidx": "redefines.hidx",
            "schema": "CUSTOMER_FILE_ROW",
            "rows": [
              [
                {
                  "CUSTOMER_TYPE": "B",
                  "SIMPLE_REDEFINITION1": {
                    "BUSINESS": {
                      "NAME": "ABC"
                    }
                  }
                },
                {
                  "CUSTOMER_TYPE": "P",
                  "SIMPLE_REDEFINITION1": {
                    "PERSONAL": {
                      "NAME": {
                        "FIRST_NAME": "Rob",
                        "LAST_NAME": "BEA"
                      }
                    }
                  }
                }
              ]
            ]
          },
          "serviceProviderConfiguration": {
            "connectionName": "hostfile",
            "operationId": "generateFileContents",
            "serviceProviderId": "/serviceProviders/hostfile"
          }
        },
        "runAfter": {}
      },
      "Parse_Host_File_Contents": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "hidx": "redefines.hidx",
            "schema": "CUSTOMER_FILE_ROW",
            "contents": "@body('Generate_Host_File_Contents')?['contents']"
          },
          "serviceProviderConfiguration": {
            "connectionName": "hostfile",
            "operationId": "parseFileContents",
            "serviceProviderId": "/serviceProviders/hostfile"
          }
        },
        "runAfter": {
          "Generate_Host_File_Contents": [
            "SUCCEEDED"
          ]
        }
      },
      "Response": {
        "type": "Response",
        "kind": "Http",
        "inputs": {
          "statusCode": 200,
          "body": "@body('Parse_Host_File_Contents')?['rows']"
        },
        "runAfter": {
          "Parse_Host_File_Contents": [
            "SUCCEEDED"
          ]
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {
    "hostfile": {
      "connection": {
        "id": "/serviceProviders/hostfile/connections/hostfile"
      },
      "connectionName": "abc",
      "api": {
        "id": "/serviceProviders/hostfile"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/1fcb7a07-ecca-4f5f-a32e-26601034e46e)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/cb4a4065-ff1b-4f77-b8a2-39bd1c3c977e)

{
  "code": "ServiceProviderActionFailed",
  "message": "The service provider action failed with error code 'ServiceOperationInvalidParameter' and error message 'The flat file processor based on HIDX: 'C:\\home\\site\\wwwroot\\Artifacts\\Maps\\redefines.hidx', and Schema: 'CUSTOMER_FILE_ROW' could not parse the input binary data. Error: 'Creation of record number: 0 failed. Description: 'HISMAGJ0044 When converting to host format parameter CUSTOMER_FILE_ROW in method PackIndependentStructure structure CUSTOMER_FILE_ROW was not of the expected type.'.'.'."
}

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-prakumar%40microsoft.com%7C8fba17541dec415bd2b308db7ba263b8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638239709652261160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2F4Dz7qewvxq8uJPqGJ0diYsyQ2IMx1B3g13tLK40CQQ%3D&reserved=0)

**Version:** 2.30701.1.1

AB#24438582

**Comment by vgouth** [comment]
Issue repro in latest VS code request

1.VS Code extension: vscode-azurelogicapps-2.45.3.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc2NDI0MDc0L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.31.2.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc2NDI0MDc0L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.31.2.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7C9b145287f20e418e2c1f08db87674b69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638252650006637632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kbPqYTij39ZqG9ht1rsLQe878QJn%2BWEbeNLJ9G92sNM%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7C9b145287f20e418e2c1f08db87674b69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638252650006637632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=q7lkzMt7ekttUTs3iCrawTbmF6yLVSMBKGqoohGhmcI%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.31.2/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.31.2_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.31.2%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.31.2_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C9b145287f20e418e2c1f08db87674b69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638252650006637632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S2OTcXG4aWL%2FqPEazIq1j%2FtrDc78UVKBig786EGGpcU%3D&reserved=0)


![image](https://github.com/Azure/LogicAppsUX/assets/113517384/d8757c30-c35a-4391-9379-5c40d025ec9c)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/753a2eec-a779-4ab4-99fd-7e24ae47d60b)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/457e1365-f5bb-4f54-b68a-0df2d40468be)

**Comment by vgouth** [comment]
Issue repro in the latest request

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C22eca00d05414450524c08db8c1dbdfd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638257831648260657%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Spc48TAD7oGuAs8oPmFAqnCllLZpAdhrd%2BkWGMT78Vo%3D&reserved=0)
**Version:** 2.30717.1.1

It is automatically adding the **backslash n** code in codeview.

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/86d2ede4-b44f-4e31-9c27-b8787a3d6fa9)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/986c9654-15d9-4645-9669-4548ce26e7ed)

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue is repro in the vsix 2.55.1
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/8fb86281-6520-41fb-9b76-f675ccf972fc)

**Comment by vgouth** [comment]
Issue repro in the latest request 

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ca913e3ff33294e1163d608db9db5f11a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638277177033505326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MKfEmdMGq%2BLkG6Dt%2Bs8o2wQO8nicOL75f4AcxCeQnZA%3D&reserved=0)
**Version:** 2.30814.1.1

Added code format is changing automatically into different format once workflow is save and run.

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/913bb52f-74c7-4cde-8fd3-c186ab5221c5)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/9f3f194f-f625-488e-a32e-78265ffc0588)

**Comment by vgouth** [comment]
Issue repro in the latest request.

1.VS Code extension - vscode-azurelogicapps-2.58.0.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc4MzA5NDU2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.36.3.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc4MzA5NDU2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.36.3.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YbUQGX1JIg4zw8dJj3tXaSQ1UvYGHZoesH4PqdR3ir0%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iTF28R1F1CAdbvqFM1XoCLdADsc09X7HLH2v22QsIpc%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.36.3/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.36.3_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.36.3%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.36.3_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HnqMsrbHp0z5Arf04tfU0ktLF%2FIFr2p48GDG0%2FVDs6s%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/5f853c28-5a68-4989-998c-c0e3e7d95a97)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/d0352442-003a-4b74-bd64-79ac7aeced41)

**Comment by vgouth** [comment]
Issue repro in the latest request

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C3bbfb26744894c0b079608dba8645d1d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638288921318543127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=J9kIfve5wM5qxBlzUsk1S6g%2FK0L8EiE%2FyNacGm2Ui1Q%3D&reserved=0)
**Version:** 2.30828.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/a13f2d2d-af26-425f-8c5d-a7bfb318d013)

Added code format is changing automatically into different format once workflow is save and run.
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/242f86c9-c1d6-4e69-a0dd-844ddf5891db)
