### ISSUE TITLE
Token picker : Selecting Multiple tokens

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2905]
### Describe the Bug with repro steps

1.Create a standard LA and add stateful workflow.
2.Add http trigger and compose.
3.Try to add multiple tokens at a time.
4.While selecting multiple tokens:

**Expected:** The token picker box should not be close until the multiple tokens selected at the same time.

**Actual:** Only a token is selected at a time and we have to again open the token picker box to select next token.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/3583e8d3-8dd6-48b4-acc5-abe1dc3c59c4)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-prakumar%40microsoft.com%7C8fba17541dec415bd2b308db7ba263b8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638239709652261160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2F4Dz7qewvxq8uJPqGJ0diYsyQ2IMx1B3g13tLK40CQQ%3D&reserved=0)

**Version:** 2.30701.1.1

AB#24439290

**Comment by Eric-B-Wu** [comment]
Will reach out to Kishor about some possible design ideas/ upgrades we can do to improve this experience

**Comment by hartra344** [comment]
Not a change we'll be making without data on how customers add tokens. This was expressly discussed in design meetings previously
