### ISSUE TITLE
Revised: Changing Tabs in VSCode causes Designer to refresh - losing all unsaved changes

### ISSUE THREAD

**Issue by axiomitdavid** [Azure/LogicAppsUX#2908]
### Describe the Bug with repro steps

1. Open workflow1 in VS Code Designer
2. Open workflow2 in VS Code Designer in a second tab
3. Make any type of change to workflow1 and do not click save button
4. Display workflow2
5. Switch to workflow1 and all changes are lost

### Version

- Extension v2.28.4

VSCode Info
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

### Additional context

Unable to now reference "workflow2" without having the "workflow1" in a state where it can be saved.

AB#24443256

**Comment by axiomitdavid** [comment]
This is impacting ability to use VSCode for Logic Apps Standard.  If you have the designer open and switch to another VSCode tab and return to the designer, the designer refreshes the workflow, losing changes and does not leave the current action open.  For complex workflows, finding your way back to where you were working takes time and you could potentially go to the wrong action and make changes where they were not intended.

Fairly certain this did not happen in older 2.x and definitely not in 1.x designer versions.  It appears to be a recent change in behaviour.

**Comment by ccastrotrejo** [comment]
Hi @axiomitdavid thanks for raising this issue. I will take a look on this.

**Comment by hartra344** [comment]
@ccastrotrejo what is the current status of this? It got reported again today and I can see how it would be disruptive.

**Comment by ccastrotrejo** [comment]
@hartra344  I haven't started working on the fix for it, I will prioritize it.

**Comment by Eric-B-Wu** [comment]
i think this may be a similar thing also for copilot where if we open up the copilot panel, the designer refreshes, losing all unsaved changes. I believe it may be because we're changing some prop in the wrappers, which causes the children to rerender

**Comment by ccastrotrejo** [comment]
Yeah it might be happening in the react projects we host. The reason of this happening is because we are not saving the "dirty" states
