### ISSUE TITLE
2.42 - Concat Regression

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#2916]
### Describe the Bug with repro steps

When using concat function, can't map 3rd parameter with the expanded function card

Repro steps 

1. Add Concat function to canvas and connect string as first input (works when function is in collapsed mode)
2. In the functions panel, add a third input
3. Attempt to connect value from canvas as third input does not work (connection disappears)

Notes:

- Third parameter isn't exactly the issue here, really cannot add a second or first parameter from expanded card either
- Adding the second parameter from the functions panel does work
- This seems to be an issue with all functions with unlimited parameters
- Able to connect second and third parameter in collapsed mode

### Screenshots or Videos

See internal link

### Version

5.42

AB#24455791

**Comment by DanielleCogs** [comment]
I am unable to reproduce this issue in the standalone app as is
