### ISSUE TITLE
2.42.0 Data mapper crash when using concat

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#2917]
### Describe the Bug with repro steps

When trying to map a 3rd input, data mapper will crash

Repro steps from video

1. Add concat function to canvas, add first connection from canvas in collapsed mode
2. In function panel, add third input
3. Connect input to third slot using canvas expanded node

### Screenshots or Videos

Please see internal tracking sheet

### Version

2.42.0

AB#24456182

**Comment by DanielleCogs** [comment]
unable to reproduce on first pass

**Comment by sandroasp** [comment]
Steps to reproduce the issue, and it is not directly related to the concat function 

https://github.com/Azure/LogicAppsUX/assets/1318263/0f62c013-bd14-4c58-880d-43971b0ea3df
