### ISSUE TITLE
Extra "body/" added when using [Perform an unbound action (preview)] on new designers

### ISSUE THREAD

**Issue by atsugimatsu** [Azure/LogicAppsUX#2920]
### Describe the Bug with repro steps

Logic app Standard
In Workflow -> designer
	1. Click add action
	2. Search for "dataverse"
	3. Select "Perform an unbound action (preview)"
	4. Fill configuration
	5. Save
Then there is extra "body/" added to the body parameters:
![image](https://github.com/Azure/LogicAppsUX/assets/106584034/3f092c9a-4a43-4f96-a297-6646e2a85bc9)

This does not happen in legacy designer, using the fallback url.
![image](https://github.com/Azure/LogicAppsUX/assets/106584034/8b194b07-0d47-4a32-ab07-bea0c08ed7fa)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#24462741

**Comment by rllyy97** [comment]
Hi @atsugimatsu, thanks for reporting your issue, we are thinking this might be a regression caused by some of our recent feature work, I've created a Known Issue you can find here to track progress: https://github.com/Azure/LogicAppsUX/issues/2949

**Comment by rllyy97** [comment]
This issue appears to be separate from the previously linked dynamic data issue.  I am still investigating the source of the regression and will update here when I have an ETA for a fix.

**Comment by atsugimatsu** [comment]
Hello @rllyy97, there seems to be a same issue with [Perform a bound action (preview)] on new designers. Please check and let us know if there is an ETA for a fix.
![image](https://github.com/Azure/LogicAppsUX/assets/106584034/6cc03881-8103-4071-a0bf-fc95cbdbcf98)

**Comment by rllyy97** [comment]
Quick update, I think I've found a safe fix and am doing some testing.  If all goes well this should be a part of our next release cycle, being fully deployed by September 8th.

**Comment by rllyy97** [comment]
@atsugimatsu I've fixed the issue and will be hotfixing it into our current release cycle, you should see it live in prod by EOD this Friday (09/29)
