### ISSUE TITLE
Logic Apps Standard built-in Service Provider SQL connector Dynamic Content output is not visible in new designer

### ISSUE THREAD

**Issue by nidubey1** [Azure/LogicAppsUX#2924]
### Describe the Bug with repro steps

In a specific Standard Logic Apps workflow we do not see the built-in Service Provider SQL connector Dynamic Content output in the subsequent action. The same works fine with fallback URL([https://aka.ms/lafallback]. Below are the details:

Unexpected New designer where the previous Service Provider SQL connector Dynamic content output is not visible example:

![image](https://github.com/Azure/LogicAppsUX/assets/85997053/de4e313b-8725-4647-97f8-2bffb35b0980)

Expected Old designer where the previous Service Provider SQL connector Dynamic content output is visible example:

![image](https://github.com/Azure/LogicAppsUX/assets/85997053/e50c0f19-410c-4d47-b0a9-6a24347938f0)

- The Logic Apps Resource has VNET Integration enabled with a route table
- Further the SQL Server is also has private endpoint enabled.
-  Tried to replicate the same scenario but could not replicate it with simple Logic Apps Standard VNET Integration and SQL Private endpoint setup
- In this specific issue Standard Logic Apps there is a route table routing traffic to Virtual Appliance. But the same setup works fine with old fallback designer.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#24467304

**Comment by c0nfus3dk1w1d4** [comment]
I also have this issue in Safari, Chrome, Edge.

**Comment by nidubey1** [comment]
Hi @Eric-B-Wu, the details are already shared with you internally, also sent to you over mail at: wue@microsoft.com

**Comment by nidubey1** [comment]
Hi @Eric-B-Wu , hope you are doing well. Do you have any updates further on the issue scenario?

**Comment by Eric-B-Wu** [comment]
talked offline with customer, seems like it was an intended change from old designer to new designer - that being said, if this causes confusion we are considering a "See All Tokens option to show type-filtered tokens" as seen in: https://github.com/Azure/LogicAppsUX/issues/1815

**Comment by Eric-B-Wu** [comment]
closing this issue as resolved after discussion with customer
