### ISSUE TITLE
Dynamic tree extension call results being unexpectedly cached

### ISSUE THREAD

**Issue by Ram-G** [Azure/LogicAppsUX#2927]
### Describe the Bug with repro steps

In LAUX package v2.38,

1. Go to an action with a folder picker editor in PA Portal.
2. Navigate 2 levels into the folder picker -- something like `/Desktop/Folder 2`
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/fefbdccb-ff08-4cd0-a383-73da8153aa29)
3. Observe that we are unable to navigate past first folder level.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

### Additional context

A related issue was -- Newly added connection not shown in "select connection" panel [#2884](https://github.com/Azure/LogicAppsUX/issues/2884) that was fixed in https://github.com/Azure/LogicAppsUX/pull/2890

AB#24470506

**Comment by shuktika12163** [comment]
@rllyy97 Since you had fixed the previous regression in stale connections, this seems to be another one due to query client change. Adding staleTime and cacheTime for list tree query seems to fix this. Would it be possible to do a quick fix for it? Thanks!
