### ISSUE TITLE
Can't Load Map

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#2932]
### Describe the Bug with repro steps

We have a fairly simple Map and two XSD schemas but it cant be loaded. Please see video for details. Here is (internal) link to YML and schemas

https://microsoft-my.sharepoint.com/:f:/p/kewear/IgDk1giPnioNRqBUO69IB40hAfijigwuY-q1dgF5IlRc1I8?e=44CKcz

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/83832436/18ef6b1e-ab03-4666-a472-3a2fbdb5161b

### Version

2.42.0

AB#24483336

**Comment by mohit-jagtiani** [comment]
Is your root Logic App project?

**Comment by kewear** [comment]
This is a working project - i have other maps that work properly

**Comment by mohit-jagtiani** [comment]
yeah, I see now existing map doesnt load on data mapper. This is not good for code sharing
