### ISSUE TITLE
Standard Logic Apps not showing any Dataverse Environments and existing workflows just say "Failed to retrieve dynamic outputs"

### ISSUE THREAD

**Issue by sladeyman** [Azure/LogicAppsUX#2934]
### Describe the Bug with repro steps

1 : open WORKFLOW
2 : select a dataverse connector
3 : Error thrown : Failed to retrieve dynamic outputs

Also - on a NEW workflow - NO ENVIRONMENTS are available for Dataverse ? 

This i s happening across THREE subscriptions ( dev, qa and prod )

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
ALL WORKFLOWS - over 100
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/84184326/75e2cbd4-bd63-44f4-b826-a2e14cde7afd)

### Browser

all

### Additional context

the worklows are still RUNNING - but we cannot EDIt any of them with dataverse connectors  ( or SharePoint )

AB#24486335

**Comment by rllyy97** [comment]
Hi @sladeyman, thank you for reporting your issue, it looks like it's having a large impact given your number of subscriptions and workflows.  If you need to access the legacy designer we have steps explaining how to do so [in our documentation here](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#fallback-to-legacy-designer).  In the meantime I'll be looking into the issue and update you on our progress.

**Comment by rllyy97** [comment]
@sladeyman I tried replicating your issue in one of my apps and wasn't able to reproduce it.
To help me dig into this issue more I might need you to send a network trace and your session ID, if you're comfortable sharing that information.
You can find information on how to collect a network trace in our documentation here:
https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file
Once you have the `.har` file you can send it to my email at rileyevans@microsoft.com

**Comment by sladeyman** [comment]
hey buddy - im hearing now his is wider issue with a few folks. 

I am pondering if it is anything to do with the recent powerapps URL changes ?

**Comment by rllyy97** [comment]
@sladeyman thanks for sending your trace and session ID!  We've been getting a lot of bug reports related to this connector and Sharepoint so it looks like we may have had a regression with some recent dynamic data changes.
I've created a Known Issue located here https://github.com/Azure/LogicAppsUX/issues/2949.
I'm going to be working on this as priority and will be updating that issue page as things progress.

**Comment by sladeyman** [comment]
Great - thanks Riley. I have also spotted an issue with Child workflows being "renamed" - this might be isolated so i will try and recreate and report if required. Not sure its connected though.

**Comment by rllyy97** [comment]
Hi @sladeyman, just updating you that we recently finished rolling out a hotfix for the issue mentioned previously, and you should now be able to see the dynamic inputs loading properly.  During my testing this also indirectly fixed the issue with dynamic outputs loading properly as well.
Feel free to test out your use cases and if anything isn't working as expected please let us know and we will reopen your issue + investigate further!
Also if you do experience the behavior of child workflows being "renamed" again feel free to make a new issue report for that as well.
