### ISSUE TITLE
Undo button doesn't complete return map to previous state

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#2939]
### Describe the Bug with repro steps

The Undo button (or CTRL + Z) won't return the map back to the previous state. Please see video.

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/83832436/254908d1-6bf2-42da-818a-9530c066fcd5

### Version

2.42

AB#24493414

**Comment by DanielleCogs** [comment]
Not exactly the same issue, but when trying to reproduce this, I had to select the "undo" button multiple times to get the correct result, but eventually it did work.
1. Add a function and two connections
2. Delete the function
3. press undo once (no effect)
4. press undo again- expected result

**Comment by Elaina-Lee** [comment]
Trying to shift to redux-undo library for undo/redo functions as per suggestions, will see how this is impacted.
