### ISSUE TITLE
Send Email (V3) - Email Body - Dynamic Variable - DataVerse

### ISSUE THREAD

**Issue by ajestrab** [Azure/LogicAppsUX#2944]
### Describe the Bug with repro steps

1. Starting action for Logic App is monitoring a Microsoft Dataverse table for Modify, Create, Delete
2. Add SMTP: Send Email (V3) action
3. Add parameters: To, From, Subject, Body
4. Select the body area
5. Insert Dynamic Variable
6. Expand the "When a row is added, modified or del..." action
7. Can not locate/select triggerBody() or "Body" as you can in the legacy editor.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome Version 115.0.5790.75 (Official Build) beta (64-bit)

AB#24498840

**Comment by rllyy97** [comment]
Hi @ajestrab, thanks for reporting your issue, we are thinking this might be a regression caused by some of our recent feature work, I've created a Known Issue you can find here to track progress: https://github.com/Azure/LogicAppsUX/issues/2949

**Comment by rllyy97** [comment]
We have released a fix for the issue mentioned above, if you are still experiencing issues with dynamic outputs please let us know and we will reopen the issue to investigate further.
