### ISSUE TITLE
Logic app STD new designer bug SharePoiont connector

### ISSUE THREAD

**Issue by jiecao-574** [Azure/LogicAppsUX#2945]
### Describe the Bug with repro steps

Issue:
When we choose SharePoint trigger, we cannot link to any SharePoint. The list is blank.
 
- Location: eastus
- ResourceUri: /subscriptions/98aaca7e-36b7-490f-90ec-84f9aadce44e/resourceGroups/rg-OpenAI/providers/Microsoft.Web/sites/sharepoint-crawler

Please see screenshot 1.

It seems a bug about new designer. When we use old designer: [https://aka.ms/lafallback], we can see all the sites:

Please see screenshot 2.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/62946066/2fc4bef9-faa5-4a90-ac6c-7d6494807bcb)
![image](https://github.com/Azure/LogicAppsUX/assets/62946066/3913584a-dd95-49c7-ae1e-d4311da42e32)

### Browser

Chrome and Edge.

AB#24500408

**Comment by c0nfus3dk1w1d4** [comment]
I too have this issue, Browser Chrome, Edge, Safari.
I am using the new designer on the standard plan, not consumption.

**Comment by rllyy97** [comment]
Hi @jiecao-574 and @c0nfus3dk1w1d4, we are thinking this might be a regression caused by some of our recent feature work, I've created a Known Issue you can find here to track progress: https://github.com/Azure/LogicAppsUX/issues/2949

**Comment by rllyy97** [comment]
We have released a fix for the issue mentioned above, I've tested the SharePoint connector and the dynamic inputs now are loading properly!  If you are still experiencing issues let us know and we can reopen and investigate further.
