### ISSUE TITLE
Dataverse / Sharepoint dynamic data issues

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#2949]
# Known Issue
When using Preview Designer, we have received several reports of issues with the `Microsoft Dataverse (legacy)` and `Sharepoint` connectors.  The issues mainly seem to be around Dynamic Data (both inputs and outputs for actions in these connectors).
These issues will not impact any existing workflows at runtime, it only impacts the designer / editing your workflows.

## When will this be fixed?
We are currently looking into the issue to locate the root problem, but are hoping to have a hotfix rolling out in the next few days.

_**Update 7/12:**_ We've completed a full rollback while we look into the issue

**_Update 7/12 (2):_** We've fixed the issue and are rolling out a hotfix, we are aiming to have all regions hotfixed by EOD

## What can I do in the meantime?
If you need to edit your workflows that include actions/triggers from these connectors, you can use our temporary fallback method located here: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file
This will let you access the legacy designer which should work the same as it did before.

AB#24505615

**Comment by Eric-B-Wu** [comment]
we're planning a rollback to a stable designer version 2.28.4

**Comment by rllyy97** [comment]
This issue has been hotfixed in all regions!  If you are still experiencing issues with Dynamic Data please let us know in detail what you're experiencing on your existing issue, or in a new issue.

**Comment by ez1003** [comment]
I still have the same issue. The SharePoint connectors seems not working on the new designer with below error. 
`Failed to retrieve dynamic outputs. As a result, this operation's outputs might not be visible in subsequent actions. Error details: Error occurred while executing the following API parameters:`

But, when I set it to the legacy designer, it seems no error. 
It shows the error suddenly without updating anything on logic app though.
