### ISSUE TITLE
Southeast Asia Standard Logic App New Designer Window unable to create Oauth API connection for Azure Monitor Log connector.

### ISSUE THREAD

**Issue by LIYINDUO** [Azure/LogicAppsUX#2953]
### Describe the Bug with repro steps

1. Initialize a WS1 standard logic app in Southeast Asia region.
2. Create a workflow.
3. Open the worklfow and add a Recurrence trigger.
4. In the following step. Search for action list for "Azure Monitor Log" connector.
5. Select one of the actions for this connector. Select "Oauth Default" method and click on "Sign-in". 
Monitor the pop-up sign-in window won't show in this case.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
NA.
```

### Screenshots or Videos

(1) Southeast Asia "Azure Monitor Logs" connector action list in New Designer are not matching with the ones in other regions.

Southeast Asia:
![image](https://github.com/Azure/LogicAppsUX/assets/19198958/a67a6adb-738b-45d1-a867-a3622d312c4f)

Other regions:
![image](https://github.com/Azure/LogicAppsUX/assets/19198958/56e06fc6-848d-47dc-826c-3a4c11b60102)

(2) Southeast Asia "Azure Monitor Logs" connector in New Designer, if customer select to use "Oauth Default" option to create API connection. The portal will stuck at "Signing in" phase and the Pop-up window to logon the account won't show.

![image](https://github.com/Azure/LogicAppsUX/assets/19198958/643d4977-a59d-4b2f-ba74-ea5e46f20320)

Current workaround we found would be to use the fallback link and utilize the Old Designer view. This way the pop-up window would display normally.

### Browser

Chrome

AB#24513944

**Comment by hartra344** [comment]
@rllyy97  can you take a look?
