### ISSUE TITLE
In the new designer, cannot see the details of certain actions in the Standard Logic App run

### ISSUE THREAD

**Issue by PremPandeyyy** [Azure/LogicAppsUX#2963]
### Describe the Bug with repro steps 

Customer cannot see the details(Inputs and Outputs) of certain actions in his Standard logic app run in the new designer

Error :

 'Unable to initialize operation details for swagger based operation - When\_Update\_System\_is\_Triggered. Error details - Unsupported domain [@Microsoft.KeyVault](<https://github.com/Microsoft.KeyVault>)(SecretUri=https: in batch call. Only ARM endpoints are supported in batch.'

In the old designer, he can see the details fine.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/138096970/63f43d17-1599-4ff9-8edd-bffc419c8c38>)

### Browser 

Chrome

### Additional context 

*No response*

AB#24529444

**Comment by rllyy97** [comment]
Hi @PremPandeyyy, thanks for the bug report, could you provide us with which connectors and actions you're having trouble with, as well as a network trace of you loading your workflow?  You can find steps on how to retrieve the network trace in our documentation here:
https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file
Once you have the network trace `.har` file you can send it to me at rileyevans@microsoft.com

**Comment by PremPandeyyy** [comment]
Hello @rllyy97

Customer's comment on what connectors and actions having issue -

"In that specific case the connector is the Dataverse List connector. But in truth it happens with any connector that uses an API connection that is dynamically set during our infraestructure deployments (hence the error message “@Microsoft.KeyVault(SecretUri=https”)."

I will send you the network trace and console logs shortly.

**Comment by rllyy97** [comment]
@prempandeyyy Just to keep you updated, I've spent some time looking into this and I haven't been able to figure out how to reproduce this issue.  I also looked at the .har file and it's not showing any errors.  I am still working on this though and will give more info when I have it.

**Comment by rllyy97** [comment]
@PremPandeyyy, can you request the workflow definition the customer is using when seeing this error?  
Also can you get the connection json for the operation's connection?  I'm guessing they have an appsetting defined somewhere in the connection object and I want to know where it is so I can try to repro their exact configuration.
You can just email it to me instead of posting it here.

**Comment by rllyy97** [comment]
@PremPandeyyy We just merged a change that I think might fix this customer's issue.  If the key vault reference was held in an app setting reference in their connection, they should see this issue fixed after our next deployment that should be live by March 1st.
If you're still in contact with the customer about this issue, if they are still experiencing it after March 1st feel free to reopen this ticket with more details.
