### ISSUE TITLE
New Designer sometimes draws a blank page

### ISSUE THREAD

**Issue by probertdaniel** [Azure/LogicAppsUX#2966]
### Describe the Bug with repro steps

1. Go to portal
2. Select an existing workflow in a Logic App
3. Click on the run history of that workflow to see designer
4. Get a blank screen

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/11536727/e4651f4a-2274-47df-9366-44b0686f0e66)

![image](https://github.com/Azure/LogicAppsUX/assets/11536727/126b2492-4107-4122-9f37-81d9b2fea442)

### Browser

Chrome

### Additional context

This doesn't happen in previous Designer - we were able to work around this by switching to old designer.
It also only affects some workflows - we're not sure why that is.

When I look in DevTools, I can see a number of errors when the designer loads:
`fi7NwFeX8cz_.js:1 [Microsoft_Azure_EMA]  10:42:00 AM useLayout org.eclipse.elk.graph.json.JsonImportException: Referenced shape does not exist: Initialize_Checkpoint_variable - {"id":"root","children":[{"id":"manual","height":40,"width":200,"layoutOptions":{"nodeType":"OPERATION_NODE"}},{"id":"Initialize_Checkpoint_Variable","height":40,"width":200,"layoutOptions":{"nodeType":"OPERATION_NODE"}},{"id":"Initialize_Configuration_variable","height":40,"width":200,"layoutOptions":{"nodeType":"OPERATION_NODE"}},`

AB#24540448

**Comment by rllyy97** [comment]
Hi @probertdaniel, thanks for the bug report!  Could you supply your `workflow.json` file to help us reproduce your issue?  If you don't want to post it publicly here you can email it to me at rileyevans@microsoft.com
