### ISSUE TITLE
Sort function missing

### ISSUE THREAD

**Issue by mohit-jagtiani** [Azure/LogicAppsUX#2968]
### Describe the Bug with repro steps

Your documenation says sort function can be used in logic app standard but is missing in designer

Please update your documentation if cant update designer

https://learn.microsoft.com/en-us/azure/logic-apps/workflow-definition-language-functions-reference

Issues is in both portal and VSCode

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Firefox

AB#24540462

**Comment by mohit-jagtiani** [comment]
when is the update available? this is blocking us

**Comment by Eric-B-Wu** [comment]
This will be fixed in our next release which will reach production in all regions by end of next week (07/28). However, all adding the sort function does is adds intellisense to the UI to support Sort; however, you can still manually type in the sort function currently and it'll still add the expression token in. See below:
![sort](https://github.com/Azure/LogicAppsUX/assets/95886809/ac7e98f6-4ede-43d8-ac76-58f2ac043e42)

**Comment by mohit-jagtiani** [comment]
how does this sort function even work? Examples in documentation is too simple
I wish to sort this json array based on created key
{
"documents": [
      {
      "properties":{
      "id" : 4322,
      "revision" : 1,
      "created" : "2021-03-30",
      "updated" : "2021-03-30"
      },
      "fileProperties" :{
      "extension" : "PDF",
      "size" : "52173"
      },
      "customerNumber" : 1,
      "accountNumber" : null,
      "transactionReference" : "2020",
      "documentType" : "EOYReport",
      "status" : "Open"
      },
      {
      "properties":{
      "id" : 4213,
      "revision" : 1,
      "created" : "2021-03-30",
      "updated" : "2021-03-30"
      },
      "fileProperties" :{
      "extension" : "PDF",
      "size" : "52173"
      },
      "customerNumber" : 1,
      "accountNumber" : null,
      "transactionReference" : "2020",
      "documentType" : "EOYReport",
      "status" : "Open"
      } ,
      {
      "properties":{
      "id" : 3432,
      "revision" : 1,
      "created" : "2021-03-29",
      "updated" : "2021-03-29"
      },
      "fileProperties" :{
      "extension" : "PDF",
      "size" : "52175"
      },
      "customerNumber" : 1,
      "accountNumber" : null,
      "transactionReference" : "2020",
      "documentType" : "EOYReport",
      "status" : "Open"
      }]
}

None of these expression work
sort(body('Parse_JSON')?['documents'], '[properties][created]')
sort(body('Parse_JSON')?['documents'], 'properties.created')
sort(body('Parse_JSON')?['documents'], item()?['properties']?['created'])

**Comment by Eric-B-Wu** [comment]
the sort function will only take a single collection as an input. Which means you'd need to combine your two outputs into one

**Comment by mohit-jagtiani** [comment]
What do you mean by single collection? Documents in above example is single collection array. I want to sort it with created which is child of properties but it this function is failing. This requirement is quite basic in integration world

**Comment by Eric-B-Wu** [comment]
you are trying to combine two collections, one being: 1.  body('Parse_JSON')?['documents'] and 2. item()?['properties']?['created'], while the sort() input will only be a single collection. I'm not too sure what your output types are, but if they were both arrays you can use something like the union functions to change the two collections into one. *note the union functionality will remove duplicates*

**Comment by mohit-jagtiani** [comment]
That is just one of the several expressions I tried. Basic requirements is sort documents array based on grand child  key ‘created’.  ‘created’ key is child key of properties. Use the example I also sent?
