### ISSUE TITLE
Workflow validation failed when using Managed Identity in Preview Designer

### ISSUE THREAD

**Issue by kaly-d** [Azure/LogicAppsUX#2981]
### Describe the Bug with repro steps

Logic App is unable to save changes when using Managed Identity authentication

**Repro Steps:**
1. Create a Logic App Consumption with System Assigned Managed Identity enabled
2. Open the Logic App in Preview Designer
3. Search for the "Microsoft Sentinel" connector and select any trigger (ex: Microsoft Sentinel alert). I also tried with "Azure Blob" connector and selected the "When a blob is added or modified (properties only) (V2)" trigger.
4. Create a connection using Managed Identity
5. Save the changes

**Error:**
Workflow validation failed for the workflow ''. {"error":{"code":"WorkflowManagedIdentityConfigurationInvalid","message":"The workflow connection parameter 'azureblob-2' is not valid. The API connection 'azureblob' is configured to support managed identity but the connection parameter is either missing 'authentication' property in connection properties or authentication type is not 'ManagedServiceIdentity'."}}

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "Microsoft_Sentinel_alert": {
        "type": "ApiConnectionWebhook",
        "inputs": {
          "host": {
            "connection": {
              "name": "@parameters('$connections')['azuresentinel-2']['connectionId']"
            }
          },
          "body": {
            "callback_url": "@{listCallbackUrl()}"
          },
          "path": "/subscribe"
        }
      }
    },
    "actions": {},
    "outputs": {},
    "parameters": {
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {
        "azuresentinel-2": {
          "connectionId": "/subscriptions/<>/resourceGroups/<>/providers/Microsoft.Web/connections/azuresentinel-9",
          "connectionName": "azuresentinel-9",
          "id": "/subscriptions/<>/providers/Microsoft.Web/locations/eastus/managedApis/azuresentinel"
        }
      }
    }
  }
}
```

### Screenshots or Videos

**Preview Designer**

_Example with Microsoft Sentinel Trigger using Managed Identity:_ 

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/1321af5b-b247-42c4-b859-16a06b059bd9)

_Example with Azure Blob Trigger using Managed Identity:_ 

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/847675fa-ab24-4d03-8af6-4e975af47e88)

### Browser

Edge

### Additional context

This issue does not occur in "Generally Available Designer"

1. Create a Logic App Consumption with System Assigned Managed Identity enabled
2. Open the Logic App in Generally Available Designer
3. Search for the "Microsoft Sentinel" connector and select any trigger (ex: Microsoft Sentinel alert). I also tried with "Azure Blob" connector and selected the "When a blob is added or modified (properties only) (V2)" trigger.
4. Create a connection using Managed Identity
5. Save the changes

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/3344f39c-aa7f-459d-b98e-847fb0c3c132)

AB#24564583

**Comment by rllyy97** [comment]
I have found and fixed the issue, it will be fully rolled out by next Friday (July 28th)
