### ISSUE TITLE
Twitter Connection Error in Azure Logic Apps

### ISSUE THREAD

**Issue by AshokButra** [Azure/LogicAppsUX#2984]
### Describe the Bug with repro steps

I am trying to connect twitter with the credentials using consumer key and consumer secret as i do not find any other options to proceed with connection like choosing default, But struct at getting some error as i passed the credentials correctly

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![Screenshot (515)](https://github.com/Azure/LogicAppsUX/assets/118210836/d5ae0567-d01f-4526-a39e-52449d7ab3ca)

### Browser

- Browser: Chrome

AB#24573376

**Comment by hartra344** [comment]
@AshokButra unfortunately twitter recently changed their API rules such that we aren't able to provide a default connection experience anymore. For you key/secret combo, are you using one of twitters new paid API tiers? I don't think they provide a free tier anymore except in very specific circumstances.

https://developer.twitter.com/en/portal/petition/essential/basic-info
