### ISSUE TITLE
Azure Function : Getting 404 while fetching the function.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2985]
### Describe the Bug with repro steps

1.Create a VS Code Project and add Stateful Workflow, Open the Designer.
2.Add http trigger and try to add any azure function.

Expected: Able to fetch azure function app.

Actual : Getting 404.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/d0c6f43e-7895-4f1e-b716-3edd6e5537b5)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

VS Code

### Additional context

VSIX : [vscode-azurelogicapps-2.45.3.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/EVedAigWoulBgg9BfZPDHIoBNUCBuVCiLHGY_jLO2dkwWQ?e=FliEqy&xsdata=MDV8MDF8di1wcmFrdW1hckBtaWNyb3NvZnQuY29tfDliMTQ1Mjg3ZjIwZTQxOGUyYzFmMDhkYjg3Njc0YjY5fDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDF8MHw2MzgyNTI2NTAwMDczOTcwMDZ8VW5rbm93bnxUV0ZwYkdac2IzZDhleUpXSWpvaU1DNHdMakF3TURBaUxDSlFJam9pVjJsdU16SWlMQ0pCVGlJNklrMWhhV3dpTENKWFZDSTZNbjA9fDMwMDB8fHw%3d&sdata=K1hnZnF2SUhoS2VsL0x5ZjJsaVdtNWJ0VWlrcGVvbUN6K3FHa3UvcmtqYz0%3d)

2. NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc2NDI0MDc0L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.31.2.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc2NDI0MDc0L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.31.2.nupkg&data=05%7C01%7Cv-prakumar%40microsoft.com%7C9b145287f20e418e2c1f08db87674b69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638252650007397006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FFrcFlsheqK83o7U1hbq4mrv9ZV8ai1TTdqWuDRlNvg%3D&reserved=0)

3. Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-prakumar%40microsoft.com%7C9b145287f20e418e2c1f08db87674b69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638252650007397006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=589zegK3OzCwSfCxKhZTmJa0PoRz4ihy44JwzrWe59Q%3D&reserved=0)

4. Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.31.2/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.31.2_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.31.2%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.31.2_any-any.zip&data=05%7C01%7Cv-prakumar%40microsoft.com%7C9b145287f20e418e2c1f08db87674b69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638252650007397006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mRdx%2B%2F6zmFbv1SeEioEFIufczcAQbSoUP8ww4EyOGXc%3D&reserved=0)

AB#24573523

**Comment by ccastrotrejo** [comment]
Fixed with this #2974
