### ISSUE TITLE
The In App SFTP connector Upload file content action has invalid File content parameter in the new designer

### ISSUE THREAD

**Issue by kaly-d** [Azure/LogicAppsUX#2999]
### Describe the Bug with repro steps

1. In the new designer, add the "In App" SFTP action 'Upload file content'
2. Click on "Add a new parameters" and select "File content"
3. The "File content" parameter should be an empty text field to specify the content, but there is a dropdown, with the option to select a flag "SupportsLargeContent". If we click it and run, the file that gets created is a file with the word "true". Right now, user has to select "enter custom value" to add the desired file content.

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/ff3a3776-af40-4cef-94fa-df8427aaf954)
 
This issue does not occur in the previous designer

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Upload_file_content": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "filePath": "/",
            "overWriteFileIfExists": true,
            "content": "true"
          },
          "serviceProviderConfiguration": {
            "connectionName": "Sftp",
            "operationId": "uploadFileContent",
            "serviceProviderId": "/serviceProviders/Sftp"
          }
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {
    "Sftp": {
      "connection": {
        "id": "/serviceProviders/Sftp/connections/Sftp"
      },
      "connectionName": "sample-connection",
      "api": {
        "id": "/serviceProviders/Sftp"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

In New Designer - 

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/210ae3a3-e26e-4c11-873f-d9ccbc5a0f15)

In Old/Fallback Designer (expected) -

![image](https://github.com/Azure/LogicAppsUX/assets/108493323/7f03181d-be6e-4772-bfae-a045633b7465)

### Browser

Edge

AB#24595100

**Comment by Eric-B-Wu** [comment]
Expect this to be in production in 2 weeks
