### ISSUE TITLE
Font styles get reset by reopening designer view on Logic Apps Consumption

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#3008]
### Describe the Bug with repro steps

1. Create a workflow
2. Add the Send Grid connector Send email action
3. The action body is an html editor. Put some text here, first change its font to 14, and make it red
4. Save the workflow
5. Reopen it in another browser tab. you will see the font in size 14 but you do not see the red color.

Note.  T Office 365 Send email action has the same issue.

From what I observe from my repro, is that if there is a font style before the color style, the color style is ignored.

	For example, if we have this  <span style=\"font-size: 14px; color: rgb(184,49,47)\">, it will show the correct font size, but the color setting is lost.

	On the other hand it is true as well.  If we have this <span style=\"color: rgb(184,49,47; font-size: 14px)\">, then the color will show, but the font size will not show.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

Old Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#24605969

**Comment by Eric-B-Wu** [comment]
If this is only happening on old designer, I don't think we'll be taking any action on this item. @hartra344 to confirm

**Comment by hartra344** [comment]
@Eric-B-Wu can you just verify that we're serializing correctly? I'm a little confused as to why this would work with 1 connector but not the othe? Doesn't make a lot of sense

**Comment by atsugimatsu** [comment]
@Eric-B-Wu I tested with Office 365 Outlook connector, and was able to replicate the same problem. 
Also, I am using Azure Portal (preview), is it supposed to be "new designer"?

**Comment by Eric-B-Wu** [comment]
yep that is the new designer, will look into this one

**Comment by hartra344** [comment]
@atsugimatu actually that's not neccesarily new designer. Azure Portal (preview) just means that you are using the version of portal that internal MSFT employees are sent to.Can you post an image of the designer you are using?

**Comment by xuehongg** [comment]
@Eric-B-Wu @atsugimatsu @hartra344  
I have updated the repro steps.

**Comment by Eric-B-Wu** [comment]
Okay I've verified this case works in new designer:
![issue](https://github.com/Azure/LogicAppsUX/assets/95886809/dd29d2ce-5e34-4cbf-a9f4-513d65bfcfb2)
but does repro in old designer with the steps above. Because this is only happening in old designer which will be deprecated, I'm not sure if there will be any action on this item

**Comment by Eric-B-Wu** [comment]
closing this issue, as we don't have any planned action in old designer
