### ISSUE TITLE
Standard_ Workflow parameters : String type parameter is accepting the value as integer and special characters.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3011]
### Describe the Bug with repro steps

1.Create a new stateful logic app in standard, open the designer.
2.Validate if 'Parameters' command button shows
3.Add some parameters, along with String parameter.
4.**Expected:** String type parameter should not accept value as integers and special characters.
**Actual:'** String type parameter is accepting the value as integers and special characters instead of only string characters.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Compose": {
        "type": "Compose",
        "inputs": "@{parameters('a')}@{parameters('d')}@{parameters('e')}@{parameters('b')}",
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {
    "a": {
      "type": "Array",
      "value": [
        1,
        2
      ]
    },
    "d": {
      "type": "Bool",
      "value": true
    },
    "e": {
      "type": "String",
      "value": "3131212312@@#@%$@"
    }
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/f3b017fe-4073-4861-b4e8-dcd94bee2c4d)

### Browser

Edge

### Additional context

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccaeede01bc6247df730608db899fa56e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638255091053826394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XkVfWg4QCG8m1pHWR2lnWsaUSDKt3WPkUseVXK7UwVY%3D&reserved=0)
**Version:** 2.30717.1.1

AB#24614038

**Comment by hartra344** [comment]
why would string type not accept that? Those are valid string characters?

**Comment by hartra344** [comment]
Just verified, this is a completely valid value for a string.
