### ISSUE TITLE
Prevent parent node from being dragged below dependent node

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3012]
### Describe the Bug with repro steps 

1\.Create a Stateful workflow and open the Designer.

 2\.Add Http request trigger and add Dropbox and add compose.

 3\.Add Dropbox token into compose create a dependent action to compose which adds implicit for loop.

 4\.Add some more compose action after step 2.

 4\.Try to Drag the Dropbox and drop in between step 4 compose actions.

**Expected:** Drag and drop can not happen in this above case with Dropbox.

**Actual:** It is happening, we can drop the Dropbox action after its dependent card.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "For_each": {
        "type": "foreach",
        "foreach": "@body('List_files_in_folder')",
        "actions": {},
        "runAfter": {}
      },
      "Compose_1": {
        "type": "Compose",
        "inputs": "fdadfhdf",
        "runAfter": {
          "Compose": [
            "SUCCEEDED"
          ]
        }
      },
      "List_files_in_folder": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "dropbox"
            }
          },
          "method": "get",
          "path": "/datasets/default/folders/@{encodeURIComponent(encodeURIComponent('6e202211-2856-4d17-9ded-5beb8b8626b0'))}"
        },
        "runAfter": {
          "For_each": [
            "SUCCEEDED"
          ]
        },
        "metadata": {
          "6e202211-2856-4d17-9ded-5beb8b8626b0": "/"
        }
      },
      "Compose": {
        "type": "Compose",
        "inputs": "@items('For_each')?['DisplayName']",
        "runAfter": {
          "List_files_in_folder": [
            "SUCCEEDED"
          ]
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {
    "dropbox": {
      "connection": {
        "id": "/subscriptions/53ce23c6-ff79-490b-a7fb-9590fe7a414a/resourceGroups/LAStnd-v-govubilish/providers/Microsoft.Web/connections/dropbox"
      },
      "connectionName": "dropbox",
      "api": {
        "id": "/subscriptions/53ce23c6-ff79-490b-a7fb-9590fe7a414a/providers/Microsoft.Web/locations/centralus/managedApis/dropbox"
      },
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

![image](<https://github.com/Azure/LogicAppsUX/assets/113517384/7eb3f52b-33c3-4cf6-8812-69f268ffc165>)

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** [https://aka.ms/emastagiLong-flowstip1](<https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2faka.ms%2femastaging-flowstip1&data=05%7c01%7cv-govubilish%40microsoft.com%7ccaeede01bc6247df730608db899fa56e%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638255091053826394%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=XkVfWg4QCG8m1pHWR2lnWsaUSDKt3WPkUseVXK7UwVY%3D&reserved=0>)

**Version:** 2\.30717.1.1

AB#24612832

**Comment by vgouth** [comment]
Issue repro in the latest request:

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C25ee41df62d44438790c08db937727d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638265912263218130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ExdI18ub8D3V7ulDw4BDJPTB28t6zLoS8UczXvO%2FLFw%3D&reserved=0)

**Version:** 2.30731.1.4

**Comment by vgouth** [comment]
Issue repro in the latest request 

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C08587520e7324008a23608db9d720c7f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638276885447380759%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=etlI5s6BaGn77nqLx5H9zxtbj797x8RnC1ZNmMz8rjQ%3D&reserved=0)
**Version:** 2.30814.1.1

**Comment by vgouth** [comment]
Issue repro in the latest request.

1.VS Code extension - vscode-azurelogicapps-2.58.0.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc4MzA5NDU2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.36.3.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc4MzA5NDU2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.36.3.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YbUQGX1JIg4zw8dJj3tXaSQ1UvYGHZoesH4PqdR3ir0%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iTF28R1F1CAdbvqFM1XoCLdADsc09X7HLH2v22QsIpc%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.36.3/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.36.3_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.36.3%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.36.3_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HnqMsrbHp0z5Arf04tfU0ktLF%2FIFr2p48GDG0%2FVDs6s%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/669a4dae-bb08-4474-ae85-e86157a738b9)

**Comment by vgouth** [comment]
Issue repro in the latest request

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C3bbfb26744894c0b079608dba8645d1d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638288921318543127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=J9kIfve5wM5qxBlzUsk1S6g%2FK0L8EiE%2FyNacGm2Ui1Q%3D&reserved=0)
**Version:** 2.30828.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/6e9ef620-9998-4ed7-9615-5c0e5c4cb9cc)

**Comment by vgouth** [comment]
Issue repro in the latest VS code request

**1.VS Code extension** - [vscode-azurelogicapps-2.63.3.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/EZqLPbe1WcBImD7iTJtkJcUB2XzuY0npAYSBrz3t9VzjAg?e=JLTViK&xsdata=MDV8MDF8di1nb3Z1YmlsaXNoQG1pY3Jvc29mdC5jb218MzZjZGIyM2QzYWYwNDgyODgxZGIwOGRiYWY3ZDViYTN8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODI5NjcyNTI1Mzc3OTM0NnxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=cFFqeE9NdWxDYjlqelRuNTh0NDhUQUE2dDBkMmNGTWlPUFA4Z0dpWjlxZz0%3d)
**2.NuGet package:** [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc5MjQ0MDM5L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.38.2.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc5MjQ0MDM5L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.38.2.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7C98cd3820f24a4770f31208dbaf01c3ad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638296194454108856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GFclQ81vlVvol1jJN%2FOrQpXJQIh9UQsiD%2FBSqm0mwRE%3D&reserved=0)
**3.Extension Bundle (CDN URL):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7C98cd3820f24a4770f31208dbaf01c3ad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638296194454108856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t38EnCXtrvwpoMOdkKBpkUGcMssK%2B5JsTxCUiun62Ls%3D&reserved=0)
**4.Extension Bundle (Direct Download):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.38.2/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.38.2_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.38.2%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.38.2_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C98cd3820f24a4770f31208dbaf01c3ad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638296194454108856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bq4GFeOnQoVNkZazW%2BEzVnBOBTzjoLKqxfzlmBHj1D4%3D&reserved=0)

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/3f63349e-6b77-4655-a85f-99f99d68be53)

**Comment by vgouth** [comment]
Issue repro in the latest request.

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C68ab59c4b7564a18677208dbba3c2567%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638308539765819678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TtcxIdxVmlhjJxK%2BDedtWPm%2BfH3wPijHfdM5ainwuus%3D&reserved=0)
**Version:** 2.30920.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/27161c15-0045-4e1f-a1de-30b0d609074e)

**Comment by ramya894** [comment]
Issue repro in the latest request.

1.VS Code extension - ​vsix icon[ vscode-azurelogicapps-2.69.0.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/EeRUYYoqyrZPtK9ZvXk0xcQBG35zXPOj8q8xsyuAvEOuTw?e=H37L8f&xsdata=MDV8MDF8di1pdHJhbXlhQG1pY3Jvc29mdC5jb218MzgwZmFkN2FjODg1NDM5NWQ3NGMwOGRiYmViOWVjN2Z8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODMxMzQ3ODEwMjUwMjkwNHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=NDd4R0dNUWIwYkVvdS9yY0xpVkN0Q3BxZk5GbXlJcGVBTGxIelFaeEFCST0%3d)

2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgwMDY5MTEwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.41.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgwMDY5MTEwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.41.1.nupkg&data=05%7C01%7Cv-itramya%40microsoft.com%7C380fad7ac8854395d74c08dbbeb9ec7f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313478102502904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o%2BlAsxRzTDKHRvX6lTsZq96Qh5YfHtWEao6ggJ9eGuU%3D&reserved=0)

3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-itramya%40microsoft.com%7C380fad7ac8854395d74c08dbbeb9ec7f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313478102502904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YCckocAD30k%2FEga%2FU5PB5yAMuAZcNUaotN3JHs6%2Fzfc%3D&reserved=0)

4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.41.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.41.1_any-any.zip</p](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.41.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.41.1_any-any.zip%253c%2Fp&data=05%7C01%7Cv-itramya%40microsoft.com%7C380fad7ac8854395d74c08dbbeb9ec7f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313478102502904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DuzEjg555AC5xNR1FR%2FsIdifpwmDQP1G%2FYE%2FsZkICk0%3D&reserved=0)>

image

**Comment by ramya894** [comment]
Issue repro in the latest request.
URL: [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-itramya%40microsoft.com%7Ceaee76e160324b6f523208dbca66fded%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638326315949862307%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HmJHVfvrsESOH6h8Hvs6EzHGzk5YFk6Q8wEkFQO2Xaw%3D&reserved=0)
Version: 2.31010.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/7e4ca420-cb7d-45a1-a02c-36d954fc58c6)

**Comment by vgouth** [comment]
Issue repro in the latest request 

**Environmental Details:**
**Version:** 2.31023.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/2a9dfcdd-98bc-4e8c-b8fb-c9b42d6b1446)

**Comment by ramya894** [comment]
Issue repro in the latest request.

1.VS Code extension -​vsix icon[ vscode-azurelogicapps-2.81.0.vsix]
2. NuGet package:  [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgyMzkzNDQ2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.47.3.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgyMzkzNDQ2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.47.3.nupkg&data=05%7C01%7Cv-itramya%40microsoft.com%7C7afedbb8ecc8427601b408dbdef2c509%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638348906542612434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QbFROD94lcyOO4kvdV03YYjCkS745YdqD3hi105fJyE%3D&reserved=0)
4. Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-itramya%40microsoft.com%7C7afedbb8ecc8427601b408dbdef2c509%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638348906542624232%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RxUVnxeNI2wYxoYs210dvYRyp1PkHdSAeRZWwpG8vnM%3D&reserved=0)

5. Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.47.3/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.47.3_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.47.3%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.47.3_any-any.zip&data=05%7C01%7Cv-itramya%40microsoft.com%7C7afedbb8ecc8427601b408dbdef2c509%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638348906542632776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IgZmkLlEztS2CCvmqc5caAdV3W%2FyQJUGqXsVUEs4wA8%3D&reserved=0)


![newviewerror](https://github.com/Azure/LogicAppsUX/assets/52390408/fbe2444f-f6f4-4c7c-b490-dd0792f0c6f3)

**Comment by ramya894** [comment]
Issue repro in the latest request.
Environmental Details:

URL: [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-itramya%40microsoft.com%7Cc21356a9a29c456331d408dbe0f0481b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638351094916062627%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ADMBm1wE2T4PQ33XUq8x0NtVeDcsRtAtS1mPFHpetIk%3D&reserved=0) 

Version: 2.31108.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/ebc752cd-1eeb-414c-ad1c-5ad199cae07b)

**Comment by ramya894** [comment]
Issue repro in the latest VScode version.

1.VS Code extension -​2.86.0

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/aa862b50-530b-48f6-ab29-c29b391cd599)

**Comment by ramya894** [comment]
Issue repro in the latest VScode version.

1.VS Code extension -​2.99.0

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/ca1b6a2c-4deb-4264-a71f-663cada35eea)

**Comment by ramya894** [comment]
Issue repro in the latest VScode version.

1.VS Code new bundle -​1.55.0

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/d1e6e254-6a35-4929-b6dc-efa5d02ad6bc)

**Comment by ramya894** [comment]
Issue repro in the latest portal version:
Version: 2.40109.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/b3e1d069-fdc2-44dc-bb26-d513f445984d)

**Comment by ramya894** [comment]
Issue repro in the latest Standard portal version:
Version: 2.40122.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/590e20b0-5290-42d9-9379-b8d56e272d1b)

**Comment by ramya894** [comment]
Issue repro in the latest vscode version.

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/f51f3390-79fa-4e28-8dff-ab73473526db)

**Comment by ramya894** [comment]
Issue repro in the latest portal version: 2.40226.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/d9a4e18c-ee02-4eaf-b874-286b2d6d5f44)

**Comment by ramya894** [comment]
Issue repro in the latest Vscode version: 2.119.0

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/68d82a73-3ab3-450f-902e-f3a36451c7c1)

**Comment by ramya894** [comment]
Issue repro in the in the latest VSCode version: 2.125.0 

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/5246fc44-a257-4b1e-bdb8-b84079f6ac3e)

**Comment by ramya894** [comment]
Issue repro in the latest portal version: 2.40311.1.4
![image](https://github.com/Azure/LogicAppsUX/assets/52390408/f5d1e591-fdad-4838-9c1b-71e5c68f0fb9)

**Comment by ramya894** [comment]
Issue repro in the latest VScode version :v.3.0.0

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/fe5ded7c-3796-4400-9d40-951041775fbb)

**Comment by ramya894** [comment]
Issue repro in the latest portal version:  2.40408.1.2

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/266c9ce9-aa1b-494e-b980-ceabc7503ba0)

**Comment by ramya894** [comment]
Issue repro in the latest Vscode version: 1.70.23

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/06d999aa-448a-400a-97eb-b33ecdf9d3a8)

**Comment by ramya894** [comment]
Issue repro in the latest VScode version: 4.13.10

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/2ce2467e-643d-4024-8fb1-b49635d60f8a)

**Comment by ramya894** [comment]
Issue repro in the latest VScode version: 4.25.0

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/52e1dcf5-9924-45d5-89aa-52106a09d0ec)
