### ISSUE TITLE
Iterating Monitoring For loop does not updating Inputs/Outputs

### ISSUE THREAD

**Issue by CumulusService** [Azure/LogicAppsUX#3016]
### Describe the Bug with repro steps

When trying to debug a Standard Logic App that has itteration ( "For Each" Loop )- navigating with the arrows won't allow to see the failed iteration 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/121898877/42898edc-51f3-43f3-97d1-0d59e6ce6787

### Browser

Chrome

AB#24623602

**Comment by ccastrotrejo** [comment]
Hi @CumulusService. I have a couple of questions regarding this issue.
Did it used to behave different in the old designer? What was the expected behavior of this specific workflow?
Is there any chance we can get the HAR file from all the behavior? You can send it to me to ccastrotrejo@microsoft.com

**Comment by CumulusService** [comment]
Hello Carlos
Correct , in the old designer whenever I wanted to navigate through a loop iterations and watch the outputs , this could have been quite easily .
The expected behavior is that by clicking the arrows the outputs of both the outer and inner  loops will be showcased , which is not the case in the given scenario.
Please instruct me on how to obtain the HAR file and I will get it for you
Thanks
Moshe

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ccastrotrejo** [comment]
Hi @CumulusService. These are the steps to get the HAR file. Also remember that while recording the network traces do the action to catch the error. I highly suggest sending the file by email as it might have personal information. 
<img width="1452" alt="Screenshot 2023-07-26 at 10 09 36 AM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/adbcad11-21c3-46c4-a4d4-12830d08397d">

**Comment by CumulusService** [comment]
Hello
You may download the file using the link below:

[​har icon] portal.azure.com.har<https://cumulusservice.sharepoint.com/:u:/s/Microsoft-Share/EYGwXVuTZ1ZBjcE6prycs4QBSbksvQDzPweLpKsevSRZRQ?e=RbHDkF>

Moshe

With very best regards,
Moshe Nachman ,
CEO and Founder
Cumulus-Service  GmbH
Fürstenrieder Straße 8b
München, 80687
 M: +972-54-6564046 / +49-152 24436050
E: ***@***.******@***.***>
W: https://cumulus-service.com/
***@***.***

**Comment by ccastrotrejo** [comment]
@CumulusService Ok thanks for sharing it. I couldn't tell any inputs or outputs API calls in the HAR file, however I was able to repro the issue. The issue is with the update of the actions in nested loops. In the meantime a workaround you can do is to go forward and back (change the nested loop number) in the nested loop. Please let me know if this workaround helped. In the meantime, I will work on fixing this issue.

**Comment by CumulusService** [comment]
Thank you so much for checking this out  Carlos
I actually tried your workaround either , changed the number of the iteration up/down but it still didn’t work

Thanks !

With very best regards,
Moshe Nachman ,
CEO and Founder
Cumulus-Service  GmbH
Fürstenrieder Straße 8b
München, 80687
 M: +972-54-6564046 / +49-152 24436050
E: ***@***.******@***.***>
W: https://cumulus-service.com/
***@***.***

**Comment by ccastrotrejo** [comment]
@CumulusService Ok, I got it. Another issue that shouldn't have been happening is that the nested loop only has one item and the pager lets you iterate it to the second item. I will work on that fix as well. I have another workaround:

1. Update the outer loop to the number you want
2. Update the nested loop to the number you want
3. Hit the refresh icon in the upper command bar.

So sorry you have to deal with all of this, please let me know if this workaround works.

**Comment by CumulusService** [comment]
I truly appreciate the efforts and willingness , no need to apologize.
I build Integrations to SAP backends and consequently the amount of records is sometimes huge so knowing the exact position of the loop that I am after is a bit tricky.
Please bear in mind that I picked it up while the execution failed and then I couldn’t know what was the exact iteration that failed ( I simply couldn’t get to it ) – the “Condition” connector states “Next Failed” however I can’t seem to find the action that failed and take care of it and all the actions seem to have worked :

***@***.***


One more thing – The Consumption Logic App has a very useful feature that allows to navigate through recent executions from the “Runs history” left pane – a feature that is definitely missing from the Standard tier Logic App-can you please consider adding it ?

***@***.***

With very best regards,
Moshe Nachman ,
CEO and Founder
Cumulus-Service  GmbH
Fürstenrieder Straße 8b
München, 80687
 M: +972-54-6564046 / +49-152 24436050
E: ***@***.******@***.***>
W: https://cumulus-service.com/
***@***.***

**Comment by ccastrotrejo** [comment]
Hi @CumulusService I just created a PR to fix this issue. There isn't an ETA of when this is going to be in prod. 
Despite the second comment. I don't know if this is something we are planning/considering on adding since there is a run history page in the overview blade where you can take a look at the most recent runs.
Please let me know if you have any problem regarding accessing this run history page.

**Comment by CumulusService** [comment]
Hi Carlos
Thanks for the update
While there is no issue accessing the run history , you can only select one at a time , the consumption logic app allows for a navigation pane where you can see all the runs in one view

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
