### ISSUE TITLE
Managed/Shared Log Analytics Connector Fails to Create Connection

### ISSUE THREAD

**Issue by shboulatom83** [Azure/LogicAppsUX#3019]
### Describe the Bug with repro steps

1. Go to LA Standard Workflow
2. Add Log Analytics Monitor Action 'Run Query and List Results'
3. Try to create OAuth authentication,
4.  it will fail as below:
![image](https://github.com/Azure/LogicAppsUX/assets/76695917/d98d9a9a-a79e-4556-8987-0cef2a7f1610)

This only happens in LA Standard Preview Designer.

Workaround is to use [lafallback](https://aka.ms/lafallback) designer

P.S: Issue doesn't happen in LA Consumption

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/76695917/d54d8a0e-491e-49b5-b5be-3042995a57eb)

### Browser

All

AB#24627027

**Comment by rllyy97** [comment]
Thanks for reporting this @shboulatom83, we recently fixed this and it will be rolling out as part of our next release!  The fix should be fully deployed by EOD Aug 28th
