### ISSUE TITLE
Cannot save modifications in Playbooks when Preview Designer is enabled

### ISSUE THREAD

**Issue by mb-gen-e-tec** [Azure/LogicAppsUX#3026]
### Describe the Bug with repro steps

In Sentinel:
1. Automation
2. Create--> Playbook (any kind)
3. Access that playbook.
4. Try to modify or add anything in the Logic App Designer (when Preview Designer is enabled)
5. Error message (see screenshot attached).

When I go to Overview and disable it by clicking on "Disable Preview Designer", I can modify it and save my changes without error.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

<img width="257" alt="logic app error message" src="https://github.com/Azure/LogicAppsUX/assets/140453608/555b50cd-ca22-4426-a4bb-ebe730a22ebb">

### Browser

Edge

AB#24633091

**Comment by Eric-B-Wu** [comment]
Hi @mb-gen-e-tec thanks for reporting this issue, the fix for this has been merged, and will be rolling out to all stations by EOD Friday 7/28

**Comment by mb-gen-e-tec** [comment]
Hi @Eric-B-Wu,
Issue persists.

**Comment by mb-gen-e-tec** [comment]
New issue
https://github.com/Azure/LogicAppsUX/issues/3039
