### ISSUE TITLE
"Parse JSON" Action- Schema loading is slow and never loaded

### ISSUE THREAD

**Issue by hkamel** [Azure/LogicAppsUX#3029]
### Describe the Bug with repro steps

1. Open an existing/new Logic App Standard Workload
2. Add "Parse JSON" action
3. The property tab will open
4. "Schema" section will show "Loading..." and will never load
5. 
![image](https://github.com/Azure/LogicAppsUX/assets/5002831/42b98eee-f6c9-4a13-9468-453e1302dc4f)

6. When clicking on "Use sample payload to generate schema" 
7. dialog will appear "Enter or paste a sample JSON payload." However, the "loading..." statement will show and never load the text to add the sample JSON
8. 
![image](https://github.com/Azure/LogicAppsUX/assets/5002831/2c28bb20-a691-49be-9d67-72fc93554314)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Edge

AB#24639128

**Comment by Eric-B-Wu** [comment]
Hi @hkamel thanks for reporting this issue, this should be the same issue as https://github.com/Azure/LogicAppsUX/issues/2788, but to verify, could you follow the steps in [Collecting Console Errors](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-console-errors) here and paste the console logs here?

**Comment by hkamel** [comment]
Thank you @Eric-B-Wu , please find the errors attached 
[portal.azure.com-1690442956655.log](https://github.com/Azure/LogicAppsUX/files/12180558/portal.azure.com-1690442956655.log)
[portal.azure.com-1690443027783.log](https://github.com/Azure/LogicAppsUX/files/12180559/portal.azure.com-1690443027783.log)
[portal.azure.com-1690443035219.log](https://github.com/Azure/LogicAppsUX/files/12180560/portal.azure.com-1690443035219.log)
[portal.azure.com-1690443047444.log](https://github.com/Azure/LogicAppsUX/files/12180561/portal.azure.com-1690443047444.log)
[portal.azure.com-1690443056472.log](https://github.com/Azure/LogicAppsUX/files/12180563/portal.azure.com-1690443056472.log)
[portal.azure.com-1690442946284.log](https://github.com/Azure/LogicAppsUX/files/12180564/portal.azure.com-1690442946284.log)

**Comment by hkamel** [comment]
The information is already provided above per the request @Eric-B-Wu  please remove the "Needs More Info" tag

**Comment by Eric-B-Wu** [comment]
Thanks for providing these, was on vacation, apologies for the delay

**Comment by Eric-B-Wu** [comment]
Curious, is the link here: https://cdn.jsdelivr.net/ working for you? I know jsDelivr is blocked in a couple of countries, and which case you'd likely need to use a VPN or wait until we have https://github.com/Azure/LogicAppsUX/issues/2788 fixed

**Comment by hkamel** [comment]
I can confirm that the https://cdn.jsdelivr.net/ is blocked and causing the issue in the designer. I have tried from a different location the designer and the action work fine.

**Comment by Eric-B-Wu** [comment]
Great thanks for confirming, in which case I'll close this issue and move any further discussion under: https://github.com/Azure/LogicAppsUX/issues/2788 as this will load monaco from npm instead of cdn, which would help resolve your issue where cdn is blocked. The current fix conflicts with our build, but when it gets fixed I'll update that issue.
