### ISSUE TITLE
Cannot save modifications in Playbooks when Preview Designer is enabled

### ISSUE THREAD

**Issue by mb-gen-e-tec** [Azure/LogicAppsUX#3039]
### Describe the Bug with repro steps

In Sentinel:
1. Automation
2. Create--> Playbook (any kind)
3. Access that playbook.
4. Try to modify or add anything in the Logic App Designer (when Preview Designer is enabled)

Error message (see screenshot attached).

When I go to Overview and disable it by clicking on "Disable Preview Designer", I can modify it and save my changes without error.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

edge, firefox...

### Additional context

Previous issue, not fixed
https://github.com/Azure/LogicAppsUX/issues/3026

AB#24652041

**Comment by rllyy97** [comment]
@mb-gen-e-tec The fix for this issue will be fully deployed by EOD Friday 7/28.  After the 28th if you are still experiencing the issue please let us know.
