### ISSUE TITLE
New Preview Designer, clicking Parameters causes designer to fail

### ISSUE THREAD

**Issue by tjohnson1010** [Azure/LogicAppsUX#3043]
### Describe the Bug with repro steps

With the new Preview Designer, clicking Parameters causes designer to fail with, "The renderComponentIntoRoot component encountered an error while loading."  This occurs in all my Logic Apps that use Parameters.

**This work as expected with Legacy Designer.**

Attached is log from Console with errors.
No errors on Network tab.

Session ID: 0d1ba0726d5c4b5da5916b4355069ca8
Version: 2.30701.1.2

Steps to reproduce:
1) Edit Any Logic App with Parameters
2) If not in new Preview Designer, click "Try Preview Designer".
3) Click [@] Parameter link

Error Summary:
{  "shellProps": {    "sessionId": "0d1ba0726d5c4b5da5916b4355069ca8",    "extName": "Microsoft_Azure_EMA",    "contentName": "DesignerEditorConsumption.ReactView"  },  "error": {    "message": "The renderComponentIntoRoot component encountered an error while loading.",    "metadata": {      "area": "renderComponentIntoRoot"    },    "error": {      "data": {        "message": "The renderComponentIntoRoot component encountered an error while loading.",        "metadata": {          "area": "renderComponentIntoRoot"        },        "capturedErrors": [          {            "message": "Error caught in error boundary",            "metadata": {              "area": "renderComponentIntoRoot",              "error": {                "stack": "Core.AssertionException: Host Service needs to be initialized before using\n    at Vd (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:3466972)\n    at Z7 (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4928250)\n    at sn (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:43429)\n    at ac (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:111135)\n    at Fr (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:77642)\n    at Lr (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:77570)\n    at jr (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:77433)\n    at Pr (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:74428)\n    at https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:30172\n    at unstable_runWithPriority (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:52:7430)\n    at St (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:29949)\n    at Tt (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:30117)\n    at _t (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:30052)\n    at ul (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:115718)\n    at pe (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:62:15416)",                "message": "Host Service needs to be initialized before using",                "name": "Core.AssertionException",                "code": "ServiceNotRegistered"              },              "errorInfo": {                "componentStack": "\n    at Z7 (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4927820)\n    at div\n    at div\n    at div\n    at div\n    at https://portal.azure.com/Content/Dynamic/GMRrvtwk1Sw4.js:2:464\n    at div\n    at div\n    at https://portal.azure.com/Content/Dynamic/KWhvNSyimoUA.js:1:576\n    at div\n    at t.FocusRectsProvider (https://portal.azure.com/Content/Dynamic/Mu_HHoibPBz6.js:19:275)\n    at https://portal.azure.com/Content/Dynamic/UVrkVk9gwhET.js:1:481\n    at https://portal.azure.com/Content/Dynamic/Mu_HHoibPBz6.js:85:438\n    at t.FocusRectsProvider (https://portal.azure.com/Content/Dynamic/Mu_HHoibPBz6.js:19:275)\n    at span\n    at https://portal.azure.com/Content/Dynamic/UVrkVk9gwhET.js:8:511\n    at https://portal.azure.com/Content/Dynamic/Mu_HHoibPBz6.js:85:438\n    at t (https://portal.azure.com/Content/Dynamic/SsPhcSHnUwtp.js:2:689)\n    at https://portal.azure.com/Content/Dynamic/Mu_HHoibPBz6.js:85:438\n    at X7 (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4928367)\n    at zH (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4463346)\n    at div\n    at https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4463804\n    at UH (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4459928)\n    at div\n    at https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4538730\n    at AZ (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4539282)\n    at iee (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4931319)\n    at div\n    at G8 (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4786243)\n    at Y8 (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4786488)\n    at Hi (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:2859332)\n    at t (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:2858417)\n    at Vi (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:2859765)\n    at c (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:2442742)\n    at GZ (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4568339)\n    at div\n    at div\n    at Wk (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4161998)\n    at https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4178482\n    at div\n    at t.FocusRectsProvider (https://portal.azure.com/Content/Dynamic/Mu_HHoibPBz6.js:19:275)\n    at https://portal.azure.com/Content/Dynamic/PeTg_z6JPXbU.js:9:441\n    at W8 (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4785125)\n    at R (https://reactblade.portal.azure.net//Content/Dynamic/3KsPtNwXSeTh.js:65:12539)\n    at $8 (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4785466)\n    at div\n    at vte (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:4965203)\n    at c (https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/szE-eA8D_rnk.js:3:2442742)\n    at Ite\n    at n (https://portal.azure.com/Content/Dynamic/8wIofAdDvDp7.js:12:1447)\n    at Ite\n    at div\n    at t.FocusRectsProvider (https://portal.azure.com/Content/Dynamic/Mu_HHoibPBz6.js:19:275)\n    at https://portal.azure.com/Content/Dynamic/UVrkVk9gwhET.js:1:481\n    at https://portal.azure.com/Content/Dynamic/Mu_HHoibPBz6.js:85:438\n    at t (https://portal.azure.com/Content/Dynamic/Mu_HHoibPBz6.js:54:434)\n    at div\n    at t.FocusRectsProvider (https://portal.azure.com/Content/Dynamic/Mu_HHoibPBz6.js:19:275)\n    at https://portal.azure.com/Content/Dynamic/PeTg_z6JPXbU.js:9:441\n    at r.ThemedFabric (https://portal.azure.com/Content/Dynamic/9I9MOrGQTp9b.js:6:1341)"              }            }          }        ]      }    },    "code": null  }}

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "When_a_file_is_added_or_modified": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "name": "@parameters('$connections')['sftpwithssh_1']['connectionId']"
            }
          },
          "method": "get",
          "path": "/datasets/default/triggers/onupdatedfile",
          "queries": {
            "folderId": "L0luYm94",
            "includeFileContent": true,
            "inferContentType": true,
            "queryParametersSingleEncoded": true
          }
        },
        "recurrence": {
          "frequency": "Minute",
          "interval": 5
        },
        "metadata": {
          "L091dGJvdW5k": "/Outbound",
          "L0luYm94": "/Inbox",
          "L2hhbmFjdXJlL291dA==": "/hanacure/out",
          "L2hhcnJ5cy90ZXN0b3V0": "/harrys/testout",
          "L2hhcnJ5cy9vdXQ=": "/harrys/out",
          "L2luYm91bmQ=": "/inbound"
        }
      }
    },
    "actions": {
      "Exception": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "name": "@parameters('$connections')['office365']['connectionId']"
            }
          },
          "method": "post",
          "body": {
            "To": "@{parameters('emailTo')}",
            "Subject": "Test Exception occurred in @{parameters('CustomerName')} EDI Inbound for file : @{base64ToString(triggerOutputs()['headers']['x-ms-file-name-encoded'])}",
            "Body": "Error At: @{last(body('Filter_Error_Messages'))?['name']}\n\nRun : @{workflow().run.name}\n\n@{if(equals(first(string(coalesce(last(body('Filter_Error_Messages'))?['outputs']?['body'],'{}'))),'{'),coalesce(last(body('Filter_Error_Messages'))?['outputs']?['body']?['error']?['message'],last(body('Filter_Error_Messages'))?['outputs']?['body']?['errorMessage'],last(body('Filter_Error_Messages'))?['error']?['message'],last(body('Filter_Error_Messages'))?['outputs']?['body'],last(body('Filter_Error_Messages'))?['error']),last(body('Filter_Error_Messages'))?['outputs']?['body'])}",
            "Importance": "High"
          },
          "path": "/Mail"
        },
        "runAfter": {
          "Filter_Error_Messages": [
            "Succeeded"
          ]
        }
      },
      "Filter_Error_Messages": {
        "type": "Query",
        "inputs": {
          "from": "@result('Scope')",
          "where": "@equals(item()['status'], 'Failed')"
        },
        "runAfter": {
          "Scope": [
            "Failed"
          ]
        }
      },
      "Scope": {
        "type": "Scope",
        "actions": {
          "Create_SPO_File": {
            "type": "ApiConnection",
            "inputs": {
              "host": {
                "connection": {
                  "name": "@parameters('$connections')['sharepointonline_1']['connectionId']"
                }
              },
              "method": "post",
              "body": "@triggerBody()",
              "path": "/datasets/@{encodeURIComponent(encodeURIComponent('https://legacyhld.sharepoint.com/sites/Multi-ClientEDI'))}/files",
              "queries": {
                "folderPath": "/Shared Documents/TestReceived/Global Amici",
                "name": "GA-@{base64ToString(triggerOutputs()['headers']['x-ms-file-name-encoded'])}.txt",
                "queryParametersSingleEncoded": true
              }
            },
            "runtimeConfiguration": {
              "contentTransfer": {
                "transferMode": "Chunked"
              }
            }
          },
          "Delete_file": {
            "type": "ApiConnection",
            "inputs": {
              "host": {
                "connection": {
                  "name": "@parameters('$connections')['sftpwithssh_1']['connectionId']"
                }
              },
              "method": "delete",
              "headers": {
                "SkipDeleteIfFileNotFoundOnServer": true
              },
              "path": "/datasets/default/files/@{encodeURIComponent(encodeURIComponent(base64ToString(triggerOutputs()['headers']['x-ms-file-path-encoded'])))}"
            },
            "runAfter": {
              "Inbound_X12": [
                "Succeeded"
              ]
            }
          },
          "Inbound_X12": {
            "type": "Workflow",
            "inputs": {
              "host": {
                "workflow": {
                  "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Inbound_X12"
                },
                "triggerName": "manual"
              }
            },
            "runAfter": {
              "Create_SPO_File": [
                "Succeeded"
              ]
            }
          }
        },
        "runAfter": {}
      }
    },
    "outputs": {},
    "parameters": {
      "CustomerName": {
        "defaultValue": "Global Amici",
        "type": "String"
      },
      "emailTo": {
        "defaultValue": "filemon@legacyscs.com",
        "type": "String"
      },
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {
        "sftpwithssh_1": {
          "connectionId": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Web/connections/sftpwithssh",
          "connectionName": "sftpwithssh",
          "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/providers/Microsoft.Web/locations/westcentralus/managedApis/sftpwithssh"
        },
        "office365": {
          "connectionId": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Web/connections/office365",
          "connectionName": "office365",
          "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/providers/Microsoft.Web/locations/westcentralus/managedApis/office365"
        },
        "sharepointonline_1": {
          "connectionId": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Web/connections/sharepointonline",
          "connectionName": "sharepointonline",
          "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/providers/Microsoft.Web/locations/westcentralus/managedApis/sharepointonline"
        }
      }
    }
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/4419979/d66fd52e-cfaa-493a-b61c-d4c59e571c66)

### Browser

Edge Version 115.0.1901.183 (Official build) (64-bit)

### Additional context

[portal.azure.com-1690401862123.log](https://github.com/Azure/LogicAppsUX/files/12176874/portal.azure.com-1690401862123.log)

AB#24655454

**Comment by rllyy97** [comment]
We've merged a fix for this issue, it should be finished deploying on Aug 11th, in the meantime non-preview designer should still work as expected

**Comment by rllyy97** [comment]
We are actually doing a hotfix early next week so I went ahead and included this as well, it should be working by EOD Monday as long as the hotfix goes through okay
