### ISSUE TITLE
TestMap - Test button is disabled until you close and come back to test. 

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#3046]
### Describe the Bug with repro steps

Invoke test, the test UX comes up. The test button is disabled since there is no instance. Paste an instance message in the provided space. Test is still disabled. Cloes the test UX and return to it. Test button is not enabled.

### Version

V 2.53.0

AB#24657235

**Comment by Elaina-Lee** [comment]
Fixed with https://github.com/Azure/LogicAppsUX/pull/3337
