### ISSUE TITLE
"Convert HTML to PDF" action in "PDF4me" connector does not get added in new LA standard designer.

### ISSUE THREAD

**Issue by JaganMSFTGitHub** [Azure/LogicAppsUX#3055]
### Describe the Bug with repro steps

1. Open a LA standard workflow.
2. Search for connector "PDF4me".
3. Select action "Convert HTML to PDF".
4. It will keep on loading forever.
5. Next, use fallback URL (https://aka.ms/lafallback) to open LA standard workflow in old designer.
6. Here we are able to add the action without any issues.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![Screenshot 2023-07-28 165207](https://github.com/Azure/LogicAppsUX/assets/140811009/2e3d3c1d-6626-4689-bf8d-5dfa4bb13c0c)

### Browser

[PDF4meConsole.log](https://github.com/Azure/LogicAppsUX/files/12193921/PDF4meConsole.log)

AB#24673059

**Comment by JaganMSFTGitHub** [comment]
Hello Riley, 

Could you please share an update on this. Any ETA on fix?

**Comment by rllyy97** [comment]
Hi @JaganMSFTGitHub, I'm currently looking into this issue and hoping to complete a fix today.  If all goes well, the ETA on the change being fully deployed should be  August 11th.
