### ISSUE TITLE
Custom Values not available in some dropdowns in Date Time Functions

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#3056]
### Describe the Bug with repro steps 

Please see internal OneNote for the examples, but we have a handful of functions in the "Equal #####" family that don't allow for a custom value in the first dropdown but do in the second dropdown.

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/83832436/5cff9014-4ae0-4929-bae6-734c92431a61>)

### Version 

2\.53.0

### Additional context 

*No response*

AB#24678716

**Comment by DanielleCogs** [comment]
@kewear we are unable to reproduce this one. I did test and it seems like 'custom input' does not show up in the dropdown until you start typing. Unsure if that is a regression or by design. Mind re-checking this one for us?
