### ISSUE TITLE
Function - Custom Value - Can't back out

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#3058]
### Describe the Bug with repro steps

If you are in a function and you select a custom value but then change your mind and try to 'back out' you can't do it. You can click on the 'X' but nothing else happens.

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/83832436/7d3ead3d-65ba-471b-acf1-71c6ef84ce5d

### Version

2.53

AB#24678808

**Comment by DanielleCogs** [comment]
This was fixed in this PR https://github.com/Azure/LogicAppsUX/pull/3049 as of today the fix is working in 2.55.4, but the extension in marketplace has not been updated
