### ISSUE TITLE
Function caching issue - dangling references

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#3059]
### Describe the Bug with repro steps

We have seen situations where a function is deleted but still shows up in Global View. Please see video on GitHub

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/83832436/2e981a75-03f9-4cb9-80ed-2abcefc57e13

### Version

2.53.0

AB#24678863

**Comment by DanielleCogs** [comment]
Unable to reproduce. As this is an older issue I'm assuming that it has been fixed since.
