### ISSUE TITLE
Update unwanted filed when updating a sharepoint item

### ISSUE THREAD

**Issue by bashiransari** [Azure/LogicAppsUX#3060]
### Describe the Bug with repro steps

Add update sharepoint item action then I removed the default fields, they are removed from the UI but they are still in code with default values.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

I removed the "MaterialCostEstimate", "MaterialCostEstimate" and "ProductsOrdered" fields but they are still in code and it results in updating these fields to the wrong values which I didn't want to update in the first place.

<img width="473" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/11271144/a16a7bfe-a76e-42e8-ab0b-c71fc097d485">

<img width="450" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/11271144/1391b034-f842-47fa-905f-6cff999d5bc3">

### Browser

Chrome

AB#24679725

**Comment by Eric-B-Wu** [comment]
Hi @bashiransari thanks for reporting this issue, will take a look to see why this is happening
