### ISSUE TITLE
Logic App with many Switch Cases

### ISSUE THREAD

**Issue by tjohnson1010** [Azure/LogicAppsUX#3064]
### Describe the Bug with repro steps

When displaying the cases in Switch, if there are several of them, it goes horizontally off the screen.  There is no scroll bar allowing us to view/edit the right most cases.

Best solution, is to default all Cases as minimized and list them vertically.   Right now, first case expands and list them vertically.  Vertical scroll is easier than horizontal.

Easy solution, add horizontal scroll bar.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "manual": {
        "type": "Request",
        "kind": "Http",
        "inputs": {
          "schema": {
            "properties": {
              "CustomerFolder": {
                "type": "string"
              },
              "Data": {
                "type": "string"
              },
              "Filename": {
                "type": "string"
              },
              "IsProduction": {
                "type": "boolean"
              },
              "Origin": {
                "type": "string"
              }
            },
            "type": "object"
          }
        }
      }
    },
    "actions": {
      "Exception": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "name": "@parameters('$connections')['office365']['connectionId']"
            }
          },
          "method": "post",
          "body": {
            "To": "@parameters('emailTo')",
            "Subject": "@{if(equals(triggerBody()?['IsProduction'],true),'','Test ')}Exception occurred in Multi-Client Outbound Customer : @{triggerBody()?['Filename']}",
            "Body": "<p>Error At : @{last(body('Filter_Error_Messages'))?['name']}<br>\n<br>\nFilename : @{triggerBody()?['Filename']}<br>\n<br>\nOrigin: @{triggerBody()?['Origin']}<br>\n<br>\nRun : @{workflow().run.name}<br>\n<br>\n@{if(equals(first(string(coalesce(last(body('Filter_Error_Messages'))?['outputs']?['body'],'{}'))),'{'),coalesce(last(body('Filter_Error_Messages'))?['outputs']?['body']?['error']?['message'],last(body('Filter_Error_Messages'))?['outputs']?['body']?['errorMessage'],last(body('Filter_Error_Messages'))?['error']?['message'],last(body('Filter_Error_Messages'))?['outputs']?['body'],last(body('Filter_Error_Messages'))?['error']),last(body('Filter_Error_Messages'))?['outputs']?['body'])}</p>",
            "Importance": "High"
          },
          "path": "/v2/Mail"
        },
        "runAfter": {
          "Filter_Error_Messages": [
            "Succeeded"
          ]
        }
      },
      "Filter_Error_Messages": {
        "type": "Query",
        "inputs": {
          "from": "@result('Scope')",
          "where": "@equals(item()['status'], 'Failed')"
        },
        "runAfter": {
          "Scope": [
            "Failed"
          ]
        }
      },
      "Initialize_Agreement": {
        "type": "InitializeVariable",
        "inputs": {
          "variables": [
            {
              "name": "Agreement",
              "type": "string",
              "value": "XX"
            }
          ]
        },
        "runAfter": {}
      },
      "Initialize_FileType": {
        "type": "InitializeVariable",
        "inputs": {
          "variables": [
            {
              "name": "FileType",
              "type": "string",
              "value": "@{last(split(triggerBody()?['Filename'],'.'))}"
            }
          ]
        },
        "runAfter": {
          "Initialize_Agreement": [
            "Succeeded"
          ]
        }
      },
      "Response_Error": {
        "type": "Response",
        "kind": "Http",
        "inputs": {
          "statusCode": 200,
          "body": "Error Occurred: @{workflow()}"
        },
        "runAfter": {
          "Exception": [
            "Succeeded"
          ]
        }
      },
      "Scope": {
        "type": "Scope",
        "actions": {
          "Process_File": {
            "type": "Switch",
            "expression": "@triggerBody()?['CustomerFolder']",
            "default": {
              "actions": {
                "Send_an_email_(V2)": {
                  "type": "ApiConnection",
                  "inputs": {
                    "host": {
                      "connection": {
                        "name": "@parameters('$connections')['office365']['connectionId']"
                      }
                    },
                    "method": "post",
                    "body": {
                      "To": "@parameters('emailTo')",
                      "Subject": "Unknown Folder in Multi-Client Outbound Customer",
                      "Body": "<p>Folder: @{triggerBody()?['CustomerFolder']}</p>",
                      "Importance": "High"
                    },
                    "path": "/v2/Mail"
                  }
                }
              }
            },
            "cases": {
              "HE": {
                "actions": {
                  "File_Type_-_HE": {
                    "type": "Switch",
                    "expression": "@last(split(triggerBody()?['Filename'],'.'))",
                    "default": {
                      "actions": {}
                    },
                    "cases": {
                      "IA": {
                        "actions": {
                          "Outbound_Flat_-_HE_-_IA": {
                            "type": "Workflow",
                            "inputs": {
                              "host": {
                                "workflow": {
                                  "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound_Flat"
                                },
                                "triggerName": "manual"
                              },
                              "body": {
                                "CustomerCode": "HE",
                                "CustomerName": "H&E",
                                "Data": "@triggerBody()?['Data']",
                                "Filename": "@triggerBody()?['Filename']",
                                "IsProduction": "@triggerBody()?['IsProduction']",
                                "Origin": "@triggerBody()?['Origin']",
                                "Process": "InvAdj"
                              }
                            }
                          }
                        },
                        "case": "ituxml"
                      },
                      "RC": {
                        "actions": {
                          "Outbound_RC": {
                            "type": "Workflow",
                            "inputs": {
                              "host": {
                                "workflow": {
                                  "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound_RC"
                                },
                                "triggerName": "manual"
                              },
                              "body": {
                                "CustomerCode": "HE",
                                "CustomerName": "H&E",
                                "Data": "@triggerBody()?['Data']",
                                "Filename": "@triggerBody()?['Filename']",
                                "IsProduction": "@triggerBody()?['IsProduction']",
                                "Origin": "@triggerBody()?['Origin']"
                              }
                            }
                          }
                        },
                        "case": "rcuxml"
                      },
                      "SC": {
                        "actions": {
                          "Outbound_Flat_-_HE_-_SC": {
                            "type": "Workflow",
                            "inputs": {
                              "host": {
                                "workflow": {
                                  "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound_Flat"
                                },
                                "triggerName": "manual"
                              },
                              "body": {
                                "CustomerCode": "HE",
                                "CustomerName": "H&E",
                                "Data": "@triggerBody()?['Data']",
                                "Filename": "@triggerBody()?['Filename']",
                                "IsProduction": "@triggerBody()?['IsProduction']",
                                "Origin": "@triggerBody()?['Origin']",
                                "Process": "ShipConfirm"
                              }
                            }
                          }
                        },
                        "case": "shuxml"
                      }
                    }
                  }
                },
                "case": "HE"
              },
              "Harry's": {
                "actions": {
                  "File_Type_-_Harry's": {
                    "type": "Switch",
                    "expression": "@variables('FileType')",
                    "default": {
                      "actions": {
                        "Set_Agreement_-_All_Others": {
                          "type": "SetVariable",
                          "inputs": {
                            "name": "Agreement",
                            "value": "Harrys_Amazon"
                          }
                        }
                      }
                    },
                    "cases": {
                      "RC-2": {
                        "actions": {
                          "Send_RC": {
                            "type": "If",
                            "expression": {
                              "and": [
                                {
                                  "equals": [
                                    "@length(xpath(xml(triggerBody()?['Data']),parameters('xUserDef3')))",
                                    1
                                  ]
                                }
                              ]
                            },
                            "actions": {
                              "Set_Agreement_-_RC": {
                                "type": "SetVariable",
                                "inputs": {
                                  "name": "Agreement",
                                  "value": "Harrys"
                                }
                              }
                            },
                            "else": {
                              "actions": {}
                            }
                          }
                        },
                        "case": "rcuxml"
                      },
                      "SC-2": {
                        "actions": {
                          "Is_DTC": {
                            "type": "If",
                            "expression": {
                              "and": [
                                {
                                  "equals": [
                                    "@endsWith(triggerBody()?['Filename'],'.Parcel.shuxml')",
                                    "@true"
                                  ]
                                }
                              ]
                            },
                            "actions": {
                              "Set_Agreement_-_SC_-_DTC": {
                                "type": "SetVariable",
                                "inputs": {
                                  "name": "Agreement",
                                  "value": "Harrys_DTC"
                                }
                              }
                            },
                            "else": {
                              "actions": {
                                "Set_Agreement_-_SC_-_Amazon": {
                                  "type": "SetVariable",
                                  "inputs": {
                                    "name": "Agreement",
                                    "value": "Harrys_Amazon"
                                  }
                                }
                              }
                            }
                          }
                        },
                        "case": "shuxml"
                      }
                    }
                  },
                  "OK_2_Send": {
                    "type": "If",
                    "expression": {
                      "and": [
                        {
                          "not": {
                            "equals": [
                              "@variables('Agreement')",
                              "XX"
                            ]
                          }
                        }
                      ]
                    },
                    "actions": {
                      "Outbound_X12_-_Harry's": {
                        "type": "Workflow",
                        "inputs": {
                          "host": {
                            "workflow": {
                              "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound_X12"
                            },
                            "triggerName": "manual"
                          },
                          "body": {
                            "Aggrement": "@variables('Agreement')",
                            "CustomerCode": "HR@{if(endsWith(variables('Agreement'),'DTC'),'D','')}",
                            "CustomerName": "Harry's",
                            "Data": "@triggerBody()?['Data']",
                            "Filename": "@triggerBody()?['Filename']",
                            "IsProduction": "@triggerBody()?['IsProduction']",
                            "Origin": "@triggerBody()?['Origin']"
                          }
                        }
                      }
                    },
                    "else": {
                      "actions": {}
                    },
                    "runAfter": {
                      "File_Type_-_Harry's": [
                        "Succeeded"
                      ]
                    }
                  }
                },
                "case": "Harrys"
              },
              "Inkey": {
                "actions": {
                  "Outbound_Flat_-_Inkey": {
                    "type": "Workflow",
                    "inputs": {
                      "host": {
                        "workflow": {
                          "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound_Flat"
                        },
                        "triggerName": "manual"
                      },
                      "body": {
                        "CustomerCode": "IK",
                        "CustomerName": "Inkey",
                        "Data": "@triggerBody()?['Data']",
                        "Filename": "@triggerBody()?['Filename']",
                        "IsProduction": "@triggerBody()?['IsProduction']",
                        "Origin": "@triggerBody()?['Origin']",
                        "Process": "ShipConfirm"
                      }
                    }
                  }
                },
                "case": "Inkey"
              },
              "Maharam": {
                "actions": {
                  "Outbound_X12_-_Maharam": {
                    "type": "Workflow",
                    "inputs": {
                      "host": {
                        "workflow": {
                          "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound_X12"
                        },
                        "triggerName": "manual"
                      },
                      "body": {
                        "Aggrement": "Maharam",
                        "CustomerCode": "MA",
                        "CustomerName": "Maharam",
                        "Data": "@triggerBody()?['Data']",
                        "Filename": "@triggerBody()?['Filename']",
                        "IsProduction": "@triggerBody()?['IsProduction']",
                        "Origin": "@triggerBody()?['Origin']"
                      }
                    }
                  }
                },
                "case": "Maharam"
              },
              "SPS": {
                "actions": {
                  "SPS_Outbound": {
                    "type": "Workflow",
                    "inputs": {
                      "host": {
                        "workflow": {
                          "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/SPS_Outbound"
                        },
                        "triggerName": "manual"
                      },
                      "body": {
                        "Data": "@triggerBody()?['Data']",
                        "Filename": "@triggerBody()?['Filename']",
                        "IsProduction": "@triggerBody()?['IsProduction']",
                        "Map": "SPS_ShipConfirm",
                        "Origin": "@triggerBody()?['Origin']"
                      }
                    }
                  }
                },
                "case": "SPS"
              },
              "Shopify": {
                "actions": {
                  "Shopify_Send2": {
                    "type": "Workflow",
                    "inputs": {
                      "host": {
                        "workflow": {
                          "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Shopify_Send2"
                        },
                        "triggerName": "manual"
                      },
                      "body": {
                        "Data": "@triggerBody()?['Data']",
                        "Filename": "@triggerBody()?['Filename']",
                        "IsProduction": "@triggerBody()?['IsProduction']",
                        "Origin": "@triggerBody()?['Origin']"
                      }
                    }
                  }
                },
                "case": "Shopify"
              },
              "Yamaha": {
                "actions": {
                  "Outbound_X12": {
                    "type": "Workflow",
                    "inputs": {
                      "host": {
                        "workflow": {
                          "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound_X12"
                        },
                        "triggerName": "manual"
                      },
                      "body": {
                        "Aggrement": "Yamaha",
                        "CustomerCode": "YA",
                        "CustomerName": "Yamaha",
                        "Data": "@triggerBody()?['Data']",
                        "Filename": "@triggerBody()?['Filename']",
                        "IsProduction": "@triggerBody()?['IsProduction']",
                        "Origin": "@triggerBody()?['Origin']"
                      }
                    }
                  }
                },
                "case": "Yamaha"
              }
            }
          },
          "Response_OK": {
            "type": "Response",
            "kind": "Http",
            "inputs": {
              "statusCode": 200
            },
            "runAfter": {
              "Process_File": [
                "Succeeded"
              ]
            }
          }
        },
        "runAfter": {
          "Initialize_FileType": [
            "Succeeded"
          ]
        }
      }
    },
    "outputs": {},
    "parameters": {
      "emailTo": {
        "defaultValue": "Multi-ClientAlerts@legacyscs.com",
        "type": "String"
      },
      "xCompany": {
        "defaultValue": "//*[local-name()=\"Shipment\"]/*[local-name()=\"Customer\"]/*[local-name()=\"Company\"]/text()",
        "type": "String"
      },
      "xUserDef3": {
        "defaultValue": "//*[local-name()='Receipt']/*[local-name()='UserDef3']/text()",
        "type": "String"
      },
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {
        "office365": {
          "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/providers/Microsoft.Web/locations/westcentralus/managedApis/office365",
          "connectionId": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Web/connections/office365",
          "connectionName": "office365"
        }
      }
    }
  }
}

### Browser

Edge

AB#24701929

**Comment by hartra344** [comment]
Do you have some screenshots of what you are saying? I'm a little confused. If you're working in the new designer, it's a fully panable canvas, just click and drag. If you're working in the old designer, then this would be a design change that is unlikely to happen there.

**Comment by tjohnson1010** [comment]
This was for the new designer. The panable canvas was the part I didn’t know about.    Thank you.

As far as having the case blocks being expanded vs. minimized, having the minimized would be easier to deal with especially there a lot of them with large amounts of code in them.  Being vertical vs horizontal, this is only valuable if you start minimized.  Then the stack nicely and you can scroll quickly to the case you need vs panning right/left to get to the one you need.   FYI:  the old designer would stack vertically if the screen width was smaller (I think 800px or less); otherwise, it would display cases horizontally.

Just as an example of old designer Switches…

Vertically:
***@***.***

Horizontally:
***@***.***



Have a good day,

Thomas Johnson
Director of IT Applications

***@***.******@***.***>  |  www.legacyscs.com<https://legacyscs.com/>

distribution | fulfillment | transportation

This confidential e-mail and any attachments are for the exclusive use of the addressee(s). If you receive this in error, please delete all copies and notify the sender. Any views expressed are those of the sender, unless stated otherwise.

**Comment by hartra344** [comment]
Since you sent them in the email response GitHub didn't post the images. Feel free to send them to me at travisharris@microsoft.com. In the meantime, I'm going to close the issue since this is a request rather than a bug. But I will continue tracking it internally and see if there's something we can do to make this better.
