### ISSUE TITLE
Cannot open workflow designer in VS Code 1.80.2

### ISSUE THREAD

**Issue by novenera** [Azure/LogicAppsUX#3068]
### Describe the Bug with repro steps

1. Select Create new Logic App workspace.
![image](https://github.com/Azure/LogicAppsUX/assets/16081468/55d8f6c7-b6fc-454e-8119-94bedfab1a6b)

2. Follow the prompts which would create the following workspace with a folder for Function App project and another for Logic App project. 
![image](https://github.com/Azure/LogicAppsUX/assets/16081468/28dc0c8b-8f3f-43c0-b844-a6f6445fef2b)

3. Right-click workflow.json and choose Open Designer
![image](https://github.com/Azure/LogicAppsUX/assets/16081468/a16e5c81-1b6c-4c07-aaab-3f1966dac1c7)

4.  Workflow designer does not start.
![image](https://github.com/Azure/LogicAppsUX/assets/16081468/8bd85209-b0fa-4131-82da-1d110357af38)

5. Logs returned as follows:
![image](https://github.com/Azure/LogicAppsUX/assets/16081468/e1891f5a-9a00-49eb-af14-453febed1f87)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Call_a_local_function_in_this_logic_app": {
        "type": "InvokeFunction",
        "inputs": {
          "functionName": "TestFunction",
          "parameters": {
            "zipCode": 85396,
            "temperatureScale": "Celcius"
          }
        },
        "runAfter": {}
      },
      "Response": {
        "type": "Response",
        "kind": "http",
        "inputs": {
          "statusCode": 200,
          "body": "@body('Call_a_local_function_in_this_logic_app')"
        },
        "runAfter": {
          "Call_a_local_function_in_this_logic_app": [
            "Succeeded"
          ]
        }
      }
    },
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http",
        "inputs": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {}
  },
  "kind": "Stateless"
}
```

### Browser

Debugging from VS Code 1.80.2

### Additional context
Logic Apps (Standard) VS Code extension v2.45.4
Azurite v3.25.0
Azure Functions v1.12.2
Azure Function Core Tools Version 4.0.4865
Function Runtime Version: 4.12.2.19454
.NET 7.0.306

AB#24719974

**Comment by Eric-B-Wu** [comment]
@novenera thanks for reporting this, to confirm, is this happening on vscode Logic Apps version 1.80.2? cause it may just be that version that is not working. I'd recommend seeing if updating to latest version 2.45.4 fixes your issue. If not we can look into it further

**Comment by ccastrotrejo** [comment]
Hi @novenera, did you try to create a normal/simple logic apps project or did you indeed want a workspace with a functions and logic app projects. Just want to confirm if we should change the wording of the second one/

**Comment by novenera** [comment]
> @novenera thanks for reporting this, to confirm, is this happening on vscode Logic Apps version 1.80.2? cause it may just be that version that is not working. I'd recommend seeing if updating to latest version 2.45.4 fixes your issue. If not we can look into it further

Hi @Eric-B-Wu - I am using Logic Apps (Standard) VS Code extension **v2.45.4**

Also sharing the current version of extensions it depends on: 
Azurite v3.25.0
Azure Functions v1.12.2

**Comment by novenera** [comment]
> Hi @novenera, did you try to create a normal/simple logic apps project or did you indeed want a workspace with a functions and logic app projects. Just want to confirm if we should change the wording of the second one?

@ccastrotrejo - I created a workspace with a Function and Logic App project, no additional logic added.  See screenshots above.

**Comment by swghimire** [comment]
hi @novenera would you mind sharing your csproj file here/ the contents of the file?

**Comment by novenera** [comment]
[LAWorkspace.zip](https://github.com/Azure/LogicAppsUX/files/12255740/LAWorkspace.zip)


> hi @novenera would you mind sharing your csproj file here/ the contents of the file?

@swghimire - Sure, see attached.

**Comment by swghimire** [comment]
For some reason you are missing a launch.json file in the LogicApps/.vscode directory. Can you please insert a file named "launch.json" in  LogicApp/.vscode? And add this as the file content 

```
{
  "version": "0.1.0",
  "configurations": [
    {
      "name": "Attach to logic app",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:azureLogicAppsStandard.pickProcess}"
    }
  ]
}

```

**Comment by ccastrotrejo** [comment]
Thanks @swghimire. I am going to check if there was a code change or anything on why the file wasn't created.

**Comment by novenera** [comment]
> C: .azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows

Hi @swghimire -

I have added launch.json to LogicApp\.vscode as follows:

![image](https://github.com/Azure/LogicAppsUX/assets/16081468/3d9dfb95-d261-42aa-86c0-bcb61c48f04e)

I also checked the version of Azure Function Core Tools and see that I have v 1.28.4...

![image](https://github.com/Azure/LogicAppsUX/assets/16081468/0a279763-9c1d-4572-9666-66e7100d64e6)

Nonetheless, I deleted that folder to force reinstall.

![image](https://github.com/Azure/LogicAppsUX/assets/16081468/8dc60d7c-5ccc-41f6-b2d1-c8e0680efc43)

Tried opening the workflow designer again and got the same error:

![image](https://github.com/Azure/LogicAppsUX/assets/16081468/d82137b0-a2e1-4fcb-955d-c42e7cd6d840)


However, I did some digging and found that this might be related to issue with Azure Function Core tools and .NET 6.0 needed to be reinstalled ([https://github.com/Azure/azure-functions-core-tools/issues/3115](https://github.com/Azure/azure-functions-core-tools/issues/3115)).  I did just that and now I am able to load the workflow designer.

![image](https://github.com/Azure/LogicAppsUX/assets/16081468/a4f59a1c-5aff-4077-9e9a-4dc9b2f88c77)


Thanks for your help @swghimire and @ccastrotrejo !

**Comment by ccastrotrejo** [comment]
I am glad it worked out. Thanks for letting us know about the solution!
