### ISSUE TITLE
Standard_Custom Http Timeout Setting Per Request Action: Getting different validation error with PT24H request timeout.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3096]
### Describe the Bug with repro steps

1.Create a standard logic app
2.Create an empty stateless workflow
3.Add a request trigger and HTTP request action.
4.The request url to point to
(**https://httptimeoutendpoint.azurewebsites.net/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI**)
5.Go to settings tab and set Request options to PT24H
6.Disable the Asynchronous pattern.
7.Save and run the workflow.
8.**Expected Result:** Debugging should run with validation error message "**The provided request options timeout of '24:00:00' for action 'HTTP' must be less than '01:00:00'**.".
**Actual Result:** Getting different validation error with PT24H request timeout " **The provided request options timeout of '1.00:00:00' for action 'HTTP' must be less '00:03:45**".

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "HTTP": {
        "type": "Http",
        "inputs": {
          "uri": "https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI",
          "method": "POST"
        },
        "runAfter": {},
        "operationOptions": "DisableAsyncPattern",
        "runtimeConfiguration": {
          "requestOptions": {
            "timeout": "PT24H"
          }
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {
    "a": {
      "type": "Array",
      "value": [
        1,
        2
      ]
    },
    "b": {
      "type": "Int",
      "value": 12
    },
    "c": {
      "type": "String",
      "value": "131"
    },
    "d": {
      "type": "Float",
      "value": 0.187
    }
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/f4c4783a-9054-4ea0-97e0-38d0667d200e)

### Browser

Edge

### Additional context

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C25ee41df62d44438790c08db937727d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638265912263218130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ExdI18ub8D3V7ulDw4BDJPTB28t6zLoS8UczXvO%2FLFw%3D&reserved=0)
**Version:** 2.30731.1.4

AB#24772232

**Comment by vgouth** [comment]
Issue repro in the latest request 

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C31f9414be49a4c559f4b08db9e31995a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638277708135546081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tmb8PFftlO0IWCSjzJoxk%2B24Uxa3Q2ixHC68X0d%2BiB0%3D&reserved=0)
**Version:** 2.30814.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/a287ced4-76b0-466f-8e5e-3d91a6de8615)

**Comment by vgouth** [comment]
@AbodeSaafan . Request you to help us on this issue. Is this the expected result for PT24H request timeout?

**Comment by AbodeSaafan** [comment]
Do you know who wrote this test case? @alexkarcher-msft  I see that you added this timeout but it's always been at 3:45 so not sure why test is different or why it just started failing, can you help take a look

**Comment by vgouth** [comment]
@AbodeSaafan Not sure who wrote this test case.
@alexkarcher-msft . Request you to please have a look into the issue.

**Comment by alexkarcher-msft** [comment]
Thanks for finding this!

I also have no idea where that 1 hour default max timeout came from. I think I wrote this UX test before we had closed on the real default max timeout. Feel free to close out this issue and update the test to reflect the 3:45 max timeout error.

**Comment by vgouth** [comment]
@alexkarcher-msft . Thanks for your response. I have updated the test case as per the update. Closing this issue as informed.
