### ISSUE TITLE
Designer is crashing when selecting the Dynamic Content button

### ISSUE THREAD

**Issue by tonytang-microsoft-com** [Azure/LogicAppsUX#3106]
### Describe the Bug with repro steps

Open logic app designer and it crashed.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0

AB#24789386

**Comment by rllyy97** [comment]
@tonytang-microsoft-com Could you provide more information so we can try to reproduce the issue?  If you can, things like the workflow file, console logs, extension version would all be helpful

**Comment by Eric-B-Wu** [comment]
There is an ICM on this, Im currently in discussion with CSS getting more information, I'll assign myself to this

**Comment by Eric-B-Wu** [comment]
this is happening due to an invalid workflow json, specifically the schema of the user. Will look into validation/to prevent designer from crashing though
