### ISSUE TITLE
Logic App Standard | Request trigger provide wrong callback url when have relative path

### ISSUE THREAD

**Issue by tonytang-microsoft-com** [Azure/LogicAppsUX#3107]
### Describe the Bug with repro steps

Create a workflow with request trigger. See call back URL in the designer. It has the wrong encoded callback URL.

expected:
https://draclogicapp.azurewebsites.net:443/api/Test/triggers/When_a_HTTP_request_is_received/invoke?api-version=2022-05-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_recei<stripped>
actual:
[https://draclogicapp.azurewebsites.net/api/Test/triggers/When_a_HTTP_request_is_received/invoke/test?api-version=2022-05-01&sp=%252Ftriggers%252FWhen_a_HTTP_request_is_received<stripped>

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

ANY

AB#24789949

**Comment by Drac-Zhang** [comment]
@tonytang-microsoft-com  
one thing need to correct, it is Logic App Standard

**Comment by Drac-Zhang** [comment]
HI Team, do we have any update on this issue or a rough ETA? Thank you
