### ISSUE TITLE
The designer is empty but the code is not.

### ISSUE THREAD

**Issue by mikaelsand** [Azure/LogicAppsUX#3116]
### Describe the Bug with repro steps

1. Deployed a workflow using YAML pipelines, base of https://github.com/Azure/logicapps/blob/master/azure-devops-sample/.pipelines/classic/cd-pipeline.yml
2. The workflow is simple, receive request, get an image from a blobstore and return it in the response.
3. When looking in the portal, the code view shows the code but the designer is empty-
4. Using VS code both views work.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Get_Imagefile": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "containerName": "mycontainer",
                        "blobName": "thinking-emoji-by-twitter.png"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "AzureBlob",
                        "operationId": "readBlob",
                        "serviceProviderId": "/serviceProviders/AzureBlob"
                    }
                },
                "runAfter": {},
                "runtimeConfiguration": {
                    "secureData": {
                        "properties": [
                            "inputs"
                        ]
                    }
                }
            },
            "Response": {
                "type": "Response",
                "kind": "Http",
                "inputs": {
                    "statusCode": 200,
                    "body": "@body('Get_Imagefile')?['content']"
                },
                "runAfter": {
                    "Get_Imagefile": [
                        "SUCCEEDED"
                    ]
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "method": "GET"
                }
            }
        },
        "parameters": {}
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![logicappstandard](https://github.com/Azure/LogicAppsUX/assets/20858407/f952d14d-44c6-49c6-ac4f-7713dd6f5811)

### Browser

- Egde 

### Additional context

I feel the whole "deploy using CI/CD pipelines" is far from clear.

AB#24819808

**Comment by rllyy97** [comment]
Hi @mikaelsand, thanks for reporting your issue!  Normally if there's an issue during deserialization, the workflow will fail to load and will show an error message, so the fact that your workflow is loading as if it instead had no actions is strange behavior to me...

If you don't mind, to help us investigate further could you gather the console errors and a network trace of you trying to load your workflow?  You can find steps to do that [here](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-console-errors), and you can send the files to me at rileyevans@microsoft.com

**Comment by mikaelsand** [comment]
DOH! I missed the fact that you responded.
