### ISSUE TITLE
ContentTransfer property is preventing me to save Stateless logic app flow

### ISSUE THREAD

**Issue by abbids** [Azure/LogicAppsUX#3124]
### Describe the Bug with repro steps

1. While adding an Http call, by default the ContentTransfer property is off (in Settings > Networking > Content Transfer)
2. If it's on, it doesn't allow me to save the logic app with the following message
Workflow validation failed for the workflow 'LogicAppFlowName'. {"error":{"code":"InvalidStatelessFlowConfiguration","message":"The runtime configuration of stateless workflow trigger or action 'HTTP-XX' at line '1' and column '5191' is not supported in stateless workflow. Switching to stateful workflow or changing the runtime configuration of trigger or action 'HTTP-get_id_from_categoryType' may resolve this error."}}
4. Once I turn it off, flow saves successfully. However, when I reopen the flow, it automatically changes the 'Content Transfer' property of all the Http calls to 'On' and starts giving this error message again. I had to manually switch them to off for all the calls to safe my workflow.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

<img width="242" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/11636144/66cd3926-d7e7-42d0-bceb-58494addfd04">

### Browser

Happening both in Chrome and Edge

AB#24832884

**Comment by jezekt** [comment]
I get the same error while trying even to just update any action (URL inside HTTP action; value of string variable; etc.) inside stateless workflow regardless of whether 'ContentTransfer' is on or off . Stateful workflows work fine.

**Comment by Eric-B-Wu** [comment]
Thanks for reporting this issue, we're currently hotfixing a settings issue which should fix your current issue: https://github.com/Azure/LogicAppsUX/pull/3143

This should be EOD today 8/16

**Comment by Eric-B-Wu** [comment]
closing this issue, as PR has been merged. This will take a few hours to release to all regions but expect this to be complete by end of day today
