### ISSUE TITLE
Operation Errors - cases parameter errors ('Equals' is required)

### ISSUE THREAD

**Issue by yuki-ACN** [Azure/LogicAppsUX#3128]
### Describe the Bug

As you can infer from the error text, there is probably a problem with the validation of the switch action of the control connector on 'designer'.

This error occurs when trying to save changes on the 'designer'.
On the other hand, saving changes in the 'code view' does not occur it.
The workflow itself can also be executed normally.
In other words, we believe that the bug occurs only for changes made from the designer.

We did not see this bug until at least 8/10/2023 at midnight (JST); we just resumed work on 8/10/2023 at 9:00am(JST) and have encountered this bug.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

As explained above.

### Workflow JSON

```json
Difficult to provide due to business critical workflow.
```

### Screenshots or Videos

<img width="902" alt="image" src="https://github.com/Azure/logicapps/assets/141885871/28d16c4b-1c24-4a26-96da-7408fc3daee7">
<img width="848" alt="image" src="https://github.com/Azure/logicapps/assets/141885871/29db91a5-0b4a-444a-89ed-2e6d83f44b27">

### Additional context

If anyone have other reports like this, please share the information.

AB#24806354

AB#24835108

**Comment by Eric-B-Wu** [comment]
> @Eric-B-Wu i think this is like related to your conditional validation. Can we get this hotfixed asap?

This was related to a change where we check the validation on every parameter before saving. This fix should have been fixed in Riley's earlier PR, https://github.com/Azure/LogicAppsUX/pull/3119, though we found another problem with that PR which we're looking to fix currently https://github.com/Azure/LogicAppsUX/pull/3129/files
