### ISSUE TITLE
System assigned managed identity does not work for azure monitor logs connector.

### ISSUE THREAD

**Issue by skyaddict** [Azure/LogicAppsUX#3134]
### Describe the Bug with repro steps

1. create a standard logic app
2. create a workflow
3. trigger manual... I use the request trigger
4. add an Azure Monitor Logs action using the system assigned managed identity. (Run query and list results)
5. point to a 'log analytics workspace' ( give the logic app log reader role on the workspace)
6. setup  a connection using the logic apps managed identity ( system-assigned managed identity)
7. I set the query to just lookup the LogicAppWorkflowRuntime for the last hour
expected result: a connection is made and the query will run
result: It seems the connector is not minting a token using the system-assigned managed identkty 400 

{
  "ResultStatus": "BadRequest",
  "Content": {
    "status": 400,
    "source": "https://logic-apis-westus.consent.azure-apim.net:443/api/tokens/exchange?api-version=2015-11-01-preview",
    "message": "Failed to retrieve token for resource=https://api.loganalytics.io. Message=Parameter=Token not found."
  },
  "Message": "Failed to get HTTP response because of invalid input (ResourceTokenExchanger, queryData). Bad request input. Please Check user input parameters (query syntax, chart type or other resource input)\r\nclientRequestId: a60695a2-5258-460a-8612-7f74eaa878a8"
}

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Run_query_and_list_results": {
                "inputs": {
                    "body": "LogicAppWorkflowRuntime",
                    "host": {
                        "connection": {
                            "referenceName": "azuremonitorlogs"
                        }
                    },
                    "method": "post",
                    "path": "/queryData",
                    "queries": {
                        "resourcegroups": "{RD}",
                        "resourcename": "{log analytics workspace}",
                        "resourcetype": "Log Analytics Workspace",
                        "subscriptions": "{subscriptionid}",
                        "timerange": "@{utcNow()}"
                    }
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}


I should mention the connection object looks like this

        "azuremonitorlogs-2": {
            "api": {
                "id": "/subscriptions/752c6b93-eba6-47af-a7af-41cb22c87947/providers/Microsoft.Web/locations/westus/managedApis/azuremonitorlogs"
            },
            "authentication": {
                "type": "ManagedServiceIdentity"
            },
            "connection": {
                "id": "/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/connections/azuremonitorlogs-2"
            },
            "connectionProperties": {
                "authentication": {
                    "audience": "https://management.core.windows.net/",
                    "type": "ManagedServiceIdentity"
                }
            },
            "connectionRuntimeUrl": "https://{logic app unique id}.common.logic-westus.azure-apihub.net/apim/azuremonitorlogs/{connectionid}"
        }
```

### Browser

edge

AB#24851159

**Comment by rllyy97** [comment]
Hi @skyaddict, thank you for reporting your issue!  Unfortunately Managed Identity is not currently supported for that connector in Standard (it is supported in Consumption).  We are currently working on trying to get it removed in the UI for that connector until MI is supported.
In the meantime the OAuth option should be working, and we're currently working on fixing a bug related to the Service Principal option as well, so that should be available soon.
