### ISSUE TITLE
Initialization bug in Http action settings

### ISSUE THREAD

**Issue by yuki-ACN** [Azure/LogicAppsUX#3138]
### Describe the Bug with repro steps

We have found a bug that causes the Http action settings to revert to the default settings when the workflow is opened in the designer. 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

When saved.
<img width="1863" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/141885871/05a542e1-2a22-4ab8-aa5b-0571b1f1d5b8">
<img width="1858" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/141885871/f7aa1dfc-472b-4f31-8291-e7222f560f33">

The next time I open it in the designer
<img width="1856" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/141885871/851f1dbe-ab11-4436-9b4e-602847bdbd78">
<img width="1865" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/141885871/3dd1533c-fd5f-4f27-88bc-75214686108d">

### Browser

Edge

AB#24855432

**Comment by Eric-B-Wu** [comment]
closing this issue, as PR has been merged. This will take a few hours to release to all regions but expect this to be complete by end of day today
