### ISSUE TITLE
Standard_SFTP service provider trigger and action : Unable to see Inputs and outputs information/data

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3140]
### Describe the Bug with repro steps

1.Create a Logic apps in standard add stateful workflow.
2.Add When files are added or modified trigger and create a connection to it.
3.Try to save the workflow.
4.After saving the workflow, add a file in filezilla application (onetime setup)
5. Open Run history, a run corresponding to addition of file in filezilla will get populated and select a run.
6. Click on any successful run.

Expected : We should be able to see Inputs and outputs information.

Actual : Unable to see Inputs and outputs data. But when we are clicking on show raw inputs and show raw outputs we are able to see the inputs and outputs.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_files_are_added_or_updated": {
                "inputs": {
                    "parameters": {
                        "folderPath": "/LAtestinggoutham",
                        "includeFileContent": true
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "Sftp-3",
                        "operationId": "whenFilesAreAddedOrModified",
                        "serviceProviderId": "/serviceProviders/Sftp"
                    }
                },
                "kind": "Polling",
                "recurrence": {
                    "frequency": "Second",
                    "interval": 3
                },
                "splitOn": "@triggerOutputs()?['body']",
                "type": "ServiceProvider"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/c2d5a3f8-d834-4eac-a973-2b10ac7c4a59)

### Browser

Edge

### Additional context

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ca913e3ff33294e1163d608db9db5f11a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638277177033505326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MKfEmdMGq%2BLkG6Dt%2Bs8o2wQO8nicOL75f4AcxCeQnZA%3D&reserved=0)
**Version:** 2.30814.1.1

AB#24856675

**Comment by vgouth** [comment]
Issue repro in the latest request.

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C89705a12422746fdd5a208dba8b63ad9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638289272945091556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1uUwh%2F5zYjEst%2FQTftjQBH7n5FG4%2Bwig4y2whGdY5qs%3D&reserved=0)
**Version:** 2.30828.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/2ab931ed-40e2-4a39-8bb7-a732a3f3b264)

**Comment by ccastrotrejo** [comment]
Same issue as #3225. This is fixed

**Comment by vgouth** [comment]
Issue no repro in the latest request 
**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C4d9af69979e549a0496708dbbb42c34f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638309667714380958%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gVYbV%2F%2BAeZeK%2FYR3%2BxPSpZnmH%2Bq760cZ1aSM%2BOOlUxQ%3D&reserved=0)
**Version:** 2.30920.1.1

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/91f44530-bbb6-4074-b640-c2eca361f1e7)
