### ISSUE TITLE
Logic Apps Standard - VS Code Designer - Concurrency Setting not persisting

### ISSUE THREAD

**Issue by axiomitdavid** [Azure/LogicAppsUX#3150]
### Describe the Bug with repro steps

Create Workflow
Add ForEach
Set Concurrency to 1 or the value you desire

Workflow JSON contains
                "runtimeConfiguration": {
                    "concurrency": {
                        "repetitions": 1
                    }
Close designer
runtimeConfiguration is removed

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
After setting Concurrency to 1

{
  "type": "Foreach",
  "foreach": "@outputs('List_to_Process')",
  "actions": {
    "Compose": {
      "type": "Compose",
      "inputs": "Something"
    }
  },
  "runAfter": {
    "List_to_Process": [
      "SUCCEEDED"
    ]
  },
  "runtimeConfiguration": {
    "concurrency": {
      "repetitions": 1
    }
  }
}


After saving the workflow, closing Designer and re-opening the same workflow
{
  "type": "Foreach",
  "foreach": "@outputs('List_to_Process')",
  "actions": {
    "Compose": {
      "type": "Compose",
      "inputs": "Something"
    }
  },
  "runAfter": {
    "List_to_Process": [
      "SUCCEEDED"
    ]
  }
}
```

### Screenshots or Videos

Before

<img width="612" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/41350688/a7766097-eb4c-4a2a-836f-1f3622f5641e">

After saving, closing and reopening

<img width="612" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/41350688/1ab3c64e-e949-4c8e-96ea-124241a898d5">

### Browser

VS Code Info

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

Azure Logic Apps Standard Extension:  2.55.6

AB#24866413

**Comment by Eric-B-Wu** [comment]
Hi @axiomitdavid, yesterday we had a hotfix that went to all regions to fix an issue where settings were not being updated in the designer https://github.com/Azure/LogicAppsUX/pull/3143. I just tried changing the concurrency in a for each loop, and no longer see it happening. Can you verify if it is fixed now?

**Comment by ccastrotrejo** [comment]
Hi @johnno82 we have just released a new vscode extension version with the hotfix. Could you please update and check if this issue still happens?

**Comment by axiomitdavid** [comment]
Confirm hotfix has corrected the issue.  Thanks for the quick response.

**Comment by axiomitdavid** [comment]
This appears to have been regressed.  Seeing the same behaviour again.
