### ISSUE TITLE
Tracked properties lost from json, code or from developer designer

### ISSUE THREAD

**Issue by djmanosv1** [Azure/LogicAppsUX#3154]
### Describe the Bug with repro steps

Go to Workflow Code, tracked properties are there
Go to Workflow Designer, tracked properties are missing

Try to save designer if do another change, now tracked properties are gone from workflow code

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "ComposeInput": {
                "inputs": "@triggerBody()",
                "runAfter": {},
                "trackedProperties": {
                    "X-Correlation-Id": "@triggerOutputs()?['headers']?['X-Correlation-Id']",
                    "input": "@outputs('ComposeInput')"
                },
                "type": "Compose"
            },
```

### Screenshots or Videos

Tracked properties lost or not visible 
![image](https://github.com/Azure/LogicAppsUX/assets/66848828/aa740f61-7cec-408a-a32d-ed32a6d396e4)

![image](https://github.com/Azure/LogicAppsUX/assets/66848828/3cd91b4a-4f61-406d-bc6e-63c3cb9b8b49)

### Browser

Edge Windows 11

### Additional context

The tracked properties are visible in json but not in designer

When I resave the designer flow, the tracked properties are gone even from the json 

AB#24869984

**Comment by Eric-B-Wu** [comment]
Hi @djmanosv1, yesterday we had a hotfix that went to all regions to fix an issue where settings were not being updated in the designer https://github.com/Azure/LogicAppsUX/pull/3143. I just tried with your workflow, and no longer see it happening. Can you verify if it is fixed now?

**Comment by Eric-B-Wu** [comment]
closing as I'm pretty certain this was caused due to our setting deserialization regression and fixed in https://github.com/Azure/LogicAppsUX/pull/3143
