### ISSUE TITLE
Failed to login. Response status code does not indicate success: 401 (Unauthorized)

### ISSUE THREAD

**Issue by jasleenkaursaundh** [Azure/LogicAppsUX#3165]
### Describe the Bug with repro steps

I am not able to connect azure logic app with twitter. In my case the pop window opens up and closes immediately and return connection failed on the Logic Apps Designer. I will appreciate your support in resolving this issue, it's a big blocker for me.  try to run it, it returns error 401!

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

<img width="461" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/100664280/952e2a3b-8c27-4701-9ebc-305befe8c0b7">

### Browser

CHROME

### Additional context

I am not able to connect azure logic app with twitter. In my case the pop window opens up and closes immediately and return connection failed on the Logic Apps Designer. I will appreciate your support in resolving this issue, it's a big blocker for me.  try to run it, it returns error 401!

AB#24895418

**Comment by Eric-B-Wu** [comment]
Hi @jasleenkaursaundh, thanks for reporting this issue. Unfortunately, twitter recently changed their API rules such that we aren't able to provide a default connection experience anymore. For your key/secret combo, are you using one of twitter's new paid API tiers? I don't think they provide a free tier anymore except in particular circumstances.

https://developer.twitter.com/en/portal/petition/essential/basic-info
