### ISSUE TITLE
Unable to initialize operation details when AppConfiguration reference is used in AppSettings

### ISSUE THREAD

**Issue by pfesenmeier** [Azure/LogicAppsUX#3166]
### Describe the Bug with repro steps

1. Create Logic App
2. Create an App Configuration and give it a key/value pair.
3. Give your Logic App Read Permission to App Configuration.
4. Create an App Setting to reference the key (`@Microsoft.AppConfiguration(Endpoint=https://my-appcg.azconfig.io; Key=my_key)`). Make sure the UI shows that the setting status is **Resolved**.
5. Create a workflow and use the app setting in an action or trigger.

Expected: To be able in the Designer to read and edit actions and triggers that use app configuration key/value.

Actual: See Error

`Unable to initialize operation details for swagger based operation - Action_Name. Error details - Unsupported domain @Microsoft.AppConfiguration(Endpoint=https: in batch call. Only ARM endpoints are supported in batch.`

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/50887639/8c9a0d62-a38c-4926-97fd-789762e2a269)
![image](https://github.com/Azure/LogicAppsUX/assets/50887639/56642e4f-6b58-4e91-b120-8e20525144a6)

### Browser

Edge
Version 115.0.1901.203 (Official build) (64-bit)

### Additional context

Using the old Designer does not resolve the issue.

AB#24897653

**Comment by rllyy97** [comment]
Hi @pfesenmeier, thank you for reporting your bug and for the detailed repro steps!
I'll be looking into this today and let you know when I have an update.

**Comment by rllyy97** [comment]
@pfesenmeier, I have a couple questions for you after doing some digging
1. Were you able to save the workflow okay without any errors in the UI?
2. Were the error screenshots seen after saving and refreshing in the workflow editor, or after trying to run the workflow and opening a run entry?
3. Would you mind sharing the code view of the action that is erroring out? (Minus any sensitive info)

**Comment by pfesenmeier** [comment]
1. Yes
2. Workflow editor. Though same errors are seen in the run view.
3 & 4:

Doing some digging, I can minimally reproduce the error by using the appsetting in `connections.json`. We are using an appsetting that references an app config in a managed API connection to blob storage:

```json
{
    "managedApiConnections": {
        "azureblob": {
            "api": {
                "id": "/subscriptions/@{appsetting('subscriptionId')}/providers/Microsoft.Web/locations/eastus/managedApis/azureblob"
            },
            "authentication": {
                "type": "ManagedServiceIdentity"
            },
            "connection": {
                "id": "..."
            },
            "connectionProperties": {
                "authentication": {
                    "audience": "https://storage.azure.com/",
                    "identity" : "...",
                    "type": "ManagedServiceIdentity"
                }
            },
            "connectionRuntimeUrl": "..."
        }
    }
}
```

We are also using the appsetting in the `.api.id` for the managed connections to event grid and service bus, and seeing the same error as described previously. 

Funny enough, we are using an appconfig value in our function connections, and do not see the error.

**Comment by rllyy97** [comment]
I was able to see the error using your repro of modifying the connections.json file to include the appsetting there, but that behavior does not work in legacy designer either, I'm not sure this is a behavior we officially support.

For your initial issue repro, were you able to do what you tried in legacy designer?  If you never tried it there you can access legacy designer from this URL:
https://ms.portal.azure.com/?microsoft_azure_ema_forceFallbackToOldDesigner=true#home

**Comment by pfesenmeier** [comment]
In my initial repro, I tried the legacy designer, and still got an error.
![image](https://github.com/Azure/LogicAppsUX/assets/50887639/09edf969-4407-41d7-9a45-2c3736a40ffc)

In the original screen shot, we are using the managed connector to event grid for the trigger "When a resource event occurs".
The connector also has the app setting / app config in the `.api.id`
```
{
        "azureeventgrid": {
            "api": {
                "id": "/subscriptions/@{appsetting('subscriptionId')}/providers/Microsoft.Web/locations/eastus/managedApis/azureeventgrid"
            },
            "authentication": {
                "type": "ManagedServiceIdentity"
            },
            "connection": {
                "id": "@{appsetting('connectionId')}"
            },
            "connectionProperties": {
                "authentication": {
                    "audience": "https://management.core.windows.net/",
                    "identity": "@{appsetting('userAssignedIdentityId')}",
                    "type": "ManagedServiceIdentity"
                }
            },
            "connectionRuntimeUrl": "@{appsetting('egRuntimeUrl')}"
        }
}
```

**Comment by rllyy97** [comment]
I reached out to some backend folks and it looks like this isn't supported behavior unfortunately, this docs page has some more info on the topic:
https://learn.microsoft.com/en-us/azure/logic-apps/devops-deployment-single-tenant-azure-logic-apps

One place it does work though is inside the connection properties, but you'll want to remove the `{}` around the appsetting, like this: 
`@appsetting('userAssignedIdentityId')`

I'm going to close this issue but if you have anything else feel free to leave more comments and I'll keep following up / reopen if needed

**Comment by haggerty-ian** [comment]
Hi @rllyy97 ,
I've looked over the documentation you linked, and I can definitely see how it is emphasized that "Service Provider Connections" should make heavy use of appsettings. However, I don't see where it says that you can't use appsettings for other connection types.

I'm trying to figure out what you are saying isn't supported. Are you saying that the unsupported behavior here is using an appsettings reference for those `id` properties inside of the "Managed API Connections"?

**Comment by Eric-B-Wu** [comment]
"@Microsoft.AppConfiguration" inside an app setting is what doesn't work. We currently don't support using the app configuration in our app settings

**Comment by haggerty-ian** [comment]
Okay, cool. I think what confuses me about that is, we have a nice UI element in our logic app settings showing how the app configuration references (and keyvault references) are correctly set up. We haven't had any issues using settings like this in other circumstances.
![config_reference_ui](https://github.com/Azure/LogicAppsUX/assets/50878637/88072d71-1c28-4ace-9dfa-d4e8f2f4f2c9)

Is it only in this circumstance (inside the `connections.json` file) that app config in app settings isn't supported, or is that supposed to be across the board? And would a keyvault reference be supported here?

**Comment by earloc** [comment]
Recently stumbled upon a similar situation here. For me, only the designer chokes on connections referencing appsettings, where the value itself points to `@Microsoft.AppConfiguration(...`.
Workflow execution, however, seem to just work fine.

Is there a valid workaround other that ditching `@Microsoft.AppConfiguration` at all form such cases?
Will this be enabled in the future?
