### ISSUE TITLE
HttpTrigger azure function step before a sendgrid email fails due to special character

### ISSUE THREAD

**Issue by gonzalo525** [Azure/LogicAppsUX#3178]
### Describe the Bug with repro steps

1. create an azure function that is an httptrigger
2. create an azure logic app where:
2a. triggers on a schedule, say every 5 minutes
2b. run the azure function in step 1
2c. send a sendgrid email (Send Email (v4)) where the body would have: 

outputs('AzureFunctionsPython/HttpTrigger')?['statusCode']

3. even if you DO NOT show the output of step 2c in the body of the email, when saving the logic app you get the error attached. 

NOTE that if you remove step 2b, this logic app works, i.e. it triggers every 5 minutes and sends out an email. Also note that I used the UI to add the httpTrigger in between step 2a and 2c, so Azure "found" the function "httpTrigger" inside the "function app" "AzureFunctionsPython". It automatically named the object "AzureFunctionsPython/HttpTrigger" and added the special character "/". Also, when the "Send Email (v4)" object allows me to enter a function in the body and the UI finds the "dynamic content" and shows me the options [output, headers, status code]. Long story short, I'm selecting things that Azure finds and then it errors out on a simple special character. How would I trigger an azure function and simply output the status code in the subsequent email?

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Microsoft Edge
Version 115.0.1901.203 (Official build) (64-bit)

AB#24912392

**Comment by gonzalo525** [comment]
Here is the error message
![azure logic apps with functions error2](https://github.com/Azure/LogicAppsUX/assets/56669621/38fbf80b-73b9-4a8d-b22e-b9c9946c9e29)

**Comment by rllyy97** [comment]
The validation error from your screenshot appears to be about your function action having the `/` character in it's name, can you try renaming your function action and remove the `/` character?
