### ISSUE TITLE
AWS S3 Create Object - Not Available

### ISSUE THREAD

**Issue by hprasad-dc1104** [Azure/LogicAppsUX#3192]
### Describe the Bug with repro steps

As Part of Action, I'm unable to see s3 create object option

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

Old Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/117668740/eb3b8788-90c1-4f97-844a-cc08c3581dbb)

### Browser

Chrome

AB#24938831

**Comment by hprasad-dc1104** [comment]
I still don't see s3 object create option in Logic app.

**Comment by Eric-B-Wu** [comment]
this api isn't owned by our team, that being said, looking at the documentation: https://learn.microsoft.com/en-us/connectors/amazons3/#actions, it doesn't seem this was supported - was this previously available?
