### ISSUE TITLE
Don't prefetch browse items when in monitoring view

### ISSUE THREAD

**Issue by hartra344** [Azure/LogicAppsUX#3194]
AB#24942488

**Comment by rllyy97** [comment]
Do we need the browse items when designer is in monitoring view for something?  We shouldn't be able to add nodes so I'm not sure when those items would be needed

**Comment by hartra344** [comment]
It's fetching them now, this bug is to make it so we don't

**Comment by hartra344** [comment]
I'll make the change, this was just something to track it :P Noticed it when I was adding resubmit
