### ISSUE TITLE
Dynamic content w.r.t Attachment from Office 365 connector when passed in other actions is adding 2 Foreach loop in Logic app standard

### ISSUE THREAD

**Issue by sonalmoze** [Azure/LogicAppsUX#3196]
### Describe the Bug with repro steps

1)Created a workflow in Logic app standard.
2)Added trigger 'When a new email arrives (V3)' 
3)You can add any action , I added action 'Create file' and can pass any dynamic content w.r.t Attachment from office 365 connector 
(This will add 2 foreach)
![image](https://github.com/Azure/LogicAppsUX/assets/143148606/a5f9b125-e982-4fe7-967d-293a061928fd)
![image](https://github.com/Azure/LogicAppsUX/assets/143148606/ede4e0fd-05fb-4389-8b9b-960aca39aa2c)

When the Logic app is tested it fails with below error :
![image](https://github.com/Azure/LogicAppsUX/assets/143148606/bc1ff315-b5c4-46b0-9417-cf9c36c989ac)

Checked consumption Logic app and fallback URL there only 1 foreach loop is added.
![image](https://github.com/Azure/LogicAppsUX/assets/143148606/98d4d286-fa1a-43f7-96be-c16a1a876d8e)

Issue is only with new designer in Logic app standard. 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#24944649

**Comment by Eric-B-Wu** [comment]
Hi @sonalmoze, thanks for reporting this issue, we have this issue here: https://github.com/Azure/LogicAppsUX/issues/3196, which we'll be using for tracking
