### ISSUE TITLE
Deleting a token from StringEditor without focusing it does not update the store 

### ISSUE THREAD

**Issue by wifun** [Azure/LogicAppsUX#3209]
### Describe the Bug with repro steps

1. Create a workflow with "compose" action
2. Add a token to the action
3. Ensure the editor is unfocused
4. Click on the 'X' to delete the token
5. Observe that "Code View" still shows the token is present, switching back to the parameters tab will "restore" the token

One consequence with this bug is when saving the workflow after removing tokens in UI, the save will not have the tokens deleted.

The update happens with the editor component "onblur" which doesn't fire if we don't focus the editor.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/55114634/9cfeceac-ba84-474a-b55a-ff7686acb262)

After deleting token:
![image](https://github.com/Azure/LogicAppsUX/assets/55114634/599e8969-a7ba-49a9-9fce-2a343372b735)

### Browser

Chrome

AB#24979077

**Comment by Eric-B-Wu** [comment]
seems like this was a regression, I can create a quick PR for this one
