### ISSUE TITLE
In China regions, new designer is not able to show trigger input and output

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#3213]
### Describe the Bug with repro steps

1. Create a test standard logic app in China East 2 with SB trigger
2. Run it and you will see the issue.

Note:
1. The issue does not happen if we switch to classic designer
2. Network trace shows no issues in bringing back the input/output from backend.  Looks like it is just a UI display issue. 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/49498706/e20258ef-5b32-4d91-8aec-3de94f76307b)

### Browser

Chrome

AB#24989197

**Comment by ccastrotrejo** [comment]
Hi @xuehongg, is there an ICM regarding this issue? Is there any way we can get the HAR file for this? 
I tried to repo, however I just got the confirm dialog to add the portal url to CORS, I added it and then I was able to see those.
