### ISSUE TITLE
initialize variable failed to retrieve dynamic inputs 

### ISSUE THREAD

**Issue by RichardFoster2** [Azure/LogicAppsUX#3215]
### Describe the Bug with repro steps

Add initialize variable
Type in name of "InstanceId"
Change Type to "string"

Then there is no save, so hit the << to close insert.

Shows error: Failed to retrieve dynamic inputs. Error Details: 'Cannot read properties of undefined (reading '0')

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#24994773

**Comment by hartra344** [comment]
@RichardFoster2 do you have a video of the issue by any chance? I can't repro the problem based on your description


https://github.com/Azure/LogicAppsUX/assets/13208452/6495ad7f-754a-4d56-85ec-424133941220

**Comment by rllyy97** [comment]
Hi @RichardFoster2, this issue is currently being hotfixed, we are trying to have the fix rolled out to all regions by EoD
Feel free to try again tomorrow and if you're still running into the issue let us know!
