### ISSUE TITLE
VSCode LogicApp Standard Designer looses all unsaved changes when another VSCode document gets focused

### ISSUE THREAD

**Issue by qbq-ber-robin-klimonow** [Azure/LogicAppsUX#3230]
### Describe the Bug with repro steps

1.: Open a LogicApp Standard Designer of any workflow
2.: Do any changes (for example adding a simple action to the workflow)
3.: Open another document in VSCode (even the workflow.json in json code editor)
4.: Click on the LogicApp Standard Designer Tab from step 2
5.: Observe all changes gone

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#25019264

**Comment by ccastrotrejo** [comment]
Hi @qbq-ber-robin-klimonow thank you so much for raising this issue. I will close this one as duplicated. We will just this issue https://github.com/Azure/LogicAppsUX/issues/2908 to keep track of it
