### ISSUE TITLE
SQL Server Connector Trigger not working: The 'ListCallbackUrl' API is not supported by triggers of type 'ServiceProvider'

### ISSUE THREAD

**Issue by zerophilmister** [Azure/LogicAppsUX#3236]
### Describe the Bug with repro steps

In the Azure portal:
1.  create a standard logic app with vnet injection and integration 
2.  create a workflow with a sql insert trigger
3.  connect to a microsoft sql server hosted on an azure vm in the same vnet - issue also happens when the logic app and sql server are in two different vnets in two different tenants with vnet peering. 
4.  select a table to monitor
5.  run trigger

On the activity log for the logic app, you will see errors for the following operations: Run and Get Web Apps Hostruntime Workflow Trigger Uri.

The message for the "Get Web Apps Hostruntime Workflow Trigger Uri" operation is: The 'ListCallbackUrl' API is not supported by triggers of type 'ServiceProvider'.

![error](https://github.com/Azure/LogicAppsUX/assets/86268610/2b46db04-7378-4641-b547-90c817ff3d58)
![la_tables](https://github.com/Azure/LogicAppsUX/assets/86268610/b6986b85-618e-471b-bce3-7218a6284812)
![la_flow](https://github.com/Azure/LogicAppsUX/assets/86268610/bc41fa41-b84a-4def-8b1b-41451b94d964)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Compose": {
        "type": "Compose",
        "inputs": "@triggerBody()",
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_row_is_inserted": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "tableName": "[dbo].[Contact]"
          },
          "serviceProviderConfiguration": {
            "connectionName": "sql-2",
            "operationId": "whenARowIsInserted",
            "serviceProviderId": "/serviceProviders/sql"
          }
        }
      }
    }
  },
  "connectionReferences": {
    "sql-2": {
      "connection": {
        "id": "/serviceProviders/sql/connections/sql-2"
      },
      "connectionName": "dbconnection",
      "api": {
        "id": "/serviceProviders/sql"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

![error](https://github.com/Azure/LogicAppsUX/assets/86268610/c06ac2aa-cd0e-4cd9-8b0a-afe6d9b986cb)

### Browser

Firefox and Chrome

### Additional context

I do not believe this is an issue with networking because I can see the tables available for the sql server when I make the connection in the logic app. 

AB#25010559

AB#25010796

AB#25025480

**Comment by zerophilmister** [comment]
Why and how would I do that?

Made this question on Microsoft questions and the issue was reproduced. The person said they are having the product team look into it:
https://learn.microsoft.com/en-us/answers/questions/1355577/getting-error-for-standard-logic-app-sql-trigger-t?comment=question#comment-1362425

**Comment by Eric-B-Wu** [comment]
Oh sorry @zerophilmister, that was a comment for us - I had previously transferred it to our backend team thinking it was a bug on their end. However, was recently added to a discussion which I was informed that the ask on the UX team is to suppress the listCallbackUrl for non-request triggers. I had just moved it back with that comment so that it wouldn't get lost again

**Comment by zerophilmister** [comment]
@Eric-B-Wu sounds good. Thank you

**Comment by zerophilmister** [comment]
Thank you.
