### ISSUE TITLE
Operation settings SecureData "LinkedToInputs" option missing description (did not confirm functionality)

### ISSUE THREAD

**Issue by wifun** [Azure/LogicAppsUX#3237]
### Describe the Bug with repro steps

I haven't tested if it's just a description that needs to be updated or that the feature is missing (I'm assuming it's the former).

In v1 designer, setting "LinkedToInputs" in manifest would have a different description:
![image](https://github.com/Azure/LogicAppsUX/assets/55114634/d8841e2e-5d84-4938-bf2c-a027d0900c3d)

In v3, the text is unchanged:
![image](https://github.com/Azure/LogicAppsUX/assets/55114634/cf029b9f-1c0f-4b49-b85d-f3dfab2ff118)

Setting:
```
secureData: {
  options: {
    outputsMode: OutputSecureDataMode.LinkedToInputs,
  },
}
```

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25031203

**Comment by Eric-B-Wu** [comment]
There is currently a gap in settings where things are missed. We will be doing a rewrite of settings: https://github.com/Azure/LogicAppsUX/issues/2266
