### ISSUE TITLE
The run history for Logic app standard shows the action execution status and inputs/outputs from previous iteration of foreach

### ISSUE THREAD

**Issue by manoharpatel** [Azure/LogicAppsUX#3240]
### Describe the Bug with repro steps

In the new designer, within a foreach if a condition is skipped, the actions after the condition show the status and inputs/outputs from the previous iteration.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

Issue in new designer:
![image](https://github.com/Azure/LogicAppsUX/assets/85441913/9af5baa2-89ec-4c5f-aadd-830b737e5c41)

The issue is not seen for the same run in the old designer:
![image](https://github.com/Azure/LogicAppsUX/assets/85441913/1db91c5c-9124-4076-b486-579f1e767bfe)

### Browser

Chrome

AB#25039445

**Comment by ccastrotrejo** [comment]
Hi @manoharpatel not yet, I will look at it today.
