### ISSUE TITLE
[Accessibility] : "Custom Tracking ID" text visually appears as a heading but not defined as heading programmatically.

### ISSUE THREAD

**Issue by shahparth-lab** [Azure/LogicAppsUX#3257]
### Describe the Bug with repro steps

[Programmatic Access - ICM - Trigger -> Settings]

User Experience:
The visually impaired users will be impacted and will not be able to navigate to important sections of the application using screen readers in heading mode.

Note: User credentials should NOT be included in the bug.
Repro Steps:
Launch URL: https://portal.microsofticm.com/imp/v5/automation/
Sign in with valid credential.
Navigate to "Service and Team" dropdown and select "ICM Shadow DRI" under 'ICM Management Service'.
Navigate to 'Get started' tab and select "Start from blank".
Select any connector (EX: Schedule) under 'All'.
Select any trigger under the triggers tab. (EX: Occurrence).
Navigate to "Menu for recurrence" option and select it.
Navigate to the "Settings" button and select it.
Verify and observe the issue.

Actual Result:
"Custom Tracking ID" text visually appears as a heading but not defined as heading programmatically.

Expected Result:
"Custom Tracking ID" text visually appears as a heading should be defined as heading programmatically.

Note: 
The same issue is observed for the other visually appearing headings in the same pane for the text such as "Settings for recurrence", "Concurrency Control", "Trigger Conditions".
The same issue is observed in the "Delete Step" dialog on the same page. Navigation: Open URL: https://portal.microsofticm.com/imp/v5/automation/ -> Start from blank -> Select any connector -> Occurrence -> Menu for recurrence -> Delete.
The Same observed with 'Service/Team(s)' text present in left navigation throughout the application. Navigation: URL: https://ppeportal.microsofticm.com/imp/v3/oncall/full > On Call list> Select 'Who's on call> Left navigation >verify the issue

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

OS: Windows 11 Version 21H2 (OS build: 22000.795)
Browser: Chrome Version 103.0.5060.134 (Official Build) (64-bit)

AB#25072759

**Comment by hartra344** [comment]
This is on the ICM portal which is still currently using V1 portal, this won't be fixed or supported. I'm working with them to move to new portal.
