### ISSUE TITLE
Error suggestions are not provided while entering any text or making Interval as blank under Recurrence pane.

### ISSUE THREAD

**Issue by shahparth-lab** [Azure/LogicAppsUX#3259]
### Describe the Bug with repro steps

User Experience:
If correct error suggestion is not provided for any form field, then user will provide incorrect values in the form fields, while submitting the form they will face the issues and they may not understand about the error occurred in the page.

Note: Login Credentials must not be provided within the bug.

Repro Steps:
Launch the URL: https://portal.microsofticm.com/imp/v5/automation/
Sign in with valid credential.
Navigate and select 'Automation' option in header section.
Navigate to various tile like Learn more, Start from blank, ICM etc. under Automation page.
Navigate and select 'Start from blank'.
Navigate all the controls on the 'Create workflow' page.
Navigate to 'Search' edit field.
Search valid/invalid connectors.
Select any connector such as 'Schedule'.
Navigate all the controls in the 'Trigger' tab.
Select 'Recurrence' list option.
Navigate to 'Recurrence' screen.
Verify the issue.

Actual Result:
Error suggestions are not provided while entering any text or making Interval as blank under Recurrence pane.

Expected Result:
Error suggestions should be provided while entering any text or making Interval as blank under Recurrence pane as Please enter value in range or entered text are not in correct format.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

OS Version: Windows 11 22H2 (OS Build:25163.1010)
Browser: Chrome Version 105.0.5195.102 (Official Build) (64-bit)

AB#25072810

**Comment by hartra344** [comment]
This is on the ICM portal which is still currently using V1 portal, this won't be fixed or supported. I'm working with them to move to new designer.
