### ISSUE TITLE
Enabling user managed identity to connect to APIHub

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#3268]
### Describe the Bug with repro steps

1. Create a LA standard
2. Disable its system identity and add a user identity
3. Create a workflow 
4. Add a managed connector like SB connector trigger to the workflow
5. Select "Logic Apps Managed Identity" as authentication method and fill in other fields. And save.
6. Now check connections.json and you see the connection like this one:

```
        "servicebus-2": {
            "api": {
                "id": "/subscriptions/xxxxxx/providers/Microsoft.Web/locations/eastus/managedApis/servicebus"
            },
            **"authentication": {
                "type": "ManagedServiceIdentity"
            },**
            "connection": {
                "id": "/subscriptions/xxxxxx/resourceGroups/GanASE_group/providers/Microsoft.Web/connections/servicebus-2"
            },
            "connectionProperties": {
                "authentication": {
                    "audience": "https://servicebus.azure.net",
                    "identity": "/subscriptions/524c1207-2135-4f08-81f3-6577a6d41405/resourcegroups/refresh/providers/Microsoft.ManagedIdentity/userAssignedIdentities/APITest1",
                    "type": "ManagedServiceIdentity"
                }
            },
            "connectionRuntimeUrl": "https://9d51d1ffc9f77572.00.common.logic-eastus.azure-apihub.net/apim/servicebus/17ee8e7251f74e528a5248c62bbd8b87"
        }
```

8. The problem is in this section.  This section is specifying to use system identity.  But in this scenario, the system identity is disabled and it should specify user identity instead.
            **"authentication": {
                "type": "ManagedServiceIdentity"
            },**

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25091017

**Comment by rllyy97** [comment]
@xeuhongg I'm confused on what the expected behavior should be, are you saying the `authentication.type` isn't supposed to be `ManagedServiceIdentity` if it's a user identity?  Shouldn't the identity just be defined in the `connectionProperties.authentication.identity` spot?
