### ISSUE TITLE
Unable to initialize operation details for swagger based operation 

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#3271]
### Describe the Bug with repro steps 

1. it happens when the user does not have logic app contributor role. 
2. The issue does not happen if the same user opens the history with the classic designer. 

![image](<https://github.com/Azure/LogicAppsUX/assets/49498706/025a7e21-65a2-47b3-848f-28361ca7b5d9>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

AB#25091314

**Comment by alavudeenb** [comment]
i have similar issue with SAP managed connector (When a message is received - trigger) used in Logic app standard.

![image](https://github.com/Azure/LogicAppsUX/assets/56952115/51c5e4eb-9bfe-48ab-8dbd-465924336703)

**Comment by VictorVenetian** [comment]
Also have similar issue: Unable to initialize operation details for swagger based operation - Execute_a_SQL_query_(V2). Error details - Error: Incomplete information for operation 'Execute_a_SQL_query_(V2)'

This occurred after moving API managed connection to new resource group. Logic app was moved previously, but API connections are not supported when trying to use portal to move to new resource group. So I created a new managed API connection to an Azure SQL DB, and then went back into workflow designer and get above error.

Any ideas?

![image](https://github.com/Azure/LogicAppsUX/assets/142360543/5433785e-8c6b-4d0e-be5d-0409ab6528be)

**Comment by chwilfing** [comment]
Same issue here: 

![image](https://github.com/Azure/LogicAppsUX/assets/16267927/208a290d-d712-4ebc-a397-8c98ddd0c133)

Sharepoint Connection which was newly created after move of the Logic App to a new Resource Group / Subscription. The 'General availably designer' does not show an error an can work with the logic app, only the 'preview' Designer shows the error.

**Comment by hartra344** [comment]
Closing this issue to track here #3271

**Comment by Wittionary** [comment]
> Closing this issue to track here #3271

Hey @hartra344 , it looks like you linked back to this issue. I was expecting a link that referenced a different issue in this repo or a related issue in another repo.

Did you intend to close this issue without a link to a spot where it's being tracked?
