### ISSUE TITLE
Referencing Parameters from a Parse JSON activity

### ISSUE THREAD

**Issue by Joyw1** [Azure/LogicAppsUX#3272]
### Describe the Bug with repro steps 

When generating a Parse JSON activity using a sample payload to generate the schema (which was a result of parameters from the inbuild SQL Connector), LogicApp correctly creates a schema with the property containing ‘@@’

Sample Schema Payload :

```
{
  "@Description": "SA border to Norseman - R1: Main Works Design and Construct"
}
```

Resulting Schema:

```
{
    "type": "object",
    "properties": {
        "@@Description": {
            "type": "string"
        }
    }
}
```

![image](<https://github.com/Azure/LogicAppsUX/assets/36072422/b8565153-bd51-4cc3-af2a-e342f556e738>)

![image](<https://github.com/Azure/LogicAppsUX/assets/36072422/4b87ec5f-e827-4d7b-8567-bfbd7b29f9d3>)

Of course, the outputs of the Parse JSON activity will reference the parameter name with one @ -ie "@Description”

![image](<https://github.com/Azure/LogicAppsUX/assets/36072422/3da34678-5cbb-4ddc-8fb3-c3eba3265e72>)

However, when selecting this parameter in a subsequent activity (such as Populate a Microsoft Word Template’), the resulting code will be incorrectly generated with two ‘@@’ characters within the parameter reference.

![image](<https://github.com/Azure/LogicAppsUX/assets/36072422/da99b3dd-8370-4264-a8cd-8fe608368625>)

```
{
  "type": "ApiConnection",
  "inputs": {
    "host": {
      "connection": {
        "referenceName": "wordonlinebusiness"
      }
    },
    "method": "post",
    "body": {
      "704457091": "@{triggerBody()?['contract_id']}",
      "740216700": "@{triggerBody()?['project_manager']}",
      "849141738": "@{triggerBody()?['notice_type']}",
      "933936541": "@{triggerBody()?['contract_clause']}",
      "1381743620": "@{('Parse_Contract_Details')?['@@Description']}"
    },
    "path": "/api/templates/getFile",
    "queries": {
      "source": "@{parameters('FlowForma-URL')}",
      "drive": "b!k35m8Jf2j0iQ3aOHiMx2irkGDXhqj1FBkqYQCygouGyRxvjPT-0uSrHgR1qlypot",
      "file": "01XRI4L5LPHGP2T3CO7ZB2X7TWEGGMJHNP"
    }
  },
  "metadata": {
    "01XRI4L5LPHGP2T3CO7ZB2X7TWEGGMJHNP": "/General Notice.docx"
  }
}
```

As workaround to the fix the issue, the dynamic code block needs to be modified to remove one of the ‘@’ characters.

We can reproduce this issue in the GA portal designer for standard logic app, but it works with the cx’s expected behavior in old UI - [https://aka.ms/lafallback](<https://aka.ms/lafallback>) and consumption logic app in GA portal designer.

Could you please check if it is an issue of the GA designer? Could you please help fix it?

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

AB#25092244

**Comment by Eric-B-Wu** [comment]
this should be fixed now
