### ISSUE TITLE
Referencing Body from Populate a Microsoft Word Template activity

### ISSUE THREAD

**Issue by Joyw1** [Azure/LogicAppsUX#3273]
### Describe the Bug with repro steps

When referencing the body from the ‘Populate a Microsoft Word Template’ activity within an subsequent activity (such as Create SharePoint File), the corresponding code generated now incorrectly contains opening and closing {}
 
`"@{body('Populate_a_Microsoft_Word_template')}"`
 
This results in invalid File Content information being passed to the subsequent activity.
 
![image](https://github.com/Azure/LogicAppsUX/assets/36072422/4e92b048-04f9-4506-a6e6-f309ff898e3e)

```
{
  "type": "ApiConnection",
  "inputs": {
    "host": {
      "connection": {
        "referenceName": "sharepointonline"
      }
    },
    "method": "post",
    "": "@{body('Populate_a_Microsoft_Word_template')}",
    "path": "/datasets/@{encodeURIComponent(encodeURIComponent(parameters('FlowForma-URL')))}/files",
    "queries": {
      "folderPath": "/Contract Templates",
      "name": "Test.docx",
      "queryParametersSingleEncoded": true
    }
  },
  "runAfter": {
    "Populate_a_Microsoft_Word_template": [
      "SUCCEEDED"
    ]
  },
  "runtimeConfiguration": {
    "contentTransfer": {
      "transferMode": "Chunked"
    }
  }
}
```
 
As workaround to the fix the issue, the dynamic code block needs to be modified to remove these characters {} so the is reference is:  `"body": "@body('Populate_a_Microsoft_Word_template')",`

We can reproduce this issue in the GA portal designer for standard logic app, but it works with the cx’s expected behavior in old UI - https://aka.ms/lafallback and consumption logic app in GA portal designer.

Could you please check if it is an issue of the GA designer? Could you please help fix it?

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#25092258

**Comment by Eric-B-Wu** [comment]
Is there any reason why you're using the expression token (fx) picker to insert a single object instead of just using the dynamic content token picker button (⚡)?

**Comment by WCMV** [comment]
I have the same issue when using the Create File action in the File System (managed) connector, I'm trying to write binary data to a file using base64ToBinary and the added curly braces do something that corrupts the binary data so the file can't be read. This only happens in the new ui, using the fallback ui seems to work fine as no brackets are added in.
