### ISSUE TITLE
Random pages attempt to open

### ISSUE THREAD

**Issue by rdejong-vos** [Azure/LogicAppsUX#3277]
### Describe the Bug with repro steps

1. Go to the designer for standard logic apps
2. Create the trigger 'When a new email arrives in a shared mailbox (V2)'
3. Attempt to enter any information

The browser shows a message after a few letters entered in any of the fields that changes will be discarded when you leave the page. this messages keeps showing up after 3-5 letters. 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_new_email_arrives_in_a_shared_mailbox_(V2)": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "office365"
            }
          },
          "method": "get",
          "path": "/v2/SharedMailbox/Mail/OnNewEmail",
          "queries": {
            "mailboxAddress": "vosautoma",
            "importance": "Any",
            "hasAttachments": false,
            "includeAttachments": false,
            "folderId": "Inbox"
          }
        },
        "recurrence": {
          "interval": 3,
          "frequency": "Minute"
        },
        "splitOn": "@triggerBody()?['value']"
      }
    }
  },
  "connectionReferences": {
    "office365": {
      "api": {
        "id": "/subscriptions/fb284090-2ed5-4688-850c-6db037b892cb/providers/Microsoft.Web/locations/westeurope/managedApis/office365"
      },
      "connection": {
        "id": "/subscriptions/fb284090-2ed5-4688-850c-6db037b892cb/resourceGroups/VGConnectors/providers/Microsoft.Web/connections/office365-7"
      },
      "connectionName": "office365-7",
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {}
}
```

### Browser

Chrome

AB#25096846

**Comment by Eric-B-Wu** [comment]
Hello @rdejong-vos, thanks for reporting this issue. This shouldn't be an issue with the designer, as the only way to trigger this dialog of "Your unsaved edits will be discarded." is to leave the page, which the designer has no way of doing. My guess is that there is something in the background on your device trying to close the page and thus is causing this to happen; however if you want more investigation, please follow the steps here: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#finding-your-session-id-or-portal-extension-version to find your sessionId and send it in the comments and I can do further investigation

**Comment by rdejong-vos** [comment]
Hello Eric,

Unfortunately, the suggested keyboard shortcut (ctrl+alt+D for windows) does nothing.
I did manage to find my session ID, but that's about all the information I can get from the 'info' section.

ac385d83ed0d4acdb85dc61709986459

**Comment by hartra344** [comment]
@rdejong-vos I'm not able to repro the issue on multiple machines I've tried. I also checked your session for any potential errors. The best guess I have is that you have a browser extension that is causing some sort of wierd interaction and unfortunately that's not a scenario we are able to support.

**Comment by rdejong-vos** [comment]
I have tested it using multiple browsers, turned off all extensions, booted a clean VM, all showed the same behavior. 
I will switch back to consumption logic apps, as this is not working.
