### ISSUE TITLE
Generate button does not save the map

### ISSUE THREAD

**Issue by alexzunigamsft** [Azure/LogicAppsUX#3301]
### Describe the Bug with repro steps

Currently "Generate" does not save the map as well. Keep "Save" as a separate gesture and update "Generate" to automatically save the map when generating the XSLT. 

### Version

v2.63

AB#25148609

**Comment by Elaina-Lee** [comment]
Tested and "generate" button works without "saving" (with .draft file generated). This was probably fixed.
