### ISSUE TITLE
Previous step data not showing variables from for-each loop

### ISSUE THREAD

**Issue by DinoSourcesRex** [Azure/LogicAppsUX#3308]
### Describe the Bug with repro steps

1. Create a trigger on "When a new email arrives"
2. Create a for-each control using `Attachments` as the input
3. Add any action (I used a simple if condition)

Observe that the for-each (attachment) is not available in the list.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Chrome Version 116.0.5845.188

AB#25161406

**Comment by rllyy97** [comment]
This is fixed in main but is yet to be released, we're aiming for the next release to finish rolling out by September 29th

**Comment by DinoSourcesRex** [comment]
Great to hear, thanks for the update and great work!
