### ISSUE TITLE
Logic Apps Standard - parameters from parameters.json are being copied into workflow.json

### ISSUE THREAD

**Issue by MrRosendahl** [Azure/LogicAppsUX#3314]
### Describe the Bug with repro steps

**Expected result**
Parameters only exist in the parameters.json.

**Actual result**
Parameters from the parameters.json are being copied into the workflow.json.

**Steps**
1. Create a new Azure Logic Apps project (Ctrl + Shift + P)
2. Create a stateful workflow (Stateful1)
3. Add a parameters.json file with 2 parameter
```json
{
  "parameterOne": {
    "type": "String",
    "value": "@appsetting('parameterOne')"
  },
  "parameterTwo": {
    "type": "String",
    "value": "@appsetting('parameterTwo')"
  }
}
```
4. Add the parameters to the local.settings.json:
```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "APP_KIND": "workflowapp",
    "ProjectDirectoryPath": "<THE_PATH>",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "parameterOne": "1",
    "parameterTwo": "2",
    "WORKFLOWS_SUBSCRIPTION_ID": ""
  }
}
```
5. Edit the workflow using the (right click) "Open Designer" 
6. Select "Skip for now" when prompted to use connectors... this step does not matter.
8. Add a Request trigger and a Response action which uses one of the parameters
9. Save, and close the designer
10. View the workflow.json
11. The parameter(s) are being copied into the workflow. **Not expected**.

### What type of Logic App Is this happening in?

Standard (VSCode)

##### Visual Studio Code
Version: 1.82.1 (user setup)
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:45:05.575Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "Http",
                "inputs": {
                    "statusCode": 200,
                    "body": {
                        "parameterOne": "@parameters('parameterOne')"
                    }
                },
                "runAfter": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "schema": {}
                }
            }
        },
        "parameters": {
            "parameterOne": {
                "type": "String",
                "value": "@appsetting('parameterOne')",
                "defaultValue": "@appsetting('parameterOne')"
            },
            "parameterTwo": {
                "type": "String",
                "value": "@appsetting('parameterTwo')",
                "defaultValue": "@appsetting('parameterTwo')"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![Screenshot 2023-09-14 084454](https://github.com/Azure/LogicAppsUX/assets/29914665/cf872ba9-6f79-4ef6-b258-e1ae4f7a85f7)

### Browser

Edge.

### Additional context

local.settings.json:
```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "APP_KIND": "workflowapp",
    "ProjectDirectoryPath": "c:\\Src\\Tmp\\paramtest",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "parameterOne": "1",
    "parameterTwo": "2",
    "WORKFLOWS_SUBSCRIPTION_ID": ""
  }
}
```

parameters.json
```json
{
  "parameterOne": {
    "type": "String",
    "value": "@appsetting('parameterOne')"
  },
  "parameterTwo": {
    "type": "String",
    "value": "@appsetting('parameterTwo')"
  }
}

```

AB#25165715

**Comment by rllyy97** [comment]
@ccastrotrejo This appears to be specific to VSCode, I was unable to reproduce in portal
