### ISSUE TITLE
ASE Standard Logic App creation at Portal unable to select existing App Service Plan.

### ISSUE THREAD

**Issue by LIYINDUO** [Azure/LogicAppsUX#3332]
### Describe the Bug with repro steps

1. Try create ASE Standard Logic App in WestEurope region.
2. Review existing Standard LA in same region, note down their ASP name.
3. When creating the Standard Logic App at portal view. Select the same ASE, try find those ASP name in dropdown which were previously noted. 
4. Observe that the these ASPs are not there in the dropdown. Only option is to create a new ASP.

5. As a workaround, we had to place the ASP name manually and deploy via ARM template. 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
NA
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/19198958/3f0afcfb-b60c-41fc-8956-dd0da3b15b8c)

![image](https://github.com/Azure/LogicAppsUX/assets/19198958/cb6f1a04-0e68-4d39-b2d3-f131bcfe58af)

![image](https://github.com/Azure/LogicAppsUX/assets/19198958/fe6246c5-7083-489e-aa82-d573c48aa37b)

### Browser

Chrome

AB#25191028

**Comment by hartra344** [comment]
This should now be fixed with a hotfix that went out today
