### ISSUE TITLE
Designer - Not showing all In-App actions in Browse View

### ISSUE THREAD

**Issue by ccastrotrejo** [Azure/LogicAppsUX#3335]
#### `Azure Function Operations` only shows up in `In-App` action when user search it in the search bar

1. Add any trigger
2. Click on add action
3. Filter actions by `In-App` actions
4. Look for `Azure Function Operations`
5. Search for `Azure Function Operations`

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

#### Search view
<img width="800" alt="Screenshot 2023-09-11 at 9 18 18 AM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/c75ee9ca-de40-4f26-8437-e841823cb024">

#### Browse view
<img width="800" alt="Screenshot 2023-09-11 at 9 18 23 AM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/cc84725b-9c55-46af-9664-184a3ad50b3e">

### Browser

Edge

AB#25194462

**Comment by Serfenia** [comment]
I've also had this with service bus In-App triggers. When searching sometimes it only shows the 'peek-lock' version of 'When a message arrives in a topic subscription' or 'When a message arrives in a queue'

**Comment by preetriti1** [comment]
The one Carlos mentioned is issue in the API data received from backend. The connector - azure function and azure api management is missing "actions", triggers capabilities and only has azure connection. Once that is fixed non service providers would show up.

@Serfenia - Can you elaborate your issue little bit, in which view are you in, do you select any filters and do you put any search terms?
Please post screenshots on the issue you are observing here, if you want to open up a new issue that is also fine and we can keep this one open for backend issue.
