### ISSUE TITLE
Getting an error when saving condition not equal ""

### ISSUE THREAD

**Issue by tergar1** [Azure/LogicAppsUX#3344]
### Describe the Bug with repro steps

On an existing standard logic app.
In designer I get an error when saving for the below expression. Saving in code view does not give an error.

"expression": {
    "and": [
      {
        "not": {
          "equals": [
            "@triggerOutputs()['queries']?['InvoiceNumber']",
            ""
          ]

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

chrome Version 116.0.5845.188 (Official Build) (64-bit)

AB#25215573

**Comment by Eric-B-Wu** [comment]
@tergar1 thanks for reporting this issue. This was a case that wasn't considered when a user would want to compare for an empty string. Let me get a fix in for this and we'll have it in our next release.
