### ISSUE TITLE
Logic Apps Standard local development not working correctly when running on port other than 7071

### ISSUE THREAD

**Issue by karlrissland** [Azure/LogicAppsUX#3349]
### Describe the Bug with repro steps

Working with a Functions and a Logic App Standard solution in Visual Studio Code.  The Logic App calls the functions.  Configured the Logic App to run on port 7072 instead of port 7071 by updating the local.settings.json file by adding;

```  
"Host": {
    "LocalHttpPort": 7072,
    "CORS": "*"
  }
```
When I Debug/Attach to the Logic APp, everything runs without an issue, but when I try to open the Logic App Overview page by right clicking on the workflow definition, the overview takes a very long time to open and when it finally opens, it shows no info, just a red network error error message.

To repo, take any logic app standard, add the json above to your local.settings.json file.  Debug/attach to run the workflow locally, and try to open the overview page for the workflow definition file.

If for some reason it opens, verify that the workflow is indeed running on a port other than 7071.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
Any workflow can be used to reproduce the issue....
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/9871029/b24adbdf-65b5-4240-8b99-295cd0d46d90)

![image](https://github.com/Azure/LogicAppsUX/assets/9871029/bf5156aa-293c-4e6e-90b4-f278bb4316a9)

### Browser

I have Edge and Safari installed, but neither are used to reproduce the problem.

AB#25221975

**Comment by ccastrotrejo** [comment]
Hi @karlrissland, thank you for raising this issue. I took a look at this and I wasn't able to attach to a different port with the Host property in the settings.json inside the workflow-design-time folder. However I was able to attach it to a different port using the tasks.json in the .vscode folder by modifying the host start process. Could you please give it a try and see if this works?
<img width="646" alt="Screenshot 2023-10-16 at 11 46 33 AM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/0d1e8d94-5299-47d7-bf41-686fbed3bd16">
