### ISSUE TITLE
Standard: When a HTTP request is received trigger up/down scroll should align well.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3354]
### Describe the Bug with repro steps

1. Create a logic app in Standard SKU in any resource group (or use existing)
2.  In workflows, create a stateful workflow
3. In designer, create a workflow with a manual request trigger (i.e. "When an HTTP Request is Received)
4.  Click on the trigger
5. In parameters tab, select both checkboxes "Method" and "RelativePath"

**Expected:**Should be able to scroll down and select the Advanced parameters options as expected.
**Actual:**Unable to scroll Up/Down and Scrollbar is not in fit view. Unable to see the Advanced parameters options as up and down scroll bar is not in fit view. Once clicked on the Advanced parameters options options are getting poped up.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
  "type": "Request",
  "kind": "Http"
}
```

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/113517384/c7c4c4d5-6e3a-46b9-b23a-5979cd94c034

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/35faaf0d-2327-4fb5-9ace-2f1330891c77)

### Browser

Edge

### Additional context

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C68ab59c4b7564a18677208dbba3c2567%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638308539765819678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TtcxIdxVmlhjJxK%2BDedtWPm%2BfH3wPijHfdM5ainwuus%3D&reserved=0)
**Version:** 2.30920.1.1

AB#25228062

**Comment by Eric-B-Wu** [comment]
This is fixed, we will try to hotfix it end of day today

**Comment by vgouth** [comment]
Issue **not** repro in the latest request 

**Environment Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ceaee76e160324b6f523208dbca66fded%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638326316037127334%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EP07Z2WQZ1vXSGHMyMBqnfnPPTQI0iVlg9iiD85SIx8%3D&reserved=0)
**Version:** 2.31010.1.1
