### ISSUE TITLE
Standard_ Workflow parameters : Edit in JSON' link not found at the bottom of the parameters panel.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3355]
### Describe the Bug with repro steps

1.Create a new stateful logic app in standard, open the designer.
2.Validate if 'Parameters' command button shows
3.Add some parameters, save and run it.
4.**Expected:** Click on the link 'Edit in JSON', found at the bottom of the parameters panel.
**Actual:'** Edit in JSON' link not found at the bottom of the parameters panel

**Note:** Issue resolved in the last request with the bug (https://github.com/Azure/LogicAppsUX/issues/2228) but similar issue repro again.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Compose": {
        "type": "Compose",
        "inputs": "abc",
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {},
  "parameters": {
    "a": {
      "type": "Array",
      "value": [
        1,
        2
      ]
    },
    "b": {
      "type": "Bool",
      "value": false
    },
    "c": {
      "type": "Int",
      "value": 123
    },
    "d": {
      "type": "Float",
      "value": 0.7
    },
    "e": {
      "type": "String",
      "value": "mani"
    },
    "f": {
      "type": "Object",
      "value": {
        "Member": {
          "Email": "v-govubilish@microsoft.com",
          "First Name": "Manikanta",
          "Last Name": "VG"
        }
      }
    }
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/7e528048-b90d-45a7-966f-706d78beec76)

### Browser

Edge

### Additional context

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C68ab59c4b7564a18677208dbba3c2567%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638308539765819678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TtcxIdxVmlhjJxK%2BDedtWPm%2BfH3wPijHfdM5ainwuus%3D&reserved=0)
**Version:** 2.30920.1.1

AB#25228761

**Comment by rllyy97** [comment]
This is just a result of the height bug here https://github.com/Azure/LogicAppsUX/issues/3354
The component is still there it's just off the bottom of the screen.  Will use the other issue for tracking since it will be fixed with the same work.

**Comment by vgouth** [comment]
Issue **not** repro in the latest request 

**Environment Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ceaee76e160324b6f523208dbca66fded%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638326316037127334%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EP07Z2WQZ1vXSGHMyMBqnfnPPTQI0iVlg9iiD85SIx8%3D&reserved=0)
**Version:** 2.31010.1.1
