### ISSUE TITLE
Standard: Overview Blade identifier Unable to scroll Up/Down in Get started tab.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3357]
### Describe the Bug with repro steps

1.Go to overview page of standard logic app.
2.Click on Get started tab

**Actual:** Unable to scroll Up/Down in Get started tab.

**Expected:** Should be able to scroll Up/Down in Get started tab.as expected.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/113517384/70a8a536-5169-44b2-930b-3e875ddf5b52

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/9598506b-12b9-453e-b774-5f21dc1b8c0a)

### Browser

Edge

### Additional context

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccca98895e6274fbb769108dbba700e57%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638308762705108168%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=akKqCaBDOSZD4yuif5NhTE8JoynosjefRJijkHQYco0%3D&reserved=0)
**Version:** 2.30920.1.1

AB#25231133

**Comment by hartra344** [comment]
fixed
