### ISSUE TITLE
Standard: Overview Blade identifier Should be able to see more run history details on screen.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3358]
### Describe the Bug with repro steps

1.Go to overview page of standard logic app.
2.Click on Run history tab.

**Actual:** Able to see less run history details on screen but there is an option of scrolling down the run history.

**Expected:** Should be able to see more run history details on screen.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/a4f874d5-11e2-4c88-88b2-4f31631b7f89)

### Browser

Edge

### Additional context

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccca98895e6274fbb769108dbba700e57%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638308762705108168%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=akKqCaBDOSZD4yuif5NhTE8JoynosjefRJijkHQYco0%3D&reserved=0)
**Version:** 2.30920.1.1

AB#25231337

**Comment by hartra344** [comment]
@vgouth was your screen height short? If so then this is by design.

**Comment by vgouth** [comment]
@hartra344 No, Travis, Screen size is not short.

**Comment by hartra344** [comment]
@vgouth What is the pixel height then? because it looks very short? To Immitate your view I have to have the blade down to 650 pixels height, at which point it might be a good idea to collapse the essentials because with the essentials open, it leaves only 210 pixels of height for the run history table.

**Comment by vgouth** [comment]
@hartra344 
Previously there was 2 scrolling bars beside run history blade. Now there is only one scrolling bar which is only for run details not for entire run history blade. Previously we are able to see 3-4 runs at a time without scrolling but now we are able to see only one run details. I can see the height as 170.
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/9f1577fa-a773-40a1-8281-82286d43458a)

**Comment by hartra344** [comment]
This is by design to make the run history take the full window where previously it would always show 3-7 runs no matter the window size. I made a change today that should improve this behavior though on super small screen heights.
