### ISSUE TITLE
[@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "gl-ES" in Intl.NumberFormat

### ISSUE THREAD

**Issue by Ram-G** [Azure/LogicAppsUX#3361]
### Describe the Bug with repro steps 

1. Open v3 designer in Power Automate. 
2. Change language to "galego" (gl-ES). 
3. Observe error banner at the top of the screen. 

Expected:

 Designer loads successfully.

Actual:

 Designer fails to load and error banner is displayed with the following message:

Produciuse un erro ao renderizar [@formatjs/intl Error MISSING\_DATA] Missing locale data for locale: "gl-ES" in Intl.NumberFormat. Using default locale: "gl-ES" as fallback. See [https://formatjs.io/docs/react-intl#runtime-requirements](<https://formatjs.io/docs/react-intl#runtime-requirements>) for more details

### What type of Logic App Is this happening in? 

Power Automate

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/10837129/c040497b-3be5-48f4-ab2d-da22cd61e8f3>)

### Browser 

Edge

### Additional context 

In parallel to filing this issue, I am creating a pull request to put in a stopgap fix to not throw error for this missing locale data. This means the designer loads, just with some english (or other fallback) text strings instead of in the desired language.

Stack trace I got for the error from code -- libs\designer\src\lib\core\DesignerProvider.tsx line 36:

{

 "code": "MISSING\_DATA"

 }

"[@formatjs/intl Error MISSING\_DATA] Missing locale data for locale: \"gl-ES\" in Intl.NumberFormat. Using default locale: \"gl-ES\" as fallback. See [https://formatjs.io/docs/react-intl#runtime-requirements](<https://formatjs.io/docs/react-intl#runtime-requirements>) for more details\n"

"Error: [@formatjs/intl Error MISSING\_DATA] Missing locale data for locale: \"gl-ES\" in Intl.NumberFormat. Using default locale: \"gl-ES\" as fallback. See [https://formatjs.io/docs/react-intl#runtime-requirements](<https://formatjs.io/docs/react-intl#runtime-requirements>) for more details\n\n at new MissingDataError ([https://local.flow.microsoft.com:44300/static/js/60.1d4c7473758b67afd2d6.chunk.js:466834:23)\n](<https://local.flow.microsoft.com:44300/static/js/60.1d4c7473758b67afd2d6.chunk.js:466834:23%29%5cn>) at createIntl ([https://local.flow.microsoft.com:44300/static/js/60.1d4c7473758b67afd2d6.chunk.js:466571:17)\n](<https://local.flow.microsoft.com:44300/static/js/60.1d4c7473758b67afd2d6.chunk.js:466571:17%29%5cn>) at createIntl ([https://local.flow.microsoft.com:44300/static/js/60.1d4c7473758b67afd2d6.chunk.js:702532:85)\n](<https://local.flow.microsoft.com:44300/static/js/60.1d4c7473758b67afd2d6.chunk.js:702532:85%29%5cn>) at new IntlProvider ([https://local.flow.microsoft.com:44300/static/js/60.1d4c7473758b67afd2d6.chunk.js:702557:19)\n](<https://local.flow.microsoft.com:44300/static/js/60.1d4c7473758b67afd2d6.chunk.js:702557:19%29%5cn>) at constructClassInstance ([https://local.flow.microsoft.com:44300/static/js/bundle.js:246245:18)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:246245:18%29%5cn>) at updateClassComponent ([https://local.flow.microsoft.com:44300/static/js/bundle.js:250465:5)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:250465:5%29%5cn>) at beginWork ([https://local.flow.microsoft.com:44300/static/js/bundle.js:251985:16)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:251985:16%29%5cn>) at beginWork$1 ([https://local.flow.microsoft.com:44300/static/js/bundle.js:256544:14)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:256544:14%29%5cn>) at performUnitOfWork ([https://local.flow.microsoft.com:44300/static/js/bundle.js:255519:12)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:255519:12%29%5cn>) at workLoopSync ([https://local.flow.microsoft.com:44300/static/js/bundle.js:255495:22)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:255495:22%29%5cn>) at performSyncWorkOnRoot ([https://local.flow.microsoft.com:44300/static/js/bundle.js:255121:9)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:255121:9%29%5cn>) at [https://local.flow.microsoft.com:44300/static/js/bundle.js:244454:24\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:244454:24%5cn>) at unstable\_runWithPriority ([https://local.flow.microsoft.com:44300/static/js/bundle.js:271334:12)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:271334:12%29%5cn>) at runWithPriority$1 ([https://local.flow.microsoft.com:44300/static/js/bundle.js:244404:10)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:244404:10%29%5cn>) at flushSyncCallbackQueueImpl ([https://local.flow.microsoft.com:44300/static/js/bundle.js:244449:7)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:244449:7%29%5cn>) at flushSyncCallbackQueue ([https://local.flow.microsoft.com:44300/static/js/bundle.js:244437:3)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:244437:3%29%5cn>) at batchedUpdates$1 ([https://local.flow.microsoft.com:44300/static/js/bundle.js:255227:7)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:255227:7%29%5cn>) at reactionScheduler ([https://local.flow.microsoft.com:44300/static/js/bundle.js:227726:47)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:227726:47%29%5cn>) at runReactions ([https://local.flow.microsoft.com:44300/static/js/bundle.js:227702:5)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:227702:5%29%5cn>) at endBatch ([https://local.flow.microsoft.com:44300/static/js/bundle.js:227401:9)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:227401:9%29%5cn>) at \_endAction ([https://local.flow.microsoft.com:44300/static/js/bundle.js:226787:5)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:226787:5%29%5cn>) at executeAction ([https://local.flow.microsoft.com:44300/static/js/bundle.js:226741:9)\n](<https://local.flow.microsoft.com:44300/static/js/bundle.js:226741:9%29%5cn>) at onOperationResolved (https://local.flow.microsoft.com:44300/static/js/bundle.js:226721:16)"

AB#25236150

**Comment by hartra344** [comment]
I don't think this is an Azure supported locale, please get a list of these and I'll see if I can add them to our localization pipeline.

**Comment by ek68794998** [comment]
@hartra344 I believe this should be our full list of locales. We do get users from other locales as well, but this is the full list that we have localized resources for. We do definitely want to keep the fallback logic that was added in #3362 though, so that if we add a new locale, it doesn't suddenly start crashing the designer.

- `bg-BG`
- `ca-ES`
- `cs-CZ`
- `da-DK`
- `de-DE`
- `el-GR`
- `en-US`
- `es-ES`
- `et-EE`
- `eu-ES`
- `fi-FI`
- `fr-FR`
- `gl-ES`
- `hi-IN`
- `hr-HR`
- `hu-HU`
- `id-ID`
- `it-IT`
- `ja-JP`
- `kk-KZ`
- `ko-KR`
- `lt-LT`
- `lv-LV`
- `ms-MY`
- `nb-NO`
- `nl-NL`
- `pl-PL`
- `pt-BR`
- `pt-PT`
- `ro-RO`
- `ru-RU`
- `sk-SK`
- `sl-SI`
- `sr-Cyrl-RS`
- `sr-Latn-RS`
- `sv-SE`
- `th-TH`
- `tr-TR`
- `uk-UA`
- `vi-VN`
- `zh-CN`
- `zh-TW`

**Comment by rllyy97** [comment]
Closing, PA issue.
