### ISSUE TITLE
Can only see 3 runs on run history page without scrolling.

### ISSUE THREAD

**Issue by mbrimble** [Azure/LogicAppsUX#3401]
### Describe the Bug with repro steps

1. Open a Logic app blade.
2. View run history

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

Old Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/26989505/a59d1359-2c4f-4ccb-8c05-9ed532333d8f)

### Browser

Chrome

### Additional context

Can we see more run history without scrolling?

AB#25340762

**Comment by hartra344** [comment]
@mbrimble if you don’t need to see it, once way you can show a lot more rows here is to collapse the “essential” pane which for your screen size appears to be taking about 25% of your real estate

**Comment by mbrimble** [comment]
Thanks I learnt something
