### ISSUE TITLE
"ResizeObserver loop completed with undelivered notifications." Console error

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#3409]
### Describe the Bug with repro steps 

We have received automated reports of a high count of console errors stating

`ResizeObserver loop completed with undelivered notifications.`

According to the error docs: [https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#:\~:text=ResizeObserver%20loop%20completed%20with%20undelivered%20notifications](<https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#:~:text=ResizeObserver%20loop%20completed%20with%20undelivered%20notifications>).

 since this is not happening until a crash / infinitely, it does not seem to be a functionality-impacting issue

 Also this appears to have only occurred on version 2.30828.1.9, we have yet to run into it on our current release, so it may have been version-specific

Logging it here just for tracking purposes.

AB#25366537

**Comment by Eric-B-Wu** [comment]
Going to reopen this issue, as it still occurs and it is one of the larger livesite errors

**Comment by hartra344** [comment]
@Eric-B-Wu If we see it as a big enough issue to keep the issue open, we should priortize getting it fixed. If it's just an issue we're using as a reminder but never plan to look at then it's not worth keeping open. (We get plenty of reminders from the error log)

**Comment by Eric-B-Wu** [comment]
I think we've only put it on hold because its non-customer impacting; however it does make a lot of noise, hiding some top errors we should be seeing on our LSI's. I'll take this one and see if I can repro to close

**Comment by hartra344** [comment]
I just did a pass through of our errors, I'm not seeing meaningful numbers of this error anymore.
