### ISSUE TITLE
cannot find a run id which has 3 characters followed by CU

### ISSUE THREAD

**Issue by Nikhil1169** [Azure/LogicAppsUX#3412]
### Describe the Bug with repro steps

In any logic app consumption in West Europe region, when i try to search for an identifier it says 'Enter a valid run id'. The issue seems to be for identifiers with more than 2 characters after xxxxxxxxCU. Example:- let's say there's a run id:- 08585051102211360065526276549CU197 has 3 numbers after CU i.e 197, even though this is present in run history we cannot find it, while if the run id was 08585051102211360065526276549CU19, only 2 character followed by CU this would have found it.

For now i couldn't find any run id in any other region with 3 characters after CU hence was only able to repro this issue in West Europe logic apps

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

)

### Browser

Edge, Chrome

AB#25371947

**Comment by rllyy97** [comment]
A fix for this has been merged to main, will also be hotfixing later today.
