### ISSUE TITLE
Filter Array expression not showing correctly in new UI of Standard Logic Apps

### ISSUE THREAD

**Issue by nidubey1** [Azure/LogicAppsUX#3414]
### Describe the Bug with repro steps

1. Create a Standard Logic Apps workflow and add a Filter array expression with either a contains clause or the greater than clause as below and then save it:

contains clause->
<img width="812" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/85997053/aa1f788f-f50a-4f71-a3d7-e3eb3929063f">

greater than clause->

<img width="815" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/85997053/83e5656e-abf2-414c-952a-e7815ab9a554">

2. Now go back to some other tab and come back to designer tab an click on the Filter array actions, there we observe that Filter query parameter only shows in advanced mode and it shows an unusual expression and the Edit basic mode is disabled:

contains clause UI:

![image](https://github.com/Azure/LogicAppsUX/assets/85997053/d2239bb1-3364-417f-a261-e31ca11a1393)

greater than clause UI:

![image](https://github.com/Azure/LogicAppsUX/assets/85997053/92165af3-fff8-4ffc-a5f7-9d7130d2cc5c)

3. However the code view looks fine as well as the run time works fine, also the fall back url shows correct UI: "https://aka.ms/lafallback". Issue is only with new UI.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Seems in all, checked Chrome and edge.

AB#25378158

**Comment by nidubey1** [comment]
Hi @Eric-B-Wu , can you please confirm when the fix will be deployed in all regions? And if you can also confirm on an ETA specific to "southeastasia"?

**Comment by Eric-B-Wu** [comment]
This will be released to all regions by 10/20. Southeast Asia will also be 10/20
