### ISSUE TITLE
HTTP + Swagger Authentication Issues #2

### ISSUE THREAD

**Issue by lachlan-wernert** [Azure/LogicAppsUX#3415]
### Describe the Bug with repro steps

1. Add authentication parameter to HTTP + Swagger action 
2. Set to 'Managed Identity' and save workflow
3. Reload page and notice the 'Managed Identity' parameter is no longer on the action
4. Save workflow and view code, no authentication saved within the code as it wasn't present in the designer

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

**Code after adding authentication and saving**
![image](https://github.com/Azure/LogicAppsUX/assets/142757545/6e68805a-f39c-44f0-92aa-df88644d4df9)

**Designer after adding authentication and saving and reloading page**
![image](https://github.com/Azure/LogicAppsUX/assets/142757545/b3e9ebf6-01e6-48d1-b203-53f12d9ac46c)

**Code after saving, after reloading the page**
![image](https://github.com/Azure/LogicAppsUX/assets/142757545/dcc5ca08-3d8d-4f55-a5b7-362428aa351f)

### Browser

Chrome, Firefox, Edge

### Additional context

The initial issue of saving the authentication parameter has been fixed, but now the designer doesn't load the authentication parameter after saving.

AB#25381617

**Comment by Eric-B-Wu** [comment]
Hi @lachlan-wernert thanks for reporting this issue, it seems this problem has been fixed; however, the fix had missed our last release cycle. We expect this to come in our next release, which we'd expect to complete in all regions by 10/20.  I'll close this issue for now, but if it still happens after the ETA above, we can reopen it for further examination.

**Comment by lachlan-wernert** [comment]
No worries, thanks for the update!
