### ISSUE TITLE
Unable to test mapping get error The .NET framework worker could not be found.

### ISSUE THREAD

**Issue by ScottMcD87** [Azure/LogicAppsUX#3421]
### Describe the Bug with repro steps

Create map Json -> Json, clicked generate, then test. Added a test json object and clicked test and received the following error in the output section. 

Status code
400 - BadRequest: The .NET framework worker could not be found.

I'm running a Mac and I have the latest version .net core. 

### Screenshots or Videos

<img width="1014" alt="Screenshot 2023-10-07 at 08 22 00" src="https://github.com/Azure/LogicAppsUX/assets/58830044/39300a0e-9577-4a24-a895-b7113e4d2ac2">
<img width="472" alt="Screenshot 2023-10-07 at 08 23 39" src="https://github.com/Azure/LogicAppsUX/assets/58830044/4ea3f504-9ef1-486b-81ef-02126c8a57d7">
<img width="772" alt="Screenshot 2023-10-07 at 08 26 35" src="https://github.com/Azure/LogicAppsUX/assets/58830044/827be0b6-6340-4f1e-9258-253ecddf31ca">

### Version

2.70.1

AB#25392274

**Comment by hartra344** [comment]
This feature is unfortunately not available on Mac today(at least the test functionality isn't). The runtime takes dependency on a library that is only available in .NET Framework (note, this is not .NET Core which would be cross platform). 

You can see it under limitation here: https://techcommunity.microsoft.com/t5/azure-integration-services-blog/announcement-azure-logic-apps-new-data-mapper-for-visual-studio/ba-p/3777138

This is something we hope we are able to enable in the future.
