### ISSUE TITLE
Disable static result should be reworded to Enable static result

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#3424]
### Describe the Bug with repro steps

Navigate to Testing tab of an action. Notice it says Disable static outputs with toggle off which gives a sense that it is enabled by default (not true). Lets follow v1 designer pattern and change the wording to Enable static outputs.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25408898

**Comment by Eric-B-Wu** [comment]
Will be fixed in our 10/27 release
