### ISSUE TITLE
(Consumption) New Logic Apps Runs History UI bugs

### ISSUE THREAD

**Issue by harris-kristanto** [Azure/LogicAppsUX#3425]
### Describe the Bug with repro steps

Hey team, I wanted to report these two items on the recently updated "Runs history" view on Logic Apps consumption:

1. The Status filter doesn't seem to be highlighted after you've selected a status, the filtering still works when you click Apply, so looks to be a UI issue.
![image](https://github.com/Azure/LogicAppsUX/assets/19896873/1bece484-c4aa-456a-9db4-a79ec60578ae)

2. The "Start time" column in the runs history doesn't seem to pick up the region format that we selected on Azure Subscription level, i.e. in the screenshot below it is still displaying as US time format, even though I have selected the NZ one, if I go to the old Run History view, it works okay.
![image](https://github.com/Azure/LogicAppsUX/assets/19896873/1d0591cc-1296-4d8e-8833-d3a6d1333f65)
![image](https://github.com/Azure/LogicAppsUX/assets/19896873/fdc29883-9e2c-4397-ab87-77426225383d)

Could you please look into this?

Thanks
Harris

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome and Edge

**Comment by lasyan3** [comment]
Also the new height of the rows is ridiculously high, please reduce it to matche the old design.

**Comment by hartra344** [comment]
@harris-kristanto I have a fix for your second point going in the next release, but for your first point, even your screen shot shows that it is highlighted. Is it more of a visibility issue with the color contrast? It's a common portal control so it's using default colors but I could see how the grey on white could make it so that there isn't enough of a contrast. I can see if it'll let me easily change it to something more contrasting.

**Comment by harris-kristanto** [comment]
Thanks @hartra344 ,

For some reason Snipping Tools does add the highlight, but in reality, it's not highlighted, please see the below screenshot:
![image](https://github.com/Azure/LogicAppsUX/assets/19896873/a0dddf80-d552-4de6-9591-3a92c10232a3)

I noticed that this only happen if you select a colour theme that is light (Azure, Blue, Light) but if you select the Dark colour, the highlight shows up:
![image](https://github.com/Azure/LogicAppsUX/assets/19896873/8e487465-1f00-4e30-9070-0995a9920941)

**Comment by hartra344** [comment]
I'm not actually able to repro it at all from my side. We're using a common Portal Control for this, I'm going to close here but put a bug into their backlog so they can take a look. Might be some CSS theming specificity mishap in that control but it's not something we directly write.

Also @lasyan3, the spacing will be greatly reduced in our next major release, probably a couple weeks.
