### ISSUE TITLE
HTML editor dropdowns for color selection of text and highlight don't get dismissed on blur

### ISSUE THREAD

**Issue by Aleks-gdb** [Azure/LogicAppsUX#3426]
### Describe the Bug with repro steps

1. Add an operation using the HTML editor, for example, Outlook's Send an Email V2.
2. Add text to the editor
3. Try to change the color of the text, open the text color selector and observe it doesn't dismiss on blur.
4. Try to highlight the text, open the highlight color selector and observe it doesn't dismiss on blur.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#25410387

**Comment by Eric-B-Wu** [comment]
Will be fixed in our 10/27 release
