### ISSUE TITLE
Schedule Summary box formatting on Dark scheme

### ISSUE THREAD

**Issue by maps-mike** [Azure/LogicAppsUX#3427]
### Describe the Bug with repro steps

1. Configure Azure Dark scheme
2. create new logic app
3. Add timer trigger & configure
4. Observe summary box - formatting is white text on white background.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
"triggers": {
      "Run_8_to_6_Mon-Fri": {
        "type": "Recurrence",
        "description": "",
        "recurrence": {
          "frequency": "Week",
          "interval": 1,
          "schedule": {
            "weekDays": [
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday"
            ],
            "hours": [
              "9",
              "10",
              "11",
              "12",
              "13",
              "14",
              "15",
              "16",
              "17",
              "18",
              "8"
            ],
            "minutes": [
              0
            ]
          },
          "timeZone": "GMT Standard Time"
        }
      }
    },
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/128395129/d19fb334-23fa-449a-9a44-8a62a52bf269)

### Browser

Edge

AB#25416126

**Comment by Eric-B-Wu** [comment]
Will be fixed in our 10/27 release
