### ISSUE TITLE
Null token input getting converted to string literal

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#3433]
### Describe the Bug with repro steps 

When you create an action with a `null` input token in the old designer directly, you see the right value - `@null`

 When you create an action in the new designer is when you get `@{null}`

This difference also occurs on other keywords like `true` and `false`

![image](<https://github.com/Azure/LogicAppsUX/assets/25409734/07e75c5c-8003-4b0d-b1c0-f4eee737a8a3>)

![image](<https://github.com/Azure/LogicAppsUX/assets/25409734/8d107e67-aa42-4145-a8df-1a5f5ce7928e>)

[https://portal.microsofticm.com/imp/v3/incidents/incident/424723241/summary](<https://portal.microsofticm.com/imp/v3/incidents/incident/424723241/summary>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

AB#25431297

**Comment by Eric-B-Wu** [comment]
@rllyy97 I'm seeing the same interaction between old/new designer - both when the parameter value is a single valuesegment resulting in @, and when its a nested object (ex dynamic data) or parameter value with  multiple valuesegments, resulting in @{}
