### ISSUE TITLE
Dropdown items are not sorted alphabetically in new designer 

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#3434]
### Describe the Bug with repro steps

![image](https://github.com/Azure/LogicAppsUX/assets/91279975/228d05f5-2e8a-482f-9a3d-e5314711c28e)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25431320

**Comment by Ryanb58** [comment]
Fixing on the side: 

https://github.com/Azure/LogicAppsUX/pull/3499

**Comment by Ryanb58** [comment]
Looks like my first run at the change was merged.

https://github.com/Azure/LogicAppsUX/pull/3499

Although, @Eric-B-Wu gave me some guidance in a comment about how we should move the sorting to a different area. Therefore, I started this new PR with the changes.

https://github.com/Azure/LogicAppsUX/pull/3582 

Still looking for a bit of guidance or clarity around one of the suggestions though.
