### ISSUE TITLE
Issue with Filter Array Action  - Filter Query not rendered correctly after changing VSCode Tab

### ISSUE THREAD

**Issue by axiomitdavid** [Azure/LogicAppsUX#3438]
### Describe the Bug with repro steps

1. Create new Standard Workflow with Compose to contain test array
2. Add Filter Array Action using item()?['array_element] in the "Choose a value" value field (Basic Mode)
![image](https://github.com/Azure/LogicAppsUX/assets/41350688/684fb179-b08f-4474-aa79-306d51c1610f)
3. Change to another VS Code tab and return to the workflow tab
4. Filter query has switched to Advanced mode with ?['array_element] 
![image](https://github.com/Azure/LogicAppsUX/assets/41350688/e3f38200-301d-4cf1-a2b7-dae30a4316b8)
5. Code View of the action appears to be correct
![image](https://github.com/Azure/LogicAppsUX/assets/41350688/0dae64f3-9733-4d1b-ae98-0ef3444c5c90)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose": {
                "type": "Compose",
                "inputs": [
                    {
                        "KeeperCompanyID": "1567",
                        "CWCompanyID": "19553"
                    },
                    {
                        "KeeperCompanyID": "1345",
                        "CWCompanyID": "19556"
                    }
                ],
                "runAfter": {}
            },
            "Filter_array": {
                "type": "Query",
                "inputs": {
                    "from": "@outputs('Compose')",
                    "where": "@equals(item()?['CWCompanyID'],19556)"
                },
                "runAfter": {
                    "Compose": [
                        "SUCCEEDED"
                    ]
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

See above

### Browser

VSCode Info

Version: 1.83.0
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:13:10.518Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

VSCode Designer Extension Ver 2.69.1

AB#25467963

**Comment by Eric-B-Wu** [comment]
Hi @axiomitdavid, thanks for catching this. We have this fixed in https://github.com/Azure/LogicAppsUX/issues/3414, which will be in all regions by 10/20
