### ISSUE TITLE
Filter Array action in new designer doesn't properly display expression

### ISSUE THREAD

**Issue by mafiallo** [Azure/LogicAppsUX#3440]
### Describe the Bug with repro steps

1. Create a new workflow with any trigger.
2. Add a _Compose_ step with the input: `{"content":[{"ID":12345}]}`
3. Add a _Filter array_ step with the following inputs:  **From** `@outputs('Compose')?['content']`  **Filter Query** `@equals(item()?['ID'],12345)`
4. Save workflow

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    },
    "actions": {
      "Compose": {
        "type": "Compose",
        "inputs": {
          "content": [
            {
              "ID": 12345
            }
          ]
        },
        "runAfter": {}
      },
      "Filter_array": {
        "type": "Query",
        "inputs": {
          "from": "@outputs('Compose')?['content']",
          "where": "@equals(item()?['ID'],12345)"
        },
        "runAfter": {
          "Compose": [
            "Succeeded"
          ]
        }
      }
    },
    "outputs": {},
    "parameters": {
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {}
    }
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/133984269/559ee61e-c02e-4ade-af67-bd503c74aca3)
![image](https://github.com/Azure/LogicAppsUX/assets/133984269/40abfc02-c440-44e8-a5ef-ee8e005b3da8)

### Browser

All browsers

### Additional context

-Only seems to occur from new designer. Also the expression displays properly from code view.
-Able to repro from both Consumption, Standard & Power Automate

AB#25471950

**Comment by Eric-B-Wu** [comment]
We will be hotfixing this - should be in all regions by EOD today
