### ISSUE TITLE
Create connection to ASB peek-lock trigger fails with 'Failed to create connection: Unknown error'

### ISSUE THREAD

**Issue by jeanpaulsmit** [Azure/LogicAppsUX#3446]
### Describe the Bug with repro steps 

1. Create new Logic App in VSCode 
2. Create Service bus "When messages are available in a queue (peek-lock)" trigger 
3. Specify name, type 'connectionstring' and populate that field 
4. Error shows up 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

n/a

### Additional context 

The error is not providing any information about the why, so not really helpful.

Actually, it reminds me of the infamous Sharepoint error 'an error occurred'.

I found out later that localauth on ASB was disabled, so it made sense it couldn't connect.

However, it would be much more helpful when the error would not say 'Unknown error' but a more descriptive one.

Maybe the VSCode extension receives some kind of 401, which could at least guide the dev in that direction.

AB#25485707

**Comment by jeanpaulsmit** [comment]
@rllyy97 thanks for getting back about this topic.
I just tested and there is no difference in response for me:
![image](https://github.com/Azure/LogicAppsUX/assets/10231104/44b15ecf-3565-4fff-8f42-42b88a4c39f3)

I'm using v3.0.3 of the extension, which I believe is the latest at the moment.

**Comment by rllyy97** [comment]
I did not investigate, reopening

**Comment by piyushpaliwal** [comment]
I am hitting the same issue but with "Send a message" action. Is there any workaround that we could potentially try while the team is working on fixing the issue? Maybe create the connection in portal and use that?

**Comment by Banchio** [comment]
I have same issue (screenshot below). Expectation here, by using Managed Identity, would be to use currently logged-on user in vs code while debugging locally and use Managed Identity while running in Logic App (similar to what happen when using DefaultAzureCredentials in dotnet). Is this correct?

![image](https://github.com/user-attachments/assets/1072fb3d-90f6-4050-a2ef-ba3467d7924c)

**Comment by Banchio** [comment]
I was able to go ahead by creating the connection manually in Azure logic apps and then pasting it in the connections.json file. My hope on the managed identity does not work unfortunately.

**Comment by MrRosendahl** [comment]
I got the same error "Failed to create connection: Unknown error" when creating an **In-app action** "Complete the message in a topic subscription" or a trigger for that matter. 

@rllyy97  **_The non In-app works._** So this is a Service bus In-app error.

**Comment by rllyy97** [comment]
Hi all, @ccastrotrejo and I will take a look at this issue soon, sorry you've had to wait so long, we'll check it out and let you know what we find soon!
