### ISSUE TITLE
Unable to upload file to Azure Devops using Logic App

### ISSUE THREAD

**Issue by bsvenki** [Azure/LogicAppsUX#3449]
### Describe the Bug with repro steps

Unable to upload file to Azure Devops using Logic App

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

chrome

AB#25491302

**Comment by hartra344** [comment]
Can you please provide some repro steps sow e can try to debug. There isn't much we can do from just this description.

**Comment by bsvenki** [comment]
Hi Travis

I am using azure logic app to connect to azue devops to create workitems.  When the email arrives the workitem should be created in devops with inline images that are in the body of the email

There is no issue in creating just a workitem but when i try to attach a file for workitem using "send a http request to azure devops" getting 404 not found error.  I searched in google some asked to convert attachment content to binary, I did so but no use. Also I have confirmed "Yes" for binary content.

Last 3 days struggling with this issue.  Request you to provide a solution for this issue. I appreciate.

Regards
Venkat
________________________________

**Comment by hartra344** [comment]
Ok so it sounds like this is an issue happening when the logic app is run, not in the UI right? If that’s the case I’ll go ahead and forward this to the team that works on that.

**Comment by bsvenki** [comment]
Thank you.

Regards
Venkat
________________________________

**Comment by bsvenki** [comment]
Travis,

I fixed the issue. you can ignore this issue.

Regards
Venkat
________________________________

**Comment by Eric-B-Wu** [comment]
will be closing this issue - as customer is resolved
