### ISSUE TITLE
Event Type Item not listing when using Event Grid Trigger in new designer of Logic App standard

### ISSUE THREAD

**Issue by saroja-sattigeri** [Azure/LogicAppsUX#3457]
### Describe the Bug with repro steps

Customer is trying to create a logic app to handle the key vault events, using the Event Grid Trigger (When a resource event occurs) in logic app standard however, event type item is not listing.

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/85295842/f5416c67-f2e1-4b8e-93d9-5add805bc665)

I've also tested at my end and could see same behavior in new designer where we need to hard code event type item(drop down does not show up) 

![Uploading image.png…]()

If we use old designer, we can choose event type items from drop down as below:

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/85295842/8483dbb9-4041-42c1-a953-60475b0eb31d)

Please check if any issue in new designer while showing up event type item or is it by design behavior?

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

NA

AB#25507607

**Comment by saroja-sattigeri** [comment]
Though for now, customer is using old designer however, they have deadline for production deployment hence, could you prioritize this or provide us with a timeline?
Observation: In new designer 'event type item' parameter is required parameter however, it's not the same in old designer

**Comment by rllyy97** [comment]
I've found a fix, working on getting it reviewed and merged.
