### ISSUE TITLE
Designer does not understand pasting expressions in the action fields 

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#3463]
### Describe the Bug with repro steps

•	Pasting in text that has expressions mixed in works pretty well in the old designer.  I'm adding error handling to my production flows, so lots of copy pasting.  When I have something like Action Name: @{items(‘Apply_to_each_varDebug’)?[‘name’]} and I paste it in to the old designer, it automatically knows that part of what I'm pasting is a formula and adjusts accordingly.  New designer isn't doing that.  Worse, when I'm trying to work with a URL that has formulas as part of it ([https://make.powerautomate.com/environments/@{outputs('Compose_-_Get_Workflow_Details')?['tags']?['environmentName']}/flows/@{outputs('Compose_-_Get_Workflow_Details')?['name']}/runs/@{outputs('Compose_-_Get_Workflow_Details')?['run']?['name']}](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmake.powerautomate.com%2Fenvironments%2F%40%257Boutputs(%27Compose_-_Get_Workflow_Details%27)%3F%5B%27tags%27%5D%3F%5B%27environmentName%27%5D%257D%2Fflows%2F%40%257Boutputs(%27Compose_-_Get_Workflow_Details%27)%3F%5B%27name%27%5D%257D%2Fruns%2F%40%257Boutputs(%27Compose_-_Get_Workflow_Details%27)%3F%5B%27run%27%5D%3F%5B%27name%27%5D%257D&data=05%7C01%7CKishor.Subedi%40microsoft.com%7Cce3082affcbc4c88de9c08dbcf50220a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638331715332316407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cPvRQgaZoEpctsoZV6EA0Mj4zV68D69IaBYBay2H84s%3D&reserved=0)), the backslashes keep getting deleted when I'm trying to go edit and turn the formula sections into formulas, which is very annoying.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25515947

**Comment by hartra344** [comment]
Fixed by #3793

https://github.com/Azure/LogicAppsUX/assets/13208452/758bd516-be40-4c54-b9e5-8bd27645b64d
