### ISSUE TITLE
Token expires while editing in web designer

### ISSUE THREAD

**Issue by chriswatsonaus** [Azure/LogicAppsUX#3467]
### Describe the Bug with repro steps 

1. Open a workflow in the designer. 
2. Leave the workflow open for long enough for the auth token to expire 
3. Make a change and attempt to save. 

Result: Error: web token expired - can't save - lose changes. Refreshing the page gets a new token, but changes are lost.

 Desired: Expired token is detected and new token is obtained before attempting to save.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

AB#25519039

**Comment by meadows-st-Techlytical** [comment]
This is continuing to happen.  I had the (new) designer open for ~ 1 hour.

**Comment by hartra344** [comment]
Just an update: We're working with the core portal team to figure out the root cause of this. Will update when we hear something. The call we make to get the most up to date token is getting sent expired tokens after an hour of non use.
