### ISSUE TITLE
Overview Blade_Run history: Resubmit button missing only for first run in run history.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3482]
### Describe the Bug with repro steps

1.Create a logic app, add any workflow, save it and run it.
2.Open the Run history.
3.Select first run in run history.
4. Attempt to Right Click to show Resubmit Context Menu

**Expected:** Resubmit Context Menu Button should be present for first run as seen for all the other runs.
**Actual:** Resubmit button missing only for first run in run history.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/113517384/74b2c9ad-ca4f-4d44-b8ac-256220226e80

### Browser

Edge

### Additional context

**Environment Details:**

**Version:** 2.31010.1.3

AB#25536531

**Comment by Eric-B-Wu** [comment]
fixed in portal repo, expect to be released in 2 weeks

**Comment by Eric-B-Wu** [comment]
reopening to also fix in standard

**Comment by vgouth** [comment]
Issue repro in standard portal 

**Environmental Details:**
**Version:** 2.31108.1.1

https://github.com/Azure/LogicAppsUX/assets/113517384/ddaf4379-ea6e-4f79-971f-86ec47f56d17

**Comment by Eric-B-Wu** [comment]
I've fixed this now, should reflect in all stations by end of week
