### ISSUE TITLE
RunHistory Minor UI bug where Arrow button Moves based on invalid Error

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3483]
### Describe the Bug with repro steps

1.Open a created standard LA having run identifier.
2.Try to copy the identifier value and paste it in run identifier search box and make it as invalid identifier by giving some random text.
3. Note that the Arrow button gets moved downwards when the error validation message shows

**Expected:** UI for invalid identifier error shown should be fine.
**Actual:** There is change in UI for invalid run identifier error shown.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/113517384/83347e63-c7e8-45d4-9494-9043a977e53b

### Browser

Edge

### Additional context

**Environment Details:**

**Version:** 2.31010.1.3

AB#25536649

**Comment by Eric-B-Wu** [comment]
fixed in portal repo, expect to be released in 2 weeks
