### ISSUE TITLE
Unable to see run history contents after changing 'Trigger access option' back to default value 'Any IP'

### ISSUE THREAD

**Issue by karanbirsingh** [Azure/LogicAppsUX#3493]
### Describe the Bug with repro steps

1. Create a new consumption logic app with any simple trigger/action
2. Change workflow settings -> trigger access option to "Specific IP ranges"
3. Save
4. Change workflow settings -> trigger access option back to "Any IP"
5. Save
6. Observe the resource JSON still has "accessControl" node
7. Navigate to the logic app run history
8. Observe run history content error: "Unauthorized: Your IP is not in the access IP range, ..."

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

Old Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON
```
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Initialize_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "a",
                            "type": "boolean",
                            "value": true
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {
            "Recurrence": {
                "evaluatedRecurrence": {
                    "frequency": "Minute",
                    "interval": 3
                },
                "recurrence": {
                    "frequency": "Minute",
                    "interval": 3
                },
                "type": "Recurrence"
            }
        }
    },
    "parameters": {}
}
```

### Screenshots or Videos

![screenshot of run history](https://github.com/Azure/LogicAppsUX/assets/7775527/20726aa0-8c35-4098-8e52-1c7f57bc8579)

### Browser

Microsoft Edge for Business
Version 118.0.2088.57 (Official build) (64-bit)

### Additional context

internal, feel free to ping me on Teams

**Comment by Eric-B-Wu** [comment]
I've created a fix (in our portal-hosting respository) - it should be out in all regions by 11/3
