### ISSUE TITLE
Body of "reply email v3" that contains multiple dynamic contents converts all of them to the same one

### ISSUE THREAD

**Issue by FleeceOfGideon** [Azure/LogicAppsUX#3497]
Section of the code that is impacted:
![image](https://github.com/Azure/LogicAppsUX/assets/134652793/81e80c46-1ba9-4795-9027-8cd99228093e)

- having set the body of the email to:
`"Body": "<p><b><strong>NumBoleto of published XMLs:</strong></b></p><p>@{body('Join_NumBoleto')}</p><p><b><strong>Functional error messages:</strong></b></p><p>@{body('Join_errorMessages')}<span>\n</span></p><p><b><strong>Technical errors messages:</strong></b></p><p>@{body('Join_errors')}</p>"`

![image](https://github.com/Azure/LogicAppsUX/assets/134652793/97c9328d-6d21-4db2-86d9-976aac6f6208)

i.e. some text together with the output of 3 different nodes

- After going out out of the editor, having the trigger run, coming back to the editor, doing some other changes to the body of the email (text, unrelated to the outputs), it has reverted to an erroneous state where it became:
`"Body": "<p><b><strong>NumBoleto of published XMLs:</strong></b></p><p>@{body('Join_errors')}</p><p><b><strong>Functional error messages:</strong></b></p><p>@{body('Join_errors')}<span>\n</span></p><p><b><strong>Technical errors messages:</strong></b></p><p>@{body('Join_errors')}</p>"`

i.e. all of the outputs are now pointing to the output of the same node

I can't be sure if it is converting all outputs to the same or if it could be a caching thing, looks to me the former.

It is not a diplay thing either as the output of the processing comes out different (I receive an email with the wrong content)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#25554792

**Comment by Eric-B-Wu** [comment]
Thanks for reporting this issue, I've created a fix, which will be in our next release (will complete on all stations - ETA 11/3

**Comment by Eric-B-Wu** [comment]
This missed our release cycle, pushing back eta to 11/17

**Comment by FleeceOfGideon** [comment]
> This missed our release cycle, pushing back eta to 11/17

Could you confirm it has now been released?

**Comment by Eric-B-Wu** [comment]
yep this was released in our november deployment and should be in all regions
