### ISSUE TITLE
An attribute node (SEGMENT) cannot be created after a child of the containing element.

### ISSUE THREAD

**Issue by bankarswapnil** [Azure/LogicAppsUX#3503]
### Describe the Bug with repro steps

My requirement is to transform JSON to SAP IDoc using Data Mapper.
IDoc has elements with couple of attributes as shown below in sample IDoc, [BEGIN/SEGMENT etc]
Simple 1-1 mapping works well.
But as soon as I add functions, attribute specific lines get moved and then I see following exception when I run the test,

[2023-10-23T09:04:57.219Z] Error on line 23 column 51 
[2023-10-23T09:04:57.219Z]   XTDE0410  An attribute node (SEGMENT) cannot be created after a child of the containing
[2023-10-23T09:04:57.219Z]   element. Most recent element start tag was output at line 22 of module 
[2023-10-23T09:04:57.219Z]      invoked by xsl:for-each at #11
[2023-10-23T09:04:57.220Z]   In template rule with match="/" on line 7 of 
[2023-10-23T09:04:57.221Z]      invoked by xsl:apply-templates at #5
[2023-10-23T09:04:57.221Z]   In template rule with match="/" on line 3 of 
[2023-10-23T09:04:57.244Z] An error occurred while transforming the given input with the provided map. Details: 'An attribute node (SEGMENT) cannot be created after a child of the containing element. Most recent element start tag was output at line 22 of module '.
[2023-10-23T09:04:57.244Z] Result: An error occurred while transforming the given input with the provided map. Details: 'An attribute node (SEGMENT) cannot be created after a child of the containing element. Most recent element start tag was output at line 22 of module '.
Exception: Microsoft.Azure.Workflows.BuiltIn.Xslt.Common.Exceptions.ErrorResponseMessageException: An error occurred while transforming the given input with the provided map. Details: 'An attribute node (SEGMENT) cannot be created after a child of the containing element. Most recent element start tag was output at line 22 of module '.

Sample IDoc : 
-------------
<?xml version="1.0" encoding="UTF-8"?>
<EXCHANGE_RATE01>
   <IDOC BEGIN="1">
      <EDI_DC40 SEGMENT="1">
         <IDOCTYP>EXCHANGE_RATE01</IDOCTYP>
         <MESTYP>EXCHANGE_RATE</MESTYP>
         <SNDPOR>BOOMI</SNDPOR>
         <SNDPRT>LS</SNDPRT>
         <SNDPRN>BOOMI</SNDPRN>
         <RCVPOR/>
         <RCVPRT>LS</RCVPRT>
         <RCVPRN>PE1CLNT100</RCVPRN>
      </EDI_DC40>
      <E1EXCHANGE_RATE SEGMENT="1">
         <LOG_SYSTEM>BOOMIDEV</LOG_SYSTEM>
         <UPD_ALLOW>X</UPD_ALLOW>
         <CHG_FIXED>X</CHG_FIXED>
         <DEV_ALLOW>000</DEV_ALLOW>
         <E1BP1093_0 SEGMENT="1">
            <RATE_TYPE>M</RATE_TYPE>
            <FROM_CURR>EUR</FROM_CURR>
            <TO_CURRNCY>AED</TO_CURRNCY>
            <VALID_FROM>20231003</VALID_FROM>
            <EXCH_RATE>3.84598</EXCH_RATE>
            <FROM_FACTOR>1</FROM_FACTOR>
            <TO_FACTOR>1</TO_FACTOR>
         </E1BP1093_0>
      </E1EXCHANGE_RATE>
   </IDOC>
</EXCHANGE_RATE01>

### Screenshots or Videos

XSLT which is getting generated behind the scene and causing the given exception,

<xsl:stylesheet xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:math="http://www.w3.org/2005/xpath-functions/math" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dm="http://azure.workflow.datamapper" xmlns:ef="http://azure.workflow.datamapper.extensions" exclude-result-prefixes="xsl xs math dm ef" version="3.0" expand-text="yes">
  <xsl:output indent="yes" media-type="text/xml" method="xml" />
  <xsl:template match="/">
    <xsl:variable name="xmlinput" select="json-to-xml(/)" />
    <xsl:apply-templates select="$xmlinput" mode="azure.workflow.datamapper" />
  </xsl:template>
  <xsl:template match="/" mode="azure.workflow.datamapper">
    <EXCHANGE_RATE01>
      <IDOC>
        <E1EXCHANGE_RATE>
          <xsl:for-each select="/*/*[@key='quotes']/*">
            <E1BP1093_0>
              <xsl:choose>
                <xsl:when test="(*[@key='quote_currency']) != ('ISK')">
                  <E1BP1093_0>
                    <RATE_TYPE>{/*/*[@key='meta']/*[@key='endpoint']}</RATE_TYPE>
                    <FROM_CURR>{*[@key='base_currency']}</FROM_CURR>
                    <TO_CURRNCY>{*[@key='quote_currency']}</TO_CURRNCY>
                    <VALID_FROM>{*[@key='start_time']}</VALID_FROM>
                    <EXCH_RATE>{*[@key='average_midpoint']}</EXCH_RATE>
                    <xsl:attribute name="SEGMENT">{'1'}</xsl:attribute>
                    <FROM_FACTOR>{'1'}</FROM_FACTOR>
                    <TO_FACTOR>{'1'}</TO_FACTOR>
                  </E1BP1093_0>
                </xsl:when>
              </xsl:choose>
            </E1BP1093_0>
          </xsl:for-each>
          <xsl:attribute name="SEGMENT">{'1'}</xsl:attribute>
          <LOG_SYSTEM>{'BOOMIDEV'}</LOG_SYSTEM>
          <UPD_ALLOW>{'X'}</UPD_ALLOW>
          <CHG_FIXED>{'X'}</CHG_FIXED>
          <DEV_ALLOW>{'000'}</DEV_ALLOW>
        </E1EXCHANGE_RATE>
        <xsl:attribute name="BEGIN">{'1'}</xsl:attribute>
        <EDI_DC40>
          <xsl:attribute name="SEGMENT">{'1'}</xsl:attribute>
          <IDOCTYP>{'EXCHANGE_RATE01'}</IDOCTYP>
          <MESTYP>{'EXCHANGE_RATE'}</MESTYP>
          <SNDPOR>{'BOOMI'}</SNDPOR>
          <SNDPRT>{'LS'}</SNDPRT>
          <SNDPRN>{'BOOMI'}</SNDPRN>
          <RCVPOR>{''}</RCVPOR>
          <RCVPRT>{'LS'}</RCVPRT>
          <RCVPRN>{'PE1CLNT100'}</RCVPRN>
        </EDI_DC40>
      </IDOC>
    </EXCHANGE_RATE01>
  </xsl:template>
</xsl:stylesheet>

### Version

Data Mapper : [2.70.1](https://github.com/Azure/LogicAppsUX/compare/v2.70.0...v2.70.1) (2023-09-22)

### Additional context

Work around 👍 
Adjust the Attribute specific lines at the start of the node respectively in XSLT as shown below and save it.
But now do not Generate XSLT using given option else it will again disturb the xslt.
Then if you run test, it works

Corrected XSLT : 
----------------
<xsl:stylesheet xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:math="http://www.w3.org/2005/xpath-functions/math" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dm="http://azure.workflow.datamapper" xmlns:ef="http://azure.workflow.datamapper.extensions" exclude-result-prefixes="xsl xs math dm ef" version="3.0" expand-text="yes">
  <xsl:output indent="yes" media-type="text/xml" method="xml" />
  <xsl:template match="/">
    <xsl:variable name="xmlinput" select="json-to-xml(/)" />
    <xsl:apply-templates select="$xmlinput" mode="azure.workflow.datamapper" />
  </xsl:template>
  <xsl:template match="/" mode="azure.workflow.datamapper">
    <EXCHANGE_RATE01>
      <IDOC>
        <xsl:attribute name="BEGIN">{'1'}</xsl:attribute>
        <E1EXCHANGE_RATE>
          <xsl:attribute name="SEGMENT">{'1'}</xsl:attribute>
          <xsl:for-each select="/*/*[@key='quotes']/*">
            <E1BP1093_0>
              <xsl:choose>
                <xsl:when test="(*[@key='quote_currency']) != ('ISK')">
                  <E1BP1093_0>
                    <xsl:attribute name="SEGMENT">{'1'}</xsl:attribute>
                    <RATE_TYPE>{/*/*[@key='meta']/*[@key='endpoint']}</RATE_TYPE>
                    <FROM_CURR>{*[@key='base_currency']}</FROM_CURR>
                    <TO_CURRNCY>{*[@key='quote_currency']}</TO_CURRNCY>
                    <VALID_FROM>{*[@key='start_time']}</VALID_FROM>
                    <EXCH_RATE>{*[@key='average_midpoint']}</EXCH_RATE>
                    <FROM_FACTOR>{'1'}</FROM_FACTOR>
                    <TO_FACTOR>{'1'}</TO_FACTOR>
                  </E1BP1093_0>
                </xsl:when>
              </xsl:choose>
            </E1BP1093_0>
          </xsl:for-each>
          <LOG_SYSTEM>{'BOOMIDEV'}</LOG_SYSTEM>
          <UPD_ALLOW>{'X'}</UPD_ALLOW>
          <CHG_FIXED>{'X'}</CHG_FIXED>
          <DEV_ALLOW>{'000'}</DEV_ALLOW>
        </E1EXCHANGE_RATE>
        <EDI_DC40>
          <xsl:attribute name="SEGMENT">{'1'}</xsl:attribute>
          <IDOCTYP>{'EXCHANGE_RATE01'}</IDOCTYP>
          <MESTYP>{'EXCHANGE_RATE'}</MESTYP>
          <SNDPOR>{'BOOMI'}</SNDPOR>
          <SNDPRT>{'LS'}</SNDPRT>
          <SNDPRN>{'BOOMI'}</SNDPRN>
          <RCVPOR>{''}</RCVPOR>
          <RCVPRT>{'LS'}</RCVPRT>
          <RCVPRN>{'PE1CLNT100'}</RCVPRN>
        </EDI_DC40>
      </IDOC>
    </EXCHANGE_RATE01>
  </xsl:template>
</xsl:stylesheet>

AB#25565252

**Comment by DanielleCogs** [comment]
Hello @bankarswapnil I can work with you to figure out this issue. First if possible could you upload the schemas you are using, and the generated LML? That will help us to diagnose where the problem is coming from. A screenshot of the area of the visual map where the xslt is breaking would be helpful too!
