### ISSUE TITLE
Unable to map different levels of nesting (AKA bug mapping EDIFACT message)

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#3516]
### Describe the Bug with repro steps

In the following screenshot, you can see I have an array called CNILoop1, then a child array called STSLoop1. Underneath STSLoop1is NADLoop2 and LOC_3, both at the same level directly under STSLoop1. When I try to map a value from each of these, the YAMl (and therefore the XSLT) thinks that both are under NADLoop2. Only NAD01 is under NADLoop2. 
 

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/83832436/7a065434-ffef-45d0-bb81-5dc20f3dba01)

![image](https://github.com/Azure/LogicAppsUX/assets/83832436/413a466d-cf44-4b15-a5c2-34073db7fa6f)

![image](https://github.com/Azure/LogicAppsUX/assets/83832436/0b093fa4-a787-4ef6-ad5a-4bb568723d98)

### Version

2.72

AB#25587805

**Comment by DanielleCogs** [comment]
Adding this screenshot that captures the whole issue in one photo
<img width="1660" alt="Screenshot 2023-10-30 at 2 22 32 PM" src="https://github.com/Azure/LogicAppsUX/assets/99753874/08c47dcf-eb57-4eb2-94f5-35f9e196916c">
