### ISSUE TITLE
DataMapper canvas is unable to render the saved mappings.

### ISSUE THREAD

**Issue by bankarswapnil** [Azure/LogicAppsUX#3520]
### Describe the Bug with repro steps

DataMapper canvas is unable to render the saved mapping.

1. Create a data mapper
2. add target XSD & JSON as source schemas
3. Do few simple 1-1 mapping, may add couple of simple string functions
4. save & generate the xslt
5. confirm respective yml & xslt files are getting created with respective code.
6. close the mapper canvas
7. now try reloading the data mapper
8. you can only see source & target xsd/json schemas but mappings along with functions will be missing
9. So you do not have any option but recreate the mappings.

### Version

[2.75.0](https://github.com/Azure/LogicAppsUX/compare/v2.74.0...v2.75.0) (2023-10-19)

### Additional context

Interesting part is, post reopening the data mapper (which fails to render the mappings) if you still go ahead try to run the tests it will run with success provided you do not save it or click on generate button. Because if save the data mapper then yml file will be cleared because your screen does not have any mappings.

AB#25588268

**Comment by DanielleCogs** [comment]
Hi @bankarswapnil would you be able to upload your schema and test LML file? As is I am unable to reproduce the issue. Thanks for your help!

**Comment by DanielleCogs** [comment]
Closing stale issue
