### ISSUE TITLE
Portal: Revert IP ranges for contents setting without any values doesnt allow machines to access contents

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#3526]
### Describe the Bug with repro steps

This happens in consumption and in ISE

1. Once we create new Logic App, the definition doesn't have an object 'accessControl'.

2. Then we add IP address for contents then definition has object as follows .

"accessControl": {
            "contents": {
                "allowedCallerIpAddresses": [
                    {
                        "addressRange": "10.0.0.2/32"
                    }
                ]
            }
        }
3. Upon removal of the entry /reverting the change the object looks like below.
 "accessControl": {
            "contents": {
                "allowedCallerIpAddresses": []
            }
        },

4. So, after removing the object is having empty array which seems to be an issues. I believe allowedCallerIpAddresses is supposed to be removed from def to resolve. 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25597606

**Comment by Eric-B-Wu** [comment]
do you know when this was happening, end of day 10/24 we had done a hotfix for this, which should have gone into all regions. The caveat is this wouldn't change the existing Logic Apps that have an empty array for IP addresses, so it would require customers to go in and first make a change on the workflow settings, and then it should no longer be happening

**Comment by xuehongg** [comment]
@Eric-B-Wu, Yes, you are correct. The issue is no longer happening. Thanks.
