### ISSUE TITLE
No way to add a step after parallel branch in new designer

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#3535]
### Describe the Bug with repro steps

![image](https://github.com/Azure/LogicAppsUX/assets/91279975/b4937f56-1527-47c9-b9d5-635a69e9c120)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25609106

**Comment by hartra344** [comment]
We discussed this, but this is by design. THe correct solution here is to use the run after setting. We can certainly add some UX to make that more discoverable if you have ideas but the +new step after a parallel branch got confusing very quickly on any non trivial workflow.
