### ISSUE TITLE
Put focus on Search box of action pane automatically

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#3538]
### Describe the Bug with repro steps

Open action pane, mouse focus is needed once again to start typing. 
![image](https://github.com/Azure/LogicAppsUX/assets/91279975/052f6e6a-1813-4475-8dec-242f46adaa52)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25613052

**Comment by hartra344** [comment]
This must be a bug with the Power Automate host and focus, this is how it's already working today. Video attached. I tested all of our host services and it works fine.

https://github.com/Azure/LogicAppsUX/assets/13208452/aa619e86-ec0f-4fb6-bd6c-2a683c203590
