### ISSUE TITLE
Action names do not accept ':'

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#3539]
### Describe the Bug with repro steps

![image](https://github.com/Azure/LogicAppsUX/assets/91279975/c159b4f8-cfcf-4993-b045-0df1be83744c)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25613127

**Comment by hartra344** [comment]
This is by design, that character is explicitly forbidden in Logic Apps. Not sure how or why it would in Power Automate given that.
