### ISSUE TITLE
Many form fields do not have visible labels

### ISSUE THREAD

**Issue by Ram-G** [Azure/LogicAppsUX#3549]
### Describe the Bug with repro steps

1. Create a new flow with designer standalone (nx serve).
2. Add a Condition action.
3. Observe that some fields (notably, the condition fields) don't have visible labels.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/10837129/fc0c69ae-9b05-4726-b1c1-b4557c96ce65)

### Browser

Edge

### Additional context

Related internal bug: https://msazure.visualstudio.com/One/_workitems/edit/13400375

AB#25622117

**Comment by hartra344** [comment]
This is a control where the entire control is the form field, not hte individual pieces. I agree this needs an accessability pass in general but the visual labels on each and every editable field in this control isn't feasible and would lead to more confusion. 

I'm guessing this bug itself came purely from an automated tool, would be happy to discuss other ways to make this work better for screen readers in particular but we're not adding labels to each and every control. Visually it's self explainable and a pretty standard tool for this kind of thing.
