### ISSUE TITLE
Run Trigger with payload fails with ajaxExtended call failed when unauthenticatedClientAction=Return401/Return403

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#3558]
### Describe the Bug with repro steps

1. Create a workflow for Logic App Standard with HTTP trigger and Easy Auth having the following section:

```json
{
  "globalValidation": {
    "requireAuthentication": true,
    "unauthenticatedClientAction": "Return401" // or Return403
  }
}
```

2. Go to workflow in the Azure Portal
3. Click Run with payload
4. Observe an error:

> ajaxExtended call failed

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "kind": "Stateful",
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http",
        "inputs": {
          "method": "POST"
        },
        "conditions": [
          {
            "expression": "@startsWith(triggerOutputs()?['headers']?['Authorization'], 'Bearer')"
          }
        ]
      }
    }
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/351644/0f9eeac0-6cf6-4406-ba50-aaadb622c1fd)

### Browser

Edge version 118.0.2088.61

### Additional context

Network logs:

> POST https://management.azure.com/subscriptions/{subId}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{appName}/hostruntime/runtime/webhooks/workflow/api/management/workflows/ProvisionAccount/triggers/When_a_HTTP_request_is_received/listCallbackUrl?api-version=2018-11-01

Response:

```
{
    "Code": "Unauthorized",
    "Message": "Encountered an error (Forbidden) from extensions API.",
    "Target": null,
    "Details": [
        {
            "Message": "Encountered an error (Forbidden) from extensions API."
        },
        {
            "Code": "Unauthorized"
        },
        {
            "ErrorEntity": {
                "Code": "Unauthorized",
                "Message": "Encountered an error (Forbidden) from extensions API."
            }
        }
    ],
    "Innererror": null
}
```

AB#25624637

**Comment by hartra344** [comment]
This is working as expected…the run method is making an unauthenticated call to your app for you. It’s meant as a simple way to test your API. If you put auth in front of it, you may need to move to a more powerful testing tool such as postman.

**Comment by abatishchev** [comment]
@hartra344 same question, where this is documented? I searched before posting.

**Comment by abatishchev** [comment]
Another question: is it possible to permit Azure Portal's AAD app instead of `AllowAnonymous`?

**Comment by hartra344** [comment]
For your first question, I'm not sure it's documented, it's just the basis of how it works. Run with payload just is just a simplified postman request to the app, , it doesn't do anything special, we can't take into account all the different variations a very niche set of users apply there and most will move to something like postman at that point anyway. 

As for your second question, I'm not sure, this is an app service question with easy auth. We're just running on an app service which allows access to normal app service features like Easy Auth.
