### ISSUE TITLE
Run with payload fails error: Access to XMLHttpRequest at '' from origin 'https://ms.portal.azure.com' has been blocked by CORS policy

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#3559]
### Describe the Bug with repro steps

1. Create a workflow for Logic App Standard with HTTP trigger and Easy Auth having the following section:

```json
{
  "globalValidation": {
    "requireAuthentication": true,
    "unauthenticatedClientAction": "AllowAnonymous"
  }
}
```

2. Go to workflow in the Azure Portal
3. Click Run with payload
4. Provide correct payload,
5. Click Run
6. Observe an error:

> Access to XMLHttpRequest at '{triggerUrl}' from origin 'https://ms.portal.azure.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "kind": "Stateful",
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http",
        "inputs": {
          "method": "POST"
        },
        "conditions": [
          {
            "expression": "@startsWith(triggerOutputs()?['headers']?['Authorization'], 'Bearer')"
          }
        ]
      }
    }
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/351644/d0c81db0-1dac-4f3b-818f-84362c6b4a29)

### Browser

Edge version 118.0.2088.61

AB#25624658

**Comment by hartra344** [comment]
This is working as expected, run is making a call to your app. If you have a CORS policy without accepting the portal endpoint you need either add portal to your CORS or use an app like postman.

**Comment by abatishchev** [comment]
@harta334 where's this is documented?
