### ISSUE TITLE
Icons are not properly visible in high contrast aquatic themes

### ISSUE THREAD

**Issue by Ram-G** [Azure/LogicAppsUX#3576]
### Describe the issue

1. Enable Windows high contrast mode (I use 'aquatic' theme).
2. Open flows that use these designer components -- html editor, array editor, and token picker.
3. Observe icon colors are incorrect.

### Are you using new designer or old designer

New Designer (With action panels)

### Screenshots or Videos

Token picker skittle:
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/64963473-2190-4440-aa8f-c2cb85cd57aa)

HTML editor:
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/42826a76-f900-413a-918a-5e1985f8cb48)

Array editor toggle:
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/f3788194-5b31-4648-8fcb-2dbdcfe52d39)

### Browser

Edge

### Additional context

Internal work item link: https://msazure.visualstudio.com/One/_workitems/edit/14039582

AB#25639232

**Comment by Ram-G** [comment]
FWIW, for Lexical editor, I see that this bug repros at https://playground.lexical.dev/ too

![image](https://github.com/Azure/LogicAppsUX/assets/10837129/8bab7387-971d-413d-96fb-d5d8e9efbd2e)

**Comment by Eric-B-Wu** [comment]
This component can be styled separate from Lexical
