### ISSUE TITLE
'More action' button is not actionable using Keyboard while it is actionable using 'mouse'

### ISSUE THREAD

**Issue by Ram-G** [Azure/LogicAppsUX#3577]
### Describe the issue

1. Open designer standalone (nx serve).
2. Search for an action. 
3. Hover over the tooltip (i) icon -- observe tooltip opens up. Observe no way to open the tooltip with keyboard.
4. Select an action.
5. On the action page, hover over the (i) icon, observe that tooltips opens up. Observe no way to open the tooltip with keyboard.

### Are you using new designer or old designer

New Designer (With action panels)

### Screenshots or Videos

On mouse hover, tooltip pops up. No way to access using keyboard.

On search results:
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/1f7de9aa-0440-4832-b57d-38a9cb8e50c3)

On action selection:
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/3d68cb12-bcf3-489c-be2c-d9fec7258cd2)

### Browser

Edge

### Additional context

Related internal work item: https://msazure.visualstudio.com/One/_workitems/edit/17554171

AB#25639340

**Comment by hartra344** [comment]
It gets read by the screen reader when the keyboard is over the operatoin

**Comment by Ram-G** [comment]
Based on my testing with nvda screen reader, looks like the tooltip text is not being read by screen reader. Is it possible the result is different with different screen readers?

Example screenshots of screen reader output below
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/5cb1c562-b91d-42fb-b209-8a94bf6f3431)
![image](https://github.com/Azure/LogicAppsUX/assets/10837129/8e7e2260-de3b-4006-ae26-0aad7d14289b)

**Comment by hartra344** [comment]
Could be, I use the screen reader built into MacOS as well as ChromeVOX for testing and both of those read it. Being on MacOS, I don't have access to NVDA or JAWS so if it's not working on those, I may need your help with fixing it.
