### ISSUE TITLE
Updating a Standard Logic App Definition via REST API 

### ISSUE THREAD

**Issue by CumulusService** [Azure/LogicAppsUX#3605]
### Describe the Bug with repro steps 

Hello, 

 I am trying to patch an exisiting workflow trigger (recurrence) via the Workflow API : 

 PUT [https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Logic/workflows/{workflowName}?api-version=2016-06-01](<https://management.azure.com/subscriptions/%7bsubscriptionId%7d/resourceGroups/%7bresourceGroupName%7d/providers/Microsoft.Logic/workflows/%7bworkflowName%7d?api-version=2016-06-01>)

I am generating the access token via the Entra ID App Regidration with the scope [https://management.core.windows.net/.default](<https://management.core.windows.net/.default>) or [https://management.core.windows.net/.default](<https://management.core.windows.net/.default>) and granted the read & contributor roles to the App.

 I first use the GET method to retrieve the payload , then modify it and perform a subsequent PUT method that returns 200 Success however the trigger remains unchaged in the portal.

[PUT\_Request.txt](<https://github.com/Azure/LogicAppsUX/files/13258052/PUT_Request.txt>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Execute_a_Oracle_query": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "oracle-5"
            }
          },
          "method": "post",
          "body": {
            "query": "SELECT  * FROM v_ext_sap_stock_balance"
          },
          "path": "/datasets/default/query/oracle"
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "Recurrence": {
        "type": "Recurrence",
        "recurrence": {
          "interval": 1,
          "frequency": "Week",
          "schedule": {
            "weekDays": [
              "Monday",
              "Tuesday"
            ],
            "hours": [
              "10",
              "11"
            ]
          }
        }
      }
    }
  },
  "connectionReferences": {
    "oracle-5": {
      "connection": {
        "id": "/subscriptions/40d49b0b-87a9-46b7-a62c-8da936959f5a/resourceGroups/TexasIntegration/providers/Microsoft.Web/connections/oracle-5"
      },
      "connectionName": "oracle-5",
      "api": {
        "id": "/subscriptions/40d49b0b-87a9-46b7-a62c-8da936959f5a/providers/Microsoft.Web/locations/westeurope/managedApis/oracle"
      },
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {
    "null": {
      "type": "String",
      "value": "null"
    }
  }
}
```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

*No response*

AB#25717716

**Comment by hartra344** [comment]
I'm trying to fully understand what the issue happening here is. You're changing teh recurrence trigger through API and expecting it to change in the designer? Are you refreshing the designer after making a change, and it will need a hard refresh of the portal most likely, the caching used in the portal does now assume people are making changes outside of portal?

**Comment by CumulusService** [comment]
Hi Sir
I must admit that this is the first time I’m performing changes to a logic App outside of the designer , I read the API Reference and for the impression that the workflow definition could be altered.
The guide mentions the PATCH method however it fails so the only choice is to use the PUT verb however that requires sending the entire workflow definition in the request body .
As for the refresh - I tried using the browser private mode , refreshed the page , cleared browser cache etc.
Didn’t help
The writes thing is that when I use the GET verb right after the PUT , I do see the changes however that doesn’t affect the workflow behaviour and doesn’t affect the trigger whatsoever

Hope you can suggest a solution

Thanks

Sent from my iPhone

On 5. Nov 2023, at 03:54, Travis Harris ***@***.***> wrote:

﻿

I'm trying to fully understand what the issue happening here is. You're changing teh recurrence trigger through API and expecting it to change in the designer? Are you refreshing the designer after making a change, and it will need a hard refresh of the portal most likely, the caching used in the portal does now assume people are making changes outside of portal?

**Comment by hartra344** [comment]
Like I said, it's generally expected that if you update the workflow outside of the portal while portal is open, you'll need to do a hard refresh for the designer to reflect that change(and I mean effectively hitting the browser refresh button or the hotkey combo for your OS). But if that's not reflecting that's wierd. I'll look into it this week sometime. In the meantime I would really advise using the designer OR using the rest API. Using both can definitely lead to something not being formatted correctly or something such that it technically works(because the backend can figure it out) but the designer maybe isn't able to.

**Comment by CumulusService** [comment]
Hi Travis
With Logic App Consumption no form of refresh is needed, I simply get the AD token , perform a PUT request and Voilà- workflow is changed.
The issue is only with Standard Logic Apps when even after a refresh nothing happens

Thanks


With very best regards,

Moshe Nachman ,

CEO and Founder

Cumulus-Service  GmbH

Fürstenrieder Straße 8b

München, 80687

 M: +972-54-6564046 / +49-152 24436050

E: ***@***.******@***.***>

W: https://cumulus-service.com/

[cid:7eb51d92-3811-4af9-9d3e-98a136173e89]



________________________________

**Comment by CumulusService** [comment]
I figured this- the PUT request is only applicable to Logic Apps of type "Consumption" and not "Standard"  ones.
No refresh / cache clearing is needed , just relaunching the Logic App and the changes are applicable
If you could investigate that thing to see why the Single-Tenant Apps won't work , it would be great as the  Consumption Logic Apps  are not natively integrated with a Virtual Network which is so needed.

Thanks !


With very best regards,

Moshe Nachman ,

CEO and Founder

Cumulus-Service  GmbH

Fürstenrieder Straße 8b

München, 80687

 M: +972-54-6564046 / +49-152 24436050

E: ***@***.******@***.***>

W: https://cumulus-service.com/

[cid:b3b3032d-7a78-43ea-b8a1-f55d5d8b1edd]



________________________________
