### ISSUE TITLE
Copy/Paste does not copy Api Connection correctly

### ISSUE THREAD

**Issue by Viktorh89** [Azure/LogicAppsUX#3621]
### Describe the Bug with repro steps

Create action that has any api connection (file/mq/sb etc)
Copy it
Paste it
If this action has more than one api connection to choose between,
it will not take the original one, looks like it takes the first one

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25743827

**Comment by Eric-B-Wu** [comment]
Hi @Viktorh89 thanks for reporting this bug, I've gone ahead a fix - expect this to be in our next release which should complete on 11/17

**Comment by Viktorh89** [comment]
Thx for quick action and for making a Great product
