### ISSUE TITLE
Body keeps changing tp HTTP

### ISSUE THREAD

**Issue by tergar1** [Azure/LogicAppsUX#3624]
### Describe the Bug with repro steps

I have an HTTP post connection after which there is a condition which references the body.
I have selected the body from the previous step which should be @{body('HTTP_ TRAT')} but instead inserts @{body('HTTP')}. I have tried changing manually but when I go to save it reverts back and then gives an error as @{body('HTTP')} does not exist.
I have created this via designer.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

chrome

AB#25743896

**Comment by Eric-B-Wu** [comment]
Thanks for reporting this bug. I created a fix for this, hoping to hotfix this in our next deployment (11/17)
