### ISSUE TITLE
VS Code_Extension Settings : Auto Start Design Time is not working as intended.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3627]
### Describe the Bug with repro steps

1. Create a logic app project in VS code.
2. Create a stateful/stateless workflow in standard LA.

**Expected:** Auto Start Design Time setting in Extension Settings should open the designer and func in task manager, in both scenarios with and without installation of dependencies binaries.

**Actual:**Auto Start Design Time setting in Extension Settings is **not** opening the designer and func in task manager is getting opened automatically once the VS code is opened, in both scenarios with and without installation of dependencies binaries.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/f85630f9-359a-4e15-9b23-ae673ead3d14)

### Browser

**VS Code extension:** 2.81.0

AB#25749227

**Comment by ccastrotrejo** [comment]
Hi @vgouth. I think there has been a misunderstanding on what the setting is intended to do. 

1. Designer shouldn't open automatically. It will only open if the user click on `Open Designer`
2. The design time api (func process) will run in task manager only when the VS Code is opened and there is a logic app project in it. 

I will close this issue, but if it fails in the above scenarios in future requests I will take a further look
