### ISSUE TITLE
Make Parse JSON sample payload UX full size

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#3644]
### Describe the Bug with repro steps

![image](https://github.com/Azure/LogicAppsUX/assets/91279975/e8fee801-09b1-414f-8080-e9e0387306cb)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

CHrome

AB#25764948

**Comment by kisubedi** [comment]
Hi @Eric ***@***.***>- is this WI fixed? Specifically, making the Parse JSON popup bigger? If so, how does it look?

-Kishor

**Comment by Eric-B-Wu** [comment]
<img width="1277" alt="Capture" src="https://github.com/Azure/LogicAppsUX/assets/95886809/76e14731-abdb-46eb-a0f4-95f8cd1c2c0b">

this is the full screen view

**Comment by kisubedi** [comment]
[heart]         Kishor Subedi reacted to your message:
________________________________
