### ISSUE TITLE
in-app connectors not showing up

### ISSUE THREAD

**Issue by pfreshman** [Azure/LogicAppsUX#3647]
### Describe the Bug with repro steps

1. Add a new workflow
2. Open the new workflow in designer mode
3. Click on 'Add a Trigger'
4. Select 'In-App' for run-time filter

No connectors are available:

<img width="1267" alt="Screenshot 2023-11-08 at 3 34 41 PM" src="https://github.com/Azure/LogicAppsUX/assets/30990740/fdcf76ee-484d-47d4-bf6a-c0fd2dfc6776">

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {}
    },
    "kind": "Stateful"
}
```

### Browser

- Browser: Brave

AB#25767077

**Comment by hartra344** [comment]
I'm not able to reproduce this: 
![CleanShot 2023-11-08 at 16 13 09@2x](https://github.com/Azure/LogicAppsUX/assets/13208452/f03c693a-ba5c-4319-8bc1-f8f7a9f57ace)

Can you tell us if you see any network or console failures happening?
