### ISSUE TITLE
Standard_Manage Identity:  Loading issue while adding actions when managed identity is disabled.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3669]
### Describe the Bug with repro steps 

1\.Create a Standard Logic app in Brazil South location and add stateful workflow.

 2\.Disable the system assigned manage identity if it is enabled save it from Identity tab.

3. Open Designer and add http request trigger. 
4. Select create job from Azure Automation with MI (laborbol)/Read a Subscription action. 

**Expected:** Should be able to add create job action from Azure Automation with MI (laborbol)/Read a Subscription even when the system assigned manage identity is disabled but the connection cannot be created.

**Actual:** Unable to add create job action from Azure Automation with MI (laborbol)/Read a Subscription when the system assigned manage identity is disabled, It is keep on loading for plenty of time.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/Azure/LogicAppsUX/assets/113517384/ddc36702-8d58-40a0-a54e-9139ca17da0d](<https://github.com/Azure/LogicAppsUX/assets/113517384/ddc36702-8d58-40a0-a54e-9139ca17da0d>)

[https://github.com/Azure/LogicAppsUX/assets/113517384/812ac608-b1cb-4ae6-9fa1-d149b0f4ed17](<https://github.com/Azure/LogicAppsUX/assets/113517384/812ac608-b1cb-4ae6-9fa1-d149b0f4ed17>)

[managedidentityharfile.zip](<https://github.com/Azure/LogicAppsUX/files/13320470/managedidentityharfile.zip>)

### Browser 

**Environmental Details: Version:** 2\.31108.1.1

### Additional context 

*No response*

AB#25792777

**Comment by rllyy97** [comment]
I'm able to repro this, specifically when system MI is disabled and there isn't a user MI

**Comment by rllyy97** [comment]
@vgouth what behavior are you expecting?  I tried to repro on legacy designer and even on legacy we don't allow setting a connection or creating a new connection due to there being no identities assigned with the logic app.  Either the system assigned identity needs to be enabled or there needs to be a user identity.

I'm going to add in some errors/warnings around this behavior and fix the loading screen bug, but are you expecting full functionality even with no identities?

**Comment by vgouth** [comment]
@rllyy97. No, I am not expecting full functionality even with no identities. But there is loading screen issue when identities are disabled.

**Comment by ramya894** [comment]
Closing it as able to load azure automation MI(labrol).
