### ISSUE TITLE
This Logic App run instance will not load. Displays spinners only

### ISSUE THREAD

**Issue by olivesprig** [Azure/LogicAppsUX#3682]
### Describe the Bug with repro steps

This Logic App run instance will not load. Displays spinners only

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25823460

**Comment by hartra344** [comment]
Do you see any console errors or failed network requests? With just the description here there isn't much we're going to be able to do.
