### ISSUE TITLE
Id Replacements are only created for newly created a node, thus downstream tokens aren't updated when an existing node renames

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#3683]
### Describe the Bug with repro steps 

1. Use an existing Logic App 
2. Use a token in an action from an upstream node 
3. Rename the upstream node 
4. Token in downstream action is not updated 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

This is a different interaction from what happens when we rename a newly created upstream node, where we update the downstream token both visually and during serialization

AB#25824301

**Comment by hartra344** [comment]
I'm thinking this was fixed as I'm not able to repro now. Feel free to reopen if that's not the case
