### ISSUE TITLE
data mapper xslt 3.0 produced by data mapper fails in Logic app workflow but works otherwise

### ISSUE THREAD

**Issue by RVonGIT** [Azure/LogicAppsUX#3688]
### Describe the Bug with repro steps 

Data mapper details: 

 Azure Logic Apps - Data Mapper v2.75.0

source field type: string 

 Destination field type: string

xslt 3.0 mapping produced by data mapper is as shown below:

![image](<https://github.com/Azure/LogicAppsUX/assets/148351141/7278c8a4-ec8c-4480-93ab-d29def57abe8>)

![image](<https://github.com/Azure/LogicAppsUX/assets/148351141/783f49da-dbdb-438f-b053-fb917aa5bfd1>)

![image](<https://github.com/Azure/LogicAppsUX/assets/148351141/86e0e1d7-4e35-4943-a275-f7e4c1a48d26>)

Data Mapper : map test produces the output as expected as shown above.

**Workflow error**

Azure Logic Apps (Standard) v2.72.2

 But, this map when executed in a Logic app workflow shows the following error with the same input.

![image](<https://github.com/Azure/LogicAppsUX/assets/148351141/ddfcd802-398c-42d5-a305-839f1569c64d>)

### Screenshots or Videos 

*No response*

### Version 

v1

### Additional context 

*No response*

AB#25828159

**Comment by kewear** [comment]
@RVonGIT would it be possible to get the artifacts so that we can try to reproduce this issue? You can upload them here or feel free to email them to me kent.weare at microsoft dot com

**Comment by Rvgituser** [comment]
@kewear yes, I'll check if I can do that at work.
If not I can create a video and share the link so you can have a look at it. Would that work?

**Comment by kewear** [comment]
Ideally getting the artifacts or  removing sensitive areas of the artifacts but keeping the pieces that cause the issue would be ideal. Otherwise a video would also help. Thanks,  Kent

**Comment by Rvgituser** [comment]
[DataMapper_Files.zip](https://github.com/Azure/LogicAppsUX/files/13684696/DataMapper_Files.zip)
Please find the attached artifacts
the readme file explains the setup.

**Comment by kewear** [comment]
Thank you @Rvgituser we will take a look. Due to holiday period, please expect some delays

**Comment by kewear** [comment]
@Rvgituser we have been unable to reproduce the issue based upon the sample inputs provided. Can you please validate the inputs you provided reproduce the issue on your side?

**Comment by RVonGIT** [comment]
Hi @kewear,

yes I can recreate this issue and send a link to the video?

**Comment by Rvgituser** [comment]
@kewear suggestions?
