### ISSUE TITLE
Text in non-HTML editors can be formatted (e.g., bolded)

### ISSUE THREAD

**Issue by ek68794998** [Azure/LogicAppsUX#3700]
### Describe the Bug with repro steps

1. Open any workflow in the designer.
2. Ensure the open workflow has some action or trigger with a text-based input that is **NOT** an HTML editor.
3. Enter something in the above text-based input.
4. Highlight the entered text.
5. Hit Ctrl+B (or Cmd+B on Mac).

Expected: Nothing should happen.
Actual: Text becomes bold.

(Also works with italics using Ctrl+I, etc.)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![format-non-html](https://github.com/Azure/LogicAppsUX/assets/1350074/b90768d0-e18d-455f-b1a8-9419c906bd57)

### Browser

Windows 11 / Chrome 119.0.6045.159.

AB#25854136

**Comment by hartra344** [comment]
Does this have any functionality issues or just cosmetic?

**Comment by Eric-B-Wu** [comment]
It's purely cosmetic, due to how our serialization works on non-htmlEditor editors which only get the the text content from the lexical text node
