### ISSUE TITLE
Run History in VS Code execution does not register

### ISSUE THREAD

**Issue by brad302** [Azure/LogicAppsUX#3705]
### Describe the Bug with repro steps

Put simply, once I kick off my LA workspace project, I fire off an execution of the boilerplate flow (as per these instructions ... https://learn.microsoft.com/en-us/azure/logic-apps/create-run-custom-code-functions) and the run history never registers.

I know the flow runs because debug points are hit and an external execution using Postman returns a result.

I've had a read, searched and ultimately found nothing that may help correct this.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Call_a_local_function_in_this_logic_app": {
        "type": "InvokeFunction",
        "inputs": {
          "functionName": "TestFunction",
          "parameters": {
            "zipCode": 85396,
            "temperatureScale": "Celsius"
          }
        },
        "runAfter": {}
      },
      "Response": {
        "type": "Response",
        "kind": "http",
        "inputs": {
          "statusCode": 200,
          "body": "@body('Call_a_local_function_in_this_logic_app')"
        },
        "runAfter": {
          "Call_a_local_function_in_this_logic_app": [
            "Succeeded"
          ]
        }
      }
    },
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http",
        "inputs": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {}
  },
  "kind": "Stateless"
}
```

### Screenshots or Videos

You can see below, there are two executions and yet no run history.

![image](https://github.com/Azure/LogicAppsUX/assets/14899088/47d47b1b-fcf7-488c-8a16-380d4c08748f)

### Browser

Chrome

AB#25862292

**Comment by hartra344** [comment]
@ccastrotrejo can you take a look?

**Comment by ccastrotrejo** [comment]
Hi @brad302. Thank you so much for raising this issue. I looked at the workflow structure that you shared with us and it seems that the kind of workflow is stateless. For stateless workflows no run history is saved. I suggest you changed the kind to `Stateful` . You can learn more about the differences in [here](https://learn.microsoft.com/en-us/azure/logic-apps/single-tenant-overview-compare#stateful-stateless)

**Comment by brad302** [comment]
Ahhhh, thanks @ccastrotrejo, I didn't even notice that section of the documentation.  Will check it out.

**Comment by brad302** [comment]
@ccastrotrejo interestingly enough, that actually didn't do the trick.  I honestly thought it would but I still get no history when debugging in VS Code.  Any other thoughts?

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsSecretStorageType": "Files",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "ProjectDirectoryPath": "c:\\Repos\\LogicApps Standard\\LogicAppsWorkspace\\Workspace\\LogicApp",
    "Workflows.StatelessWorkflow.OperationOptions": "WithStatelessRunHistory"
  }
}
```

**Comment by ccastrotrejo** [comment]
Hi @brad302, I looked again at the documentation, and it only says that the user should update the local.settings.json  inside the workflow-designtime folder, however the update needs to be done also in the root local.settings.json. 
I did the change in both files and I was able to get the run history for stateless workflows. You can see the change by the overview page as the state type now says `(debug mode)`. Could you please give it a try? Thanks!

<img width="1490" alt="Screenshot 2023-11-17 at 8 19 44 AM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/c719f556-0aeb-4e37-b7b9-fcc604b2bf87">

**Comment by brad302** [comment]
Will do, thanks for the update. Hopefully the documentation is also updated based on our conversation.

**Comment by ccastrotrejo** [comment]
@brad302 Sure thing, I am glad it worked!
