### ISSUE TITLE
Designer doesn't work for nested dynamic UI

### ISSUE THREAD

**Issue by siddharth-ms** [Azure/LogicAppsUX#3707]
### Describe the Bug with repro steps

We are trying to generate a UI like:
![Screenshot 2023-11-16 184656](https://github.com/Azure/LogicAppsUX/assets/104004368/4d233379-38fb-4bd1-8201-80af2b8f23ba)

We have a SAP manifest which looks like below:
![Screenshot 2023-11-16 184530](https://github.com/Azure/LogicAppsUX/assets/104004368/ecebb46d-aae3-4e49-b990-c66317473e21)
Where we have a dynamic reference on the parameter `bodyType`, which can be `[XML, JSON, Dynamic]`
Based on particular selection (i.e `bodyType` as `Dynamic`) a call is being made to:
```curl
POST https://management.azure.com/subscriptions/f34b22a3-2202-4fb1-b040-1332bd928c84/resourceGroups/siddharth-imp/providers/Microsoft.Web/sites/sid-sap-testbox/hostruntime/runtime/webhooks/workflow/api/management/operationGroups/sap/operations/getCallRfcInputVarientSchemaSwagger/dynamicInvoke?api-version=2018-11-01

...<With bodyType as Dynamic in payload>...
```
Which responds with another dynamic parameter `bodyType` & `rfcName`:
![Screenshot 2023-11-16 184426](https://github.com/Azure/LogicAppsUX/assets/104004368/a3357d75-bd32-4f63-9514-cd6b835622e1)
Now when we enter a valid entry for `rfcName` a call to `dynamicInvoke` is not being made to fetch further set of Dynamic UI parameters.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#25863805

**Comment by preetriti1** [comment]
Something is not correct in your screenshot, firstly when you put dynamic properties in a schema that object schema becomes a dynamic property so anything defined inside properties of that schema will not be shown in the UI.
Please state your ask, what do you actually want to do in the operation?

**Comment by siddharth-ms** [comment]
So we have a UI like below:
![Screenshot 2023-11-16 184656](https://github.com/Azure/LogicAppsUX/assets/104004368/ac44a620-e491-4d45-bf05-a08b2c094e6c)

And it makes two dynamic UI calls,
1. First is when we select `bodyType` as `Dynamic`. We see new parameters appear, ie. `rfcName` and `groupRfcFilter`.  Below is the response form this dynamic call:
![Screenshot 2023-11-16 184426](https://github.com/Azure/LogicAppsUX/assets/104004368/6e976104-50ba-46dc-9d2e-e8ac9d0d605f)
2. When a `rfcName` is selected, it should ideally call another `dynamicInvoke` to retrieve new parameters depending on `rfcName`.

Is this a scenario that is not currently supported?

**Comment by hartra344** [comment]
discussion can continue in #3709 and in person
