### ISSUE TITLE
Dynamic Lists in a Dynamic UI Element is not performant

### ISSUE THREAD

**Issue by siddharth-ms** [Azure/LogicAppsUX#3708]
### Describe the Bug with repro steps

We are trying to generate a UI like:

![Screenshot 2023-11-16 184656](https://github.com/Azure/LogicAppsUX/assets/104004368/4d233379-38fb-4bd1-8201-80af2b8f23ba)

We have an element `rfcName` with Dynamic List, Ref: Manifest below:
![Screenshot 2023-11-16 185901](https://github.com/Azure/LogicAppsUX/assets/104004368/2e38fc2a-f26d-4f7d-8474-78e0a2e06ccd)
Where the contents of the elements are fetched by a `dynamicInvoke` call like:
```
https://management.azure.com/subscriptions/f34b22a3-2202-4fb1-b040-1332bd928c84/resourceGroups/siddharth-imp/providers/Microsoft.Web/sites/sid-sap-testbox/hostruntime/runtime/webhooks/workflow/api/management/operationGroups/sap/operations/listRfcs/dynamicInvoke?api-version=2018-11-01
```

The element works just fine when it's a static element, but performance is much slower and the page becomes un-responsive when the element is created through a dynamic call, Here the field `rfcName` is generate as a result of `Dynamic` selection of `bodyType`.

Selecting `bodyType` as `Dynamic` makes below call:
```bash
curl 'https://management.azure.com/subscriptions/f34b22a3-2202-4fb1-b040-1332bd928c84/resourceGroups/siddharth-imp/providers/Microsoft.Web/sites/sid-sap-testbox/hostruntime/runtime/webhooks/workflow/api/management/operationGroups/sap/operations/getCallRfcInputVarientSchemaSwagger/dynamicInvoke?api-version=2018-11-01' \
  -H 'x-ms-user-agent: LogicAppsDesigner/2.75.0 (host azure-logic-apps-client ; source DesignerStandard)' \
  --data-raw $'{"parameters":{"bodyType":"Dynamic"},...' \
  --compressed
```
and Response:
![Screenshot 2023-11-16 190321](https://github.com/Azure/LogicAppsUX/assets/104004368/310971ae-adfe-4165-9ec8-6fff0a17b5b6)
Which results in creation of dynamic field `rfcName`. When is element is top level element, and not a dynamic element, it is able to handle list of RFCs but not in case of Dyanmic element.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#25863872

**Comment by preetriti1** [comment]
Just to be clear, you are not seeing dynamic list being populated for rfcName when that is a dynamic property returned by body type dynamic call?

**Comment by siddharth-ms** [comment]
No, we see a REST call to `dynamicInvoke` fetching all the RFCs. But while populating the UI stops responding, and the Edge browser suggests to kill the page.
