### ISSUE TITLE
Issue using parameters from dynamic input in dynamic output payload

### ISSUE THREAD

**Issue by siddharth-ms** [Azure/LogicAppsUX#3709]
### Describe the Bug with repro steps

We have a manifest like below:
![Screenshot 2023-11-16 200328](https://github.com/Azure/LogicAppsUX/assets/104004368/cfbeafcd-4f68-4332-aed7-e0a6a17fa27d)
Where some input parameters are coming dynamically (marked red), We are unable to use those dynamic input parameters (which are not present on as static input, but appears after a `dynamicInvoke` call), in dynamic output parameter values in outputs (marked yellow). For example, `fcName` below is a parameter dynamically created by selecting `RFC`. This parameter (`rfcName`) is not being passed to the input payload of dynamic output call.

![Screenshot 2023-11-17 093113](https://github.com/Azure/LogicAppsUX/assets/104004368/18dbe58d-746a-4865-8ac3-f2a5f9e9d9f1)

Below is the raw manifest:
```git
{
  "inputs": {
    "type": "object",
    "properties": {
      "operationType": {
        "type": "string",
        "title": "Operation Type",
        "description": "Operation Type to Generate Schema.",
        "default": "RFC",
        "enum": [
          "BAPI",
          "RFC",
          "IDoc",
          "tRFC"
        ]
      },
      "fileNamePrefix": {
        "type": "string",
        "title": "File Name Prefix",
        "description": "File Name Prefix for Generate Schema."
      }
    },
    "required": [
      "operationType"
    ],
    "x-ms-dynamic-properties": {
      "dynamicState": {
        "extension": {
          "operationId": "getSchemaInputSwagger",
          "parameters": {}
        },
        "isInput": true
      },
      "parameters": {
        "operationType": {
          "parameterReference": "operationType"
        }
      }
    }
  },
  "inputsLocation": [
    "inputs",
    "parameters"
  ],
  "isInputsOptional": false,
  "outputs": {
    "type": "object",
    "properties": {
      "body": {
        "x-ms-dynamic-properties": {
          "dynamicState": {
            "extension": {
              "operationId": "getSchemaResponseDyanmicSchema",
              "parameters": {}
            }
          },
          "parameters": {
            "operationType": {
              "parameterReference": "operationType"
            },
+            "rfcName": {
+             "parameterReference": "rfcName"
+          },
            "fileNamePrefix": {
              "parameterReference": "fileNamePrefix"
            }
          }
        }
      }
    }
  },
  "isOutputsOptional": false,
  "settings": {
    "secureData": {},
    "trackedProperties": {
      "scopes": [
        "Action"
      ]
    }
  },
  "includeRootOutputs": false,
  "connectionReference": {
    "referenceKeyFormat": "serviceprovider"
  },
  "statusBadge": {
    "name": "Production",
    "description": "Production"
  },
  "operationOptions": "None"
}
```

Is this type of call supported?

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#25864112

**Comment by preetriti1** [comment]
This scenario is never supported, all dynamic calls made either for inputs or outputs must depend on static parameters in the swagger/manifest

**Comment by siddharth-ms** [comment]
Are there plans for supporting those?

**Comment by hartra344** [comment]
@siddharth-ms since you're internal, let's talk offline after thanksgiving and see what you're needs are exactly and if there's another way to achieve the same thing.

**Comment by hartra344** [comment]
linking to #3707 for discussion since these are all for a single scenario

**Comment by siddharth-ms** [comment]
Discussed offline this scenario is not supported. Feel free to close it
