### ISSUE TITLE
Newlines are arbitrarily lost after blurring HTML editor when using dynamic content

### ISSUE THREAD

**Issue by ek68794998** [Azure/LogicAppsUX#3710]
### Describe the Bug with repro steps 

1. Open any flow that has an action using HTML editor. 
2. Open above action in panel. 
3. Add some dynamic content, formatting, and use multiple newlines (leaving 2 full line breaks between usually reproes). 
4. Click another node. 
5. Click the node edited in step 3. 

Expected: The content should not change between steps 3 and 5.

 Actual: A number of newlines will suddenly be missing.

### What type of Logic App Is this happening in? 

Power Automate

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![newline-loss-2](<https://github.com/Azure/LogicAppsUX/assets/1350074/522d4ac5-7c9b-4b43-b671-de658abd9d5d>)

### Browser 

Windows 11 / Chrome 119

### Additional context 

One thing I noticed is that it seems like sometimes Lexical is serializing line breaks using `&lt;p&gt;`, sometimes using `&lt;br&gt;`, and sometimes using `&lt;span&gt;\n&lt;/span&gt;`. It seems like unifying these might be the best path forward?

Sample, captured from `libs\designer-ui\src\lib\html\index.tsx:15`:

![image](<https://github.com/Azure/LogicAppsUX/assets/1350074/b6d46a58-ad2b-43f3-a773-3241e4c25acc>)

AB#25870417

**Comment by ek68794998** [comment]
I'll be taking a look at this one myself, but figured I would post the bug here too in case anyone more familiar with Lexical has any ideas.

**Comment by ek68794998** [comment]
I've made a bit of progress by improving `convertEditorState` logic. However, there appear to be some bugs that originate inside Lexical.

For example, here is some content I've worked with. I've color coded three sections: 1) yellow, text + token; 2) green, newlines only; 3) pink, bold text + token.

![image](https://github.com/Azure/LogicAppsUX/assets/1350074/7f599434-c64a-447b-990f-e88b250c4eac)

Lexical control DOM nodes; notice that in total, there are 3 `<br>` tags:

![image](https://github.com/Azure/LogicAppsUX/assets/1350074/77dfa25f-a20a-4767-b1f9-84016fe46b8e)

But once it gets run through `$generateHtmlFromNodes`, there is only one `<br>` remaining (green section):

![image](https://github.com/Azure/LogicAppsUX/assets/1350074/c5992957-303e-4996-a66b-206fbcf12c41)

As a result, when I switch away from and back to this node, I'm left with only one blank line. My understanding is that the rough structure should be `<p>...</p><p><br><br></p><p>...</p>`, with total of two line breaks. I believe this is actually related to Lexical issue 3879 that is linked in the comments of this file.

I'm working on continuing to improve `convertEditorState` logic to work around this, but it seems like this might be on Lexical to address.

**Comment by hartra344** [comment]
@ek68794998 did you finish fixing this? it doesn't appear to be reproing for me?
