### ISSUE TITLE
"Create workflow..." fails with "Cannot read properties of undefined (reading 'fsPath')" error

### ISSUE THREAD

**Issue by brad302** [Azure/LogicAppsUX#3711]
### Describe the Bug with repro steps

1. Go to Azure extension
2. Select "Azure LogicApps" button from the workspace accordion/section
3. "Create Workflow..."

The following error occurs ...

![image](https://github.com/Azure/LogicAppsUX/assets/14899088/1bc09c48-e986-4847-a85e-5943bdeab45b)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Call_a_local_function_in_this_logic_app": {
                "type": "InvokeFunction",
                "inputs": {
                    "functionName": "MyFunctionRenamed",
                    "parameters": {
                        "zipCode": 85396,
                        "temperatureScale": "Celsius"
                    }
                },
                "runAfter": {}
            },
            "Response": {
                "type": "Response",
                "kind": "http",
                "inputs": {
                    "statusCode": 200,
                    "body": "@body('Call_a_local_function_in_this_logic_app')"
                },
                "runAfter": {
                    "Call_a_local_function_in_this_logic_app": [
                        "Succeeded"
                    ]
                }
            }
        },
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

As already shown in the steps to recreate.  Unfortunately, I have no more information than that.

I do also have this issue (which I thought may be related) ...

![image](https://github.com/Azure/LogicAppsUX/assets/14899088/f6fc1898-09d0-4c43-8dc1-39ecf62be50f)

 and after finding an associated issue (https://github.com/microsoft/vscode-azurefunctions/issues/3773) that was resolved, unfortunately, my workspace only has a single `.csproj` file and the context of that issue isn't exactly the same.

### Browser

Chrome

AB#25875619

**Comment by CharlesWarwick** [comment]
I am seeing this behaviour and it started immediately after updating the VS Code  LAS extension to [2.81.5](https://github.com/Azure/LogicAppsUX/compare/v2.81.4...v2.81.5)

1. immediately after the reload in the image, I could not create a workflow and got this error.
2. When I reverted to v2.72.2 I could create workflows again

![image](https://github.com/Azure/LogicAppsUX/assets/7351746/64367737-345e-4113-9ea9-3a581f22f92f)

**Comment by brad302** [comment]
@CharlesWarwick thanks for the heads up ...!  Very helpful.

**Comment by ccastrotrejo** [comment]
HI all, thanks for raising this issue. I will take a look at this and come up with a fix

**Comment by ccastrotrejo** [comment]
Ok I have created this PR https://github.com/Azure/LogicAppsUX/pull/3779 to fix this bug. We will include the fix in the release of the extension
