### ISSUE TITLE
Consumption Portal "IP ranges for contents" are not being saved

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#3717]
### Describe the Bug with repro steps

Go to workflow properties blade
Enter some IP for "IP ranges for contents" and save it. No error.
Now browse to some other blade like Overview blade etc
Now come back to the windows properties blade and you will find the specific IP is not showing at all. It is lost.
Take a HRA issue for the above repro and it appears the PUT request to the backend did not include the specified IP

<img width="281" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/49498706/677375d8-da53-4f22-a95f-32b4b87176cf">

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by rllyy97** [comment]
Just for documenting, this is not a recent regression, the blade rewrite for this blade was ~2 months ago

**Comment by rllyy97** [comment]
This has been fixed and merged in our Portal repo.
