### ISSUE TITLE
Create new Project : files is not iterable

### ISSUE THREAD

**Issue by iulianmarius** [Azure/LogicAppsUX#3734]
### Describe the Bug with repro steps

1. Click "create new project" in Visual Studio Code Workspaces.
2. Select a folder
3. select Stateful Workflow

Action: azureLogicAppsStandard.createNewProject
Error type: TypeError
Error Message: files is not iterable

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
no workflow
```

### Browser

no browsers

### Additional context

Version: 2.81.5
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

<details>
<summary>Call Stack</summary>

```
dotnet.ts:194:22dotnet.ts:194:22
tslib.es6.js:76:1tslib/tslib.es6.js:76:1
Module.__awaiter tslib/tslib.es6.js:72:1
getLocalDotNetVersionFromBinaries main.js:484191:20
executeDotnetTemplateCommand.ts:92:83executeDotnetTemplateCommand.ts:92:83
tslib.es6.js:76:1tslib/tslib.es6.js:76:1
Module.__awaiter tslib/tslib.es6.js:72:1
getFramework main.js:484349:20
executeDotnetTemplateCommand.ts:78:9executeDotnetTemplateCommand.ts:78:9
tslib.es6.js:76:1tslib/tslib.es6.js:76:1
Module.__awaiter tslib/tslib.es6.js:72:1
validateDotnetInstalled main.js:484336:20
Function.<anonymous> CodelessWorkflowCreateStep.ts:43:34
tslib.es6.js:76:1tslib/tslib.es6.js:76:1
Module.__awaiter tslib/tslib.es6.js:72:1
Function.createStep main.js:470112:24
WorkflowStateTypeStep.<anonymous> WorkflowStateTypeStep.ts:44:58
tslib.es6.js:76:1tslib/tslib.es6.js:76:1
Module.__awaiter tslib/tslib.es6.js:72:1
WorkflowStateTypeStep.getSubWizard main.js:470428:24
AzureWizard.<anonymous> @microsoft/AzureWizard.js:122:1
fulfilled @microsoft/AzureWizard.js:9:43
```

</details>

AB#25917427

**Comment by AymanEnter** [comment]
Any update on this blocking issue. Thanks

**Comment by ccastrotrejo** [comment]
Ok I have created this PR https://github.com/Azure/LogicAppsUX/pull/3779 to fix this bug. We will include the fix in the release of the extension
