### ISSUE TITLE
Data Mapper: Don't add field to destination if not present on source.

### ISSUE THREAD

**Issue by John-Bosch** [Azure/LogicAppsUX#3750]
### Describe the Bug with repro steps

Currently, when doing JSON to JSON transformations if a mapped field is not present on the source JSON object, the resulting destination JSON object has the mapped field present with its default value. I want the ability to specify the "not present" behaviour (as opposed to the "null" behaviour) to be either "don't create" or "set to default".

This would greatly aid in the transformation of objects such as Dataverse Web API updates where not having a field present on an entity means "don't update this field" whereas having it there means update it to that value (so present with a value means update the field to that value, present and null sets the field to null, not present at all means leave the field unchanged).

### Version

Logic App Standard extension 2.81.5

AB#25957981

**Comment by alexzunigamsft** [comment]
@John-Bosch I believe what you're looking for can be achieved through "if" and "exists" functions. If the source JSON object exists, then map to the target.

**Comment by kewear** [comment]
Closing issue based upon the suggestion that Alex offered above
