### ISSUE TITLE
Data Mapper: Can't use "Copy" function

### ISSUE THREAD

**Issue by John-Bosch** [Azure/LogicAppsUX#3751]
### Describe the Bug with repro steps

1. Create very simple source and destination schemas (doesn't matter that they are identical for this test).

`{
    "type": "object",
    "properties": {
        "CollectionName": {
            "type": "string"
        },
        "Items": {
            "type": "object",
            "properties": {
                "Property1": {
                    "type": "string"
                },
                "Property2": {
                    "type": "string"
                }
            }
        }
    }
}`
2. Create a simple data map whereby you use the "copy" function to deep copy the array property:
![image](https://github.com/Azure/LogicAppsUX/assets/5135377/4fa0a608-cfd4-4879-9d69-bf70e7281c43)

3. Note what's written in the code window.
4. Generate the XSLT and note that the "<map key="Items" />" is there as expected.
5. Close all windows and reload the data map.
6. Note that your deep copy has gone away:
![image](https://github.com/Azure/LogicAppsUX/assets/5135377/98d92d3e-c1df-438a-b6ec-d37792f1359f)

7. Regenerate the XSLT and note the "<map key="Items" />" is now also gone.

### Version

2.81.5

AB#25958557

**Comment by DanielleCogs** [comment]
This copy is only supported from XML to XML. JSON does not have an equivalent "any" data type for this to work. We have an internal work item to make this documentation more clear.
