### ISSUE TITLE
Split On setting for trigger is default off in V3 unlike the classic designer

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#3755]
### Describe the Bug with repro steps 

In old designer, create a flow with 'When an item is created' SPO trigger. Navigate to the action settings and notice Split On setting is by default on. This means the output of this trigger is a single SP item, whose tokens are available in subsequent action.

In new designer, the setting is off by default. This means the output of this trigger is an SP item array, whose tokens are available in subsequent action.

The consequence of this is:

1. in the old designer, flow would run once for each new item which is more predictable. In the new designer, any new items added trigger the same flow. this is unpredictable behavior. 
2. new designer creates an unnecessary loop which throws off customers. 
3. Trigger tokens might not be available in the subsequent action in new designer, as trigger output is an array, and only token accessible is output/body. 

### What type of Logic App Is this happening in? 

Power Automate

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/91279975/f04b5df1-fbb2-4169-9bb0-5bfef1c1c162>)

Customers feedback volume complaining about unnecessary loop: 

![image](<https://github.com/Azure/LogicAppsUX/assets/91279975/a6eedbf4-63a2-49d2-90ef-34e4f4bd2e6f>)

![image](<https://github.com/Azure/LogicAppsUX/assets/91279975/60075143-e67d-43c0-96ee-f713f97faceb>)

![image](<https://github.com/Azure/LogicAppsUX/assets/91279975/fb658d8b-53e6-48e2-9e5e-689186be72e9>)

### Browser 

Chrome

### Additional context 

*No response*

AB#25966928

**Comment by hartra344** [comment]
Fixed already
