### ISSUE TITLE
Info icon header missing

### ISSUE THREAD

**Issue by Aleks-gdb** [Azure/LogicAppsUX#3758]
### Describe the Bug with repro steps

1. Go to add a new action
2. Select any connector
3. Hover over the info icon for an operation in the list
4. Observe no header
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/d997b9a6-c33a-4227-816b-ab015bd1a51c)

Before:
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/6d031f07-2cd9-4979-880d-8bd2edd6decd)

### What type of Logic App Is this happening in?

Power Automate

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#25970306

**Comment by hartra344** [comment]
This was intentional. It’s duplicate information for both visual users and for screen reader users.
