### ISSUE TITLE
Connector's operations list is misaligned

### ISSUE THREAD

**Issue by Aleks-gdb** [Azure/LogicAppsUX#3759]
### Describe the Bug with repro steps

1. Go to add an action in the designer
2. Select any connector that has multiple operations
3. Observe extra padding
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/b074cd7c-3363-42cc-8a5f-f8114e2a18e5)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

### Additional context

Seems like this is due to user agent stylesheets being applied after switching the component to use a list vs buttons

AB#25970331

**Comment by hartra344** [comment]
I'm wanting to make sure I'm seeing what you're seeing. Are you takling about the padding on the right or are they somehow not pixel aligned with each other in some way I'm missing? The padding at the beginning is intented and part of the design.

**Comment by Aleks-gdb** [comment]
> I'm wanting to make sure I'm seeing what you're seeing. Are you talking about the padding on the right or are they somehow not pixel aligned with each other in some way I'm missing? The padding at the beginning is intended and part of the design.

There was no padding on the left of the list:
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/835afba9-04e0-49f8-a0a6-1ad2e3a8fe6e)

**Comment by Eric-B-Wu** [comment]
this is happening because we had moved these options into a li, which has a built in padding-inline-start, created a fix here: https://github.com/Azure/LogicAppsUX/pull/3764
