### ISSUE TITLE
Apply to Each- Current Item is not available

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#3761]
### Describe the Bug with repro steps 

![image](<https://github.com/Azure/LogicAppsUX/assets/91279975/dcc699a7-0d18-4c07-8011-1ed4b91845ea>)

Same flow in v1: No Current item option

![image](<https://github.com/Azure/LogicAppsUX/assets/91279975/e90874da-a1bc-4cbc-a37d-369391b9d944>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

AB#25970401

**Comment by Eric-B-Wu** [comment]
is the Apply to Each and For Each action the same thing in Power Automate? At least in logic apps I'm seeing the current item in the For Each scope

**Comment by kisubedi** [comment]
Yes looks like it is only reproing for us.

**Comment by hartra344** [comment]
If it's only reproing for Power Automate then it's likely a local manifest issue in your host. Closing here.
