### ISSUE TITLE
How to generate guid() or uuid() and pass null values into target ?

### ISSUE THREAD

**Issue by bankarswapnil** [Azure/LogicAppsUX#3773]
### Describe the Bug with repro steps

Hi Team,

I am facing two difficulties in Json to Json mappings,
1.
Source json has following payload [just cleared other elements for clarity],

{
     "supply": {
          "city": null
      }
}

But in Target json payload, null value is reflecting as empty string,
{
   "supply": {
       "city": ""
    }
}
How to enforce null value as is in the target ?

2.
How to map a function guid() or uuid() into target element?
 
Thanx,
-Swapnil

### Version

Latest VSCode : 1.84.2 [Installed on 29Nov2023]
where data mapper is OOTB whereas std logic apps extension is : 2.81.5 (2023-11-14)

AB#26001872

**Comment by Ezeckiel2517** [comment]
I kinda have the same problem where my source json have an empty value and the target need a null. The target system do not accept empty "" string in email because "" is in a valid email format, where null is OK.

**Comment by DanielleCogs** [comment]
We separated these issues into two, to prioritize them separately! 
https://github.com/Azure/LogicAppsUX/issues/3992 - GUID
https://github.com/Azure/LogicAppsUX/issues/3993 - NULL values

**Comment by DanielleCogs** [comment]
Closing this issue as they will be tracked in the above issues separately! Thanks for reporting
