### ISSUE TITLE
Cannot create a new SendGrid Connector in a standard logic app

### ISSUE THREAD

**Issue by murdockcrc** [Azure/LogicAppsUX#3781]
### Describe the Bug with repro steps 

1. Go to the logic app workflow designer 
2. Try to create a new sendgrid connector (send email V4) 
3. The GUI will ask for a name and an API key. 
4. Create the connector. The portal fails with this error:

![image](<https://github.com/Azure/LogicAppsUX/assets/4062119/afdde439-8170-414b-be6f-b9826a30523f>) 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/4062119/f30bcc75-0d51-4054-998a-a610ff2a0c9f>)

### Browser 

MacOS Edge Version 119.0.2151.97 (Official build) (arm64)

### Additional context 

*No response*

AB#26025027

**Comment by rllyy97** [comment]
After talking to some folks that worked on the `testLink` logic this appears to be controlled by the connector owner, and would need to be fixed by them.
However I just tried to repro and it looks like this has been fixed!
Let us know if you have any other difficulties.

**Comment by Mark-Pearson-APD** [comment]
I appear to be having the same issue as above, all teh same details aprt from i'm using a firefox browser - 122.0 (64-bit

**Comment by rllyy97** [comment]
I'm also seeing this issue again, reopening for investigation.

**Comment by rllyy97** [comment]
Looks like the test request is failing specifically when run through our batch api, replicating the request without it returns data as expected and avoids the error

**Comment by Mark-Pearson-APD** [comment]
Appologies @rllyy97, How do i go about making this connection work now within the LogicApp itself? I;m not sure what you mean by removing the batch API, as i don't see that option within the Workflow option?

**Comment by rllyy97** [comment]
@Mark-Pearson-APD, it was an issue on our side!  You shouldn't have to change anything to have it work again, the change is a part of our next release and should be live in all regions by EoD Feb 16th.  Until then I'd recommend using [our fallback url](https://aka.ms/lafallback) to access legacy designer to create your connection.  Once the connection is created it should work fine over in new designer.

**Comment by Mark-Pearson-APD** [comment]
@rllyy97, thanks, I'm getting a permissions error now, So i will look at creating a new API key specific for this purpose. Any idea on what specifically needs to be granted? If this is outside of your support scope then no worries.

**Comment by rllyy97** [comment]
I don't know what would need to be granted sorry

**Comment by adelmo-chl** [comment]
Hi, sorry to post on an closed thread
I'm facing the same issue and the fallback url goes back to the portal, can you confirm that the fix went live at Feb 16th?

**Comment by rllyy97** [comment]
Hi @adelmo-chl, we had a small delay to some of our regions, so depending on your region you might not yet have the fix.  We will be finishing up our release to all regions by EoD Tuesday.  Please try again sometime late Tuesday / Wednesday and if you're still seeing the issue let me know and I'll look into it more!

**Comment by adelmo-chl** [comment]
hi @rllyy97 the error has changed, but I don't know if it's related to this issue or a new one:
![image](https://github.com/Azure/LogicAppsUX/assets/137422404/41339cb6-c0b1-4cf4-a4f7-e267944244c0)

**Comment by Mark-Pearson-APD** [comment]
Hi @adelmo-chl ,

I have tested mine today and all appears to be working as expected. So i would assume that this error you are seeing is not related to this issue. But i could of course be wrong.

**Comment by rllyy97** [comment]
@adelmo-chl I'm also seeing this issue, but I'm seeing it in preview and legacy designer, this might be an issue with our backend, I'll look around and let you know what I find

**Comment by rllyy97** [comment]
Closing this in favor of a separate ICM that was opened. https://github.com/Azure/LogicAppsUX/issues/4260
