### ISSUE TITLE
SQL Action test case failing with error message='Incorrect syntax near 'SalesLT'

### ISSUE THREAD

**Issue by ramya894** [Azure/LogicAppsUX#3787]
### Describe the Bug with repro steps

1.Create a new workflow app using VS Code.

2.Create a stateful workflow

3.Add a HTTP trigger to the workflow and save the workflow

4.Add an "Execute Query" action after the trigger

5.Verify that connection creation is valid,  you should provide the connection string you have WITH the password in the connection string.

6.After connection is successfully created, you should be able to fill out the input of the action. This is where you would add your query and any query parameters.

7.added the query
 SELECT TOP 20 pc.Name as CategoryName, p.name as ProductName
FROM SalesLT.ProductCategory pc
JOIN SalesLT.Product p
ON pc.productcategoryid = p.productcategoryid;

8.Get the trigger URL by going to the "overview" page for the workflow

9.Using postman to call the trigger URL, run failed with error.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Execute_query": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "query": "SELECT TOP 20 pc.Name as CategoryName, p.name as ProductNameFROM SalesLT.ProductCategory pcJOIN SalesLT.Product pON pc.productcategoryid = p.productcategoryid;"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "sql-6",
                        "operationId": "executeQuery",
                        "serviceProviderId": "/serviceProviders/sql"
                    }
                },
                "runAfter": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![sqlacerror](https://github.com/Azure/LogicAppsUX/assets/52390408/1b6b5831-c1ac-4e9e-b8c1-867beeb6d070)

### Browser

VSIX version: 2.86.0

**Comment by hartra344** [comment]
@Eric-B-Wu can you take a look? It looks like when we're serializing we may be removing new lines in this case.
