### ISSUE TITLE
Consumption: Using existing Sentinel API connection with User Assigned MI causing LA save failure

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#3801]
### Describe the Bug with repro steps 

1. Create a user assigned MI and assign to Logic App 
2. Create 2 Sentinel API connections with user assigned MI in Logic App, use one of the 2 Sentinel connections for the Sentinel action and then save the Logic App 
3. Open designer again then switch to the other Sentinel API connection, after click save button, we can see the exception

![image](<https://github.com/Azure/LogicAppsUX/assets/49498706/5f1d90c9-5964-46ae-aed4-6d949daa99bb>) 

Note: The issue does not repro with the preview designer.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

Old Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
If anyone runs into this, the suggestion for now is to use preview designer.
