### ISSUE TITLE
Incorrect translation in UI

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#3805]
### Describe the Bug with repro steps 

This happens in the new designer. It happens to both Power Automate UI and logic app UI.

Create a workflow in English and then change the portal language to French for example, you will see this UI.

![image](<https://github.com/Azure/LogicAppsUX/assets/49498706/49e0f34f-bf7f-4ff0-8f6e-081a7769edb4>)

However, on the left side marked in red - appears Parameters, Testing and About in English

Also, the second tab which is Parametres in French should be Settings

Another example:

![image](<https://github.com/Azure/LogicAppsUX/assets/49498706/eb1fca52-91f0-4bc9-b5e8-63f74e320b74>)

### What type of Logic App Is this happening in? 

Power Automate

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
We can fix parts where English isn’t being translated but as a team we don’t have much insight or control into what the translation is. It’s a central automated service. We do our best to provide descriptive context with every string, but that’s the best we can do.

**Comment by hartra344** [comment]
Actually it looks like these are getting properly translated overall but something is getting lost when included in portal. I'll mark this as a bug to get looked at.

**Comment by jaimereyesmx** [comment]
@hartra344, Is there an update on when this issue will be resolved?

**Comment by hartra344** [comment]
THe problem is that after a quick look into this, they are being translated correctly, they just arent being used/injected into the UI. It's something that will get looked at but it's somehting deeper going on in the build system I think which may take some time. so no ETA at the moment
