### ISSUE TITLE
Local changes being discarded when navigating away from workflow designer.

### ISSUE THREAD

**Issue by brad302** [Azure/LogicAppsUX#3809]
### Describe the Bug with repro steps

1. Open an existing workflow in VS Code.
2. Change it in some way, i.e. add or remove a step.
3. Navigate away from the workflow designer to another workflow.
4. Go back to that workflow, the workflow refreshes back to the original prior saved state.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
N/A
```

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/14899088/7ee534a7-a611-4b36-aec6-d0990aab7d22

### Browser

Chrome

### Additional context

It has a tendency to be quite annoying after having made numerous changes and then losing them all because you forget to save before navigating away.

**Comment by hartra344** [comment]
This is a known issue tracked here #2908

**Comment by brad302** [comment]
Thanks @hartra344 ... kinda figured it was tracked somewhere but my searching yielded limited results and not that issue.
