### ISSUE TITLE
Dependency validation - failed to find tasks.json

### ISSUE THREAD

**Issue by mcollier** [Azure/LogicAppsUX#3822]
### Describe the Bug with repro steps

Open opening a Logic App Standard project in VSCode, with the Logic App Standard extension enabled, I notice the following error:
```
6:13:15 PM: Azure Logic Apps Standard Runtime Dependencies validation and installation completed successfully.
6:13:15 PM: Error: Failed to find: /workspaces/logic-app-std-pg01/src/.vscode/tasks.json
```
The error message is correct in that the `tasks.json` file does **not** exist. Should the Logic App Standard extension create the file if it doesn't exist?

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Not applicable - VSCode.

### Additional context

**Visual Studio Code**
Version: 1.85.0 (user setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.23545

**Logic App Standard**
ms-azuretools.vscode-azurelogicapps
v2.81.5

**Comment by ccastrotrejo** [comment]
Hi @mcollier, thanks for raising this issue. Yes, when a logic app project its created the `tasks.json` file should be created inside the `/.vscode` folder in the root path of the project. This file is needed when running/debugging the workflows. 

I am curious since you don't have it, aren't you experiencing any troubles running the workflows?
Also, regarding the path in the output it seems that its a vscode workspace. Do you have  multiple logic app projects within the workspace? or is it just the name of the folder?

**Comment by ccastrotrejo** [comment]
@mcollier We determine a logic app project root path, the same root path in which the `host.json` file is located. The `host.json` file help us to execute the extension bundle. That being said, we look for the a `/.vscode/tasks.json` in the logic app root project path. This means that the file should be inside the src folder. 

Does the launch and tasks works fine for you even if the `/.vscode` is outside the `src` folder?

**Comment by mcollier** [comment]
I've noticed if I put the `.vscode` folder inside the `src` folder, the Logic App Standard extension doesn't generate the `Failed to find: /workspaces/logic-app-std-pg01/src/.vscode/tasks.json` error message.  However, VS Code doesn't pick up the tasks.  

If I put the `.vscode` folder at the root, VS Code picks up the tasks, but I get the error message.

_Note: I'm attempting to run this from a VS Code dev container._
