### ISSUE TITLE
VS Code Dark Mode - Designer Data/Expression Colors Very Poor Contrast

### ISSUE THREAD

**Issue by axiomitdavid** [Azure/LogicAppsUX#3826]
### Describe the Bug with repro steps

When using a VS Code theme that is using a dark background, the color chosen to display the UI makes it impossible to see UI elements without moving the cursor over the element

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
Not relevant
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/41350688/07249bb2-2184-4cba-a6a1-fc508afd5eb6)

### Browser

Edge

### Additional context

Accessibility standard issue ?

**Comment by hartra344** [comment]
@ccastrotrejo can you take a look?
