### ISSUE TITLE
Visual Studio Code Designer folder workflow-designtime duplicated

### ISSUE THREAD

**Issue by timjansenortec** [Azure/LogicAppsUX#3827]
### Describe the Bug with repro steps

1. Open Visual Studio Code
2. Install Logic App Standard extension
3. Create a new logic app
4. Convert logic app to NuGet based app
5. Run designer

after this I have the following folder structure:
```
.vscode
  extensions.json
  launch.json
  settings.json
  tasks.json
Artifacts
  Maps (empty)
  Schemas (empty)
lib
  (with bunch of empty folders)
Properties
  launchSettings.json
Stateful1
  workflow.json
workflow-designtime
  workflow-designtime <- duplicate
    host.json <- duplicate for designer
    local.settings.json <- duplicate for designer
  .funcignore
  connections.json <-- duplicate from root
  host.json
  local.settings.json  
.gitignore
host.json
local.settings.json
logicapp.csproj
```
As you can see above the workflow-designtime folder is duplicated. Also the files host.json and local.settings.json are duplicated, these files exist in 2 places for the designer.

In the past workflow-designtime looked like this:
```
workflow-designtime
  host.json
  local.settings.json  
```
So also the connections.json file has been moved/duplicated into the workflow-designtime folder. Is this intentional?

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

N.A.

**Comment by ccastrotrejo** [comment]
Hi @timjansenortec Thanks for raising this issue. I tried to repro but couldn't do it. Was there any other action/step you did? Is this a consistent behavior whenever you Convert logic app to NuGet based app?

**Comment by ccastrotrejo** [comment]
ohhh I was able to repro it now. I will work on fixing this issue
