### ISSUE TITLE
LogicApps designer slow

### ISSUE THREAD

**Issue by KarlVilhelm** [Azure/LogicAppsUX#3828]
### Describe the Bug with repro steps

Trigger: Scheduled flow

1. Get rows from SQL
2. For each row from SQL
3. Get a row from SQL
4. Add row in Microsoft Dataverse

The designer mode is unbelievable slow, not able to modify Logic App through designer mode at all. 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Microsoft Edge, Google Chrome

**Comment by hartra344** [comment]
Is this the only steps you have? Can you tell us more about the full workflow? How many actions? What kind of computer are you running on? We definitely want to make sure we are able to address any performance issues but with just the steps you described, I'm not able to see any issues.
