### ISSUE TITLE
It would be better if we have reverse engineering

### ISSUE THREAD

**Issue by SRGuptha** [Azure/LogicAppsUX#3835]
### Describe the Bug with repro steps

I have XSLT, but I am not able to do reverse engineering using the existing XSLT with the data mapper, if any option there please do let me know

### Version

V2.2

### Additional context

I have XSLT, but I am not able to do reverse engineering using the existing XSLT with the data mapper, if any option there please do let me know

**Comment by kewear** [comment]
Hi @SRGuptha - currently this is not possible. Can you explain a bit more about your scenario? Are these BizTalk maps or from another platform?
