### ISSUE TITLE
Cannot save due to left-over trigger error

### ISSUE THREAD

**Issue by tdutch1** [Azure/LogicAppsUX#3850]
### Describe the Bug with repro steps 

1. Create a Logic App workflow (in a Logic App Standard resource) 
2. In the designer, select HTTP as the trigger (I did this by accident). Try to save and the message will indicate that a URI is required. 
3. Remove the HTTP action and add a "When a request is received" as the trigger. Set the required properties. 
4. The save button is still disabled and the Errors button still shows the original trigger problem, even though the HTTP action is no longer part of the workflow. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http",
        "inputs": {
          "schema": {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "properties": {
              "ClaimId": {
                "type": "string"
              },
              "ProcessDate": {
                "type": "string",
                "format": "date"
              },
              "ProgramCode": {
                "type": "string"
              },
              "ProcedureNumber": {
                "type": "integer"
              },
              "ProcessType": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "FullVIN": {
                "type": "string"
              }
            },
            "required": [
              "ClaimId",
              "ProcessDate",
              "ProgramCode",
              "ProcedureNumber",
              "FullVIN"
            ]
          },
          "method": "POST"
        }
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

*No response*

**Comment by Eric-B-Wu** [comment]
@tdutch1 thanks for reporting this issue, I'll look to get this fixed in our next release, but the next release will likely be at the start of next year

**Comment by Eric-B-Wu** [comment]
Should be fixed now
