### ISSUE TITLE
Data map loads but mapping is gone

### ISSUE THREAD

**Issue by romlodihc** [Azure/LogicAppsUX#3862]
### Describe the Bug with repro steps

I have created a data map where is map and array in xml to an array in json. The mapping is showing me an error (also tried to map in to the presenceHours in this scenario but then nothing works) but creating an XSLT works and the output is valid. However, when I save this map and reopen it, the mapping is completely gone. If I then save it again, all of my other mappings are gone.

Initial development which works.
![error-but-xslt-works](https://github.com/Azure/LogicAppsUX/assets/152623217/b8220f98-e1c2-4f37-b868-dd635cd89bb6)

After saving and reopening it:
![mapping-gone-after-saving](https://github.com/Azure/LogicAppsUX/assets/152623217/66c47025-16df-489b-943d-ec6e7956976b)

The Report_Entry has a maxOccurs unbounded and a type complex. Mapping it to the error presenceHours fails with warning:
Warning: input node type does not match the schema node's type
XSLT is generating but no output.

When mapping to the arrayItem, an error/warning occurs but cannot be seen. XSLT generates well. Mapping works.

### Version

[v2.86.4]

**Comment by romlodihc** [comment]
I've done some extra tests. It has to do with the xpath function in de data mapper. It is a valid one, I also created the XSLT from it, so it seems to fail after adding and saving the data mapper with the xpath function.

**Comment by DanielleCogs** [comment]
This seems to be an issue with the frontend converting an LML file into a map when the source is xsd and the target file type is json. Most likely will require a code fix. Please expect a delay as it is the holidays, but we will be prioritizing this. I'll update here if I find a reasonable workaround to help until the fix is released.
