### ISSUE TITLE
Unable to add a schema to the Data Mapper designer 

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/LogicAppsUX#3863]
### Describe the Bug with repro steps

I am unable to add a schema when creating a map.

Reproduction steps:

1. Create a new Logic App project
2. Close and reopen VSCode
3. Add schema.json to folder \Artifacts\Schemas
```json
{
  "type": "object",
  "properties": {
    "prop1": {
      "type": "string"
    }
  }
}
```
2. Choose Data Mapper: Create new data map
3. Designer surface shows. Click Add a source schema
4. Choose Select existing and select schema.json.
5. Click Add. 

Nothing happens until I click Cancel.

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/9644248/08e5465a-8343-4140-a579-466932b6a69b)

### Version

v2.86.4

Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554

### Additional context

I have tried with the host.json and local.settings.json according to [Logic Apps Data Mapper - Compiling and Testing Your Map](https://techcommunity.microsoft.com/t5/azure-integration-services-blog/logic-apps-data-mapper-compiling-and-testing-your-map/ba-p/3995075) and local.settings.json according to [Data Mapper for Azure Logic Apps (Standard) reaches General Availability](https://techcommunity.microsoft.com/t5/azure-integration-services-blog/data-mapper-for-azure-logic-apps-standard-reaches-general/ba-p/3982731). Restarted VS Code between each attempt.

It would really help if these articles had similiar local.settings.json files.

**Comment by DanielleCogs** [comment]
@ErikMogensen thank you for reporting this! We found the cause of the problem, and will be releasing a hotfix shortly. Until then, you can fix this by editing '{your-project}/workflow-designtime/local.settings.json' to remove 'workflow-designtime' from 'ProjectDirectoryPath'

![image](https://github.com/Azure/LogicAppsUX/assets/99753874/dbb0e093-9a01-46df-9714-8afc0edcedfd)

**Comment by ErikMogensen** [comment]
Are you able to see my comment above @DanielleCogs or should I create a new issue? 

I should mention that I never had  'workflow-designtime' in my 'ProjectDirectoryPath'.

**Comment by ccastrotrejo** [comment]
Hi @ErikMogensen, do you still have the issue after updating the `ProjectDirectoryPath` in the `workflow-designtime/local.settings.json` directory? or you just simply doesn't have the `workflow-designtime` directory?

Also, just to mention the fix for the new extension version will be only affect when you create a new logic app project, therefore if you have already created prior this new version you will need to update the property as stated above

**Comment by ErikMogensen** [comment]
Ah! I didn't realize there was another local.settings.json file! After removing 'workflow-designtime' from  the ProjectDirectoryPath and restarting vs code it worked 🎉

**Comment by ccastrotrejo** [comment]
@ErikMogensen I am glad it worked fine! :)
