### ISSUE TITLE
Strings are not localized for Indonesia

### ISSUE THREAD

**Issue by Aleks-gdb** [Azure/LogicAppsUX#3866]
### Describe the Bug with repro steps

Different components in the designer are missing loc strings, see screenshots below

### What type of Logic App Is this happening in?

Power Automate

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/42044630/54974a18-6738-4cf5-bbbc-aa09da1bc4bc)
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/3ffd0729-9c55-4e66-8181-eafc8202892d)
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/8b4deb70-5c5e-4e18-bd84-3a24f57cd213)
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/e505bf20-7709-44bb-9c3d-a4ed4403e759)
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/04000d60-1168-40c7-81b6-b7981e301b53)

### Browser

Edge

**Comment by Eric-B-Wu** [comment]
hmm it looks like we have the translation, but we just dont use it in our intlprovider, I can go ahead and add that

**Comment by Eric-B-Wu** [comment]
Fixed in https://github.com/Azure/LogicAppsUX/pull/3868
