### ISSUE TITLE
Feature request: Add code/setting to automatically start Azurite when it is needed (i.e. not already running and debugging)

### ISSUE THREAD

**Issue by MrRosendahl** [Azure/LogicAppsUX#3889]
### Describe the Bug with repro steps

In VS Code:
1. Create a new Logic apps project in a folder
2. Choose standard logic app and leave the default name as workflow
3. Install logic apps standard extension with the default settings, (start azurite when workflow loads)
4. Close the folder
5. Open the folder, now pretending you Only need to view/edit some bicep or the workflow Json or some config, i.e. nothing that requires that the Azurite service is running.

... Azurite starts, _¤%@£$"!!_, I have to close the popups manually again.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
N/A
```

### Screenshots or Videos

![Azurite-popups](https://github.com/Azure/LogicAppsUX/assets/29914665/f300004a-3715-4b77-bbd5-ff0972376f06)

### Browser

N/A

### Additional context

I really do not like the Azurite popups which you have to **MANUALLY CLOSE** every time a project loads, it might be great when debugging the Azurite extension, but please, close them, or better yet don't show them at all when everything works, or perhaps a setting for that too. It is frustrating to have to close the popups manually every time I open a logic apps project... and opening alot of projects every day... well, _¤%@£$"!!_ 

I know that "manually staring Azurite" or always try to start Azurite is the easier solution which requires little logic to get working. But since you have that working already, a better approach (in my opinion) would be to detect when Azurite actually has to be started, i.e. when debugging is pressed AND if Azurite is not already running on the computer.

_We all have a finit number of keypresses in life... let's make the best use of them!_

**Comment by ccastrotrejo** [comment]
Hi @MrRosendahl thanks for raising this issue. I will bring this issue to the table and discuss the best approach to tackle it. I took a look at the Azurite extensions setting and couldn't find any setting to disable the logs when their services get initialized. I will reach out in the thread as soon as there is any response
