### ISSUE TITLE
VS Code extension does not sync between computers

### ISSUE THREAD

**Issue by mikaelsand** [Azure/LogicAppsUX#3906]
### Describe the Bug with repro steps

1. Installed The VS Code extension on my work laptop, and are having [issues](https://github.com/Azure/LogicAppsUX/issues/3899)
2. Thinking it might be the work laptop's fault, I turned on syncing and opened up VS Code on my gaming rig.
3. All extensions synced.
4. The Logic Apps standrad extension does not work because it is looking for its dependencies using a path that does not exist. It looks for the dependencies in the user folder from my worklaptop. That folder does not exist outside of my worklaptop.
5. It does not try to install the dependencies...

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

egde

**Comment by ccastrotrejo** [comment]
Hey @mikaelsand thank you so much for raising this issue. What is happening is that VS Code is indeed synchronizing the extensions and their configurations between your work and personal computer. That might be the reason your personal computer has a path that only exists in your work computer.  Unfortunately, that might be a more VS Code oriented issue.

As a workaround to force your personal computer to install the binaries and set the right path in your personal computer you can do the following:

1. `Ctrl`+`Shift`+`P` -> Reset binaries dependency settings
2. Restart vscode
3. Logic Apps Extension will ask if you would like to install the binaries dependencies and accept.

Let me know if this doesn't work for you

**Comment by mikaelsand** [comment]
(Sorry I was off for the holidays)
That is some next level stuff. Thank you, it worked :-)
