### ISSUE TITLE
Cannot use Azure connectors from VS Code

### ISSUE THREAD

**Issue by mikaelsand** [Azure/LogicAppsUX#3915]
### Describe the Bug with repro steps

1. After days of issues I updated the function core tools to the latest version and everything started working.
2. I followed [these instructions](https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#add-the-request-trigger) on how to create a logic app and a standard workflow (I have done it before but figured I might need a restart).
3. When opening the designer I was asked if I wanted to use Azure Connectors. I said yes, and filled out the name of a resource group and a location.
4. I added the request trigger but there is no Office 365 action. There are NO Azure Connector Actions (see screen shot).
5. I used ctrl+p and typed "Use connectors from Azure". I got back "Azure connectors are enabled for the workflow". Still no connectors.
6. I reloaded the designer, no connectors.
7. I reloaded vs code, still no connectors.
8. I created a brand new project and started over, still no connectors.
9. This all worked before by the way. I have created this exact same workflow before.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

<img width="476" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/20858407/6a7dfc40-574b-4911-9a44-765b85129111">

### Browser

Using VS code, so no browser.

**Comment by ccastrotrejo** [comment]
Hi @mikaelsand, thank you so much for raising this issue. We use the `WORKFLOWS_SUBSCRIPTION_ID` in the local.settings.json to enable the azure connectors in the designer locally. Could you please let me know if the value of that setting in your local.settings.json is different from an empty string? or if it is indeed the subscription id from the resource group you want to choose?

**Comment by mikaelsand** [comment]
@ccastrotrejo Thank you! That worked like a charm. Sorry for the late reply. Holiday break.

The local.settings.json was populated with information form the account I use for private things. I was connected to the Azure Resources extension, so I guess you guys pick up the settings from there.

The extension defaults to my private account (since I use that for syncing settings for instance).
