### ISSUE TITLE
Error configuring services in an external startup class. Microsoft.Azure.Workflows.WebJobs.Extensions

### ISSUE THREAD

**Issue by danielenriquez** [Azure/LogicAppsUX#3922]
### Describe the Bug with repro steps 

1-Open Logic App in Visual Studio Code designer

 2- Azure Function core tools latest version 4.x

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Local host, Chome

### Additional context 

Error configuring services in an external startup class. Microsoft.Azure.Workflows.WebJobs.Extensions: Could not load type 'Microsoft.Azure.WebJobs.Host.Listeners.IListenerDecorator' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

 [2024-01-02T09:19:56.417Z] A host error has occurred during startup operation '3d9931ed-314b-404a-b023-4c81d0086ea0'.

 [2024-01-02T09:19:56.417Z] Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Microsoft.Azure.Workflows.WebJobs.Extensions: Could not load type 'Microsoft.Azure.WebJobs.Host.Listeners.IListenerDecorator' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

 Value cannot be null. (Parameter 'provider')

**Comment by kaivanengineer** [comment]
I am also facing same issue. Is there any solution?

**Comment by ccastrotrejo** [comment]
Hi all, thanks for raising this issue. It does seem that this is related/duplicated to this https://github.com/Azure/logicapps/issues/943. I know that the issue says that you are using the latest Azure Functions Core tools version 4.x, however, could you please double check that is indeed the 4.0.5455 version or newer?

If issue is still happening, please let me know and I will take a further look. Thanks!

**Comment by jonesbratconed** [comment]
I have downloaded and installed v4.0.5455, but when running I see this in the output:
Azure Functions Core Tools
Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667

Is there a version we should revert to until this can be resolved?

**Comment by ccastrotrejo** [comment]
Hi @jonesbratconed it seems that you are getting two different versions installed. Unfortunately, there isn't an Azure Logic Apps (Standard) extension that you can revert to, both softwares are handled independently.

Starting with version 2.81.5, the Azure Logic Apps (Standard) extension for Visual Studio Code includes a dependency installer that automatically installs all the required dependencies in a new binary folder. You can check the complete documentation [here](https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#tools) and learn more about this new feature [here](https://techcommunity.microsoft.com/t5/azure-integration-services-blog/making-it-easy-to-get-started-with-the-azure-logic-apps-standard/ba-p/3979643).

That been said, it looks like the function core tools the extension is executing is the one installed in the dependencies folder. Could you please check if the func core tools that it's executing has the following path? `C:\Users\<your-user-name>\.azurelogicapps\dependencies\FuncCoreTools\func`

**Comment by jonesbratconed** [comment]
We can't install much on C:\ so we use the F:\.  In VS Code the value for Azure Logic Apps Standard: Func Core Tools Binary Path is F:\Users\<your-user-name>\.azurelogicapps\dependencies\FuncCoreTools\func and the DLL has a date of 5/20/2023.

Here is my output:
7:46:22 PM: Running command: "F:\Users\JONESBR\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "32752"...
NodeJs Binaries: F:\Users\JONESBR\.azurelogicapps\dependencies\NodeJs

Azure Functions Core Tools
Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667

FuncCoreTools Binaries: F:\Users\JONESBR\.azurelogicapps\dependencies\FuncCoreTools
[2024-01-09T00:46:29.546Z] Found f:\Repos\LogicApp\logic-dev.csproj. Using for user secrets file configuration.
[2024-01-09T00:46:32.172Z] Error configuring services in an external startup class.
[2024-01-09T00:46:32.172Z] Error configuring services in an external startup class. Microsoft.Azure.Workflows.WebJobs.Extensions: Could not load type 'Microsoft.Azure.WebJobs.Host.Listeners.IListenerDecorator' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2024-01-09T00:46:32.223Z] A host error has occurred during startup operation 'c735c9c2-991f-48f5-ade7-2c8ac8514c59'.
[2024-01-09T00:46:32.309Z] Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Microsoft.Azure.Workflows.WebJobs.Extensions: Could not load type 'Microsoft.Azure.WebJobs.Host.Listeners.IListenerDecorator' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Value cannot be null. (Parameter 'provider')
[2024-01-09T00:46:32.384Z] Host startup operation has been canceled
[2024-01-09T00:46:32.469Z] Azure Storage connection string is empty or invalid. Unable to write diagnostic events.
DotNetSDK Binaries: F:\Users\JONESBR\.azurelogicapps\dependencies\DotNetSDK
Local binary .NET SDK version 6.0.417
7:47:52 PM: Azure Logic Apps Standard Runtime Dependencies validation and installation completed successfully.

**Comment by RensBraksh** [comment]
> F:\Users\JONESBR\.azurelogicapps\dependencies\FuncCoreTools\func

I didn't get the pop up message, but removing the folder did the trick for me. Thanks!

**Comment by jonesbratconed** [comment]
I've seen and executed the pop-up, but after deleting the dependencies folder and re-launching VS Code, I have the following output showing it is installing version **4.0.5198**

11:08:25 AM: Running command: "F:\Users\JONESBR\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "50692"...
The system cannot find the path specified.
NodeJs Binaries: F:\Users\JONESBR\.azurelogicapps\dependencies\NodeJs
Creating temporary folder... C:\Users\JONESBR\AppData\Local\Temp\.azurelogicapps\NodeJs
Downloading binaries from: https://nodejs.org/dist/v18.17.1/node-v18.17.1-win-x64.zip
Successfullly downloaded NodeJs binaries.
Extracting C:\Users\JONESBR\AppData\Local\Temp\.azurelogicapps\NodeJs\NodeJs.zip
Extraction NodeJs successfully completed.
Removed C:\Users\JONESBR\AppData\Local\Temp\.azurelogicapps\NodeJs
FuncCoreTools Binaries: F:\Users\JONESBR\.azurelogicapps\dependencies\FuncCoreTools
Creating temporary folder... C:\Users\JONESBR\AppData\Local\Temp\.azurelogicapps\FuncCoreTools
**Downloading binaries from: https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.5198/Azure.Functions.Cli.win-x64.4.0.5198.zip**
11:10:50 AM: Error in dependencies validation and installation: "{0}"...
Successfullly downloaded FuncCoreTools binaries.
Extracting C:\Users\JONESBR\AppData\Local\Temp\.azurelogicapps\FuncCoreTools\FuncCoreTools.zip
Extraction FuncCoreTools successfully completed.
Removed C:\Users\JONESBR\AppData\Local\Temp\.azurelogicapps\FuncCoreTools

![image](https://github.com/Azure/LogicAppsUX/assets/97191115/93784aed-6719-4509-98b9-4f88526375ac)

**Comment by jonesbratconed** [comment]
I manually downloaded the zip for 5455 and extracted to the dependencies folder.  This resolved the problem.  Still uncertain why the dependency installer didn't install the correct version.

**Comment by jonesbratconed** [comment]
That was from the output.  This was in the Terminal, but not sure datetime logged:
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS F:\Repos\LogicApp> func --version
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\JONESBR\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin/func ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\JONESBR\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\bin/func',
  path: 'C:\\Users\\JONESBR\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\bin/func',
  spawnargs: [ '--version' ]
}

Node.js v18.16.1

**Comment by ccastrotrejo** [comment]
Hi @danielenriquez Is this issue still happening?

**Comment by jonesbratconed** [comment]
I was able to do the latest upgrade today and can still open the designer and everything seems to be working as expected.

**Comment by ccastrotrejo** [comment]
@jonesbratconed Good to hear that. I will close the issue if anyone experiences this error again, I will reopen it and take a further look.
