### ISSUE TITLE
Logic Apps Consumption new designer doesn't display all connectors for staging region

### ISSUE THREAD

**Issue by ynauls** [Azure/LogicAppsUX#3924]
### Describe the Bug with repro steps

This is a canary (or staging) region.  Region can be access in Logic Apps PM subscription.

1. Go to Logic Apps PM subscription.
2. Create logic App Consumption in "east us (stage)" region
3. Add Http Trigger
4. Try to add non built-in (shared or custom) action.

In new designer, only "built-in" connectors are available, in old designer, all connectors are displayed

## new designer
![image](https://github.com/Azure/LogicAppsUX/assets/10816194/6bd63e8f-a2dc-47c0-a718-c52357186fc6)

## old designer
![image](https://github.com/Azure/LogicAppsUX/assets/10816194/720ad578-0a96-4046-9295-7ba70c292e1e)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

## new designer
![image](https://github.com/Azure/LogicAppsUX/assets/10816194/6bd63e8f-a2dc-47c0-a718-c52357186fc6)

## old designer
![image](https://github.com/Azure/LogicAppsUX/assets/10816194/720ad578-0a96-4046-9295-7ba70c292e1e)

### Browser

Edge Version 120.0.2210.91 (Official build) (64-bit)

**Comment by rllyy97** [comment]
This appears to be an issue with the region ID when it's part of resource IDS we get back from our apis, in some places it has the parenthesis: `eastus(stage)` and in others it does not `eastusstage`, so when we have to exact match certain ids it causes issues.
