### ISSUE TITLE
Can't start the background design-time process

### ISSUE THREAD

**Issue by yunn246** [Azure/LogicAppsUX#3925]
### Describe the Bug with repro steps

The background design-time is set to auto start, but vscode cannot start it anymore.
Since this appears, data mappers that are created previously are missing all connections and cannot load schemas. 

### Screenshots or Videos

When VSCode is opened
![image](https://github.com/Azure/LogicAppsUX/assets/91293619/69bebdc7-8199-4510-8ab5-65589b285d6a)

When I try to load data mapper
![image](https://github.com/Azure/LogicAppsUX/assets/91293619/6f4ed719-a760-46e8-8d90-1bef4e67cfe9)

### Version

- Extension version [v2.86.5]

**Comment by ccastrotrejo** [comment]
Hi @yunn246 thank you so much for raising this issue, it seems that command we use to from functions core tools to start the design time process its failing. Is there any chance we can get a screenshot from the terminal and from the output console log in vscode when this issue is happening?

**Comment by yunn246** [comment]
Hi, I don't see anything in terminal, but here are screenshots from the output when the issue happened. I was trying to open an existing lml in data mapper. 
![image](https://github.com/Azure/LogicAppsUX/assets/91293619/a3ab4887-48b6-4cbb-aa20-3e30258b3878)
![image](https://github.com/Azure/LogicAppsUX/assets/91293619/4a1e0fa5-db48-4aa7-9cba-5895297a61dd)

**Comment by ccastrotrejo** [comment]
Hi @yunn246 it does seem that the azure functions core tools version is the one having troubles. Checking the binaries installation after opening vscode should install/update the function core tools automatically, it does looks like something is wrong with updating it. To get the latest versions, as a workaround, could you please remove the complete folder `C:\Users\yuw\.azurelogicapps\depedencies` and restart vscode? This will install the latest version. 

I will work on try to fix this issue. Thanks!

**Comment by ccastrotrejo** [comment]
Hi @yunn246 I was able to repro the exact same scenario. Azure Logica Apps extension will ask the user to update azure function core tools whenever this extension setting is set to true. Could you verify if this setting is set to true? 
Therefore a popup will appear in the UI asking if you would like to update function core tools and you would need to update it
<img width="804" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/ac209f0a-6738-459a-a983-69ebe5a300ce">

<img width="488" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/d5546ee8-c67d-4293-a243-2861b16ac574">

**Comment by yunn246** [comment]
Hi @ccastrotrejo, I checked the setting and it's already set to true. I didn't see the warning message pop-up. 
![image](https://github.com/Azure/LogicAppsUX/assets/91293619/25b5730c-1182-4755-aa16-88f477696ab7)
I have also tried remove the dependencies folder and let it install automatically, but background design-time process still can't start.

**Comment by ccastrotrejo** [comment]
@yunn246 Does the output logs say something about the function core tools?
