### ISSUE TITLE
Multi select drop down is not showing options in new designer

### ISSUE THREAD

**Issue by kbsaravana** [Azure/LogicAppsUX#3931]
### Describe the Bug with repro steps

we noticed multiselect dropdown in action's parameter don't show values in new designer. I can repro the issue in Azure portal. 

we have this "Severity" parameter in our custom connector action, which allows multi select. This is working fine in the old designer.
![image](https://github.com/Azure/LogicAppsUX/assets/10658378/6cfda3c2-1c55-415f-8548-d9fc7402c8cf)

connector json is defined as below given for that "Severity" parameter. 
![image](https://github.com/Azure/LogicAppsUX/assets/10658378/a64a071d-50a5-41ea-8d7c-36e25e11cb73)

but when the same logic app is opened in the new designer, drop down options are not shown in Azure portal. 
![image](https://github.com/Azure/LogicAppsUX/assets/10658378/c04b8787-d88b-4fcf-9dcf-8692df8e4603)

I see this error for opening the same logic app with new designer in my local box,
![image](https://github.com/Azure/LogicAppsUX/assets/10658378/e0ec9a94-c0b4-4038-a3df-5e255978c2f4)

could you please check this issue with priority. This is a P0 scenario for usage of our custom connector. 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

**Comment by hartra344** [comment]
@Eric-B-Wu  can you take a look?
