### ISSUE TITLE
Copy Pasting the Code View from one workflow to another causes the new workflow(created by copy pasting the code) desginer UI to fail in Standard Logic Apps

### ISSUE THREAD

**Issue by nidubey1** [Azure/LogicAppsUX#3935]
### Describe the Bug with repro steps 

1. Create a Standard Logic Apps and use the below workflow definition JSON to create a new Stateful Workflow in it(use the UI to create a similar design if possible) and save it. The workflow design will look something like this: 

![image](<https://github.com/Azure/LogicAppsUX/assets/85997053/9acc3036-90ba-4ad6-8d11-730fdd06cb6c>)

2. Now create another Stateful Workflow in the Same Logic Apps, the go to it's code view and replace it with the definition from the workflow created in above step 1 and save it. 
3. Now go to the new workflow designer or go somewhere else say overview of workflow and come back to new workflow designer created in step 2 by copy paste in code view and try to do some changes, after some time following error screen will come in the designer: 

![image](<https://github.com/Azure/LogicAppsUX/assets/85997053/e035f3f8-4f07-4bd6-985b-5b48cbda93fb>)

4. NOTE: Old designer works fine. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Send_event": {
                "inputs": {
                    "body": {
                        "ContentData": "@{triggerBody()?['ContentData']}",
                        "Properties": {
                            "contentType": "application/json"
                        }
                    },
                    "host": {
                        "connection": {
                            "referenceName": "eventhubs-2"
                        }
                    },
                    "method": "post",
                    "path": "/@{encodeURIComponent('testehub')}/events",
                    "retryPolicy": {
                        "count": 4,
                        "interval": "PT3M",
                        "minimumInterval": "PT3M",
                        "type": "exponential"
                    }
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "metadata": {
            "ExportMetadata": {
                "ExportCorrelationId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                "ExportDate": "2023-09-08T10:15:34"
            }
        },
        "outputs": {},
        "triggers": {
            "When_events_are_available_in_Event_Hub": {
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "eventhubs-2"
                        }
                    },
                    "method": "get",
                    "path": "/@{encodeURIComponent('testehub')}/events/batch/head",
                    "queries": {
                        "consumerGroupName": "$Default",
                        "contentType": "application//json",
                        "maximumEventsCount": 100
                    }
                },
                "recurrence": {
                    "frequency": "Second",
                    "interval": 2
                },
                "splitOn": "@triggerBody()",
                "type": "ApiConnection"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

*No response*

### Browser

- Edge

### Additional context

*No response*

**Comment by nidubey1** [comment]
Hi Team is anyone checking on this? And do we have an ETA on the fix?

**Comment by rllyy97** [comment]
Hi @nidubey1, I'll be looking into this issue today and let you know what I find

**Comment by nidubey1** [comment]
Hi @rllyy97 contributor access has been provided to your official id on the resource which has the repro: "/subscriptions/df36f4f9-0937-428e-9e7d-437124945424/resourceGroups/NDResourceGroup/providers/Microsoft.Web/sites/testLAND2Jan2024"

Original Workflow which works is:  "testLAeHub"
Copied code view workflow is: "testLAeHub-1"

To repro the issue you can either copy paste the original workflow in a new workflow or even go to the designer of the copied code view workflow: "testLAeHub-1" and click on trigger and select "minimum partition key" checkbox and click somewhere else, the issue will occur:

<img width="901" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/85997053/74f12bea-b21f-457d-b15b-2e5ee2fe772b">

**Comment by rllyy97** [comment]
I tried your repro steps on `testLAeHub-1` and the parameters added as expected for me.
I tried a few other things but I'm still unable to repro your issue, could you collect the console and network logs and send them to my email I mentioned before?

Showing the parameter added fine:
![image](https://github.com/Azure/LogicAppsUX/assets/25409734/1a14cbd2-2d8d-4876-84b2-abdb008703c4)

**Comment by nidubey1** [comment]
HI @rllyy97 , the requested network and console logs from repro have been shared over mail.

**Comment by nidubey1** [comment]
Hi @rllyy97 ,do you have any update here?

**Comment by rllyy97** [comment]
I don't have any updates yet sorry, we've been very busy with other work but we still have this on our radar 👍 
I will make an effort to revisit this sometime this week if I have the bandwidth, or I'll have another engineer take a look
Either way we'll provide updates here as soon as we have them, thanks for being patient with us!

**Comment by preetriti1** [comment]
@nidubey1 - Are you still facing this issue? If yes, can you please give access to the app to psamband@microsoft.com?

**Comment by preetriti1** [comment]
@nidubey1 I will have to close this issue as I didnt get any response on the above ask.. We have made lot of fixes and improvements in past few months, please try again if you still face this you can reopen this issue.
