### ISSUE TITLE
action from Microsoft Translator V3 on standard logic app designer freezes in a loading page

### ISSUE THREAD

**Issue by swakMS** [Azure/LogicAppsUX#3940]
### Describe the Bug with repro steps

add an action in logic app standard workflow, choose any action from connector "Microsoft Translator V3" and it just keeps loading and freezes there and doesn't give any details to configure .

if we use fallback url it works there in old designer

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

chrome

**Comment by swakMS** [comment]
customer wants to know why they can’t access the connector using the normal\new portal URL and should they keep using fallback url?

**Comment by swakMS** [comment]
Could you share any updates please?

**Comment by rllyy97** [comment]
Hi @swakMS, @valentina-vallalta is helping look into this, we don't have any updates yet but are currently investigating.
We will provide an update here as soon as we have one, thanks for your patience.

**Comment by valentina-vallalta** [comment]
This change will be a part of our next release, which should be live in all regions by EOD February 2nd
