### ISSUE TITLE
URL not generated after Saved.

### ISSUE THREAD

**Issue by jpteh** [Azure/LogicAppsUX#3961]
### Describe the Bug with repro steps

After saving the LA, the URL is not generated at all.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by hartra344** [comment]
@jpteh can you provide more information? At a base repro, I am not seeing this problem. Is there something different or specific that you are doing?

https://github.com/Azure/LogicAppsUX/assets/13208452/d7c6c8ab-2e70-4ece-8d1e-ff28362227f8
