### ISSUE TITLE
Duplicate token for Select action

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#3967]
### Describe the Bug with repro steps 

Create a flow: Manual -> Get items -> Select -> Compose. In Compose, you'll see 3 tokens in V3, Output, Outputs, Output Item.

In V1, for same flow, you'll see 1 token only Output.

In v3, Output and Outputs are duplicates. I think we should only keep one. This is confusing customers. They both do the same thing.

![image](<https://github.com/Azure/LogicAppsUX/assets/91279975/54fc9f60-e3e7-42de-a933-08d183eb37ae>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by kisubedi** [comment]
![image](https://github.com/Azure/LogicAppsUX/assets/91279975/3f43ca83-c46a-40ff-8150-5e7b30721d99)
Customer comment

**Comment by rllyy97** [comment]
Hi @kisubedi, thanks for the report, I'm actually seeing _all_ actions have the `Outputs` output for some reason, this is not intended and I'll be looking into a fix
I'll give updates here as I have them

**Comment by kisubedi** [comment]
Hi Riley, most actions do need the Outputs token. We only need to deduplicate where needed.
[A screenshot of a computer  Description automatically generated] [A screenshot of a computer  Description automatically generated]


-Kishor

**Comment by kisubedi** [comment]
Actually I can confirm that Filter Array is producing a Outputs token which fails flow save. So this is another one we need to get rid of. I wonder if there's a pattern.

[A screenshot of a computer  Description automatically generated]
