### ISSUE TITLE
On applying filter based on Time interval and clicking on run id, can see Filter is gone and it displays all the run id.

### ISSUE THREAD

**Issue by sonalmoze** [Azure/LogicAppsUX#3974]
### Describe the Bug with repro steps

1. Go to Logic app consumption and overview blade to filter runs with custom time range.
<img width="425" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/143148606/04475c27-2755-4713-aa78-f33d6b95fca2">

2. Filter the runs based on Time interval.
<img width="473" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/143148606/279bef2c-a4ed-41cf-9540-2ff2a3af623d">

3. When I click on the run id , if we see left hand side all the filter is gone and we could see all the run ids.

<img width="646" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/143148606/b5b9a12e-46c8-4904-a24c-5521503c4d0b">

4. If we want to filter on this blade, we can't do that as it does filtration based on  below and not the interval.
<img width="292" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/143148606/e3eec28d-0686-4455-92a0-8ae325d7bc8c">

5. We need to go back again on run history and check the run id for the filtered time interval.
6. This filter works fine for status:
(E.g I filtered for status: Failed)
<img width="296" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/143148606/760f5381-69d0-48a4-a577-13a8fe66e6c8">

<img width="395" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/143148606/99e35f0b-83ec-430e-9a89-3b2babfb9542">

7. If we click on any run id , we could see run history on left hand side appears as per filter.
<img width="458" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/143148606/c92d9579-aacc-409f-9d4d-7c9a25554c66">

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Microsoft Edge

**Comment by hartra344** [comment]
This is by design, the new filter allows stating both sides of the time, the old one that gets opened only allows one so it doesn’t translate the filter. This is something that will improve when we can rewrite the full run history blade to match.
