### ISSUE TITLE
False reporting when posting several requests one by one

### ISSUE THREAD

**Issue by medelmetoui** [Azure/LogicAppsUX#3983]
### Describe the Bug with repro steps 

![false](<https://github.com/Azure/LogicAppsUX/assets/127999891/f0d02324-a45d-4fda-87c5-aa400a9aa39f>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Microsoft Edge

### Additional context 

From the screen shot if i click on '>!' it take me to only one error,

 wheras when i check one by one i get that there are many errors.

 This have lead us to multiple false reporting

**Comment by hartra344** [comment]
@medelmetoui This is a UX level fix so it'll apply to all resources. Including ones that already exist. It does take about 2 weeks from code check in to production deployment though so you may not be seeing the change yet.
