### ISSUE TITLE
Standard Logic App at Azure portal unable to see "Environment variables" in main menu bar.

### ISSUE THREAD

**Issue by LIYINDUO** [Azure/LogicAppsUX#3985]
### Describe the Bug with repro steps

(1) At a customer's environment we are unable to see  "Environment variables" option in main menu bar. But we can see relevant App settings present in the configuration blade like the classic view.
(2) We tried to hard refresh browser and also change to another type of browser, issue is still present.
(3) We tried to collect portal extension version but failed to open monitoring tools with short key "Ctrl+Alt+D". May I ask is there another way to open the monitoring tools other than using the short key？

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
NA.
```

### Screenshots or Videos

Normal Menu:
![image](https://github.com/Azure/LogicAppsUX/assets/19198958/27fd1f74-bc77-47fb-803e-f0e8f447c004)

Customer's Menu:
![image](https://github.com/Azure/LogicAppsUX/assets/19198958/a51ab60a-19b9-4bbc-8863-2c7015b90298)

### Browser

Chrome and Microsoft Edge.

**Comment by hartra344** [comment]
Environment variables as a separate menu option is something being rolled out slowly. Different people will see it come online at different times. Until then, it exists in the configuration option.
