### ISSUE TITLE
Run History isn't showing for Logic Apps Workflows (Consumption)

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#3994]
### Describe the Bug with repro steps

If you click on a Run History item, the main panel will not load where the run history is displayed. 

![image](https://github.com/Azure/LogicAppsUX/assets/83832436/cc5a411b-23d0-40bc-b439-c69bcf455f33)

If you look at the console in dev tools we have some errors.

![image](https://github.com/Azure/LogicAppsUX/assets/83832436/0367ec94-b366-4577-b926-979de38b0669)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

### Additional context

We have customer logging ticket as well

**Comment by lfbarbieri-ipl** [comment]
We are seeing the same issue with our Logic Apps running in ISE environment, or consumption Logic Apps.

**Comment by hartra344** [comment]
Rolled back to fix quickly and will be updating the current release with a fix later today. Should be working for you now though, might require a hard refresh though.
