### ISSUE TITLE
Paste action pastes random action that was never copied

### ISSUE THREAD

**Issue by shahparth-lab** [Azure/LogicAppsUX#3995]
### Describe the Bug with repro steps

**Repro:**
1. Go to designer
2. Click on + to add action
3. Select "Paste an action" 
4. Previous action is pasted without it being copied 
**Expected behavior**
Paste an action should be disabled (still show it as an option) and only enabled when an action is copied

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

<img width="426" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/80121421/f060aec6-8ddf-488d-ae54-ce0ec7e1d479">

### Browser

Chrome

### Additional context

For a P1, we can also show an info box to communicate how to copy action, ie "right click and copy your action first"

**Comment by hartra344** [comment]
That is how it works, are you sure you didn't have a copied action from a previous session or a different window?
