### ISSUE TITLE
History not loading in Run History and Trigger History

### ISSUE THREAD

**Issue by Kalatiya** [Azure/LogicAppsUX#4002]
### Describe the Bug with repro steps

1. Go to QA-API-PostOrder-ESL
2. click on Workflows
3. Go to PostOrderScale2016 (for example)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

None of the history is showing - on multiple computers and accounts.
Also some elements of Logic App Designer is not opening.

### Browser

Chrome 

### Additional context

Restarting machines and clearing cache not fixing issue.

**Comment by rllyy97** [comment]
Customer has reported they restarted the app service and the issue was cleared up.
Closing this issue.
