### ISSUE TITLE
Dynamic content tokens do not show user-friendly display names on logic app/flow

### ISSUE THREAD

**Issue by Aleks-gdb** [Azure/LogicAppsUX#4009]
### Describe the Bug with repro steps

The same issue as #1764 is back but for all editors.
[Bug 26398392](https://msazure.visualstudio.com/One/_workitems/edit/26398392): Dynamic content friendly name is replaced by gibberish upon Saving flow

1. Create a flow with "When a new response is submitted" trigger from Microsoft Forms.
2. Add "Send an email" action from outlook or any action to insert dynamic content into.
4. Use dynamic content from trigger in the action.
5. Save the logic app/flow.
6. Exit into logic app/flow details page and go to edit the logic app/flow again
7. Notice that the dynamic content value shows the token path vs the token display name.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/42044630/c379962a-6df7-4825-8015-fba486d72e49)

### Browser

Edge

**Comment by Eric-B-Wu** [comment]
we default to title first and then use the name if there is no title, we may want to see what the manifest is for this action to see if the output is missing a title property

**Comment by kisubedi** [comment]
Hi @rllyy97 ! I was checking in make.test today expecting this fix to show up for us after 108 LA package drop and it still is reproing. Could you please double check if the issue was fixed?
