### ISSUE TITLE
Invalid parameters appear when nested parameters are present in action input

### ISSUE THREAD

**Issue by siddharth-ms** [Azure/LogicAppsUX#4020]
### Describe the Bug with repro steps 

1. [Internal] Open [sid-sap-testbox.ui-test](<https://ms.portal.azure.com/#view/Microsoft_Azure_EMA/WorkflowMenuBlade/~/designer/resourceId/%2fsubscriptions%2ff34b22a3-2202-4fb1-b040-1332bd928c84%2fresourceGroups%2fsiddharth-imp%2fproviders%2fMicrosoft.Web%2fsites%2fsid-sap-testbox%2fworkflows%2fui-test/location/Australia%20East/isReadOnly~/false>) in `BTS4` 
2. Create `[RFC] Call function in SAP` in-app action 
3. Set the `Input Type` to `Custom` 
4. Then select the optional `RFC Name`, and set it as `STFC_CONNECTION` 
5. A new dynamic textbox appear `REQTEXT`, enter `Hello` in that 
6. Check save. - This experience is great. 

![image](<https://github.com/Azure/LogicAppsUX/assets/104004368/a123dde4-e9b9-4987-9421-87e1ab142631>)

7. Now refresh the page, or go to code view and then back to designer 
8. Open the same action - A new parameter `body` will appear that was not part of the input when the action was first authored 

![image](<https://github.com/Azure/LogicAppsUX/assets/104004368/ee37e2ed-77dd-40d5-b930-1ff6967cd5eb>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "[RFC]_Call_function_in_SAP": {
                "inputs": {
                    "parameters": {
                        "body": {
                            "REQUTEXT": "Hello"
                        },
                        "inputBodyType": "Custom",
                        "outputBodyType": "XML",
                        "rfcGroupFilter": "*",
                        "rfcName": "STFC_CONNECTION"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "sap",
                        "operationId": "callRfc",
                        "serviceProviderId": "/serviceProviders/sap"
                    }
                },
                "runAfter": {},
                "type": "ServiceProvider"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by preetriti1** [comment]
@siddharth-ms - The manifest is incorrect and that is why it behaves weirdly with the dynamic inputs.
![image](https://github.com/Azure/LogicAppsUX/assets/48265693/0eba69fe-f472-4998-8ecf-0e791ea2b350)

You cannot have x-ms-dynamic-properties defined and also have some static properties for the same object. if any property has x-ms-dynamic-properties defined, then the dynamic call should result in replacing that whole property schema. This is the same case both for manifest based operations and swagger based operations.
You can defined another property and mark that as dynamicproperties and it should be working fine. You might have to change the location of your inputs for runtime... but that is how we have all manifests defined today.

If you need to discuss more, please set up time with me. I am closing with this comment
