### ISSUE TITLE
Localization issue - untranslated text in Japanese

### ISSUE THREAD

**Issue by Aleks-gdb** [Azure/LogicAppsUX#4063]
### Describe the Bug with repro steps 

1. Access to Power Automate.

 
2. Navigate to "Create" in the left pane.

 
3. Click "Automated cloud flow" > Enter any Flow name > Choose your flow’s trigger.

 
4. Click "Create" button.

 
5. A new design flow edit display will appear.

If it is not a new design, turn on the "New designer" toggle in the upper right corner of the screen.

 
6. Click on the flow shown on the edit display.

 

[Expected Result]​​​​

パラメーター

概要

[Corresponding English Text]​

Parameters

About

### What type of Logic App Is this happening in? 

Power Automate

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/42044630/ecd22ab7-be4f-4d3e-9b08-a2cd40f251a0>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by Aleks-gdb** [comment]
The Testing tab label is also not localized:
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/a0f58ac4-d80e-44c3-a05f-c8444dbccee6)

**Comment by hartra344** [comment]
I realized we have 2 of this issue. Closing this one in favor of tracking here: #3805
