### ISSUE TITLE
Map Json to Xml

### ISSUE THREAD

**Issue by Lappante** [Azure/LogicAppsUX#4093]
### Describe the Bug with repro steps 

Bug is happening when i have a source schema of type json and a target schema of type xsd.

1. Create schema, set source schema to a .json-schema and target schema to .xsd-schema. 
2. Go to Overview in the Mapper-UI and drag some lines 
3. Save, Generate XSLT, and Test works fine and the code view shows the correct xslt data. 
4. Close the map and load it again, this is where it breaks, the code view shows no mappings of attributes, hence all the lines in the UI is gone aswell. 

### Screenshots or Videos 

*No response*

### Version 

Azure Logic Apps (Standard): v2.99.1

### Additional context 

*No response*

**Comment by yoHasse** [comment]
Is this resolved? Can't find any referens to a fix
