### ISSUE TITLE
attachment content for Office 365 "Send an email (V2)" disappears after saving the workflow

### ISSUE THREAD

**Issue by yaser71180** [Azure/LogicAppsUX#4095]
### Describe the Bug with repro steps

in logic app standard new designer, 
1- adding Send an email (V2) action and configure the attachment content 
![Send an email (V2)](https://github.com/Azure/LogicAppsUX/assets/32329442/1953c065-caa8-499d-8b56-bf4e74ac0c9b)
2- save workflow successfully.
3- close and open the workflow designer again
4- attachment content is empty
![image](https://github.com/Azure/LogicAppsUX/assets/32329442/88fa2808-a794-45be-8fd6-267e01cc9671)

5- by looking at browser trace, we can see the API call https://management.azure.com/subscriptions/99116a50-926e-44bb-b3f0-6691c02d05a1/resourceGroups/LARunHistory_RG/providers/Microsoft.Web/sites/ymsalehrunhistory/deployWorkflowArtifacts?api-version=2018-11-01

the payload was as below, it is clear that attachment content is empty, so it is UI issue
{
    "files": {
        "blob/workflow.json": {
            "definition": {
                "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
                "actions": {
                    "Read_blob_content": {
                        "type": "ServiceProvider",
                        "inputs": {
                            "parameters": {
                                "containerName": "files",
                                "blobName": "2019_CeratoK3_Manual.pdf",
                                "inferContentType": false
                            },
                            "serviceProviderConfiguration": {
                                "connectionName": "AzureBlob",
                                "operationId": "readBlob",
                                "serviceProviderId": "/serviceProviders/AzureBlob"
                            }
                        },
                        "runAfter": {}
                    },
                    "Send_an_email_(V2)": {
                        "type": "ApiConnection",
                        "inputs": {
                            "host": {
                                "connection": {
                                    "referenceName": "office365-2"
                                }
                            },
                            "method": "post",
                            "body": {
                                "To": "yasersaleh@microsoft.com",
                                "Subject": "test",
                                "Body": "<p>test</p>",
                                "Attachments": [
                                    {
                                        "Name": "2019_CeratoK3_Manual.pdf",
                                        "ContentBytes": ""
                                    }
                                ],
                                "Importance": "Normal"
                            },
                            "path": "/v2/Mail"
                        },
                        "runAfter": {
                            "Read_blob_content": [
                                "SUCCEEDED"
                            ]
                        }
                    }
                },
                "contentVersion": "1.0.0.0",
                "outputs": {},
                "triggers": {
                    "When_a_blob_is_added_or_updated": {
                        "type": "ServiceProvider",
                        "inputs": {
                            "parameters": {
                                "path": "files/"
                            },
                            "serviceProviderConfiguration": {
                                "connectionName": "AzureBlob",
                                "operationId": "whenABlobIsAddedOrModified",
                                "serviceProviderId": "/serviceProviders/AzureBlob"
                            }
                        }
                    }
                }
            },
            "kind": "Stateful"
        },
        "parameters.json": {
            "ti": {
                "type": "Int",
                "value": 20
            }
        }
    }
}

Note: I can edit successfully from code view

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
    "files": {
        "blob/workflow.json": {
            "definition": {
                "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
                "actions": {
                    "Read_blob_content": {
                        "type": "ServiceProvider",
                        "inputs": {
                            "parameters": {
                                "containerName": "files",
                                "blobName": "2019_CeratoK3_Manual.pdf",
                                "inferContentType": false
                            },
                            "serviceProviderConfiguration": {
                                "connectionName": "AzureBlob",
                                "operationId": "readBlob",
                                "serviceProviderId": "/serviceProviders/AzureBlob"
                            }
                        },
                        "runAfter": {}
                    },
                    "Send_an_email_(V2)": {
                        "type": "ApiConnection",
                        "inputs": {
                            "host": {
                                "connection": {
                                    "referenceName": "office365-2"
                                }
                            },
                            "method": "post",
                            "body": {
                                "To": "yasersaleh@microsoft.com",
                                "Subject": "test",
                                "Body": "<p>test</p>",
                                "Attachments": [
                                    {
                                        "Name": "2019_CeratoK3_Manual.pdf",
                                        "ContentBytes": ""
                                    }
                                ],
                                "Importance": "Normal"
                            },
                            "path": "/v2/Mail"
                        },
                        "runAfter": {
                            "Read_blob_content": [
                                "SUCCEEDED"
                            ]
                        }
                    }
                },
                "contentVersion": "1.0.0.0",
                "outputs": {},
                "triggers": {
                    "When_a_blob_is_added_or_updated": {
                        "type": "ServiceProvider",
                        "inputs": {
                            "parameters": {
                                "path": "files/"
                            },
                            "serviceProviderConfiguration": {
                                "connectionName": "AzureBlob",
                                "operationId": "whenABlobIsAddedOrModified",
                                "serviceProviderId": "/serviceProviders/AzureBlob"
                            }
                        }
                    }
                }
            },
            "kind": "Stateful"
        },
        "parameters.json": {
            "ti": {
                "type": "Int",
                "value": 20
            }
        }
    }
}
```

### Browser

Edge

**Comment by Eric-B-Wu** [comment]
this should be fixed, however we'll still be missing 1 station before eod today, I'll run a hotfix for this in that missing station

**Comment by Eric-B-Wu** [comment]
the fix will go out EOD today

**Comment by Eric-B-Wu** [comment]
fix should now be in, closing - we can reopen if anyone is still facing the issue.
