### ISSUE TITLE
Show descriptive error message in expression editor

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#4111]
### Describe the Bug with repro steps 

Create a simple flow.

When an item is created -> Compose. in compose, add an expression concat("1", "2") and try saving. It says expression is invalid. Can we add ' Expression is invalid. Please use single quote' when we know double quotation is used to represent a string ?

This is a basic fundamental scenario for users where they are getting really confused. In expression, we accept single quotation, in filter query, we accept double quotation, we need to make it super clear in UX.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
@valentina-vallalta can you take this one? ERic should be able to help you out. This one is medium priority though so focus on higher priority bugs you may have first.
