### ISSUE TITLE
Built-in SQL doesn't save Service Provider Connection

### ISSUE THREAD

**Issue by Drac-Zhang** [Azure/LogicAppsUX#4117]
### Describe the Bug with repro steps 

LA STD doesn't save SQL Service Provide Connection in the below scenario:

If Managed SQL Connection was already created (i.e. added to the connections.json)

When adding In-App SQL, and creating its connection. Logic App would save fine, but no entry found in Connections.json

Design Time throws the below error upon re-opening logic app:

![image](<https://github.com/Azure/LogicAppsUX/assets/72241569/1c8f39bb-0b2b-4d9e-a487-324ed9040d2d>)

1. Create Clean Logic App (or make sure we don't have anything in connections.json) 
2. Create Workflow 
3. Add SQL Managed Connector 
4. Save 
5. Verify API Connection Created 
6. Run Once 
7. Go To Designer, add Built In SQL --> Create SP Connection 
8. Save --> Saves successfully with no errors on portal or HAR 
9. Check SP Connection -- Empty 

When we experience this issue, there's no payload related to connections.json

![image](<https://github.com/Azure/LogicAppsUX/assets/72241569/eec7251f-9480-4a35-b0f6-aa7fd028a969>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Get_tables": {
                "inputs": {
                    "serviceProviderConfiguration": {
                        "connectionName": "sql",
                        "operationId": "getTables",
                        "serviceProviderId": "/serviceProviders/sql"
                    }
                },
                "runAfter": {},
                "type": "ServiceProvider"
            },
            "Get_tables_(V2)": {
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "sql"
                        }
                    },
                    "method": "get",
                    "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('dractestsql.database.windows.net'))},@{encodeURIComponent(encodeURIComponent('dractestsql'))}/tables"
                },
                "runAfter": {
                    "Get_tables": [
                        "SUCCEEDED"
                    ]
                },
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

*No response*

### Browser

Chrome, Edge

### Additional context

*No response*

**Comment by hartra344** [comment]
@rllyy97 I think we need to verify if this is both a FE/BE issue as well as figure out if we're swallowing an error we shouldn't be swallowing. If backend is returning that it's all good and just not saving it then we can pass off to them.
