### ISSUE TITLE
Dynamic Schema Null Paramater

### ISSUE THREAD

**Issue by Encodian** [Azure/LogicAppsUX#4120]
### Describe the Bug with repro steps 

1. Create a new app in logic apps 
2. Add the Encodian 'Create Excel' action 
3. Create an Encodian connection (obtain an API Key here - [https://www.encodian.com/apikey](<https://www.encodian.com/apikey>)) 
4. Select the output format: 

![image](<https://github.com/Azure/LogicAppsUX/assets/45834050/c9bfd78e-1343-41cc-a5d8-acd90ba2815b>)

5. Manually set a filename and file content 

![image](<https://github.com/Azure/LogicAppsUX/assets/45834050/f3f7b73a-a6d6-49da-9418-e2be7c59f100>)

6. Save the App 

![image](<https://github.com/Azure/LogicAppsUX/assets/45834050/c415e378-c946-4e7a-95de-dbd6f7bc323d>)

Perform the same steps in Power Automate (works fine)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

We are seeing differences between how Power Automate and Logic Apps handle connector dynamic schemas.

**Reference Schema:** https://[api.apps-encodian.com/swagger/v1/swagger.json](<https://api.apps-encodian.com/swagger/v1/swagger.json>)

**Reference Action:** Convert Excel

When working in Power Automate the Convert Excel actions works fine in both the old and new designer… see below:

![image](<https://github.com/Azure/LogicAppsUX/assets/45834050/9db65e80-abaa-4461-bcc2-84cc1703461e>)

However, in Logic Apps (both old and new designer) upon adding the 'Convert Excel' action and selecting a value from the dynamic schema the app cannot be saved because the properties of the action have not been set properly:

![image](<https://github.com/Azure/LogicAppsUX/assets/45834050/18ec4cdf-a01f-4817-9cad-05fe8f85afbe>)

Can you advise?

### Browser 

All browsers

### Additional context 

*No response*

**Comment by hartra344** [comment]
@Eric-B-Wu can you take a look?

**Comment by Eric-B-Wu** [comment]
This does seem like an issue on the manifest side given that this isn't working from the old designer which hasn't been changed in over a year.

From the manifest we're seeing that the parameter outputFormatParameter is supposed to be within input.query:
```
        "parameters": [
            {
                "name": "connectionId",
                "in": "path",
                "required": true,
                "type": "string",
                "x-ms-visibility": "internal"
            },
            // here we specify the outputFormatParameter that gets popualted and calls the dynamic data
            {
                "in": "query",
                "name": "outputFormatParameter",
                "description": "Set the output file type",
                "type": "string",
                "enum": [
                    "PDF",
                    "HTML",
                    "CSV",
                    "TXT",
                    "XLSX",
                    "XLS",
                    "XLTX",
                    "PNG",
                    "TIFF"
                ],
                "x-ms-visibility": "important",
                "x-ms-summary": "Output Format"
            },
            {
                "in": "body",
                "name": "conversion",
                "description": "Request object, refer to schema definition: DtoConvertExcel",
                "schema": {
                    "$ref": "#/definitions/DtoConvertExcel"
                }
            }
        ]
```

and when the dynamic data is fetched for outputFormat=HTML (
https://management.azure.com//subscriptions/{subscription}/resourceGroups/{resourceGroup}/providers/Microsoft.Web/connections/encodiandocumentmanager/extensions/proxy/api/v1/DynamicSchema/GetDynamicSchemaConvertExcel?api-version=2018-07-01-preview&outputFormat=HTML). We see:

```
{
    "dynamicSchemaConvertExcel": {
        "type": "object",
        "required": [
            "outputFilename",
            "fileName",
            "fileContent",
            "outputFormat"
        ],
        "properties": {
            "outputFilename": {
                "type": "string",
                "x-ms-visibility": "internal",
                "x-ms-summary": "Output Filename",
                "description": "The filename of the output document",
                "default": "word"
            },
            // internal property so it won't create a parameter
            "outputFormat": {
                "type": "string",
                "x-ms-visibility": "internal",
                "x-ms-summary": "Output Format"
            },
            "fileName": {
                "type": "string",
                "x-ms-visibility": "important",
                "x-ms-summary": "Filename",
                "description": "The filename of the source file, the file extension is mandatory: 'file.xlsx' and not 'file'"
            },
            "fileContent": {
                "format": "byte",
                "type": "string",
                "x-ms-visibility": "important",
                "x-ms-summary": "File Content",
                "description": "The file content of the source file"
            },
            "worksheet": {
                "type": "string",
                "x-ms-visibility": "advanced",
                "x-ms-summary": "Worksheet",
                "description": "Specify the name of a specific worksheet"
            },
            "onePagePerSheet": {
                "type": "boolean",
                "x-ms-visibility": "advanced",
                "x-ms-summary": "One Page Per Sheet",
                "description": "Place all sheets into one page."
            },
            "allColumnsInOnePagePerSheet": {
                "type": "boolean",
                "x-ms-visibility": "advanced",
                "x-ms-summary": "All Columns in One Page Per Sheet Name",
                "description": "Place each column of a sheet into its own page."
            },
            "removeDocumentMarkup": {
                "type": "boolean",
                "x-ms-visibility": "advanced",
                "x-ms-summary": "Remove Markup",
                "description": "Set MS Office document comments and tracked changes removal option.",
                "default": "true"
            },
            "exportHiddenSheets": {
                "type": "boolean",
                "x-ms-visibility": "advanced",
                "x-ms-summary": "Export Hidden Sheets",
                "description": "Sets whether hidden worksheets should be exported",
                "default": "false"
            },
            "cultureName": {
                "type": "string",
                "x-ms-visibility": "advanced",
                "x-ms-summary": "Culture Name",
                "description": "Change the thread culture used to process the request."
            }
        }
    }
}
```
where outputFormat is a **required property**; however it being an **internal property**. Note that this is a different outputFormat from the manifest. This is why we have outputFormatParameter as being populated with html in inputs.queries, and outputFormat being an empty string and never being populated with any value

**Comment by Encodian** [comment]
@hartra344 - I'm not convinced this is a bug with the manifest. This works without issue in Power Automate for both the old and new designers, it just doesn't work in Logic Apps. Moreover, the Power Automate schema mandates that any 'Internal property must be made a required property... so that configuration is correct. Can you please advise? The dynamic schema's were built with guidance and assistance from the P/A team using examples they provided...

**Comment by rllyy97** [comment]
Hi all, I'm expecting this issue to be fixed once this change rolls out.  https://github.com/Azure/LogicAppsUX/pull/4374
I found what appears to be a bug in our old designer code that got carried over to new designer where one of our "internal" parameter checks was not respecting the flag we were passing.

**Comment by preetriti1** [comment]
So the issue here is - the dynamic schema returned in LogicApps which has the outputFormat does not set the value to anything, so being an internal parameter and not having default value set it will always be serialized as empty.

<img width="615" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/48265693/6f326bec-6d57-46de-aad2-11f68d3d0196">

When we send the request to fetch dynamic schema [body schema] we do send query parameter as PDF value, so that should have been written as the default value in the outputFormat in body parameter. Once that is done it should be working in Logic App.

@Encodian - Any parameter marked as internal, will never show up in UI. And if it is required, then "default" needs to be set in the schema, otherwise designer client would not know what value to write. I am assuming this works in PA because the dynamic schema call might be setting this correctly.
