### ISSUE TITLE
Workflow overview blade "Runtime Version" link missing CSS style for dark theme.

### ISSUE THREAD

**Issue by ynauls** [Azure/LogicAppsUX#4127]
### Describe the Bug with repro steps 

1. Go to Logic App Standard workflow overview 
2. View Runtime Version 

![image](<https://github.com/Azure/LogicAppsUX/assets/10816194/b2e5c489-37d3-4fed-a16c-98e5e6ff2224>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json
N/A
```

### Screenshots or Videos

![image](<https://github.com/Azure/LogicAppsUX/assets/10816194/b7b90317-8544-4967-bf34-809738c31204>)

### Browser

Edge

### Additional context

*No response*

**Comment by hartra344** [comment]
https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/9548581?_a=files
