### ISSUE TITLE
Issue connecting to surveymonkey connector

### ISSUE THREAD

**Issue by sandeep853085** [Azure/LogicAppsUX#4131]
### Describe the Bug with repro steps 

After selectin required trigger and click sign a pop-up window is getting opened with survey monkey login window but in the original window we end up getting error "browser closed"

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Tried with edge, firefox and chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
It like on the SurveyMonkey connector specifically, our popup window is showing as closed for a second during initialization when it's still open, which closes our login flow and you have to restart.  Not sure why but I'm still investigating.

**Comment by rllyy97** [comment]
We released a mitigation for this issue and you should be able to create SurveyMonkey connections again.
The issue is still present, but until the root issue is fixed this will unblock customers.
