### ISSUE TITLE
'sign' is illegal keyword (in HTTP's 'Request' action body at least)

### ISSUE THREAD

**Issue by aidanmartinCLA** [Azure/LogicAppsUX#4136]
### Describe the Bug with repro steps 

1. Add a 'Response' action to a Logic App. 
2. Fill out the response body, write the keyword "sign". I wanted to send a response like "Invalid API key; sign up for one here" 
3. Page automatically redirects [https://portal.azure.com/#create/hub](<https://portal.azure.com/#create/hub>) and discards and unsaved progress in the workflow. 
4. Navigate back to the workflow and notice irregular functionality in edits continuing until page is reloaded. 

Another note, not quite bug, albeit a useful addition: save chats with assistant through duration of user's session, AKA don't delete chat when window is closed/minimized.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge browser

### Additional context 

*No response*

**Comment by hartra344** [comment]
For the main bug, I'm not able to repro? Am I following your steps correctly? 

https://github.com/Azure/LogicAppsUX/assets/13208452/528a2c62-9082-439b-a443-a1218a036805

**Comment by aidanmartinCLA** [comment]
Here's repro in that example. With another workflow, the redirect is automatic ('Response' with 400 code as default case in switch).

https://github.com/Azure/LogicAppsUX/assets/157390376/702c410d-7e74-4cc8-932b-cc479945cb7c

**Comment by hartra344** [comment]
ok I am able to repro now. We'll look into what's causing it: but 2 mitigations/observations for you in the meantime:
1) It only does it when I type quickly, try typing it slowly and see if that helps
2) When the "your unsaved edits" dialog pops up, click cancel and it won't redirect you.

**Comment by aidanmartinCLA** [comment]
Thanks Travis, I figured it good someone made aware or maybe unknown bugs are better. After the initial popup is cancelled out of, the issue persists in the session's state continuing to pop up at character level inputs on any field, so as a user I have to stop, save, and refresh before the apps works as expected. No big deal, I can workaround.

**Comment by rllyy97** [comment]
Looks like the behavior is coming from these Azure Portal keyboard shortcuts: https://learn.microsoft.com/en-us/azure/azure-portal/azure-portal-keyboard-shortcuts
There's a few of them but the `G+N` is what we're seeing here

**Comment by hartra344** [comment]
@aidanmartinCLA Riley's explanation makes sense except you say that it continues to pop up? Is it specifically when you're hitting those key combos somehow? One I continue on, I don't see any adverse affects going through my workflow and continuing to make changes.

**Comment by Eric-B-Wu** [comment]
I think its because the editors we're using aren't considered inputs, but rather text-editable divs, which makes key changes propogate to the portal level. And I guess it doesnt accept it until the page navigates; I'm gonna look to suppressing these shortcuts while the designer is open
