### ISSUE TITLE
Unable to change format in Send an email action (after HTML fixes) when a token is applied in editor

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#4139]
### Describe the Bug with repro steps 

In Send email action, add any dynamic content or an expression, now try changing the font family/size/background color/header, and it does not work.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
This was fixed in this PR:
https://github.com/Azure/LogicAppsUX/pull/4099
![test](https://github.com/Azure/LogicAppsUX/assets/95886809/4956ddf4-9547-42e8-98ac-a96acfca7f65)
