### ISSUE TITLE
Cannot use logic app designer.

### ISSUE THREAD

**Issue by johan-burman** [Azure/LogicAppsUX#4151]
### Describe the Bug with repro steps 

1. Azure Logic Apps: Create new project… 
2. Select current folder 
3. Create stateful workflow 
4. Right-click, Open Designer 

"Unexpected end of JSON input"

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "kind": "Stateful"
}
```

### Screenshots or Videos

![image](<https://github.com/Azure/LogicAppsUX/assets/93716545/7a0857fc-44ee-4c67-9347-ffe965f97345>)

### Browser

VS Code

### Additional context

*No response*

**Comment by johan-burman** [comment]
After downgrading to v2.99.1, this issue went away.

**Comment by hartra344** [comment]
@ccastrotrejo
