### ISSUE TITLE
 Cannot Move Actions In Preview Designer (FireFox) #983 

### ISSUE THREAD

**Issue by influential-eliot** [Azure/LogicAppsUX#4153]
### Describe the Bug with repro steps 

1. Build Logic App with actions 
2. Ensure that there are parallel tasks 
3. Attempt to move an action 

### Describe the Bug 

*I have also logged this, [here](<https://github.com/Azure/logicapps/issues/983>), so you can consider that the ticket for the 'Old Designer' as I wanted to select that it occurs in both.*

When trying to move an action, anywhere, in the Logic Apps Designer View it displays a 'nope' circle (🚫) and will not move the action.

This occurs on multiple tenancies for multiple clients and is affecting my ability to easily produce work for them, and also happens in the old designer.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose": {
                "inputs": "asdasd",
                "runAfter": {
                    "Initialize_MessageCategoryVAR": [
                        "Succeeded"
                    ],
                    "Initialize_MessageSourceVAR": [
                        "Succeeded"
                    ],
                    "Response": [
                        "Succeeded"
                    ]
                },
                "type": "Compose"
            },
            "Initialize_MessageCategoryVAR": {
                "inputs": {
                    "variables": [
                        {
                            "name": "MessageCategoryVAR",
                            "type": "string",
                            "value": "@triggerBody()['messageCategory']"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            },
            "Initialize_MessageEmailBodyVAR": {
                "inputs": {
                    "variables": [
                        {
                            "name": "MessageEmailBodyVAR",
                            "type": "string",
                            "value": "@{triggerBody()['messageEmailBody']}"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            },
            "Initialize_MessageSourceVAR": {
                "inputs": {
                    "variables": [
                        {
                            "name": "MessageSourceVAR",
                            "type": "string",
                            "value": "@triggerBody()['messageSource']"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            },
            "Response": {
                "inputs": {
                    "statusCode": 200
                },
                "kind": "Http",
                "runAfter": {
                    "Initialize_MessageEmailBodyVAR": [
                        "Succeeded"
                    ]
                },
                "type": "Response"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {
            "manual": {
                "inputs": {
                    "schema": {
                        "properties": {
                            "messageCategory": {
                                "type": "string"
                            },
                            "messageEmailBody": {
                                "type": "object"
                            },
                            "messageSource": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "messageCategory",
                            "messageSource",
                            "messageEmailBody"
                        ],
                        "type": "object"
                    }
                },
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "parameters": {}
}
```

### Screenshots or Videos

![Move blocked](<https://github.com/Azure/LogicAppsUX/assets/112952958/74997133-67fc-496f-84f4-3558acbb28b9>)

### Browser

FireFox

**Type**: Nightly

**Version**: 124.0a1 (2024-01-31) (64-bit)

**Add-ons**: Multiple-Account Containers

#### Logged Elsewhere?

I have made a ticket on the Mozilla FireFox forums, but that doesn't seem like the most ideal place for it.

[https://support.mozilla.org/en-US/questions/1439176](<https://support.mozilla.org/en-US/questions/1439176>)

#### Further Details

This was working a week ago or so.

Have there been changes to the designer that caused this? As I have seen issues with the V2 Designer in Power Automate, too. There the 'experimental features' expression builder does not fulfill autofil on function suggestions or quote closing.

Alternatively, is it possible that there is a change in FireFox which caused this? I have attempted this with all Add-ons disabled.

#### FireFox

**Type**: Nightly

**Version**: 124.0a1 (2024-01-31) (64-bit)

**Add-ons**: Multiple-Account Containers

#### Edge

**Type**: Microsoft Edge for Business (Chromium)

**Preview releases**: Yes

**Version**: Version 122.0.2365.16 (Official build) stable app, beta channel (64-bit)

##### Origin is not a trusted origin

Looking in Dev Tools there is a "*Origin is not a trusted origin*" error, could that be related?

I have the security up nice and high, so perhaps it is preventing a perceived XSS issue?

```
Origin is not a trusted origin. Session: origin:https://ema.hosting.portal.azure.net [DesignerFramePage.js:81:32](https://ema.hosting.portal.azure.net/ema/Content/2.40122.1.5/Scripts/Workflow/ViewModels/FramePages/DesignerFramePage.js)
    eventListener https://ema.hosting.portal.azure.net/ema/Content/2.40122.1.5/Scripts/Workflow/ViewModels/FramePages/DesignerFramePage.js:81
    (Async: EventListener.handleEvent)
    createFrameManager https://ema.hosting.portal.azure.net/ema/Content/2.40122.1.5/Scripts/Workflow/ViewModels/FramePages/DesignerFramePage.js:95
    <anonymous> https://ema.hosting.portal.azure.net/ema/Content/2.40122.1.5/Scripts/Workflow/ViewModels/FramePages/DesignerFramePage.js:1242
    <anonymous> https://ema.hosting.portal.azure.net/ema/Content/2.40122.1.5/Scripts/Workflow/ViewModels/FramePages/DesignerFramePage.js:1244
```

##### DNS over HTTPS

Disabling this, or adding the sites made no difference.

##### DNS General

In case it made any difference I have used a different DNS provider to my default, and it was the same on Cloudflare's `1.1.1.1`.

**Comment by hartra344** [comment]
Is this happening in other browsers for you as well? If it just started last week and also started happening in old designer then I would lean to it being a bug/change in Firefox. We haven’t updated the code in old designer in about a year and a half. Also I’m going to leave this issue open for discussion further but close the other. We don’t need both since this one notes that it happens in both.
