### ISSUE TITLE
Cannot Move Actions In Designer View (FireFox)

### ISSUE THREAD

**Issue by influential-eliot** [Azure/LogicAppsUX#4154]
### Describe the Bug 

*I have also logged this in the LogicAppsUX repo, [here](<https://github.com/Azure/LogicAppsUX/issues/4153>), if you needed tickets for old and new designer, you now have them and this is the 'old' one.*

When trying to move an action, anywhere, in the Logic Apps Designer View it displays a 'nope' circle (🚫) and will not move the action.

This occurs on multiple tenancies for multiple clients and is affecting my ability to easily produce work for them, and also happens in the preview designer.

### Plan Type 

Consumption

### Steps to Reproduce the Bug or Issue 

1. Build Logic App with actions 
2. Ensure that there are parallel tasks 
3. Attempt to move an action 

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose": {
                "inputs": "asdasd",
                "runAfter": {
                    "Initialize_MessageCategoryVAR": [
                        "Succeeded"
                    ],
                    "Initialize_MessageSourceVAR": [
                        "Succeeded"
                    ],
                    "Response": [
                        "Succeeded"
                    ]
                },
                "type": "Compose"
            },
            "Initialize_MessageCategoryVAR": {
                "inputs": {
                    "variables": [
                        {
                            "name": "MessageCategoryVAR",
                            "type": "string",
                            "value": "@triggerBody()['messageCategory']"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            },
            "Initialize_MessageEmailBodyVAR": {
                "inputs": {
                    "variables": [
                        {
                            "name": "MessageEmailBodyVAR",
                            "type": "string",
                            "value": "@{triggerBody()['messageEmailBody']}"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            },
            "Initialize_MessageSourceVAR": {
                "inputs": {
                    "variables": [
                        {
                            "name": "MessageSourceVAR",
                            "type": "string",
                            "value": "@triggerBody()['messageSource']"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            },
            "Response": {
                "inputs": {
                    "statusCode": 200
                },
                "kind": "Http",
                "runAfter": {
                    "Initialize_MessageEmailBodyVAR": [
                        "Succeeded"
                    ]
                },
                "type": "Response"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {
            "manual": {
                "inputs": {
                    "schema": {
                        "properties": {
                            "messageCategory": {
                                "type": "string"
                            },
                            "messageEmailBody": {
                                "type": "object"
                            },
                            "messageSource": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "messageCategory",
                            "messageSource",
                            "messageEmailBody"
                        ],
                        "type": "object"
                    }
                },
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "parameters": {}
}
```

### Screenshots or Videos

![Move blocked](<https://github.com/Azure/logicapps/assets/112952958/d07caa16-593f-484a-9513-53f2eeafd98e>)

#### Logged Elsewhere?

I have made a ticket on the Mozilla FireFox forums, but that doesn't seem like the most ideal place for it.

[https://support.mozilla.org/en-US/questions/1439176](<https://support.mozilla.org/en-US/questions/1439176>)

#### Further Details

This was working a week ago or so.

Have there been changes to the designer that caused this? As I have seen issues with the V2 Designer in Power Automate, too. There the 'experimental features' expression builder does not fulfill autofil on function suggestions or quote closing.

Alternatively, is it possible that there is a change in FireFox which caused this? I have attempted this with all Add-ons disabled.

#### FireFox

**Type**: Nightly

**Version**: 124.0a1 (2024-01-31) (64-bit)

**Add-ons**: Multiple-Account Containers

#### Edge

**Type**: Microsoft Edge for Business (Chromium)

**Preview releases**: Yes

**Version**: Version 122.0.2365.16 (Official build) stable app, beta channel (64-bit)

##### Origin is not a trusted origin

Looking in Dev Tools there is a "*Origin is not a trusted origin*" error, could that be related?

I have the security up nice and high, so perhaps it is preventing a perceived XSS issue?

```
Origin is not a trusted origin. Session: origin:https://ema.hosting.portal.azure.net [DesignerFramePage.js:81:32](https://ema.hosting.portal.azure.net/ema/Content/2.40122.1.5/Scripts/Workflow/ViewModels/FramePages/DesignerFramePage.js)
    eventListener https://ema.hosting.portal.azure.net/ema/Content/2.40122.1.5/Scripts/Workflow/ViewModels/FramePages/DesignerFramePage.js:81
    (Async: EventListener.handleEvent)
    createFrameManager https://ema.hosting.portal.azure.net/ema/Content/2.40122.1.5/Scripts/Workflow/ViewModels/FramePages/DesignerFramePage.js:95
    <anonymous> https://ema.hosting.portal.azure.net/ema/Content/2.40122.1.5/Scripts/Workflow/ViewModels/FramePages/DesignerFramePage.js:1242
    <anonymous> https://ema.hosting.portal.azure.net/ema/Content/2.40122.1.5/Scripts/Workflow/ViewModels/FramePages/DesignerFramePage.js:1244
```

##### DNS over HTTPS

Disabling this, or adding the sites made no difference.

##### DNS General

In case it made any difference I have used a different DNS provider to my default, and it was the same on Cloudflare's `1.1.1.1`.

**Comment by influential-eliot** [comment]
It does not happen in Edge, no. I thought I had mentioned that, sorry if I hadn't.

**Comment by hartra344** [comment]
Then opening the issue on Mozilla might have been the right move. For drag and drop we use the generic html5 drag and drop browser API. So it could be that Mozilla had a release that broke it in some way. This is particularly more likely with it happening in old designer where the code hasn’t been even rebuilt in over a year as it’s in stable maintenance phase.

**Comment by influential-eliot** [comment]
Yeah, I was curious about that.

Because the old Power Automate designer (V2) has stopped autofilling function suggestions and quote closing when the 'experimental features' is turned on.
 
I'll try to start poking harder on the Moz end, then.

**Comment by influential-eliot** [comment]
Looks like this is working again, @hartra344 ... not sure whether it was a Nightly update, or anything your end (am guessing the former) but yeah ... [webcompat have indicated things were working for them](https://github.com/webcompat/web-bugs/issues/133233#issuecomment-1946820729).

I'd say that it all magically started working about an hour ago, but that could've been overnight.

**Comment by hartra344** [comment]
Glad whatever it was got fixed. Going to close this for now, feel free to rope me in if it starts again and you need help engaging with the Mozilla devs.

**Comment by influential-eliot** [comment]
Cheers, @hartra344 ... 👍 

Where would be the right place to speak to problems with the Power Automate (**PA**) designers?

There are a number of other (_small to middling_) issues I've noted with the javascript stuffs, and those are mostly in PA, rather than Logic Apps (**LA**) **core** (_ie. not preview_) designer.

I know that the designers share code, but I would assume that this isn't the place for reporting PA issues specifically, I just cannot seem to find a public spot that isn't the community forum. (_which has zero chance of reaching the right people_)

Most of these are almost exclusively with Designer V2 (_with experimental settings_), so I'm aware that PA V2 issues are unlikely to get much headroom. That said, it does (_as you say_) share much of its code with the core LA designer.

_Don't worry, I'm not looking for a place to slag off the new designer on either platform, totally rooting for both to be usable soon!_

**Comment by hartra344** [comment]
Feel free to report here and note that it's a PA specific issue with as much info as possible. If it's not caused by the actual designer code I'll make sure the bug gets to the right place. We also have a few developers/PMs from PA that are around this repo as well. Here are a few: @kisubedi @ek68794998 @jaimereyesmx

**Comment by influential-eliot** [comment]
Thanks, mate ... will absolutely do that.

( _this may come back to haunt you!_ 😅 )
