### ISSUE TITLE
Logic app standard- Microsoft Forms connector gives "The response is not in a JSON format" while sign in to create api connection

### ISSUE THREAD

**Issue by swakMS** [Azure/LogicAppsUX#4167]
### Describe the Bug with repro steps 

using LA Standard. unable to sign in to create api connections for Microsoft forms connector trigger or action. tried in other regions but still same. in fallback url it is working

Step 1: Go to logic apps-->designer--> add an action\trigger-->search Microsoft forms--> select an action

![image](<https://github.com/Azure/LogicAppsUX/assets/78227025/4fcd4831-cc43-48b1-b25f-efa270691269>)

step 2: after selecting trigger or action and tries to sign in gives error

![image](<https://github.com/Azure/LogicAppsUX/assets/78227025/d2232c86-7c01-4049-bc64-d1be54bb872a>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

edge, chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @swakMS, I'm not able to repro your issue when following the steps you outlined, to help me investigate further could you get the console and network logs of you trying to create that connection and email them to me at rileyevans@microsoft.com
You can find instructions on how to collect these logs from our docs site here: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-console-errors
