### ISSUE TITLE
"When a client is updated" trigger of the "3E Events" connector does not add the "body" parameter in trigger definition.

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#4169]
### Describe the Bug with repro steps 

When you add the trigger and save the workflow, you can check the code view and you will find it missing "body section.

But if you perform the same step with power automate, you will see a "body" section like below.

![image](<https://github.com/Azure/LogicAppsUX/assets/49498706/483a2703-174b-4b60-9986-e446857eb4e3>)

So basically this trigger works for power automate, but not for logic app.

The trigger has this swagger below.

```json
{
  "post": {
    "responses": {
      "201": {
        "$ref": "#/responses/okCreateSubscription"
      },
      "400": {
        "$ref": "#/responses/badRequestCreateSubscription"
      },
      "401": {
        "$ref": "#/responses/unauthorized"
      },
      "403": {
        "$ref": "#/responses/forbidden"
      }
    },
    "description": "This operation triggers a flow when a client is updated.",
    "summary": "When a client is updated",
    "operationId": "ClientUpdatedEventTrigger",
    "x-ms-visibility": "important",
    "x-ms-trigger": "single",
    "parameters": [
      {
        "name": "connectionId",
        "in": "path",
        "required": true,
        "type": "string",
        "x-ms-visibility": "internal"
      },
      {
        "name": "body",
        "in": "body",
        "required": true,
        "x-ms-visibility": "internal",
        "schema": {
          "type": "object",
          "x-ms-visibility": "internal",
          "properties": {
            "application": {
              "$ref": "#/definitions/application"
            },
            "callbackUrl": {
              "$ref": "#/definitions/callbackUrl"
            },
            "object": {
              "type": "string",
              "description": "The ID of the object.",
              "title": "Object",
              "x-ms-visibility": "internal",
              "default": "Client"
            },
            "state": {
              "type": "string",
              "description": "The state of the object.",
              "title": "State",
              "x-ms-visibility": "internal",
              "default": "Updated"
            }
          },
          "required": [
            "application",
            "callbackUrl",
            "object",
            "state"
          ]
        }
      }
    ],
    "externalDocs": {
      "url": "https://docs.microsoft.com/connectors/3eevents/#when-a-client-is-updated"
    }
  }
}
```

here are the two references cited in above swagger. Maybe logic app designer has problem with the "callbackUrl" field which is x-ms-notification-url?

```json
"application": {
    "type": "string",
    "description": "The client's application unique name in the Events Webhook service.",
    "title": "Destination Application",
    "default": "MsPowerPlatform",
    "x-ms-visibility": "internal"
},
"callbackUrl": {
    "type": "string",
    "description": "The callback URL to deliver events.",
    "title": "Callback URL",
    "x-ms-visibility": "internal",
    "x-ms-notification-url": true
},
```

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>)

Yes

### Browser

Chrome

**Comment by JaganMSFTGitHub** [comment]
Hello @rllyy97 Any updates on this?

**Comment by rllyy97** [comment]
@JaganMSFTGitHub, no updates yet, I haven't had time to look into this issue, I'll give an update once I do

**Comment by JaganMSFTGitHub** [comment]
Hello @rllyy97 Did you get some time to look into this?

**Comment by JaganMSFTGitHub** [comment]
Hello @rllyy97 I request you to please share an update on this as this is an S500 customer and currently they are expecting some update from our end.

**Comment by rllyy97** [comment]
@JaganMSFTGitHub I have been on-call and haven't had time to look into this, I will look into it today and see what I can find

**Comment by rllyy97** [comment]
I'm seeing this behavior in Legacy Designer as well (Consumption)

**Comment by rllyy97** [comment]
@JaganMSFTGitHub When the customer is adding/using that trigger in Power Automate, are they using the new designer or old designer?

**Comment by JaganMSFTGitHub** [comment]
Hello @rllyy97 Customer is using the old designer in the power automate.

**Comment by rllyy97** [comment]
I was taking a look at this other github issue we have: https://github.com/Azure/LogicAppsUX/issues/4120
That issue leads me to believe this is something with the fact that the body is marked as an 'internal' parameter
ie. `"x-ms-visibility": "internal"`

**Comment by JaganMSFTGitHub** [comment]
@rllyy97 Many thanks for looking into this. Is it possible to share an ETA with the customer for fixing this issue?

**Comment by JaganMSFTGitHub** [comment]
Hello @rllyy97 Could you please let us know if it is possible to share an ETA with the customer for fixing this issue.

**Comment by rllyy97** [comment]
Hi @JaganMSFTGitHub, I don't have an ETA to share with the customer.  We are being very careful about what we change, since this does not currently work in legacy designer we don't have an example of a solution, and whatever we change with the schema parsing we will need to confirm it won't cause unintended errors for other schemas as well.
I spoke with Power Automate and they are also not seeing this work in their new designer, we will be discussing it to see what differences they have that we might be able to use.

**Comment by rllyy97** [comment]
@JaganMSFTGitHub No updates yet

**Comment by rllyy97** [comment]
I am currently investigating this.  Like I said in my last major comment, we are being very careful about what we change in this area.  Since this does not currently work in legacy designer we don't have an example of a solution, and whatever we change with the schema parsing we will need to confirm it won't cause unintended errors for other schemas as well.

**Comment by preetriti1** [comment]
@JaganMSFTGitHub - This is not an issue with designer, for 3E Events connector, the body parameter when defined as "internal" should have specified the default value. Any parameter defined as internal should always specify default value that goes in the definition. Also it should not expand its properties because we wont be parsing the object to its leaf nodes.

@xuehongg - Can we ask the BAPI Connector team to fix the swagger of this connector?

**Comment by xuehongg** [comment]
@preetriti1 @rllyy97 @JaganMSFTGitHub 

Yes, this connector looks never properly certified with logic apps. I have transferred the ICM 459556096 to connector certification team.
