### ISSUE TITLE
See more on some connector is not show in dark mode in Azure Portal

### ISSUE THREAD

**Issue by hugogirard** [Azure/LogicAppsUX#4173]
### Describe the issue 

1. Create a new service bus 
2. Create a topic with a subscription in the Service Bus 
3. Create a new logic app standard 
4. Use the trigger when a message are available in a Topic 
5. Add after the action - Initialize variable 
6. Select type string 
7. The value is the correlation ID of the service bus 

Here the problem in dark mode in the Azure Portal you don't see the see more option in the action.

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

![bug](<https://github.com/Azure/LogicAppsUX/assets/64166891/2b2d6b6b-0916-4eea-ab87-706a1a3b1cdb>)

### Browser 

- Edge 
- Chrome 

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
will be fixed with this PR: https://github.com/Azure/LogicAppsUX/pull/4376

**Comment by Eric-B-Wu** [comment]
closing as this is now merged, will be deployed 4/5 ETA
