### ISSUE TITLE
Cannot paste tokens into HTML editor

### ISSUE THREAD

**Issue by ek68794998** [Azure/LogicAppsUX#4183]
### Describe the Bug with repro steps 

1. In any flow, add a token 
2. Copy that token's code (from Code View) 
3. Paste it into an HTML editor (raw or WYSIWYG) 

Expected: The token should be pasted.

 Actual: The raw code `@{...}` is pasted.

Validated in PAuto and localhost on Standard LA.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![paste-html](<https://github.com/Azure/LogicAppsUX/assets/1350074/059c681e-b723-4c7a-a17e-d0d41101c16f>)

### Browser 

Chrome 121.0.6167.161, Windows 11 x64.

### Additional context 

*No response*

**Comment by ek68794998** [comment]
Looks like this was a known gap in the initial PR: #3793
![image](https://github.com/Azure/LogicAppsUX/assets/1350074/95d5e68d-4a7f-4e7d-8da0-4445500c0e59)

However, when I enabled the functionality locally, it seemed to work. I'm curious if maybe the original gap was caused by something that was fixed when tokens were re-implemented to use `@{ }` format instead of `$[ ]$`.

@Eric-B-Wu who probably has context.

**Comment by Eric-B-Wu** [comment]
> Looks like this was a known gap in the initial PR: #3793 ![image](https://private-user-images.githubusercontent.com/1350074/304537999-95d5e68d-4a7f-4e7d-8da0-4445500c0e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjgwNTUsIm5iZiI6MTcwNzkyNzc1NSwicGF0aCI6Ii8xMzUwMDc0LzMwNDUzNzk5OS05NWQ1ZTY4ZC00YTdmLTRlN2QtOGRhMC00NDQ1NTAwYzBlNTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMTYyMjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU0YzA5M2U0OTM0ZjM2MmUzMDNhYzJmY2E5MjhiMWRkMjUzMjI5MDAxYWYzMzBiMmExZjExMGRiZTg1NDZjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jBdwmHK41cexzvTRduAjp3kdLwfQrJZxgjGRi57ublU)
> 
> However, when I enabled the functionality locally, it seemed to work. I'm curious if maybe the original gap was caused by something that was fixed when tokens were re-implemented to use `@{ }` format instead of `$[ ]$`.
> 
> @Eric-B-Wu who probably has context.

followed up offline on this
