### ISSUE TITLE
Concurrency control max limit has changed from 100 in v1 to 50 in v3

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#4186]
### Describe the Bug with repro steps 

![image](<https://github.com/Azure/LogicAppsUX/assets/91279975/b6f58f28-69f0-42ac-aa9e-9148159d1634>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Did some investigation and this looks like we're just not adjusting the limits when an operation is a trigger.
We have the proper limits defined for both `action` and `trigger` but we are only using the `action` limits.
