### ISSUE TITLE
Nested workflow link is missing in new designer

### ISSUE THREAD

**Issue by Xiaoyu-Huang** [Azure/LogicAppsUX#4189]
### Describe the Bug with repro steps 

In old designer, we are able to find the nested workflow link in the workflow run history. Please see image below. Unfortunately, we are not able to find the link in new logic app designer. This is a very useful feature to investigate nested workflow run issues.

![image](<https://github.com/Azure/LogicAppsUX/assets/22843713/feae490e-ebcc-4912-8984-5c3a26911d2f>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
So it looks like this was missed because it never available in standard and standard/consumption handle this action differently. Might be an issue we need to figure out how to standardize on first so that it works in both.

**Comment by lukak-msft** [comment]
+1 on this request.

We rely on subworkflows heavily to encapsulate and reuse logic.
And navigating through complex hierarchies of workflow executions to understand what happened, became very painful in the new UI.

**Comment by hartra344** [comment]
Fixed in https://github.com/Azure/LogicAppsUX/pull/5401
