### ISSUE TITLE
Trigger access option display incorrect value when enable AAD policy

### ISSUE THREAD

**Issue by Drac-Zhang** [Azure/LogicAppsUX#4190]
### Describe the Bug with repro steps 

1. Enable "Azure Active Directory Authorization Policies" in Logic App Consumption with any simple policy

![image](<https://github.com/Azure/LogicAppsUX/assets/72241569/87cf9f13-071c-4dbe-8a14-619dfb998dfe>)

 
2. Go to "Workflow settings" and we will find the "trigger access option" change to "Only other logic apps", but the Logic App still can be triggered from Postman

![image](<https://github.com/Azure/LogicAppsUX/assets/72241569/15810055-5a9a-4a5e-ac8f-a252730b0f4f>)

 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by rllyy97** [comment]
I've found and fixed the issue, it will be a part of our next release cycle which should be deployed to all regions by EoD March 1st.
Setting the trigger access should still function properly, the only issue should be with the value that is displayed upon page load.
