### ISSUE TITLE
The loading of Trigger/Action is not functioning correctly.

### ISSUE THREAD

**Issue by EmilienLeroy** [Azure/LogicAppsUX#4201]
### Describe the Bug with repro steps 

1. Create a new project. 
2. Open the workflow in the designer. 
3. Attempt to add a trigger. 
4. Experience a significant delay in the loading of all triggers. 
5. Once the loading process is complete, notice that several connectors are missing, and no built-in options appear. 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "kind": "Stateful"
}
```

### Screenshots or Videos

[https://github.com/Azure/LogicAppsUX/assets/31723722/bc9a340d-a977-4d25-ac11-cf0c4500e3d7](<https://github.com/Azure/LogicAppsUX/assets/31723722/bc9a340d-a977-4d25-ac11-cf0c4500e3d7>)

When it's finished, there is nothing in the In-App section.

![image](<https://github.com/Azure/LogicAppsUX/assets/31723722/2019e043-cf12-404b-b125-4437e95c0278>)

### Browser

Chrome

### Additional context

I work with remote SSH on VS Code.

Operating System: **Window 10**

 Operating System Remote: **Debian 12**

 VS Code Version: **1\.86.2**

 Logic Apps Extension: **v2.114.0**

Everything else works perfectly. I have created a simple workflow using JSON and ran it locally, and it worked. I only have this issue that is a bit inconvenient for my work.

I have also checked the extension log, and I didn't see any errors in it.

**Comment by ccastrotrejo** [comment]
Hi @EmilienLeroy thanks for raising this issue. 
Are you sure you are using the Logic apps Extions v2.114.0? The latest in production is v2.108.3. Can you use the latest in production and try again if this issue is present? Since this version hasn't been released, I will take a look at the issue and try to fix it before releasing a new version. Thanks!

**Comment by EmilienLeroy** [comment]
Hi @ccastrotrejo,

Yes, I manually installed it from the release section as I encountered the same issue with version 2.108.3. I've tested several previous versions as well. While I suspect the issue might be related to my configuration, I haven't been able to locate any error logs.

**Comment by ccastrotrejo** [comment]
@EmilienLeroy Alright, that makes more sense. I did a couple of tests with v2.114.0 and with the version of the upcoming release cycle. Although I couldn't repro it. Is there any chance I can get your project in a zip file? This will help me to check your config and try to repro it as similar as you are doing it.
You can share it with me to ccastrotrejo@microsoft.com
Thanks!

**Comment by EmilienLeroy** [comment]
@ccastrotrejo I installed the plugin locally, directly on my Windows OS, and it seems to be functioning correctly as I now have access to the In-App connector. However, I am uncertain whether the issue was related to my Linux configuration, the remote SSH setup, or another factor. For the time being, I am closing the issue, but if someone encounters a similar problem with a remote setup or on Linux, it could be the potential cause.

![image](https://github.com/Azure/LogicAppsUX/assets/31723722/a4d5426b-6443-40cb-b6fc-c8a1eea105a6)
