### ISSUE TITLE
run history search on Logic app consumption on overview page is not working

### ISSUE THREAD

**Issue by yaser71180** [Azure/LogicAppsUX#4222]
### Describe the Bug with repro steps 

1. Open logic app consumption at overview page 
2. copy any run id from the list 
3. past the run id in search box "Specify the run identifier to open monitor view directly" and then click the right arrow 
4. we expect to open the run history details, but in reality nothing happens. 

![image](<https://github.com/Azure/LogicAppsUX/assets/32329442/eb171ada-2612-4cbc-a54a-13d815831a36>)

![image](<https://github.com/Azure/LogicAppsUX/assets/32329442/a49c3f3d-fd91-464f-b6ae-e471000f2123>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

Old Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
Taking a look, this appears to be specific to having preview designer enabled though so in the mean time it should work if you use the Generally Available designer. I'll see if we can get a hotfix out for this ASAP.

**Comment by hartra344** [comment]
Hotfix will be out later today with this fixed
