### ISSUE TITLE
Inconsistent output from prettier causing extra changes in PR

### ISSUE THREAD

**Issue by DanielleCogs** [Azure/LogicAppsUX#4234]
### Describe the Bug with repro steps 

Seeing inconsistencies in prettier output between commits/PRs. [https://github.com/Azure/LogicAppsUX/pull/4229/files](<https://github.com/Azure/LogicAppsUX/pull/4229/files>) see comment here. Not a huge issue but can create some confusion for PR reviews.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
NA
```

### Screenshots or Videos

NA

### Browser

NA

### Additional context

*No response*

**Comment by hartra344** [comment]
There's nothing we can personally do about this so I"m going to close it but if you're seeing a case where prettier is being inconsistent please report the bug to them. Their # 2 highest core tenant is consistency (# 1 is don't make functional changes).
