### ISSUE TITLE
Unable to create SendGrid connection

### ISSUE THREAD

**Issue by adelmo-chl** [Azure/LogicAppsUX#4260]
### Describe the Bug with repro steps 

1. Go to the logic app workflow designer 
2. Try to create a new sendgrid connector (send email V4) 
3. The GUI will ask for a name and an API key. 
4. Create the connector. The portal fails with this error:

![Screenshot 2024-02-26 063223](<https://github.com/Azure/LogicAppsUX/assets/137422404/d0e399ca-e75c-42ac-bc6a-a0eafa912d20>) 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome Version 120.0.6099.199 (Official Build) (64-bit)

### Additional context 

*No response*

**Comment by hartra344** [comment]
@rllyy97 Just tried this and I'm able to repro it. Looks like it's an issue on the testLink again, who do we need to rope in to get this fixed?

**Comment by rllyy97** [comment]
I've worked with Brian on testLink work in the past, I'll reach out to him about it and get it figured out

**Comment by shboulatom83** [comment]
> I've worked with Brian on testLink work in the past, I'll reach out to him about it and get it figured out

Hi Riley, we faced the same in LA (Std), in consumption it working fine...

**Comment by rllyy97** [comment]
I spoke with Brian and this appears to be an issue with the `testLink` data that SendGrid is providing for their connector.
Previously when we had a similar issue it was resolved just from the SendGrid team updating their testLink data.
Nothing can be done by us to resolve this unfortunately.

**Comment by rllyy97** [comment]
Quick note, we looked back in our connection log data and for SendGrid connections we saw our `testLink` requests go from all 200s to all 404s like we're seeing now around February 3rd/4th.

**Comment by bryanm0204** [comment]
I think this should be under standard logic apps and not consumption? Is there any workaround to make it work?

**Comment by shboulatom83** [comment]
> I think this should be under standard logic apps and not consumption? Is there any workaround to make it work?

Hi Bryan, seems using old designer allows connection creation:
[https://aka.ms/lafallback](url)

**Comment by bryanm0204** [comment]
> > I think this should be under standard logic apps and not consumption? Is there any workaround to make it work?
> 
> Hi Bryan, seems using old designer allows connection creation in Standard: [https://aka.ms/lafallback](url)
> 
> and using Generally Available Designer for consumption ![image](https://private-user-images.githubusercontent.com/76695917/309736814-03456c82-0216-4293-815e-7fa91bdcdd00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDg0MTUsIm5iZiI6MTcwOTYwODExNSwicGF0aCI6Ii83NjY5NTkxNy8zMDk3MzY4MTQtMDM0NTZjODItMDIxNi00MjkzLTgxNWUtN2ZhOTFiZGNkZDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAzMDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZmIwOWVlNmE5NDVhY2ZiYjQxNjAyMjAzMjcwNmY5MjAwNjBkOTcyNjY2NTEwMTVkY2ZhZjJhYWJmNzVlNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HpsfuIEEun4xc5jcO8NnSnzqPsNKPNPartkCpvsLr8c)

How do I access the old designer for standard? The link you provided returned 0 results. I have no problem creating sendgrid connection via consumption; but I need to make this work in standard.

**Comment by rllyy97** [comment]
@bryanm0204  The link shared is correct but it looks like the underlying url didn't match, use this one: https://aka.ms/lafallback
Also I just tried creating a sendgrid connection in legacy standard and I'm still seeing the same error,  @shboulatom83 if you are able can you take a network trace of you creating the connection in legacy standard?  The requests should be the same between legacy/preview on standard so I'm not sure what might be going on...
My email is RileyEvans@Micosoft.com

**Comment by bryanm0204** [comment]
> @bryanm0204 The link shared is correct but it looks like the underlying url didn't match, use this one: https://aka.ms/lafallback Also I just tried creating a sendgrid connection in legacy standard and I'm still seeing the same error, @shboulatom83 if you are able can you take a network trace of you creating the connection in legacy standard? The requests should be the same between legacy/preview on standard so I'm not sure what might be going on... My email is [RileyEvans@Micosoft.com](mailto:RileyEvans@Micosoft.com)

@rllyy97 I was able to find the old designer. The workaround is good; add the connection in the old designer, save it. Then you may now use the new designer and proceed with the development.

**Comment by shboulatom83** [comment]
> RileyEvans@Micosoft.com

Hi Riley, I sent you the requested over Teams

**Comment by shboulatom83** [comment]
> > @bryanm0204 The link shared is correct but it looks like the underlying url didn't match, use this one: https://aka.ms/lafallback Also I just tried creating a sendgrid connection in legacy standard and I'm still seeing the same error, @shboulatom83 if you are able can you take a network trace of you creating the connection in legacy standard? The requests should be the same between legacy/preview on standard so I'm not sure what might be going on... My email is [RileyEvans@Micosoft.com](mailto:RileyEvans@Micosoft.com)
> 
> @rllyy97 I was able to find the old designer. The workaround is good; add the connection in the old designer, save it. Then you may now use the new designer and proceed with the development.

Hi Bryan, did this work for Consumption or Standard? as seems this workaround is only for Consumption Logic Apps.

**Comment by JatinSanghvi** [comment]
I think it will be worth updating this issue thread. Logic Apps team addressed this issue for both Logic Apps Consumption and Standard on March 27. If you are still seeing the error on Logic Apps (Standard), please be sure to use the new designer when creating the SendGrid connection. Not going into details, but we suspect the issue was caused due to a slight change in the SendGrid API behavior, so we updated the HTTP request being sent to SendGrid to get the problem resolved.
