### ISSUE TITLE
Creation of service bus action is failing in both VSCode and standard portal

### ISSUE THREAD

**Issue by ramya894** [Azure/LogicAppsUX#4264]
### Describe the Bug with repro steps 

1\.Create a new Logic App Project

2. Add a workflow to your local project 
3. Open the workflow.json file in designer and author a new workflow

 a. Add http request Trigger

 b. Add a compose action here with custom text

 c. Add a ServiceBus action. From the add new paramter dropdown add content and add random text in JSON format like {"a":"b"} 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose": {
                "type": "Compose",
                "inputs": "frtgy",
                "runAfter": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

*No response*

### Browser

Microsoft Edge

### Additional context

![servicebus error](<https://github.com/Azure/LogicAppsUX/assets/52390408/c6dc245b-70fc-4f17-b614-e8b7bc0599d1>)

**Comment by rllyy97** [comment]
Hi @ramya894, this will be fixed with the following PR: https://github.com/Azure/LogicAppsUX/pull/4265
