### ISSUE TITLE
Cannot insert Compose output as dynamic content

### ISSUE THREAD

**Issue by tdutch1** [Azure/LogicAppsUX#4269]
### Describe the Bug with repro steps 

1. Create a Logic App Standard workflow 
2. Use Compose to create content 
3. Create a Send Message (Service Bus) action 
4. Select (check) the "Content" parameter to expose the Content field 
5. Click into the Content field, click the lightning bolt icon (dynamic content), and then click the Compose action in the list. Nothing happens. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![logapp_issue_timd](<https://github.com/Azure/LogicAppsUX/assets/7774114/4ab100ac-1c86-4943-a6c7-21cb2b828699>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
@tdutch1  You'll want to click on the "outputs" below the "create json for dataverse update" text to add the action's output as dynamic data.  We've received a few reports that the new UI is confusing people and we're working on adjusting it to be clearer.
Thanks for the report!
