### ISSUE TITLE
Resubmit button not working in new designer

### ISSUE THREAD

**Issue by cristiteodorov** [Azure/LogicAppsUX#4274]
### Describe the Bug with repro steps 

1. Go to an existing, completed run 
2. Make sure you are on the new designer. 
3. Hit Resubmit -> Says it has resubmitted with green tick 
4. Check runs history -> it has not been resubmitted 
5. If you repeat steps 1-4 in old designed, you will see the resubmitted run in the history 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
Thanks for the bug report, we'll have this fixed in the upcoming release. Looks like "Cancel Run" has the same bug so that'll be fixed as well.
