### ISSUE TITLE
Missing "Microsoft.Azure.Functions.ExtensionBundle.Workflows" bundle.

### ISSUE THREAD

**Issue by drobert-bfm** [Azure/LogicAppsUX#4291]
### Describe the Bug with repro steps 

Create a Logic App (Standard) in VSCode for Linux.

Get a "NOENT: no such file or directory, scandir '/home//.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows'" error.

There's no such bundle at that location.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
Not applicable. Any workflow causes this.
```

### Screenshots or Videos

*No response*

### Browser

Not applicable

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hi @drobert-bfm thank you so much for raising this issue. Usually the extension bundle gets downloaded during the activation of the extension when opening vscode. 

- Which extension version are you using?
- During which command are you getting this issue?
