### ISSUE TITLE
Logic App Consumption resubmit feature broken in new designer

### ISSUE THREAD

**Issue by Drac-Zhang** [Azure/LogicAppsUX#4303]
### Describe the Bug with repro steps 

1. Create a Logic App in West Europe and add a "Sliding Window" trigger with new designer 
2. Run workflow once 
3. Open run history window (not run history list in overview) and click resubmit, you will get the exception

![image](<https://github.com/Azure/LogicAppsUX/assets/72241569/539e185a-f556-42f0-a76d-35a0e930c330>) 

Error message in HAR is: 

 {

 "error": {

 "code": "NoRegisteredProviderFound",

 "message": "No registered resource provider found for location 'westeurope' and API version '2018-11-01' for type 'workflows'. The supported api-versions are '2015-02-01-preview, 2015-08-01-preview, 2016-06-01, 2016-10-01, 2017-07-01, 2018-07-01-preview, 2019-05-01'. The supported locations are 'northcentralus, centralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, westus, eastus, eastus2, japanwest, japaneast, brazilsouth, brazilsoutheast, swedencentral, qatarcentral, australiaeast, australiasoutheast, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westus3, jioindiawest, westcentralus, uksouth, ukwest, francecentral, francesouth, koreacentral, koreasouth, southafricanorth, southafricawest, uaecentral, uaenorth, switzerlandnorth, switzerlandwest, norwayeast, norwaywest, germanynorth, germanywestcentral, polandcentral, italynorth, israelcentral'."

 }

 }

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {
            "Sliding_Window": {
                "evaluatedRecurrence": {
                    "frequency": "Minute",
                    "interval": 1
                },
                "recurrence": {
                    "frequency": "Minute",
                    "interval": 1
                },
                "type": "SlidingWindow"
            }
        }
    },
    "parameters": {}
}
```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by hartra344** [comment]
This is a known issue and is fixed in an update rolling out this week.
