### ISSUE TITLE
Azure HTTP connector fails with "BadRequest - Http request failed: the content was not a valid JSON."

### ISSUE THREAD

**Issue by wiktorklusek** [Azure/LogicAppsUX#4304]
### Describe the Bug with repro steps 

Whener my logic apps runs it stops on the HTTP Connector with the following message:

BadRequest

 Http request failed: the content was not a valid JSON. Error while parsing JSON: 'Unexpected character encountered while parsing value: S. Path '', line 0, position 0.'

The issue is, that we are not getting any other information on why it failed, no Status Code is being displayed and no other Outputs are returned.

![image](<https://github.com/Azure/LogicAppsUX/assets/63818570/2a2ff18e-d693-43b5-bfeb-e07435cf3be6>)

![image](<https://github.com/Azure/LogicAppsUX/assets/63818570/a4a61135-e0a2-4a72-b1a4-7fe20135d5b8>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
The TSG tells how to get a HAR adn console trace, Can you please collect those and send them to me at travisharris@microsoft.com ? We'll need a little more information from that in order to debug this.

**Comment by wiktorklusek** [comment]
The Azure portal is sending all the requests in this scenario. Are they archived somewhere on Azure?

**Comment by hartra344** [comment]
Not in a way that helps us with debugging issues like this. We don't store this sort of information from requests because it could cause privacy issues. By asking for a HAR trace, we allow you to curate what we're able to see and limit to only what's needed for debugging a specific issue.
