### ISSUE TITLE
Expression changing itself after hitting save

### ISSUE THREAD

**Issue by shahparth-lab** [Azure/LogicAppsUX#4309]
### Describe the Bug with repro steps 

1. Create a stateful workflow 
2. Add a HTTP trigger, and following HTTP and compose action 
3. Add expression for referring to only $content variable from HTTP action 
4. After hitting save I was given a particular error FOR http action, I have added a screenshot - it says Tokenize\_a\_document is invalid (sharing a video offline) 
5. Even after deleting the action, the error still persists 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
@shahparth-lab  what part of this is behaving unexpectedly? The error message is coming from the backend and is a correct error message. You're referencing an action that doesn't exist in the workflow. When I remove the token or the action it saves just fine. When I reference the HTTP action as it exists it also works just fine.

https://github.com/Azure/LogicAppsUX/assets/13208452/8eae7bb7-0f04-458d-9b3c-51982246386b

**Comment by shahparth-lab** [comment]
@hartra344 The expression changes itself. See when I author it to refer to HTTP and hit SAVE, it changes to an action name ("Tokenize") which does not exist by itself as I have deleted it and it should keep the HTTP reference as expected behavior but it does not for my workflow

**Comment by hartra344** [comment]
ok I see somehting happening in your video, but even following the exact same steps in your video on the exact app you're using.....I can't repro what you're doing.
