### ISSUE TITLE
Resubmit doesn't work

### ISSUE THREAD

**Issue by DruiBanshee** [Azure/LogicAppsUX#4311]
### Describe the Bug with repro steps

1-Resubmit a good run after changing playbook
2-Doesn't get any new log on the Run history
3-Check the activity log:

Resource
/subscriptions/xxxxxxxxxxx/resourcegroups/xxxxxxxx/providers/Microsoft.Logic/workflows/xxxxxxx/triggers/xxxxxxxxx
Operation name: Trigger Run
Time stamp: Tue Mar 05 2024 16:05:46 GMT+1300 (New Zealand Daylight Time)
Event initiated by: xxxxxxxxxxx

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Edge, Firefox

**Comment by hartra344** [comment]
Thank you for the report. This is a known issue, a fix is rolling out this week. In the mean time it should still work with the GA designer.
