### ISSUE TITLE
Option "Show Logic App run details" to follow a call to a different logic app in logs is missing in the Preview Designer when compared to old designer. 

### ISSUE THREAD

**Issue by cristiteodorov** [Azure/LogicAppsUX#4317]
### Describe the Bug with repro steps 

1. Create a logic app that has an Action where a different HTTP trigger logic app is called. 
2. Run the logic app. 
3. Go to see the details / logs of the run. 
4. Select the Action that calls another logic app. 
5. Notice there is no option to: "Show Logic App run details" - this is available in both versions of the old designer and helps a lot when debugging issues. 

Hiding the run Id the user is currently looking at under the "Run Details" button also creates more difficulty when debugging.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
Thanks for the report. We are tracking this issue here #4189 so I’m closing this one as a duplicate.
