### ISSUE TITLE
Unable to see IBM MQ Send message action (built in) after upgrade

### ISSUE THREAD

**Issue by mihoro1181** [Azure/LogicAppsUX#4343]
### Describe the Bug with repro steps 

1. create simple workflow and add any trigger 
2. try to search for MQ (built in)actions and Send message action is no more available 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

Old Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/162995962/fb3216d0-f7b1-4e8c-88d9-7c98cef318e5>)

### Browser 

Chrome

### Additional context 

Unable to see the IBM MQ send message action (built in), after upgrade

**Comment by rllyy97** [comment]
From what I can see we are getting this operation's data properly, but we aren't showing it in search.
I will look into this more and let you know when we've implemented a fix.

**Comment by rllyy97** [comment]
We will be patching a fix for this into the current release, we will be starting the process today and it should finish up sometime tomorrow.
