### ISSUE TITLE
When using appsettings in a connection the designer gives an error for the action

### ISSUE THREAD

**Issue by JWScheijgrond** [Azure/LogicAppsUX#4352]
### Describe the Bug with repro steps 

Create a new workflow

Add a step to call an api in this case the LogAnalytics Data Collector

Change the connections.json to retrieve the subscriptionid from the appsettings.

The designer will no longer show the step

see screenshots for the error message, the connections.json and the log from edge developer tools.

When I replace the appsettings with the subscriptionid value then the designer works again.

This has worked previously and the workflow also works only the designer fails since about a week.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

Trying the fallback for the old designer that does not give an error.

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Log_Failure_To_Send": {
                "inputs": {
                    "body": "{\"SomeError\"}",
                    "headers": {
                        "Log-Type": "FunctionalLog"
                    },
                    "host": {
                        "connection": {
                            "referenceName": "azureloganalyticsdatacollector"
                        }
                    },
                    "method": "post",
                    "path": "/api/logs"
                },
                "type": "ApiConnection"
            },
            "Response": {
                "inputs": {
                    "body": "OK",
                    "statusCode": 200
                },
                "kind": "Http",
                "runAfter": {},
                "type": "Response"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "manual": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![image](<https://github.com/Azure/LogicAppsUX/assets/29395368/4c0c18cc-1734-4f2b-8f12-56323d22b803>)

![image](<https://github.com/Azure/LogicAppsUX/assets/29395368/d059105f-531f-41cd-97cb-cbd226437b0f>)

![image](<https://github.com/Azure/LogicAppsUX/assets/29395368/42eafdbc-f780-474a-a1b0-82c03d13fc54>)

### Browser

- Browser: Edge

### Additional context

*No response*

**Comment by rllyy97** [comment]
Fixed with https://github.com/Azure/LogicAppsUX/pull/4353
We will be hotfixing this change by EoD
