### ISSUE TITLE
Error when trying to select "dataset" in [Refresh a dataset] action of [Power BI] connector.

### ISSUE THREAD

**Issue by metakahash1** [Azure/LogicAppsUX#4358]
### Describe the Bug with repro steps 

Logic app Standard

 In Workflow -> designer

1. Click add action ([Refresh a dataset] action of [Power BI] connector) 
2. Select [Workspace] 
3. Select [Datasets] -> The error occurred, "e.charAt is not function"

![image](<https://github.com/Azure/LogicAppsUX/assets/86219310/0f933cc1-fec4-4be9-aae1-a3a9095723e1>) 

The issue occurs only in the case of Standard Logic Apps new UI.

- Standard Logic Apps Old UI

![image](<https://github.com/Azure/LogicAppsUX/assets/86219310/1a3a2f0e-5a7f-483d-8509-730a7460cd05>)

 
- Consumption Logic Apps

![image](<https://github.com/Azure/LogicAppsUX/assets/86219310/b820e2b7-6f78-429f-87ea-3a692a1cf379>)

 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by valentina-vallalta** [comment]
Hello @metakahash1,
I am having some trouble reproducing this error and need more information from you to continue fixing this. Please send this information to me through email at vvallalta@microsoft.com
I need information from the console errors and the network calls.
To get this information please follow the instructions under "Collecting console errors" and "Collecting network logs in a HAR file" from our docs file found at this [link](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-console-errors). (https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-console-errors)
