### ISSUE TITLE
Expression editor is not complaining about a non existent function at design time

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#4371]
### Describe the Bug with repro steps 

Try putting following function: 

![image](<https://github.com/Azure/LogicAppsUX/assets/91279975/7ffb9157-da23-4503-a55d-609ec105858d>)

or addMonth(utcNow(), 1) and it doesnot complain until runtime error.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
Not likely to change to be honest. We provide the editor some intellesense to help add functions, but it doesn't fully parse the expression or break it into it's full AST to make sure everything is valid. We would need to reimplement the backend functionality to do that and that's not likely.
