### ISSUE TITLE
SFTP-SSH Create File action "Get All File Metadata" flag keeps defaulting to "Yes" even if it's set to "No" from Code View

### ISSUE THREAD

**Issue by kaly-d** [Azure/LogicAppsUX#4375]
### Describe the Bug with repro steps 

1. Open Logic App Standard in new designer. 
2. Add a workflow with an HTTP trigger and SFTP-SSH "Create File" action 
3. By default, the "Get All File Metadata" flag is set to "Yes" 

![image](<https://github.com/Azure/LogicAppsUX/assets/108493323/e178c0cf-8be1-4467-b616-828741599509>)

![image](<https://github.com/Azure/LogicAppsUX/assets/108493323/54d69f6f-1002-41ac-8e3b-dfbb209766bd>)

4. If I save it as "No", the Code View shows the changes have been applied with the flag set to False 

![image](<https://github.com/Azure/LogicAppsUX/assets/108493323/baa747a5-ff1d-447e-835d-4a71707e89f4>)

![image](<https://github.com/Azure/LogicAppsUX/assets/108493323/0a1af004-3ad4-435f-8790-659053a8360c>)

5. If I leave the page and come back to the designer, the "Get All File Metadata" flag is back to showing "Yes", though the Code View still retains the "False" setting. 

![image](<https://github.com/Azure/LogicAppsUX/assets/108493323/204ff6f4-a89d-4353-b24a-d6e0da22418a>)

![image](<https://github.com/Azure/LogicAppsUX/assets/108493323/a25a4ebe-a258-4bba-995e-9977a1b518ce>)

Seems a UI issue only that keeps displayed "Yes", since the Code View is correctly applying whichever flag we set.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Create_file": {
                "inputs": {
                    "body": "123",
                    "headers": {
                        "ReadFileMetadataFromServer": false
                    },
                    "host": {
                        "connection": {
                            "referenceName": "sftpwithssh-1"
                        }
                    },
                    "method": "post",
                    "path": "/datasets/default/files",
                    "queries": {
                        "folderPath": "/home/sftpuser",
                        "name": "test.txt-@{utcNow()}",
                        "queryParametersSingleEncoded": true
                    }
                },
                "runAfter": {},
                "runtimeConfiguration": {
                    "contentTransfer": {
                        "transferMode": "Chunked"
                    }
                },
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "Recurrence": {
                "recurrence": {
                    "frequency": "Second",
                    "interval": 1,
                    "startTime": "2024-03-15T15:29:00",
                    "timeZone": "Pacific Standard Time"
                },
                "type": "Recurrence"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

Get All File Metadata flag is set to True/Yes

![image](<https://github.com/Azure/LogicAppsUX/assets/108493323/543473f5-bbde-480b-b197-6e9ebc5777aa>)

But actually in the Code View, the flag is set to False.

![image](<https://github.com/Azure/LogicAppsUX/assets/108493323/07a0fab0-c7b6-4092-a9c6-0ce0eb2f4e15>)

### Browser

- Edge

### Additional context

This behavior doesn't occur in the old designer. The flag change is properly displayed in the UI.

![image](<https://github.com/Azure/LogicAppsUX/assets/108493323/5af05ee8-e7bf-4e9c-acdf-1f2856671843>)

![image](<https://github.com/Azure/LogicAppsUX/assets/108493323/88dde11f-4d78-4ad0-a6fd-cf2aef5cafde>)

**Comment by hartra344** [comment]
I think this is related to a bug that is fixed in the current release being rolled out next week. I'll verify it today to make sure.

**Comment by hartra344** [comment]
This should now be fixed in production, feel free to reopen if you still reproduce it
