### ISSUE TITLE
Error code insufficient to identify issue and blocking save

### ISSUE THREAD

**Issue by RealScottyD** [Azure/LogicAppsUX#4397]
### Describe the Bug with repro steps 

I am trying to save my workflow and receive an error notification reading "Unexpected number in JSON at position 1 (line 2 column 2)." This doesn't indicate what step the error is in. When I attempt to view the workflow in code view, code view will not load. The error is not showing as an "error" in the menu bar, and it is preventing me from saving my changes.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/122304257/be7f73ca-67a8-4737-8576-69f84a00a5d5>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hey @RealScottyD thanks for raising this issue. Usually, this type of issue occurs when there is an error in the structure of a JSON object, sometimes JSON objects are really picky with the structure like double quotes and numbers, etc.

In this case, as the error says, it's a `workflow serialization error`, which means that something might be wrong with the workflow object structure. So far, I can't tell what's wrong as I can't see your workflow object. Is there any chance you can share with us the workflow structure? You can share it here or send it to my email: ccastrotrejo@microsoft.com

I know that the `code view` button doesn't work, but you can also click in the `Logic app code view` button in the left side panel.
<img width="505" alt="Screenshot 2024-03-20 at 4 47 23 PM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/4d027cec-fd78-4f91-958f-bf8aa97b1641">

**Comment by RealScottyD** [comment]
Hey Carlos @ccastrotrejo, thanks for the quick reply. I back-tracked my steps from the last save point and found that the error occurs when I try to set parameters, specifically for clientId and clientSecret, both as SecureStrings with default values.

**Comment by ccastrotrejo** [comment]
Hey @RealScottyD I am glad you were able to back track and find out the root cause. I think I was able to repro the issue. 
In the meantime could you try to add the double quotation marks at the beginning and at the end of the default value? This will help to make sure to save it as a string.

If this doesn't help, please let me know

**Comment by RealScottyD** [comment]
Hey @ccastrotrejo - Adding the quotes worked. Hopefully this won't impact the actual values that are passed in the HTTP request. I will follow-up if I have any further issues.
