### ISSUE TITLE
SecureString parameter not provided error in new (now GA) Logic Apps designer

### ISSUE THREAD

**Issue by fkoning-sp** [Azure/LogicAppsUX#4404]
### Describe the Bug with repro steps 

1. Create a new Logic App with a SecureString parameter 
2. Fill the parameter with a 'Actual value' (either by deployment or in code view) 
3. Leave the designer 
4. Re-enter the designer (now the actual value will be empty, one of the perks of a SecureString parameter) 
5. Make an random edit to your workflow 
6. Try to save 
7. Now you get an error: Workflow validation failed for the workflow ''. `{"error":{"code":"InvalidTemplate","message":"The template validation failed: 'The value for the workflow parameter '&lt;your parameter&gt;' at line '1' and column '###' is not provided.'."}}` 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

- Browser: Microsoft Edge 

### Additional context 

*No response*

**Comment by rllyy97** [comment]
We are hotfixing this issue, the hotfix should be complete by Monday EoD
