### ISSUE TITLE
Cannot edit in Codeview

### ISSUE THREAD

**Issue by khbrantley** [Azure/LogicAppsUX#4433]
### Describe the Bug with repro steps 

1. Open a Logic App 
2. Click on Code view {} 
3. Attempt to check text in right code view pane 
4. Receive "Cannot edit in read-only editor" error

 It is imperative that this function remains as there are some code updates that can only be made in Code View. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/135636228/fcf6027a-a75a-4b02-9ac9-504244757afc>)

### Browser 

Firefox, Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
This is by design and we don't have plans to change it, the code editor found on the menu panel can still be used to edit code directly. The code view that is side by side with designer is for read only to check output.

**Comment by hartra344** [comment]
https://github.com/Azure/LogicAppsUX/assets/13208452/f2378c95-2662-430a-be09-4d9e2fdda103
