### ISSUE TITLE
addl. UI scroller helps to avoid mouse drag issues - logic app designer view

### ISSUE THREAD

**Issue by SREED365** [Azure/LogicAppsUX#4435]
### Describe the Bug with repro steps 

1. Click on logic app run time to see Error details when there's a failure 
2. New UI is in General Availability in-place of Legacy Designer 
3. No instruction on scrolling to bottom or top to screen, UX may be slightly puzzled, with no guidance to user 
4. Keeping "UI scroller" for look-up navigation is much helpful instead hand symbol press & drag 
5. One click takes less time & efficiency sake, instead press & drag to bottom 
6. personal human energy consumption also more for new navigation in human ergonomics perspective 
7. show the Error highlights, error code as a tool tip and that helps quick idea & smoother operations 
8. Display Error details (high-level) On hover 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome (Google Chrome)

### Additional context 

additional UI scroller helps to avoid mouse drag issues - logic app designer view 

 Like in Legacy Designer

Note: Not sure how TSG helps to get back UI scroller other than using "Enable Legacy Designer" I am good with that to serve the purpose.

**Comment by hartra344** [comment]
I'm not sure I understand the ask @SREED365 , you can use normal mouse scrolling in the UX as well as the drag and pan. It's true there are no scroll bars and there's no real way to add those back but we do have a mini map to that can also be used for navigation. We also added some other ways to navigate, you mentioned errors panel, if you open the error panel and see an error, there should be a "go to operation" button that should take you directly to the action you need to fix.

There is also a magnifying glass button at the bottom left corner; that can be used to jump to any action in the workflow. CTRL+SHIFT+P is a keyboard shortcut for this as well.
