### ISSUE TITLE
Logic app some trigger and action became Chinese

### ISSUE THREAD

**Issue by AllisonLi1230** [Azure/LogicAppsUX#4440]
### Describe the Bug with repro steps 

1. Cx open the logic app standard designer, the trigger and action shows Chinese and the portal language is English. It could not change back to English when we try to restart logic app, change portal language to Chinese and change back to English. 
2. This issue caused the logic app could not be triggered by sentinel playbook 
3. When we changed back to old design, this issue is gone 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/145325914/ff6e9ccf-b611-4456-814d-a082a503f191>)

### Browser 

Chrome, Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
As shown below, the UX does not localize action names regardless of portal language and we use the action name for the . And as far as I can tell, the API also does not localize either based on browser language. The only way to localize the name of a trigger or action is for the user themselves to rename it. 
The name or the name's locale also should not impact runtime or it's ability to trigger at all, if you find that it is please open a support case.

https://github.com/Azure/LogicAppsUX/assets/13208452/c86bf362-6b38-44e0-8eeb-d02220572158
