### ISSUE TITLE
Save button is not working

### ISSUE THREAD

**Issue by john-long2** [Azure/LogicAppsUX#4448]
### Describe the Bug with repro steps 

Make changes the save button does not save the work. When try to browse away it asks if you want to save the work.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/104009538/a8f47375-d52e-4444-8f2e-5597f809b5c5>)

![image](<https://github.com/Azure/LogicAppsUX/assets/104009538/20d16760-cbd9-4f84-bbd9-8f0c4843c07b>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @john-long2, can you provide us with some more info about your situation?  Things like the workflow.json, console logs / network logs would be helpful for us.  You can send the logs directly to my email: rileyevans@microsoft.com

**Comment by john-long2** [comment]
Hi,  

Can you try saving a Logic App Standard in the portal using the new designer?  Doe sit work for you?

If I use https://portal.azure.com/?microsoft_azure_ema_forceFallbackToOldDesigner I can save succesfully.

Thanks
John

**Comment by rllyy97** [comment]
Yes I can save in several of my standard logic apps / workflows.
What behaviour are you seeing when you say "the save button does not save the work"?
Are you seeing any error messages?  Does it say it saved then not show the changes on refresh?

**Comment by john-long2** [comment]
Hi Riley, 

 I have emailed you a video of what is happening and my workflow.json

Thanks
John

**Comment by rllyy97** [comment]
Received.  Can you gather your console and network logs with me over email as well?  From what you've shared it looks like the logs should show us what the problem is.

**Comment by john-long2** [comment]
Hi, sent over email. They bounced first time as too large,

**Comment by rllyy97** [comment]
Not seeing your email, could you try again and zip the files up?  Might still be too large

**Comment by john-long2** [comment]
[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/zip_16x16.png]portal.azure.com 1.zip<https://johnlongconsultancy-my.sharepoint.com/:u:/g/personal/john_johnlong_info/ETz4xOzlumRGm6CYVv759rwBsl9RHlmuQTKHrggBn1j8Aw>

________________________________

**Comment by john-long2** [comment]
________________________________

**Comment by john-long2** [comment]
I've zipped they are 12mb now I've attached as a one drive link see if it works?

**Comment by john-long2** [comment]
[Uploading portal.azure.com.zip…]()

**Comment by john-long2** [comment]
[portal.azure.com-1711467190620.log](https://github.com/Azure/LogicAppsUX/files/14762539/portal.azure.com-1711467190620.log)

**Comment by rllyy97** [comment]
Got the files, I'll take a look and see what I find
I also tried using your workflow json to create an app mirroring yours and I'm not seeing the same issue even with the same workflow.

**Comment by john-long2** [comment]
Thanks Riley,

I'm signing off now I can work around the issue using the old link but I prefer the new designer.

I f you want to screen share tomorrow let me know.

Cheers
John
________________________________

**Comment by rllyy97** [comment]
Sounds good, I'll keep looking and let you know if I find anything.
Thanks for your help John!

**Comment by rllyy97** [comment]
Yeah I'm not able to repro and I'm not sure what would be causing it, logs aren't showing much, we can hop on a call and dig into it more once you're available (I work ~9-5 CST)

**Comment by john-long2** [comment]
Hi Riley, please could we jump on a call today to go through this?  It is affecting more member of the team now so is beocming a bit of an issue for us.  What time is good for you

**Comment by Eric-B-Wu** [comment]
@john-long2, Riley is currently out of office this week, but if you'd like to send an email to Wue@microsoft.com; I can help with setting up a call this week to address this issue

**Comment by rllyy97** [comment]
Hey @john-long2, I'm back in office and am happy to hop on a call with you to take a look at your issue more.  I'd be free anytime ~9-5 CST, if you want to shoot for 9:30am CST any day this week that works great for me.  (Not sure what time zone you are in)
If another time works better for you just let me know, I can be flexible!

**Comment by john-long2** [comment]
Hi Riley,

I have found the issue seems to be confined to one of our subscriptions, but it would be good to take you through it so you can work out why its happening.

I work in the UK so I can jump on a call when you come online.. say 10am  your time?  Think thats 17:00 with me?

Thanks
John
________________________________

**Comment by rllyy97** [comment]
@john-long2 Would you be able to grant me access one of the logic apps in the broken subscription? (rileyevans@microsoft.com)  
The error we saw on the call earlier looks like it could be coming from a lot of different places and I'd like to open it up with my debug tools.
I would recommend creating a new logic app / workflow with just a request and response action to test with.  Also trying this with just those two actions will make sure it's something with the subscription and not the actions within the workflow.

**Comment by john-long2** [comment]
Hi Riley,

I have spent some more time on this.

The issue was in the connections setting.  I have some powershell that create this file as part of the devops pipeline.  As we don't reference any functions in these solutions the value was being set as null.  When I replaced this with {} I was able to save again. I have updated the pipelione now.

Many Thanks for helping me with this.

Cheers
John

[cid:377aee07-f137-4ee8-a14b-9959e1c9a04e]


________________________________

**Comment by rllyy97** [comment]
Glad to hear you found a fix on your side!  I think I also found a couple places that could be causing this issue on our side as well, I'm getting them fixed for anyone else that might run into this in the future.
