### ISSUE TITLE
Unable to choose tenant in Oauth sign in for connectors in Azure portal which restricts in loading subscription  

### ISSUE THREAD

**Issue by ShabsMS** [Azure/LogicAppsUX#4449]
### Describe the Bug with repro steps 

On the new designer , tried creating a Oauth connection (eg Azure event grid ).

The sign in would be successful but the subscription drop down did not list the subscription where i am creating the Logic app (The logic app is present in a subscription of a different tenant .)please refer to the screenshot .

Customers tend to be part of multiple tenant and in old designer we had the option to choose tenant from drop down , now we don't have the option in new designer . When we give custom value of subscription , then we got the error of access token(refer screenshot)

Have used fallback url to fix the issue for now , please fix this.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/95284014/40d35b91-a975-4a98-84a5-b679839accd0>)

### Browser 

edge,chrome

### Additional context 

*No response*

**Comment by PremPandeyyy** [comment]
Hello @rllyy97 
I have another customer with the same issue and the connector is - Azure App Services

**In new designer** - both consumption and standard logic app does not give the option to select the tenant when creating OAuth connection and the subscriptions field in the action shows up the subscription from different tenant customer (Customer is part of multiple tenants)
 
**In old designer(lafallback)** - consumption logic app shows up the option to select the tenant when creating connection whereas the standard doesn't. 


Please could you help with the fix on this as well. Thank you.

**Comment by rllyy97** [comment]
I had some other higher priority work come up when I first took a look at this, and I'm starting my investigation up again.
Will provide updates on a fix as I have them.

**Comment by jesseck3013** [comment]
Hi @rllyy97 

The issue persists with the Azure VM connector. It does not provide options for choosing tenants. I can only create a new connection to the /common/ tenant. 

![Image](https://github.com/user-attachments/assets/eda82dd3-ae49-40da-abfb-018350316122)
