### ISSUE TITLE
Workflow run link missing breadcrumbs

### ISSUE THREAD

**Issue by VicBColeman** [Azure/LogicAppsUX#4460]
### Describe the Bug with repro steps 

1. Select a workflow and click on a recent run 
2. Copy URL 
3. Paste into another tab/window 

Note that breadcrumbs are missing so can't get back to logic app/workflow

 This also appears to break some components

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/165110997/b5bcb83c-2878-46e3-8dfe-a953e3137b6b>)

Few broken components that can't be viewed properly from this URL: 

![image](<https://github.com/Azure/LogicAppsUX/assets/165110997/77c30df3-7823-4869-8046-51adf919872d>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
This is unfortunately a limitation of azure portal deep linking. Nothing we can do to fix that on our end.

as for the broken connectors. Please open a separate issue for that with more information specific to it.
