### ISSUE TITLE
Missing quotation marks on cases after editing.

### ISSUE THREAD

**Issue by taylormb** [Azure/LogicAppsUX#4465]
### Describe the Bug with repro steps 

1. Open logic app 
2. Edit logic app for changes/viewing 
3. Error received upon saving 
4. Quotation marks are wiped from Cases under switches 
5. have to enter quotation marks around case numbers 
6. save successful. 

- every time edit is selected the quotation marks are wiped. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
See attachment
```

### Screenshots or Videos

![ISIRS_EVEN - missing quotes](<https://github.com/Azure/LogicAppsUX/assets/68337878/375256b6-1c40-40b7-ba60-01cb8fb194c1>)

[json.txt](<https://github.com/Azure/LogicAppsUX/files/14775596/json.txt>)

### Browser

Chrome

### Additional context

*No response*

**Comment by hartra344** [comment]
@valentina-vallalta can you check this one out?
