### ISSUE TITLE
Dynamic Schema not rendering with New Designer in Logic Apps

### ISSUE THREAD

**Issue by pavohra** [Azure/LogicAppsUX#4467]
### Describe the Bug with repro steps 

1. Goto portal.azure.com and create a Logic App with consumption model. 
2. In the Logic App Designer, confirm that new designer is enabled. Choose a trigger, and add an action which uses dynamic schema. Enter required parameters to trigger the dynamic schema call. 
3. Observe that the dynamic schema doesn't render as expected. 
4. Save the Logic app. Switch to Legacy designer and confirm that the dynamic schema gets rendered as expected. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

Dynamic schema action with Legacy Designer:

![image](<https://github.com/Azure/LogicAppsUX/assets/57201020/cb967608-4aad-4f56-8b49-acc89aabe688>)

Dynamic Schema action with New Designer:

![image](<https://github.com/Azure/LogicAppsUX/assets/57201020/eab239b8-46a0-4962-a618-fe2f35d53997>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
https://github.com/Azure/LogicAppsUX/assets/13208452/a71ebbb8-e560-43aa-8147-9f71aed64fd1

Do you have any specific examples of actions doing this. I tried with the action in your screenshots and I'm not getting the same behavior you are.

**Comment by pavohra** [comment]
Attached is the video showing the issue. The version you have tried for Execute recommendation action is old and uses static values. We have made changes to use dynamic values and dynamic schema for Execute recommendation action and that's where we are seeing this issue.

In the video you may observe that after I select the Quarantine App option from the drop down, I expect to see the list of parameters show up (App Id1, Environment id1). But nothing shows up. if I save the logic app and switch to legacy Designer, yo may see those parameters show up

![Dynamic Schema](https://github.com/Azure/LogicAppsUX/assets/57201020/bfe6a143-8349-4418-a1e8-86dd6359c898)

**Comment by preetriti1** [comment]
@pavohra I do not see any dynamic parameter in this action in the swagger. I am doing West US region in LA consumption. So if you have any specific region where I can test your latest changes let me know.

**Comment by preetriti1** [comment]
I emailed the exact issue in the connector swagger, the value-path is incorrectly set and once that is updated it should show up in the UI. Open this issue if you have any other issue once the swagger is fixed.
