### ISSUE TITLE
New designer is not showing the action input parameters mapped as inputs in manifest/swagger in monitoring view

### ISSUE THREAD

**Issue by Xiaoyu-Huang** [Azure/LogicAppsUX#4472]
### Describe the Bug with repro steps 

In old designer for kusto connection action, it is showing the cluster, database and query in input parameters in run history.

![image](<https://github.com/Azure/LogicAppsUX/assets/22843713/109356d9-48ac-4997-b9d5-c602ed8cf175>)

in new designer, all those information are missing.

![image](<https://github.com/Azure/LogicAppsUX/assets/22843713/ac5b5d42-5903-491a-b029-a473f93aae71>)

**Same issue applied to all other connections.**

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
Mentioned this to @Xiaoyu-Huang in teams but this might have been a case where old designer was doing some special casing for this connector. If that's the case then we won't be carrying that over. Special casing for specific connectors is something we wholesale said we would not do going forward.

**Comment by preetriti1** [comment]
@Xiaoyu-Huang  - Are you able to see these parameters in the designer when you go for editing with your current connection?

**Comment by Xiaoyu-Huang** [comment]
Does it working for all logic app library versions? I am currently using 4.3.2.

**Comment by Xiaoyu-Huang** [comment]
> @Xiaoyu-Huang - Are you able to see these parameters in the designer when you go for editing with your current connection?

Does it work for any versions? I am curretly using 4.3.2

**Comment by simenums** [comment]
Really good to see this progressing! Will this PR also fix the issue we see with strings being escaped? (correct that they are escaped when being sent to the api, but in the view it should show the string nicely formatted like in the good old designer)

**Comment by simenums** [comment]
@ccastrotrejo : When will this be deployed to production? I still experience issues with this.

**Comment by ccastrotrejo** [comment]
Hi @simenums this should be deployed to production

**Comment by simenums** [comment]
@ccastrotrejo : Thanks for the reply! My fault. I can confirm that it works in production now. All good 👍
