### ISSUE TITLE
Not able to create Azure blob connection (managed connector) with Managed identity in new designer

### ISSUE THREAD

**Issue by jainarpit-ms** [Azure/LogicAppsUX#4478]
### Describe the Bug with repro steps 

**Issue Description:**

When trying to create an azure blob connection (managed connector) getting the below error:

"*Failed to create connection: {"error":{"code":"InvalidApiConnectionDynamicInvokeRequest","message":"The workflow reference is missing in the dynamic invocation request for api connection 'azureblob'. A reference to workflow with managed identity enabled is required for connections that are configured to be used with managed identity."}}*"

The same thing is working in the old designer.

**Steps to repro the issue:**

- Open any new workflow 
- Add Azure Blob trigger "When a blob is added or modified (properties only) (V2)" 
- Try to create connection using the managed identity. 

Attaching the Browser network traces for both designer.

[BlobConnectionIssue\_NewDesigner.json](<https://github.com/Azure/LogicAppsUX/files/14791337/BlobConnectionIssue_NewDesigner.json>)

[BlobConnectionIssue\_OldDesigner.json](<https://github.com/Azure/LogicAppsUX/files/14791338/BlobConnectionIssue_OldDesigner.json>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

New designer:

![image](<https://github.com/Azure/LogicAppsUX/assets/165294421/7b14f1c1-bd09-4dd8-96b0-4b5f56218adc>)

Old Designer

![image](<https://github.com/Azure/LogicAppsUX/assets/165294421/ce95bd23-cb9d-4531-947d-0fb7bbd9e7ad>)

### Browser 

Microsoft Edge

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Do you have either the system identity or a user-defined identity enabled on your logic app?

**Comment by jainarpit-ms** [comment]
The system assigned identity is enable for the logic app
![image](https://github.com/Azure/LogicAppsUX/assets/165294421/023badbd-b1fe-4bb8-a28a-6ab46ef67192)

**Comment by Dave-Coles** [comment]
Same, This is working in my lab environment but I can no longer create a new connection using a System Managed Identity.  Consumption logic app would be no good in this instannce

**Comment by rllyy97** [comment]
Hi all, I'm working on a fix for this and will be hotfixing it today, sorry for any inconvenience this is causing

**Comment by rllyy97** [comment]
This should be fixed in all regions, if anyone is still running into this issue please report it here and we'll take another took!
