### ISSUE TITLE
Problem with the Count parameter of the Until action

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#4481]
### Describe the Bug with repro steps 

1. Create a standard logic app and create a workflow in it 
2. Add the Until loop to it and you can see its Count parameter has a default value of 60 
3. Save the workflow, check code view and designer view, the Count parameter is good with value 60 
4. Now In designer change the Count parameter to some other value like 300, save workflow, check code view and designer view, the Count parameter is good with value 300 
5. Now in designer, delete the Count parameter, save workflow, the code view and designer view look good with no Counter parameter. 

![image](<https://github.com/Azure/LogicAppsUX/assets/49498706/7479cdaa-f60d-4f4d-a553-f80e1d665d6c>)

6. Now add some action like Compose to the workflow, save it, Check code view and designer view , you will find the Counter parameter is back with its default value of 60. 

The old designer does not have this issue, because in old designer, the Counter parameter cannot be deleted.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

ICM 486728741

**Comment by AyanaKobashikawa** [comment]
@Eric-B-Wu 
I'm sorry to bother you.
Please confirm this problem as soon as possible, as it is keeping our clients waiting.

**Comment by Eric-B-Wu** [comment]
Apologies for the delay, we've identified a code bug and will be hotfixing this issue today, we expect this to complete EOD today to all regions.

**Comment by AyanaKobashikawa** [comment]
@Eric-B-Wu 
Before reporting to the customer, I have some additional questions on this issue.
 
Is the Count parameter an optional parameter?
If the Count parameter is deleted, is my understanding correct that the default value will not be set unless the user subsequently modifies the Count parameter with the value?
Is my understanding correct that the loop count of the Until action will exceed the default limit If the Count parameter is deleted (initially 60 loops)?
If the Count paramete been deleted, is it correct that the number of loops in the Until action will exceed 5000?

**Comment by Eric-B-Wu** [comment]
> Apologies for the delay, we've identified a code bug and will be hotfixing this issue today, we expect this to complete EOD today to all regions.

there have been release delays that's still holding the deployment, will try to get this deployed as quick as possible.

**Comment by Eric-B-Wu** [comment]
@AyanaKobashikawa  
1. Is the Count parameter an optional parameter? According to the Manifest, yes.
2. If the Count parameter is deleted, is my understanding correct that the default value will not be set unless the user subsequently modifies the Count parameter with the value? That is what was intended, but there was a bug that we'd use the default anyways when serializing the parameter, causing the issue seen in this bug
3. Is my understanding correct that the loop count of the Until action will exceed the default limit If the Count parameter is deleted (initially 60 loops)? Yes if the limit is unset, it will go until either the loop is finished or the max limit is reached: [Here ](https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-limits-and-config?tabs=consumption#until-loop)is the link for until limits for each sku

4. If the Count paramete been deleted, is it correct that the number of loops in the Until action will exceed 5000? It should be capped at 5000, and if count parameter is unset, it should still not exceed 5000 iterations

**Comment by AyanaKobashikawa** [comment]
@Eric-B-Wu 
Thank you for your answer. I am aware of the contents of 1~4.

This issue has been closed. Thank you for your response.
