### ISSUE TITLE
Can't input outputs body as mock data in new UI designer

### ISSUE THREAD

**Issue by ShingoHanai** [Azure/LogicAppsUX#4501]
### Describe the Bug with repro steps 

1. Open Logic App by designer. 
2. Move to [Testing] tab of target action. 
3. Add "Outputs" in [Testing - Select Fields]. 
4. Add "Body" in [Output - Select Fields]. 
5. You can see there is no component to input mock body. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/66820701/8eaf5952-2fde-418e-a684-57368283fc00>)

### Browser 

Google Chrome

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
This seems like an issue with the manifest, @ShingoHanai would you be able to send me which action this is? If it is a custom connector, would you then be able to send the manifest to me?

**Comment by ShingoHanai** [comment]
@Eric-B-Wu 
In my customer's situation, it happens when using Get risk detections action of Azure AD Identity Protection connector.
However it works fine now. I understand it is related to swagger statement. Is it correct?
![image](https://github.com/Azure/LogicAppsUX/assets/66820701/e3452d7a-c986-4148-8c47-715be0e92f81)

**Comment by Eric-B-Wu** [comment]
@ShingoHanai yep the testing tab is built on top of the existing Swagger, so if there's a problem we'll need to dig into what the connector is sending to address the issue

**Comment by ShingoHanai** [comment]
@Eric-B-Wu Thanks for your teaching. I think there in no problem related to this issue so far. We can close this ticket.
