### ISSUE TITLE
Issue with Connection for a Custom Connector

### ISSUE THREAD

**Issue by rkkudja** [Azure/LogicAppsUX#4503]
### Describe the Bug with repro steps 

1. Open logic apps atpi-corpprofile-prd 
2. Click on edit 
3. Errors tab is highlighted so click on it. 
4. click on open operation 
5. It says invalid connection. so click on change connection 
6. Gives a blank error 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![error](<https://github.com/Azure/LogicAppsUX/assets/39629363/6cab7121-6f43-44bc-a4ce-5ef51b726b70>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by preetriti1** [comment]
@rkkudja - Do you mind sharing network and console logs when you click on edit to open the designer and mail them to psamband@microsoft.com 

It looks like the connection associated with this custom connector is marked as invalid from service, we need to confirm that.

**Comment by rkkudja** [comment]
We found the issue was the new designer in logic apps.  When we switched back to the old designer the error went away.

[cid:stblogo_fd536810-28f5-48fd-9f49-da874aa3b2f7.png]  Robert Kudja
Sr. Net Developer


Starboard Cruise Services
Mobile (786) 556-4846
