### ISSUE TITLE
Localized strings missing Croatian

### ISSUE THREAD

**Issue by Aleks-gdb** [Azure/LogicAppsUX#4507]
### Describe the Bug with repro steps 

The strings are not localized in Croatian.

### What type of Logic App Is this happening in? 

Power Automate

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/42044630/d9d8f39c-87d1-4f10-9398-fc554de5862d>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
Talked to @Aleks-gdb  offline, there are languages PA supports that Azure doesn't support. They are going to help onboard those localizations.
