### ISSUE TITLE
Low Contrast on the new designer token picker for dark team

### ISSUE THREAD

**Issue by wsilveiranz** [Azure/LogicAppsUX#4511]
### Describe the issue 

1. In VS Code, select a dark theme 
2. Open a workflow in design mode 
3. create an action and click on the action picker or function picker 
4. Notice that the titles of the actions / function types uses the same colors as the light theme, making it really hard to read. 

![image](<https://github.com/Azure/LogicAppsUX/assets/13143907/dc83e380-87d1-4bc6-8310-cc4d50b2b301>)

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

*No response*

### Browser 

VS Code

### Additional context 

Tested with latest version of the extension (v.3.0.1)

**Comment by ccastrotrejo** [comment]
Issue was solved in this PR https://github.com/Azure/LogicAppsUX/pull/4376. This will be fixed in the next release cycle
