### ISSUE TITLE
Service Now connection is created and then closes

### ISSUE THREAD

**Issue by nikhilsira** [Azure/LogicAppsUX#4513]
### Describe the Bug with repro steps

https://portal.microsofticm.com/imp/v3/incidents/incident/487762701/summary

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

N/A

**Comment by preetriti1** [comment]
@nikhilsira I have moved this ICM to connectors team because the error is coming from connectors on making dynamic call. Its in the network logs attached. Please let the person know about this if they come back on this and ask them to follow up with connectors team.
