### ISSUE TITLE
Forward/Backward Buttons Missing for While Loops on Run History

### ISSUE THREAD

**Issue by sra80** [Azure/LogicAppsUX#4518]
### Describe the Bug with repro steps 

Click on historical run of a logic app event with a while loop in

 The usual buttons for jumping between each occurrence are missing, making it impossible to debug

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
There was a delay in our hotfix, but we're looking to get this in all regions by EOD today. Apologies for the inconvenience. The item to fix it: https://github.com/Azure/LogicAppsUX/pull/4468
