### ISSUE TITLE
Request to the backend service timed out - Analyze Document for Prebuilt or Custom Models (v3.0 API) 

### ISSUE THREAD

**Issue by lalumiere-mike** [Azure/LogicAppsUX#4522]
### Describe the Bug with repro steps 

Hello,

I would like some guidance on how to troubleshoot the following :

On my Logic App RUNDI: 08584895287534025921438520390CU18

We use the "Analyze Document for Prebuilt or Custom Models (v3.0 API) " Object to get details from an invoice document : 

 Here's my code snippet: 

 {

 "method": "post",

 "queries": {

 "api-version": "2023-07-31"

 },

 "path": "/documentModels/SousContrat\_19032024:analyze",

 "host": {

 "connection": {

 "name": "/subscriptions/802be743-068d-4439-8012-52204b75102f/resourceGroups/Solisco-DEV-RSG/providers/Microsoft.Web/connections/formrecognizer"

 }

 },

 "body": {

 "$content-type": "application/pdf",

 "$content": "JVBERi0xLjQKJeLjz9MKMSAwIG9iago8PAovVHlwZSAvUGFnZXMKL0NvdW50ID … (content truncated for this post)"

 }

 }

We received the following error : GatewayTimeout

{

 "error": {

 "code": 504,

 "message": "Request to the backend service timed out",

 "source": "logic-apis-canadaeast.azure-apim.net",

 "path": "choose[3]\when[1]\choose[1]\otherwise\send-request",

 "policyId": "",

 "clientRequestId": "281958fa-bbd1-4efc-b9ae-13afc0ece6bd"

 }}

This issue has resolved by itself since it was recorded on on April 2nd, 2024 (Canada East) at 9.16AM (EST). Resolution was observed at 2.15pm (EST)

Any idea on we can either find or troubleshoot to the root cause of our issue. Please note that the files to be processed are stored on a Blob Storage.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
For issues like this we suggest opening a support ticket. We can only really help with front end UX issues here and this is something that would need an engineer to look at logs to help with and likely forward to the Gateway team to take a look at.

**Comment by lalumiere-mike** [comment]
> For issues like this we suggest opening a support ticket. We can only really help with front end UX issues here and this is something that would need an engineer to look at logs to help with and likely forward to the Gateway team to take a look at.


Hello, 

Thanks for your response, Do you have the hyperlink to fill a support request ?
