### ISSUE TITLE
No Option to Duplicate Workflow

### ISSUE THREAD

**Issue by jrahma** [Azure/LogicAppsUX#4528]
### Describe the Bug with repro steps 

1. Go to Logic App 
2. Create a new Workflow 
3. Try to create another workflow 

There is no way to duplicate an existing workflow and we have to create the new one from scratch.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

All

### Additional context 

*No response*

**Comment by hartra344** [comment]
Closing for now as this is actually going to require a solid amount of backend work to make possible. Have made them aware that this is an ask.
