### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by jrahma** [Azure/LogicAppsUX#4530]
### Describe the Bug with repro steps 

Currently there is no mobile app to check the status of the workflow log on the move

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Mobile devices

### Additional context 

*No response*

**Comment by hartra344** [comment]
There are currently no plans for a Logic Apps Mobile app
