### ISSUE TITLE
max waiting run value disappearing in the logic app  in new designer .

### ISSUE THREAD

**Issue by ShabsMS** [Azure/LogicAppsUX#4539]
### Describe the Bug with repro steps 

in new designer add the max waiting run setting from code view .

![image](<https://github.com/Azure/LogicAppsUX/assets/95284014/f8dee8d1-9ff2-4c7b-8827-254c26376f0a>)

from the designer peek code of trigger :

![image](<https://github.com/Azure/LogicAppsUX/assets/95284014/e074d121-a46e-4972-8683-8eafecdec918>)

the behaviour is quite weird , sometimes on the initial try we can see the max waiting run setting from designer peek code ,and sometimes not.

the value even disappears from the code of the workflow when we make any change to the Logic app (edit and save).[Both consumption and standard]

![image](<https://github.com/Azure/LogicAppsUX/assets/95284014/9efd3186-15c4-413a-a5f1-af9187d24f56>)

Also we have observed in LA consumption though sometimes the max waiting run is present , the waiting runs are huge in number and not the specified value.

![image](<https://github.com/Azure/LogicAppsUX/assets/95284014/946d3e87-7c98-4eff-8452-ed4c42c5f36c>)

On using old designer we don't see these problems.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

edge

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
adding @preetriti1 as she may know whether or not this setting should be added
