### ISSUE TITLE
Http request trigger not found on Standard Azure Logic app

### ISSUE THREAD

**Issue by siyamthandasabelaomutual** [Azure/LogicAppsUX#4541]
### Describe the Bug with repro steps 

In-App Http Request trigger not found

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
Hi @siyamthandasabelaomutual, I'm unable to reproduce this issue - if possible would you be able to collect HAR traces following these steps: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file and send them to wue@microsoft.com?
