### ISSUE TITLE
open trigger action panel for customized  connection crash the whole UI

### ISSUE THREAD

**Issue by Xiaoyu-Huang** [Azure/LogicAppsUX#4547]
### Describe the Bug with repro steps 

my team owns a customized connector called Geneva Health. In workflow edit mode, open the trigger action of Geneva health connection, it crashes the whole UI.

![image](<https://github.com/Azure/LogicAppsUX/assets/22843713/e38515b3-04c4-4f83-8857-7fc8bf0f42c1>)

Here is the exception throwed in console.

![image](<https://github.com/Azure/LogicAppsUX/assets/22843713/4034f365-663c-4444-bb55-f577a8887573>)

By debugging the code, looks like looks like the trigger panel is trying to sort something, then it throws exception there.

![image](<https://github.com/Azure/LogicAppsUX/assets/22843713/ebefa51b-88d0-473a-99b4-9dc46ff33262>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

`{ "definition": { "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#", "contentVersion": "1.0.0.0", "triggers": { "When_a_monitor_fires_for_an_unhealthy_resource": { "type": "ApiConnectionWebhook", "inputs": { "host": { "connection": { "name": "@parameters('$connections')['Health']['connectionId']" } }, "body": { "namespace": "RecoveryService/V2", "metric": "ResourceMetrics/Healthy", "monitor": "MonitorForUpdateCreate", "completionTimeout": 300, "callbackUrl": "@{listCallbackUrl()}" }, "path": "/api/v1/HealthWebhook/accounts/@{encodeURIComponent('GenevaAutomationTest')}/webhooks/subscribe" } } } ...... `

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
@Xiaoyu-Huang would you be able to send me the manifest of your trigger in the custom connector at wue@microsoft.com?
