### ISSUE TITLE
Dynamic content of the actions in the [Until]action doesn't appear in the following actions

### ISSUE THREAD

**Issue by ZhouYiyun001** [Azure/LogicAppsUX#4556]
### Describe the Bug with repro steps 

Hi,Experts

Cx is facing an issue when using the New Designer view that the Dynamic content of the actions in the [Until]action doesn't appear at the condition action.

 Meanwhile Dynamic content appears properly in the old Designer view. 

 We also reproduced this issue in our environment.

1. Open Logic App by designer. 
2. Add [Until] action to workflow 
3. Add [Get status of job] action (which is in [Azure Automation] connector) in the [Until] action 
4. Add [condition] action to workflow 
5. Click "choose a value" in [condition] action 
6. Find the Dynamic content of [Get status of job] action doesn't appear 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Microsoft Edge

### Additional context 

*No response*

**Comment by ZhouYiyun001** [comment]
@Eric-B-Wu 
Thank you for fixing the issue.
But I still can’t confirm the change in my environment, so the dynamics contents still doesn’t appear at the condition action.
Will it cost more times before the change reflects?

![IMG_0502](https://github.com/Azure/LogicAppsUX/assets/165250510/c3707e42-9573-4b9a-8a14-4dd7b66d8ff8)
![IMG_0501](https://github.com/Azure/LogicAppsUX/assets/165250510/d97e3e70-c3f7-494b-adfa-9f89daa06998)

**Comment by Eric-B-Wu** [comment]
@ZhouYiyun001 this wasn't included in the hotfix, so this will go out in our regular release expected to come out 4/19 in all regions
