### ISSUE TITLE
"Move file" Sharepoint action doesn't show "If Another File Is Already There" options

### ISSUE THREAD

**Issue by AlexM2000** [Azure/LogicAppsUX#4578]
### Describe the Bug with repro steps 

1. Add "Move file" Sharepoint action to workflow 
2. Select "If Another File Is Already There" option. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/47482767/f51e0454-1ee6-457f-9774-ebe64c41c768>)

### Browser 

Microsoft Edge for Business 123.0.2420.65

### Additional context 

*No response*

**Comment by AlexM2000** [comment]
The same issue appears on Google Chrome 123.0.6312.106 (Official Build) (64-bit)

**Comment by AlexM2000** [comment]
Hi @rllyy97, on my side "If Another File Is Already There" still doesn't show options.
![image](https://github.com/Azure/LogicAppsUX/assets/47482767/ae86fc15-4489-4067-a306-0b0d2ece2008)

I understand it might be because fix wasn't deployed to production yet but pinging just in case.

**Comment by Eric-B-Wu** [comment]
Hi @AlexM2000 yeah this hasn't been deployed, we expect this to be part of our regular deployment which is expected to complete in all regions ETA 4/19
