### ISSUE TITLE
Assistant chat not working 

### ISSUE THREAD

**Issue by NenadCrncec** [Azure/LogicAppsUX#4579]
### Describe the Bug with repro steps 

1. go to logic app designer 
2. open Assistant 
3. ask anyting 

assistant reports an error, for any kind of input.

 chat-session-id:237D3CD9-E940-47DC-A3BD-02398B4309F1

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[portal.azure.com-1712652398922.log](<https://github.com/Azure/LogicAppsUX/files/14915992/portal.azure.com-1712652398922.log>)

![image](<https://github.com/Azure/LogicAppsUX/assets/105413747/3727edbe-9e94-4029-a57a-880d9b921d3c>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
@NenadCrncec this may be due to something that in your workflow that our api endpoint isn't handling properly. If possible could you send me a copy of your workflowJson to wue@microsoft.com?
