### ISSUE TITLE
Installation fails because DotNetSDK cannot be downloaded

### ISSUE THREAD

**Issue by paierlep** [Azure/LogicAppsUX#4580]
### Describe the Bug with repro steps 

1. Have VSCode 
2. Follow the installation guide [https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#dependency-installer](<https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#dependency-installer>) \- with the "Install all dependencies automatically (preview)"-Method 
3. Observe that NodeJs, FuncCoreTools install properly, but the .Net SDK installation fails (see log below) 
4. Download .Net SDK 6 manually (i.e.: [https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.420-windows-x64-binaries)](<https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.420-windows-x64-binaries%29>), unzip it into the `.azurelogicapps\dependencies\DotNetSDK` folder. 
5. VSCode Extension works now. 

```
[...]
DotNetSDK Binaries: C:\Users\USER\.azurelogicapps\dependencies\DotNetSDK
Creating temporary folder... C:\Users\USER\AppData\Local\Temp\.azurelogicapps\DotNetSDK
Downloading dependency from: https://dot.net/v1/dotnet-install.ps1
Successfullly downloaded DotNetSDK dependency.
12:15:35 PM: Running command: "powershell -ExecutionPolicy Bypass -File C:\Users\USER\AppData\Local\Temp\.azurelogicapps\DotNetSDK\DotNetSDK.ps1 -InstallDir C:\Users\USER\.azurelogicapps\dependencies\DotNetSDK -Channel 6.0"...
Unable to download https://aka.ms/dotnet/6.0/dotnet-sdk-win-x64.zip.
In C:\Users\USER\AppData\Local\Temp\.azurelogicapps\DotNetSDK\DotNetSDK.ps1:483 Zeichen:13
+             throw $DownloadException
+             ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Unable to download https://aka.ms/dotnet/6.0/dotnet-sdk-win-x64.zip.
```

I am not sure who owns the dotnet-install.ps1 script, however the generated URL is wrong (because EOL of the version?)

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

No Browser

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @paierlep thank you so much for raising this issue, I guess the script is hosted and supported by the dotnet organization/team. I tried to repro the issue and it seems they have changed the url from where the sdk gets downloaded. I will close issue and if you or someone else still faces this issue I will take a further look.
<img width="1060" alt="Screenshot 2024-04-18 at 12 04 40 PM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/ac0698b2-a4f7-4a20-9b88-d3590a2d936a">

**Comment by paierlep** [comment]
OK - Thank you!
