### ISSUE TITLE
Invalid type on split on value '@triggerBody()', split on not in array

### ISSUE THREAD

**Issue by mike-vosskuhler** [Azure/LogicAppsUX#4581]
### Describe the Bug with repro steps 

To reproduce,

1. copy the JSON in the "Workflow JSON" section in this bug report into the code view in a consumption logic app. 
2. Then open the designer, 
3. the legacy designer works fine (you can see the split on working when drilling down into the settings) 
4. the new designer breaks and only displays an error without any abilities to edit the manual trigger step 

This functionality worked fine in the legacy designer and that is also where we designed these logic apps. We are now unable to make changes to those logic apps using the new designer. **See attached screenshot for example of what the error looks like**

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "manual": {
        "splitOn": "@triggerBody()",
        "type": "Request",
        "kind": "Http",
        "inputs": {
          "schema": {
            "properties": {
              "test": {
                "type": "string"
              }
            },
            "type": "object"
          }
        }
      }
    },
    "actions": {},
    "outputs": {},
    "parameters": {}
  },
  "parameters": {}
}
```

### Screenshots or Videos

![image](<https://github.com/Azure/LogicAppsUX/assets/138524308/3edcb531-9de2-4c7a-827a-521037a3ac95>)

### Browser

MS Edge Version 123.0.2420.81

### Additional context

*No response*

**Comment by mike-vosskuhler** [comment]
> It looks like old designer doesn't let you add the split-on property from the UI at first, you have to add it in through code view then it appears in old-designer. Going to check with some folks to see what expected behavior is and if we should just show split-on for that trigger in consumption always.

Having split-on available in the UI by default would definitely be helpful for us.

**Comment by rllyy97** [comment]
@mike-vosskuhler, I took a deeper look into this and we actually do show the split-on setting on the request trigger in both standard and consumption in new designer.  The issue here is that your schema object is of type "object", if you change the schema to be type "array", the setting will appear and should work as you'd expect.  To make the error go away you can just remove the split on value, then edit as needed in new designer.
I'm not sure what the run behavior would have been before when the schema was of type object.

Closing as this all seems to be working as expected but I'll still respond if you'd like to discuss more.

**Comment by mike-vosskuhler** [comment]
> @mike-vosskuhler, I took a deeper look into this and we actually do show the split-on setting on the request trigger in both standard and consumption in new designer. The issue here is that your schema object is of type "object", if you change the schema to be type "array", the setting will appear and should work as you'd expect. To make the error go away you can just remove the split on value, then edit as needed in new designer. I'm not sure what the run behavior would have been before when the schema was of type object.
> 
> Closing as this all seems to be working as expected but I'll still respond if you'd like to discuss more.

Thanks for the feedback @rllyy97, when using an array in the schema it works indeed. In the old designer it would still split any array being passed just fine, but it would indeed not show the split on option in the UI unless added in the code. 

I have tested the suggested solution with the following logic app definition:
```
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {
            "$connections": {
                "defaultValue": {},
                "type": "Object"
            }
        },
        "triggers": {
            "manual": {
                "inputs": {
                    "schema": {
                        "items": {
                            "properties": {
                                "test": {
                                    "type": "integer"
                                }
                            },
                            "required": [
                                "test"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "kind": "Http",
                "splitOn": "@triggerOutputs()?['body']",
                "type": "Request"
            }
        }
    },
    "parameters": {
        "$connections": {
            "value": {}
        }
    }
}
```

and the following payload:
```
[{"test": 1}, {"test": 2}]
```

and it working well. So I will be using this with the new designer going forward.

**Comment by rllyy97** [comment]
@mike-vosskuhler Yeah I think how you had it previously in old designer was just something we should've caught during validation but weren't, the way you have it in your last message is how it should be, glad you've got it working now!
