### ISSUE TITLE
Invalid Number Of User Identities - Multiple user identities are not supported. Please select only one user identity.

### ISSUE THREAD

**Issue by ZoltanK-MSFT** [Azure/LogicAppsUX#4582]
### Describe the Bug with repro steps 

1 - Vanilla new LA Std

2 - add user assigned Managed Identities (I added 9), disable the system assigned Managed Identity.

3 - create a simple workflow (http trigger, O365 send e-mail action)

4 - make a validation error in the workflow in code view and save it (i.e. change "path": "/v2/Mail" to "path": "s/v2/Mail")

5 - try to open designer after it (the error in title occurs)

6 - even after correcting the validation error or deleting the single workflow, and adding a new one, the error remains.

7 - after this when I enabled system assigned MI, the error disappears

8 - keeping the system assigned MI in place, and adding back the validation error, the same error comes.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
happens with simple workflow.
```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by rllyy97** [comment]
This a restriction coming from the backend, on standard logic apps if you leave the system identity enabled you should not see this error page no matter how many user identities you have defined.
