### ISSUE TITLE
Missing button for merging parallel branches

### ISSUE THREAD

**Issue by Drac-Zhang** [Azure/LogicAppsUX#4586]
### Describe the Bug with repro steps 

When switch to preview (GA) designer, after creating parallel branches, we cannot directly add a new action which can merge branches

![image](<https://github.com/Azure/LogicAppsUX/assets/72241569/51ea2b8b-0c00-4e22-82af-f2fc13dd4368>)

In legacy designer, we have following button:

![image](<https://github.com/Azure/LogicAppsUX/assets/72241569/2acd0b05-3af8-4a0a-b308-c8500a10ab9b>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose": {
                "inputs": "Test",
                "runAfter": {},
                "type": "Compose"
            },
            "Compose_1": {
                "inputs": "Test",
                "runAfter": {},
                "type": "Compose"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {
            "$connections": {
                "defaultValue": {},
                "type": "Object"
            }
        },
        "triggers": {
            "manual": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "parameters": {
        "$connections": {
            "value": {}
        }
    }
}
```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by hartra344** [comment]
This was removed by design because it lead to very confusing and inconsistant UI for it. The way to do this now is using the run after setting to be clearer and more precise.
