### ISSUE TITLE
Connections JSON View component has static height, overflows container

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#4591]
### Describe the Bug with repro steps 

When opening the connections JSON view for a logic app, the code editor seems to have a static height.

This has some weird scroll interactions with the page letting you hide the tabs at the top of the connections blade.

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/25409734/80caa75a-acb4-4e45-8c17-5194e59d0cae>)

**Comment by Eric-B-Wu** [comment]
This might be a regression when moanco editor was moved over, and imported here - will take a look

**Comment by rllyy97** [comment]
I think this has been here a while, I saw one of the containers in portal is set manually to 1000px

**Comment by hartra344** [comment]
Yeah this is plain portal, not a react blade. Using same monaco it's been using for a while.

**Comment by hartra344** [comment]
going to close this for now, this is a blade on our backlog to migrate to react
