### ISSUE TITLE
Logic App Standard Connections are not visible under Connections in Resource pane

### ISSUE THREAD

**Issue by Sathyapriaa** [Azure/LogicAppsUX#4601]
### Describe the Bug with repro steps 

Connections are not visible in Logic app Resource pane -> Connections

 Both Managed and built in connectors are not visible and 'Connections.json' file is empty.

 The runtime succeeds without any issue. Same issue noted with fallback URL.

 New API connections are getting created successfully, however those are also not visible in Designer. Adding new connector actions succeeds by using existing connections.

 No errors noted in browser Network logs.

 Console Logs shows below error.

**"Unable to initialize operation details for swagger based operation - Complete\_Quote\_Flow. Error details - Incomplete information for operation 'Complete\_Quote\_Flow' "**

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![errorscreenshot](<https://github.com/Azure/LogicAppsUX/assets/154325672/b21d0821-a05c-4eb3-9adf-72afe1f0f7e4>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
I'm thinking there may be something going on with your permissions or the backend of hte connectors you're using since this is also happening for you with the fallback. There isn't enough information here for us to investigate as a github issue. Are you able to open a support case?

**Comment by hartra344** [comment]
ICM: 492750525
