### ISSUE TITLE
[ Arbitrary error code, needs more information from customer ]

### ISSUE THREAD

**Issue by wx953999109** [Azure/LogicAppsUX#4610]
### Describe the Bug with repro steps 

{

 "error": {

 "code": "InvalidAuthenticationTokenTenant",

 "message": "访问令牌来自错误的颁发者“[https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/”。它必须与此订阅相关联的租户“https://sts.windows.net/1c0be383-a924-44a3-b4fc-1c0c1af304ea/”匹配。请使用颁发机构](<https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/%e2%80%9d%e3%80%82%e5%ae%83%e5%bf%85%e9%a1%bb%e4%b8%8e%e6%ad%a4%e8%ae%a2%e9%98%85%e7%9b%b8%e5%85%b3%e8%81%94%e7%9a%84%e7%a7%9f%e6%88%b7%e2%80%9chttps://sts.windows.net/1c0be383-a924-44a3-b4fc-1c0c1af304ea/%e2%80%9d%e5%8c%b9%e9%85%8d%e3%80%82%e8%af%b7%e4%bd%bf%e7%94%a8%e9%a2%81%e5%8f%91%e6%9c%ba%e6%9e%84>) (URL)“https://login.windows.net/1c0be383-a924-44a3-b4fc-1c0c1af304ea”获取令牌。请注意，如果将订阅转让给另一个租户，并不会影响服务，但有关新租户的信息可能需要花时间传播(最多一小时)。如果只需转让订阅和查看此错误消息，请稍后重试。"

 }

 }

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

edge

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Can you provide us with more information including when and where you are seeing this error object?
We cannot investigate anything from just the error object alone.
