### ISSUE TITLE
Error using API Management action with multipart/form-data request payload: "Failed to retrieve dynamic inputs" after switching to the new designer 

### ISSUE THREAD

**Issue by MatthewFrewin** [Azure/LogicAppsUX#4611]
### Describe the Bug with repro steps 

1. Create an API Management operation with a multipart/form-data request schema. I used the 'echo API' in APIM and created a request with the following JSON:

`"/multiparttest": { "post": { "summary": "Multipart Form Test", "operationId": "multipart-form-test", "requestBody": { "content": { "multipart/form-data": { "schema": { "properties": { "multpart_id_str": { "type": "string" } } } } } }, "responses": { "200": { "description": null } } } } ` 
2. Open/Create a Logic App, and ensure you are using the new designer. 
3. Add an API Management action, choosing the 'echo API' and the 'Multipart Form Test' operation (or whichever API you have created the multipart/form-data operation in). 
4. Once you have selectied the "Operation Id" an error message appears saying "Failed to retrieve dynamic inputs. Error details: 'l is undefined'". 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "manual": {
        "type": "Request",
        "kind": "Http",
        "inputs": {
          "schema": {}
        }
      }
    },
    "actions": {
      "multipart-form-test": {
        "type": "ApiManagement",
        "runAfter": {}
      }
    },
    "outputs": {},
    "parameters": {
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {}
    }
  }
}
```

### Screenshots or Videos

*No response*

### Browser

Firefox

### Additional context

This works fine in the Legacy Designer.

Also, be aware that using the API Management form designer UI to edit an operation with a request type of "multipart/form-data" deletes any previous multipart/form-data for that operation. This is a separate bug that has already been reported for API Management.

**Comment by preetriti1** [comment]
@MatthewFrewin Do you mind sharing the swagger operation for your multipart request? We can use it to investigate on our part on how the swagger is looking and why it is not working in the designer.

**Comment by MatthewFrewin** [comment]
@preetriti1 Sure, here you go:

```
/lists/import_optin:
post:
  tags:
    - Lists
  summary: Lists - Import
  description: >-
    Import a list
  operationId: lists-import
  requestBody:
    content:
      multipart/form-data:
        schema:
          properties:
            id:
              type: string
            api_id:
              type: string
            field_map_api_identifier:
              type: string
            import_file:
              type: file
  responses:
    '200':
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Import_Status'
          example:
            import_status:
              status: ACCEPTED or FAILED
              import_reference: ''
              error_message: Error message if upload failed
```
