### ISSUE TITLE
Logic App Designer slow response - failed to fetch error

### ISSUE THREAD

**Issue by vasugari26121999** [Azure/LogicAppsUX#4616]
### Describe the Bug with repro steps 

When opening the designer (in both Legacy and Generally available designer mode), it just throwing "failed to fetch" error to load the connector actions and even loading the runs is quite delaying and unresponsive.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
This morning there was an outage in West Europe I believe that was causing these symptoms. Would you have been affected by that? Is it still happening?
