### ISSUE TITLE
Sometimes when you click save, the designer then shows you an old version of the flow.

### ISSUE THREAD

**Issue by IDrumsey** [Azure/LogicAppsUX#4625]
### Describe the Bug with repro steps 

doesn't happen everytime, so idk.

1. make a change. 
2. click save. 
3. observe old version of flow being displayed. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @IDrumsey, just double checking but is this a consumption flow using the new designer?  Or are you using old designer?
Also when you say the old version of the flow is displayed are you saying after you refresh, or just immediately the flow reverts to an old version of the workflow when you click save in the command bar?

We will need a little more info as well if you can provide it for us, just see if there are any console errors when you try to save the workflow.
If you are only seeing this on one / a few workflows please include your workflow JSON as well, but if you're seeing this across all apps then it's probably something else.

**Comment by IDrumsey** [comment]
it's consumption on the new designer.

**Comment by rllyy97** [comment]
@IDrumsey Could you please provide the rest of the info from my comment above?  I won't be able to investigate this without it as I'm unable to determine what the specific issue is

**Comment by IDrumsey** [comment]
> @IDrumsey Could you please provide the rest of the info from my comment above? I won't be able to investigate this without it as I'm unable to determine what the specific issue is

Respectfully, no. The docs said pasting some of that info could be sensitive. I'd rather not take that chance. Also that takes me a decent amount of time to do. Especially since this isn't my product. If it helps, I think it happens when you press discard. I've had such a rough time with the new Logic App interface today alone, you'll probably come across the bug if you start messing with building stuff in logic apps. Sorry!

**Comment by hartra344** [comment]
Closing issue since no repro information can be provided

**Comment by Eric-B-Wu** [comment]
Riley had mentioned this may be related to his Portal PR, where our discard basically takes it from the originally cached workflow, our save doesn't recache the original workflow; so if you save, and then discard, it resets the workflow from before the save
