### ISSUE TITLE
error message when adding Microsoft Bookings trigger: The renderComponentIntoRoot component encountered an error while loading.

### ISSUE THREAD

**Issue by ZoltanK-MSFT** [Azure/LogicAppsUX#4630]
### Describe the Bug with repro steps

New workflow - add new Microsoft Bookings trigger, e.g. When a appointment is Created.
Same works with the old/legacy designer.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/74300019/f1ddf31c-a365-47d9-bc04-87a167d2858a)

### Browser

Edge

**Comment by Eric-B-Wu** [comment]
@ZoltanK-MSFT would you be able to send netowrk logs over to wue@microsoft.com. Also do you have any existing Microsoft booking connections or are you creating a new one?

**Comment by ZoltanK-MSFT** [comment]
Discussed with Eric via MS internal channel on 18th April.

**Comment by Eric-B-Wu** [comment]
there is an issue where if dynamic data passes an object, we were not parsing to get dropdown options for dynamic data and thus erroring. I'll have this fixed in my next PR
