### ISSUE TITLE
When there are messages in a queue (V2) does not have split on settings, is it intended or is there a way around to have a run for each Queue Message?

### ISSUE THREAD

**Issue by amshivraj** [Azure/LogicAppsUX#4638]
### Describe the Bug with repro steps

Go to Settings of When there are messages in a queue (V2)  trigger, we cannot find SplitOn functionality

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Cler_-_Publipic_Failed": {
        "type": "Workflow",
        "inputs": {
          "host": {
            "workflow": {
              "id": "Clir"
            }
          },
          "body": {
            "action": "ProcessMes"
          }
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "metadata": {
      "ExportMetadata": {
        "ExportCorrelationId": "89b9ffdb-ec65-4b83-bb63-bb926581fbed",
        "ExportDate": "2024-04-11T06:13:39"
      }
    },
    "outputs": {},
    "triggers": {
      "When_there_are_messages_in_a_queue_(V2)": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "azurequeues"
            }
          },
          "method": "get",
          "path": "/v2/storageAccounts/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}/queues/@{encodeURIComponent('vuccess1')}/message_trigger"
        },
        "recurrence": {
          "interval": 1,
          "frequency": "Second"
        }
      }
    }
  },
  "connectionReferences": {
    "azurequeues": {
      "connection": {
        "id": "/subscriptions/457766d5-a401456/resourceGroups/r-rtaldev/providers/Microsoft.Web/connections/azurequeues-48"
      },
      "connectionName": "azurequeues-48",
      "api": {
        "id": "/subscriptions/45776611-a5b7-d102aa456/providers/Microsoft.Web/locations/centralus/managedApis/azurequeues"
      },
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {
    "topicname": {
      "type": "String",
      "value": "egtpc"
    }
  }
}
```

### Screenshots or Videos

![SplitOnFunctionalityForAzureStorageTrigger](https://github.com/Azure/LogicAppsUX/assets/18248316/e0b32677-4f73-4e40-8bda-e21ad2379268)

### Browser

Edge, Chrome
![SplitOnFunctionalityForAzureStorageTrigger](https://github.com/Azure/LogicAppsUX/assets/18248316/65666af3-e42b-4437-8cc6-d3f2c432bbe9)

### Additional context

When there are messages in a queue (V2) does not have split on settings, is it intended or is there a way around to have a run for each Queue Message? Also, the connections are not triggering even though connections were created properly. Thanks in advance for any help.

**Comment by Eric-B-Wu** [comment]
@amshivraj are you using a stateful workflow? I believe split on is only supported in stateful and note in stateless

**Comment by amshivraj** [comment]
Thanks @Eric-B-Wu , I was using stateless workflow, later on figured out that it is supported only in stateful workflows. Not sure what was the intention from Microsoft team. Would love to understand better the reason. 

Also have issues with Auth in this connector, only Managed Identity works as of now.

**Comment by preetriti1** [comment]
@amshivraj Can you please list the issues you are facing with authentication? like is storagekeys are not working for you?

**Comment by amshivraj** [comment]
![image](https://github.com/Azure/LogicAppsUX/assets/18248316/f9445e6c-62af-4624-bdbe-83fbea6c4e1d)
