### ISSUE TITLE
Test run is not getting generated for Webhook test case

### ISSUE THREAD

**Issue by ramya894** [Azure/LogicAppsUX#4641]
### Describe the Bug with repro steps

Install and setup ngrok
a. Download the ngrok client from [ngrok - download](https://ngrok.com/download) and unzip it.  

Note: Only In standard portal ngrok is not required for this test case to run.

2.
b. Open the unzipped location in CMD

3.
c. Create an account and connect it to the client. ngrok authtoken <your_auth_token>.
		i.  Follow the step 2  https://dashboard.ngrok.com/get-started/setup

4.
d. Expose local host on internet with command "ngrok http 7071" in the command prompt opened in step 1b.

5.
e. Copy the forwarding address, you will need this later to set a property in vs code local settingsSelect Administrator: Command Prompt - ngrok http 7071 
ngrok by @inconshreveable 
Session Status 
ccount 
erslon 
Region 
eb Interface 
Forwarding 
Forwarding 
nnections 
online 
Arjun (Plan: Free) 
2.3.35 
United States (us) 
htt 
: 00K. ic 
-> http://10ca1host:7871 
https://78S288b8b3dg . ngrok.io -> http://10ca1host:7ß71 
ttl 
opn 
pse 
pee 

6.
g. Add the property in local.settings.json in your workflow app under values. Paste value from step e. "Workflows.WebhookRedirectHostUri": [http://<value>.ngrok.io](http://705200b8b3d9.ngrok.io/) o 
local.settings.json X 
{b local.settings.json > 
O workflow.json 
"IsEncrypted": false, 
"Values" : 
"AzureWebJobsStorage": "UseDeve10pmentStorage=true" , 
" FUNCTIONS 
" FUNCTIONS 
"WORKFLOWS 
"WORKFLOWS 
"WORKFLOWS 
"WORKFLOWS 
V2 COMPATIBILITY mODE 
"Workflows. WebhookRedirectHostUri " : 
WORKER RUNTIME": "dotnet", 
": "true", 
"http://78s4fcec7193. ngrok. io" , 
TENANT ID" : 
SUBSCRIPTION ID" : 
RESOURCE GROUP NAME • 
". "brazilsouth", 
LOCATION NAME • 
"72f988bf-86f1-41af -glab-2d7cde11db47" , 
" 8ed4fe6g-c95b -4dd2-ag38-msef1c8abe3" , 
" . "aaaaarchidda" , 

EXPECTED RESULT
Setup is complete

7.
Now you all the callback URLs called from service will go through ngrok client and you can see logs in the client. You can test using
	• HTTP webhook action
	• HTTP webhook trigger
	• API connection actions and triggers like 
		○ sending approval email
		○ sending an email (This is not a part of this test case)
		○ When an email arrives.(trigger)
When an email arrives mentioning me(trigger)

Note: Callback URL in overview page for webhook trigger is not expected anymore.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "HTTP_Webhook_1": {
                "type": "HttpWebhook",
                "inputs": {
                    "subscribe": {
                        "method": "POST",
                        "uri": "https://lognappwebhook.azurewebsites.net:443/api/st/triggers/When_a_HTTP_request_is_received/invoke?api-version=2022-05-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=zOnp4mXDNJqN6NIemCi6tEUc7_B-BSb-tdR8rbe4hOQ"
                    },
                    "unsubscribe": {
                        "method": "POST",
                        "uri": "https://lognappwebhook.azurewebsites.net:443/api/st/triggers/When_a_HTTP_request_is_received/invoke?api-version=2022-05-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=zOnp4mXDNJqN6NIemCi6tEUc7_B-BSb-tdR8rbe4hOQ"
                    }
                },
                "runAfter": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "HTTP_Webhook": {
                "type": "HttpWebhook",
                "inputs": {
                    "subscribe": {
                        "method": "POST",
                        "uri": "https://lognappwebhook.azurewebsites.net:443/api/st/triggers/When_a_HTTP_request_is_received/invoke?api-version=2022-05-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=zOnp4mXDNJqN6NIemCi6tEUc7_B-BSb-tdR8rbe4hOQ"
                    },
                    "unsubscribe": {
                        "method": "POST",
                        "uri": "https://lognappwebhook.azurewebsites.net:443/api/st/triggers/When_a_HTTP_request_is_received/invoke?api-version=2022-05-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=zOnp4mXDNJqN6NIemCi6tEUc7_B-BSb-tdR8rbe4hOQ"
                    }
                }
            }
        }
    },
    "kind": "Stateful"
}

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/cfe8ca73-1e4c-4998-888e-4b76173b2476)

### Browser

VScode:vsversion:4.4.2

**Comment by ramya894** [comment]
Issue repro in the latest Vscode version: 1.70.23

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/3fab41e5-1190-45b5-8756-a4a51e34ca00)

**Comment by ccastrotrejo** [comment]
Hey @ramya894 This issue is related to https://github.com/Azure/LogicAppsUX/issues/2163. Closing this issue as the new scenario doesn't expect the callback to be exposed. We will open this issue and update the test scenario if customers want the callback URL to be exposed.
