### ISSUE TITLE
Open Designer is not working for existing Logicapps project

### ISSUE THREAD

**Issue by sukhmeetb** [Azure/LogicAppsUX#4645]
### Describe the issue

1 Open Folder.
2. Select the logicapps project folder from local
3. right-click on workflow.json
4. Designer gives error. "Error in determing project root"

### Are you using new designer or old designer

New Designer (With action panels)

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/5358821/94c6eb5d-7374-4760-8249-60e1dcd0aacd)

### Browser

Chrome

**Comment by ccastrotrejo** [comment]
Hi @sukhmeetb thanks for raising this issue. When users open the designer usually, we try to find the logic app project root based on the following 3 things

- There is a local.settings.json file in the root folder
- There is a host.json file in the root folder
- The host.json file in the root folder has a `extensionBundle` property like this one:
`"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  `}

If your logic app project is in a multi-root workspace usually a dropdown menu will be prompted to enter the right logic app project root. 

Is there any chance you can verify if none of the prior 3 requisites are met?
