### ISSUE TITLE
Incorrect determination of variable type in Set Variable and subsequent errors/value conversion on save 

### ISSUE THREAD

**Issue by dshapovalov1971** [Azure/LogicAppsUX#4649]
### Describe the Bug with repro steps

Load provided workflow, in new designer it mixes up variable types in **Set Variable** steps. **Set record from registration** and **Set record from user info** steps assign JSON to object type variable and values are set to object, but if you look into Code View for these two steps in the designer, it thinks it's a string type and converts value to string, as well saving it this way and messing up the workflow.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
Does not let me post JSON here, says it is too long

https://dsh.bounceme.net/bug.json
```

### Browser

Edge

**Comment by hartra344** [comment]
Looks like this is related to #4644 so linking and closing this one just in favor of using that one for tracking. Thank you for the report :)
