### ISSUE TITLE
Showing "invalid" value for variables when the values are valid

### ISSUE THREAD

**Issue by IDrumsey** [Azure/LogicAppsUX#4651]
### Describe the Bug with repro steps

I started working on this logic app again and when I try to save, a bunch of errors prevent me from saving. when I look, they're all a bunch of validation errors. They started out saying "Invalid boolean" for initializing variables when the variable was a string type or another type. So I just clicked the type dropdown and clicked string and it went away. But when I pressed save again, new validation errors just popped right back up. Now they're saying

![image](https://github.com/Azure/LogicAppsUX/assets/58646634/3c86e5f5-9770-40d5-8b2b-e37b9a0bc486)

I have no clue how to reproduce this. It just started happening on 4/18/2024. I hadn't worked on this logic app for a couple days and it wasn't happening before.

I did end up fixing it by doing what i said above a lot (clicking the type again) to a point where I just had one pesky validation error left. I fixed that one by deleting the action and recreating it.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by Eric-B-Wu** [comment]
@IDrumsey  thanks for reporting this. This is a bug that was introduced this release. We're currently hotfixing this change. We expect it to be patched within 3-4 hours. Apologies.

**Comment by Eric-B-Wu** [comment]
closing now hotfix is in
