### ISSUE TITLE
Export consumption plan logic app to standard plan logic app

### ISSUE THREAD

**Issue by SunidhiShastry** [Azure/LogicAppsUX#4672]
### Describe the Bug with repro steps

Following instructions here - https://learn.microsoft.com/en-us/azure/logic-apps/export-from-consumption-to-standard-logic-app
1. Installed Logic Apps (Standard) extension (version installed v3.0.3) - on vscode 
2. Selected subscription, region and logic app to export
3. Left default selected option of "Generate infrastructure templates" under Advanced options
4. Review showed green checks against logic app
5. Selected local folder to export to
6. Received error - Export failed. Request failed with status code 400

Expected to see that the consumption plan logic app was exported to local folder specified

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/51328454/0e3f1742-dc42-4b89-a359-3ee746c5fc47)

### Browser

Seeing issue on VSCode

**Comment by ccastrotrejo** [comment]
Hey @SunidhiShastry thanks for raising this issue. It seems that there is an issue with the request sent when trying to get the package. Is there any chance you could check the network tab in developer tools in vscode extension while doing this action?
You can open the developer tools by typing `Ctrl`+`Shift`+`P` and  type `Toggle Developer Tools` in the command paletter
