### ISSUE TITLE
Won't allow copy and paste when trying to create a JSON Schema in When a HTTP request is received trigger or Parse JSON connectors

### ISSUE THREAD

**Issue by ChrispyPage** [Azure/LogicAppsUX#4673]
### Describe the Bug with repro steps

1. Create a flow with a "When a HTTP request is received" trigger.
![image](https://github.com/Azure/LogicAppsUX/assets/88534118/d56ef9f6-2241-453c-ae2e-07a699b5f38f)
2. Click on the "Use sample payload to generate schema".
![image](https://github.com/Azure/LogicAppsUX/assets/88534118/05202ec3-7bb7-4e0c-aef0-8f29aab9a075)
3. Copy a JSON object (from notepad++ for instance) and try to paste in the "Enter or paste a sample JSON payload." editor.
4. No JSON is transferred.
5. The same happens when trying to paste into a Parse JSON connector.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge
Chrome

**Comment by Eric-B-Wu** [comment]
Thanks for letting us know @ChrispyPage, there is a bug in Monaco (the editor we use in this instance) when we updated to their latest version. As a mitigation, we're adding into the latest release a option to at least allow users to Ctrl/ CMD + V onto the editor until they get it fixed on their end.

**Comment by Eric-B-Wu** [comment]
Closing as it is complete and merged, just waiting for UX deployment
