### ISSUE TITLE
LogicApps Custom connector - Unable  to initialize operation details for swagger operation

### ISSUE THREAD

**Issue by fsarabia** [Azure/LogicAppsUX#4675]
### Describe the Bug with repro steps 

After the UX migration to the new designer, a workflow that uses a custom connector stopped working.

The custom connector action finishes as successful (green check) even though it shows the message "Unable to initialize operation details for swagger based operation - Error details - Incomplete information for operation ''" during the run history. I'm also unable to edit the operation and the tabs "Parameters, Settings, Code View, Testing, About" do not appear.

This custom connector uses a "dynamic" connection. 

 "connection": {

 "name": "@parameters('$connections') [variables('dynamicConnName')]['connectionId']"

 }

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by harshalCG** [comment]
Having the same exact issue as above, any leads will be helpful thanks

**Comment by rllyy97** [comment]
Hi @fsarabia + @harshalCG,

I'm currently investigating this issue, could either/both of you send me your workflow.json file?
Possibly also your connections.json file just to be safe, feel free to remove anything values might think are sensitive if you'd like
My email is rileyevans@microsoft.com

**Comment by preetriti1** [comment]
We are unable to resolve the connections because it refers logic app variables in combination with workflow parameters. Currently this is an unsupported scenario because variable values are determined or changed during runtime. We do not resolve variables in the connection expression but we do for workflow parameters.
If this is an arm template variable then this should be sent as resolved before we load the designer, but looks like it is LA variables.

**Comment by fsarabia** [comment]
The flow is not failing, it executes as it should but it shows the
error/warning in the runtime log which is very confusing.  It’s
understandable that it cannot resolve a dynamic connection, but this
warning  is misleading and it didn’t work like that before.  Thanks!

**Comment by preetriti1** [comment]
@fsarabia PLease send a screenshot of which warning you are talking about.

**Comment by fsarabia** [comment]
See the screenshots, I also have included one from the previous UX for you
to compare. Thanks!

All images are from run history.

[image: Screenshot 2024-04-30 at 2.54.02 PM.png]
[image: Screenshot 2024-04-30 at 2.54.14 PM.png]

Previous UX (no warning/error displayed)
[image: Screenshot 2024-04-30 at 2.55.09 PM.png]

**Comment by preetriti1** [comment]
@fsarabia  - I do not see any screenshots attached. Can you please reattach the screenshots?

**Comment by harshalCG** [comment]
I was able to get past this error, had to switch from the new designer view to the old designer view and that solved the issue

**Comment by preetriti1** [comment]
@fsarabia @harshalCG - PLease share the screenshots of the warning you saw earlier, the ones previously shared is not available in teh issue please check. Also old designer is retiring on September 1st
