### ISSUE TITLE
HTTP action with "Authentication" set to "None" shows error in the new designer. Looks fine in the fallback designer.

### ISSUE THREAD

**Issue by JaganMSFTGitHub** [Azure/LogicAppsUX#4679]
### Describe the Bug with repro steps

1. Add a "HTTP" action in a standard logic app workflow and set the "Authentication" to "None". Save the workflow.

<img width="689" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/140811009/58379ae2-00d4-4153-8ede-6b0930cc41c1">

2. Run the workflow.

3. Visit the run history. The HTTP action will show error.

<img width="725" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/140811009/89334ceb-7021-41ca-95ae-5db0d3ac7ee0">

4. Access the same run using the fallback URL and it shows correctly.

<img width="1344" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/140811009/06029425-326e-452e-b8f7-94b27f5acf77">

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "HTTP": {
                "inputs": {
                    "authentication": {
                        "type": "None"
                    },
                    "method": "GET",
                    "uri": "https://www.google.com/"
                },
                "runAfter": {},
                "runtimeConfiguration": {
                    "contentTransfer": {
                        "transferMode": "Chunked"
                    }
                },
                "type": "Http"
            },
            "Terminate": {
                "inputs": {
                    "runStatus": "Succeeded"
                },
                "runAfter": {
                    "HTTP": [
                        "SUCCEEDED"
                    ]
                },
                "type": "Terminate"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Browser

Edge

**Comment by Eric-B-Wu** [comment]
@JaganMSFTGitHub as mitigation please clear the authentication parameter using the X or the clear All. I'm going to work on a fix for this

**Comment by JaganMSFTGitHub** [comment]
Hello @Eric-B-Wu Yes, we have suggested the same workaround to the customer.

Thanks for looking into this. I will wait for the fix.

**Comment by Eric-B-Wu** [comment]
This will be added into our next release which will finish 5/3.

**Comment by Eric-B-Wu** [comment]
Closing as it is complete and merged, just waiting for UX deployment
