### ISSUE TITLE
Logic Apps Designer updates from 2024-04-19 broke custom connector dynamic body schema feature.

### ISSUE THREAD

**Issue by JimGolden** [Azure/LogicAppsUX#4688]
### Describe the Bug with repro steps

Logic Apps Designer updates from 2024-04-19 broke custom connector dynamic body schema feature.
This functionality worked prior to 2024-04-18. It is supported and working in the Legacy Designer.
It also is working in the Power Automate Flow Designer. 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Get_Reference": {
                "inputs": {
                    "body": {
                        "documentId1": " ",
                        "returnValue": "f6affd8c-57d4-08d1-de06-ee2bc4fe222a"
                    },
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['BST_Connect_Dev1']['connectionId']"
                        }
                    },
                    "method": "post",
                    "path": "/v1/document-references",
                    "queries": {
                        "Find": " ",
                        "Top": 100,
                        "documentReferenceTypeRoute": "api/v1/projects/{projectId}/client",
                        "documentType": "api/v1/projects/{projectId}",
                        "environment": "dev1/bst-integration/v1",
                        "schema": "Final"
                    }
                },
                "runAfter": {},
                "type": "ApiConnection"
            },
            "Send_an_email_(V2)": {
                "inputs": {
                    "body": {
                        "Body": "<p>@{body('Get_Reference')?['code']}<br>\n@{body('Get_Reference')?['name']}<br>\n@{body('Get_Reference')?['displayName']}</p>",
                        "Importance": "Normal",
                        "Subject": "test project",
                        "To": "jgolden@bstglobal.com"
                    },
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['office365']['connectionId']"
                        }
                    },
                    "method": "post",
                    "path": "/v2/Mail"
                },
                "runAfter": {
                    "Get_Reference": [
                        "Succeeded"
                    ]
                },
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {
            "$connections": {
                "defaultValue": {},
                "type": "Object"
            }
        },
        "triggers": {
            "When_a_workflow_event_occurs": {
                "inputs": {
                    "body": {
                        "url": "@{listCallbackUrl()}"
                    },
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['BST_Connect_Dev1']['connectionId']"
                        }
                    },
                    "path": "/v1/when-workflow-event-occurs",
                    "queries": {
                        "afterActionState": "InProgress",
                        "beforeActionState": "fddaf77a-33bf-4488-ac43-ec9767792edc",
                        "documentType": "projects",
                        "environment": "dev1/bst-integration/v1",
                        "id": "0",
                        "schema": "Draft",
                        "workflow": "ProjectApproval",
                        "workflowAction": "7d6f0d3c-d407-4ad8-b432-64c923d2b8cb"
                    }
                },
                "type": "ApiConnectionWebhook"
            }
        }
    },
    "parameters": {
        "$connections": {
            "value": {
                "BST_Connect_Dev1": {
                    "connectionId": "/subscriptions/f8e27864-7c7a-4279-ba39-0ea647f307da/resourceGroups/rg-bst-eastus-dev1-bstintsvc/providers/Microsoft.Web/connections/BST-Connect-Dev1",
                    "connectionName": "BST-Connect-Dev1",
                    "id": "/subscriptions/f8e27864-7c7a-4279-ba39-0ea647f307da/resourceGroups/rg-bst-eastus-dev1-bstintsvc/providers/Microsoft.Web/customApis/BST_Connect_Dev1"
                },
                "office365": {
                    "connectionId": "/subscriptions/f8e27864-7c7a-4279-ba39-0ea647f307da/resourceGroups/rg-bst-eastus-dev1-bstintsvc/providers/Microsoft.Web/connections/office365",
                    "connectionName": "office365",
                    "id": "/subscriptions/f8e27864-7c7a-4279-ba39-0ea647f307da/providers/Microsoft.Web/locations/eastus2/managedApis/office365"
                }
            }
        }
    }
}
```

### Screenshots or Videos

Legacy Designer works correctly and dynamically calls body schema.
![image](https://github.com/Azure/LogicAppsUX/assets/12801904/075b5e70-c0b7-4c62-b60b-1f40dc77317c)

**The exact same Logic App in the Generally Available Designer has a bug where it will no longer call the body schema route. It does not render the UI correctly.**
![image](https://github.com/Azure/LogicAppsUX/assets/12801904/43a7bb35-3503-4b38-b3e2-cec2ec236816)

Power Automate Designer works correctly and dynamically calls body schema.
![image](https://github.com/Azure/LogicAppsUX/assets/12801904/aae798a0-b4b6-47ba-8e15-4a8724a0e158)

### Browser

Microsoft Edge

### Additional context

Connector Definition for document-references Looks like this. body schema no longer executes in the new Logic Apps Designer since 2024-04-19 updates.

/v1/document-references:
    get:
      responses:
        '200':
          description: ok
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  description: id
                displayName:
                  type: string
                  description: displayName
                code:
                  type: string
                  description: code
                name:
                  type: string
                  description: name
      summary: List Document Reference
      description: List Document Reference
      operationId: ListDocumentReference
      consumes:
        - application/json
      parameters:
        - name: environment
          in: query
          required: true
          type: string
          description: Environment
          x-ms-summary: Environment
          x-ms-visibility: important
        - name: documentReferenceTypeRoute
          in: query
          required: true
          type: string
          x-ms-visibility: important
          description: Document Reference Type
          x-ms-summary: Document Reference Type
        - name: Find
          in: query
          required: false
          type: string
          x-ms-visibility: important
          description: Find
          x-ms-summary: Find
        - name: Top
          in: query
          required: true
          type: string
          x-ms-visibility: important
          description: Top
          x-ms-summary: Top
        - name: schema
          in: query
          required: true
          type: string
          x-ms-visibility: important
          description: Determine which schema to query (e.g. Draft, Final)
          x-ms-summary: Schema
        - name: documentId1
          in: query
          required: true
          type: string
          description: documentId1
          x-ms-summary: documentId1
        - name: documentId2
          in: query
          required: true
          type: string
          description: documentId2
          x-ms-summary: documentId2
        - name: documentId3
          in: query
          required: true
          type: string
          description: documentId3
          x-ms-summary: documentId3
        - name: documentId4
          in: query
          required: true
          type: string
          description: documentId4
          x-ms-summary: documentId4
        - name: documentId5
          in: query
          required: true
          type: string
          description: documentId5
          x-ms-summary: documentId5
        - name: dependsOnName
          in: query
          required: true
          type: string
          description: dependsOnName
          x-ms-summary: dependsOnName
        - name: dependsOnValue
          in: query
          required: true
          type: string
          description: dependsOnValue
          x-ms-summary: dependsOnValue
      x-ms-visibility: internal
    post:
      responses:
        '200':
          description: Success
          schema:
            type: object
            x-ms-dynamic-schema:
              operationId: GetApiDocumentSchema
              value-path: schema
              parameters:
                documentTypeRoute:
                  parameter: documentReferenceTypeRoute
                apiName: bst-integration-api
                method: GET
                lastRoute: id
                property: responses
                environment:
                  parameter: environment
                excludeProperties: parentPath
                documentSchema: Draft
      summary: Get Reference
      description: >-
        This action retrieves a valid list of values for a reference lookup by
        searching the underlying business keys based on a 'Find' value that you
        provide.
      operationId: GetDocumentReference
      consumes:
        - application/json
      parameters:
        - name: environment
          in: query
          required: true
          type: string
          description: >-
            Dynamic list of Environments that the user can access (e.g.,
            Production, Test).
          x-ms-summary: Environment
          x-ms-visibility: important
          x-ms-dynamic-values:
            operationId: ListAPIEnvironments
            value-path: path
            value-title: caption
            parameters:
              apiNameFilter: bst-integration-api
        - name: documentType
          in: query
          required: true
          type: string
          x-ms-visibility: important
          description: >-
            Dynamic list of root or child Documents available based upon the
            Environment that is selected (e.g., Projects, Projects > Tasks).
          x-ms-summary: Document Type
          x-ms-dynamic-values:
            operationId: ListDocumentTypes
            value-path: route
            value-title: caption
            parameters:
              environment:
                parameter: environment
              parentPath: all
        - name: documentReferenceTypeRoute
          in: query
          required: true
          type: string
          x-ms-visibility: important
          description: >-
            Dynamic list of References available based upon the Document Type
            this is selected (e.g., Client, Company, Organization, etc.).
          x-ms-summary: Reference Type
          x-ms-dynamic-values:
            operationId: ListDocumentReferenceTypes
            value-path: route
            value-title: caption
            parameters:
              environment:
                parameter: environment
              documentType:
                parameter: documentType
        - name: Find
          in: query
          required: false
          type: string
          x-ms-visibility: important
          description: >-
            A Find value used to look up a Reference and provide a valid list of
            values based upon a partial match (contains) of any the underlying
            business keys, including Code and Name.
          x-ms-summary: Find
          default: ' '
        - name: Top
          in: query
          required: true
          type: integer
          x-ms-visibility: important
          description: >-
            A Top value used to restrict and subset the number of results that
            are returned.
          x-ms-summary: Top
          default: 100
        - name: schema
          in: query
          required: true
          type: string
          x-ms-visibility: important
          description: >-
            Dynamic list of Document Schemas based upon the Document Type that
            is selected (Draft or Final).
          x-ms-summary: Schema
          x-ms-dynamic-values:
            operationId: ListDocumentSchema
          default: Final
        - name: body
          in: body
          required: true
          schema:
            type: object
            x-ms-dynamic-schema:
              operationId: GetApiDocumentReferenceSchema
              value-path: schema
              parameters:
                documentReferenceTypeRoute:
                  parameter: documentReferenceTypeRoute
                addValue: true
                addBodyPrefix: false
                environment:
                  parameter: environment
                documentTypeRoute:
                  parameter: documentType
            x-ms-visibility: important
          x-ms-visibility: important

**Comment by JimGolden** [comment]
**This is a very critical issue for our live production clients.** This feature was working in the Logic app new designer as of 4/18/2024. Then discovered broken after the 4/19/2024 deployed updates.
The only workaround is to use the Legacy Designer until this issue can be resolved.

 - name: body
          in: body
          required: true
          schema:
            type: object
            x-ms-dynamic-schema:
              operationId: GetApiDocumentReferenceSchema
              value-path: schema
              parameters:
                documentReferenceTypeRoute:
                  parameter: documentReferenceTypeRoute
                addValue: true
                addBodyPrefix: false
                environment:
                  parameter: environment
                documentTypeRoute:
                  parameter: documentType
            x-ms-visibility: important

**Comment by Eric-B-Wu** [comment]
@JimGolden, will you be able to send me a network trace following this step: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file and send it to wue@microsoft.com? We'll have a hard time identifying the root of the issue without it
