### ISSUE TITLE
cannot connect to Microsoft 365 from azure logic app

### ISSUE THREAD

**Issue by Bingqing-Xu** [Azure/LogicAppsUX#4709]
### Describe the Bug with repro steps

1 go to logic apps
2 click on the node: send email v2 with outlook and Microsoft
3 login with my email 
4 tried with : xbu2nj@bosch.com and bingqing.xu@cn.bosch.com
5 both feedback: no account

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Edge

**Comment by hartra344** [comment]
@Bingqing-Xu are you using the Outlook.com connector or the Office365 connector? 
![CleanShot 2024-04-25 at 11 20 54@2x](https://github.com/Azure/LogicAppsUX/assets/13208452/b6bf6669-4f21-41d9-8dd7-b84b21c41933)

It looks like your emails should be Office365, so if you're using the Outlook.com one it's expecting @outlook.com or something along those lines.

**Comment by Bingqing-Xu** [comment]
My outlook account is for business which come from my company bosch. Which is end with bosch.com or cn.bosch.com.
And my colleague in German used the same type email (end with bosch.com) for the  Office 365 Outlook - Send an email (V2) was succeed. So i think it should be some kind of regional issue but not the incorrect email.

**Comment by hartra344** [comment]
If you're using a business email then you should use "Office 365 Outlook" and not "Outlook.com". That's what you were using?

**Comment by Bingqing-Xu** [comment]
Best regards,

Bingqing XU

Vehicle Motion, IB2 (VM/TCR-Nj)
Bosch Automotive Products (Suzhou) Co. Ltd Nanjing Branch | No.1 Runbo Road (Runyang Road, South Gate) | Nanjing Economic & Technological | Development Zone, Jiangsu | P.R. CHINA
Tel. +86 25 880-40129 | ***@***.******@***.***>

Registered Office: Suzhou, Registration Court: State Administration of Industry & Commerce, P.R.China
Board of Directors: David Xu, Ying Zhang, Norman Roth
​

**Comment by Bingqing-Xu** [comment]
i cannot upload my screen shoot to this comment, so i replied with e-mail. And i have to say i tried both for "Office 365 Outlook" and "Outlook.com". Do not work for anyone.
