### ISSUE TITLE
Cannot save logic app standard workflows after modification

### ISSUE THREAD

**Issue by PremPandeyyy** [Azure/LogicAppsUX#4710]
### Describe the Bug 

When customer makes any modification to his logic app standard workflow, he cannot save it. Nothing happens at all. No error/warning/pop-up. Collected F12 logs but no entry when click on save.

It works fine in the legacy designer - aka.ms/lafallback

This is the workaround for the time being.

Portal Extension Version -

![image](<https://github.com/Azure/logicapps/assets/138096970/e3be7a0d-ca0c-4366-a865-a23dbf7c4beb>)

### Plan Type 

Standard

### Steps to Reproduce the Bug or Issue 

With the above mentioned portal version, just try to edit any existing workflow or add a new one and save it.

 Nothing happens.

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
The expected extension version we should expect for all prod regions is: 2.40408.1.6

**Comment by PremPandeyyy** [comment]
@Eric-B-Wu 
The test performed few mins back. The issue was the same as reported.

![image](https://github.com/Azure/LogicAppsUX/assets/138096970/7426887e-ccd8-4096-a0c0-cb28f37b2c27)

**Comment by Eric-B-Wu** [comment]
can you see if there are any console logs? also is there a repro?

**Comment by PremPandeyyy** [comment]
@Eric-B-Wu, this is the only error that we could see in the console logs when replicating the issue. We do not have in-house repro.

![image](https://github.com/Azure/LogicAppsUX/assets/138096970/1d5f4ab9-f556-40c6-92c9-7f21555cf422)

**Comment by hartra344** [comment]
Are they able to try a different browser? Just to help us narrow down potential causes? Also do they have any browser extensions installed? Can you send us a copy of their workflow json file? This one is one that isn’t making a lot of sense to me without more info.

**Comment by PremPandeyyy** [comment]
So, they just installed Chrome and tried but to no avail. No browser extensions installed.

The issue is also when creating a fresh new workflow, so I don't think it is with any specific workflow definition. Even if they just create a new workflow and try adding a trigger and save, same issue occurs.

![image](https://github.com/Azure/LogicAppsUX/assets/138096970/11f66adf-d76c-4efd-a84f-270feefd6fa3)

**Comment by Eric-B-Wu** [comment]
It's difficult to determine where its erroring, from this error it looks like somewhere instead of an object we're sending a function. Can we collect har logs for when this logic app is initialized, it'll let us see what they have on the logic-app side because this doesn't seem workflow-specific

**Comment by preetriti1** [comment]
@PremPandeyyy - PLease set ClientOptimization to "Off" in the yellow aquare details and the get the console logs, that will help us to see the stack trace much clearly.

**Comment by hartra344** [comment]
@eric-b-wu was this looked at? Is it still valid?

**Comment by Eric-B-Wu** [comment]
This was fixed, was a null check missing that was added. Think its just that we haven't created a deployment since this was checked in (running into some local build issues, but I hope to get that unblocked today)
