### ISSUE TITLE
automasss

### ISSUE THREAD

**Issue by GUIBE27** [Azure/LogicAppsUX#4717]
### Describe the Bug with repro steps

va para o visual code 
faça uma analise profunda das configuraçoes e extensoes 
otimize todas
me forneça os melhores codigos e melhoress recursos

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by hartra344** [comment]
Sorry, I can’t read Portuguese but translate is telling that you’re just looking for best practices? Is this reporting an actual bug?
