### ISSUE TITLE
For Scope Copy/Paste iterator tokens aren't updated

### ISSUE THREAD

**Issue by hartra344** [Azure/LogicAppsUX#4724]
For Scopes such as for each loops, when copy/pasted, the tokens references inside aren't updated to reference the new scope name they fall under

**Comment by Eric-B-Wu** [comment]
oh thought I did add support for this, I can take a look again

**Comment by Eric-B-Wu** [comment]
oh I see the issue, I update the token value (so when hovering the token itself), but i dont update the serialized value
