### ISSUE TITLE
Token search is limited to 12th keyword

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#4731]
### Describe the Bug with repro steps

More details here: https://msazure.visualstudio.com/One/_workitems/edit/27575618

<img width="869" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/91279975/b8f51b54-06d7-4b96-bc2a-6eb3776157e6">

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by Eric-B-Wu** [comment]
we can try to increase the threshold to see if that fixes the issue

**Comment by hartra344** [comment]
@eric-b-wu is there a reason for a threshold on this at all? Couldn't we just search the entire token name?

**Comment by kisubedi** [comment]
Yes please, that'd be great. Thank you,
Kishor
________________________________

**Comment by hartra344** [comment]
Found the issue and fixed it in other search places as well. It looks like Fuse(our library for fuzzy search) by default places higher priority on characters at the beginning of the string and falls off almost completely around 12. This change above tells it to ignore the location in the string.
