### ISSUE TITLE
No error is detected when an invalid parameter is left behind from a deleted action

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#4732]
### Describe the Bug with repro steps

Flow checker pane when it shows error and warnings- makers have a way to click on the error and corresponding action will open up. However, When design time errors dont open in Flow checker, maker needs to painstakingly search for the erroring action looking at the error message and the action name from error message banner. 

Manual -> Get items 
In Get items, put a valid Site address/library name from dropdown
Now add Apply to each action and consume the body/value token from  Get items action
Add a compose action, you can put anything here.
Now remove the Site address/library name from step #2- and try publishing the flow
![image](https://github.com/Azure/LogicAppsUX/assets/91279975/d7ac5f63-7a2c-40c2-86f7-65f95a5be170)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by hartra344** [comment]
The bug here isn't that we aren't surfacing design time errors in Flow Checker, it's that we aren't detecting invalid tokens when actions are deleted(and aren't removing them either, that part is on purpose).

**Comment by hartra344** [comment]
Recording of issue here: 

https://github.com/Azure/LogicAppsUX/assets/13208452/c2d2b44b-a3f2-4c7d-b687-4d51a6903e40

**Comment by kisubedi** [comment]
Thank you for the video walkthrough @Travis ***@***.***>. Can we pop open Flow checker pane for this sort of action level errors ?  I understand some flow level errors don't make sense, but majority of errors I assume are action level errors, and its painstaking for makers to know which action is erroring in the absence of the Flow checker (view error -> click and navigate to action) functionality.

Sincerely,
Kishor
________________________________

**Comment by hartra344** [comment]
Found that we have anohter issue tracking this specific problem: #2343 closing this to use that for tracking
