### ISSUE TITLE
custom parameter couldn't be added in  [Create job] action in Standard Logic Apps designer view

### ISSUE THREAD

**Issue by ZhouYiyun001** [Azure/LogicAppsUX#4735]
### Describe the Bug with repro steps

Hi,Experts

Cx is facing an issue when using the New Designer view in Standard Logic Apps that the needed custom parameter couldn't be added in [Create job] action in Azure Automation connector, since there is no [Runbook Parameter] option.
So the Cx feel confused when using the Standard Logic Apps.

We also reproduced this issue in our environment.

1. Open Logic App by designer.
2. Add [create job] action to workflow 
3. Open parameters tab and open [Advanced parameters] pull down
4. Find there is no [Runbook Parameter] option in [Advanced parameters].

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

edge

**Comment by ZhouYiyun001** [comment]
![IMG_0643](https://github.com/Azure/LogicAppsUX/assets/165250510/2188cbdc-46a9-450e-a281-bc658af85029)

**Comment by hartra344** [comment]
This is unfortunately a case where we have 2 actions/connectors that have the same name/seemingly do the same thing. When you search for create job there are 2 options as shown below. One without a badge and one with the "In App" badge. If you are looking for the one with "Runbook Parameters". You are looking for the one with the "In App" badge. This isn't a UI issue but I will pass the feedback along to the team that owns the connectors.

![CleanShot 2024-04-29 at 21 47 15@2x](https://github.com/Azure/LogicAppsUX/assets/13208452/c00bb1ee-06ee-42c1-afdd-683b3f534687)
