### ISSUE TITLE
Paste/Schema Paste not working

### ISSUE THREAD

**Issue by vim5818** [Azure/LogicAppsUX#4738]
### Describe the Bug with repro steps

1. Copy a schema from notepad or from another ALA workflow.
2. Add an " Action"--> "Parse JSON" ---> Input --> Schema.
3. Try to Paste Schema or even try to paste a Sample Payload. --> Right click, 'Paste' nothing happens, use shortcut --> "Ctl + V" nothing happens.
5. It will not do anything

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Microsoft Edge

**Comment by hartra344** [comment]
THis is a known issue with the Monaco editor: https://github.com/microsoft/monaco-editor/issues/4474

In the next release rolling out in the next week we have rolled back the Monaco Editor version to a version where this worked
