### ISSUE TITLE
List Blob (V2) started to break after 4/30/2024

### ISSUE THREAD

**Issue by algeehui** [Azure/LogicAppsUX#4747]
### Describe the Bug with repro steps

**Description**
List Blob (V2) started to break after 4/30/2024. During the time no changes were made in the Logic App or Storage Account. 

I found that it works only when folder is specified as a Container (and not Folder in a Container). 

**Works with Container but not Folder**
Works when Folder = "/edw-landing" (which is a container)

Does not work when Folder = "/edw-landing/AdHocs/" (which is a folder)

![image](https://github.com/Azure/LogicAppsUX/assets/9313701/bc155dee-1293-4d87-8cc1-b55718021d44)

**Error from Lists blobs (V2)**
`"body": {
        "status": 400,
        "message": "Verify that the path exists and does not contain the blob name. ListFolder is not allowed on blobs.\r\nclientRequestId: d5081c8a-299e-4eec-a8d5-6e80bea371a1",
        "error": {
            "message": "Verify that the path exists and does not contain the blob name. ListFolder is not allowed on blobs."
        }}
`

**Tried the following but did not make a difference:** 
- Types of Blob Storage account 
   > StorageV2 with Hierarchical Namespace
   > StorageV2 with Hierarchical Namespace
- Types of API Connection Authentication
   > Access Key
   > Logic Apps Managed Identify

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "properties": {
        "provisioningState": "Succeeded",
        "createdTime": "2024-05-01T16:57:54.3924592Z",
        "changedTime": "2024-05-01T18:35:39.5782726Z",
        "state": "Enabled",
        "version": "08584870183458978211",
        "accessEndpoint": "https://prod-18.westus2.logic.azure.com:443/workflows/f028ccf926aXXXXXXXXXXXXXXXXXXX",
        "definition": {
            "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
            "contentVersion": "1.0.0.0",
            "parameters": {
                "$connections": {
                    "defaultValue": {},
                    "type": "Object"
                }
            },
            "triggers": {
                "Recurrence": {
                    "recurrence": {
                        "interval": 15,
                        "frequency": "Day",
                        "timeZone": "US Mountain Standard Time",
                        "schedule": {
                            "hours": [
                                "5"
                            ],
                            "minutes": [
                                0
                            ]
                        }
                    },
                    "evaluatedRecurrence": {
                        "interval": 15,
                        "frequency": "Day",
                        "timeZone": "US Mountain Standard Time",
                        "schedule": {
                            "hours": [
                                "5"
                            ],
                            "minutes": [
                                0
                            ]
                        }
                    },
                    "type": "Recurrence"
                }
            },
            "actions": {
                "Lists_blobs_(V2)": {
                    "runAfter": {},
                    "metadata": {
                        "JTJmZWR3LWxhbmRpbmclMmZBZEhvY3MlMmY=": "/edw-landing/AdHocs/",
                        "JTJmZWR3LWxhbmRpbmc=": "/edw-landing",
                        "JTJmZWR3LWxhbmRpbmclMmZDTVMlMmY=": "/edw-landing/CMS/"
                    },
                    "type": "ApiConnection",
                    "inputs": {
                        "host": {
                            "connection": {
                                "name": "@parameters('$connections')['azureblob']['connectionId']"
                            }
                        },
                        "method": "get",
                        "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}/foldersV2/@{encodeURIComponent(encodeURIComponent('/edw-landing/AdHocs'))}",
                        "queries": {
                            "useFlatListing": false
                        }
                    }
                }
            },
            "outputs": {}
        },
        "parameters": {
            "$connections": {
                "value": {
                    "azureblob": {
                        "id": "/subscriptions/a9cd0XXX-XXXX-XXXX-XXXXXXXXX/providers/Microsoft.Web/locations/westus2/managedApis/azureblob",
                        "connectionId": "/subscriptions/a9cd0XXX-XXXX-XXXX-XXXXXXXXX/resourceGroups/rg-WB-EDW-TEST-ALVIN/providers/Microsoft.Web/connections/azureblob",
                        "connectionName": "azureblob"
                    }
                }
            }
        },
        "endpointsConfiguration": {
            "workflow": {
                "outgoingIpAddresses": [
                    {
                        "address": "13.XX.XXX.XXX"
                    }
                ],
                "accessEndpointIpAddresses": [
                    {
                        "address": "13.XX.XXX.XXX"
                    }
                ]
            },
            "connector": {
                "outgoingIpAddresses": [
                    {
                        "address": "52.XXX.XXX.XXX"
                    }
                ]
            }
        }
    },
    "id": "/subscriptions/a9cd0XXX-XXXX-XXXX-XXXXXXXXX/resourceGroups/rg-WB-EDW-TEST-ALVIN/providers/Microsoft.Logic/workflows/ala-wellsky-payroll-alvin-listdir2",
    "name": "ala-wellsky-payroll-alvin-listdir2",
    "type": "Microsoft.Logic/workflows",
    "location": "westus2",
    "identity": {
        "type": "SystemAssigned",
        "principalId": "a5c47XXX-XXXX-XXXX-XXXX-XXXXXXXX",
        "tenantId": "cfd86XXX-XXXX-XXXX-XXXX-XXXXXXXX"
    }
}
```

### Browser

Chrome

**Comment by preetriti1** [comment]
@algeehui - I can see incorrect value in the definition as folder parameter in the path value, if that is corrected it would work fine. I cannot repro this in the production portal.

The path value in List Blobs (V2) should be replaced with `"/v2/datasets/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}/foldersV2/@{encodeURIComponent(encodeURIComponent('JTJmZWR3LWxhbmRpbmclMmZBZEhvY3MlMmY='))}",`

How was this definition created? was it really not updated recently?

**Comment by algeehui** [comment]
@preetriti1 Great observation! I do not know why the version of Workflow JSON showed like that. I used the "Open folder" button to choose a folder and tried running it again but still got the same error. 

![image](https://github.com/Azure/LogicAppsUX/assets/9313701/a1019eb0-3c45-427e-bd3b-2ef70ef1c16d)
![image](https://github.com/Azure/LogicAppsUX/assets/9313701/bbcfbba0-ce26-46df-b6f4-519d534b3245)

**Comment by Eric-B-Wu** [comment]
I've opened an incident on our partner team who owns this connector to get more information from them on why this action/trigger is failing. From what we're seeing this is only happening in west us 2, so it may be possible to try this on a different region and see if that resolves the issue

**Comment by algeehui** [comment]
The failed Logic Apps with List Blob (V2) in West US 2 are working properly now. Appearently the issue has been fixed! Thank you so much for the prompt response!
