### ISSUE TITLE
Initialize variable/Set variable for string fails with "Enter a valid integer."

### ISSUE THREAD

**Issue by niphlod** [Azure/LogicAppsUX#4750]
### Describe the Bug with repro steps

1. Add a "Initialize variable" block
2. Set the type to "String"
3. try setting a default value as a string

It seems that the problem happens since the introduction of FlowChecker, and it happens opening already existing flows, new ones are not affected

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/122119/ceaeeca6-4085-4d6f-b4f3-f986267aec3d)

![image](https://github.com/Azure/LogicAppsUX/assets/122119/5128ca0b-9380-440a-abbe-3e504c667931)

![image](https://github.com/Azure/LogicAppsUX/assets/122119/0411150e-5287-4475-a947-ccc1c6631844)

### Browser

VSCode Editor

**Comment by Eric-B-Wu** [comment]
Thanks for reporting to us this regression, we've hotfixed an update to v4.13.2, and and we're advising to not use 4.4.3. Apologies for the inconvenience

**Comment by niphlod** [comment]
thanks a lot @Eric-B-Wu
