### ISSUE TITLE
Int variables in visual studio code designer

### ISSUE THREAD

**Issue by Trumslagaren** [Azure/LogicAppsUX#4751]
### Describe the Bug with repro steps

An initialized integer variable is not handled correct within visual studio code.

The value that is set to the variable is handled as string. Doesn't matter if I try to convert the value to int. It's still handled as string.

If I modify the code and set the value to int in the json file and then opening up the designer, it's converted back to string.

After deploy and trying to run the workflow I get an error indicating that the variable cannot be updated with a String value.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

![1](https://github.com/Azure/LogicAppsUX/assets/148242906/388cc992-e6db-4eee-802e-ffdca7dcf246)
![2](https://github.com/Azure/LogicAppsUX/assets/148242906/1574f050-20e8-435d-bff6-f493a4f2b1a9)
![3](https://github.com/Azure/LogicAppsUX/assets/148242906/be16aaf0-b854-480f-a27b-06303d967dc6)

### Browser

Chrome

**Comment by Eric-B-Wu** [comment]
Thanks for reporting to us this regression, we've hotfixed an update to v4.13.2, and and we're advising to not use 4.4.3. Apologies for the inconvenience
