### ISSUE TITLE
Not able to Export Logic App even after Sign-in

### ISSUE THREAD

**Issue by TejaswiParimi2009** [Azure/LogicAppsUX#4752]
### Describe the issue 

Not able to Export Logic App even after Sign-in in Visual Studio Code

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @TejaswiParimi2009 what is the issue that you are experiencing?
Can you try to sig in using the following command from the command palette? Please make sure is the command `azure-account.login`
<img width="649" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/5edad9b0-8ea1-4d04-8da9-a7d6823341af">
