### ISSUE TITLE
Different input required in portal vs VSCode when using the Dataverse connector

### ISSUE THREAD

**Issue by Trumslagaren** [Azure/LogicAppsUX#4753]
### Describe the Bug with repro steps

Having issues using VS code with the Dataverse connector and when using the Bound to Action method.

In Azure Portal it seems to work fine, but when using VS code I suddenly get additional required parameters that are mandatory. I need to manually remove the parameters from the json every time I use the designer. The workflow runs when I publish and the parameters has been removed, if I just fill in any value in the parameters and publish the workflow, it fails on every run.

It has nothing to do with the input to the action in Dynamics, the required parameters shows up on every action.

This is what VSCode generates as mandatory parameters.

 "body": {
        "error": {
            "code": "",
            "message": ""
        }
    }

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![5](https://github.com/Azure/LogicAppsUX/assets/148242906/6afe6303-070a-418e-8002-7b87ef4cd339)
![4](https://github.com/Azure/LogicAppsUX/assets/148242906/05cf1048-29c9-4258-bb67-65f718b820c1)

### Browser

VSCode/Chrome

**Comment by preetriti1** [comment]
@ccastrotrejo - We need to update vscode vsix with the latest hotfix we did for portal, these contain bug fixes for the dynamic issues.

**Comment by ccastrotrejo** [comment]
Will release a new extension version by the end of the day today

**Comment by ccastrotrejo** [comment]
@Trumslagaren please update the extension to the newest version. This latest version will include the fix for it.
