### ISSUE TITLE
VS Code Designer 4.4.3 Flow Checker - "Enter a Valid Array" Error

### ISSUE THREAD

**Issue by anthonywhite** [Azure/LogicAppsUX#4756]
### Describe the Bug with repro steps

1. Valid workflow under 3.0.3 extension version
2. Upgrade VS Code extension to 4.4.3
3. Open in designer, add a note to trigger
4. Flow checker reports multiple errors on Init variable actions - "Enter a Valid Array"
5. These are integer/string vars!
6. switch back to extension 3.0.3 all is fine again

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/22643372/fe53be7f-46c0-4227-bc7a-6c6ad08b8652)

### Browser

N/A

**Comment by Eric-B-Wu** [comment]
Thanks for reporting to us this regression, we've hotfixed an update to v4.13.2, and and we're advising to not use 4.4.3. Apologies for the inconvenience
