### ISSUE TITLE
Add resubmit from action feature to Azure Logic Apps REST API

### ISSUE THREAD

**Issue by kalarusp** [Azure/LogicAppsUX#4776]
### Describe the Bug with repro steps

There is a new feature included in new designer to resubmit from action. However, we'd love to have the same feature available from Logic Apps REST API like we do have for resubmit of whole logic app run - https://learn.microsoft.com/en-us/rest/api/logic/workflow-trigger-histories/resubmit?view=rest-logic-2016-06-01&tabs=HTTP.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by hartra344** [comment]
It’s actually the same API 😊 the difference is that you include a body with the actions you want to resubmit from. I’ll reach out to our docs people about making sure it’s added to our docs but if you want to see it in action and how it works, just check out the network inspector from your browser.
