### ISSUE TITLE
Multi-select for connectors

### ISSUE THREAD

**Issue by kalarusp** [Azure/LogicAppsUX#4777]
### Describe the Bug with repro steps

Enable connector multi-select to be able to copy or delete many actions at once.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by hartra344** [comment]
There are technical reasons we can’t do multi select of loose actions, however we’re rolling out copy/paste for scope nodes now. You should see that in the next few days and should allow you to copy paste large groupings of actions.
