### ISSUE TITLE
Enable copy/paste between logic apps opened in separate tabs

### ISSUE THREAD

**Issue by kalarusp** [Azure/LogicAppsUX#4779]
### Describe the Bug with repro steps

Enable copy/paste between logic apps opened in separate browser tabs.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by hartra344** [comment]
We made a change in the release rolling out now (should be done by 5/8) that enables the use of the OS clipboard for copy/paste #4668 This should allow this as well as even different browsers or even between a browser and VSCode.
