### ISSUE TITLE
Workflow not deployed to portal after successful deployment.

### ISSUE THREAD

**Issue by v82abhishekverma** [Azure/LogicAppsUX#4793]
### Describe the Bug with repro steps 

I am using Azure Logic App Standard extension v4.13.2. Developed the stateful workflow locally using Visual Studio Code. Deployed to Azure using VS code. Output window show deployment successfully, connection and parameter file deployed but workflow is missing. I cant see workflow on portal.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

I am using Azure Logic App Standard extension v4.13.2. Developed the stateful workflow locally using Visual Studio Code. Deployed to Azure using VS code. Output window show deployment successfully, connection and parameter file deployed but workflow is missing. I cant see workflow on portal.

FYI.. When I rolled back to v2.81.5 which I was using until last Friday, I able to deploy the workflow successfully.

Seems V4.x.x got bug.

![AbhishekVerma1982_0-1714754428150](<https://github.com/Azure/LogicAppsUX/assets/61831053/1a77474b-dc8e-457a-8d3e-7bf42e7530c7>)

### Browser 

Chrome

### Additional context 

I am using Azure Logic App Standard extension v4.13.2. Developed the stateful workflow locally using Visual Studio Code. Deployed to Azure using VS code. Output window show deployment successfully, connection and parameter file deployed but workflow is missing. I cant see workflow on portal.

FYI.. When I rolled back to v2.81.5 which I was using until last Friday, I able to deploy the workflow successfully.

Seems V4.x.x got bug.

**Comment by ccastrotrejo** [comment]
Hi @v82abhishekverma sorry for the late reply on this, could you please update to the latest vscode extension version and see if this is happening? I tried to repro and couldn't do it
