### ISSUE TITLE
New designer removes body

### ISSUE THREAD

**Issue by SonnyGillissen** [Azure/LogicAppsUX#4795]
### Describe the Bug with repro steps 

When you have a body defined in an Azure API Management action as "raw input" and you switch to the New Designer (nowadays called the 'Generally Available Designer') the body gets removed. When switching back to code view the entire "body": "@{}" part is gone. When you add it again, switch to the Designer and back to Code it's gone again.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Every browser

### Additional context 

*No response*

**Comment by preetriti1** [comment]
@SonnyGillissen - Can you please clarify where you are authoring the api management action in Legacy designer (old) or the GA designer?
Also please add some screenshots on what value you are adding and when it is being wiped away.

**Comment by SonnyGillissen** [comment]
It's the new designer, as can be seen in my original logging.
First I add the following body to the code:
![image](https://github.com/Azure/LogicAppsUX/assets/66731117/40a32cbc-4036-4e6c-b2cc-c2dcef44bdc6)

Next I switch to the new designer where the body is not showing:
![image](https://github.com/Azure/LogicAppsUX/assets/66731117/df675ba0-72b9-4405-b277-58ff9a4546d5)

When I make a change, wherever, and go back to code it's gone:
![image](https://github.com/Azure/LogicAppsUX/assets/66731117/976315ef-3c5d-49fc-8b86-81e8e6d8aeef)

**Comment by SonnyGillissen** [comment]
I did send the additonal information
