### ISSUE TITLE
HTML editor toolbar should utilize Fluent v9 components instead of custom ones

### ISSUE THREAD

**Issue by ek68794998** [Azure/LogicAppsUX#4814]
### Describe the Bug with repro steps

HTML toolbar uses many custom components for defining the toolbar buttons, icons, dropdowns, etc. We should utilize Fluent v9 components for the toolbar to get proper A11Y and bugfixes for free.

We should utilize `<Toolbar>`, `<Popover>`, etc. I started working on this in [`ek/dropdown-focus` branch](https://github.com/Azure/LogicAppsUX/compare/main...ek68794998:LogicAppsUX:ek/dropdown-focus?expand=1) but the scope got too large for me to do everything in one go.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

All browsers.

### Additional context

Additional discussion here: #4813

**Comment by ek68794998** [comment]
I can probably take this work in the coming weeks unless someone from LAUX wants to take it first.

**Comment by hartra344** [comment]
> I can probably take this work in the coming weeks unless someone from LAUX wants to take it first.

Go for it :) I don't think any LAUX members will have cycles this quarter for it.
