### ISSUE TITLE
Could not find path to extension bundle

### ISSUE THREAD

**Issue by brad302** [Azure/LogicAppsUX#4839]
### Describe the Bug with repro steps

Just trying to run my logic app in VS code.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
N/A
```

### Browser

Chrome

### Additional context

Action: azureLogicAppsStandard.getDebugSymbolDll
Error type: Error
Error Message: Could not find path to extension bundle.

Version: 4.13.2
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.83.1
Language: en

<details>
<summary>Call Stack</summary>

```
getExtensionBundleFolder main.js:438683:11
getDebugSymbolDll main.js:438653:34
main.js:49498:16main.js:49498:16
main.js:49484:71main.js:49484:71
__awaiter4 main.js:49463:14
main.js:49497:37main.js:49497:37
main.js:41788:18main.js:41788:18
main.js:43378:40main.js:43378:40
main.js:43308:71main.js:43308:71
__awaiter4 main.js:43287:14
callWithTelemetryAndErrorHandling main.js:43375:14
main.js:41774:96main.js:41774:96
main.js:41755:71main.js:41755:71
__awaiter4 main.js:41734:14
main.js:41767:117main.js:41767:117
n.h extensionHostProcess.js:125:84283
n.$executeContributedCommand extensionHostProcess.js:125:85143
i.S extensionHostProcess.js:134:10827
i.Q extensionHostProcess.js:134:10593
i.M extensionHostProcess.js:134:9683
i.L extensionHostProcess.js:134:8901
s.value extensionHostProcess.js:134:7565
c.z extensionHostProcess.js:80:1902
c.fire extensionHostProcess.js:80:2119
m.fire extensionHostProcess.js:96:14010
s.value extensionHostProcess.js:153:7902
c.z extensionHostProcess.js:80:1902
c.fire extensionHostProcess.js:80:2119
m.fire extensionHostProcess.js:96:14010
MessagePortMain.<anonymous> extensionHostProcess.js:153:6182
```

</details>

**Comment by brad302** [comment]
@ccastrotrejo any thoughts on this one?  I haven't been having much fun of late.

**Comment by brad302** [comment]
@ccastrotrejo any thoughts?  I'm having to work between two machines at present, it's driving me nuts.

**Comment by ccastrotrejo** [comment]
Hi @brad302 thanks for raising this issue and sorry for not replying earlier. It seems that the command to we use to find the extension bundle to attacth the debug symbols is throwing an error when its getting executed. There a couple fo things to do  to debug it. Could you please do the following?

- Could you please check if the following folder contains any folders (these folders are the actual extension bundles) `/Users/<username>/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows`
- Does the value in the Fun Core Tools Binary Path extension setting points to `/Users/<username>/.azurelogicapps/dependencies/FuncCoreTools/func`?
<img width="1012" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/b4206150-80af-4302-8b46-cd615c192c5c">

- Check the complete error in the Logic Apps Standard output channel. 
<img width="1824" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/881c019d-320b-4e5b-8aa5-123503df74b9">

**Comment by brad302** [comment]
@ccastrotrejo yeah, all that looks fine.  Question, can I change the port that `func.exe` is running on?  I've had a dig but can't see to find any concrete way.

**Comment by brad302** [comment]
Again, it's the local VPN.  It was just a different error to begin with.  Closing!
