### ISSUE TITLE
Issue with ise export tool in vscode

### ISSUE THREAD

**Issue by vinodkumarnallavade** [Azure/LogicAppsUX#4846]
### Describe the Bug with repro steps 

1. We have a consumption logic with When A Message Is Received In A Queue action (managed connector) and the return type of this is ServiceBusMessage.

 
2. When we export this using export tool to standard logic app the connector been converted to built-in and then the response type of the action is an Array. which is fine.

 
3. But the next steps we have considering the output would be servicebus message and the tool is not able to recognize it and it just take it as a 1 message and using it wrong it next action expressions.

 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by wsilveiranz** [comment]
@vinodkumarnallavade can you share the original logic apps definition, or a screenshot of the logic app?

**Comment by ccastrotrejo** [comment]
Closing this issue as lack of information from user. Will reopen if needed
