### ISSUE TITLE
Filter query is incorrectly serialized in v3, causing invalid expression, when function is extended

### ISSUE THREAD

**Issue by tbabatund** [Azure/LogicAppsUX#4876]
### Describe the Bug with repro steps

1. Create a simple flow using filter array as shown below
![image](https://github.com/Azure/LogicAppsUX/assets/168464523/1c6ac990-7f4d-4e85-916a-091de53f4bfa)
2. Save and go to code view. You will notice the filter query is correctly serialized and it is valid
<img width="554" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/168464523/ffdb62db-87d3-493b-b180-40fd61f739a9">
2. Now switch to advanced mode and manually extend the filter query as shown below
<img width="1008" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/168464523/cfbec6b8-c213-4b93-b493-38cdd85ae079">
4. Save and go to code view and you will notice the filter query is incorrectly serialized and it is an invalid query.  
<img width="590" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/168464523/35aeb0dd-ee3d-470c-a2bb-85809ff08d64">
5. When you repro the same thing in V1, serialization is correct and expression is valid. Notice 'item()' has no '@'.
<img width="442" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/168464523/3f00c441-1086-40f6-84a7-fa4fa1e2a950">

 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Filter_array": {
        "type": "Query",
        "inputs": {
          "from": [],
          "where": "@and(equals(@{item()},'Something'),equals(@{item()},'Somethingelse'))"
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "Recurrence": {
        "type": "Recurrence",
        "recurrence": {
          "frequency": "Week",
          "interval": 15,
          "schedule": {
            "hours": [
              "0",
              "5",
              "8"
            ],
            "minutes": [
              12,
              13
            ]
          },
          "timeZone": "Dateline Standard Time"
        }
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Browser

Chrome

**Comment by takyyon** [comment]
@preetriti1 is taking a look at this

**Comment by preetriti1** [comment]
This is not a bug, you cannot enter half expressions in editor and half in the function expression of token picker.. If you open token picker and write the complete expression from and, equals, equals and pick item from the picker it will be serialized correctly
