### ISSUE TITLE
VS Code Deployment of Custom Code Project Missing APP_KIND App Setting

### ISSUE THREAD

**Issue by StephenWThomas** [Azure/LogicAppsUX#4888]
### Describe the Bug with repro steps 

I am using VS Code with Azure Logic App Standard extension version v4.13.2.

1. Create a new workspace with Logic App and Custom Code 
2. Deploy, even the sample project, into Azure, creating a new Standard Logic App 
3. Run the Logic App workflow 
4. See the following at runtime: GetFunctionFailed - The function 'ProcessInbound' does not exist in the function app. 
5. Code works locally 
6. Seems to be missing the APP\_KIND = workflowApp application setting 
7. When this is added to the Logic App, it works as expected 

Thanks.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
N/A - VS Code deployment issue
```

### Screenshots or Videos

*No response*

### Browser

Chrome.

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hi @StephenWThomas sorry for the late reply and thanks for raising this issue. 
This issue was fixed in this PR: https://github.com/Azure/LogicAppsUX/pull/5095
It will be part of our next release cycle ETA: 7/16
