### ISSUE TITLE
Can't find the link to see run details of a child logic app run called from a parent logic app (this is available in legacy designer when viewing run history)

### ISSUE THREAD

**Issue by alex-hodges-relativity** [Azure/LogicAppsUX#4892]
### Describe the Bug with repro steps

Can't find the link to see run details of a child logic app run called from a parent logic app (this is available in legacy designer when viewing run history)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by hartra344** [comment]
Closing as a duplicate #4189
