### ISSUE TITLE
Designer not working: Error connect ECONNREFUSED 127.0.0.1:8000

### ISSUE THREAD

**Issue by MohamedEliyas-A** [Azure/LogicAppsUX#4894]
### Describe the Bug with repro steps 

1. Open the workflow file, workflow.json 
2. right click and open in designer. 
3. Getting the below error:

 connect ECONNREFUSED 127.0.0.1:8000, Source: Azure Logic App Standard 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

10:54:19 AM: Running command: "C:\Users\Eliyas.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "8028"…

 10:54:20 AM: Running command: "C:\Users\Eliyas.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "8744"…

 NodeJs Binaries: C:\Users\Eliyas.azurelogicapps\dependencies\NodeJs

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

Azure Functions Core Tools

 Core Tools Version: 4.0.5801 Commit hash: N/A +5ac2f09758b98257e728dd1b5576ce5ea9ef68ff (64-bit)

 Function Runtime Version: 4.34.1.22669

Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

Azure Functions Core Tools

 Core Tools Version: 4.0.5801 Commit hash: N/A +5ac2f09758b98257e728dd1b5576ce5ea9ef68ff (64-bit)

 Function Runtime Version: 4.34.1.22669

FuncCoreTools Binaries: C:\Users\Eliyas.azurelogicapps\dependencies\FuncCoreTools

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 [2024-05-25T08:54:33.677Z] A host error has occurred during startup operation '0ee28beb-6eca-4a46-af7b-baa6a343edaf'.

 [2024-05-25T08:54:33.678Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.

 Value cannot be null. (Parameter 'provider')

 [2024-05-25T08:54:33.740Z] Host startup operation has been canceled

 [2024-05-25T08:54:34.496Z] A host error has occurred during startup operation '6a953087-9fde-454f-bdc1-413076b62509'.

 [2024-05-25T08:54:34.498Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.

 Value cannot be null. (Parameter 'provider')

 [2024-05-25T08:54:34.581Z] Host startup operation has been canceled

 DotNetSDK Binaries: C:\Users\Eliyas.azurelogicapps\dependencies\DotNetSDK

 Local binary .NET SDK version 6.0.421

 10:55:34 AM: Azure Logic Apps Standard Runtime Dependencies validation and installation completed successfully.

 10:55:43 AM: Running command: "C:\Users\Eliyas.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "2700"…

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

Azure Functions Core Tools

 Core Tools Version: 4.0.5801 Commit hash: N/A +5ac2f09758b98257e728dd1b5576ce5ea9ef68ff (64-bit)

 Function Runtime Version: 4.34.1.22669

Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 [2024-05-25T08:55:50.854Z] A host error has occurred during startup operation '4de6aaab-5733-4ad0-9e4d-a0ec873a52ef'.

 [2024-05-25T08:55:50.855Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.

 Value cannot be null. (Parameter 'provider')

 [2024-05-25T08:55:50.921Z] Host startup operation has been canceled

 10:58:39 AM: Running command: "C:\Users\Eliyas.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "4632"…

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

Azure Functions Core Tools

 Core Tools Version: 4.0.5801 Commit hash: N/A +5ac2f09758b98257e728dd1b5576ce5ea9ef68ff (64-bit)

 Function Runtime Version: 4.34.1.22669

Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 [2024-05-25T08:58:46.445Z] A host error has occurred during startup operation '43b24af9-3696-4eed-a79a-8a1653657db7'.

 [2024-05-25T08:58:46.446Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.

 Value cannot be null. (Parameter 'provider')

 [2024-05-25T08:58:46.500Z] Host startup operation has been canceled

 10:59:20 AM: Error: connect ECONNREFUSED 127.0.0.1:8000

 11:00:43 AM: Running command: "C:\Users\Eliyas.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "880"…

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

Azure Functions Core Tools

 Core Tools Version: 4.0.5801 Commit hash: N/A +5ac2f09758b98257e728dd1b5576ce5ea9ef68ff (64-bit)

 Function Runtime Version: 4.34.1.22669

Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 11:00:48 AM: Error: connect ECONNREFUSED 127.0.0.1:8000

 [2024-05-25T09:00:52.074Z] A host error has occurred during startup operation 'c19d97eb-1184-462f-9067-943ebc3b85c2'.

 [2024-05-25T09:00:52.075Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.

 Value cannot be null. (Parameter 'provider')

 [2024-05-25T09:00:52.174Z] Host startup operation has been canceled

 11:01:25 AM: Running command: "C:\Users\Eliyas.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "8044"…

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

Azure Functions Core Tools

 Core Tools Version: 4.0.5801 Commit hash: N/A +5ac2f09758b98257e728dd1b5576ce5ea9ef68ff (64-bit)

 Function Runtime Version: 4.34.1.22669

Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

 [2024-05-25T09:01:32.539Z] A host error has occurred during startup operation '7969ecc6-b936-470f-b9dc-e65a79c67adc'.

 [2024-05-25T09:01:32.540Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.

 Value cannot be null. (Parameter 'provider')

 [2024-05-25T09:01:32.591Z] Host startup operation has been canceled

**Comment by CharlesWarwick** [comment]
I am getting the same behaviour. 
- It started about a week ago
- I only get it for one of my VS Code LAS workspaces
- I can't find/see any difference in the other Workspaces that work

I **can** get the designer to start properly and work ok, if do the following :

1. Manually start azurite 
2. run **func host** from **terminal** "C:\Users\xxxxxx\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8001 -verbose"

**Comment by ccastrotrejo** [comment]
Hi @MohamedEliyas-A and @CharlesWarwick  this issue is related to this one https://github.com/Azure/LogicAppsUX/issues/4624. I just made the fix for it,  it will be in the next release. 
The main reason is because the AzureWebJobsSecretStorageType setting in the workflow-designtime/local.setting.json it getting updated to an empty string. In the meantime, could you please update the property as below?

"AzureWebJobsSecretStorageType": "Files"

**Comment by ccastrotrejo** [comment]
Hi, do you see any more errors in the console log? 
Can you please check if indeed the executable exists in the 
 `C:\Users\XXXX\.azurelogicapps\dependencies\FuncCoreTools\func` path
