### ISSUE TITLE
New designer showing incorrect dynamic content. 

### ISSUE THREAD

**Issue by zelda001** [Azure/LogicAppsUX#4913]
### Describe the Bug with repro steps 

The new designer is displaying incorrect dynamic content. Initially, I thought I was not saving it correctly because the dynamic content kept selecting a different field (e.g., 'Requester's Name'). However, when I switched back to the Legacy Designer, it showed the correct dynamic content (e.g., 'User's Display Name').

The run history also shows the correct dynamic content, indicating that the issue lies with the new designer.

See screenshots.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

While editing in New Designer, the dynamic content is 'User's Name Displayname':

![Screenshot from 2024-05-30 11-52-54](<https://github.com/Azure/LogicAppsUX/assets/113965976/dc79c188-1bbe-48a3-bbb2-514d5b16f675>)

After saving it, the dynamic content shows 'RequestersName…'

![Screenshot from 2024-05-30 11-54-03](<https://github.com/Azure/LogicAppsUX/assets/113965976/5c2e28ce-8b42-4055-8a3b-6de38cb3541a>)

However, when switch to Legacy Designer it shows the correct dynamic content ('User's Name Displayname'). Notice the name of the action too, "Send an Email to the Creator". I have edited that in new designer, yet it still shows the default title "Send approval email".

![Screenshot from 2024-05-30 12-06-47](<https://github.com/Azure/LogicAppsUX/assets/113965976/69bb95a0-1d1e-4fd1-8bce-049d975f1de4>)

### Browser 

Firefox

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
Hi @zelda001, would you be able to provide which action you're using that the dynamic content is changing for? At first I thought it was that the dynamic content was getting the wrong one; however, given that the title also didn't change, I'm wondering if the designer is using an older copy of the Logic App

**Comment by zelda001** [comment]
Hello @Eric-B-Wu, The action is "Send an email (V2)"

**Comment by Eric-B-Wu** [comment]
> Hello @Eric-B-Wu, The action is "Send an email (V2)"
What about the action where the token is gotten from? From the icon it looks like a sharepoint action

**Comment by hartra344** [comment]
sync

**Comment by zelda001** [comment]
> > Hello @Eric-B-Wu, The action is "Send an email (V2)"
> > What about the action where the token is gotten from? From the icon it looks like a sharepoint action

Hello the sharepoint item is "Create an Item"

**Comment by Eric-B-Wu** [comment]
Hi @zelda001 there has been some changes in the token selection, and I'm no longer able to reproduce this issue. If you are still able to create this issue, please feel free to let me know and I can reopen for investigation
