### ISSUE TITLE
Cannot access logic apps (Internal Error)

### ISSUE THREAD

**Issue by PRAGNYA-NR** [Azure/LogicAppsUX#4929]
### Describe the issue 

1. Go to visual studio code 
2. Sign into Azure 
3. create new logic app 
4. Cannot access it 
5. 

![vs_code_cannot_Access_iternal_error](<https://github.com/Azure/LogicAppsUX/assets/77718736/b2dd82df-f752-4490-a911-abeb3a229e44>)

![internal_error_cannot_access_logic_App](<https://github.com/Azure/LogicAppsUX/assets/77718736/1cd448b4-f071-4c18-8c02-6c9b7c61d931>)

![image](<https://github.com/Azure/LogicAppsUX/assets/77718736/8b3a70b7-219c-489c-b55b-45a8c9740d38>) 

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

*No response*

### Browser 

vs code

### Additional context 

in Visual studio code

**Comment by ccastrotrejo** [comment]
Hi @PRAGNYA-NR thank you so much for raising this issue. There is an ongoing internal email thread about this issue and the fix has been done on the backend side. Will close this issue and will update it once the fix has been deployed.

**Comment by ccastrotrejo** [comment]
Hi @Krishna001223 this should be fixed by now. I tested it on some of our internal subscriptions and Logic Apps and it worked. Does still happens on your end? Is the `defaultHostName` property still being throwed?

**Comment by AzureDev0012** [comment]
Hi 

We are also getting same error,  but the logicapp has already few workflows deployed earlier. But not sure what happened we are unable to deploy from vs code now. 
we can’t see any error, except “Could not resolve resource” message below the resource

**Comment by ccastrotrejo** [comment]
Ok, so I have re-open so we are aware of this happening again. 
@AzureDev0012 what error do you see when you try to deploy to portal?

**Comment by ccastrotrejo** [comment]
I can see some of our internal logic apps getting the same error. I will spend some time looking at these

**Comment by AzureDev0012** [comment]
We are not getting "deploy to logic app" option when right click on the Logic App. 
Having only 3 options (Edit tags, refresh, Open in Portal)

Thanks

**Comment by ccastrotrejo** [comment]
@AzureDev0012 yes, if the `Could not resolve resource` error its on the logic app, you might not be able to deploy to it.

**Comment by AzureDev0012** [comment]
@ccastrotrejo Is this because of configuration/ Application setting values?

**Comment by ccastrotrejo** [comment]
Hi @AzureDev0012 not really. I just found the issue internally and will make a hotfix to resolve this.

**Comment by ccastrotrejo** [comment]
@AzureDev0012  @PRAGNYA-NR  A new extension version was released on Friday. This should fix that error

**Comment by wittysuyu** [comment]
Hi @ccastrotrejo, just would like to quick check if web app resource experiencing similar issue is related to the current bug?
![image](https://github.com/user-attachments/assets/b0f01a87-efb9-4c93-a4d8-7550979807b7)
![image](https://github.com/user-attachments/assets/7002541a-2f13-4be1-bb75-4fe932852e97)
![image](https://github.com/user-attachments/assets/998b766c-7ec0-449d-b540-de0432fac8a8)

If it is a separate issue, feel free to let me know and I will raise new thread.

**Comment by AzureDev0012** [comment]
> @AzureDev0012 @PRAGNYA-NR A new extension version was released on Friday. This should fix that error

Thanks @ccastrotrejo It's working Now. Able to Deploy

**Comment by ccastrotrejo** [comment]
Hi @wittysuyu might be related, however the `App Services` section its a different extension and codebase, you might need to reach out to them, or raise a Github issue on their side so they can resolve this. https://github.com/Microsoft/vscode-azureappservice
