### ISSUE TITLE
Mapping gets wiped out when choosing "Load Existing Map"

### ISSUE THREAD

**Issue by lindejon** [Azure/LogicAppsUX#4939]
### Describe the Bug with repro steps

When I choose 1. Create new data map and create a map between to schemas, then save it. 2. Choose "Load Existing data map" and choose the recently created mapping file 3. Result is that the map designer is opened empty and the work is lost (mapping file is suddenly empty).

### Version

v4.13.11

**Comment by DanielleCogs** [comment]
Hi @lindejon is it possible for you to upload your source schema, target schema and map file? That would help us to figure this out! Is it happening for every map?

**Comment by lindejon** [comment]
Hi,

this happens for every map for me and my collegues when mapping json schema to xml schema. So we devided to use the mapping tool available for visual studio 2019, where it lools like the old biztalk mapper. Sorrybthat I have no exampöe files.

Regards,
Jonas

Jonas
________________________________
