### ISSUE TITLE
After VS Code update, cannot bring up Designer

### ISSUE THREAD

**Issue by mschumacker-ncf** [Azure/LogicAppsUX#4951]
### Describe the Bug with repro steps

VS Code updated automatically (specs below).  After update, cannot open designer.

Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome, but this is VS Code

### Additional context

When clicking 'Open Designer', get message 'Starting workflow design-time API, which might take a few seconds.'

Output:
3:01:32 PM: Running command: "C:\Users\mschumacker\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "20984"...
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]

Azure Functions Core Tools
Core Tools Version:       4.0.5801 Commit hash: N/A +5ac2f09758b98257e728dd1b5576ce5ea9ef68ff (64-bit)
Function Runtime Version: 4.34.1.22669

Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
[2024-06-07T20:01:34.392Z] A host error has occurred during startup operation 'ee14a666-b821-4097-b3bf-0a10d57661f2'.
[2024-06-07T20:01:34.392Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.
Value cannot be null. (Parameter 'provider')
[2024-06-07T20:01:34.409Z] Host startup operation has been canceled
3:06:33 PM: Error: connect ECONNREFUSED 127.0.0.1:8000

connect ECONNREFUSED 127.0.0.1:8000

**Comment by ccastrotrejo** [comment]
Hi @mschumacker-ncf, thanks for raising this issue, could you please check or try adding these values to the local.settings.json inside the `workflow-designtime` folder in your project? These properties should be inside the `"Values"` property
"AzureWebJobsSecretStorageType": "Files",
 "APP_KIND": "workflowapp",

**Comment by mschumacker-ncf** [comment]
I already had the APP_KIND in the settings, but adding the AzureWebJobsSecredStorageType setting did make this start working again.  I'll mark it closed.

**Comment by ccastrotrejo** [comment]
@mschumacker-ncf I am glad that it got solved. Was there any property with an empty value? I am trying to figure out the root cause of it
