### ISSUE TITLE
App Service Pricing Plan difference

### ISSUE THREAD

**Issue by john-long2** [Azure/LogicAppsUX#4954]
### Describe the Bug with repro steps

On an existing logic app - appservice plan the prices are much lower than on a newly created one.
Existing
![image](https://github.com/Azure/LogicAppsUX/assets/104009538/0235db46-019d-4d77-95c6-d6a51bbc7a7b)
New
![image](https://github.com/Azure/LogicAppsUX/assets/104009538/b7caa683-5412-45ae-9b5a-c2c8177b71a4)

Why are these prices different.  We have budgeted the solution based on the existing prices, these new prices are a big increase almost double?

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

edge

**Comment by hartra344** [comment]
Sorry, we build the UI here and I don't have a ton of insight into the billing process or how pricing is decided. I would advise reaching out to a sales rep or opening a support ticket.
