### ISSUE TITLE
[""] disappears from condition Expression parameter

### ISSUE THREAD

**Issue by ZhouYiyun001** [Azure/LogicAppsUX#4981]
### Describe the Bug with repro steps 

Hi,Experts

Cx is facing an issue when using the New Designer view in Standard Logic Apps that the parameter in condition Expression diappear, when the [""] was entered as the parameter.

Cx wants to use [""] to mean blank as a condition rule.

We also reproduced this issue in our environment.

1. Open Logic App by designer. 
2. Add [Condition] action to workflow 
3. Open parameters tab and enter [""] in the "and" rule. 
4. Save the change and Go to Overview. 
5. Open the designer view and Find the [""] has been disappeared in Condition parameters. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

edge

### Additional context 

*No response*

**Comment by ZhouYiyun001** [comment]
![IMG_1166](https://github.com/Azure/LogicAppsUX/assets/165250510/e59ff208-52b5-401c-b510-761c0ca58dee)
![IMG_1167](https://github.com/Azure/LogicAppsUX/assets/165250510/1c990719-7400-4a62-bdf4-cebbbd14fc95)
![IMG_1168](https://github.com/Azure/LogicAppsUX/assets/165250510/d6d7e237-c9f1-4f3b-9a4a-1246b8c20b60)

**Comment by hartra344** [comment]
So if the customer is wanting a blank string, "" and an empty box is actually exactly the same and equivalent. There is no functional different but the designer doesn't show "" that aren't literal in the string when it deserializes. This is by design.
