### ISSUE TITLE
Collapse Scope Nodes on Load

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#4995]
### Describe the Bug with repro steps 

1. Have a large logic app with multiple nested scopes 
2. Open run history 
3. Note that all scopes are expanded. Users are reporting that there is a large initial load time, sometimes to a point where the page can become unresponsive 
4. This issue is not apparent in Old Designer 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

All

### Additional context 

I had a call with a customer where the new designer has become unusable, as it has a long initial load time. I noticed a lot of it was due to loading of nested actions, and especially when loading inputs/outputs of those nested actions there was a significant delay. Creating this incident to collapse scope nodes as done in old designer for larger workflows or to investigate better ways of addressing this issue

**Comment by hartra344** [comment]
I know @rllyy97  looked into doing this as well as part of hte consumption readiness work. I think there were some problems with delaying the load of the nested components in redux even if they were collapsed. I do agree though that if we could find a way to delay that or reduce that, it would be a big win.

**Comment by rllyy97** [comment]
What Travis said is correct.  However, even if we do still do the background initialization, hiding some nodes in the renderer might speed things up a bit, it's worth looking into.

**Comment by EnochZZ717** [comment]
May I know the ETA for resolving this issue? The legacy designer will be retired in September 2024, will this issue be fixed before then?

**Comment by EnochZZ717** [comment]
Hi Team, any update for this. Since the Legacy Designer will retire in 2 weeks, will the issue be resolved before then?

**Comment by rllyy97** [comment]
Hi @EnochZZ717, recently I worked on a lot of performance improvements and one of them was that nodes offscreen will not be rendered, which overlaps with the perf benefits we would get from this feature.  That change will be live with our next release, and I don't think we'll be spending resources towards this issue (for perf reasons) now that we have that alternative fix.

**Comment by EnochZZ717** [comment]
Hi @rllyy97 , thanks for the update, could you let me know when the next release is scheduled?

**Comment by Eric-B-Wu** [comment]
This we would expect to see to all regions by 8/20

**Comment by kisubedi** [comment]
@rllyy97 you had said the ETA for this to be 8/20- is that accurate or has that changed?

**Comment by rllyy97** [comment]
@kisubedi The performance improvements went like around 8/20, the collapsing of scope nodes on load was not implemented yet, and it's currently not being worked on

**Comment by kisubedi** [comment]
@rllyy97 Is it planned ? If so, can you share tentative ETA please ?
