### ISSUE TITLE
Could not resolve resource "/subscriptions/..." in vs code logic app resource

### ISSUE THREAD

**Issue by SuryaMeda** [Azure/LogicAppsUX#5008]
### Describe the Bug with repro steps 

unable to deploy the standard logic apps from visual studio code. getting Error status in Azure resources in VS code

![error ](<https://github.com/Azure/LogicAppsUX/assets/84790568/25afcef5-93ad-47dd-96cb-a46389f9fcae>)

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![error ](<https://github.com/Azure/LogicAppsUX/assets/84790568/745ff1bd-f8ed-49bc-8124-79310e9591c3>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @SuryaMeda thanks for raising this issue. This is a known issue, and the Backend team is working on fixing it.  I know the PR is already merged and we are just waiting for the fix to make it to the release cycle. 
I will close it and mark it as duplicate for this one https://github.com/Azure/LogicAppsUX/issues/4929. And I will update the issue once the deployment is fixed.
