### ISSUE TITLE
Copied Float Variable, acted like Boolean

### ISSUE THREAD

**Issue by hardEight** [Azure/LogicAppsUX#5052]
### Describe the Bug with repro steps 

1 Copied Float Variable

 2 Pasted further down

 3 Would only allow True/False values until saved and reopened.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by DanielleCogs** [comment]
Can you please add some additional context and screenshots here? I'd like to know exactly what your scenario is

**Comment by hardEight** [comment]
Danielle,
It happened a few times yesterday. I copied a float variable, pasted the action farther down the screen, Deleted the contents in the value field, and it changed to the dropdown for the boolean values. I can't seem to recreate it now though in the same application. 

I did notice something else today. When in that application I updated a handful of action names and saved it. Then I tried to recreate the float issue. Instead of saving that change (for the float) I would hit Discard. I guess it reloaded the initial code into the designed as the action names were changed back to the original ones. I exited and went back in and the action names were correct from me saving it. Seems like it refreshed to the original code when opened, instead of the latest version saved.

**Comment by DanielleCogs** [comment]
Still a bit unsure what you mean about the first part, could you attach a screen recording?

For the second, this is a known issue, and we are working on a fix! It should be released in the next few weeks.

**Comment by hardEight** [comment]
Had it happen again!
Copied a set variable action and the options were the boolean ones.
![AccessTokenString](https://github.com/user-attachments/assets/19e631a0-67f0-43e9-a009-081460a0d9c5)
![Boolean options](https://github.com/user-attachments/assets/d4014f55-6c9b-46ba-93ea-76f71ff6e57b)
