### ISSUE TITLE
Keyboard focus order is incorrectly defined on the designer 

### ISSUE THREAD

**Issue by DhruvDhiman92** [Azure/LogicAppsUX#5062]
### Describe the Bug with repro steps 

1. Create a flow with any trigger and any api action, e.g. When new email arrives. 
2. Add actions in the workflow 
3. Use keyboard navigation 
4. Observe that focus order is not as expected. Focus should move as up to down and left to right. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![tabIndex](<https://github.com/Azure/LogicAppsUX/assets/3824852/c6a215bb-e393-4513-84da-923eed609a9e>)

### Browser 

Edge, Chrome

### Additional context 

*No response*

**Comment by DanielleCogs** [comment]
related to issue 4890
