### ISSUE TITLE
The renderComponentIntoRoot component encountered an error while loading

### ISSUE THREAD

**Issue by lfbarbieri-ipl** [Azure/LogicAppsUX#5064]
### Describe the Bug with repro steps

1. Go to Logic App Standard in Azure Portal
2. Click on Workflows
3. Select a Workflow
4. Click on Designer or Previous Run

We get the following error: 

![image](https://github.com/Azure/LogicAppsUX/assets/55300966/e49b28f6-0863-4554-9241-7079074e5edb)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/55300966/772a3ee5-35e4-4da9-851a-7094e1c88155)

### Browser

Microsoft Edge

**Comment by lfbarbieri-ipl** [comment]
I am in West US 2.
Have tried multiple browsers, laptop and Azure Cloud PC, same error.

**Comment by hartra344** [comment]
You don’t need to blur out the session ID, it’s not secret information but could help us diagnose the issue. Are there any network errors or console errors appearing?

**Comment by lfbarbieri-ipl** [comment]
Wasn't sure about the Session ID... thanks for the heads up.

It's 4081358c86b140c6b14a6ef8750bf965

**Comment by lfbarbieri-ipl** [comment]
Spoke too soon, here is the debug on that:

![image](https://github.com/Azure/LogicAppsUX/assets/55300966/74c7f6f7-773e-4301-9f3f-24360759d38f)

**Comment by takyyon** [comment]
@lfbarbieri-ipl Can you check if you see the same behavior here? - https://portal.azure.com/?Microsoft_Azure_EMA=stage4

**Comment by lfbarbieri-ipl** [comment]
Yes it works with the link provided.  Still not working with standard url.

**Comment by lfbarbieri-ipl** [comment]
Just checked again, and standard url is working again.  Seems issue is resolved.  Thank you for the assistance.

**Comment by preetriti1** [comment]
@lfbarbieri-ipl - Do you mind checking the issue in https://aka.ms/emastaging ? If you are able to repro, I would like you to capture network traces and console logs from browser and send it to psamband@microsoft.com

Please do Ctrl+Alt+D and turn off client optimisations like below and then do the above.
![image](https://github.com/Azure/LogicAppsUX/assets/48265693/283fca02-5546-4a98-b98e-2628228e7d6f)

**Comment by lfbarbieri-ipl** [comment]
I have reproduced issue in requested environment, logs sent to email.

**Comment by JohnGGeo** [comment]
Using the https://portal.azure.com/?Microsoft_Azure_EMA=stage4 also corrected this error for me. Thanks.
