### ISSUE TITLE
Cannot add a recurrence trigger

### ISSUE THREAD

**Issue by chrisbeck-marquis** [Azure/LogicAppsUX#5065]
### Describe the Bug with repro steps 

Create a new Logic App

 Create a new workflow

 Click the "Add a Trigger"

 In the search box, type "recurrence", as directed by the Assistant functionality.

 Result: The only option that appears in the list is "Entigrations.io - Whenever a recurring payment is received".

 I cannot create a simple Logic App anymore.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/61799466/2a433271-5472-4c71-9478-17e2c9c739d2>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
Are you sure this is a consumption logic app and not a standard logic app. The only scenario where recurrence doesn't appear is if you're in a Standard Logic App and make it stateless. Recurrence can't track time runs without state so it's not available.

**Comment by chrisbeck-marquis** [comment]
You’re right. They’ve changed the interface to default to “standard”, which we have never used. It was very disorienting and unfriendly from Microsoft to just change that interface with no big banner.

I don’t normally use GitHub and didn’t see a link to go change the bug after I discovered this last night. Sorry for the distraction.

Just curious, why would there be no recurrence of sliding schedule just because it’s a standard workflow? Those are some of the most common trigger mechanisms.

Thanks,

CHRIS BECK | Chief Technical Officer
MARQUIS DATA | marquisdata.com
425.295.4567 | ***@***.******@***.***>
https://calendly.com/chris-beck-marquis

**Comment by hartra344** [comment]
Just to clarify we didn't change anything to Standard, it's a SKU you choose when you create the logic app. There is Consumption(which is the classic Logic App) and there is Standard(runs on dedicated App Service Resources). 

In Standard, when you create a Workflow (Standard can host multiple workflows vs Consumption which is 1 app = 1 workflow) you can choose for that workflow to be stateful or stateless. Stateless is a performance optimization for workflows that need quick latency but it gives up the ability to use triggers/actions that rely on state. recurrence trigger is a stateful trigger. 

You can use recurrence trigger in a standard Logic App if you choose stateful when choosing you workflow.

https://learn.microsoft.com/en-us/azure/logic-apps/single-tenant-overview-compare
https://learn.microsoft.com/en-us/azure/logic-apps/single-tenant-overview-compare#stateful-and-stateless-workflows
