### ISSUE TITLE
Unable to "Open Designer" in VScode

### ISSUE THREAD

**Issue by PatrickCLee** [Azure/LogicAppsUX#5072]
### Describe the issue 

I'm trying to "Open Designer in my local VScode. The rest I'll show in images.

![Snipaste_2024-07-04_08-59-35](<https://github.com/Azure/LogicAppsUX/assets/56762943/171815c8-5678-47aa-bb59-0b387a151ec6>)

![Snipaste_2024-07-04_09-00-20](<https://github.com/Azure/LogicAppsUX/assets/56762943/4312db27-ef45-44b9-9a83-2150da61f0c1>)

![Snipaste_2024-07-04_09-00-37](<https://github.com/Azure/LogicAppsUX/assets/56762943/02657b14-337f-4c3c-8466-e75fb220d2f8>)

![Snipaste_2024-07-04_09-00-45](<https://github.com/Azure/LogicAppsUX/assets/56762943/4f36835e-1fe7-4f8e-8997-0188de165b53>)

After the sign in process through browser back to VScode, stopped.

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

*No response*

### Browser 

Chrome version 126.0.6478.127

### Additional context 

Windows 10 professional edition

**Comment by ccastrotrejo** [comment]
Hi @PatrickCLee Can you try to sign in using the following command from the command palette? Please make sure is the command azure-account.login
![image](https://github.com/Azure/LogicAppsUX/assets/102700317/2d074d0c-b5fb-44f0-ab1e-0908b8f2e5ed)

**Comment by PatrickCLee** [comment]
Hi @ccastrotrejo the behavior is the same. Prompt a new tab in browser, click the account to log in, shows "You are signed in now and can close this page.", back to VScode and not logged in.

**Comment by ccastrotrejo** [comment]
Hey @PatrickCLee this seems like an odd behavior, I will spend some trying to repro it. When you come back to the vscode is there any error in the terminal or output channel? Do you get any error notification? Is there a login notification that keeps loading forever?


There is an ongoing task in which we will remove the Azure Account dependency from our extension so users will only need to sign in once from the resources azure tab

**Comment by ccastrotrejo** [comment]
Hi @PatrickCLee did you had any chance to see if there was a login notification waiting or loading for a long time?

**Comment by PatrickCLee** [comment]
oh my sorry, I checked output tab and terminal both no error message, and no other notification.
Maybe I should full uninstall and re-install?

**Comment by ccastrotrejo** [comment]
@PatrickCLee if you could do that, it would be great

**Comment by ccastrotrejo** [comment]
Hi @PatrickCLee just checking out did it worked?

**Comment by PatrickCLee** [comment]
Hello @ccastrotrejo  sorry I was assigned to other tasks, will check back to you later

**Comment by PatrickCLee** [comment]
Hello @ccastrotrejo , after uninstall and remove all the settings and install again, it works! thank you
