### ISSUE TITLE
Fields can't be JSON, "The Expression is invalid."

### ISSUE THREAD

**Issue by PatrickCLee** [Azure/LogicAppsUX#5074]
### Describe the Bug with repro steps 

1. add which ever trigger 
2. add Compose (Data Operations new) as action 
3. write JSON object in input field 
4. The expression is invalid.

![image](<https://github.com/Azure/LogicAppsUX/assets/56762943/0d909dbc-d691-4920-97e9-59691350a52e>) 

Same behavior for "Add a row into a table" (Excel Online Business), \*Body\* field.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/Azure/LogicAppsUX/assets/56762943/9ecfe161-c9c8-43df-98d0-815b4c1eb1d9](<https://github.com/Azure/LogicAppsUX/assets/56762943/9ecfe161-c9c8-43df-98d0-815b4c1eb1d9>)

### Browser 

Edge version 126.0.2592.68

### Additional context 

Video recording is on VScode, same bug shwon on Edge and Chrome

**Comment by hartra344** [comment]
This isn’t supported, you should build the JSON in the main editor. The expression editor is for building an expression function that can be condensed to a token.
