### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by srnamala** [Azure/LogicAppsUX#5078]
### Describe the Bug with repro steps 

{

 "Message": "The request is invalid.",

 "ModelState": {

 "consentInfo": [

 "No consent server information was associated with this request."

 ]

 }

 }

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
Can you give some more information about how to repro? What kind of connection are you trying to make?
