### ISSUE TITLE
Unable to edit code view after making changes in designer

### ISSUE THREAD

**Issue by imaginethosewagons** [Azure/LogicAppsUX#5086]
### Describe the Bug with repro steps 

make a change in the designer view, then attempt to edit the code view

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
Which code view are you trying to edit in? If you're switching in the menu then it's supported. Editing in the flyout code view however isn't supported it's ready only.

**Comment by imaginethosewagons** [comment]
Ah, that would solve it then.  The process I am familiar with is via the designer, but some items, such as removing escape characters to allow /n and such to be parsed would be to do most of it via the Logic App designer, then to simply click on the "Code View" button, but it sounds like that is no longer an option. The "Logic app code view" does appear to continue to work though.

![image](https://github.com/Azure/LogicAppsUX/assets/111706256/773a854c-ca31-4dfb-81c8-fd0d576da309)

**Comment by imaginethosewagons** [comment]
as per @hartra344 , the flyout is only read only and the process to edit code is to swap to the "Logic App Code View".
