### ISSUE TITLE
Logic App doesn't load using the new designer

### ISSUE THREAD

**Issue by chmancha** [Azure/LogicAppsUX#5087]
### Describe the Bug with repro steps 

This issue was found through Incident Automation, however, I can confirm I can repro the issue in the Azure Portal as well.

 Note: I have confirmed this only happens using the new designer, old designer loads the workflow correctly.

1. Go to the [impacted workflow](<https://portal.microsofticm.com/imp/v5/automation/workflows/MSI-Gateway-Availability-Prod-Main/edit?serviceId=e7315d9d-e66d-4d34-9331-882af3d7079e&branch=master&environment=Public>) 
2. Notice how when using the new designer, the workflow (Logic App) doesn't load in the designer 

I have checked all calls and data is coming from backend correctly, no failed calls and Workflow JSON looks fine. Also, no other workflows are impacted by this issue, not even in the same account, only this workflow.

In Incident Automation we're currently consuming version 4.28.0 of the new designer. Issue can be repro with the latest version from Azure Portal as well (as of 7/8/24).

The workflow is quite long but I'm unaware of any limitation to the number of actions allowed in a single workflow that could cause this not to load in the new designer. I wasn't able to paste the workflow json below since it exceeded the max number of characters allowed to file the Issue, but you can see the workflow json in the Incident Automation UI (Code View)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Tested with both Edge and Chrome

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
Hi @chmancha, will you be able to give me the repro on Azure Portal at wue@microsoft.com. I can look to investigate this issue

**Comment by chmancha** [comment]
I've sent the email, please let me know if more info is needed

**Comment by Eric-B-Wu** [comment]
followed up on the email thread for network logs/console logs

**Comment by chmancha** [comment]
Hi @Eric ***@***.***>, sorry this email went to my spam for some reason, I have attached the files you requested in the previous email for troubleshooting.
The error is in line 221 for the console logs.

Thanks for looking into this

Thanks,
Christian Mancha
***@***.***
