### ISSUE TITLE
The "Generate deployment scripts..." command is a preview feature and might be subject to change.

### ISSUE THREAD

**Issue by veronicagt094** [Azure/LogicAppsUX#5088]
### Describe the Bug with repro steps 

I am trying to generate the deployment script for the logic app since I must deploy the process in Azure Devops.

 I have tried the function deployment task and the new extension from azure devops.

 Another alternative is this one from visual studio code but after trying to generate the script I get this message

### What type of Logic App Is this happening in? 

VS Code

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![LAPP](<https://github.com/Azure/LogicAppsUX/assets/17504745/9c86485d-1d47-4e36-960c-00f4660051d9>)

### Browser 

visual studio code

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @veronicagt094, thanks for raising this issue. The information message that we show as "The "Generate deployment scripts..." it just simply works as informational content. It's to let the user know that this feature is in preview and not stable.

In the current production version, the command does nothing if it detects no connections in the workflow (it doesn't even shows an alert about this), as indicated by the absence of a connections.json file in the logic app folder. From your screenshot, it is clear that there are no connections in your folder.

We are improving this feature. The upcoming version will allow the generation of deployment scripts even without any connections.

Could you please try adding some actions in your workflow that require connections? We will be releasing the new version in about 2 weeks.
