### ISSUE TITLE
New Designer Logic App Connector Not Displaying All Logic Apps

### ISSUE THREAD

**Issue by hutch-the-dev** [Azure/LogicAppsUX#5093]
### Describe the Bug with repro steps 

1. Choose the "Choose a logic app workflow" connector action. 
2. Search for a particular logic app that exists within the same region as this workflow and other workflows that do appear in the list. 
3. Note that the logic app cannot be found. This does not occur in the Legacy Designer and the specified workflow does appear in the list. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

We have 500+ logic apps in this region as well, in case this is some sort of client query limit issue.

**Comment by rllyy97** [comment]
Hi @hutch-the-dev, thanks for reporting your issue!
I saw your context that you have 500+ logic apps in the region, this is a known issue, I'll see about trying to get this fixed for you and leave comments here about any updates.

**Comment by rllyy97** [comment]
Hi @hutch-the-dev, I took a look and we should actually be requesting them all properly in this situation; my previous comment was thinking of a different query.  From my testing it does look like we are making the same requests between old / new designer so I'm not quite sure where the issue is.  I am still investigating and will let you know when I have more information.

**Comment by rllyy97** [comment]
@hutch-the-dev Could you send me a network log of you adding the `Choose a Logic Apps Workflow` action and loading the workflows in new designer, and also let me know which apps you're expecting to see but don't see?  I'm curious on if they are being returned and filtered out for some reason, or if they are just not being returned.
You can send the log file to me directly when you have it at RileyEvans@microsoft.com.
You can find information on how to collect these logs from our docs [here](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-console-errors).
