### ISSUE TITLE
Designer very slow

### ISSUE THREAD

**Issue by pdestefanis-phrma** [Azure/LogicAppsUX#5098]
### Describe the Bug with repro steps 

Open the designer to view an existing run

 The designer is much slower than the legacy designer. Every single time.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
Can you give more information about the workflows you’re trying to open? What is slow? Any videos? This isn’t an actionable issue as it is right now.

**Comment by pdestefanis-phrma** [comment]
Hello Travis,

Agreed, I’m sorry for the lack of detail. You can close this one.
Good job on the new editor, BTW 😊

Pablo
