### ISSUE TITLE
No Scroll bars, cant using hand to scroll down

### ISSUE THREAD

**Issue by viriio** [Azure/LogicAppsUX#5112]
### Describe the Bug with repro steps 

Open a large Logic app.

 No Left hand scroll bars on open.

If you trying to click and draw to go down on left or right side of the logic app sometimes it works sometimes it doesnt. Refreshing the page fixes it when the bug happens but happens very often on larger logic apps.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge latest build

### Additional context 

New interface is unusable.

**Comment by rllyy97** [comment]
Hi @viriio, thanks for reporting your issue.
With new designer you won't see any scrollbars in the main canvas, navigation is all done by dragging the canvas around like you mentioned, scrolling to zoom, or you can use the minimap tool found in the lower lefthand corner of the canvas for faster navigation:
![image](https://github.com/user-attachments/assets/c0ce7aff-55d1-4889-8a18-4c90d8461dd8)

When you try to drag navigate and you say it doesn't work, is the whole designer editor slowing down / having issues or just the dragging?
Also if you are able could you supply us with your workflow.json?  I'd like to see if anything in particular is slowing your experience down or if it is just the size.
You can email me directly if you are worried about posting it here, my email is rileyevans@microsoft.com
Feel free to remove any sensitive info
