### ISSUE TITLE
Advanced Parameters on Actions are Wiped After Successful Save

### ISSUE THREAD

**Issue by Jprescott1994** [Azure/LogicAppsUX#5129]
### Describe the Bug with repro steps 

When I go into my logic apps for creating JIRA and click "advanced parameters" and add a description then click "save", if I close out the logic app and re-open it and select the create jira action the advanced parameters are wiped and so is the description. This is resulting in JIRAs getting logged with no information.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Tested on both Chrome and Edge.

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @jprescott1994, thanks for reporting your issue.
I tried to reproduce the behavior you're describing but I'm unable to do so.
You're saying that the jira action parameters are not saving, are parameters on other operations saving?  And are any other kinds of edits saving? (ie. renaming operations, creating / moving operations)  Feel free to do it in another workflow if you're worried about altering anything in production.  
From what you're describing, to me it just sounds like the workflow isn't actually saving for whatever reason, and is showing that it saved anyways.  Could you provide us with a console + network trace of you saving and reloading your workflow?  It will help tell us exactly what data is being saved and loaded.
You can find info on how to collect those logs from our docs [here](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-console-errors), and you can email them directly to me at rileyevans@microsoft.com

**Comment by Jprescott1994** [comment]
Fantastic, thanks!

From: Riley Evans ***@***.***>
Sent: Wednesday, July 31, 2024 1:35 PM
To: Azure/LogicAppsUX ***@***.***>
Cc: Jonah Prescott ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Azure/LogicAppsUX] Advanced Parameters on Actions are Wiped After Successful Save (Issue #5129)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Closed #5129<https://github.com/Azure/LogicAppsUX/issues/5129> as completed via #5240<https://github.com/Azure/LogicAppsUX/pull/5240>.

-

**Comment by Jprescott1994** [comment]
Hey Riley, has this been deployed to production? I just tested yesterday and still encountering this issue with advanced parameters being wiped in the new designer.

From: Riley Evans ***@***.***>
Sent: Wednesday, July 31, 2024 1:35 PM
To: Azure/LogicAppsUX ***@***.***>
Cc: Jonah Prescott ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Azure/LogicAppsUX] Advanced Parameters on Actions are Wiped After Successful Save (Issue #5129)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Closed #5129<https://github.com/Azure/LogicAppsUX/issues/5129> as completed via #5240<https://github.com/Azure/LogicAppsUX/pull/5240>.

-

**Comment by rllyy97** [comment]
Hi Jonah, the fix for this is included in our upcoming release.  We will be releasing over August 19th - 23rd depending on your region.  Sorry for the delay!

**Comment by Jprescott1994** [comment]
Awesome thank you!

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Riley Evans ***@***.***>
Sent: Tuesday, August 6, 2024 12:17:44 PM
To: Azure/LogicAppsUX ***@***.***>
Cc: Jonah Prescott ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Azure/LogicAppsUX] Advanced Parameters on Actions are Wiped After Successful Save (Issue #5129)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi Jonah, the fix for this is included in our upcoming release. We will be releasing over August 19th - 23rd depending on your region. Sorry for the delay!
