### ISSUE TITLE
Send_an_email_(V2) action fails with attachment, when added using new logic app designer

### ISSUE THREAD

**Issue by sagnik17** [Azure/LogicAppsUX#5133]
### Describe the Bug with repro steps 

When dynamic content for attachment added using new designer, the content type didn't added base64 conversion by default, as below

`"Attachments": [ { "ContentBytes": "@{body('Get_blob_content_(V2)')}", "Name": "@body('Parse_JSON')?['ExportFileName']" } ],`

While in case of old designer, it was added by default, as below

`Attachments": [ { "ContentBytes": "@{base64(body('Get_blob_content_(V2)'))}", "Name": "@body('Parse_JSON')?['ExportFileName']" } ],`

**Repro Steps**

1. Create Logic App. 
2. Use new designer to develop the workflow. 
3. Select Get\_blob\_content\_(V2) action. 
4. Select attachments and select the dynamic content from previous step. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

When dynamic content for attachment added using new designer, the content type didn't added base64 conversion by default, as below

`"Attachments": [ { "ContentBytes": "@{body('Get_blob_content_(V2)')}", "Name": "@body('Parse_JSON')?['ExportFileName']" } ],`

While in case of old designer, it was added by default, as below

`Attachments": [ { "ContentBytes": "@{base64(body('Get_blob_content_(V2)'))}", "Name": "@body('Parse_JSON')?['ExportFileName']" } ],`

### Browser 

Chrome & Edge

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
@sagnik17  thanks for reporting this issue, I'll take a look at why this is happening. This may be a regression caused because Power Automate (which is built off our designer) doesn't cast these tokens to base64 and caused a side-effect on us

**Comment by Eric-B-Wu** [comment]
Hey @sagnik17, I'm looking to reproduce this issue; however, don't seem I can. Can you let me know if you are still running into this issue, and if you are could you send a video of how to reproduce it? 
![attachment](https://github.com/user-attachments/assets/72951771-8672-4c6c-b59e-1d4019c167d4)

**Comment by sagnik17** [comment]
Yeah, looks like, it working for me now. not sure but earlier, I tried multiple times, and I was able to repro the issue.
