### ISSUE TITLE
On-premsise data gateway zip file extraction does not work - requires new folder, then fails, requires that a folder exists, then fails

### ISSUE THREAD

**Issue by cwguru** [Azure/LogicAppsUX#5135]
### Describe the Bug with repro steps 

- Any trigger 
- Copy zip file 
- Extract zip file into folder (If I mention a folder that does not exist, the error will be that the folder is not found, if I mention a folder that does exist, the error will be that the folder already exists. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @cwguru I'm confused on what you are meaning with your issue, could you clarify a little more?  You say "any trigger" then "copy zip file", what zip file are you meaning?  Is this in portal or something in vscode?
