### ISSUE TITLE
Feature Request - Provide ability to execute workflow from Overview page when a recurrence trigger is used

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#5151]
### Describe the Bug with repro steps 

We expose Run/Run with payload on portal and VS Code but in VS Code when a recurrence trigger is used, there is no way to kick off the workflow other than waiting for it to run on the interval. It would be nice to have an explicit gesture and allow the ability to kick it off similar to portal.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/4b8e9b3b-2d17-4592-a4f0-25dea930279d>)

Portal experience (Consumption

![image](<https://github.com/user-attachments/assets/ae650977-d8f4-4f68-83f1-cfba36d0553b>)

### Browser 

N/A

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @kewear thanks for raising this, this would be a great feature, for how different the vscode and portal is its not as easy as just enable the button. The extension bundle exposes one callback url for the "request" type triggers and thats the reason on why we can call it.
I will ask the BE team is there any expose api in the localhost for the extension bundle which we might be able to call and run the triggers that doesn't expose a callback url.
