### ISSUE TITLE
new logic app workflow run is showing wrong execution time on actions 

### ISSUE THREAD

**Issue by Xiaoyu-Huang** [Azure/LogicAppsUX#5167]
### Describe the Bug with repro steps 

In the workflow run review, the old designer shows 0s for action "Set variable 11", however, the new logic app designer shows 1h 1m. And new logic app designer workflow run view frequently freeze the whole UI.

Here are the screenshots for both old designer and new designer.

 Old designer:

![image](<https://github.com/user-attachments/assets/2f946858-09ec-474a-8014-e4b688c43fb0>)

New designer:

![image](<https://github.com/user-attachments/assets/0fa28df2-de07-462b-8d29-0e834d8d478b>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @Xiaoyu-Huang thanks for raising this issue, is there any chance you can share with us the an HAR file from the network tab from both experiences? 
Here is a quick guide on how to get HAR files [collecting-network-logs-in-a-har-file](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file)

You can send the files to my email at ccastrotrejo@microsoft.com

**Comment by Xiaoyu-Huang** [comment]
> Hi @Xiaoyu-Huang thanks for raising this issue, is there any chance you can share with us the an HAR file from the network tab from both experiences? Here is a quick guide on how to get HAR files [collecting-network-logs-in-a-har-file](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file)
> 
> You can send the files to my email at [ccastrotrejo@microsoft.com](mailto:ccastrotrejo@microsoft.com)

We have already jumped into a call to repro it. Let me know if there is anything else you need

**Comment by ccastrotrejo** [comment]
As discussed over the call, this issue is due to the loading of the time of the actions that are within loops, it seems that for a reason it is taking a general time instead of the time that the action individually took in the iteration of the loop. I will make a fix for it. 
On the other hand, the performance issues that we experienced will be tackled in a separate issue.
