### ISSUE TITLE
CustomHTTP: Encountered an issue with request options timing out.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5184]
### Describe the Bug with repro steps 

1\.Create a standard logic app

 2\.Create an empty stateless workflow

 3\.Add a request trigger and HTTP request action

 4\.Configure the request url to point to 

 ([https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI](<https://httptimeoutendpoint.azurewebsites.net:443/api/longresponse/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=BiCOpndJgI4xnNMW0n1MkN0NgRPgcH0NIK-h8NStZrI>))

 5\.Go to the settings tab and set Request options > request timeout to PT1S/PT24H.

**Expected:** When adding or deleting the request timeout option "PT1S/PT24H", it should be possible to add or delete all the values "PT1S/PT24H" simultaneously without having to press or reselect the Request options search bar again.

**Actual:**We **cannot** add or delete the entire "PT1S/PT24H" values simultaneously. Instead, we must deselect and reselect the Request options search bar to add or delete the full value. Currently, it only permits us to add or delete a single character at a time unless we deselect and reselect.

**Note:** The functionality seems to be operating correctly, except for the issue mentioned above.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/4704fdd3-0bdf-4e58-af62-8545c5038e9c](<https://github.com/user-attachments/assets/4704fdd3-0bdf-4e58-af62-8545c5038e9c>)

[https://github.com/user-attachments/assets/5bfb816b-5639-4316-ba35-c34ed7aed0a3](<https://github.com/user-attachments/assets/5bfb816b-5639-4316-ba35-c34ed7aed0a3>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40722.1.1

**Comment by Eric-B-Wu** [comment]
Do you have a way this is reproducible? Currently I'm on my machine trying to, but unable to

**Comment by vgouth** [comment]
I have created logic app in Central US location. Mentioned all the steps above. Functionality seems to be operating correctly. But the only issue is we have to press or reselect the request option search bar again and again to enter values. It is currently taking single character at a time.

**Comment by ccastrotrejo** [comment]
Closing this issue as this is already fixed. We will be cherry-picking to release
