### ISSUE TITLE
Service Bus_Peek-lock : Missing Split-On option

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5185]
### Describe the Bug with repro steps 

1. Create a Standard logic app 
2. Create a stateless workflow in the same app. 
3. Add a service bus "When messages are available in a queue (peek-lock)" trigger. 
4. In the trigger, enter the queue name of your first service bus queue in "Queue name". In the trigger settings disable Split On. 

**Expected:** Split-on option should be present in trigger settings.

**Actual:** Split-on option **missing** in trigger settings.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/72bc6800-374e-4345-a4c2-a8f0cd1fb10a>)

![image](<https://github.com/user-attachments/assets/5e3f777c-cae2-4eb6-87bf-f27b20b3ed55>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40722.1.1

[@Eric-B-Wu](<https://github.com/Eric-B-Wu>) Please update me whether it was intended change

**Comment by ccastrotrejo** [comment]
@vgouth This is an intended change here is the PR that introduced it https://github.com/Azure/LogicAppsUX/pull/4081
