### ISSUE TITLE
Can not edit code in new logic app UI

### ISSUE THREAD

**Issue by megamax34** [Azure/LogicAppsUX#5186]
### Describe the issue 

1. Open logic app in the new designer UI (Generally Available Designer). 
2. Click code view to edit something manually in the code. 
3. Start to edit code like in the Legacy Designer. 
4. Error pops up that says it is read only. 

This is a crucial feature to logic apps. The designer can not handle all possibilities and most times you need to go in and manually make a change. There are lots of times where I move large blocks of actions or switch out an action for another one but dont want all the downstream references to change so it has to happen in one push. With a read only code editor it will become very difficult to do simple or complex adjustments.

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

Please do not get rid of the code editor, it will cripple logic app developers.

**Comment by ccastrotrejo** [comment]
Hi @megamax34, thanks for raising this issue.  Is this a Consumption Logic Apps? 
If yes, as workaround for the meantime you can click on the `Logic app code view` button on the left panel and switch from code view and designer view. I know it's not the same experience from clicking in the upper command bar while you are in designer view, but it will take you to the code view and you can make your changes over there and then come back to designer view. Let me know if this helps
<img width="285" alt="image" src="https://github.com/user-attachments/assets/36bd1c27-6cb9-4edd-b598-9d0018419bed">

**Comment by megamax34** [comment]
Hey @ccastrotrejo I am using consumption logic apps so thank you for the tip! I can edit the code but you are right about the time wasted flipping back and forth.
Side question: will this go away in September? I see the notification bar that says it will be retired in September. Also, are there plans to integrate editable code view in the general designer?

**Comment by ccastrotrejo** [comment]
Hi @megamax34, I am glad the workaround is working for you. Yes the old (legacy) designer will become unavailable and the new one will be the only generally accessible. As for the plans for making the code view tab editable, I am not fully aware of it. I will triage it with the team and ask if there are any plans for it.

**Comment by megamax34** [comment]
@ccastrotrejo 
Sorry I may have worded it wrong but will the code view I am using right now as a work around still be available after September?

![image](https://github.com/user-attachments/assets/dd422bb8-8817-44da-b087-16d7f00f0996)

Thank you for bringing it up in your next triage. We use a lot of logic apps and the idea of having to switch back and forth like this is worrying especially with the other limitation of the new designer.

**Comment by ccastrotrejo** [comment]
Yes, that workaround experience will be available. Just the designer is the one that is going to change

**Comment by hartra344** [comment]
Closing as a duplicate, I also left a note on the other item here #3101 

As Carlos said, the legacy designer will go away in September but the code editor view will remain.
