### ISSUE TITLE
LA STD- unable to see retry history on HTTP actions in for each loop

### ISSUE THREAD

**Issue by swakMS** [Azure/LogicAppsUX#5215]
### Describe the Bug with repro steps 

Add HTTP action inside for each loop, let action fail with any 5xx or retriable error codes.

 Go to failed run and navigate to failed action, there is no retry tab at all

![image](<https://github.com/user-attachments/assets/09220dce-622a-474e-a867-3280da6473dd>)

if you open the similar HTTP action outside loop it shows the retry

 and in HAR traces also we can find the retry history, but on UI its not showing

![image](<https://github.com/user-attachments/assets/f4ef8bb3-b2f7-409b-8bb0-957cb18e3cdd>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

edge, chrome

### Additional context 

*No response*

**Comment by swakMS** [comment]
do we have any ETA or workaround for this please?

**Comment by ccastrotrejo** [comment]
Hi @swakMS thanks for raising this issue. There is not ETA or workaround yet. By the retry tab, do you mean the "submit from this action button". Could you please share a screenshot in which the retry tab can be seen?
<img width="657" alt="image" src="https://github.com/user-attachments/assets/af80fb0f-4a7f-4778-be3c-55de0a044970">

**Comment by ccastrotrejo** [comment]
Nvm, I was able to see the retry tab in code, let me check it again

**Comment by swakMS** [comment]
@ccastrotrejo  Thank you for fixing it. We still do not see the retry tab showing up
<img width="758" alt="image" src="https://github.com/user-attachments/assets/cedc4970-a2dd-466f-b156-a4e3d1dc224c">
 however it does show now in old designer [lafallback url ](https://aka.ms/lafallback).
<img width="674" alt="image" src="https://github.com/user-attachments/assets/0b1abbd6-bcb2-4dc9-97d1-dd4337303199">

**Comment by ccastrotrejo** [comment]
Hi @swakMS, this will be fixed in the next 2 weeks in portal, however please keep using the old designer as a workaround
