### ISSUE TITLE
VSC connection profiles will not handshake due to Azure outage.

### ISSUE THREAD

**Issue by mattyjbennett** [Azure/LogicAppsUX#5223]
### Describe the Bug with repro steps 

1. Go to your logic app workflow.json file in VSC. 
2. Attempt to open the designer. 

![image (2)](<https://github.com/user-attachments/assets/b4f80d9e-0a4c-4714-a188-7e33226821f9>)

You will get a blank screen and after an attempt to handshake credentials will not be read.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
Closing since this is related to a known outage and not soemthing we can fix at the moment. Please follow it on the Azure Status page.
