### ISSUE TITLE
V3 is replacing / with ~1 so Excel column with / in their name can not be operated upon

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#5245]
### Describe the Bug with repro steps 

Please find full repro details here: [https://msazure.visualstudio.com/One/\_workitems/edit/28901913](<https://msazure.visualstudio.com/One/_workitems/edit/28901913>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by preetriti1** [comment]
@kisubedi - This is not an issue in the LA Consumption portal but maybe in PA portal. The difference would be OpenApiConnection special code related to aliasing, please let your designer engineer debug this issue and confirm if it is not in aliasing specific code or in common code. Currently does not seem to be an issue in LA with swagger based operations

![image](https://github.com/user-attachments/assets/f262f351-5204-4f6d-be23-13cc4219943f)
