### ISSUE TITLE
Can not add data to Excel data where column contains / in their name

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#5256]
### Describe the Bug with repro steps 

Full repro steps here: [Bug 28938461](<https://msazure.visualstudio.com/One/_workitems/edit/28938461>): [v3] [LAUX] Can not add data to Excel data where column contains / in their name

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
I'm not able to repro this at all in Logic Apps using Azure portal. Everything works as expected. I suspect something is going on in the PA Host side to cause this.
