### ISSUE TITLE
Auto Runtime Dependencies always installs fallback version of FuncCoreTools

### ISSUE THREAD

**Issue by chris-w-dev** [Azure/LogicAppsUX#5262]
### Describe the Bug with repro steps

When *Auto Runtime Dependencies Validation And Installation* is enabled and the Azure Functions Core Tools have never been downloaded, it always installs version 4.0.5455. However, the latest version of the [Core Tools is 4.0.5907](https://github.com/Azure/azure-functions-core-tools/releases/latest)

Reproduction steps:
1.	Go to the Azure Logic Apps (Standard) extension settings and make sure *Auto Runtime Dependencies Validation And Installation* is checked
2.	Close VSCode
3.	Remove directory `%UserProfile%\.azurelogicapps\dependencies\FuncCoreTools`
4.	Start VSCode again: *Validating Runtime Dependency: Functions Runtime* should start and download version 4.0.5455 instead of the latest version
5.	Observe its progress in the output window for Azure Logic Apps (Standard)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/b0a363c6-eafc-4f26-a5b3-e5d2de9e70b0)

### Browser

N/A

### Additional context

Extension version: v4.31.7

**Comment by ccastrotrejo** [comment]
Issue is solved in above PR
