### ISSUE TITLE
logic app version 4.54 styling issue on connection panel

### ISSUE THREAD

**Issue by Xiaoyu-Huang** [Azure/LogicAppsUX#5272]
### Describe the Bug with repro steps 

I am trying to adopt 4.54.0. There are two issues I have identified.

 "@microsoft/logic-apps-designer": "4.54.0",

 "@microsoft/logic-apps-shared": "4.54.0",

1. the connection detail panel is overflow its parent container. I haven't digged deeper yet, but it is for sure something changed. as older version 4.28, we don't have this issue. before, I dig more into it, I want to make sure this is an expected change not a regression. then I could investigate the fix on our side. I believe this new version hasn't been rolled out to portal yet, so I am not able to verify on Azure portal

 
2. if click outside of the connection panel, the expected result should be close the connection panel, but it opens an empty panel with text "please select the card to see the content". this is for sure a bug.

 

![designer4 54](<https://github.com/user-attachments/assets/816df78d-599c-44fa-9070-22dee24239ae>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![designer4 54](<https://github.com/user-attachments/assets/d8ba55cb-ffce-4225-a804-018907979395>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by preetriti1** [comment]
This issue is not there anymore, please use any version from hotfix/v4.74 which is released in portal.
