### ISSUE TITLE
New designer editing step name keeps losing focus

### ISSUE THREAD

**Issue by osimaleki** [Azure/LogicAppsUX#5277]
### Describe the Bug with repro steps 

In the new designer, add a new step. Then open the step and try to edit the name. After each character, the input loses focus. So the only way to update the name is to do it one character at a time and clicking the input after each character to regain focus.

Alternatively, you can paste a longer text as a workaround.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Tried Chrome and Edge

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @osimaleki, thank you for reporting this!  I am in the process of fixing this now, we should have a hotfix rolling out by EoD
