### ISSUE TITLE
Custom Connector Dynamic Schema loses saved parameters when designer is loaded

### ISSUE THREAD

**Issue by richardcornelius-prin6** [Azure/LogicAppsUX#5286]
### Describe the Bug with repro steps 

When using a dynamic schema within a custom connector, saved parameter values are lost when the designer is reloaded, unless the parameter is marked as required.

 Saving the workflow *does* store the values, and the API call to retrieve the logic app definition retrieves the saved values successfully, as can be seen in the network logs. It appears to be the Logic Apps designer UX that is not reading the saved values.

 Works fine in the legacy designer, as it has done for the last few years.

 Repro video attached along with zipped HAR

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/14117ea4-ffc3-43fd-97ac-e4d5be264fab](<https://github.com/user-attachments/assets/14117ea4-ffc3-43fd-97ac-e4d5be264fab>)

### Browser 

Edge and Chrome

### Additional context 

zipped HAR:

[portal.azure.com.zip](<https://github.com/user-attachments/files/16502965/portal.azure.com.zip>)

**Comment by rllyy97** [comment]
Hi @richardcornelius-prin6, thanks for reporting your issue, we have a fix for this included in our next release cycle which should be fully released by next Friday, Aug 16th.  Until then feel free to keep using legacy designer and once the fix is out of you still run into issues let us know!

**Comment by richardcornelius-prin6** [comment]
That's great news, thanks Riley

**Comment by richardcornelius-prin6** [comment]
Hi again, save opening another bug for something I suspect might also be in your next release... could you please confirm if the issue of booleans not displaying a dropdown when inside an array item will also be fixed? Same context as above - custom connector dynamic schema
