### ISSUE TITLE
Action name field loses focus after each keystroke

### ISSUE THREAD

**Issue by tdutch1** [Azure/LogicAppsUX#5291]
### Describe the Bug with repro steps 

1. Open a Logic App workflow (I'm working in a standard workflow) 
2. Create or click on any action 
3. Type into the action's name field 
4. After each keystroke, the field loses the focus. It's necessary to type the name in a text editor and paste it in, but that is made difficult because the backspace nor delete key work in the field correctly. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

Tried reloading the Logic App (Standard) designer several times but the problem persists.

**Comment by hartra344** [comment]
@rllyy97 can you take a look?
