### ISSUE TITLE
Unable to load the Logic App Designers window 

### ISSUE THREAD

**Issue by Mounesh1881** [Azure/LogicAppsUX#5292]
### Describe the Bug with repro steps 

I encountered several errors while using Visual Studio Code. Here are the details:

1. Connection Error: I received the following error message: `No connection could be made because the target machine actively refused it. (127.0.0.1:10000)`. This error occurred across Azure.Core, System.Net.Http, and System.Net.Sockets.

 
2. Blob Storage Error: There was an error performing a read operation on the Blob Storage Secret Repository. The exact error message was: `There was an error performing a read operation on the Blob Storage Secret Repository`.

 
3. Undefined Property Error: I encountered an error stating `Cannot read properties of undefined (reading 'credentials2')`.

 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "kind": "Stateful"
}
```

### Screenshots or Videos

*No response*

### Browser

chrome

### Additional context

10:25:49 AM: Error: Cannot read properties of undefined (reading 'credentials2')

For detailed output, run func with --verbose flag.

 [2024-08-06T04:55:44.052Z] Failed to start a new language worker for runtime: node.

 [2024-08-06T04:55:44.053Z] System.Private.CoreLib: A task was canceled.

 [2024-08-06T04:55:44.764Z] Worker process started and initialized.

 [2024-08-06T04:55:44.010Z] Failed to start a new language worker for runtime: node.

 [2024-08-06T04:55:44.010Z] System.Private.CoreLib: A task was canceled.

 [2024-08-06T04:55:47.266Z] Host lock lease acquired by instance ID '0000000000000000000000006BC66BB1'.

 10:25:49 AM: Error: Cannot read properties of undefined (reading 'credentials2')

 Value cannot be null. (Parameter 'provider')

 Value cannot be null. (Parameter 'provider')

 10:28:21 AM: Stopping Design Time Api

 Creating temporary folder… C:\Users\MOUNES\~1.PAT\AppData\Local\Temp.azurelogicapps\FuncCoreTools

 Downloading dependency from: [https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.5907/Azure.Functions.Cli.win-x64.4.0.5907.zip](<https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.5907/Azure.Functions.Cli.win-x64.4.0.5907.zip>)

 Successfullly downloaded FuncCoreTools dependency.

 Extracting C:\Users\MOUNES\~1.PAT\AppData\Local\Temp.azurelogicapps\FuncCoreTools\FuncCoreTools.zip

 10:30:33 AM: Timeout: validateFuncCoreToolsIsLatest

 10:33:50 AM: Retrying: validateFuncCoreToolsIsLatest

 FuncCoreTools Binaries: C:\Users\Mounesh.Pattar.azurelogicapps\dependencies\FuncCoreTools

**Comment by ccastrotrejo** [comment]
Hi @Mounesh1881 thanks for raising this issue. I haven't seent the first 2 errors before
- First one might be related to a different extension since its trying to connecto to a remote computer or machine.
- Second one I don't have any idea on this
- Third one is about not being abe to retrive the credentials from your subscription. We use the credentials to be able to load the desinger with azure connectors.


Is there any popup or warning message requesting you to sign in? 
Can you try to sign in using the following command from the command palette? Please make sure is the command azure-account.login
![image](https://github.com/user-attachments/assets/f5ce3af1-ba52-4cf7-9653-536c6b1bfb57)

**Comment by Mounesh1881** [comment]
thank you so much it is working now.
