### ISSUE TITLE
Can't log in the account that doesn't belong to the current tenant in Consumption plan

### ISSUE THREAD

**Issue by ZhouYiyun001** [Azure/LogicAppsUX#5293]
### Describe the Bug with repro steps 

Hi,Experts

Cx is facing an issue when creating teams API connection in the New Designer view of Standard and consumption Logic Apps.

 In consumption plan, Cx must first select the Tenant ID in pull down list before login the account.

 Meanwhile, in Standard plan Cx does not need to select the Tenant ID before login.

 We also reproduced this issue in our environment.

Cx wants to log in the account that doesn't belong to the current tenant in Consumption plan, so Cx wonder the way to realize it.

 Also, Cx also mentions that he felt confused with the difference between plans.

■How to reproduce this problem

1. Open Logic App by designer. 
2. Add [Teams] action to workflow. 
3. Open create connection tab and cilck [sign in]. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by ZhouYiyun001** [comment]
consumption plan
![IMG_1724](https://github.com/user-attachments/assets/1c64bde5-2958-42f1-b03b-5a27d046933c)
![IMG_1725](https://github.com/user-attachments/assets/9598e8e5-c79b-4a3c-b083-7bc36fa372a2)

Standard plan
![IMG_1726](https://github.com/user-attachments/assets/c407534a-199b-4e55-af0a-9442a748a10a)

**Comment by ZhouYiyun001** [comment]
Hi, @rllyy97 
Is there any updates on this issue?

**Comment by rllyy97** [comment]
Hi @ZhouYiyun001, I do not have any updates yet, I will try to work on this as part of our next sprint.
Until this is fixed please advise customers to use legacy designer for creating any connections they are unable to create in new designer.

**Comment by ZhouYiyun001** [comment]
Hi, @rllyy97 
Thank you for the information of workarounds. You mentioned that you will look into this issue on next sprint. Could you give me an approximate time, since the legacy designer will be retired in September, our Cx may have concern on using the workaround we provide.

**Comment by ZhouYiyun001** [comment]
Hi,@rllyy97 
Thank you for fixing this issue.
but we can't confirm the fix in our environment. when will this fix release?

**Comment by Eric-B-Wu** [comment]
This fix will go out to all regions by 9/6
