### ISSUE TITLE
When editing element names in new designer, after each input the cursor disappears

### ISSUE THREAD

**Issue by MingdongL** [Azure/LogicAppsUX#5295]
### Describe the Bug with repro steps

When changing the name of an action, after every input the cursor disappears which is super annoying 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by rllyy97** [comment]
Hi @MingdongL, thanks for reporting your issue!  We are currently in the process of rolling out a hotfix for this and it should be resolved for you in a few hours
