### ISSUE TITLE
Custom Connector Dynamic Schema: booleans not displaying a dropdown when inside an array item

### ISSUE THREAD

**Issue by richardcornelius-prin6** [Azure/LogicAppsUX#5308]
### Describe the Bug with repro steps 

When a dynamic schema contains a data type of boolean within an array item, the new designer UX does not display a dropdown selection.

Additionally, if a value is then entered manually, it does not validate the value as a boolean.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Screenshot 2024-08-07 101405](<https://github.com/user-attachments/assets/9e7ba72b-27eb-4150-8afa-29dbfd2225e5>)

![Screenshot 2024-08-07 101456](<https://github.com/user-attachments/assets/1d439181-8684-417a-8699-3693c048704e>)

![Screenshot 2024-08-07 102748](<https://github.com/user-attachments/assets/adff5d5c-fb73-44ee-9daa-5265333c15fd>)

### Browser 

Any

### Additional context 

*No response*

**Comment by richardcornelius-prin6** [comment]
Hi. Do you have an update for this issue?

**Comment by Eric-B-Wu** [comment]
Would you be able to send a copy of you custom connector swagger to Wue@microsoft.com? I think currently we only support combobox editors in the array, which is built of the schema of the swagger. I can take a look to supporting dropdown editors for this scenario
