### ISSUE TITLE
AzureWebJobsStorage is removed from workflow-designtime local.settings.json

### ISSUE THREAD

**Issue by sneakyflint** [Azure/LogicAppsUX#5312]
### Describe the Bug with repro steps 

As of VSCode Extension Version v4.44.8, the local.settings.json file is updated when starting the Workflow Design Time. The `AzureWebJobsStorage` property is removed, and `"AzureWebJobsSecretStorageType": "Files"` is added. When using the Azurite storage emulator to support the workflow-designtime functions host, this prevents the workflow design time API from starting as expected.

1. Open VSCode and allow the workflow design-time to auto start, or manually start it if auto start is disabled by right clicking on a workflow.json file, and choosing "Open Designer".

![image](<https://github.com/user-attachments/assets/af3967fe-fdbd-4a05-aeef-253c00530271>) 
2. Observe the following error message appear in the Output for Azure Logic Apps (Standard): 

```
3:04:16 PM: Running command: "func host start --port 8000" with pid: "6047"...

Azure Functions Core Tools
Core Tools Version:       4.0.5907 Commit hash: N/A +807e89766a92b14fd07b9f0bc2bea1d8777ab209 (64-bit)
Function Runtime Version: 4.834.3.22875

[2024-08-07T15:04:19.308Z] A host error has occurred during startup operation '12b701b1-f4f2-45f7-9ea2-e9485c890c7b'.
[2024-08-07T15:04:19.308Z] Microsoft.WindowsAzure.Storage: Value cannot be null. (Parameter 'connectionString').
Value cannot be null. (Parameter 'provider')
[2024-08-07T15:04:24.447Z] Host startup operation has been canceled
```

3. Review the value of `workflow-designtime/local.settings.json` and observe that `AzureWebJobsStorage` has been removed and `AzureWebJobsSecretStorageType` has been added. 

Before:

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "APP_KIND": "workflowapp",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    ...
  }
}
```

After:

```
{
  "IsEncrypted": false,
  "Values": {
    "APP_KIND": "workflowapp",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsSecretStorageType": "Files"
    ...
  }
}
```

The issue is resolved by reverting to v4.44.7. PR #5298 specifically seems to have introduced this behavior.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

*No response*

### Browser

Visual Studio Code

 Version: 1.91.1

 Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729

 Date: 2024-07-09T22:07:46.768Z (4 wks ago)

 Electron: 29.4.0

 ElectronBuildId: 9728852

 Chromium: 122.0.6261.156

 Node.js: 20.9.0

 V8: 12.2.281.27-electron.0

 OS: Darwin arm64 23.5.0

### Additional context

The following VSCode settings are set for the Logic Apps Standard extension in our environment. It is also worth noting that we are using the Code Workspaces feature, and Logic Apps is being passed the `ProjectDirectoryPath` property in the workflow-designtime `local.settings.json` file.

```
"azureLogicAppsStandard.projectLanguage": "JavaScript",
                "azureLogicAppsStandard.dotnetBinaryPath": "dotnet",
                "azureLogicAppsStandard.nodeJsBinaryPath": "node",
                "azureLogicAppsStandard.funcCoreToolsBinaryPath": "func",
                "azureLogicAppsStandard.autoStartAzurite": false,
                "azureLogicAppsStandard.autoStartDesignTime": false,
                "azureLogicAppsStandard.autoRuntimeDependenciesValidationAndInstallation": false,
                "azureLogicAppsStandard.dataMapperVersion": 2,
                "azureLogicAppsStandard.parameterizeConnectionsInProjectLoad": true,
                "azureLogicAppsStandard.projectRuntime": "~4",
                "azureLogicAppsStandard.showNodeJsWarning": false,
                "azureLogicAppsStandard.showMultiCoreToolsWarning": false,
                "azureLogicAppsStandard.showProjectWarning": false,
                "azureLogicAppsStandard.showStartDesignTimeMessage": false,
                "azureLogicAppsStandard.showTargetFrameworkWarning": false,
                "azureLogicAppsStandard.showDotNetWarning": false,
                "azureLogicAppsStandard.showCoreToolsWarning": false,
```

**Comment by ccastrotrejo** [comment]
Hi @sneakyflint thanks for raising this issue and for describing the error so well. Thats right we indeed introduced that new behavior in this new version.
Having the `AzureWebJobsStorage` in the `workflow-designtime/local.settings.json` was a bug that was introduced and was preventing the designer to load. The right property is `AzureWebJobsSecretStorageType`. 


I know you posted the workflow.json and seems that there are no actions, therefore there are no connections. But this error is related to the actual resolution of a connection. Some actions can be connected to portal through a `connectionString` Does any other workflow in your logic apps project was connections? maybe there is a connectionString which value might be null.

**Comment by ccastrotrejo** [comment]
@sneakyflint Does this also happens in the root local.settings.json?

**Comment by sneakyflint** [comment]
Hi @ccastrotrejo - 
This issue does not impact the root directory's local.settings.json.

We need to use the `AzureWebJobsStorage` property as we run Azurite separately from the built-in Azurite triggered by the extension, hence `azureLogicAppsStandard.autoStartAzurite` is set to false in our configuration. Without this property present in `workflow-designtime/local.settings.json`, the functions host for workflow-designtime is not able to find and connect to the storage emulator.

Regarding the mention of `connectionString` in the error message, this error is from `Microsoft.WindowsAzure.Storage` which appears to be the upstream .NET package used by the functions host to access the storage account of the functions host. In addition the output I shared is from the workflow-designtime host specifically; it is not from the Logic Apps function host.

`AzureWebJobsSecretStorageType` [is used to control where the function host keys are stored](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobssecretstoragetype) and does not appear to be related to storage account connectivity.  

#5298 appears to have primarily been intended to ensure `"AzureWebJobsSecretStorageType": "Files"` is present as its absence does seem to prevent the workflow-designtime from starting. However it appears there was previously [logic to prompt re: overwrites to the local.settings.json file that was removed](https://github.com/Azure/LogicAppsUX/pull/5298/files#diff-c47ca582e801a41f20a122805a2e4201c63be47bf8479e46e18a5d66a6e32ddcL101-L125) in this PR, which is what is likely causing `AzureWebJobsStorage` to be dropped.


Is there a path to us being able to adjust the `AzureWebJobsStorage` property for `workflow-designtime/local.settings.json` in local development in future versions and avoid having this setting be removed during the overwrite operation?

**Comment by ccastrotrejo** [comment]
Hey @sneakyflint,
It's good that the issue is not impacting directory's local.settings.json. This is the location where the `AzureWebJobsStorage` should be set. The logic apps extension only uses azurite and the autoStartAzurite setting when we run and debug the logic app locally, not when we open the designer. The `workflow-designtime/local.settings.json` shouldn't have that setting, despite using or not the built-in azurite.


Definitely the error that is causing the `func host start` to fail is this one  `Microsoft.WindowsAzure.Storage: Value cannot be null. (Parameter 'connectionString').` Which is preventing the designer to load, however I don't know where it is coming from. 


If you downgrade the extension and remove the `AzureWebJobsStorage` property from the `workflow-designtime/local.settings.json`, does the issue still happens?

**Comment by sneakyflint** [comment]
@ccastrotrejo
Upon downgrading the extension to 4.44.7 and below, removing the `AzureWebJobsStorage` property still produces the same error:
```
Azure Functions Core Tools
Core Tools Version:       4.0.5907 Commit hash: N/A +807e89766a92b14fd07b9f0bc2bea1d8777ab209 (64-bit)
Function Runtime Version: 4.834.3.22875

[2024-08-07T21:28:45.814Z] A host error has occurred during startup operation 'e236014c-f23d-486a-a4aa-312f454ff83b'.
[2024-08-07T21:28:45.814Z] Microsoft.WindowsAzure.Storage: Value cannot be null. (Parameter 'connectionString').
Value cannot be null. (Parameter 'provider')
[2024-08-07T21:28:51.035Z] Host startup operation has been canceled
```

Removing AzureWebJobsSecretStorageType does also cause a failure which is expected:
```
Azure Functions Core Tools
Core Tools Version:       4.0.5907 Commit hash: N/A +807e89766a92b14fd07b9f0bc2bea1d8777ab209 (64-bit)
Function Runtime Version: 4.834.3.22875

[2024-08-07T21:27:39.952Z] A host error has occurred during startup operation 'a6658a48-1e7f-4800-b7b7-3c84e05c4a2c'.
[2024-08-07T21:27:39.952Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.
Value cannot be null. (Parameter 'provider')
[2024-08-07T21:27:40.006Z] Host startup operation has been canceled
9:28:43 PM: Running command: "func host start --port 8000" with pid: "1845"...
```

Our working config on 4.44.7 is: 
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "APP_KIND": "workflowapp",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "ProjectDirectoryPath": "/workspaces/{removed}/logicapps",
    "AzureWebJobsSecretStorageType": "Files"
  }
}
```

Thanks in advance for the assistance.

**Comment by ccastrotrejo** [comment]
Yes, thats right the second failure is expected. 
So far I haven't found a way to repro the issue. Do you execute azurite before opening the designer?

**Comment by sneakyflint** [comment]
Hi @ccastrotrejo - yes, we execute Azurite via a VSCode task before opening the designer.
Are you able to run devcontainers and/or GitHub Codespaces in your environment? I can send you an email with our devcontainer.json & Dockerfile along w/ a sample repo if so; that should allow you to reproduce the behavior reliably.

Let me know; thanks.

**Comment by ccastrotrejo** [comment]
Hi @sneakyflint I have done the Github Codespaces before, I don't know too much about the devcontainers but I can give it a try, the sample repo would be great to repro it. My email is ccastrotrejo@microsoft.com Thanks!!

**Comment by ccastrotrejo** [comment]
Hi @sneakyflint I finally found the issue.
- So first the `AzureWebJobsStorage` property shouldn't be inside the local.settings.json inside the `workflow-designtime` directory. The `AzureWebJobsSecretStorageType` should be there instead. The extension makes sure of that, so there is nothing you need to change there
- Your workspace configuration is all right, the settings and the azurite tasks that you have there its all right. So you don't need to change anything.
- The root cause of the issue is the following: The `host.json` inside the `workflow-desingtime` folder is missin the following sctructure: 
`"extensions": {
    "workflow": {
      "settings": {
        "Runtime.WorkflowOperationDiscoveryHostMode": "true"
      }
    }
  }` 
Please just add it at the bottom so it ends up looking like this. I don't find a reason why this was removed, but having this property will make it work it again. Also removing the `workflow-designtime` folder and restarting the vscode or trying to launch the designer will create the folder with the right properties.
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/47c75a87-4774-42e9-9ebc-324a3579757f">


One more thing that I just noticed is that in the `host.json` inside the `workflow-designtime` directory and in the root directory, in the `"Microsoft.Azure.Functions.ExtensionBundle.Workflows"` you are using the version `"[1.0.0, 1.66.20)"`. The extension bundle packs the backend code that we use to run the logic apps locally, limiting it to the 1.66.20 isn't allowing to download the latest, therefore you might not get bug fixes or features with the newer versions. I recommend you change it to `"[1.*, 2.0.0)"`, therefore you can get latest updates. FYI the lates one is `1.70.96`

**Comment by sneakyflint** [comment]
Hi @ccastrotrejo - thank you so much for your help here.
I was able to update the host.json file on my end and confirmed that the `workflow-designtime` host runs as expected with these changes. I also tried upgrading to the latest extension bundle version and it appears to be working as expected now - I was holding off due to #5221 which seems to have been resolved upstream in private repo.

I am going to go ahead and mark this as closed but feel free to re-open if needed.

Thanks again! 😄

**Comment by ccastrotrejo** [comment]
I am glad it worked @sneakyflint
