### ISSUE TITLE
[Templates][Single workflow] Create: Parameters

### ISSUE THREAD

**Issue by bonicaayala** [Azure/LogicAppsUX#5315]
### Description: 

- Templates - Single workflow 
- Create - Parameters 

### Links 

- [Designs](<https://www.figma.com/board/PUBvXenonFIm55nmuimizV/Logic-Apps-Onboarding-%28Bonica%29?node-id=440-40824&t=DyZM66yW3rJ2lHZ0-4>) 

### Screenshots 

![image](<https://github.com/user-attachments/assets/70c4903e-8ea5-43e8-a8ce-bfa95582cf75>)

**Comment by Elaina-Lee** [comment]
https://github.com/Azure/LogicAppsUX/pull/5342
