### ISSUE TITLE
SFTP - SSH crashes new designer when you try to choose 4 sub-folders in Path

### ISSUE THREAD

**Issue by tjohnson1010** [Azure/LogicAppsUX#5324]
### Describe the Bug with repro steps 

Pre-requiste have an SFTP account setup with a folder depth at least 4 deep beyond the root folder (e.g. /upload/prod/inbound/company)

2. Open an existing Logic App online under new designer 
3. Click "Add an action" 
4. Find "SFTP - SSH" 
5. Choose "Create file" 
6. Choose (or create) the SFTP Connector to use under "Change Connection" if necessary 
7. Click the folder icon in "Folder Path" 
8. Click the ">" icon 4 times. 

The new designer will freeze now. Eventually a pop-up will come up saying the page isn';t responding. Even if you click "Wait", it will just eventually just pop-up the same message again. This will cause you to lose everything you have done since your last save.

This works fine with the Legacy Designer.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/8fe1195f-a7c6-4c66-b068-287d2465ecb8>)

### Browser 

Edge Version 127.0.2651.86 (Official build) (64-bit)

### Additional context 

*No response*

**Comment by hartra344** [comment]
@Eric-B-Wu  can you take a look?

**Comment by ShingoHanai** [comment]
One customer ask us same issue occurs in file picker of Box connector.

**Comment by tjohnson1010** [comment]
This is still an issue if trying to reference more than 3 sub-directories deep.

**Comment by preetriti1** [comment]
This is fixed now, please reopen the issue if this still persists
