### ISSUE TITLE
Discrepancy between Apply-to-Each connector description and execution behavior

### ISSUE THREAD

**Issue by spanvalkar** [Azure/LogicAppsUX#5329]
### Describe the Bug with repro steps

1. Go to V3 designer.
2. Create a flow with a manual trigger, compose action, and an apply-to-each block.
3. Save the flow.
4. Run the flow with apply-to-each having a concurrency value significantly above 1 (e.g. 5-10). Note the runtime.
5. Run the flow again with apply-to-each having a concurrency control value set to off (like in the image below). Note how the runtime is significantly longer than the runtime of the flow in step 4 with the concurrency value between 5-10.

![image](https://github.com/user-attachments/assets/0d119035-0d01-4d59-8abf-520b5fba8cff)

### What type of Logic App Is this happening in?

Power Automate

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

All -> no difference between browsers found.

**Comment by hartra344** [comment]
Closing here while you follow up with backend
