### ISSUE TITLE
Parallel branch gone after logic app designer froze

### ISSUE THREAD

**Issue by BlackMercy** [Azure/LogicAppsUX#5332]
### Describe the Bug with repro steps 

My workflow had 2 parallel branch and I was developing on one branch where suddenly the designer froze (usually the mouse cursor would be a hand to allow user to move around but this time it was a normal pointer cursor) and I couldn't click on any action nor move around. The flow was recently saved before this happen. I navigated away to the Overview page of the Logic App and clicked on "Logic app designer" to continue my work just to found out that the other branch was gone.

I immediately checked Version history and found that the parallel branch was gone in the last 3 versions and I'm confident that I didn't delete or touch that branch. Proof is that I still saw that parallel branch before it froze, how can it disappear in the last 3 versions?

This is the first time I encountered this after having developed countless Logic App workflows, so I'm not sure if it can be reproduced.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge 126.0.2592.102

### Additional context 

*No response*

**Comment by hartra344** [comment]
So to be clear, you’re not able to repro this issue and aren’t sure what triggered it to happen?

**Comment by BlackMercy** [comment]
> So to be clear, you’re not able to repro this issue and aren’t sure what triggered it to happen?

That's right. I know it's difficult to investigate but thought it's still worth filing a bug.

**Comment by hartra344** [comment]
I'm going to go ahead and close it because without that info it's unactionable. If you hit it again however, feel free to reopen with whatever information you can give.
