### ISSUE TITLE
Dataverse Connector 'Perform a bound action' shows an extra parameter named $

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#5339]
### Describe the Bug with repro steps 

With the new designer, the portal shows an extra parameter as $.

![image](<https://github.com/user-attachments/assets/a0651063-d1e0-4a08-b23b-387f6a65cf0f>)

With the old designer, the portal shows the last parameter correctly (no $ parameter).

![image](<https://github.com/user-attachments/assets/5fecd5e0-e0b4-4337-a5d2-9020112b4554>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
Query in both designers is to api/flow/$metadata.json/api/data/v9.1/emails/Microsoft.Dynamics.CRM.SendEmail/inputs?api-version=2018-07-01-preview

Response in both is
{
    "schema": {
        "type": "object",
        "properties": {
            "IssueSend": {
                "type": "boolean",
                "default": false,
                "x-ms-property-name-alias": "body/IssueSend"
            },
            "TrackingToken": {
                "type": "string",
                "x-ms-property-name-alias": "body/TrackingToken"
            }
        },
        "required": [],
        "description": "Action parameters",
        "x-ms-property-name-alias": "body"
    }
}

But in the new designer we get an extra $ parameter.
```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

523293471

**Comment by preetriti1** [comment]
@xuehongg - Can you please add me to your app so I can verify on what is happening with the dynamic data. This connector has only dynamic data so with my inputs I cannot even hit this scenario to try for a repro.

**Comment by preetriti1** [comment]
The fix for this issue should be available in production in September first week
