### ISSUE TITLE
Workflow designer is not loading

### ISSUE THREAD

**Issue by saroja-sattigeri** [Azure/LogicAppsUX#5344]
### Describe the Bug with repro steps 

Go to workflow, click on designer or click on any run to see monitoring view

### What type of Logic App Is this happening in? 

Logic app standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

Getting this error while loading both workflow designer and run history design view

![image](<https://github.com/user-attachments/assets/d29aa247-192a-4d81-be12-1f5b3c512b25>)

Customer's logic app standard is in ASE which has one workflow, workflow has 153 actions as a best practice suggested to have no more than 50 actions however, customer has been able to load designer earlier for almost 2 months and all of a sudden from yesterday morning, started getting this error (runtime works fine).

Tried to capture HAR traces but designer is giving the page as below:

![image](<https://github.com/user-attachments/assets/a2372481-8571-4e52-827b-9a1dbcaa9054>)

Further, tried in old designer [https://aka.ms/lafallback](<https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2faka.ms%2flafallback&data=05%7c01%7csasatti%40microsoft.com%7cd225a387a19540fd5a7e08db5c051b23%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638204949435775580%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=P51sjV3MmO%2BtFo%2B5ogkcM4Pz%2BkvNwME46vNC67m3ohY%3D&reserved=0>) , in old designer design loads.

To reproduce at our end, collected workflow code but could not replicate the issue( i could load design in seconds)

 However, from console trace via session id was able to check in session analyzer, here's the link- [https://extensionanalyzer.azure-test.net/session?sessionId=d81536b949be4415b47db78186964984&redirected=true#experimentation](<https://extensionanalyzer.azure-test.net/session?sessionId=d81536b949be4415b47db78186964984&redirected=true#experimentation>)

![image](<https://github.com/user-attachments/assets/268d40a7-8990-405e-97a8-79aff7d1e011>)

### Browser 

[https://extensionanalyzer.azure-test.net/session?sessionId=d81536b949be4415b47db78186964984&redirected=true#experimentation](<https://extensionanalyzer.azure-test.net/session?sessionId=d81536b949be4415b47db78186964984&redirected=true#experimentation>)

### Additional context 

NA

**Comment by saroja-sattigeri** [comment]
I could not provide workflow code/json as it's exceeding given limit

**Comment by jodoroth** [comment]
We have similar issue for another customer (2408080050001229) who is seeing issue while loading the workflow designer in Standard Logic App.


<img width="647" alt="image" src="https://github.com/user-attachments/assets/4b6fac57-92ab-45ba-ac06-5c5ad6037fd1">


The workflow has 194 actions and they didnt see any issues with the designer until two days back. Runtime works without issues. With the fallback Url customer is able to load the workflow in the designer and with the new designer the workflow loads intermittent and at time it just give page unresponsive error (refer above screenshot).

Collected the workflow code from the customer and see it takes a longer time to load it in the designer view.

Please find the below session analyzer link for the session id captured while customer was loading the workflow in the designer
<img width="862" alt="image" src="https://github.com/user-attachments/assets/858db071-9df2-4c32-876c-eef15d65f8f4">




https://extensionanalyzer.azure-test.net/session?sessionId=f91bac93ff674bf0aca98b407a3ac8f2#shellerrors

**Comment by dmeeuws** [comment]
We are experiencing the same. For sure last week we did not experience issues like this.

**Comment by CharnichartDev** [comment]
I am also encountering a few issues, such as unrecognized connections, inaccessible Logic Apps, and difficulty creating a new one.

![image](https://github.com/user-attachments/assets/0f735f14-ff6b-496d-b170-b15c425c87fd)

**Comment by hartra344** [comment]
We did a rollback of our latest deployment yesterday so we can investigate what might be happening.

@CharnichartDev what you're seeing is something completely different. That's UI owned by the Azure Portal team, not by my team.

**Comment by Eric-B-Wu** [comment]
Closing this issue with the rollback and new deployment seeing the original issue as fixed
