### ISSUE TITLE
Create a Jira Issue V3 Advanced Parameters Disappearing

### ISSUE THREAD

**Issue by ethan-cher** [Azure/LogicAppsUX#5346]
### Describe the Bug with repro steps 

1. Add the create an issue step v3 action for Jira in a logic app. 
2. When adding an advanced parameter and adding anything to the description. 
3. After saving, all added stuff disappears when refreshing the page. 
4. It used to work before, but something has changed. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Brave mainly, but Microsoft Edge also has the issue.

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @ethan-cher we had a [related issue](https://github.com/Azure/LogicAppsUX/issues/5129) that we fixed a few weeks ago, can you try to reproduce your issue and let us know if it's fixed for you?
If it's not fixed I'll go ahead and take a look

**Comment by ethan-cher** [comment]
> Hi @ethan-cher we had a [related issue](https://github.com/Azure/LogicAppsUX/issues/5129) that we fixed a few weeks ago, can you try to reproduce your issue and let us know if it's fixed for you? If it's not fixed I'll go ahead and take a look

Hey, it looks like it is working fine now. Thanks for the update.
