### ISSUE TITLE
The renderComponentIntoRoot component encountered an error while loading- 'ClickSend SMS' connector action 'Send Voice message'

### ISSUE THREAD

**Issue by Sathyapriaa** [Azure/LogicAppsUX#5352]
### Describe the Bug with repro steps 

1\.Open Logic app designer - choose ClickSend SMS connector

2. Use action 'Send Voice message' 
3. Create API connection 
4. Once done, try configuring, it will throw the below error (in attachment)

![image](<https://github.com/user-attachments/assets/ed5677a5-7f65-494d-90c5-fa3943e2692c>) 

Please be noted that this issue occurs only in new designer. The old designer is working as expected.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by DanielleCogs** [comment]
I tried to reproduce but need more information. @Sathyapriaa what did you try to configure after adding the Connection? A screen recording and HAR file would be very helpful to diagnose this if I cannot reproduce it locally

**Comment by DanielleCogs** [comment]
Found the error when selecting 'Add a message'
