### ISSUE TITLE
Using consumption plan, some of our splitOn configurations are not displayed correctly

### ISSUE THREAD

**Issue by jdefesche1** [Azure/LogicAppsUX#5353]
### Describe the Bug with repro steps 

We have a group of logic apps (consumption) that use the splitOn features. This is a sample:

```
"splitOn": "@xpath(xml(triggerBody()), 'RootNode')",
                        "splitOnConfiguration": {
                            "correlation": {
                                "clientTrackingId": "@guid()"
                            }
                        }
```

When I open the editor it shows an error: Unable to initialize operation details for operation - manual. Error details - Invalid split on format in '@xpath(xml(triggerBody()), 'RootNode')'

At a first glance, the split on does work at runtime.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
"triggers": {
                        "manual": {
                            "inputs": {
                                "schema": {
                                    "properties": {
                                        "root": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "key"
                                }
                            },
                            "kind": "Http",
                            "runtimeConfiguration": {
                                "concurrency": {
                                    "maximumWaitingRuns": 100,
                                    "runs": 2
                                }
                            },
                            "type": "Request",
                            "splitOn": "@xpath(xml(triggerBody()), 'RootNode')",
                            "splitOnConfiguration": {
                                "correlation": {
                                    "clientTrackingId": "@guid()"
                                }
                            }
                        }
                    }
```

### Screenshots or Videos

![Screenshot 2024-08-12 163852](<https://github.com/user-attachments/assets/7154bcd6-8c58-4b18-a1db-d5f00d873992>)

### Browser

FireFox

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hey @jdefesche1 thanks for raising this issue. I have a question and a couple of suggestions regarding this one.
- Does this issue also happens in Legacy designer?

I tried to repro your issue and indeed I saw the error. After a little bit of research on why this was happening, I realized that your splitOn expression might wrong. Here are the things that I noticed:

- Your splitOn expression is as following : `"@xpath(xml(triggerBody()), 'RootNode')"`. Usually, the splitOn logic comes from the triggerBody or triggerOuputs. Having a function at the beginning might be the reason this is breaking. A more suitable expression might be the following `"@triggerBody()?['RootNode']",`   This will get the value from the RootNode property from the body of the trigger.
- Besides this you might need to update your trigger inputs schema as following, this will ensure that your triggerBody has the `RootNode` property : `{
    "schema": {
      "properties": {
        "RootNode": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    }
  }`

Please let me know if this works

**Comment by jdefesche1** [comment]
@ccastrotrejo Thanks for your response. The legacy designer has no issues. Will discuss with our team what we can do about the statement.

**Comment by ccastrotrejo** [comment]
@jdefesche1 Thats sounds good, let me know if that is what you intended to do with the splitOn option. Also, FYI the legacy designer will be fully deprecated in the next 2 months, so let's not completely rely on it

**Comment by jdefesche1** [comment]
@ccastrotrejo Talked with the team and it's difficult to find another way as we use encoded xml within a json with a body and context token. What did you use to reproduce the issue? Is it a fact that any function in the splitOn breaks the designer?

**Comment by ccastrotrejo** [comment]
@jdefesche1 Sorry I might be wrong with my first answers. I am taking a further look at this and will come up with some findings about what is going on and if we should support this type of functions in splitOn in new designer
