### ISSUE TITLE
Cannot show all API connections for SQL server connector on Generally Available Designer

### ISSUE THREAD

**Issue by EnochZZ717** [Azure/LogicAppsUX#5361]
### Describe the Bug with repro steps 

cx created more than 100 API connections for the SQL Server connector, but the Generally Available Designer only shows around 29 API connections. However, the Legacy Designer displays all API connections. I have reproduced this issue on my end as well.

 On Generally Available Designer, the sql-8 connection is not in the list

![image](<https://github.com/user-attachments/assets/1ae3b2f7-b92d-4d4b-a3aa-4da3054d03b9>)

but we can see it on Legacy designer

![image](<https://github.com/user-attachments/assets/15279efa-3be3-49a4-9789-2d99e295a001>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
@rllyy97 can you take a look? Maybe a paging issue?

**Comment by EnochZZ717** [comment]
Hi Team, any update for this? cx needs confirmation that the issue to be fixed before the retirement of legacy designer in September 2024.

**Comment by EnochZZ717** [comment]
Hi @rllyy97, any updates for this?

**Comment by rllyy97** [comment]
Hi @EnochZZ717 I'm planning on taking a look at this this week, we will have this in before the retirement of legacy designer

**Comment by EnochZZ717** [comment]
Hi @rllyy97, could you please let me know when this fix will be deployed to Australia East?

**Comment by rllyy97** [comment]
@EnochZZ717 This should be live in our next release, ETA for all regions is September 20th
