### ISSUE TITLE
Logic App GA Designer Microsoft Form DynamicInput not available issue

### ISSUE THREAD

**Issue by dengyanbo** [Azure/LogicAppsUX#5362]
### Describe the Bug with repro steps 

We cannot reproduce this issue in our environment. But we can always reproduce the issue in customer environment (customer workflow, api connection and forms).

1. In Logic App GA designer, we can create a Microsoft Form trigger and action, but the drop down list of forms or questions are empty. 
2. We can manually put form id into the drop down list and its runtime works fine. However, we cannot find any dynamic content from the action in coming steps. 
3. Once we switch back to legacy designer, the issue is mitigated - everything works fine then. 
4. We collected HAR for both legacy designer and GA designer. We found 500 error returned by Form API in GA designer. HARs can be found in IcM 526510361 or internal email thread (For user privacy purpose). 
5. The error in HAR shows in the following screenshots

![image](<https://github.com/user-attachments/assets/dbc49f37-d363-4f18-afec-ed09b6a05f81>) 
6. We can also find the error in APIM log, see IcM 526510361 for details. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome and Microsoft Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
@preetriti1 can you take a look? Looks like there is an ICM attached, might be an issue on the backend
