### ISSUE TITLE
GA Designer crashing on Consumption LA, on Blob Storage actions/triggers, when there's no containers

### ISSUE THREAD

**Issue by IvorYPT** [Azure/LogicAppsUX#5365]
### Describe the Bug with repro steps 

1. Create LA consumption 
2. Open designer 
3. Add Blob trigger 
4. Select container 

If a container exists in the Storage or Legacy designer is used, there is no error.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "When_a_blob_is_added_or_modified_(properties_only)_(V2)": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "name": "@parameters('$connections')['azureblob-1']['connectionId']"
            }
          },
          "method": "get",
          "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}/triggers/batch/onupdatedfile",
          "queries": {
            "folderId": "",
            "maxFileCount": 10,
            "checkBothCreatedAndModifiedDateTime": false
          }
        },
        "recurrence": {
          "interval": 3,
          "frequency": "Minute"
        },
        "splitOn": "@triggerBody()"
      }
    },
    "actions": {
      "Create_blob_(V2)": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "name": "@parameters('$connections')['azureblob-1']['connectionId']"
            }
          },
          "method": "post",
          "headers": {
            "ReadFileMetadataFromServer": true
          },
          "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('AccountNameFromSettings'))}/files",
          "queries": {
            "folderPath": "/test",
            "name": "karts2.zip",
            "queryParametersSingleEncoded": true
          }
        },
        "runAfter": {},
        "runtimeConfiguration": {
          "contentTransfer": {
            "transferMode": "Chunked"
          }
        }
      }
    },
    "outputs": {},
    "parameters": {
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {
        "azureblob-1": {
          "id": "/subscriptions/30e3e2d6-ae2a-417f-9e09-261198f8c8f6/providers/Microsoft.Web/locations/westeurope/managedApis/azureblob",
          "connectionId": "/subscriptions/30e3e2d6-ae2a-417f-9e09-261198f8c8f6/resourceGroups/HackathonDataverse_group/providers/Microsoft.Web/connections/azureblob-1",
          "connectionName": "azureblob-1"
        }
      }
    }
  }
}
```

### Screenshots or Videos

![image](<https://github.com/user-attachments/assets/c720a865-92bf-41f7-865d-793c5c5d1d48>)

![image](<https://github.com/user-attachments/assets/39682e2a-6b30-438b-a694-38823d812cd1>)

### Browser

Edge

### Additional context

{ "shellProps": { "sessionId": "85355b33d7434b328d7ca77918c88f91", "extName": "Microsoft\_Azure\_EMA", "contentName": "DesignerEditorConsumption.ReactView" }, "error": { "message": "The renderComponentIntoRoot component encountered an error while loading.", "metadata": { "area": "renderComponentIntoRoot" }, "error": { "data": { "message": "The renderComponentIntoRoot component encountered an error while loading.", "metadata": { "area": "renderComponentIntoRoot" }, "capturedErrors": [ { "message": "Error caught in error boundary", "metadata": { "area": "renderComponentIntoRoot", "error": { "stack": "TypeError: e.filter is not a function\n at Ace ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9979284)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9979284%29%5cn>) at Dce ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9981741)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9981741%29%5cn>) at fn ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:43441)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:43441%29%5cn>) at Vn ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:50260)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:50260%29%5cn>) at lc ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:112118)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:112118%29%5cn>) at Ar ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:77654)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:77654%29%5cn>) at Dr ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:77582)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:77582%29%5cn>) at Lr ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:77445)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:77445%29%5cn>) at Tr ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:74440)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:74440%29%5cn>) at [https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:30184\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:30184%5cn>) at unstable\_runWithPriority ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:50:7430)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:50:7430%29%5cn>) at Et ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:29961)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:29961%29%5cn>) at Ot ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:30129)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:30129%29%5cn>) at Pt ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:30064)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:30064%29%5cn>) at Nr ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:74761)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:60:74761%29%5cn>) at Object.notify ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:63:11891)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:63:11891%29%5cn>) at t.notifyNestedSubs ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:63:11461)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:63:11461%29%5cn>) at t.handleChangeWrapper ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:63:11529)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:63:11529%29%5cn>) at h ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:62:6060)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:62:6060%29%5cn>) at [https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10079169\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10079169%5cn>) at bOe (https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10508298)", "message": "e.filter is not a function", "name": "TypeError" }, "errorInfo": { "componentStack": "\n at Dce ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9979868)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9979868%29%5cn>) at Rde ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10028983)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10028983%29%5cn>) at div\n at Pde ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10028524)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10028524%29%5cn>) at div\n at div\n at div\n at xBe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10710297)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10710297%29%5cn>) at SBe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10708906)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10708906%29%5cn>) at IBe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10720582)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10720582%29%5cn>) at div\n at MBe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10718409)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10718409%29%5cn>) at div\n at div\n at \_ue ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9912942)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9912942%29%5cn>) at div\n at div\n at div\n at div\n at [https://ms.portal.azure.com/Content/Dynamic/VtLXfPwcKyBm.js:36:503\n](<https://ms.portal.azure.com/Content/Dynamic/VtLXfPwcKyBm.js:36:503%5cn>) at div\n at div\n at [https://ms.portal.azure.com/Content/Dynamic/VtLXfPwcKyBm.js:21:576\n](<https://ms.portal.azure.com/Content/Dynamic/VtLXfPwcKyBm.js:21:576%5cn>) at div\n at t.FocusRectsProvider ([https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:267:275)\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:267:275%29%5cn>) at [https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:146:481\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:146:481%5cn>) at [https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:318:438\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:318:438%5cn>) at t.FocusRectsProvider ([https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:267:275)\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:267:275%29%5cn>) at span\n at [https://ms.portal.azure.com/Content/Dynamic/VtLXfPwcKyBm.js:13:511\n](<https://ms.portal.azure.com/Content/Dynamic/VtLXfPwcKyBm.js:13:511%5cn>) at [https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:318:438\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:318:438%5cn>) at t ([https://ms.portal.azure.com/Content/Dynamic/VtLXfPwcKyBm.js:171:765)\n](<https://ms.portal.azure.com/Content/Dynamic/VtLXfPwcKyBm.js:171:765%29%5cn>) at [https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:318:438\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:318:438%5cn>) at zue ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9919643)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9919643%29%5cn>) at HBe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10732278)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10732278%29%5cn>) at hWe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10750733)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10750733%29%5cn>) at MX ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9209206)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9209206%29%5cn>) at div\n at [https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9209592\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9209592%5cn>) at AX ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9209042)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:9209042%29%5cn>) at div\n at [https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10320832\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10320832%5cn>) at Bxe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10321399)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10321399%29%5cn>) at bWe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10754117)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10754117%29%5cn>) at div\n at eze ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10561537)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10561537%29%5cn>) at tze ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10561968)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10561968%29%5cn>) at Fs ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:7782807)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:7782807%29%5cn>) at t ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:5766830)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:5766830%29%5cn>) at Bs ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:7782934)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:7782934%29%5cn>) at div\n at div\n at yy ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:8433103)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:8433103%29%5cn>) at [https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10123279\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10123279%5cn>) at div\n at t.FocusRectsProvider ([https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:267:275)\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:267:275%29%5cn>) at [https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:175:441\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:175:441%5cn>) at KRe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10560099)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10560099%29%5cn>) at R ([https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:63:12498)\n](<https://reactblade-ms.portal.azure.net//Content/Dynamic/wvqRmzcFOmrg.js:63:12498%29%5cn>) at GRe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10560243)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10560243%29%5cn>) at div\n at t ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:5325712)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:5325712%29%5cn>) at div\n at vKe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10871542)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10871542%29%5cn>) at ne ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:5701227)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:5701227%29%5cn>) at Qxe ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10345381)\n](<https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/xrr9RhtUXGkz.js:3:10345381%29%5cn>) at \_Ke\n at l ([https://ms.portal.azure.com/Content/Dynamic/Wtt7lXD-Iz1I.js:15:1470)\n](<https://ms.portal.azure.com/Content/Dynamic/Wtt7lXD-Iz1I.js:15:1470%29%5cn>) at \_Ke\n at div\n at div\n at div\n at t.FocusRectsProvider ([https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:267:275)\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:267:275%29%5cn>) at [https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:146:481\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:146:481%5cn>) at [https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:318:438\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:318:438%5cn>) at t ([https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:287:434)\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:287:434%29%5cn>) at div\n at t.FocusRectsProvider ([https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:267:275)\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:267:275%29%5cn>) at [https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:175:441\n](<https://ms.portal.azure.com/Content/Dynamic/AdHUtpwRFMI-.js:175:441%5cn>) at r.ThemedFabric (https://ms.portal.azure.com/Content/Dynamic/V7dAZOOulK9Z.js:8:1576)" } } } ] } }, "code": null }}

**Comment by PedroAlmeidaMS** [comment]
@preetriti1 issue is still not fixed.

Consumption and Standard designers still crashing

**Comment by preetriti1** [comment]
Deployment ETA is 8/22
