### ISSUE TITLE
Revoke-AADSignInSessions-incident -> Start with Microsoft Sentinel Alert and not Incident

### ISSUE THREAD

**Issue by AxentysKevinKeurvels** [Azure/LogicAppsUX#5366]
### Describe the Bug with repro steps 

1. Create the template playbook named Revoke-AADSignInSessions-incident 
2. Open the designer 
3. See the first action is Microsoft Sentinel Alert and not Incident 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

- Browser : Chrome 

### Additional context 

*No response*

**Comment by hartra344** [comment]
This is an experience owned by the Sentinel team, not the Logic Apps team. I would open a ticket with them to see what's going on.
