### ISSUE TITLE
Reset-AADPassword-IncidentTrigger - HTTP request forbidden

### ISSUE THREAD

**Issue by AxentysKevinKeurvels** [Azure/LogicAppsUX#5367]
### Describe the Bug with repro steps 

1. Create the template playbook named Reset-AADPassword-IncidentTrigger 
2. Go in Identity 
3. Give it the rights 
4. Test : forbidden 
5. Create a app registrations 
6. Go to API permission 
7. Give it the rights : 

 User.ReadWrite.All

 User.ManageIdentities.All

 Directory.ReadWrite.All 
8. Change in the playbook by indicating the value of the app 
9. Test : forbidden 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

- Browser : Chrome 

### Additional context 

*No response*

**Comment by hartra344** [comment]
This is an experience owned by the Sentinel team, not the Logic Apps team. I would open a ticket with them to see what's going on.
