### ISSUE TITLE
Variables: Scrolling up and down not working to view all the actions under variable action.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5384]
### Describe the Bug with repro steps 

1\.Create a logic app.

2. Add stateless workflow. 
3. Add a http request trigger. 
4. Add initialize variable action. 
5. Add Append to Array variable actions. 
6. Scroll down is not working with 100% screen resolution. 

**Expected:** Scroll up and down should work to show all the actions fields under variable action with 100% resolution.

**Actual:** Scroll up and down is **not working** to show all the actions fields under variable action. We have to make change in screen resolution from 100% to 90% to view the actions.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/53d63ac4-7ac1-4bf4-9bd3-7bf52f4a7540>)

 [

[https://github.com/user-attachments/assets/01ec8426-5e07-423a-b31e-36f02b989c97](<https://github.com/user-attachments/assets/01ec8426-5e07-423a-b31e-36f02b989c97>)

\]\(url)

### Browser 

Edge

### Additional context 

**Version:** 2\.40813.1.2

**Comment by vgouth** [comment]
**Screen Resolution Issue** 
Issue repro while creating the connections to Azure Function App, Workflow parameters, Managed API connections, Service bus connections etc. While it doesn't impact functionality, it requires minimizing and maximizing the screen to proceed.

**Comment by rllyy97** [comment]
Offending PR: https://github.com/Azure/LogicAppsUX/pull/5259
