### ISSUE TITLE
Text for Log Stream should be in camel case in designer

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5387]
### Describe the Bug with repro steps 

1. Create a logic app. 
2. Create a stateful/stateless workflow and open the desigenr 
3. Text for Code View should be in camel case . 

**Actual:** Text for Code View is not in camel case

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/b22b8c00-051a-4a49-96f4-ca51baef4ca5>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40813.1.2

**Comment by hartra344** [comment]
No it shouldn't, the actual bug here is that "Stream" in "Log Stream" should not be upper case

**Comment by vgouth** [comment]
Thank you for the clarification travis @hartra344

**Comment by vgouth** [comment]
Issue repro in the latest request. Log Stream should not be in Camel Case.

**Version :** 2.40826.1.3

![image](https://github.com/user-attachments/assets/7e02e63a-8179-41c3-bd93-95fe43943bc0)

**Comment by vgouth** [comment]
Issue repro in the latest request. Log Stream, Run History, Access Keys,Cancel Run should not be in Camel Case.

Version: 0.2022.1.764

**Comment by ccastrotrejo** [comment]
This will be fixed in upcoming releases
