### ISSUE TITLE
Existing file system connections are not displayed

### ISSUE THREAD

**Issue by fanweiyan-coder** [Azure/LogicAppsUX#5398]
### Describe the issue 

1. go to a standard logic app 
2. click the designer under the stateful workflow 
3. add an action, and select create file of the file system (on promise) 
4. The connection that I created before is not displayed, and I need to enter the information again 
5. After about five to ten minutes, the previous connection can be selected

 Note：He had established more than 20 file system connections. 

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

The first image is the problem status page. The second image is the normal page after waiting five to 10 minutes

![1723685942788](<https://github.com/user-attachments/assets/3ea1bb49-ab06-4869-8505-287be4e42988>)

![1723686094005](<https://github.com/user-attachments/assets/c7fdefbd-d38f-45d8-a2fd-94531972a3d2>)

### Browser 

Edge，Chrome

### Additional context 

Not sure if it is the same problem, the file system connector（on promise） sometimes shows an error as shown below, but we did not click many times

![1723686289992](<https://github.com/user-attachments/assets/86ed0fc1-aab2-4238-bb71-353bdc8516f4>)

**Comment by hartra344** [comment]
I'm not sure this is a UX bug, could be a API bug. Can you please open an ICM ticket on the Logic Apps team to investigate? Please include HAR traces and console log errors where appropriate.

**Comment by fanweiyan-coder** [comment]
[portal.azure.cn2.har.zip](https://github.com/user-attachments/files/16882695/portal.azure.cn2.har.zip)
Hi   Team，we created a icm ticket  before，but  received  as follows ：
"in Logic App, when we try to retrieve the API connection of a specific connector, it is an API call send to ARM API ([Resource Groups - List - REST API (Azure Resource Management) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/resources/resource-groups/list?view=rest-resources-2021-04-01)).

 
By default, it has a limitation that how many resources can be returned in a single call if it cannot be retrieved for the first time, it will provide "nextLink" in http response for the next integration which I saw in cx's HAR trace. 

Meanwhile, as per my understanding, the filter is applied after we retrieve the list, so it possible that we have an empty list but with "nextLink", so this issue mostly due to too many API connections in cx's resource group, but I believe we should consider this situation and fix in front end."

I  attached the har package, could you have a look? Thanks.

**Comment by hartra344** [comment]
Should be fixed in #5595
