### ISSUE TITLE
Minimap is getting cut off at hte bottom

### ISSUE THREAD

**Issue by hartra344** [Azure/LogicAppsUX#5403]
![image](https://github.com/user-attachments/assets/6e916476-9870-4c9a-adf2-3a8abec65aa6)

**Comment by rllyy97** [comment]
This is fixed in main with the panel height pr reversion from yesterday

![image](https://github.com/user-attachments/assets/1be57eff-dc2f-4dc1-a0bc-009ec29f1576)
