### ISSUE TITLE
Update local .NET SDK notification keeps appearing after updating .NET SDK

### ISSUE THREAD

**Issue by chris-w-dev** [Azure/LogicAppsUX#5416]
### Describe the Bug with repro steps 

The update local .NET SDK notification keeps appearing after updating an existing .NET SDK dependency to the latest .NET SDK version using the Auto Dependencies Installation.

 This only occurs when multiple SDK versions exist for the same major .NET version in folder `DotNetSDK`.

Notification text:

`Update your local .NET SDK version (6.0.424) to the latest version (6.0.425) for the best experience.`

Installed .NET SDKs:

```
6.0.424 [C:\Users\<username>\.azurelogicapps\dependencies\DotNetSDK\sdk]
6.0.425 [C:\Users\<username>\.azurelogicapps\dependencies\DotNetSDK\sdk]
8.0.303 [C:\Users\<username>\.azurelogicapps\dependencies\DotNetSDK\sdk]
8.0.401 [C:\Users\<username>\.azurelogicapps\dependencies\DotNetSDK\sdk]
```

**Reproduction steps:**

1. Go to the Logic App Standard extension settings and make sure *Auto Runtime Dependencies Validation And Installation* is checked 
2. Make sure an older version of the .NET 6 (or 8) SDK is installed in `C:\Users&amp;lt;username&amp;gt;\.azurelogicapps\dependencies\DotNetSDK\sdk` 
3. Open a new VSCode window, the Validating Runtime Dependency: .NET SDK should start, and display notification `Update your local .NET SDK version (6.0.&lt;old version&gt;) to the latest version (6.0.&lt;new version&gt;) for the best experience.` 
4. Click *Update* in the notification and wait for the .NET SDK update to be installed. 
5. Close VSCode 
6. Open a new VSCode window. Validating Runtime Dependency: .NET SDK should start again. 

**Actual result:**

 Notification `Update your local .NET SDK version (6.0.&lt;old version&gt;) to the latest version (6.0.&lt;new version&gt;) for the best experience.` is shown again, even though it was successfully installed.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

N/A

### Additional context 

Extension version: v4.44.9

**Comment by rmartin-msft** [comment]
Has this been completed? The bug still occurs after updating the VSCode Logic App (Standard) Extension to v4.57.7

**Comment by chris-w-dev** [comment]
@rmartin-msft in [v4.66.0](https://github.com/Azure/LogicAppsUX/releases/tag/v4.66.0) or later. We just have to wait a little bit more I guess.
