### ISSUE TITLE
Replication task: Some Actions are missing in service bus queue action.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5419]
### Describe the Bug with repro steps 

1\.Create a stateless workflow in the logic app. 

 2\.Add a service bus "When messages are available in a queue (peek-lock)" trigger. 

 3\.In the trigger, enter the queue name of your first service bus queue in "Queue name".

4. Add a For each action and select Messages from the dynamic content as its input parameter.

 5\.Within the for each loop add the action "Dead-letter the message/Abandon the message/Complete the message" from service bus. In the Message ID field select "Message ID" from the dynamic content popup. 
5. Save the workflow. 

**Expected:** Should able to see Dead-letter the message/Abandon the message/Complete the message actions in service bus action.

**Actual:** Not able to see Dead-letter the message/Abandon the message/Complete the message actions in service bus action.

**Note:** If the actions are renamed to what we have seen in below screenshot is there any change in functionality of those actions.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/213d44f7-e979-41f6-b8b5-8d5be22fa6da>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40813.1.3

**Comment by preetriti1** [comment]
@vgouth Not clear what you did after save.. did you open this workflow again and then added an action ad did not observe these operations in the service bus connector or loading the workflow actions failed.
Or it failed in step #5 in your steps?

**Comment by vgouth** [comment]
@preetriti1 
The process failed at step 5. Instead of finding the options to **Dead-letter the message/Abandon the message/Complete the message**, I noticed the action names have been changed. If these changes were intentional, could you please explain the new actions' expected behavior and outcomes? Feel free to contact me if you need further clarification on the test case.

**Comment by preetriti1** [comment]
@vgouth These are just name changes and they are now clearly indicating it is for a queue, so you might find extra inputs in the operatrion like to select a queue.. no change from teh test case and expected behaviors and outcomes should be same from runtime point of view.
