### ISSUE TITLE
Monitoring View: Dark and light theme messed up

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5427]
### Describe the Bug with repro steps 

1. Create a project in VS code. 
2. Add a workflow to your local project 
3. Open the workflow.json file in designer and author a new workflow 
4. Add any triggers and actions of your own choice. 
5. Press F5 to build and run your project

 6\.Open overview page. Right + Click on workflow.json file and "Overview".

 7\.Copy call back URL from the overview page

 8\.Send the http request POST via Postman and wait for the response

 9\.Refresh the overview page and your should see your local run

 10\.Open the monitoring view for your run from the overview page 
6. Verify the run details and action inputs and output 

**Expected:** Dark and light theme should not be messed up

**Actual:** Dark and light theme messed up

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/fb95ba28-55f8-489a-8ad0-e1d1854dc327>)

### Browser 

VS Code

### Additional context 

VSIX Verison : 4.57.3

**Comment by ccastrotrejo** [comment]
This issue gets fixed with the following PR: https://github.com/Azure/LogicAppsUX/pull/5397
We are cherry-picking it for the release
