### ISSUE TITLE
Unable to add dynamic content when entering in an expression.

### ISSUE THREAD

**Issue by mberry-vb** [Azure/LogicAppsUX#5435]
### Describe the Bug with repro steps

1. Add an action. ex: "sharepoint get file content using path"
2. In any parameter, click 'insert expression' (fx)
3. click 'dynamic content'
4. try clicking any option from a previous step, value does not get entered into the expression box.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Which operating system are you using?

Windows

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/d4ced3dc-dad4-4d60-992e-0838f469b5a1)

### Browser

Firefox

### Additional context

Applies to all parameters in every block I have tried.

**Comment by hartra344** [comment]
We'll be hot fixing this today. We got a fix in for this before the release but somehow it didn't make it into the release branch. Thank you for reporting this!
