### ISSUE TITLE
Logic Apps creates unnecessary For Next loops

### ISSUE THREAD

**Issue by MWG-Musco-Olive** [Azure/LogicAppsUX#5443]
### Describe the Bug with repro steps 

When I am trying to use data from a previous step where I retrieved records the Logic app (correctly) auto creates a For Next box , but if there are multiple pieces of data from the previous step the new (terrible designer) creates an additional level of For Next each time I use another field. For instance if I read a SQL table that has data for a GL journal line , and then I try to Create record in D365 for the Journal line, when I put the currencly from the SQL data on the currency field of the D365 create record box, it creates a For Next loop, then when I add the next field (company for instance) it puts it inside another For next loop and so on.

![2024-08-20 15_52_05-D365_PROD_AR_Invoice_Journal - Microsoft Azure and 4 more pages - Work - Microso](<https://github.com/user-attachments/assets/36731735-085d-47a1-926c-5ad9cfcb1672>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![2024-08-20 15_52_05-D365_PROD_AR_Invoice_Journal - Microsoft Azure and 4 more pages - Work - Microso](<https://github.com/user-attachments/assets/d179e663-0c64-422b-a94d-6a40655d429e>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by aviators-germany** [comment]
This happens often when you selecting the wrong property hierarchy. You should check if you selected the correct property.

**Comment by MWG-Musco-Olive** [comment]
I had already created this Logic app using the old designer in the past, and I am building it the exact same way (pointing to a different D365 instance) using the new designer.  I am sure I was using the correct hierarchy.  It happens on every Logic App I try to build with the new designer.

**Comment by ccastrotrejo** [comment]
Hey @MWG-Musco-Olive thanks for raising this issue. I tried to repro your issue on my end but couldn't do it. Is there any chance you can share your workflow.json with me? You can post it here or share it to my email: ccastrotrejo@microsoft.com

I was able to get jus one for each loop. Just to confirm.
- Does the `Currency` and `Company` tokens come from the same SQL action?
- When you click on the first foreach action is the input the same as the input from the second foreach action?

Inputs for the foreach should look like this in code view `"@body('Get_rows_(V2)')?['value']"` 

<img width="1139" alt="image" src="https://github.com/user-attachments/assets/fde91797-7367-4d68-9e93-93359261a63b">

**Comment by MWG-Musco-Olive** [comment]
Sorry so late in responding.  3 day weekend and then catching up.      Yes I am sure that both pieces of data were from the same input source.  I already switched back to the original development environment that is still available (thank God) , and finished the Logic app.  But I will create a test app using the new interface today and if the problem is still there I will send you the .json file.   Thank you.

**Comment by ccastrotrejo** [comment]
@MWG-Musco-Olive yes, sharing with use the workflow JSON will help us to try to repro the issue. Thanks!
