### ISSUE TITLE
[Templates][Single workflow] Create: Context pane updates

### ISSUE THREAD

**Issue by bonicaayala** [Azure/LogicAppsUX#5455]
### Updates: 

1. Update title to: *Create a new workflow from template* 
2. Use Accordion to display name of template and description. 
3. ~~Update tab Name + state to: *Basics (plural)*~~ Update Basic to Basics (plural) 
4. ~~Move Basics tab to the first position~~ 
5. Update Workflow name description: *Avoid spaces and the following symbols in your workflow name: \ / : \* ? " < > \| @, #, $, %, &.* 
6. State: 

 a. Update State type to State

 b. Update State description to: *This workflow supports the following states. The state determines how data is managed and retained during execution of workflows. Learn more [redirect icon]* 
7. Update icon for feedback button in footer 

### Assets: 

Link to redirect icon: [https://iconcloud.design/search/filter/Fluent%20System%20Library/Fluent%20Regular/Open/8406032d3-3821b375b](<https://iconcloud.design/search/filter/Fluent%20System%20Library/Fluent%20Regular/Open/8406032d3-3821b375b>)

Include "Feedback" button in footer to enable users to easily submit feedback. Text is placeholder.

- option 1: [IconCloud \| Search - announcement > Megaphone](<https://iconcloud.design/search/announcement/047109840-3821b375b>) 
- option 2: [IconCloud \| Search - announcement > Megaphone Loud](<https://iconcloud.design/search/announcement/940b09b7b-3821b375b>) 

### Screenshots: 

![image](<https://github.com/user-attachments/assets/802a1737-7b3b-4ac8-8030-9267a2719e06>)

### Browser 

Edge

**Comment by Elaina-Lee** [comment]
Following the previous discussion, the feedback button will be addressed in a separate context at a later time. 

We won't have a link to direct them at the moment. Discussion is on-going to decide opening another context pane in portal for this.
