### ISSUE TITLE
Trigger or Actions' Inputs or outputs do not load

### ISSUE THREAD

**Issue by Santiagosala2** [Azure/LogicAppsUX#5459]
### Describe the Bug with repro steps 

1. Go to the workflow run history 
2. Select one of the workflow runs 
3. Click on any action to see the input or outputs (error loading) 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/eda15343-e38f-4e79-a531-b13a6d9d58f7>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
Are you behind a firewall or Saw or anything that would prevent you from directly accessing the app? The inputs and outputs come from direct calls to the app rather than our main API so if you can't access the app then we can't load inputs and outputs.

**Comment by Santiagosala2** [comment]
> Are you behind a firewall or Saw or anything that would prevent you from directly accessing the app? The inputs and outputs come from direct calls to the app rather than our main API so if you can't access the app then we can't load inputs and outputs.

Sorry, I just realised that reason why I could not see the data is because the flow is stateless. Thanks
