### ISSUE TITLE
[Templates][Create] State type

### ISSUE THREAD

**Issue by bonicaayala** [Azure/LogicAppsUX#5469]
### Describe the Bug with repro steps 

During the create experience, both state radio buttons are unselected. Make the template default state active to enable the user to see what the template defaults to.

![image](<https://github.com/user-attachments/assets/cbc083be-7076-46aa-8a6b-2dad697e0acc>)

![CleanShot 2024-08-22 at 08 23 12](<https://github.com/user-attachments/assets/35e54b3a-21a0-4a5c-a461-8ab0de7d6541>)

**Comment by preetriti1** [comment]
@bonicaayala - I will only auto select it and not change the text to Default, because if some templates just contains stateless putting default in stateful text is not going to make sense.

**Comment by bonicaayala** [comment]
@preetriti1 

**Updates:** 
- Changed State type to: State
- Updated text: This workflow supports the following states. The state determines how data is managed and retained during execution of workflows. Learn more [icon] 

**Scenario: When both state and stateless are supported:** 
![CleanShot 2024-08-23 at 09 59 56@2x](https://github.com/user-attachments/assets/121ebeb6-0672-45f0-be85-eb3f5de3ae60)
