### ISSUE TITLE
Logic app not saving work done in actions

### ISSUE THREAD

**Issue by johnsonm05** [Azure/LogicAppsUX#5472]
### Describe the Bug with repro steps 

I edit an action but the changes do not actually save. I have noticed this in logic apps with 10 or more actions. The logic will save temporarily but if I need to edit the logic app in the future, when I open the action all of the settings and parameters are gone forcing me to rebuild the action.

This may be isolated to the Dynamics 365 F&O actions.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by preetriti1** [comment]
@johnsonm05 - It will be nice if you can share a screenshot of your workflow and which actions were having trouble, I am assuming you have dynamic parameters in those actions and on reloading the workflow that is showing up is it?

**Comment by Andrew-Lahikainen** [comment]
I see this too. I'll try update this with repro steps, but I can't really tell under what conditions it happens. I end up having to hit save multiple times in order for it to stick. Only really started seeing this when the workflow got bigger.

No timeouts on the workflow "commit" or anything?
