### ISSUE TITLE
New Designer doesn't render HTML correctly

### ISSUE THREAD

**Issue by tjohnson1010** [Azure/LogicAppsUX#5487]
### Describe the Bug with repro steps 

If I try to set the content of an Office365 connector's Send Email v2 action to the attached image, the new designer saves it incorrectly. The Legacy Designer works as expected. I was adding to the end of the body the following when I saw it failing.

`join(variables('ErrorList'),'&lt;br /&gt;')`

From what I see, the new designer made it a span and set the ID of the span to the function instead of the contents of the span.

 When I exit the New Designer and go back the function is missing from viewer.

New Designer saves body as:

`"Body": "&lt;p class=\"editor-paragraph\"&gt;Run : @{workflow().run.name}&lt;/p&gt;&lt;p class=\"editor-paragraph\"&gt;&lt;/p&gt;&lt;br&gt;&lt;p class=\"editor-paragraph\"&gt;Errors were found with:&lt;/p&gt;&lt;p class=\"editor-paragraph\"&gt;&lt;span id=\"@{join(variables('ErrorList'),'&lt;br /&gt;')}\"&gt;&lt;/span&gt;&lt;/p&gt;&lt;p class=\"editor-paragraph\"&gt;&lt;/p&gt;&lt;br&gt;"`

Legacy Designer save body as:

`"Body": "&lt;p&gt;Run : @{workflow().run.name}&lt;br&gt;\n&lt;/p&gt;\n&lt;p&gt;Errors were found with:&lt;br&gt;\n@{join(variables('ErrorList'),'&lt;br /&gt;')}&lt;/p&gt;"`

**Expected Result for this test run was:**

 Run : 08584771701736181813929434981CU16

Errors were found with:

 170\_2654486\_ce4b0577-8dbb-4c9c-bf44-d7547e9f9263.pdf

**But ended up with:**

 Run : 08584771697585121504207377341CU81

Errors were found with:

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Screenshot 2024-08-23 133239](<https://github.com/user-attachments/assets/4b1bdc94-ecb9-4c26-a097-12528e742155>)

### Browser 

Edge 

 Version 127.0.2651.105 (Official build) (64-bit)

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @tjohnson1010  thanks for raising this issue. Issue related to https://github.com/Azure/LogicAppsUX/issues/5463
