### ISSUE TITLE
When selecting the out trigger, I cannot scroll down to change the connection to a new email

### ISSUE THREAD

**Issue by vietluu-collab** [Azure/LogicAppsUX#5494]
### Describe the Bug with repro steps 

1. Go to a logic app with outlook email trigger 
2. Select a lot of parameters until the change connection is hidden. 
3. You will see that you cannot scroll down to change the connection anymore 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by Elaina-Lee** [comment]
Hi @vietluu-collab, if this is still happening, could you help me by providing a video of how to repro? I am unable to repro this.

https://github.com/user-attachments/assets/7ef99c67-cb83-417f-b665-c7192ba608f0
