### ISSUE TITLE
Azure Resource Manager: Failed to see all the actions

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5513]
### Describe the Bug with repro steps 

1\.Create a Standard Logic app in Brazil South location and add stateful workflow.

2. Add a request trigger. 
3. Add a single-auth Managed Identity Supported Connector (eg. Azure Resource Manager, Key vault, etc.) and choose any operation. 

**Expected:** Should able to see all the actions when we click on see all actions under Azure Resource Manager action.

**Actual:**Failed to see all the actions when we click on see all actions under Azure Resource Manager action.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/9c87f997-93fb-45fd-b63e-60db9257e782](<https://github.com/user-attachments/assets/9c87f997-93fb-45fd-b63e-60db9257e782>)

[ARM.zip](<https://github.com/user-attachments/files/16756948/ARM.zip>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40826.1.3

**Comment by ccastrotrejo** [comment]
Hey @vgouth was this something its just happening in Brazil south? I tried to repo but couldn't do it.
Is this constantly happening in your end?

**Comment by vgouth** [comment]
@ccastrotrejo , Yes, we have to create a logic app specifically in Brazil South region for managed identity test case. It is constantly happening at my end.

**Comment by DanielleCogs** [comment]
Note: HAR does not contain any of the API calls we need
