### ISSUE TITLE
LogicApp Designer - In-app connectors are not showing up in GitHub Codespaces

### ISSUE THREAD

**Issue by clangner-quibiq** [Azure/LogicAppsUX#5529]
### Describe the Bug with repro steps 

Hello together,

 we are currently evaluating GitHub Codespaces as a remote dev environment for shattered dev teams.

 Plans are to use the LogicApp(Standard) Extension to model LogicApp Workflows with a GUI.

**We have the following problem:**

 When adding an action to a workflow in the LogicApp Designer, the in-app connectors don't show up.

 This behavior changes sporadically and disappears sometimes through disable and enable the extension or stop and start the codespace.

![image](<https://github.com/user-attachments/assets/027a2e64-f5e1-4fce-a39d-ccf5b325572a>)

Details:

 After creating the codespace for the first time and creating a stateful LogicApp (standard), the Azure connectors including in-app could be selected.

As soon as the Designer is reopened or the LogicApp Extension or the Codespace window is restarted, the following behavior occurs:

 o If “Use azure connectors” was selected, in-app connectors can no longer be selected

 o If “Skip for now” was selected, the Designer no longer starts with various error messages

![image](<https://github.com/user-attachments/assets/e1e81176-bfe5-4b4f-ae13-b2e1fa0c4781>)

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Linux

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

*No response*

### Browser

Edge Version 128.0.2739.42 (64-Bit)

### Additional context

The console outputs the following, but in case of available in-app connectors the log looks the same

![image](<https://github.com/user-attachments/assets/b2b7bc66-2111-4ee1-a317-720b87b98ec6>)

Additionally, everytime the codespace window is reloaded, two new portforwardings for FuncCoreTools are created:

![image](<https://github.com/user-attachments/assets/e7b83622-eb02-48d2-b1b1-5992e83a87c2>)

**Comment by hartra344** [comment]
We do not currently have official support for GitHub codespaces. It looks like visual studio but has different architecture and limitations in how our backend code has to run and be communicated with. 

We do have it on our backlog to support in the future though and I'll flag this as a request when we next discuss priorities.
