### ISSUE TITLE
Frozen Webpage - File Identifer Selection

### ISSUE THREAD

**Issue by anilyamangil-jll** [Azure/LogicAppsUX#5540]
### Describe the Bug with repro steps 

In sharepoint action, List Folder, the "File Identifer" box is not functional. When navigating in folders, the browser gets frozen and not able to select the folder or files.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge.

### Additional context 

*No response*

**Comment by DanielleCogs** [comment]
Was able to select top-level folders, but saw lag when selecting nested folders, then page crashed. Able to reproduce.

**Comment by preetriti1** [comment]
This is fixed by this https://github.com/Azure/LogicAppsUX/pull/5576 
ETA for production deployment is 09/10
