### ISSUE TITLE
Only boolesch value possible after copying "Initialize variable" in Logic App

### ISSUE THREAD

**Issue by ghghrzg** [Azure/LogicAppsUX#5557]
### Describe the Bug with repro steps 

I inserted the action Initialize variable, after copying the action i'm only allowed to enter a bool value despite the selection "String".

![image](<https://github.com/user-attachments/assets/33cbdede-4bb8-4d60-9843-59326f27c7a7>)

![image](<https://github.com/user-attachments/assets/fd188212-a68b-43c6-9885-115db0676aa0>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by Elaina-Lee** [comment]
https://github.com/user-attachments/assets/b8004cba-68ae-4a3c-bfe0-df044f4902a4



I am unable to reprod this, so will be closing the ticket assuming it has been fixed. If the issue persists, please reach out to me or re-open this ticket. Thanks!
