### ISSUE TITLE
Microsoft Forms trigger is not working when a new response is submitted 

### ISSUE THREAD

**Issue by durakk1** [Azure/LogicAppsUX#5569]
### Describe the Bug with repro steps 

1. Create a new trigger with Microsoft Forms: When a new response is submitted 
2. Choose an existing MS Form for the trigger 
3. Create an action with Microsoft Forms: Get response details 
4. Get the response ID: @{triggerBody()?['resourceData']?['responseId']} 
5. Submit a new form response 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Get_response_details": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "microsoftforms-1"
            }
          },
          "method": "get",
          "path": "/formapi/api/forms('@{encodeURIComponent('KxmWNfX9LE6m-qy3Bslj2FReV8qWXv5LsbFugCA4IfZUN05NNU1IWjJURzlGN1FOQU5KNUk3U1VMTy4u')}')/responses",
          "queries": {
            "response_id": "@triggerBody()?['resourceData']?['responseId']"
          }
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_new_response_is_submitted": {
        "type": "ApiConnectionWebhook",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "microsoftforms-1"
            }
          },
          "body": {
            "eventType": "responseAdded",
            "notificationUrl": "@listCallbackUrl()",
            "source": "ms-connector"
          },
          "path": "/formapi/api/forms/@{encodeURIComponent('KxmWNfX9LE6m-qy3Bslj2FReV8qWXv5LsbFugCA4IfZUN05NNU1IWjJURzlGN1FOQU5KNUk3U1VMTy4u')}/webhooks"
        }
      }
    }
  },
  "connectionReferences": {
    "microsoftforms-1": {
      "connection": {
        "id": "/subscriptions/7fa91683-7a55-4063-b92f-a4cb7409dd43/resourceGroups/az-rg-rdata-dev-01/providers/Microsoft.Web/connections/microsoftforms"
      },
      "connectionName": "microsoftforms",
      "api": {
        "id": "/subscriptions/7fa91683-7a55-4063-b92f-a4cb7409dd43/providers/Microsoft.Web/locations/eastus2/managedApis/microsoftforms"
      },
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

Issues:

- If "Split on" is enabled on the trigger, flow would never activate, even when you try to run it manually. 
- If "Split on" is disabled on the trigger, flow would not trigger on form response but it fires when you run it manually. However it does not return the response ID to the next step and response ID becomes null in the action: 

 {

 "response\_id": null

 }

**Comment by preetriti1** [comment]
@durakk1 - Can you please try to create your workflow from this portal link - https://aka.ms/emastaging and then update your result of execution?

**Comment by durakk1** [comment]
@preetriti1 I created a new workflow from that portal link and I can confirm the issue remains the same: 

- With split on enabled, it does not trigger and manual run doesn't work.
- With split on disabled, it does not trigger however it registers the submission with manual run.

**Comment by durakk1** [comment]
@preetriti1 I just tested the same workflow in our second Logic Apps instance in our RG and it worked on that instance. I think I should open a ticket for this internally as it will be difficult to replicate this. 

Please let me know if you still want to explore this though.

**Comment by preetriti1** [comment]
@durakk1 - Please open a ticket for that and it looks likes a runtime issue so it will be investigated appropriately. I am going to close this ticket.
