### ISSUE TITLE
Using custom connector is giving - Invalid connection, please update your connection to load complete details

### ISSUE THREAD

**Issue by takyyon** [Azure/LogicAppsUX#5579]
### Describe the Bug with repro steps 

The customer is using a custom connector and has encountered the following issue: "Invalid connection, please update your connection to load complete details," despite the API connection indicating it has connected successfully.

The same connector functions correctly in the legacy system, as detailed in the attached document.

![IMG_0660](<https://github.com/user-attachments/assets/d2501068-2d2b-4fdd-8db7-c91201d9a754>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

Customer has shared the har file as well

**Comment by preetriti1** [comment]
We have a fix going in for this release already. ETA 09/10
