### ISSUE TITLE
API Management shape in new designer does not create correct reference to API

### ISSUE THREAD

**Issue by apropl** [Azure/LogicAppsUX#5599]
### Describe the Bug with repro steps 

1. Create API management shape in new designer and point out API 
2. The api shape is created in the logic app designer, named "s112-accountingentryitem" in arm template below. But in code view it points to the wrong template. 

"template": "/s112-accountingentryitem/AccountingEntryItemv2"

I dont know where it gets the above from? Cannot be found in APIM.

3. Create API management shape in old designer and point out API 
4. The api shape is created in the logic app designer, named "AccountingEntryItemv2" in arm template below. In code view it now points to the correct template. 

"template": "/mip/hrplus/s112\_EmployeeInformation/v1/bulkapi/AccountingEntryItemv2"

API URL Suffix: /mip/hrplus/s112\_EmployeeInformation

 Version: v1/

 Operation: bulkapi/AccountingEntryItemv2

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    },
    "actions": {
      "s112-accountingentryitem": {
        "type": "ApiManagement",
        "inputs": {
          "api": {
            "id": "/subscriptions/xxx/resourceGroups/apimanagement/providers/Microsoft.ApiManagement/service/MyApimInstance/apis/s112-accountingentryitem"
          },
          "method": "get",
          "pathTemplate": {
            "template": "/s112-accountingentryitem/AccountingEntryItemv2"
          }
        },
        "runAfter": {}
      },
      "AccountingEntryItemv2": {
        "type": "ApiManagement",
        "inputs": {
          "api": {
            "id": "/subscriptions/xxx/resourceGroups/apimanagement/providers/Microsoft.ApiManagement/service/MyApimInstance/apis/s112-hrplus_employeeinformation"
          },
          "method": "get",
          "pathTemplate": {
            "template": "/mip/hrplus/s112_EmployeeInformation/v1/bulkapi/AccountingEntryItemv2"
          }
        },
        "runAfter": {
          "s112-accountingentryitem": [
            "SUCCEEDED"
          ]
        }
      }
    },
    "outputs": {},
    "parameters": {
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {}
    }
  }
}
```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

*No response*

**Comment by rllyy97** [comment]
Hi @apropl I tried to reproduce your issue and was not seeing the same behavior, I'll need some more information to investigate this properly.
Specifically I would like to take a look at the swagger file and the operation id you are trying to add.
I would also like to see the serialized code for your apim operation from both old and new designer.
If you have tried to run the operation after saving in new-designer could you also include any sort of runtime failure you are seeing?
For the swagger file if you do not have it you can just take a network trace instead (instructions here: https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#collecting-console-errors)
If you don't want to upload any of that information here you can go ahead and just email it directly to me at rileyevans@microsoft.com
