### ISSUE TITLE
Page Unresponsive SharePoint file change trigger

### ISSUE THREAD

**Issue by CAdvBI** [Azure/LogicAppsUX#5606]
### Describe the Bug with repro steps

1. Add Trigger.
2. Select "when a file is created or modified (properties only)
3. Select site address from dropdown (https:campusadvhq.sharepoint.com)
4. Select library name: Operations Shared Documents
5. Select Folder under "Advanced Parameters". Drill through stops functioning at "Recurring Processes" folder.

Page becomes unresponsive.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Which operating system are you using?

Windows

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

![Trigger Error Logic App](https://github.com/user-attachments/assets/54bdfab4-2880-4d5f-a903-13e7fd34c562)
![Unresponsive Page](https://github.com/user-attachments/assets/7b93c5e4-e910-427c-9854-60237489ec52)

### Browser

Chrome

### Additional context

This functions fine within Power Automate. Permissions are there. Not sure what is happening.

**Comment by hartra344** [comment]
This is a known issue and we have a fix in PR now that'll be in our next release.
