### ISSUE TITLE
Gmail Sender Failing with some characters in sending

### ISSUE THREAD

**Issue by jdubya86** [Azure/LogicAppsUX#5614]
### Describe the Bug with repro steps 

Using Logic App to send a gmail, using the atatched JSON input creates a CC string failure and fails the send and thus the app.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "To": " Eag*******llips.com, di****ri.co",
  "Cc": "s*****co, \"7240, Ranger\" <Ranger.7240@co******s.com>",
   "Subject": "Received: Yan******7.pdf _  Yan****07.pdf",
  "Body": "***snipped****CADPLOOPSTOP*</p>",
  "Attachments": [
    {
```

### Screenshots or Videos

*No response*

### Browser

chrome

### Additional context

*No response*

**Comment by Elaina-Lee** [comment]
You have indicated that you are using the new designer. I confirmed with the team that this connector is not supported for standard (new designer). We are looking into hiding unsupported actions/connectors to minimize confusion.
