### ISSUE TITLE
Designer removing params for nested workflow using nested parameters

### ISSUE THREAD

**Issue by leemck99** [Azure/LogicAppsUX#5615]
### Describe the Bug with repro steps 

This is for an existing workflow/s, that has previously been working.

 Preview portal also has the error, whereas fallback designer does not.

1. Workflow A has a trigger action with nested properties eg 

![image](<https://github.com/user-attachments/assets/f472ba67-ee6b-45d9-8462-bae3d05ebfd3>) 
2. In Workflow B, when calling Workflow A (shown as la-gwf-post-), it will only show the header option in Advance Parameters, and displays an error message : 

![image](<https://github.com/user-attachments/assets/6711aa07-9ce8-427b-8016-1c23d5395340>) 
3. Looking at the workflow.json it has the all the params: 

![image](<https://github.com/user-attachments/assets/ae8f3933-0820-446d-bd00-9f9655e0f85c>) 
4. While in the designer, making any edit and hitting save (any action, not just the nested workflow), it then clears out the body inputs: 

![image](<https://github.com/user-attachments/assets/7a879f90-6168-4180-a63d-360e45dc4c3b>) 

It's only when the nested workflow has nested parameters, all others are ok.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by preetriti1** [comment]
@leemck99 - I am not able to repro this issue -
this is what I have in my child workflow
"inputs": {
                    "body": {
                        "code": true,
                        "file": {
                            "field1": "@concat('priti', 'anshu')",
                            "field2": "@indexOf('Good Afternoon','oo')",
                            "field3": "hjkhjkhjk"
                        },
                        "url": "hjkhjk"
                    },
                    "headers": {
                        "aaaa": "@{triggerBody()}"
                    },
                    "host": {
                        "workflow": {
                            "id": "child"
                        }
                    }
                }
                
And this is my schema in child workflow -
                
![image](https://github.com/user-attachments/assets/7b47d1bb-dbdd-473a-8206-de53d120b735)

I am able to load them fine in our portal. Do you mind sharing the workflow.json of both child workflow and parent workflow so we can try to replicate to see where the error is.

Also share the snippet of console errors.

**Comment by leemck99** [comment]
Hi @preetriti1, I have been able to replicate in test workflows.  

In addition to having the nested parameters, it looks like it only happens when the value is set by a loop item.  I have created a parent workflow with a simple for each loop, which sets Field1 to items('For_each') and is reproducing the error.  The attached files should be able to recreate for you.

In addition, if you click on buttons "Insert dynamic content" or "Insert expression" for one of the nested params (Field1, Field2, Field3), you get the below error, but if you click on button for top level param (url) you don't get the error.
![image](https://github.com/user-attachments/assets/3aa1569a-048e-4253-a8a6-a739f571e3a7).

Hopefully this helps.

[test-child-wf.json](https://github.com/user-attachments/files/16937770/test-child-wf.json)
[test-parent-wf.json](https://github.com/user-attachments/files/16937771/test-parent-wf.json)

**Comment by preetriti1** [comment]
@leemck99 The crash during dynamic content insertion is being fixed and the issues are coming because of incorrect handling of "null" type in your nested fields in new designer... we are identifying the issues and fixing it.

**Comment by leemck99** [comment]
This issue is still occurring in the designer for both the standard and preview portals.  Is the fix pending deployment, otherwise if it has already been released it hasn't resolved as yet.

**Comment by Elaina-Lee** [comment]
@leemck99 could I ask which region you are using? It seems that the fix made was part of the previous deployment cycle which is not fully rolled out yet, so we would need to confirm but that may be why.

**Comment by leemck99** [comment]
Hi @Elaina-Lee, we are using Australia East & South East.

**Comment by Elaina-Lee** [comment]
@leemck99 It does seem that we haven't rolled out to that region yet; it should be rolled out by the EOW. I suggest that you try again after and let us know if it persists next week.
