### ISSUE TITLE
"Unable to initialize operation" error in Generally available new designer

### ISSUE THREAD

**Issue by PranavPatil924** [Azure/LogicAppsUX#5623]
### Describe the Bug with repro steps 

I have recently done the migration of logic apps to new subscription and created new connections and configured the same (using new designer) . Then deleted old connections.

 Now if I open logic app in designer mode (new, generally available designer), it shows below error message ( Unable to initialize Operation) . 

 Snip - Using New designer

![image](<https://github.com/user-attachments/assets/75fb55d5-8be0-4c47-ac55-1726c0bb1339>)

If I open same app using legacy designer, it doesn't show any error. However it doesn't list out existing available connection.

 Snip - Using Legacy Designer 

![image](<https://github.com/user-attachments/assets/86fbbdb2-8c0b-462c-8492-15c023cac7b1>) 

![image](<https://github.com/user-attachments/assets/9a7dbfae-999c-44a3-951b-67ddae8df63b>) \- No existing connections listed

Can you help to rectify this issue as I am unable to use previously created connection and also see the warning that Legacy designer will be deprecated soon

Note- Logic app is running fine but issue with designer

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Microsoft Edge

### Additional context 

*No response*

**Comment by preetriti1** [comment]
@PranavPatil924 Can you please share your connections json part from codeview? Also your current workflow resourceId, need to verify few things

**Comment by PranavPatil924** [comment]
HI Team,,

Thanks, old subscription id reference were observed in connection (id) through code view   , After replacing this with new subscription id the issue is resolved. Now I am able to see the existing connection using new designer. Closing this issue
