### ISSUE TITLE
Drag and drop problem when an action inside a Switch references an action before the Switch

### ISSUE THREAD

**Issue by peramhe** [Azure/LogicAppsUX#5625]
### Describe the Bug with repro steps 

1. Create a Logic App using the workflow JSON below 
2. Save it and re-open the editor (not sure if this is needed) 
3. Try to drag and drop Compose action outside of the Switch- Cannot drag it after the Switch 
- Can drag it before the Switch 
- If I drag it before the Switch, cannot drag it back inside or after the Switch but can drag the Switch before the Compose action 

 

Expected result:

Should be able to drag Compose action after the Switch without having to first move it before the Switch and then move the Switch before the Compose action.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    },
    "actions": {
      "Parse_JSON": {
        "type": "ParseJson",
        "inputs": {
          "content": {
            "Test": "Sample"
          },
          "schema": {}
        },
        "runAfter": {}
      },
      "Terminate": {
        "type": "Terminate",
        "inputs": {
          "runStatus": "Failed"
        },
        "runAfter": {
          "Switch": [
            "Succeeded"
          ]
        }
      },
      "Switch": {
        "type": "Switch",
        "expression": "@dayOfWeek()",
        "default": {
          "actions": {
            "Compose": {
              "type": "Compose",
              "inputs": {
                "Test": "@body('Parse_JSON')"
              }
            }
          }
        },
        "cases": {
          "Case": {
            "actions": {},
            "case": 1
          }
        },
        "runAfter": {
          "Parse_JSON": [
            "Succeeded"
          ]
        }
      }
    },
    "outputs": {},
    "parameters": {
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {}
    }
  }
}
```

### Screenshots or Videos

![drag_drop_problem](<https://github.com/user-attachments/assets/6167f279-67cc-4dd7-91a9-25e8666ca267>)

### Browser

Microsoft Edge Version 128.0.2739.67 (Official build) (64-bit)

### Additional context

*No response*

**Comment by Eric-B-Wu** [comment]
This fix will be in our next release ETA 9/27
