### ISSUE TITLE
Chatbot panel is overlapping with designer

### ISSUE THREAD

**Issue by Elaina-Lee** [Azure/LogicAppsUX#5647]
### Describe the Bug with repro steps 

1. open a workflow 
2. open chatbot 
3. notice the overlap on the command bar part & minimap also pushed out

![image](<https://github.com/user-attachments/assets/e2d3a5b7-0a80-449b-9155-586c1b7aedb8>) 
4. click on one of the actions 
5. notice action panel is cut off due to pushed off from chatbot panel

![image](<https://github.com/user-attachments/assets/70867479-df93-436e-8949-393063b7fe5d>) 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/d682ea4a-6e44-435f-b138-65508557664f](<https://github.com/user-attachments/assets/d682ea4a-6e44-435f-b138-65508557664f>)

### Browser 

all

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
can you go ahead and remove the rightShift/chatbotWidth altogether here and instead use something dynamic. This was something that I was meant to do but never got around to support: https://msazure.visualstudio.com/One/_workitems/edit/25841407

**Comment by Elaina-Lee** [comment]
> can you go ahead and remove the rightShift/chatbotWidth altogether here and instead use something dynamic. This was something that I was meant to do but never got around to support: https://msazure.visualstudio.com/One/_workitems/edit/25841407

Ah good point, seems like adjusting the padding in places won't fix the overflow problem.

**Comment by preetriti1** [comment]
This is not a blocker to remove old designer since chatbot only exists in new designer
