### ISSUE TITLE
"Show Logic App run details" doesn't work when data passed in in very large

### ISSUE THREAD

**Issue by tjohnson1010** [Azure/LogicAppsUX#5658]
### Describe the Bug with repro steps 

When tracing a Logic App run, where the Logic App passes a large amount of data to another Logic App, the "Show Logic App run details" button does not bring up the second Logic App as expected.

 1) Have a Logic App call another Logic App passing a very large payload in the message.

 2) Go to the calling Logic and view the Run.

 3) Click the Action calling the second Logic App.

 4) Click the "Show Logic App run details" button in the right panel.

This does work when the data isn't very large.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/e74b929a-f210-461e-87af-e4ecb7784dc8](<https://github.com/user-attachments/assets/e74b929a-f210-461e-87af-e4ecb7784dc8>)

### Browser 

Microsoft Edge for Business

 Version 128.0.2739.67 (Official build) (64-bit)

### Additional context 

*No response*

**Comment by hartra344** [comment]
Do you see any errors in your browser console or network trace?

**Comment by hartra344** [comment]
Thanks for the detailed information, we'll look into it
