### ISSUE TITLE
Missing integrate button under the function app

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5664]
### Describe the Bug with repro steps 

1\.Create a Function App. Search for "function app" in the search box if you can't find this type of resource.

 2\.Select the created Function App,

 3\.Click the "Integrate" button under the function, and in the "Route template" textbox, enter "my/own/template". We'll use the same value later on.

**Expected:** Integrate button under the function should be available.

**Actual:** Missing integrate button under the function

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/b76a613b-2ec6-4dc5-b6c5-3afb20eaac02>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40909.1.2

**Comment by hartra344** [comment]
This isn't our code, if this is for a test case please work with someone in the team to find the new correct behavior for the test.
