### ISSUE TITLE
Switch mode option is not available in new designer

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5669]
### Describe the Bug with repro steps 

1. Create a consumption logic app. 
2. Select the “request” as trigger 
3. Select the “Google sheet – insert row”

 File: your excel file

 Worksheet: select the sheet 
4. Switch mode, make sure the content does not change 

**Expected:** Switch mode option should be present. We should be able to switch between designer view and code view.

**Actual:** Switch mode option is not available in new designer.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

**Version:** 2\.40909.1.2

**Comment by hartra344** [comment]
This will be available in the next release. In the meantime you can select code view from the Logic app menu sidebar to edit code.
