### ISSUE TITLE
Unable to Open the Logic app run

### ISSUE THREAD

**Issue by AzureDev0012** [Azure/LogicAppsUX#5671]
### Describe the Bug with repro steps 

Open the logic App, then Logic App Workflow.

 Try to open the Logic App run in different Tab. It fails to Open (Attached the error screen shot).

 But just click on the run (on Same Tab), it is opening.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
NA
```

### Screenshots or Videos

When try to open the Logic App run in Different tab

![image](<https://github.com/user-attachments/assets/2e0c1a99-6127-4bb7-a75e-a864e0a8660f>)

### Browser

Edge, Chrome…

### Additional context

*No response*

**Comment by Eric-B-Wu** [comment]
Hi @AzureDev0012, would you be able to grab console and har logs following: https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#collecting-console-errors and send it to wue@microsoft.com for further investigation?

**Comment by AzureDev0012** [comment]
@Eric-B-Wu I have the logs in mail

**Comment by Eric-B-Wu** [comment]
Hi @AzureDev0012, we've deployed a fix which has been working for other customers. Please let me know if you are still facing the same issue
