### ISSUE TITLE
Failed to run "Local binary .NET SDK version" command. Check output window for more details.

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#5675]
### Describe the Bug with repro steps 

Created new project in VS Code and am getting this error

NodeJs Binaries: C:\Users\kewear.azurelogicapps\dependencies\NodeJs

 FuncCoreTools Binaries: C:\Users\kewear.azurelogicapps\dependencies\FuncCoreTools

 3:47:07 PM: Running command: "Local binary .NET SDK version 6.0.421"…

 DotNetSDK Binaries: C:\Users\kewear.azurelogicapps\dependencies\DotNetSDK

 'Local' is not recognized as an internal or external command,

 operable program or batch file.

 3:47:07 PM: Azure Logic Apps Standard Runtime Dependencies validation and installation completed successfully.

 3:47:52 PM: Logic App project name set to hybridTest

 3:47:55 PM: Running command: "Local binary .NET SDK version 6.0.421"…

 'Local' is not recognized as an internal or external command,

 operable program or batch file.

 3:47:55 PM: Error: Failed to run "Local binary .NET SDK version" command. Check output window for more details.

 3:50:02 PM: Running command: "Local binary .NET SDK version 6.0.421"…

 'Local' is not recognized as an internal or external command,

 operable program or batch file.

 3:50:03 PM: Error: Failed to run "Local binary .NET SDK version" command. Check output window for more details.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/40a29e1c-f3d2-4c86-9c83-9d86029ab68d>)

### Browser 

NA

### Additional context 

*No response*

**Comment by wsilveiranz** [comment]
@ccastrotrejo this looks like an issue on with onboarding, can you check with @kewear ?

**Comment by kewear** [comment]
Some additional details - it looks like it is somehow related to vscode-azurelogicapps-4.23.0 4.vsix which is a hybrid vsix. I have used this vsix before. But regardless, not sure what I should do with that error message

**Comment by ccastrotrejo** [comment]
Hey @kewear it looks like your settings configuration have changed. It looks like the vscode extension is trying to directly execute the `Local binary .NET SDK version 6.0.421` command, which is something we don't do. Could you please check if you have the following configuration right?

- Azure Logic Apps Standard: Func Core Tools Binary Path - /Users/username/.azurelogicapps/dependencies/FuncCoreTools/func
- Azure Logic Apps Standard: Node JS Binary Path - /Users/username/.azurelogicapps/dependencies/NodeJs/bin/node
- Azure Logic Apps Standard: Dotnet Binary Path - /Users/username/.azurelogicapps/dependencies/DotNetSDK/dotnet

`username` its just a placeholder should be your username in your computer

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/762bdc94-9fe8-4f06-9858-99516d9e25c6">

**Comment by kewear** [comment]
I have tried to repo this and now seems to be functioning properly so I will close ticket
