### ISSUE TITLE
Logic App designer "save" button not gray even saved successfully

### ISSUE THREAD

**Issue by huidongl** [Azure/LogicAppsUX#5682]
### Describe the Bug with repro steps 

Whenever customer open the workflows in Standard Logic App, the save and discard button is always enabled even if customer already saved it successfully and didn't make any changes.

Customer save the workflow and it had a "successfully saved workflow" notification. And the "save" and "discard" button became gray

Customer click any other blade such as "overview" and then click the designer to get back to the designer view again, the "save" and "discard" button are enabled again. If customer now click another blade, it will have a warning that you have something unsaved, but actually we didn't make any changes to the code.

We made comparison for the code view when the save button was gray and not gray, and the code are exactly the same.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/ecbb1c4a-fcb9-43f6-8c38-2ddee0f34317>)

![image](<https://github.com/user-attachments/assets/d2077395-e3b7-4b66-8c1b-5f20643e30fb>)

### Browser 

Edge, I am attaching the two workflow JSON after save successfully and re open the designer

[workflow1.json](<https://github.com/user-attachments/files/17011496/workflow1.json>)

[workflow2.json](<https://github.com/user-attachments/files/17011494/workflow2.json>)

### Additional context 

*No response*

**Comment by huidongl** [comment]
May I know if we have any update on this issue? Thanks!

**Comment by Elaina-Lee** [comment]
Hi @huidongl, have you observed this issue specifically on these workflow only? I was testing around and was unable to observe this, so would like to confirm

https://github.com/user-attachments/assets/ca318d13-3515-4146-aa05-69e7b801aea2

**Comment by huidongl** [comment]
Hi @Elaina-Lee , the customer's issue is different than the video. 

Customer did not make any changes to the workflow in designer, and after saving, the save button became gray. And the click the overview, if they click back to designer view, the save button is not gray out. I have collected the workflow.json and attached them here, which are copied by clicking the top of the designer "{ }code view". One was collected right after saving success and the save button became gray, and the other one collected when they returned to the designer and the save button is black. We compared the two files and they are identical.

**Comment by huidongl** [comment]
@Elaina-Lee May I know if we can have any update on this issue? Our Customer is S500 and we haven't update with them for more than a week. Thank you!

**Comment by huidongl** [comment]
@Elaina-Lee  After testing with customer we found this issue may not be related to any specific workflows. For example, even if I create a workflow with very simple actions, after saving it, without making any changes, I just randomly click the action or trigger, the "Save" button will become highlighted again. 

![image](https://github.com/user-attachments/assets/d7f5d318-4c77-4fde-9555-a428c4382ca3)

And if I want to exit the designer, I will get a warning that I have unsaved changes, but I actually didn't change anything, but just opened a random connector design window. 

![image](https://github.com/user-attachments/assets/4a9456b8-06cd-41e4-8031-5b24d8974dfd)

You can easily reproduce this issue.

**Comment by Elaina-Lee** [comment]
@huidongl Thanks for providing additional context. I acknowledge what's going on and investigating. 

From what I am observing on my own repro, the save button getting highlighted does not happen when the action or trigger gets clicked. The issue is that when you click on some of the actions/triggers then the input box, then the save button becomes highlighted again. Is this correct?

Also moving forward, would you consider opening the incident for high priority items? Thank you

**Comment by huidongl** [comment]
@Elaina-Lee  Yes that's correct. If you click the input box part of the connector the save button will become highlighted again. Would you like me to open an ICM or an incident in Github?

**Comment by Elaina-Lee** [comment]
@huidongl For anything higher in priority such as S500, please open the ICM. Actually, would you create one for this one as well? I had a discussion with other teammates and that way it'd be easier to keep track of those if you would need it resolved sooner.

**Comment by preetriti1** [comment]
@huidongl - We have found the issue and will be working on fixing it. Let us know if this is blocking the customer in anyway.
Please follow this github issue for tracking the fix and release ETA.
