### ISSUE TITLE
Replication task: Some Actions are missing in service bus queue action. 

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5683]
### Describe the Bug with repro steps 

1\.Create a stateless workflow in the logic app.

2\.Add a service bus "When messages are available in a queue (peek-lock)" trigger.

3\.In the trigger, enter the queue name of your first service bus queue in "Queue name".

Add a For each action and select Messages from the dynamic content as its input parameter.

 4\.Within the for each loop add the action "Dead-letter the message/Abandon the message/Complete the message" from service bus. In the Message ID field select "Message ID" from the dynamic content popup.

5. Save the workflow. 

**Expected:** Should be able to see Dead-letter the message/Abandon the message/Complete the message actions in service bus action.

**Actual:** Not able to see Dead-letter the message/Abandon the message/Complete the message actions in service bus action.

**Note:**Will renaming the actions as shown in the screenshot below affect their functionality? It appears a queue must be selected for the modified action. Could you explain the purpose of selecting these queues? I've encountered a similar issue before, as documented here: [https://github.com/Azure/LogicAppsUX/issues/5419)](<https://github.com/Azure/LogicAppsUX/issues/5419%29>). Feel free to contact me if you need further discussion on the test case.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/e772abfa-2003-4a07-a3e7-814067769cd8>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40909.1.2

**Comment by Eric-B-Wu** [comment]
The action no longer exists: https://learn.microsoft.com/en-us/connectors/servicebus/#actions, for these test cases let's switch over to the other actions ex. [Complete the message in a topic subscription](https://learn.microsoft.com/en-us/connectors/servicebus/#complete-the-message-in-a-topic-subscription)
