### ISSUE TITLE
failed to start a run for [logic app name]

### ISSUE THREAD

**Issue by pschonefeld-sot** [Azure/LogicAppsUX#5696]
### Describe the Bug with repro steps 

1. Select Run with Payload; 
2. Add payload as json (this is only happening for POST for me) 
3. Cick "Run" … get error but the run history is logged ok 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

This might prevent me calling POST http trigger flows from another logic app.

**Comment by Eric-B-Wu** [comment]
We'll use https://github.com/Azure/LogicAppsUX/issues/5648 for tracking of this incident. I'll follow up with our backend team to see why they're giving us an error

**Comment by Eric-B-Wu** [comment]
yep this should be in our next release, which should be 7/25
