### ISSUE TITLE
"Submit from this action" in New Designer doesn't use newest LogicApp version

### ISSUE THREAD

**Issue by peanutsp** [Azure/LogicAppsUX#5697]
### Describe the Bug with repro steps 

1. Open a previous run from Run History 
2. Make any kind of change in the LogicApp designer or code view 
3. Click "Submit from this action" after choosing an action in the "Run History" view of the previous run 
4. The run will use the version of the LogicApp that was saved when the run was started, ignoring any changes made in the meaintime. When re-running the LogicApp completely (NOT from "this action") the LogicApp uses the latest version that was saved. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome, Firefox

### Additional context 

When the same steps are done using a Rerun of the whole App, the newest version of the LogicApp is chosen. Using 2 different versions of the LogicApp when choosing different re-run options is counter-intuitive.

**Comment by hartra344** [comment]
This is by designer. The run from Action is there to help pick up where you left off if for instance a database is down or something and that causes and action to fail. It is not designed for rerunning with an updated workflow.json.
