### ISSUE TITLE
Input payloads wiped out after making a small change in a switch

### ISSUE THREAD

**Issue by hardEight** [Azure/LogicAppsUX#5703]
### Describe the Bug with repro steps 

1. Clicked Edit to open the designer 
2. Edited the text in a switch 
3. Saved

 The next run failed because the payload that should have been sent to the Fin & Ops instance was empty. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
It's attached. Github wouldn't allow me to submit with it.
```

### Screenshots or Videos

![AllTheseAreMissingInputs](<https://github.com/user-attachments/assets/c5cfa418-e84c-41a4-a6cc-c760b657aa3d>)

[Code09162024.txt](<https://github.com/user-attachments/files/17047040/Code09162024.txt>)

[Code09172024\_BodiesRemovedFromInput.txt](<https://github.com/user-attachments/files/17047043/Code09172024_BodiesRemovedFromInput.txt>)

![FirstCompare](<https://github.com/user-attachments/assets/96c0e248-f202-43d3-9ce1-421cada81285>)

![TheOnlyChange](<https://github.com/user-attachments/assets/c1bd1a27-8424-4ca6-81c3-ef15e25fda4b>)

### Browser

Edge Version 129.0.2792.41 (Official build) stable app, beta channel (64-bit)

### Additional context

So I entered the new designer. Changed a switch value to a shorter string, and all the input bodies for the Fin & Ops connectors were wiped out as you can see in the comparison of the code.

**Comment by Eric-B-Wu** [comment]
Hi @hardEight I was unable to reproduce this issue, if you load of up the older version of your workflow and rename it again, does it cause the body to be removed once again?

**Comment by hardEight** [comment]
Yeah I can't recreate it either but, it happened.

**Comment by Eric-B-Wu** [comment]
I'll continue to do a few tests on my end; however, without it happening again, it will be a little difficult to determine where the problem area is. If this ever happens again with any repro steps and please feel free to create a new issue if this issue closes due to automatically being closed

**Comment by hardEight** [comment]
Totally understand, intermittent and non-reproducible issues are the worst!

Thanks
