### ISSUE TITLE
msla-designer-canvas is not using 100% side of parent

### ISSUE THREAD

**Issue by Xiaoyu-Huang** [Azure/LogicAppsUX#5704]
### Describe the Bug with repro steps

I am trying to adopt the latest version 4.94.0. I noticed that the designer cannot be rendered. after debugging, I noticed some class styling change which caused the designer cavas isn't using 100% of parent, The version we used earlier is 4.51.5

   "@microsoft/logic-apps-designer": "4.94.0",
    "@microsoft/logic-apps-shared": "4.94.0",
    
    
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/bf87fd64-2f40-4fcf-a469-9174e8405260">

    

### What type of Logic App Is this happening in?

Consumption (Portal)

### Which operating system are you using?

Windows

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

**Comment by rllyy97** [comment]
Hi @Xiaoyu-Huang, this was an intended breaking change as part of this PR: https://github.com/Azure/LogicAppsUX/pull/5397
Instead of using `height: 100%` we have `flex: 1` instead, you should be able to wrap the designer component in a flex box to have it fill the space again
