### ISSUE TITLE
Logic Apps deployment BUG

### ISSUE THREAD

**Issue by FeverDream1** [Azure/LogicAppsUX#5711]
### Describe the Bug with repro steps 

When I deploy Logic app through ARM templet, the deployment will overwrite the UMI of blob content,

 It will show the UMI doesn't select anything. But it can still work . I think this is a displaying bug.

 It influences my work that I can do nothing. My leader think I shouldn't deploy anything until I resolve this question . In fact I don't think this issue belongs to me. Because in eariler time, I can see the UMI is correct after deployment.

 Hope someone can help me on this question

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Uploading screenshot.png…\]\()

### Browser 

Edge

### Additional context 

*No response*

**Comment by FeverDream1** [comment]
Could you see the screenshot?

**Comment by FeverDream1** [comment]
![screenshot](https://github.com/user-attachments/assets/c98d6465-8142-4e73-880e-1e8bca6c3c84)
[portal.azure.com.zip](https://github.com/user-attachments/files/17092426/portal.azure.com.zip)
Please see my attachments

**Comment by takyyon** [comment]
Actually, can you send me the har on email instead? - krmitta@microsoft.com

**Comment by FeverDream1** [comment]
I've sent the email already.
Please check it , thanks.
