### ISSUE TITLE
Logic App Designer is not showing after switching it to Generally Available Designer

### ISSUE THREAD

**Issue by SaravananSubramanian27** [Azure/LogicAppsUX#5714]
### Describe the Bug with repro steps 

1. Go to existing Logic App with Service bus trigger connection

 
2. Open Logic app Designer/ Run History

![image](<https://github.com/user-attachments/assets/de7fa4b5-8448-41a2-a1dc-d0c4b2849c67>)

 
3. Switch to Generally Available Designer

![image](<https://github.com/user-attachments/assets/e387f9ef-8c85-45a8-b831-46d0a9179179>)

![image](<https://github.com/user-attachments/assets/87183ef8-2fa8-42ac-8d6b-8d78e1174a4b>)

 
4. All the tasks disappears (but Logic App runs without failure, not able to see Activities)

 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by takyyon** [comment]
Can you attach your workflow.json, and attach a har file for your repro with the designer?

**Comment by SaravananSubramanian27** [comment]
Please find the details Workflow.json. I couldnt upload HAR file, as github doesnt allow it. 
<img width="448" alt="image" src="https://github.com/user-attachments/assets/ac218c02-5fde-43ca-bd1f-a673b8cb59f7">


[LogicApp.json](https://github.com/user-attachments/files/17091873/LogicApp.json)

**Comment by takyyon** [comment]
You can send me the har directly here - krmitta@microsoft.com

**Comment by PedroAlmeidaMS** [comment]
Issue is on Service Bus Triggers and possibly actions, 

[Microsoft_Azure_EMA]  9:19:40 AM useLayout org.eclips**e.elk.graph.json.JsonImportException: Referenced shape does not exist: Initialize_bannerID - {"id":"root","children":[{"id":"When_a_message_is_received_in_a_topic_subscription_(peek-lock)","height":40,"width":200,"layoutOptions":{"nodeType":"OPERATION_NODE"}},**

I was able to reproduce this issue using the same JSON that was used by the bug creator.
other customers reporting the same issue.

Session ID: cee22fb378824e9fad76552b3a767e88


Sending the console log directly to you.

**Comment by rllyy97** [comment]
Hi @SaravananSubramanian27, I took a look at your workflow definition, you have an action named `Initialize_mdmUpdaterSuccessful` that runs after `Initialize_BannerID`.  In the run-after setting you have a case difference in the action name (you have it set to `Initialize_bannerID`).  If you modify that run after setting to have the action names casing match it should load the workflow fine.
