### ISSUE TITLE
Firefox Nightly (Deb) 132.0a1 Crashes On New Power Automate Instant Button Flow

### ISSUE THREAD

**Issue by influential-eliot** [Azure/LogicAppsUX#5728]
### Describe the Bug with repro steps 

1. New Instant Cloud Flow 
2. Name it 
3. Select '*Manually trigger a flow*' 
4. Tap to continue … and crash 

### What type of Logic App Is this happening in? 

Power Automate

### Which operating system are you using? 

Linux

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Firefox Nightly 132.0a1 (*Mozilla Firefox Debian Package \| mozilla-deb - 1.0*)

(*just updated*)

I ran this on a completely fresh profile with zero modifications and on my existing main profile … it crashed both.

### Additional context 

I have also logged this in the Mozilla forum, here: [https://support.mozilla.org/en-US/questions/1465140](<https://support.mozilla.org/en-US/questions/1465140>)

This works fine in the following browsers with zero modifications to the browsers:

- **Ungoogled Chromium** \- Absolutely fine, no add-ons 
- **Firefox mozilla-deb - 1.0 130.0.1 (64-bit)** \- Absolutely fine, no add-ons 

I have no screenshots of a crash and no flow to send details of.

I am forced to use the new designer by way of the creation flow, there is no way to use the old designer for creating a new flow. At least, I don't know what URL / JS I'd need to manipulate to get that.

**Comment by hartra344** [comment]
This isn't a piece of UI we own here but I can make sure this gets sent to the right people to take a look at on the power automate side. It's not uncommon for nightly firefox builds to have issues like this though. In the past, the Mozilla team has been good about addressing them when they're reported.

**Comment by ek68794998** [comment]
Hello @influential-eliot, Power Automate side here!

+1 to what @hartra344 said. For this kind of issue, the Power Automate team would usually be the ones to take a look.

However, in this case, I was not able to repro with Firefox release build 130.0.1 x64 on Windows 11, which would be our primary focus for support. If you're still seeing this issue when Firefox 132 hits public release, feel free to ping me in this thread and we'll carry forward the issue with the Power Automate team. Thanks!

**Comment by influential-eliot** [comment]
Cheers, both ... but I would imagine that if it crashes in PA, it will crash in LA. Which I will now test. 😩 

But I wasn't really looking for help ... but it's a shame to read the above. Either way, good luck.

Also, @ek68794998 ... I mean ... I cannot use Windows ... so ... if this bug filters down to mainline Firefox on Linux will that basically be it for me and my (actual) job?

I logged it because:

- ... I presume that when you are testing the GUI (used in both, hence the next point) you test not just with current versions of browsers, but with future versions like DEV and Canary for EDGE
- ... there was *literally* an option to log PA UI issues here ... so ... I have 

... but ... Whatever works. 🤷 😅

**Comment by ek68794998** [comment]
> Also, @ek68794998 ... I mean ... I cannot use Windows ... so ... if this bug filters down to mainline Firefox on Linux will that basically be it for me and my (actual) job?

No, it just happens in this case that I can't easily test out Firefox's public release with a Linux machine. But if we somehow get a Linux-specific bug on stable release, we'll figure that out at the point in time when it happens.

> ... there was literally an option to log PA UI issues here ... so ... I have

Yeah, no problem with the issue being posted. Would rather be aware of it than not, even if we're not looking deeper right now. Since we do share a good chunk of code between LA and PA, a problem in this code base might appear in both&mdash;but it also might not. 😊

> `edit` Also, where do we publicly raise issues with the V3 designer for Power Automate if not here?

Generally, you would go through either [the official support channel](https://www.microsoft.com/power-platform/products/power-automate/support) or through the [Power Automate community forum](https://community.powerplatform.com/forums/thread/?groupid=46ce02a3-e1a7-4176-81fc-d93a4001d287).

**Comment by influential-eliot** [comment]
Cheers, @ek68794998 👍 

Oh and ... '_the official support channel_' isn't public and the Power Automate community forum is a different resource ( _which currently doesn't work - have sent all issue to italent, yep_ 😉 ) not well equipped (_like this_).

Thanks anyway. 👍

**Comment by hartra344** [comment]
@influential-eliot feel free to post any issues here if you're in doubt. If it's not shared code or caused by our code, we can always do what we just did and make sure it does get put in front of the right people.

**Comment by influential-eliot** [comment]
Many thanks!
