### ISSUE TITLE
not able to connect cosmos database through managed identity

### ISSUE THREAD

**Issue by hsiangtingyang** [Azure/LogicAppsUX#5729]
### Describe the Bug with repro steps 

go to designer and add an action.

 search cosmos database query operation.

 the UI just provides the connection string to be filled out.

 I have already added logic app's managed identity into the cosmos db. not sure is it working and how to work it for managed identity.

[https://ms.portal.azure.com/#view/Microsoft\_Azure\_EMA/DesignerEditor.ReactView/id/%2fsubscriptions%2fe5874924-875c-48d4-874b-1d410e6514c5%2fresourceGroups%2fmediavalidation-ppe%2fproviders%2fMicrosoft.Web%2fsites%2fmvsteststatus%2fworkflows%2fmvsteststatusmonitor/location/East%20US/isReadOnly\~/true/isMonitoringView\~/true/runId/08584748190643678493686429590CU00](<https://ms.portal.azure.com/#view/Microsoft_Azure_EMA/DesignerEditor.ReactView/id/%2fsubscriptions%2fe5874924-875c-48d4-874b-1d410e6514c5%2fresourceGroups%2fmediavalidation-ppe%2fproviders%2fMicrosoft.Web%2fsites%2fmvsteststatus%2fworkflows%2fmvsteststatusmonitor/location/East%20US/isReadOnly~/true/isMonitoringView~/true/runId/08584748190643678493686429590CU00>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

edge

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @hsiangtingyang, from what I can tell the only connection authorization available for the Cosmos DB connector is via connection string, MI is not supported as far as I'm aware

**Comment by hsiangtingyang** [comment]
Are there any future plans to support it in Logic Apps?
