### ISSUE TITLE
Input Testing(tokens+User text): Token is inserting after the full text instead place of selected partial text.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5766]
### Describe the Bug with repro steps 

1\.Create a logic app and add http request trigger.

 2\.Add until action.

 3\.Enter some text and from this text select some partial text and try to insert the token at the place of the partial text.

 4\.Token should be insert at the place of the partial selected text.

**Expected :** Token should be insert at the place of the partial selected text.

**Actual :** Token is inserting after the full text instead place of selected partial text.

Note: Working fine with HTTP, CSV, HTML table, send an email, condition actions in new designer.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/6866511e-d9d2-4bb0-b96d-ab8a1af76873](<https://github.com/user-attachments/assets/6866511e-d9d2-4bb0-b96d-ab8a1af76873>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
This is expected behavior, the Row elements are Single Value segments and thus will delete the existing string if you try to add a segment
