### ISSUE TITLE
Foreach: Adjusting the number of loops in the "For each" action is not working in monitoring view

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5769]
### Describe the Bug with repro steps 

1\.Create a consumption logic app.

 2\.Click on edit and open designer.

 3\.Add http request trigger.

 4\.Add Dropbox - List files in folder action.

 5\.Add filter array action.

 6\.Add DisplayName token from Dropbox in Filter array parameter which adds implicit foreach.

 7\.In from parameter select body parameter.

 8\.Save and run the workflow.

 9\.Upon executing the workflow in the monitoring view, Adjusting the number of loops in the "For each" action is not working in monitoring view according to our preferences.

**Expected:** Upon executing the workflow in the monitoring view, Adjusting the number of loops in the "For each" action should be possible and work fine in monitoring view according to our preferences.

**Actual:** Upon executing the workflow in the monitoring view, Adjusting the number of loops in the "For each" action is **not working** in monitoring view according to our preferences.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/c8719698-b3f6-455f-ba36-057a0a4e0d69](<https://github.com/user-attachments/assets/c8719698-b3f6-455f-ba36-057a0a4e0d69>)

### Browser 

Edge

### Additional context 

**Version:** 0\.2022.1.764

**Comment by Eric-B-Wu** [comment]
I think I see the issue. Its that you're trying to delete the 2 in the video, but this requires a value within the input or else it wouldn't know which loop to fetch. The right way to do this would be to select the 2 and replace the value you need to be replaced or to add the value after the 2, and then delete the 2.
