### ISSUE TITLE
Cannot work on a particular action when summoning the Assistant

### ISSUE THREAD

**Issue by shahparth-lab** [Azure/LogicAppsUX#5780]
### Describe the Bug with repro steps 

1. Create a workflow in Logic App (Standard) 
2. Add an action and open it (in my case I did not know how to configure expression inside of an action) 
3. Now, click on Assistant and you will find: reduced action panel size, canvas zoom in/out options overlaying on the actions, Assistant panel is misaligned with the designer panel with an awkward close button 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/7dbf6645-21c5-482a-a245-671b221a940b](<https://github.com/user-attachments/assets/7dbf6645-21c5-482a-a245-671b221a940b>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @shahparth-lab, a fix for this issue is currently being rolled out along with our release, we should see this fixed in all regions by EoD October 4th.
