### ISSUE TITLE
SQL server: New Connection getting added after error popup

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5785]
### Describe the Bug with repro steps 

1. Create a consumption logic app 
2. Create a on premises data gateway 
3. Open designer add http request trigger. 
4. Add SQL Server action 
5. Create a new connection using authentication as SQL Server Authentication. 
6. Give required data 

**Expected:** Connection should establish without any error

**Actual:**New Connection getting added after error popup

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/e4b61840-eeb0-4981-8ae7-06d2de0740a5>)

![image](<https://github.com/user-attachments/assets/fb76f9df-6587-4a06-aecd-4a1d9e2e3f04>)

### Browser 

Edge

### Additional context 

**Version:**0\.2022.1.764

**Comment by rllyy97** [comment]
@vgouth Do you know if this is new behavior / was this not happening before?

**Comment by vgouth** [comment]
@rllyy97 This is the first instance we ran this consumption test pass after long time.

**Comment by daviburg** [comment]
@vgouth please double check that the created connection can actually be used to execute a query on the SQL server. Connections will be saved as ARM resource prior to using them for a test connection call, so even if the test connection call fails, the saved resource will still be there.
It does appear to have a green checkmark next to it, which normally indicates a successful test connection call.
To be able to investigate this from the back-end angle, include the connection resource id, the test logic app resource id, and take a network trace so you can extract the request id of the test connection call. Include which Azure region is been tested, and the UTC time of the test connection request.

**Comment by vgouth** [comment]
@daviburg Following the update to version 2.40923.1.5, the green checkmark indicating a successful connection no longer appears after an error message is displayed. I will keep this issue open and continue to monitor it during the next testing phase. Should the problem persist, I will provide an update here. 
Someone with knowledge of SQL configuration needs to investigate the instance of the SQL server used for testing. Feel free to reach out to me directly so we can discuss this further.

**Comment by rllyy97** [comment]
Jhanvi helped resolve this issue offline
