### ISSUE TITLE
Custom connectors : Unable to fetch custom connectors actions with the connector name

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5788]
### Describe the Bug with repro steps 

1. Create a Logic App custom connector

 
2. Click on the edit on the connector

 
3. Click on the SOAP radio button, Select SOAP to REST Call mode, WSDL URL Import mode

 
4. For wsdl link URL Please reach out to me and click on the Import.

 
5. The general information section, security tab, definition tab should have values as in Expected Result fields. Ensure Base URL is disabled.

 
6. Click on the update connector, it should be saved successfully.

 
7. Create a logic app, Add request trigger and look up actions with the connector name. It should show the actions available under definition

a. Cancel order

b. GetMostRecentOrder

c. GetOpenOrders

d. GetOrder

e. submitOrder

 

**Expected:** Look up actions with the connector name should show the actions available under definition.

**Actual:** Unable to fetch custom connectors actions

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/4edf3e66-8a75-4ec6-8d27-e8ca936519da](<https://github.com/user-attachments/assets/4edf3e66-8a75-4ec6-8d27-e8ca936519da>)

### Browser 

Edge

### Additional context 

**Version:** 0\.2022.1.764

**Comment by Eric-B-Wu** [comment]
closing for: https://github.com/Azure/LogicAppsUX/issues/5787
