### ISSUE TITLE
Custom connectors : Unable to fetch custom connectors actions with the connector name with SOAP pass-through

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5791]
### Describe the Bug with repro steps 

1\.Create a Logic App custom connector

 2\.Click on the edit on the connector

 3\.Click on the SOAP radio button, show 2 Call mode "SOAP to REST", "SOAP pass-through" in dropdown list.

 4\.Select SOAP pass-through call mode.

 5\.The general information section, security tab, definition tab should have values from Expected result. Update the general information tab

 6\.Select the scheme as HTTP and add the host and the base file as below from the fazio service.

 7\.Click on the update connector, it should be saved successfully.

 8\.Create a logic app, add a trigger "When a HTTP request is received", add an action with the connector name. It should show the actions available under definition above.

**Expected:** Look up actions with the connector name should show the actions available under definition.

**Actual:** Unable to fetch custom connectors actions with the connector name with WSDL file

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/35351115-302c-4acf-a811-63ac80249fee>)

### Browser 

Edge

### Additional context 

**Version:** 0\.2022.1.764

**Comment by Eric-B-Wu** [comment]
closing for: https://github.com/Azure/LogicAppsUX/issues/5787
