### ISSUE TITLE
Customer using custom connector and in the new designer facing this issue "Invalid connection, please update your connection to load complete details"

### ISSUE THREAD

**Issue by takyyon** [Azure/LogicAppsUX#5794]
### Describe the Bug with repro steps 

The same connector functions correctly in the legacy system

![image](<https://github.com/user-attachments/assets/fbe347eb-d275-40cd-ba9b-fb0aa652cef9>)

![image](<https://github.com/user-attachments/assets/a5ffde97-722f-44b3-b200-8e2ca6cecd0c>)

Legacy designer

![image](<https://github.com/user-attachments/assets/834d1cb9-56d5-449f-ab29-7f0b80fc0bc5>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

All browsers

### Additional context 

*No response*

**Comment by takyyon** [comment]
Requested a workflow json from the customer

**Comment by Eric-B-Wu** [comment]
closing for: https://github.com/Azure/LogicAppsUX/issues/5787

**Comment by takyyon** [comment]
Workflow from the customer

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "For_each_-_invoice": {
                "actions": {
                    "Condition_-_check_whether_to_send_email": {
                        "actions": {
                            "Send_an_email_(V2)": {
                                "inputs": {
                                    "body": {
                                        "Attachments": [
                                            {
                                                "ContentBytes": "@{base64(body('HTTP_GET_-_Invoice_Details'))}",
                                                "Name": "@{concat(items('For_each_-_invoice'),'.xml')}"
                                            }
                                        ],
                                        "Body": "<p>Attached invoice for @{items('For_each_-_invoice')}</p>",
                                        "Importance": "Normal",
                                        "Subject": "la-ovt-OI-DO2-usw2 - Invoice XML - @{items('For_each_-_invoice')}",
                                        "To": "@parameters('email_recipient')"
                                    },
                                    "host": {
                                        "connection": {
                                            "name": "@parameters('$connections')['office365']['connectionId']"
                                        }
                                    },
                                    "method": "post",
                                    "path": "/v2/Mail"
                                },
                                "runAfter": {},
                                "type": "ApiConnection"
                            }
                        },
                        "expression": {
                            "and": [
                                {
                                    "equals": [
                                        "@parameters('send_email')",
                                        true
                                    ]
                                }
                            ]
                        },
                        "runAfter": {
                            "HTTP_GET_-_Invoice_Details": [
                                "Succeeded"
                            ]
                        },
                        "type": "If"
                    },
                    "HTTP_GET_-_Invoice_Details": {
                        "inputs": {
                            "authentication": {
                                "audience": "@parameters('apiManagerAuthAudience')",
                                "type": "ManagedServiceIdentity"
                            },
                            "headers": {
                                "Content-Type": "application/json",
                                "Host": "@parameters('ApiManagerURL')",
                                "Ocp-Apim-Trace": "false"
                            },
                            "method": "GET",
                            "uri": "https://@{parameters('ApiManagerURL')}/open_invoice/usa/invoices-xml/@{items('For_each_-_invoice')}"
                        },
                        "runAfter": {},
                        "type": "Http"
                    },
                    "Receive_-_Push_to_Legacy_DO2_System": {
                        "inputs": {
                            "body": "@body('HTTP_GET_-_Invoice_Details')",
                            "headers": {
                                "Content-Type": "application/xml"
                            },
                            "host": {
                                "connection": {
                                    "name": "@parameters('$connections')['lacc-ovt-d365-finance-Invoice-Receipt-LegacyService-usw2_1']['connectionId']"
                                }
                            },
                            "method": "post",
                            "path": "/Receive"
                        },
                        "runAfter": {
                            "Condition_-_check_whether_to_send_email": [
                                "Succeeded"
                            ]
                        },
                        "type": "ApiConnection"
                    }
                },
                "foreach": "@parameters('InvoiceIDs')",
                "runAfter": {},
                "type": "Foreach"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {
            "$connections": {
                "defaultValue": {},
                "type": "Object"
            },
            "ApiManagerURL": {
                "defaultValue": "apim-ovt-tst-uw2.azure-api.net",
                "type": "String"
            },
            "InvoiceIDs": {
                "defaultValue": [
                ],
                "type": "Array"
            },
            "apiManagerAuthAudience": {
                "defaultValue": "api://fb533134-4c5d-4249-851a-101d399b727c",
                "type": "String"
            },
            "email_recipient": {
                "defaultValue": "jasminka.mancevska@encana.com",
                "type": "String"
            },
            "send_email": {
                "defaultValue": false,
                "type": "Bool"
            }
        },
        "triggers": {
            "Recurrence": {
                "evaluatedRecurrence": {
                    "frequency": "Week",
                    "interval": 1
                },
                "recurrence": {
                    "frequency": "Week",
                    "interval": 1
                },
                "type": "Recurrence"
            }
        }
    },
    "parameters": {
        "$connections": {
            "value": {
                "lacc-ovt-d365-finance-Invoice-Receipt-LegacyService-usw2_1": {
                    "connectionId": "/subscriptions/51780b97-491d-46c9-8c7a-c99ddb366b83/resourceGroups/rg-ovt-d365-integration-tst/providers/Microsoft.Web/connections/lacc-ovt-d365-finance-Invoice-Receipt-LegacyService-usw2-1",
                    "connectionName": "lacc-ovt-d365-finance-Invoice-Receipt-LegacyService-usw2-1",
                    "id": "/subscriptions/51780b97-491d-46c9-8c7a-c99ddb366b83/resourceGroups/rg-ovt-d365-integration-tst/providers/Microsoft.Web/customApis/lacc-ovt-d365-finance-Invoice-Receipt-LegacyService-usw2"
                },
                "office365": {
                    "connectionId": "/subscriptions/51780b97-491d-46c9-8c7a-c99ddb366b83/resourceGroups/rg-ovt-d365-integration-tst/providers/Microsoft.Web/connections/office365",
                    "connectionName": "office365",
                    "id": "/subscriptions/51780b97-491d-46c9-8c7a-c99ddb366b83/providers/Microsoft.Web/locations/westus2/managedApis/office365"
                }
            }
        }
    }
}

**Comment by simenums** [comment]
@rllyy97 @vgouth @Eric-B-Wu  @preetriti1 : We still experience this issue. This is issue is much more serious from today since the legacy designer is not available anymore ! When is deployment of fix planned?

**Comment by ccastrotrejo** [comment]
HI @simenums we are taking a look at the issue again. In the meantime, please use this url to use the old designer in consumption: https://portal.azure.com/?microsoft_azure_ema_forceFallbackToOldDesigner=true#home

**Comment by rllyy97** [comment]
This issue is fixed in the following PR: https://github.com/Azure/LogicAppsUX/pull/6023.
It will be releasing over the course of the next week
