### ISSUE TITLE
Standard LogicApp - Search not showing built-in actions

### ISSUE THREAD

**Issue by ezhilarasikannan** [Azure/LogicAppsUX#5804]
### Describe the Bug with repro steps 

- Go to Azure Portal 
- Using Non Prod Retail Subscription 
- Logic Apps - mpg-dev-std 
- stateful -> is the workflow name 
- Recurrence is not showing when adding design 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

MacOS

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/9ce5d772-9090-45d8-bee3-c09e76b9caae>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @ezhilarasikannan, I'm not able to reproduce this issue unfortunately.
One thing to check is that that workflow is actually a `stateful` workflow.
If you accidentally created a `stateless` workflow instead, you shouldn't be seeing the recurrence trigger. 

![image](https://github.com/user-attachments/assets/edfd43bb-2578-4037-9203-ae9a66b77c76)

**Comment by ezhilarasikannan** [comment]
Hi @rllyy97 ,
Its stateful workflow only
<img width="1143" alt="image" src="https://github.com/user-attachments/assets/d27ea314-d74d-4a80-bc99-00bfdf9a0391">

**Comment by rllyy97** [comment]
If you open up the panel to add a trigger but don't search for anything, do you see the `Schedule` connector?  Or is it not there

![image](https://github.com/user-attachments/assets/149c60cd-854b-4337-bf94-bf139e0e2fc1)

**Comment by ezhilarasikannan** [comment]
<img width="813" alt="image" src="https://github.com/user-attachments/assets/cdb030f9-a061-4651-a435-e976b19cd0e0">

**Comment by ezhilarasikannan** [comment]
<img width="813" alt="image" src="https://github.com/user-attachments/assets/245bddfe-624e-4984-a4ae-39aa300b05ba">

**Comment by rllyy97** [comment]
It's strange that we're not seeing _any_ in-app connectors show up, can you check the console for errors and collect a network trace?
You can find info on how to get that info here: https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#collecting-console-errors
And you can email me directly at rileyevans@microsoft.com
