### ISSUE TITLE
Custom Code - Assemblies view

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#5814]
### Describe the Bug with repro steps 

I deployed some .NET 8 custom code from VS Code. The code works and it is visible in Kudu. However, when I go to Artifacts/Assemblies I see nothing. I have a suspicion that we are only showing the .NET 4.7 assemblies in that UX

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

I deployed some .NET 8 custom code from VS Code. The code works and it is visible in Kudu. However, when I go to Artifacts/Assemblies I see nothing. I have a suspicion that we are only showing the .NET 4.7 asssemblies in that UX

![image](<https://github.com/user-attachments/assets/c7b83f5a-b86c-4d9f-b67b-35aaf5227d8a>)

![image](<https://github.com/user-attachments/assets/ed616ab3-06f9-49df-9595-a45cda81a78c>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @kewear thanks for raising this issue. Yes it seems that the blade API calls just works when retrieving .net 4.7 files. I have a solid repro for this. I will work on making it dynamically and work for both scenarios.

**Comment by kewear** [comment]
Awesome... thanks @ccastrotrejo

**Comment by ccastrotrejo** [comment]
The fix for this is done. Will be rolled out in the upcoming deployments
