### ISSUE TITLE
Swagger/HTTP task does not serialize

### ISSUE THREAD

**Issue by simonlaszcz** [Azure/LogicAppsUX#5824]
### Describe the Bug with repro steps 

when the retry policy is 'none':

Workflow validation failed for the workflow ''. {"error":{"code":"InvalidRequestContent","message":"The request content is not valid and could not be deserialized: 'Could not find member 'retryPolicy' on object of type 'FlowTemplateAction'. Path 'properties.definition.actions.Task\_', line 1, position 1817.'."}}

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by simonlaszcz** [comment]
Any idea when this fix will be deployed?

Thanks

**Comment by rllyy97** [comment]
Hi @simonlaszcz, it will be a part of our next release cycle, unfortunately we started one yesterday so the next one will be releasing between Oct. 28th and Nov. 1st
