### ISSUE TITLE
Error during deployment script generation 

### ISSUE THREAD

**Issue by yasarqamar** [Azure/LogicAppsUX#5830]
### Describe the issue 

I am trying to deploy my Logic App (Standard) using Visual Studio Code extension. 

 When i try to Generate Deployment Script I get the following error:

*Error during deployment script generation: Error: API call to Consumption Resources failed: "The provided subscription identifier 'undefined' is malformed or invalid."*

![image](<https://github.com/user-attachments/assets/b6fe4bc7-99ce-4dd1-8c04-e4406fa3ff31>)

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

![logicappdeployment_error](<https://github.com/user-attachments/assets/98128b3f-e561-47be-b683-12dbe3faf9b3>)

### Browser 

N/A

### Additional context 

*No response*

**Comment by lambrianmsft** [comment]
@yasarqamar, 

In your local.settings.json of your logic app, is "WORKFLOWS_SUBSCRIPTION_ID" AND "WORKFLOWS_RESOURCE_GROUP_NAME" set?

**Comment by yasarqamar** [comment]
Hi, I realised I had incorrect values set in local settings json. I have since corrected them after which the above issue has resolved. Thanks.
