### ISSUE TITLE
Error during deployment script generation: Error: The deployment artifact file is missing

### ISSUE THREAD

**Issue by yasarqamar** [Azure/LogicAppsUX#5838]
### Describe the Bug with repro steps 

I have a logic app workspace on visual studio code and i'm following the tutorial here: [https://learn.microsoft.com/en-us/azure/logic-apps/automate-build-deployment-standard](<https://learn.microsoft.com/en-us/azure/logic-apps/automate-build-deployment-standard>)

When i try to 'Generate Deployment Scripts' all the connections are successfully retreived as deployment artifacts and unzipped.

However, I then get the below error:

![image](<https://github.com/user-attachments/assets/48bc9c7a-1f05-49ca-8edd-c89e263f39a1>)

It seems like the artifacts are not being created correctly

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

N/A

### Additional context 

*No response*

**Comment by lambrianmsft** [comment]
@yasarqamar,
Is the folder the connections are extracted in and the folder the Standard Resources API call is saying the files are missing in the same?

**Comment by yasarqamar** [comment]
Most likely it was due to multiple workspace sessions.
I managed to resolve this by creating a new Logic App Workspace on VSCode and then started from scratch.

**Comment by lambrianmsft** [comment]
@yasarqamar,
I would say that is not ideal to have to restart from scratch and not what we want our experience to be. Having multiple workspaces should not affect this and is an experience issue that we are trying to replicate. If you reopen the workspace that you encountered this in, do you get the same error? Was a new workspace session created and that was the one where it occurred in?
