### ISSUE TITLE
Managed API Connection created by Logic App Standard is not showing Authentication type as "Logic Apps Managed Identity"

### ISSUE THREAD

**Issue by aakanshaverma1310** [Azure/LogicAppsUX#5841]
### Describe the Bug with repro steps 

I'm trying to use List Blob (v2) (managed connector), i have managed identity enabled on logic app and have StorageBlobDataContributor role assigned on storage account for LA.

when i try to add managed connector and run the workflow, i get 403 forbidden.

```
{
   "status": 403,
   "message": "AuthorizationFailure\r\nclientRequestId: <>",
   "error": {
     "message": "AuthorizationFailure"
   },
   "source": ""
 }
```

Also,

On the overview page of managed API connection, i see managed identity as Authentication

but when i click Edit API Connection, then nothing is selected in Authentication Type option.

i cant even Logic Apps Managed Identity selected.

it is supposed to be auto populated after creating system-assigned managed identity connection in List Blob (V2) connector .

Have followed pre-requisites -

1. managed identity enabled on logic app 
2. StorageBlobDataContributor role assigned on storage account for LA. 

![Image](<https://github.com/user-attachments/assets/5f1d5082-1a4d-4a5a-98f8-575c07fec76b>)

![Image](<https://github.com/user-attachments/assets/1a86dad2-2b69-4e26-97c2-4c60e5eb4b2a>)

Any suggestions?

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by aakanshaverma1310** [comment]
@hartra344  - Can you please guide?

**Comment by preetriti1** [comment]
@aakanshaverma1310 - How did you create the connection? What connection type did you choose while creating the connection? Please share screenshots of what you chose and how it looked like in designer after you were in parameters tab?
ALso share the snippet of your connections.json of the managedAPiConnections section of this connection.
