### ISSUE TITLE
VS Code_Transform XML to JSON: Unable to fetch **liquid file** from both logic app and integration account even after adding the file.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5846]
### Describe the Bug with repro steps 

**Prerequisites:**

1\.Create an integration account or use existing integration account which is one time setup. Select the pricing tier as standard.

 a) To link integration account to logic app.

 b) In integration account's navigation menu, under Settings, select Callback URL.Find the Generated Callback URL property value, copy the value, and save the URL to use later for linking.

 c)On your logic app's navigation menu, under Settings, select Environment variables.On the Environment variables page, check whether the app setting named WORKFLOW\_INTEGRATION\_ACCOUNT\_CALLBACK\_URL exists.

 If the app setting doesn't exist, at the end of the settings list, add a new app setting by entering the following:

 "WORKFLOW\_INTEGRATION\_ACCOUNT\_CALLBACK\_URL":""

 d) In the Logic App, navigate to Artifacts > Maps, click on "Add", and upload a XSLT map.

 e) In the Integration account, navigate to Settings > Maps, click on "Add", and upload a XSLT map.

2\.Open the designer and incorporate an HTTP request trigger.

 3\.Insert a Transform XML to JSON action. 

 4\.For the content you wish to transform, add the code 

 " active 10 "(add without inverted commas).

5. Set the Source to Logic App/Integration account. 
6. For the Name, select the SimpleXmlToJsonTemplateWithOneChild liquid file that has been uploaded to the Logic App/Integration account 

**Expected:** Should able to fetch **SimpleXmlToJsonTemplateWithOneChild.liquid file** from both logic app and integration account after adding the file .

**Actual:** Unable to fetch **SimpleXmlToJsonTemplateWithOneChild.liquid file** from both logic app and integration account even after adding the file.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/12df6fa5-aed9-446c-8736-89b767e0b808>)

![Image](<https://github.com/user-attachments/assets/a4466ecf-f0f2-4785-b6e4-12fa6b893013>)

Integration account which linked

![Image](<https://github.com/user-attachments/assets/81f038e7-9d85-4c39-8cf3-2b4e23853cdf>)

### Browser 

VS Code

### Additional context 

**VSIX Version:** 4\.96.0

**Comment by ccastrotrejo** [comment]
Hi @vgouth I took a look at this issue and it seems that the action in the logic app that you are using for the test is not the right one. I double checked the test case in the test suite.
The action that you are using is the "Transform XML" from the "XML Operations" connector.
The action that is needed it the "Transfrom XML to JSON" from the "Liquid Operations" connector. 

I was able to fetch the liquid files from the Logic App and from the Integration account with the right action
![Image](https://github.com/user-attachments/assets/a4acb78c-b4cb-40e3-b787-149c9c1003ac)
![Image](https://github.com/user-attachments/assets/647d74fc-eb5f-4c7a-977f-895e9816bf8a)

Please let me know if I am wrong, and then I can reopen the issue

**Comment by vgouth** [comment]
@ccastrotrejo Thank you for the clarification. I was able to fetch the values. Apologies for the wrong action selected.

**Comment by ccastrotrejo** [comment]
Absolutely, no worries at all. I am glad it got solved this way
