### ISSUE TITLE
Logic apps standard from visual studio code running locally in debug mode

### ISSUE THREAD

**Issue by akhanna007** [Azure/LogicAppsUX#5852]
Does this occur consistently? 

 Repro steps:

1\.

 2\.

Action: azureLogicAppsStandard.pickProcess

 Error type: Error

 Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureLogicAppsStandard.pickProcessTimeout" setting.

Version: 4.85.3

 OS: win32

 OS Release: 10.0.22631

 Product: Visual Studio Code

 Product Version: 1.94.1

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
Hi @akhanna007 thanks for raising this issue. It looks like the logic app is indeed not getting attached to the functions process.

- Do you see if the `functions` process is indeed running or exists?
- Does the process runs fine without debug mode?
