### ISSUE TITLE
Run history: Issue with loading Raw inputs and Raw outputs, as it's displaying an error message.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5855]
### Describe the Bug with repro steps 

1. Install on premises data gateway. 
2. create a on premises data gateway using azure portal with same location that gateway is installed. 
3. Create a logic app with same location that gateway is created. 
4. Open designer 
5. Add File system - When a file is created (properties only) trigger. 
6. create a new connection. 
7. Give connection name, root folder path, username and password. 
8. Select gateway subscription where gateway is created. 
9. click on create a new connection 
10. select the token from token picker. 
11. Add compose action and select list of file names taken from token picker. 
12. Save and run the workflow 
13. Now add a file in the provider root folder path. 
14. Run will get success. 
15. Open run to see Raw inputs and Raw outputs. 

**Expected:** Should able to see Raw inputs and Raw outputs

**Actual:** Unable to see Raw inputs and Raw outputs. It is showing an error.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/c18421eb-7163-42af-8560-f01ab730c482](<https://github.com/user-attachments/assets/c18421eb-7163-42af-8560-f01ab730c482>)

![Image](<https://github.com/user-attachments/assets/b674c027-89c3-4823-91ca-d8e5e480d172>)

### Browser 

Edge

### Additional context 

**Version:** 2\.41007.1.5

**Comment by ccastrotrejo** [comment]
Hi @vgouth, I tried to repro this issue with the `lap-gateway-goutham-10102024` logic app but it seems that the connection for the trigger isn't set up anymore. Is there any chance you can setup the connection and run it again, therefore I can take another look at it?

I tried with a previous logic app `lap-gateway-goutham-30092024` and I was able to see the raw outputs blade.

**Comment by vgouth** [comment]
Hello @ccastrotrejo . Now I was able to view monitoring view with same run and same logic app. I guess was a transient issue or something went wrong.

![Image](https://github.com/user-attachments/assets/92b898e0-2191-42b9-939f-1a0e3a1cc14b)

**Comment by ccastrotrejo** [comment]
Sounds good, I will close this issue for now, however if this keeps happening we can reopen and take a further look on this
