### ISSUE TITLE
Error from "Deploy to Logic app"

### ISSUE THREAD

**Issue by DonBenci** [Azure/LogicAppsUX#5867]
Does this occur consistently? 

 Repro steps:

1\.

 2\.

Action: azureLogicAppsStandard.deploy

 Error type: TypeError

 Error Message: Cannot read properties of undefined (reading 'kind')

Version: 4.85.3

 OS: darwin

 OS Release: 23.1.0

 Product: Visual Studio Code

 Product Version: 1.94.1

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
Hi @DonBenci thanks for raising this issue. 
- Is there any way you can give us more information and the steps on how this is happening?
- Is this happening after your selected the remote logic app to deploy to? or after you created a new logic app?
