### ISSUE TITLE
Logic Apps created via VS Code Extension try to create the associated AppInsights resources with Classic resource mode

### ISSUE THREAD

**Issue by lgiuliani80** [Azure/LogicAppsUX#5870]
Does this occur consistently? YES

 Repro steps:

1. Create a new Logic App Resource via the "Deploy to Logic App" command 

Action: azureLogicAppsStandard.deploy

 Error type: Error

 Error Message: Error in creating logic app. RestError: Region doesn't support Classic resource mode for Application Insights resources. Please use Workspace-based mode.

Version: 4.85.3

 OS: win32

 OS Release: 10.0.22631

 Product: Visual Studio Code

 Product Version: 1.94.2

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
Hi @lgiuliani80 thanks for rasising this issue, I haven't seen any error like this before. I will triage it with the team.
- Do you select any specific region while trying to deploy your logic app?

**Comment by lgiuliani80** [comment]
The selected region is "Italy North".

**Comment by ccastrotrejo** [comment]
Hi @lgiuliani80 After some research I found out that App Insights Teams deprecated the Classic resource mode. You might need to move out or migrate it to Workspace base mode, here is a link that can be helpful
https://azure.microsoft.com/en-us/updates/we-re-retiring-classic-application-insights-on-29-february-2024/

I have a couple of questions
- Did you create the App Insight a long time ago? or did you created it while creating the Logic App?
- If you created it while creating the logic app, could you please share the steps you followed?

**Comment by lgiuliani80** [comment]
I think there is a misunderstanding. I know perfectly that the Classic resource mode was deprecated long time ago. What I'm saying is that the feature makes the plugin CREATE resources on Azure is _unaware_ of that change and still tried to create AppInsights resources with Classic resource mode.
![Image](https://github.com/user-attachments/assets/8b486341-b255-4696-9be8-c3aed780e6a9)
![Image](https://github.com/user-attachments/assets/d05d3df9-7b4b-4763-b281-3bce6078765e)
