### ISSUE TITLE
New Designer truncates JSON Schema when switching from old to new designer

### ISSUE THREAD

**Issue by DP-NTT-AU** [Azure/LogicAppsUX#5877]
### Describe the Bug with repro steps 

1. Take LogicApp flow that has a parse json action with associated schema previously written with old designer. 
2. Open flow in default new designer 
3. open parse json action and review schema Display, schema appears truncated, code view shows the full JSON schema. 
4. switch back to old designer and JSON Schema appears fully intact and can be copied/paste. 
5. switch back to new designer and JSON schema is truncated again. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/8f0e5fab-239d-4188-a506-108c16d6b9bf>)

![Image](<https://github.com/user-attachments/assets/369636fc-72a2-43f9-a908-d8da21648814>)

### Browser 

microsoft Edge Version 129.0.2792.89 (Official build) (64-bit)

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
@DP-NTT-AU  thanks for reporting this, I wasn't able to reproduce this on my end, would you happen to be able to give me a copy of your schema and I can see if this is happening specifically for this JSON?

**Comment by DP-NTT-AU** [comment]
> [@DP-NTT-AU](https://github.com/DP-NTT-AU) thanks for reporting this, I wasn't able to reproduce this on my end, would you happen to be able to give me a copy of your schema and I can see if this is happening specifically for this JSON?

Hi @Eric-B-Wu , thanks for your response. I was a little nervous to just cut/paste the schema back in to the Parse JSON action, not being an expert by any means, however I did and that has fixed the issue. so possible there may have been a 'hidden' character in the original schema that did not upset the olde designer, but does affect the new designer. I will close this issue now. I do have some other anomalous issues with the new designer but will work through those and raise an issue if needed. thank you again.

The fix for this issue was to recreate the schema in the new designer and save.

**Comment by Eric-B-Wu** [comment]
> > [@DP-NTT-AU](https://github.com/DP-NTT-AU) thanks for reporting this, I wasn't able to reproduce this on my end, would you happen to be able to give me a copy of your schema and I can see if this is happening specifically for this JSON?
> 
> Hi [@Eric-B-Wu](https://github.com/Eric-B-Wu) , thanks for your response. I was a little nervous to just cut/paste the schema back in to the Parse JSON action, not being an expert by any means, however I did and that has fixed the issue. so possible there may have been a 'hidden' character in the original schema that did not upset the olde designer, but does affect the new designer. I will close this issue now. I do have some other anomalous issues with the new designer but will work through those and raise an issue if needed. thank you again.
> 
> The fix for this issue was to recreate the schema in the new designer and save.

glad that seemed to fix your issue, and yep if there are any other issues you are facing in the new designer feel free to open another issue and we will look to address
