### ISSUE TITLE
Issue with the output of dynamic inputs in nested for each loops

### ISSUE THREAD

**Issue by Gopikrish25** [Azure/LogicAppsUX#5883]
### Describe the Bug with repro steps 

1. Two for each loops to read an element in nested array 
2. Try inputting a dynamic value from parent array [for each] in any action added in the child array [for each\_2]. 

Result: When Logic App is run the dynamic inputs coming from parent array/for each loop are returned as 'null'

This issue is reproducible only in the new designer and the current woraround it to use the legacy designer when inputting the above dynamic inputs.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
@Gopikrish25 are you seeing the null being gotten from the parent happening on the run history blade? If possible could you provide a screenshot or recording of this happening?

**Comment by Gopikrish25** [comment]
@Eric-B-Wu  Yes, currently we mitigated this issue for now and we will not be able to repro it to provide you with more info.
