### ISSUE TITLE
Dataverse connector encoding organization URL causing connection to fail

### ISSUE THREAD

**Issue by matemora** [Azure/LogicAppsUX#5907]
### Describe the Bug with repro steps 

1. Create new logic app 
2. Add dataverse connector (example: list rows) 
3. Try to run (connection unsuccessful) - checking cause of error show the environment has "/" and ":" encoded (from https://) 
4. Check code view, the organization is set to `"organization": "@{encodeURIComponent(encodeURIComponent('https://pharmacy.crm.dynamics.com'))}"` 

**Temporary fix:** edit the connector in the code view to have only the URL, like [https://pharmacy.crm.dynamics.com](<https://pharmacy.crm.dynamics.com>) in the example above.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

MacOS

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

{

 "definition": {

 "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",

 "actions": {

 "For\_each": {

 "actions": {

 "Update\_a\_row": {

 "inputs": {

 "body": {

 "abt\_name": "@join(createArray(item()?['abt\_Client']['name'],substring(replace(item()?['abt\_referencedate'],'-',''),1, 6)),' - ')"

 },

 "headers": {

 "accept": "application/json;odata.metadata=full",

 "organization": "@{encodeURIComponent(encodeURIComponent('https://pharmacy.crm.dynamics.com'))}",

 "prefer": "return=representation,odata.include-annotations=*" }, "host": { "connection": { "referenceName": "commondataservice-1" } }, "method": "patch", "path": "/api/data/v9.1/@{encodeURIComponent(encodeURIComponent('abt\_enrollmentcountentries'))}(@{encodeURIComponent(encodeURIComponent(item()?['abt\_enrollmentcountentryid']))})" }, "type": "ApiConnection" } }, "foreach": "@body('List\_rows')?['value']", "runAfter": { "List\_rows": [ "SUCCEEDED" ] }, "type": "Foreach" }, "List\_rows": { "inputs": { "headers": { "accept": "application/json;odata.metadata=full", "organization": "@{encodeURIComponent(encodeURIComponent('https://pharmacy.crm.dynamics.com'))}", "prefer": "odata.include-annotations=*"

 },

 "host": {

 "connection": {

 "referenceName": "commondataservice-1"

 }

 },

 "method": "get",

 "path": "/api/data/v9.1/@{encodeURIComponent(encodeURIComponent('abt\_enrollmentcountentries'))}",

 "queries": {

 "$expand": "abt\_Client($select=name)"

 }

 },

 "runAfter": {},

 "type": "ApiConnection"

 }

 },

 "contentVersion": "1.0.0.0",

 "outputs": {},

 "triggers": {

 "Recurrence": {

 "recurrence": {

 "frequency": "Month",

 "interval": 1

 },

 "type": "Recurrence"

 }

 }

 },

 "kind": "Stateful"

 }

### Screenshots or Videos 

*No response*

### Browser 

- Browser: chrome 

### Additional context 

it doesn't affect previously created logic apps, seems to be a recent problem that is generating the wrong configuration for new logic apps.

**Comment by ccastrotrejo** [comment]
Hi @matemora thanks for raising this issue. We made a new release this week, which intends to have the fix for this issue. 

Could you please follow the guide to [Find your session ID or portal extension version](https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#finding-your-session-id-or-portal-extension-version), and lets us know you `Microsoft_Azure_EMA` version?

The version with the intended fix should be `2.41007.1.13`

Related to https://github.com/Azure/LogicAppsUX/pull/5911

**Comment by ccastrotrejo** [comment]
This should be fixed by now.
