### ISSUE TITLE
Getting settingValue.startsWith is not a function while trying to open Designer

### ISSUE THREAD

**Issue by azharmunir-smf** [Azure/LogicAppsUX#5919]
Does this occur consistently? Yes

 Repro steps:

1. Just open the logic app project in VSCode and try to open the designer 

Action: azureLogicAppsStandard.openDesigner

 Error type: TypeError

 Error Message: settingValue.startsWith is not a function

Version: 4.96.2

 OS: darwin

 OS Release: 23.6.0

 Product: Visual Studio Code

 Product Version: 1.94.2

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by rllyy97** [comment]
Hi @azharmunir-smf, This issue was fixed in version 4.98.0, you should be able to update your VSCode extension to something past 4.98.0 to see this fixed 👍
