### ISSUE TITLE
Inconsistency in workflow between Web designer and VS Code extension (when using Azure Key Vault)

### ISSUE THREAD

**Issue by jkgwnne** [Azure/LogicAppsUX#5926]
### Describe the Bug with repro steps 

I am developing an Azure Logic App workflow in VS Code using the 'Azure Logic Apps (Standard)' extension. Upon pushing changes to Azure DevOps Repos it will update the online Logic App on Azure. My problem arises when trying to use the 'Azure Key Vault (Get Secret)' action:

If I add the action in VS Code, it adds it to workflow.json as type 'ServiceProvider', which is rejected by the ARM template when running the pipeline. In the end, I added the actions manually in Azures web designer, copied the code from the 'code view' tab, pasted it into VS Codes workflow.json (see snippet), and pushed that. This worked, however, the Logic App extension in VS does not recognize this action (see image).

Therefore, there is (1) an inconsistency in the code the web editor and the VS Code extension creates the code, and (2) the VS Code extension does not recognize code generated by the web editor.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```JSON
"Get_graph_secret": {

 "inputs": {

 "host": {

 "connection": {

 "name": "@parameters('$connections')['keyvault']['connectionId']"

 }

 },

 "method": "get",

 "path": "/secrets/@{encodeURIComponent('OnboardProjectMember-GraphSecret')}/value"

 },

 "runAfter": {},

 "type": "ApiConnection"

 },

 "Get_password": {

 "inputs": {

 "host": {

 "connection": {

 "name": "@parameters('$connections')['keyvault']['connectionId']"

 }

 },

 "method": "get",

 "path": "/secrets/@{encodeURIComponent('SandboxFictoriousPassword')}/value"

 },

 "runAfter": {

 "Get_graph_secret": ["Succeeded"]

 },

 "type": "ApiConnection"

 }
```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/3192a5d6-23fd-4272-aae7-4eec203514af>)

### Browser

Edge

### Additional context

VS Code Version: 1.94.2 (user setup)

Azure Logic Apps (Standard) Version: 2.0.16

In case it is relevant: It is a Consumption Logic App

**Comment by ccastrotrejo** [comment]
Hi @jkgwnne thanks for raising this issue. 
Our vscode extension doesn't support the creation, authorization, and deployment of Consumption Logic Apps, this extension is only for Standard Logic Apps. The reason on why the type of the `Get Secret` action is different is because there are some types of actions that are available in Standard Logic Apps, whereas some aren't in consumption. Also the structure/schema of the actions differ from each other
