### ISSUE TITLE
"When a new email arrives (V3)" not being seen as valid trigger

### ISSUE THREAD

**Issue by jasparm** [Azure/LogicAppsUX#5929]
### Describe the Bug with repro steps 

When "When a new email arrives (V3)" is set as trigger then multiple initialize variable actions are added serially, then changed in settings to run after the email trigger so they run parallel, the email trigger is no longer seen as valid. This does not happen when actions are added using the "add parallel branch" option, only when they are added serially and then changed to all be dependents on the trigger.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

{

 "definition": {

 "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",

 "contentVersion": "1.0.0.0",

 "triggers": {

 "When\_a\_new\_email\_arrives\_(V3)": {

 "type": "ApiConnectionNotification",

 "inputs": {

 "host": {

 "connection": {

 "name": "@parameters('$connections')['office365']['connectionId']"

 }

 },

 "fetch": {

 "pathTemplate": {

 "template": "/v3/Mail/OnNewEmail"

 },

 "method": "get",

 "queries": {

 "importance": "Any",

 "fetchOnlyWithAttachment": false,

 "includeAttachments": false,

 "folderPath": "Inbox"

 }

 },

 "subscribe": {

 "body": {

 "NotificationUrl": "@listCallbackUrl()"

 },

 "pathTemplate": {

 "template": "/GraphMailSubscriptionPoke/$subscriptions"

 },

 "method": "post",

 "queries": {

 "importance": "Any",

 "fetchOnlyWithAttachment": false,

 "folderPath": "Inbox"

 }

 }

 },

 "splitOn": "@triggerBody()?['value']"

 }

 },

 "actions": {

 "Initialize\_variable": {

 "type": "InitializeVariable",

 "inputs": {

 "variables": [

 {

 "name": "ff",

 "type": "boolean"

 }

 ]

 },

 "runAfter": {}

 },

 "Initialize\_variable\_1": {

 "type": "InitializeVariable",

 "inputs": {

 "variables": [

 {

 "name": "aa",

 "type": "boolean"

 }

 ]

 },

 "runAfter": {}

 },

 "Initialize\_variable\_2": {

 "type": "InitializeVariable",

 "inputs": {

 "variables": [

 {

 "name": "sa",

 "type": "boolean"

 }

 ]

 },

 "runAfter": {

 "When\_a\_new\_email\_arrives\_(V3)": [

 "SUCCEEDED"

 ]

 }

 }

 },

 "outputs": {},

 "parameters": {

 "$connections": {

 "type": "Object",

 "defaultValue": {}

 }

 }

 },

 "parameters": {

 "$connections": {

 "value": {

 "office365": {

 "id": "/subscriptions/9536a98c-a8c9-470f-bf4d-be12edb39300/providers/Microsoft.Web/locations/australiasoutheast/managedApis/office365",

 "connectionId": "/subscriptions/9536a98c-a8c9-470f-bf4d-be12edb39300/resourceGroups/rg-pentana-ai-backoffice/providers/Microsoft.Web/connections/office365-2",

 "connectionName": "office365-2"

 }

 }

 }

 }

 }

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/2035a8a1-b5f1-49cb-881b-1d6171bdff98>)

![Image](<https://github.com/user-attachments/assets/b5013a92-93e6-4285-b7ac-3d6ed800ab20>)

![Image](<https://github.com/user-attachments/assets/baad8996-253d-41d0-801e-4c803f7de1d4>)

[portal.azure.com-1729552745010.log](<https://github.com/user-attachments/files/17467721/portal.azure.com-1729552745010.log>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
@jasparm Thank you for the issue report!  It looks like our run after setting is being incorrectly set when pointing to a trigger.
If an action is meant to run after a trigger, the `runAfter` property should be set to an empty object `{}`.
Instead we are defining it like we would an action, which is incorrect and what we're seeing here.
I will work on a fix and update the issue once it is completed.
