### ISSUE TITLE
Run History page isn't responding when actions' input/output size is large

### ISSUE THREAD

**Issue by jesseck3013** [Azure/LogicAppsUX#5938]
### Describe the Bug with repro steps 

Run History page isn't responding when actions' input/output size is large, especially the Compose action.

For example, this workflow reads 8 mb data from blob storage, and composes it in a json.

![Image](<https://github.com/user-attachments/assets/67fe42fd-6c81-413e-9fab-ad8dfa2d339b>)

After the unresponding alert shows up, the designer will crash.

![Image](<https://github.com/user-attachments/assets/d515f9cb-f447-4823-bd5f-33d25ba5c09c>)

Previously, actions do not render large size input/ouput. They only render a button to open the full input/output on another page.

![Image](<https://github.com/user-attachments/assets/a956c03d-593c-4ea4-9816-a4c7ffb6e0f6>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

- Browser: [Edge, Chrome] 

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Related to https://github.com/Azure/LogicAppsUX/pull/5739
