### ISSUE TITLE
Intermittent `Unable to initialize operation details for swagger based operation` error message on OPDG-based actions in the run history

### ISSUE THREAD

**Issue by TWolversonReply** [Azure/LogicAppsUX#5939]
### Describe the Bug with repro steps 

Viewing the run history for a workflow using the OPDG filesystem connector, the run history is at random made unusable by the below error message:

![Image](<https://github.com/user-attachments/assets/c00e7eb0-0819-4591-987e-26a20532efd5>)

I was only able to retrieve the full error message by inspecting the text element in the developer console and there is no way to see it otherwise. This reads:

> Unable to initialize operation details for swagger based operation - List\_files\_in\_folder. Error details - The provided subscription identifier '@appsetting('WORKFLOWS\_SUBSCRIPTION\_ID')' is malformed or invalid.

There is nothing wrong with `WORKFLOWS_SUBSCRIPTION_ID`, it exists and the value is correct. This problem is intermittent, the workflow works perfectly for a while, exhibits this error which prevents any further development by making it impossible to view run history, and then goes away without having changed anything.

I have noticed an incorrect outbound request in the console:

![Image](<https://github.com/user-attachments/assets/9bdc1fc5-d036-477c-83f2-1c26ade8115d>)

This has the unsubstituted appsetting references embedded in the URL, which suggests this has been pulled from the connections.json and used unmodified by some part of the tooling, which is obviously not correct.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

Various, with different OPDG-based actions, parameterised according to [https://techcommunity.microsoft.com/t5/azure-integration-services-blog/parameterizing-managed-connections-with-logic-apps-standard/ba-p/3660679](<https://techcommunity.microsoft.com/t5/azure-integration-services-blog/parameterizing-managed-connections-with-logic-apps-standard/ba-p/3660679>)

### Screenshots or Videos 

*No response*

### Browser 

Chrome Version 129.0.6668.101 (Official Build) (64-bit)

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @TWolversonReply thanks for raising this issue, is this just happening in monitoring view or also in normal designer view when you modify the workflow?
I was able to only repro it in monitoring view

**Comment by ccastrotrejo** [comment]
It seems that we are not resolving the references when loading monitoring view. I will work on making a fix

**Comment by billchesnut** [comment]
we are having the same issue, it is fine in the designer, fails in run history

**Comment by rllyy97** [comment]
Hi @TWolversonReply / @billchesnut / @serenaliqing, we have received a few reports of this issue and have created a parent ticket here that you can use to track progress: https://github.com/Azure/LogicAppsUX/issues/5977

**Comment by serenaliqing** [comment]
Thank you for the kind investigation Team. We're looking forward to your fix this week.
