### ISSUE TITLE
Dataverse connector - can't use custom Parameter for Environment

### ISSUE THREAD

**Issue by rikdekoning** [Azure/LogicAppsUX#5940]
### Describe the Bug with repro steps 

1. Create new Logic App 
2. Create new string parameter 'Environment' with the environment URL (e.g. [https://org12345678.crm4.dynamics.com/](<https://org12345678.crm4.dynamics.com/>)) as Value 
3. Add Dataverse trigger 'When a row is added, modified or deleted' 
4. Select newly create parameter 'Environment' for Environment 
5. Configure rest of the trigger (*tables appear, so environment URL is correct*) 
6. Add another action (*doesn't matter which*) 
7. Save Logic App and add/modify a record in your selected Dataverse table 
8. Logic App won't trigger 

When you look at the code view, the organization attribute of the trigger is set to "@{encodeURIComponent(encodeURIComponent(parameters('Environment')))}". This will replace all special URL characters (':', '/') with unicode characters. In our example, it becomes 'https%253A%252F%252Forg12345678.crm4.dynamics.com%252F' It seems like the Logic App doesn't understand the outcome of this. If you remove the double EncodeURIComponent() expression from the code view and save the Logic App, it will work again.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @rikdekoning thanks for raising this issue. We made a new release this week, which intends to have the fix for this issue. 

Could you please follow the guide to [Find your session ID or portal extension version](https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#finding-your-session-id-or-portal-extension-version), and lets us know you `Microsoft_Azure_EMA` version?

The version with the intended fix should be `2.41007.1.13`

**Comment by rikdekoning** [comment]
Hi @ccastrotrejo , thanks for your reply. It looks like it has been fixed in the 2.41007.1.13 version!

**Comment by ccastrotrejo** [comment]
Thanks for confirming
