### ISSUE TITLE
Unable to initialize operation (Azure Data Explorer Connector) - Run History

### ISSUE THREAD

**Issue by alapinsk** [Azure/LogicAppsUX#5947]
### Describe the Bug with repro steps 

While inspecting the execution of the workflow using Azure Portal, 

 Azure Data Explorer task have an issue "Unable to initialize operation"

![Image](<https://github.com/user-attachments/assets/09c425b2-efaa-440f-8b91-f976352474f1>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome and Edge

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @alapinsk thanks for raising this issue, could you please confirm if connection for that action is using some sort of parameterization in the connection id? Something like this `'@appsetting('WORKFLOWS_SUBSCRIPTION_ID')' `?

Also does this also happens in designer view?
