### ISSUE TITLE
Designer changes actual Logic App workflow code

### ISSUE THREAD

**Issue by sergiuatfwf** [Azure/LogicAppsUX#5949]
### Describe the Bug with repro steps 

For a Logic App:

1. Click on 'Automation \ Export Template' 
2. View the code 
3. Click on 'Overview \ Edit' 
4. Switch to 'Code view' 
5. View the code 

For some sections, the code in the Edit (designer or code view) is different than the actual code of the Logic App and the code that is executed.

 It seems that the Editor validates and changes the code somehow.

Example:

 Export template (section):

![Image](<https://github.com/user-attachments/assets/2e53ddac-9d2a-4105-abc5-6536bba38e69>)

Now, same section, in the Edit \ Code view screen:

![Image](<https://github.com/user-attachments/assets/edfc805a-4028-4a2e-984c-5051c3681ba9>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

Example:

 Export template (section):

![Image](<https://github.com/user-attachments/assets/2e53ddac-9d2a-4105-abc5-6536bba38e69>)

Now, same section, in the Edit \ Code view screen:

![Image](<https://github.com/user-attachments/assets/edfc805a-4028-4a2e-984c-5051c3681ba9>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
This is somewhat expected behavior, the code view you're seeing in the designer code editor is deterministically compiled using designer. The other code views outside of designer just use the file currently stored on the backend. This is how we allow you to edit code for a workflow that hasn't been saved yet. However this means that if you edit the code somewhere other than designer(or even potentially using the old designer in some places) then the code you see here and the non designer code view may be different.

**Comment by sergiuatfwf** [comment]
I'm not sure I can agree.

If I have a working Logic App which was designed with the classic editor and executes properly, I don't realy want the new editor to change the Logic App code upon opening it.
I don't want it to rename some action name or remove variable assignments without event telling me what is wrong in my logic app definition.

The fact that the designer implements different rules than the execution / runtime / deployment (via bicep) is worrying for me.

**Comment by hartra344** [comment]
You can think of what the designer does as being the same as a code compiler. Different compilers may compile down to different exact bits, but are functionally the same. If somehow the designer is changing your action names are variable initialization then yes that’s a bug however, if it’s simply changing The order of things or functionally equivalent replacements of how it’s defined then that’s not a bug.

**Comment by influential-eliot** [comment]
Sorry, but when you are talking about a production resource like this ... "_Somewhat expected_" is not "_expected_" behaviour, @hartra344 . :(
 
The designer is literally breaking processes that are relied upon (and, yes, they have backups/reporting/etc) in production ... simply by saving a completely unrelated change.
