### ISSUE TITLE
storage accoutn name or endpoint issue

### ISSUE THREAD

**Issue by achan-msft** [Azure/LogicAppsUX#5954]
### Describe the Bug with repro steps 

In Azure Logic app, I tried to create an action that creates a blob. I already had my azure blob storage account and added a container. I connected to my storage account using managed identity and also SAS. Neither one seemed to work at all. When I say it didn't work, I mean the container that I added can't be located.

The screenshot I attached shows the storage account name. I tried to put the account name but it never worked regardless of what authentication approach I use.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/bb2a4adb-8620-4ab7-821a-5af4de0b3786>)

### Browser 

chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
@achan-msft Would you mind collecting console + network logs and sending them to me at rileyevans@microsoft.com?
It sounds like your dynamic data isn't loading and the network logs should tell us as to why.
You can find info on collecting logs from our docs site here: https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#collecting-console-errors
