### ISSUE TITLE
"The provided subscription identifier '@{appsetting('workflows_subscription_id')}' is malformed or invalid

### ISSUE THREAD

**Issue by GordonHo-IPG** [Azure/LogicAppsUX#5962]
### Describe the Bug with repro steps 

In viewing the workflow result in Overview, it shows error "Unable to initialize operation …. 

 but it works OK in the designer view.

 Following is the error log from the console, it seems that the variable workflows\_subscription\_id is not substituted in the overview page.

![Image](<https://github.com/user-attachments/assets/9fc05194-689a-46e0-b7ae-b64ab92d86e9>)

---

When i come to Designer View (No issue)

![Image](<https://github.com/user-attachments/assets/ab644cc9-0d54-4101-a4fb-f844fa64437e>)

Session ID: c051a968d9a5459c809e8a9060630f3a

 HubsExtension: 105ms \| Version: 14.219.0.1649509452.241016-2253

 Microsoft\_Azure\_EMA: 225ms \| Version: 2.41007.1.13

 WebsitesExtension: 18ms \| Version: 5.245.1.3

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/b656c2bf-6907-4699-888b-642bf9019648>)

![Image](<https://github.com/user-attachments/assets/bfff7ec7-153f-49ea-af2c-162d25ad386a>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @GordonHo-IPG thanks for raising this issue I will close it as duplicate to https://github.com/Azure/LogicAppsUX/issues/5939
