### ISSUE TITLE
Steps that make use of API Connections show "Unable to initialize operation"

### ISSUE THREAD

**Issue by las3r** [Azure/LogicAppsUX#5963]
### Describe the Bug with repro steps 

I have a couple of steps in my logic app that are using API Connections (Microsoft.Web/connections):

1) Keyvault connection (get secret)

2) Event grid connection (trigger for logic apps)

In the old designer these would load, and I would be able to change the steps. In the new designer every step that utilizes an API connection shows the following:

Event hub trigger:

![Image](<https://github.com/user-attachments/assets/1adabe5d-2e75-4e24-946c-524286827518>)

Keyvault "get secret" step:

![Image](<https://github.com/user-attachments/assets/fa062aae-f382-4e01-b011-6062ff762663>)

The request I see it making a few calls when the page loads to:

`GET https://management.azure.com/subscriptions/&amp;amp;amp;lt;subscription&amp;amp;amp;gt;/providers/Microsoft.Web/locations/westeurope/apiOperations?%24top=5000&amp;amp;amp;amp;%24skiptoken=10000&amp;amp;amp;amp;%24filter=type%20eq%20%27Microsoft.Web%2flocations%2fmanagedApis%2fapiOperations%27%20and%20properties%2fintegrationServiceEnvironmentResourceId%20eq%20null&amp;amp;amp;amp;api-version=2018-07-01-preview`

The response to this call is:

```
{ 
value: []
}
```

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```JSON
{
  "When_a_CustomerCaseUpdate_event_occurs": {
    "splitOn": "@triggerBody()",
    "splitOnConfiguration": {
      "correlation": {
        "clientTrackingId": "@coalesce(triggerBody()?['id'], guid())"
      }
    },

    "type": "ApiConnectionWebhook",
    "inputs": {
      "body": {
        "properties": {
          "destination": {
            "endpointType": "webhook",
            "properties": {
              "endpointUrl": "@{listCallbackUrl()}"
            }
          },
          "filter": {
            "includedEventTypes": [
              "CustomerCase"
            ]
          },
          "topic": "@concat(parameters('subscriptionId'), '/resourceGroups/', parameters('infra').environment.resourceGroup, '/providers/Microsoft.EventGrid/domains/', parameters('infra').eventGrid.name)"
        }
      },
      "host": {
        "connection": {
          "name": "@parameters('$connections')['azureeventgrid']['connectionId']"
        }
      },
      "path": "@concat(parameters('subscriptionId'), '/providers/Microsoft.EventGrid.Domains/resource/eventSubscriptions')",
      "queries": {
        "x-ms-api-version": "2017-09-15-preview"
      }
    }
  }
}
```

### Screenshots or Videos

*No response*

### Browser

Edge, Chrome

### Additional context

- There are no 500's in the network tab 
- There are no console errors. 
- This worked fine in the old designer/

**Comment by rllyy97** [comment]
Hi @las3r, thank you for reporting this issue, we have received a few reports of this issue and have created a parent ticket here that you can use to track progress: https://github.com/Azure/LogicAppsUX/issues/5977

**Comment by ccastrotrejo** [comment]
Hi @las3r I wasn't able to repro it yet. 
- Is there any chance we can get your workflow json schema from your logic app? It seems that the one posted above its just from the trigger. You can share it with me to my email ccastrotrejo@microsoft.com

Usually this error ` "message": "Unable to initialize operation details for swagger based operation - When_a_CustomerCaseCommentUpdate_event_occurs. Error details - Operation Id cannot be determined from definition and swagger",`  gets thrown when there isn't a match between the action id and the actions we get from the connector swagger.

**Comment by ccastrotrejo** [comment]
Thanks I just received it. Will let you know if I need something else or if I find anything going on

**Comment by ccastrotrejo** [comment]
@las3r Just replied back via email.

**Comment by las3r** [comment]
I have just replied to @ccastrotrejo. Seems the new designer doesn't really like the way we provide the "path" parameter to API connection-based logic app actions. We're getting closer!

**Comment by ccastrotrejo** [comment]
Hi @las3r I replied to your email, could you please try the scenarios I stated on the email. Thanks!

**Comment by ccastrotrejo** [comment]
Hi @las3r as discussed on the email thread, the way you are parameterizing the path in the action is not ideal. I tested it in old designer and doesn't seem to work either. Could you please give it a try in the old designer and confirm it works with this private url?
https://aka.ms/lafallback
