### ISSUE TITLE
azure logic apps Invalid connection, please update your connection to load complete details

### ISSUE THREAD

**Issue by perodriguezstb** [Azure/LogicAppsUX#5964]
### Describe the Bug with repro steps 

The logic app is working but it shows an error:

"azure logic apps Invalid connection, please update your connection to load complete details"

I noticed the "connected to" connection name differs from ![Image](<https://github.com/user-attachments/assets/456eafda-ff5e-4850-9ffb-1c97ea5cd7d4>)

![Image](<https://github.com/user-attachments/assets/3f3aab42-a8b6-4259-a769-26d8080a780b>)

 what shows in the Code View tab. (attached)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @perodriguezstb , thank you for reporting this issue, we have received a few reports of this issue and have created a parent ticket here that you can use to track progress: https://github.com/Azure/LogicAppsUX/issues/5977

**Comment by rllyy97** [comment]
Hi @perodriguezstb, thank you for reporting your issue, could you please gather console and network logs from you loading the workflow, opening the action, and clicking the "change connection" button?
You can send the logs to me directly at rileyevans@microsoft.com
If you need help gathering the logs we have documentation to help you here: https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#collecting-console-errors
