### ISSUE TITLE
Logic Apps Monitoring view - Unable to initialize operation

### ISSUE THREAD

**Issue by rllyy97** [Azure/LogicAppsUX#5977]
## What is the issue? 

On the Logic Apps monitoring view / when opening a workflow run, users may see some actions fail to initialize, showing an error message like the following:

> "Unable to initialize operation …"

This should happen on operations that have connections with app settings values.

 We know why this is happening, but we are still looking into what change might have caused this all of a sudden.

## What is being done to fix it? 

We are currently working on a fix for the issue and are expecting to release it in a hotfix sometime this week.

 Thank you for your patience as we work to get this resolved!

**Comment by billchesnut** [comment]
Do you have any updates on this? It is starting to really impact my development efforts because I am working inside a VNET.

**Comment by ccastrotrejo** [comment]
Hey @billchesnut yes, we have made the fix for this issue, and we have started the rollout of it. As for now could you please use this private link for portal, this environment should contain the fix for it? [Azure Stage 1](https://ms.portal.azure.com/?feature.canmodifystamps=true&Microsoft_Azure_EMA=stage1#home)

**Comment by billchesnut** [comment]
thanks, that is working

**Comment by rllyy97** [comment]
Quick status update, we are almost halfway through the fix rollout, we should reach all stages by EoD Friday

**Comment by rllyy97** [comment]
The fix for this issue should be live in all production regions, closing this issue, if anyone is still facing the issue try clearing your cache to pick up the new version.  If you are _still_ having issues please leave us a comment and we will investigate further!

**Comment by las3r** [comment]
Thanks for being so quick with a fix. The problem however hasn't fixed for me. I have even used google chrome to check (I don't use chrome), just to make sure it wasn't cache on my side. For me it's the same as it was in #5963.

**Comment by RobJoosen** [comment]
Hi, Same here:

![Image](https://github.com/user-attachments/assets/867ab24a-1a56-41e5-a7ad-82b158c13255)

**Comment by ccastrotrejo** [comment]
Hi @RobJoosen and @las3r 
Do you see any error in the console log or in the network tab? Do you have writing permissions in the logic apps that you are trying to take a look?
The mentioned fix was intended to solve the parameterization of appsettings and avoid unresolved parameterization in the API calls like this 
![Image](https://github.com/user-attachments/assets/eff0600c-3eac-4b1f-86b2-5662eba38b2e)

**Comment by las3r** [comment]
I have the right writing permissions (owner). 

Simple keyvault "get secret" action (Based on an api connection):
```
{
    "schemaVersion": 1,
    "extractionType": "FxError",
    "message": "Unable to initialize operation details for swagger based operation - Get_secret. Error details - Operation Id cannot be determined from definition and swagger",
    "name": "MsPortalFx.Errors.Error/Error",
    "stack": "    at https://portal.azure.com/Content/Dynamic/cD7e6jg6jXHe.js:1:273594\n    at Array.forEach (<anonymous>)\n    at https://portal.azure.com/Content/Dynamic/cD7e6jg6jXHe.js:1:273549\n    at https://portal.azure.com/Content/Dynamic/Qu8SkCtRv2c_.js:19:2582\n    at Array.filter (<anonymous>)\n    at t.FunctionProxyImpl._flushCallQueue (https://portal.azure.com/Content/Dynamic/Qu8SkCtRv2c_.js:19:1962)\n    at r.onmessage (https://portal.azure.com/Content/Dynamic/Qu8SkCtRv2c_.js:19:1285)",
    "blade": {
        "id": "Extension/Microsoft_Azure_EMA/Blade/DesignerEditorConsumption.ReactView",
        "instanceId": "Blade_ca62b9d0c9134203877ca6af010b395f_14_0"
    },
    "online": true
}
```

and my event grid trigger action:
```
{
    "schemaVersion": 1,
    "extractionType": "FxError",
    "message": "Unable to initialize operation details for swagger based operation - When_a_CustomerCaseCommentUpdate_event_occurs. Error details - Operation Id cannot be determined from definition and swagger",
    "name": "MsPortalFx.Errors.Error/Error",
    "stack": "    at https://portal.azure.com/Content/Dynamic/cD7e6jg6jXHe.js:1:273594\n    at Array.forEach (<anonymous>)\n    at https://portal.azure.com/Content/Dynamic/cD7e6jg6jXHe.js:1:273549\n    at https://portal.azure.com/Content/Dynamic/Qu8SkCtRv2c_.js:19:2582\n    at Array.filter (<anonymous>)\n    at t.FunctionProxyImpl._flushCallQueue (https://portal.azure.com/Content/Dynamic/Qu8SkCtRv2c_.js:19:1962)\n    at r.onmessage (https://portal.azure.com/Content/Dynamic/Qu8SkCtRv2c_.js:19:1285)",
    "blade": {
        "id": "Extension/Microsoft_Azure_EMA/Blade/DesignerEditorConsumption.ReactView",
        "instanceId": "Blade_ca62b9d0c9134203877ca6af010b395f_14_0"
    },
    "online": true
}
```

Other:
```
{
    "designerVersion": "4.105.8",
    "designerID": "B4DC8745-AC38-4CD0-9C62-FF9F6CD7DC3C"
}
```

Please note that my previous case was closed (#5963) in favor of this "rollup" issue here, but it seems they are two specific (and different) issues.

**Comment by sdk11DB** [comment]
Hi,
I am facing the same issue as this.
![Image](https://github.com/user-attachments/assets/10e35776-81ab-4f3e-a6f6-68f57a409f78)

**Comment by ccastrotrejo** [comment]
Ok, thanks for letting me know. @las3r I will reopen yours and take a further look, I will try to repro and answer back on that issue thread.

@sdk11Db do you get any console or network errors while doing this?

**Comment by RobJoosen** [comment]
As an additionL I noticed this behaviour in Consumption Logic Apps as well....

**Comment by sdk11DB** [comment]
> Ok, thanks for letting me know. [@las3r](https://github.com/las3r) I will reopen yours and take a further look, I will try to repro and answer back on that issue thread.
> 
> [@sdk11DB](https://github.com/sdk11DB) do you get any console or network errors while doing this?

I do not see any run time errors or network errors. The flows run without any issues. It is only when I try to open in edit, it comes like this.

**Comment by sdk11DB** [comment]
> > Ok, thanks for letting me know. [@las3r](https://github.com/las3r) I will reopen yours and take a further look, I will try to repro and answer back on that issue thread.
> > [@sdk11DB](https://github.com/sdk11DB) do you get any console or network errors while doing this?
> 
> I do not see any run time errors or network errors. The flows run without any issues. It is only when I try to open in edit, it comes like this with the issue.

Hello, any update on this ? I still have the issue.

**Comment by las3r** [comment]
@sdk11DB this is further discussed in https://github.com/Azure/LogicAppsUX/issues/5963.

**Comment by ccastrotrejo** [comment]
Hi @sdk11DB 

Is there any chance we can get your workflow json schema from your logic app? The error from @las3r seems really specific to their workflows, and would be good if yours is because of the same reason. Thanks!
You can share it with me to my email [ccastrotrejo@microsoft.com](mailto:ccastrotrejo@microsoft.com)

**Comment by ebytreesa** [comment]
Hi, I am facing the same issue. I get a console error like this
 
"Unable to initialize operation details for swagger based operation - Create_or_update_document_(V3). Error details - Operation Id cannot be determined from definition and swagger"

**Comment by ccastrotrejo** [comment]
Hi @ebytreesa, Is there any chance we can get your workflow json schema from your logic app? You can share it with me to my email [ccastrotrejo@microsoft.com](mailto:ccastrotrejo@microsoft.com)

**Comment by ebytreesa** [comment]
Hi @ccastrotrejo, I’ve emailed you the workflow JSON schema from a different address

**Comment by ebytreesa** [comment]
> Hi [@ebytreesa](https://github.com/ebytreesa), Is there any chance we can get your workflow json schema from your logic app? You can share it with me to my email [ccastrotrejo@microsoft.com](mailto:ccastrotrejo@microsoft.com)

Hi @ccastrotrejo, I’ve emailed you the workflow JSON schema from a different address

**Comment by ccastrotrejo** [comment]
Hi @ebytreesa , could you please send it again? It seems that I couldn't receive your email

**Comment by ebytreesa** [comment]
@ccastrotrejo Any update on my issue?

**Comment by ccastrotrejo** [comment]
Hi @ebytreesa I replied to you via email with a couple of follow up questions. Whenever you have a chance, could you please answer back?

**Comment by ebytreesa** [comment]
Hi,

I couldn’t open the attatchment in the other email. Can you send it again
in this email?

Thank you

Regards
Eby

**Comment by ccastrotrejo** [comment]
Hi @ebytreesa this is just an email that GitHub sends whenever we comment in the GitHub issue. I am not able to see your email. But here are the follow up questions:
Does this work in old designer and doesn’t work in the new one?
Do you get any errors in the network tab?
Do you happen to know what is the complete error message that the action is throwing when loading the new designer?

**Comment by ebytreesa** [comment]
Hi,

It was working in the old designer. It is not there anymore.
We don’t get any error in the network tab.
The error message that the action is throwing is ‘unable to initialize
operation’, similar to the other pictures posted by others.

**Comment by mramott** [comment]
Hi @ccastrotrejo. We are also experiencing this issue. We have a workflow that calls a Document Intelligence custom model analyzer. It works fine but then randomly stops working when triggered by another logic app. The workflow displays the previously-quoted error:

Unable to initialize operation details for swagger based operation - step here_. Error details - Operation Id cannot be determined from definition and swagger.

Deleting and replacing the step solves the issue, only for it to recur at a random time later.

I'm hoping I may be able to email you logs and our workflow.json for a closer look. If this is possible, please do let me know (with my advance thanks.

**Comment by JoeHague86** [comment]
I am also still having this issue. The logic app worked fine initially but seemingly after a few days it starts to fail, additionally when editing you cannot select the connector in its broker state![Image](https://github.com/user-attachments/assets/729053bb-5de9-4803-b720-2e9708e5b1c6)

**Comment by ccastrotrejo** [comment]
Hi @JoeHague86 thanks for raising this issue. 
- Do you see any issues in the console tab? 
- Does your connection use settings parameterization?

**Comment by JoeHague86** [comment]
![Image](https://github.com/user-attachments/assets/975f9469-be1b-4390-84df-fc19eaf6f056)
This is all I get when clicking on the connector when viewing the run, I am not using any specific settings parameterisation

**Comment by ccastrotrejo** [comment]
Hi @JoeHague86 
Do you mind sharing with me again the workflow.json and some HAR log traces while you trying to open designer? Here is a small guide on how to get the HAR file. [collecting-network-logs-in-a-har-file](https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file)

Pleas share does files with me to my email. [ccastrotrejo@microsoft.com](mailto:ccastrotrejo@microsoft.com)

**Comment by bps70** [comment]
Despite clearing the cache we still encounter this UI error - even on newly created connetors - so the issue is still there.
Error from console:
id
: 
"Extension/Microsoft_Azure_EMA/Blade/DesignerEditorConsumption.ReactView"
instanceId
: 
"Blade_adfce9d5a54d415fa0d1bf874b2f7fab_26_0"
[[Prototype]]
: 
Object
data
: 
undefined
documentVisibilityState
: 
undefined
extractionType
: 
"FxError"
message
: 
"Unable to initialize operation details for swagger based operation - BrugerAdmin_WhoAmI_Connector. Error details - Token \"SatsBeregningSatsBeregningAnnullerRequest\" does not exist."
name
: 
"MsPortalFx.Errors.Error/Error"
online
: 
true
schemaVersion
: 
1
stack
: 
"    at https://portal.azure.com/Content/Dynamic/cD7e6jg6jXHe.js:1:273594\n    at Array.forEach (<anonymous>)\n    at https://portal.azure.com/Content/Dynamic/cD7e6jg6jXHe.js:1:273549\n    at https://portal.azure.com/Content/Dynamic/Qu8SkCtRv2c_.js:19:2582\n    at Array.filter (<anonymous>)\n    at t.FunctionProxyImpl._flushCallQueue (https://portal.azure.com/Content/Dynamic/Qu8SkCtRv2c_.js:19:1962)\n    at r.onmessage (https://portal.azure.com/Content/Dynamic/Qu8SkCtRv2c_.js:19:1285)"
[[Prototype]]
: 
Object
[[Prototype]]
: 
Object
 
{resourceID: '/subscriptions/bd6d06c2-c4a6-480f-80c5-bc4413b3fa4…Microsoft.Logic/workflows/UTIL_BrugerAdmin_WhoAmI', designerVersion: '4.105.8', designerID: '30D2650C-F0F6-4AF5-B307-1B4E157D781B'}
designerID
: 
"30D2650C-F0F6-4AF5-B307-1B4E157D781B"
designerVersion
: 
"4.105.8"

**Comment by bps70** [comment]
Sorry - figured it out - it was an issue with our swagger definition which caused this error.

**Comment by clb900528** [comment]
Hi @ccastrotrejo Is there currently a solution to this issue?

![Image](https://github.com/user-attachments/assets/7ebf6e03-b2ed-4853-8422-deb0cc11d7ae)

**Comment by ccastrotrejo** [comment]
Hi @clb900528 it seems that the issue is related, however its quite hard to determine what is going on, if indeed its related or if there is an already implemented solution to it. Could you please create a new GitHub issue detailing what is happening in your logic app? You can do that here https://github.com/Azure/LogicAppsUX/issues
