### ISSUE TITLE
Breaking changes / regression on runtime parameters handling

### ISSUE THREAD

**Issue by bkgge** [Azure/LogicAppsUX#5985]
### Describe the Bug with repro steps 

Context : logic app consumption

We notice a recent change in the way Logic App is handling parameters that make impossible to save (in code view) the workflow.

The following minimal sample can be saved without errors in the code view :

```
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "triggers": {
            "Recurrence": {
                "type": "Recurrence",
                "recurrence": {
                    "interval": 10,
                    "frequency": "Day"
                }
            }
        },
        "actions": {},
        "outputs": {},
        "parameters": {
            "param0": {
                "type": "Bool",
                "defaultValue": true
            },
            "$connections": {
                "type": "Object",
                "defaultValue": {}
            }
        }
    },
    "parameters": {
        "param0": {
            "type": "Bool",
            "value": true
        },
        "$connections": {
            "value": {}
        }
    }
}
```

The following minimal sample cannot be saved in the code view :

```
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "triggers": {
            "Recurrence": {
                "type": "Recurrence",
                "recurrence": {
                    "interval": 10,
                    "frequency": "Day"
                }
            }
        },
        "actions": {},
        "outputs": {},
        "parameters": {
            "param0": {
                "type": "Bool",
                "defaultValue": true
            },
            "$connections": {
                "type": "Object",
                "defaultValue": {}
            }
        }
    },
    "parameters": {
        "param0": {
            "type": "Bool",
            "value": false
        },
        "$connections": {
            "value": {}
        }
    }
 #}
```

Error returned :

```
"error": {
        "code": "InvalidTemplate",
        "message": "The template validation failed: 'The value for the workflow parameter 'param0' at line '1' and column '170' is not provided.'."
    }
```

The only change made is switching the param0 value from false to true in the runtime parameters.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

{

 "definition": {

 "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",

 "contentVersion": "1.0.0.0",

 "triggers": {

 "Recurrence": {

 "type": "Recurrence",

 "recurrence": {

 "interval": 10,

 "frequency": "Day"

 }

 }

 },

 "actions": {},

 "outputs": {},

 "parameters": {

 "param0": {

 "type": "Bool",

 "defaultValue": true

 },

 "$connections": {

 "type": "Object",

 "defaultValue": {}

 }

 }

 },

 "parameters": {

 "param0": {

 "type": "Bool",

 "value": false

 },

 "$connections": {

 "value": {}

 }

 }

 #}

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

We also notice that :

- the runtime parameters's type is now mandatory when saving with code view (an error is triggered if not) 
- when switching to UI and then code view the runtime parameters's type is deleted, so if an other change need to be done in code view, the parameter's type need to be added manually to be saved.

**Comment by Eric-B-Wu** [comment]
Hey @bkgge, thanks for reporting this issue, I've identified the issue and have a bugfix for this.

**Comment by bkgge** [comment]
Hi @Eric-B-Wu, thanks for the quick fix, do you know when it will be delivered to the logics apps designer in the Azure portal ?
