### ISSUE TITLE
LA Std Run History fails with parameterized Managed connections

### ISSUE THREAD

**Issue by shboulatom83** [Azure/LogicAppsUX#5990]
### Describe the Bug with repro steps 

1. Use managed connector, such as Teams, or SPO 
2. Have the connection related to the managed connector parameterized in connections.json; for example the subscription id is a parameterized parameter that references an appSettings value

![Image](<https://github.com/user-attachments/assets/5639040d-99c6-4f55-8844-6d81fb1f5de5>) 
3. The logic app will run fine in Designer and Runtime. But will show errors in Run History.

![Image](<https://github.com/user-attachments/assets/5adac1b2-6984-4d45-a513-3e645bc57c6b>) 
4. Errors are related to REST API call that is not resolving the parameterized subscription id 

![Image](<https://github.com/user-attachments/assets/a15658ae-6b4e-4461-928c-d1abf684c267>)

![Image](<https://github.com/user-attachments/assets/3045c2d9-cbcc-416e-98c8-7f5a23b755fe>) 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

All

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
Closing for https://github.com/Azure/LogicAppsUX/issues/5977
