### ISSUE TITLE
Show Logic App Run details not working in Logic Apps

### ISSUE THREAD

**Issue by cristiteodorov** [Azure/LogicAppsUX#5999]
### Describe the Bug with repro steps 

1. Go to a run of a logic app that calls another logic app. 
2. select the logic app that was ran inside the main logic app (child logic app) 
3. A pane with options expands on the right. The first button is "Show Logic App run details" 
4. Click the button - it should take you to that specific run. The button does nothing. 
5. Tested in both Google Chrome and Microsoft Edge and the same result in both, button does nothing and no error logged in console. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome and Edge

### Additional context 

*No response*

**Comment by rllyy97** [comment]
This is fixed with the following PR: https://github.com/Azure/LogicAppsUX/pull/5956
It's currently in our upcoming release, and is also being hotfixed.
