### ISSUE TITLE
Error starting azure logic apps extension

### ISSUE THREAD

**Issue by gbuckholtz** [Azure/LogicAppsUX#6002]
Does this occur consistently? 

 Repro steps:

1\.

 2\.

Action: autoStartDesignTime

 Error type: TypeError

 Error Message: Cannot read properties of undefined (reading 'uri')

Version: 4.107.3

 OS: darwin

 OS Release: 23.6.0

 Product: Visual Studio Code

 Product Version: 1.88.1

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
HI @gbuckholtz thanks for raising this issue. This doesn't occur consistently.
Are you trying to open a Logic App project?
Do you have our binaries dependencies installed in your following path? `/Users/<your username>/.azurelogicapps/dependencies`

**Comment by gbuckholtz** [comment]
I am not using Logic Apps in this project.  I do have several Azure Functions, though.  I will update you if I notice it happens regularly.

**Comment by ccastrotrejo** [comment]
@gbuckholtz I see, that shouldn't be happening since you have several Azure Functions and not Logic Apps in it.
I will close this issue as this is not happening with Logic Apps.
Please let us know if that happens more consistently in the future and we can re-open it.
