### ISSUE TITLE
Cannot change default retryPolicy to HTTP swagger operation

### ISSUE THREAD

**Issue by systems-imei** [Azure/LogicAppsUX#6010]
### Describe the Bug with repro steps 

Cannot change default retryPolicy to HTTP swagger operation

1. click on swagger operation 
2. click on settings 
3. change retry Policy to None 
4. click save 

Gettting the following error

Workflow validation failed for the workflow ''. {"error":{"code":"InvalidRequestContent","message":"The request content is not valid and could not be deserialized: 'Could not find member 'retryPolicy' on object of type 'FlowTemplateAction'. Path 'properties.definition.actions..retryPolicy', line 1, position 2409.'."}}

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

{

 "type": "Http",

 "metadata": {

 "apiDefinitionUrl": "https:///swagger/docs/v1",

 "swaggerSource": "custom"

 },

 "inputs": {

 "method": "post",

 "uri": "https://",

 "body": "@body('CosmosDbCasperJob--UpdateById')"

 },

 "retryPolicy": {

 "type": "none"

 },

 "runAfter": {

 "DoingSomething": [

 "Succeeded"

 ]

 }

 }

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/ebd978e3-5b00-4231-b6a8-acd5f2ec4005>)

![Image](<https://github.com/user-attachments/assets/7639fa5f-7ade-4eb6-9502-4e43c2859ab4>)

![Image](<https://github.com/user-attachments/assets/0db365f4-9fbc-4ab7-8e5c-5b61a85443c0>)

### Browser 

edge

### Additional context 

Worked on the old designer but not on the new one

**Comment by rllyy97** [comment]
Hi @systems-imei, thanks for reporting your issue, we do have this fixed as part our upcoming release. https://github.com/Azure/LogicAppsUX/pull/5831

You should see the issue fixed between Nov 7th - 13th depending on your region.
Thanks for your patience as we get this rolled out!

**Comment by gaven-imei** [comment]
I still get the same error. I am located in Australia
