### ISSUE TITLE
Outlook - Send Email an Email (work & school accounts)

### ISSUE THREAD

**Issue by czbbruner** [Azure/LogicAppsUX#6016]
### Describe the Bug with repro steps 

The Outlook "Send an Email (v2)" function appears to not recognize work & school accounts when asking to sign in to create a connection.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Browser 

Edge browser.

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
Hi @czbbruner thanks for raising this issue, there are two different Outlook connectors, this would depend on the account that you have. 
- Are you using the Outlook.com or the Office 365 Outlook connector?
![Image](https://github.com/user-attachments/assets/8539279e-84df-47a5-835b-fc79fa30a890)

**Comment by czbbruner** [comment]
@ccastrotrejo 
I see! That worked perfectly to fix the problem I was having. Thank you for the information about the two different connectors. 

Closing this issue as resolved.
