### ISSUE TITLE
Show Logic App run details doesn't work for large files

### ISSUE THREAD

**Issue by tjohnson1010** [Azure/LogicAppsUX#6018]
### Describe the Bug with repro steps 

When transferring a large set of data to another Logic App, the "Show Logic App run details" button when debugging doesn't do anything. It should pull up that instance of the called Logic App.

1) Go into the Run History of a Logic App that will pass a large dataset to another logic app.

 2) Click the action that calls the other Logic App.

 3) Click the "Show Logic App run details" button, and notice it does nothing.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

{

 "definition": {

 "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",

 "contentVersion": "1.0.0.0",

 "triggers": {

 "manual": {

 "type": "Request",

 "kind": "Http",

 "inputs": {

 "schema": {

 "properties": {

 "CustomerFolder": {

 "type": "string"

 },

 "Data": {

 "type": "string"

 },

 "Filename": {

 "type": "string"

 },

 "IsProduction": {

 "type": "boolean"

 },

 "Origin": {

 "type": "string"

 }

 },

 "type": "object"

 }

 }

 }

 },

 "actions": {

 "Exception": {

 "runAfter": {

 "Filter\_Error\_Messages": [

 "Succeeded"

 ]

 },

 "type": "ApiConnection",

 "inputs": {

 "host": {

 "connection": {

 "name": "@parameters('$connections')['office365']['connectionId']"

 }

 },

 "method": "post",

 "body": {

 "To": "@parameters('emailTo')",

 "Subject": "@{if(equals(triggerBody()?['IsProduction'],true),'','Test ')}Exception occurred in Multi-Client Outbound Customer : @{triggerBody()?['Filename']}",

 "Body": "

Error At : @{last(body('Filter\_Error\_Messages'))?['name']}

\n

\nFilename : @{triggerBody()?['Filename']}

\n

\nOrigin: @{triggerBody()?['Origin']}

\n

\nRun : @{workflow().run.name}

\n

\n@{if(equals(first(string(coalesce(last(body('Filter\_Error\_Messages'))?['outputs']?['body'],'{}'))),'{'),coalesce(last(body('Filter\_Error\_Messages'))?['outputs']?['body']?['error']?['message'],last(body('Filter\_Error\_Messages'))?['outputs']?['body']?['errorMessage'],last(body('Filter\_Error\_Messages'))?['error']?['message'],last(body('Filter\_Error\_Messages'))?['outputs']?['body'],last(body('Filter\_Error\_Messages'))?['error']),last(body('Filter\_Error\_Messages'))?['outputs']?['body'])}

",

 "Importance": "High"

 },

 "path": "/v2/Mail"

 }

 },

 "Filter\_Error\_Messages": {

 "runAfter": {

 "Scope": [

 "Failed"

 ]

 },

 "type": "Query",

 "inputs": {

 "from": "@result('Scope')",

 "where": "@equals(item()['status'], 'Failed')"

 }

 },

 "Initialize\_Agreement": {

 "runAfter": {},

 "type": "InitializeVariable",

 "inputs": {

 "variables": [

 {

 "name": "Agreement",

 "type": "string",

 "value": "XX"

 }

 ]

 }

 },

 "Initialize\_FileType": {

 "runAfter": {

 "Initialize\_Agreement": [

 "Succeeded"

 ]

 },

 "type": "InitializeVariable",

 "inputs": {

 "variables": [

 {

 "name": "FileType",

 "type": "string",

 "value": "@{last(split(triggerBody()?['Filename'],'.'))}"

 }

 ]

 }

 },

 "Response\_Error": {

 "runAfter": {

 "Exception": [

 "Succeeded"

 ]

 },

 "type": "Response",

 "kind": "Http",

 "inputs": {

 "statusCode": 200,

 "body": "Error Occurred: @{workflow()}"

 }

 },

 "Scope": {

 "actions": {

 "Process\_File": {

 "cases": {

 "Bawls": {

 "case": "BAWLS",

 "actions": {

 "ShipStation\_Outbound": {

 "type": "Workflow",

 "inputs": {

 "host": {

 "workflow": {

 "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/ShipStation\_Outbound"

 },

 "triggerName": "manual"

 },

 "body": {

 "Data": "@triggerBody()?['Data']",

 "Filename": "@triggerBody()?['Filename']",

 "IsProduction": "@triggerBody()?['IsProduction']",

 "Origin": "@triggerBody()?['Origin']"

 }

 }

 }

 }

 },

 "Dual": {

 "case": "Dual",

 "actions": {

 "Outbound\_Transform\_-*Dual": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound\_Transform" }, "triggerName": "manual" }, "body": { "CustomerCode": "DU", "CustomerName": "Dual", "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']" } } } } }, "Harry's": { "case": "Harrys", "actions": { "File\_Type*\-*Harry's": { "cases": { "RC-Harry's": { "case": "rcuxml", "actions": { "Send\_RC": { "actions": { "Set\_Agreement*\-*RC": { "type": "SetVariable", "inputs": { "name": "Agreement", "value": "Harrys" } } }, "else": { "actions": {} }, "expression": { "and": [ { "equals": [ "@length(xpath(xml(triggerBody()?['Data']),parameters('xUserDef3')))", 1 ] } ] }, "type": "If" } } } }, "default": { "actions": { "Set\_Agreement*\-*All\_Others": { "type": "SetVariable", "inputs": { "name": "Agreement", "value": "Harrys\_Amazon" } } } }, "expression": "@variables('FileType')", "type": "Switch" }, "OK\_2\_Send": { "actions": { "Outbound\_X12*\-*Harry's": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound\_X12" }, "triggerName": "manual" }, "body": { "Aggrement": "@variables('Agreement')", "CustomerCode": "HR@{if(endsWith(variables('Agreement'),'DTC'),'D','')}", "CustomerName": "Harry's", "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']" } } } }, "runAfter": { "File\_Type*\-*Harry's": [ "Succeeded" ] }, "else": { "actions": {} }, "expression": { "and": [ { "not": { "equals": [ "@variables('Agreement')", "XX" ] } } ] }, "type": "If" } } }, "INKEY": { "case": "INKEY", "actions": { "Outbound\_Flat*\-*Inkey": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound\_Flat" }, "triggerName": "manual" }, "body": { "CustomerCode": "IK", "CustomerName": "INKEY", "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']", "Process": "ShipConfirm" } } } } }, "Maharam": { "case": "Maharam", "actions": { "Outbound\_X12*\-*Maharam": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound\_X12" }, "triggerName": "manual" }, "body": { "Aggrement": "Maharam", "CustomerCode": "MA", "CustomerName": "Maharam", "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']" } } } } }, "SUNNYLiFE": { "case": "SUNNYLiFE", "actions": { "NetSuite\_vs.\_SPS": { "actions": { "SPS\_Outbound": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound\_Transform" }, "triggerName": "manual" }, "body": { "CustomerCode": "SL", "CustomerName": "SUNNYLiFE", "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']" } } } }, "else": { "actions": { "NetSuite\_Outbound": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/NetSuite\_Outbound" }, "triggerName": "manual" }, "body": { "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']" } } } } }, "expression": { "and": [ { "not": { "equals": [ "@first(xpath(xml(triggerBody()?['Data']),parameters('xUserDef4')))", "SUNNYLiFE" ] } }, { "equals": [ "@variables('FileType')", "shuxml" ] } ] }, "type": "If" } } }, "Shopify": { "case": "Shopify", "actions": { "Shopify\_Send2": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Shopify\_Send2" }, "triggerName": "manual" }, "body": { "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']" } } } } }, "WAYB": { "case": "WAYB", "actions": { "NetSuite\_Outbound\_2": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/NetSuite\_Outbound" }, "triggerName": "manual" }, "body": { "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']" } } } } }, "Yamaha": { "case": "Yamaha", "actions": { "Outbound\_X12*\-*Yamaha": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound\_X12" }, "triggerName": "manual" }, "body": { "Aggrement": "Yamaha", "CustomerCode": "YA", "CustomerName": "Yamaha", "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']" } } } } }, "Yamazaki": { "case": "Yamazaki", "actions": { "Outbound\_Transform*\-*Yamazaki": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound\_Transform" }, "triggerName": "manual" }, "body": { "CustomerCode": "YZ", "CustomerName": "Yamazaki", "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']" } } } } }, "Plain\_Supply": { "case": "Plain Supply", "actions": { "Condition": { "actions": { "Outbound\_Flat": { "runAfter": { "Flat\_File\_Decoding": [ "Succeeded" ] }, "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound\_Flat" }, "triggerName": "manual" }, "body": { "CustomerCode": "PS", "CustomerName": "Plain Supply", "Data": "@{body('Flat\_File\_Decoding')}", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']", "Process": "ItemBalance" } } }, "Flat\_File\_Decoding": { "type": "FlatFileDecoding", "inputs": { "content": "@triggerBody()?['Data']", "integrationAccount": { "schema": { "name": "PS\_ItemBalance" } } } } }, "else": { "actions": { "Outbound\_Transfer": { "type": "Workflow", "inputs": { "host": { "workflow": { "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Logic/workflows/Outbound\_Transfer" }, "triggerName": "manual" }, "body": { "CustomerCode": "PS", "CustomerName": "Plain Supply", "Data": "@triggerBody()?['Data']", "Filename": "@triggerBody()?['Filename']", "IsProduction": "@triggerBody()?['IsProduction']", "Origin": "@triggerBody()?['Origin']" } } } } }, "expression": { "and": [ { "equals": [ "@variables('FileType')", "ibupl" ] } ] }, "type": "If" } } } }, "default": { "actions": { "Send\_an\_email*(V2)": {

 "type": "ApiConnection",

 "inputs": {

 "host": {

 "connection": {

 "name": "@parameters('$connections')['office365']['connectionId']"

 }

 },

 "method": "post",

 "body": {

 "To": "@parameters('emailTo')",

 "Subject": "Unknown Folder in Multi-Client Outbound Customer",

 "Body": "Folder: @{triggerBody()?['CustomerFolder']}

Run : @{workflow().run.name}

",

 "Importance": "High"

 },

 "path": "/v2/Mail"

 }

 }

 }

 },

 "expression": "@triggerBody()?['CustomerFolder']",

 "type": "Switch"

 },

 "Response\_OK": {

 "runAfter": {

 "Process\_File": [

 "Succeeded"

 ]

 },

 "type": "Response",

 "kind": "Http",

 "inputs": {

 "statusCode": 200

 }

 }

 },

 "runAfter": {

 "Initialize\_FileType": [

 "Succeeded"

 ]

 },

 "type": "Scope"

 }

 },

 "outputs": {},

 "parameters": {

 "emailTo": {

 "defaultValue": "Multi-ClientAlerts@legacyscs.com",

 "type": "String"

 },

 "xCompany": {

 "defaultValue": "//*[local-name()=\"Shipment\"]/*[local-name()=\"Customer\"]/*[local-name()=\"Company\"]/text()", "type": "String" }, "xUserDef3": { "defaultValue": "//*[local-name()='Receipt']/*[local-name()='UserDef3']/text()", "type": "String" }, "xUserDef4": { "defaultValue": "//*[local-name()='Shipment']/\*[local-name()='UserDef4']/text()",

 "type": "String"

 },

 "$connections": {

 "type": "Object",

 "defaultValue": {}

 }

 }

 },

 "parameters": {

 "$connections": {

 "value": {

 "office365": {

 "id": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/providers/Microsoft.Web/locations/westcentralus/managedApis/office365",

 "connectionId": "/subscriptions/b43660bb-5fa5-4cd2-9481-262705080580/resourceGroups/Multi-Client/providers/Microsoft.Web/connections/office365",

 "connectionName": "office365"

 }

 }

 }

 }

 } 

### Screenshots or Videos 

*No response*

### Browser 

Microsoft Edge for Business

 Version 130.0.2849.56 (Official build) (64-bit)

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @tjohnson1010, this is a known issue that has been fixed in the following PR: https://github.com/Azure/LogicAppsUX/pull/5739
It will be a part of our next release starting Nov 7th, and will finish releasing to all stages by Nov 13th.
If you are blocked by this, you can use our staging slot [here](https://ms.portal.azure.com/?feature.canmodifystamps=true&Microsoft_Azure_EMA=staging#home), but keep in mind that this is a pre-production release and I would advise not to use it more than needed.
