### ISSUE TITLE
Error when asking a simple question

### ISSUE THREAD

**Issue by RobScott-Trimble** [Azure/LogicAppsUX#6034]
### Describe the Bug with repro steps 

Any question I ask of the Assistant, I get a "Sorry, something went wrong. Please try again.". Here is the chat-session-id: 4470C888-EF4F-4B17-8DFF-D4C70F3C7DF9

### What type of Logic App Is this happening in? 

Standard

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/25c81b3d-50f3-4028-be11-b1f9d1d4ff0a>)

### Browser 

Chrome - latest version (130.0.6723.92 (Official Build) (64-bit))

### Additional context 

See screenshot image

**Comment by RobScott-Trimble** [comment]
By clicking on the Assistant button

![Image](https://github.com/user-attachments/assets/0f045939-f4fb-48eb-8c71-8e50aaa974e3)

**Comment by ccastrotrejo** [comment]
Hi @RobScott-Trimble thanks for raising this issue. We were able to repro it, we will work on the fix of it!

**Comment by ccastrotrejo** [comment]
@RobScott-Trimble In the meantime as a workaround could you please use the following url to use portal? This private link has the fix for the workflow assistant [aka.ms/emastaging](https://ms.portal.azure.com/?feature.canmodifystamps=true&Microsoft_Azure_EMA=staging#home)
