### ISSUE TITLE
The search bar in the Dynamic Content expression window does not search.

### ISSUE THREAD

**Issue by megamax34** [Azure/LogicAppsUX#6038]
### Describe the Bug with repro steps 

- Open a consumption logic app 
- create a bunch of actions 
- open one of the actions (lets use Compose as the sample action) 
- click in the parameters textbox and select the dynamic content pop up (we want to select the outputs of a previous action) 
- attempt to search for an action 
- nothing pops up even though its the exact name of the action 
- Search is not smart and does not find even the simplest of names 
- I should be able to look for action types, action names, and even custom properties like variable names. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

No

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/349aa93d-7c3f-43f5-9682-18548f1c5e4e>)

### Browser 

edge

### Additional context 

Its small bugs like this in the new UI that makes me desperately miss the old view. I find that it takes me longer to develop with the new view. load times of actions has been slightly improved and re-run from a specific action are great but there are a lot of issues that still need worked on to get back to where we were with the old view.

**Comment by rllyy97** [comment]
Hi @megamax34, thanks for reporting the issue!  And thank you for being honest with us about your thoughts on the new UI, we aim for full parity with old designer so if you have any other bugs you've seen please do let us know, or comment if it has an existing report.  If it's a small issue like this one, there's a good chance we can get it fixed pretty quick as well!

For release timing on this fix, we are in some release freezes so it might take some time, but it will be a part of our next release.
