### ISSUE TITLE
SFTP actions are skipping properties pane and opening Create anew connection pane instead.

### ISSUE THREAD

**Issue by tjohnson1010** [Azure/LogicAppsUX#6042]
### Describe the Bug with repro steps 

When adding an SFTP action, it goes to Create a new connection instead of showing teh properties whcih has a dropdown to choose an existing connection with a link to create a new connection.

1> Create a new Logic App

 2> Add an HTTP Request trigger

 3> Add a SFTP - Get file content path action

 4> Note it goes straight to create a new connection.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Microsoft Edge for Business

 Version 130.0.2849.68 (Official build) (64-bit)

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @tjohnson1010, this behavior is intended to only happen if there are no valid connections for the connector available to use.  If you add the action, create a new connection, then go to change the connection, do you see other valid connections you should have been able to choose from?

**Comment by tjohnson1010** [comment]
I think the issue may have been I created eth Logic app in the wrong Region.    I just created a logic app in the right region, and it did what it was supposed to do.

FYI:  A while back, if I clicked new from a Resource Group and picked Logic Apps, it would default the Region to the Resource Group’s region.  Now the setup screen defaults to the subscription’s Region (I think).

Have a good day,

Thomas Johnson
Director of IT Applications

Phone: 630.242.3385
***@***.******@***.***>  |  www.legacyscs.com<https://legacyscs.com/>

distribution | fulfillment | transportation

This confidential e-mail and any attachments are for the exclusive use of the addressee(s). If you receive this in error, please delete all copies and notify the sender. Any views expressed are those of the sender, unless stated otherwise.

**Comment by rllyy97** [comment]
Glad to hear you were able to get it figured out!
