### ISSUE TITLE
Swagger uri not found on Code View when using new designer

### ISSUE THREAD

**Issue by anatiSRT** [Azure/LogicAppsUX#6046]
### Describe the Bug with repro steps 

Hi,

When viewing the logic app using the new designer, the Swagger uri is marked as '**NotFound**' on Code View and it causes an error on run time.

Old Designer:

![Image](<https://github.com/user-attachments/assets/938c9007-8bbe-4455-b1db-f62a10972ea4>)

New Designer:

![Image](<https://github.com/user-attachments/assets/95fd5fa4-77af-4d84-a23e-5bdc101f4d7a>)

Error:

![Image](<https://github.com/user-attachments/assets/883ec327-a6b1-4d32-a5cf-3144bfa64b7d>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by anatiSRT** [comment]
@Eric-B-Wu - Please reopen this ticket. This issue still exists using new designer. 

Please see below screenshot.
![Image](https://github.com/user-attachments/assets/a61e06e0-6c01-4f5a-8ab0-4aad6c3844d4)

**Comment by Eric-B-Wu** [comment]
Once we check in something in code, there's usually a 2-3 week delay before it reaches production. We'd expect this to be fixed in our next release
