### ISSUE TITLE
We would like to revert to the legacy Logic Apps designer, as the new designer is challenging to use and troubleshoot.

### ISSUE THREAD

**Issue by belaie** [Azure/LogicAppsUX#6051]
### Describe the Bug with repro steps 

We would like to revert to the legacy Logic Apps designer, as the new designer is challenging to use and troubleshoot.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

We would like to revert to the legacy Logic Apps designer, as the new designer is challenging to use and troubleshoot.

### Additional context 

*No response*

**Comment by hartra344** [comment]
We aren’t able to continue supporting the legacy designer, However, as Carlos said above, we’re very open to listening to problems you have and using that to make the new designer better. Please continue opening issues with those problems that you have.

**Comment by belaie** [comment]
When debugging a running workflow in the new Logic App designer, the interface displays spinning wheels (indicating activity) even on actions further down the workflow that have not yet been executed. This behavior makes it challenging to identify and troubleshoot issues accurately, as it creates confusion about which steps are actively processing and which are pending.
