### ISSUE TITLE
Outlook SendEmail V2

### ISSUE THREAD

**Issue by TroyDeppert** [Azure/LogicAppsUX#6054]
When I select 'Outlook - Send Email (V2)', it prompts me to login to Azure to create a connection. From past experience, I know this will create a problem with all the other Logic Apps that use that connection. Why doesn't have the option to use an existing connection like the Legacy editing did?

**Comment by ccastrotrejo** [comment]
Hi @TroyDeppert thanks for raising this issue. 
Is this happening in a Consumption or Standard Logic App?
Was this the first connection you created?

We do offer the experience of selecting different connections, or an already created connection. If you click in change connection, you will be able to see the old connections created. 


![Image](https://github.com/user-attachments/assets/980c3a99-65fa-4cad-801b-fcdf14b2fc20)
![Image](https://github.com/user-attachments/assets/1d60cb57-3c01-4dfe-9f06-61bae7f876f8)

**Comment by TroyDeppert** [comment]
Hello,

They are Consumption Logic Apps.  Here is what I see when I select Outlook Send Email (V2):

***@***.***

There is no way to select other connections.  It just keeps prompting for sign in under Create a new connection.

Thanks,
Troy

**Comment by ccastrotrejo** [comment]
Hi @TroyDeppert is this the first connection that you create? Even if you sign in does it continue prompting to create a new connection? If you create the connection does the designer shows the experience to change the connection?

**Comment by TroyDeppert** [comment]
No, the connection I want to use has already been created.  It is called AzureDI.
For some reason, it doesn't recognize that the connection already exists.
Since we have been converted to the new editor with no option go back, I can copy a previous Send Email and paste it and make the necessary changes.
The problem is, when I create a new logic app, this cut-and-paste method is no longer available to me and it doesn’t show a ‘Change Connection’ anywhere, just the Sign in.

**Comment by ccastrotrejo** [comment]
@TroyDeppert Is there any chance you can share with us your workflow schema? If you want you can share it to my email ccastrotrejo@microsoft.com

**Comment by TroyDeppert** [comment]
Is that the URL to the Logic App or the Code View?
Here is the weird thing.  I was just testing it on an old disabled Logic App, and the first time it brought up the correct dialog box with the correct connection.
I removed it, then tried it 2 more times and both the subsequent times showed the ‘Sign In’ option.

**Comment by ccastrotrejo** [comment]
@TroyDeppert its the code view. Ok thanks for letting us know this specific scenario

**Comment by TroyDeppert** [comment]
Attached is the code view.

**Comment by ccastrotrejo** [comment]
Hi @TroyDeppert we didn't see anything anormal from the workflow schema. Is there any chance we can get the network logs from whenever you open the designer and it prompts to create a new connection? You can do that by following the steps of this guide [collecting-network-logs-in-a-har-file](https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file)
Please send the HAR file to my email: ccastrotrejo@microsoft.com as this might contain sensitive information

**Comment by TroyDeppert** [comment]
So, even after zipping the file, it wouldn’t send it.
I could drop it into Box if that’s OK for you all.

**Comment by TroyDeppert** [comment]
I sent an email that the log capture was too large to send via email even when zipped.
I asked if you could pull it from a Box account.

Troy
________________________________

**Comment by ccastrotrejo** [comment]
Hi @TroyDeppert yes  if you could provide us a link from where to download it, would be great!

**Comment by TroyDeppert** [comment]
Hello Carlos,

Here is the link to the file:
https://www.dropbox.com/scl/fo/ed9s8f7gdcr9dl9oe0c2j/APdxVHHRItgZ8B39ItYVM2c?rlkey=zsgxpboz8h33fxfgq5sersvmn&st=0p6dxfk1&dl=0

Please email if there is a problem accessing the file.

Thanks,
Troy

**Comment by ccastrotrejo** [comment]
Hi @TroyDeppert, I was able to get the HAR file but couldn't find any particular reason on whyt this is failing. I noticed that for some reason one of the api calls tries to get the connections from the 'outlook' connector rather than the 'office365'. Are all of your actions from the same conector?

**Comment by TroyDeppert** [comment]
Hello,

That may be part of the problem.  When I’m setting up the email, I look for the Outlook Send Email action.
I’ll try to do the Office365 one.  It still doesn’t explain why it works sometimes but not all the times.

Thanks,
Troy
