### ISSUE TITLE
Unable to use AI Assistant - not generating Workflow description

### ISSUE THREAD

**Issue by gopaltalrejaShell** [Azure/LogicAppsUX#6063]
### Describe the Bug with repro steps 

Go to LogicApp Wf.

 Open Workflow designer.

 Click on Assistant.

 Write - Describe this workflow in the Text Box.

 Throws Error - Something went wrong. Chat Id 6E15BD0D-C3E9-4913-AF4F-09B64F9154B8

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

explorer

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hi @gopaltalrejaShell thanks for raising this issue. I will close this issue as we are going to keep the following one as the parent one https://github.com/Azure/LogicAppsUX/issues/6034
We were able to repro it and will come up with a fix. Thanks!

**Comment by ccastrotrejo** [comment]
@gopaltalrejaShell In the meantime as a workaround could you please use the following url to use Azure Portal? This private link has the fix for the workflow assistant [aka.ms/emastaging](https://ms.portal.azure.com/?feature.canmodifystamps=true&Microsoft_Azure_EMA=staging#home)
