### ISSUE TITLE
Unable to fetch all API connector triggers or actions.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#6069]
### Describe the Bug with repro steps 

1\.Create a new Standard Logic App Project in VS Code

 2\.Add a workflow to your local project

 3\.Open the workflow.json file in designer and author a new workflow

 4\.Add http request Trigger or Add API connection triggers

5. Add API connection actions like office 365 outlook/sharepoint/dropbox/Google sheets 

**Expected:** Should able to fetch all API connector triggers or actions.

**Actual:** Unable to fetch all API connector triggers or actions.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

**Triggers:**

![Image](<https://github.com/user-attachments/assets/ff40099e-af3a-42ea-879e-d696feecdfc2>)

![Image](<https://github.com/user-attachments/assets/f3807e38-8314-41e6-bb3a-c17bed6ca05f>)

![Image](<https://github.com/user-attachments/assets/4308b077-42c7-49b7-a7d4-90352292a646>)

![Image](<https://github.com/user-attachments/assets/e635f984-6ff1-4dd0-9e66-bac66be54503>)

**Actions:**

![Image](<https://github.com/user-attachments/assets/d5bd29ee-bfef-43b2-b6fc-95db96167267>)

![Image](<https://github.com/user-attachments/assets/8f3994f2-bd6b-4add-818e-4cbb345056bd>)

![Image](<https://github.com/user-attachments/assets/f8a240e2-6d94-4733-a33e-68291ea67556>)

![Image](<https://github.com/user-attachments/assets/5f0f88e7-4f07-4e6b-9770-bce4498c17c7>)

### Browser

VS Code

### Additional context

**VSIX Version :** 4\.116.7

**Comment by ccastrotrejo** [comment]
Hi @vgouth thanks for raising this issue. This gets solved with the following PR https://github.com/Azure/LogicAppsUX/pull/5988
