### ISSUE TITLE
New Logic Apps designer adds quotation marks and back slash to the code

### ISSUE THREAD

**Issue by PeterKlapwijk** [Azure/LogicAppsUX#6070]
### Describe the Bug with repro steps 

I have added multiple until actions in a Logic Apps flow using the new designer.

 Under loop until I selected data from a previous step. In the right field I entered 204.

Upon saving the flow I get multiple errors:

Workflow validation failed for the workflow ''. {"error":{"code":"InvalidTemplate","message":"The template validation failed: 'The template action 'Until\_Delete\_windowsHelloForBusinessAuthenticationMethod' at line '1' and column '8632' is not valid: \"The template language expression '*sanitized*' is not valid: the string character '\"' at position '89' is not expected.\".'."}}

Workflow validation failed for the workflow 'LAEmergencyRevokeAccessv1.0'. The template validation failed: 'The template action 'Until\_DELETE\_microsoftAuthenticatorAuthenticationMethod' at line '1' and column '10199' is not valid: "The template language expression 'equals(outputs('HTTP\_GET\_authentication\_methods')?['statusCode'],"204")' is not valid: the string character '"' at position '65' is not expected.".'.

After reviewing the code in Code view it turns out the number 204 is added as \"204\"

When I remove the quotes and back slashes, I can save the flow. When I add additional actions to the flow, the issue returns after which I need to remove the "\ again and again.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/0af12293-5fe3-469c-840c-c7917484a1b8>)

### Browser

Microsoft Edge.

### Additional context

*No response*

**Comment by jkerai1** [comment]
noticed similar behavior when you are trying to expressions on things like \n, took me a while to realise it was adding another backslash so my expression was never being evaluated had to go into code view and change it from \\n to \n

**Comment by PeterKlapwijk** [comment]
Why is this closed? The issue still occurs. Please reopen the issue!

**Comment by Solarvista187** [comment]
There appears to have been some regression as this issue is still occurring. Can this issue please be reopened.

**Comment by JoeBarisSpring** [comment]
We are seeing the same issue on our side, this is a still a huge problem @Eric-B-Wu - please can this issue be re-opened?
