### ISSUE TITLE
Workflow validation failed and is unable to switch to designer view

### ISSUE THREAD

**Issue by josegomes41** [Azure/LogicAppsUX#6079]
### Describe the Bug with repro steps 

All our consumption logic apps that use integration account (xslt transformation, liquid, edifact encoding) can't be edited in the portal and for some the logic app designer appears empty. We didn't change anything and this happens in different subscriptions and integrations accounts.

Error message:

![Image](<https://github.com/user-attachments/assets/dc011026-3ecd-413b-a5b3-c391a83304d9>)

Workflow Settings:

![Image](<https://github.com/user-attachments/assets/76121132-3561-473c-977d-b83ace07150a>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

*No response*

**Comment by Eric-B-Wu** [comment]
Hi @josegomes41 would you be able to try on our staging link https://portal.azure.com/?feature.canmodifystamps=true&Microsoft_Azure_EMA=staging#home there was a fix that is currently going out that is there to fix a code view issue where its unable to get the integration account

**Comment by josegomes41** [comment]
Hi @Eric-B-Wu 

I don't get the integration account error but for some logic apps I can't see anything in the designer:

Example:

![Image](https://github.com/user-attachments/assets/c859d4dc-e149-411d-9d3d-e4e19b334abf)

The logic runs and I can see the run details:

![Image](https://github.com/user-attachments/assets/ab4dfd7d-37a5-49a9-ad17-5662713b4f10)


Best Regards

**Comment by Eric-B-Wu** [comment]
Would you be able to send har and console logs to me at Wue@microsoft.com following these steps: https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#collecting-console-errors? This'll let me look at which part could be failing

**Comment by Eric-B-Wu** [comment]
closing issue, followed up through email - turned out to be Referenced shape does not exist issue due to new designer being case-sensitive
