### ISSUE TITLE
The renderComponentIntoRoot component encountered an error on the Arc Browser

### ISSUE THREAD

**Issue by FakieHeelflip** [Azure/LogicAppsUX#6084]
### Describe the Bug with repro steps 

In the designer of a Cosumption Logic App I face an Error in the Arc Browser while opening Azure Data Explorer KQL query Connector.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

MacOS

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/4279e436-ff2e-4ca3-921d-e5890e1d31a7>)

### Browser

Arc Browser

### Additional context

Error message in the console:

![Image](<https://github.com/user-attachments/assets/c445aec7-29c7-4b31-8f4c-e77d588ea3eb>)

**Comment by ccastrotrejo** [comment]
Hi @FakieHeelflip thanks for raising this issue. We wll take a look at our logs from the session id, but by any chance do you see any errors in the console or network tabs? Also, does this only happens in Arc browser?

**Comment by FakieHeelflip** [comment]
Hi @ccastrotrejo , thank you for the response. I added the console error messages into the issue post. Anyways, the creation of the kql connector with your provided link works in the Arc Browser. Thank you. When do you plan to deploy those changes?

**Comment by ccastrotrejo** [comment]
Hi @FakieHeelflip, thanks for letting us know about this. I am glad it's working now. This release is expected to be completed by Wednesday next week.
I will close this issue as its solved in the upcoming release
