### ISSUE TITLE
[Screen reader - Logic apps - Search]: Blank Tool tip is defined for the info icons present in the "Go to operation" dialog.

### ISSUE THREAD

**Issue by takyyon** [Azure/LogicAppsUX#6100]
### Describe the issue 

User Experience: 

 Keyboard dependent users and screen reader dependent users will get impacted if blank tool tip is defined as the user expects the tool tip to provide additional information or guidance for the users who want to learn more about the updates. 

 Note: User credentials should NOT be included in the bug.

Pre-requisites:

- Make sure dependencies such as Azure Logic Apps (Standard), Azure Functions, C# are installed. 
- Navigate to Azure control present on the right side and select it. 
- Navigate to LogicApp icon present under workspace section, click on tat and select 'Create New Project'. 
- Navigate select stateful workflow, then enter the name of the workflow. 
- Once the workflow has been created then enter the name of the created workflow in edit field present on the top and press Enter. 
- Navigate to 'Open in current window' and select it. 
- A dialog will appear, select 'Yes', now the workflow will open in new window. 

Repro Steps:

- Open Visual Studio app. 
- Navigate to any workflow and right click on it, then select 'open designer'. 
- Navigate to toolbar present on the left side of the screen at the bottom. 
- Navigate to Search control and select it. 
- After selecting the 'Search' control a blade appears on right side, check whether the user is able to search any action or not. 
- Observe whether blank tool tip is defined for the info icons present in the "Go to operation" dialog or not. 

Actual Result: 

 Blank Tool tip is defined for the info icons present in the "Go to operation" dialog as a result when focus moves to the info icons screen reader announces as "Undefined undefined graphic"

Expected result: 

 Blank Tool tip should not be defined for the info icons present in the "Go to operation" dialog.

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

*No response*

### Browser 

Chrome, Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
https://msazure.visualstudio.com/One/_workitems/edit/29364326
