### ISSUE TITLE
Edit swagger operation - Failed to fetch - stack

### ISSUE THREAD

**Issue by gaven-imei** [Azure/LogicAppsUX#6114]
### Describe the Bug with repro steps 

1. Edit logic app 
2. All swagger operations return the following error 

Unable to initialize operation details for operation - . Error details - {"message":"Failed to fetch","stack":"TypeError: Failed to fetch\n at https://portal.azure.com/Content/Dynamic/BeUd4hejqUig.js:113:24094","isError":true}

3. All my logic apps have the exact same error 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/c9130313-ab63-424d-af14-5822241aed2b>)

### Browser

Edge

### Additional context

*No response*

**Comment by hartra344** [comment]
This looks like something more specific to you that I'm not sure we can fix in a github issue. Please file a support request for more help on this.
