### ISSUE TITLE
Existing LogicApp which use Custom Connector will fail to save after promotion in Versions Menu.

### ISSUE THREAD

**Issue by koichi-ozawa-motex** [Azure/LogicAppsUX#6115]
### Describe the Bug with repro steps 

1. Open existing Logic App which is using Custom Connector in Azure Portal. 
2. Goto Versions menu. 
3. Select a version and "History Version" will appear in modern UI. 
4. There is a disabled "Promote" menu and "Errors" menu in UI. 
5. So promote is disabled that I cannot Promote（rollback to） old version of Logic App. 

Even if I use "https://aka.ms/lafallback" before opening logic app, it won't be effective.（It shows "History Version" in modern UI.）

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

MacOS

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http"
            }
        },
        "actions": {
            "GetTenant": {
                "type": "ApiConnection",
                "inputs": {
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['LANSCOPE']['connectionId']"
                        }
                    },
                    "method": "get",
                    "path": "/LanscopeTrial",
                    "queries": {
                        "tenantId": "OZAWA",
                        "debug": 0
                    }
                },
                "runAfter": {}
            }
        },
        "outputs": {},
        "parameters": {
            "$connections": {
                "type": "Object",
                "defaultValue": {}
            }
        }
    },
    "parameters": {
        "$connections": {
            "value": {
                "LANSCOPE": {
                    "id": "/subscriptions/xxx/resourceGroups/xxxx/providers/Microsoft.Web/customApis/LANSCOPE",
                    "connectionId": "/subscriptions/xxx/resourceGroups/xxxx/providers/Microsoft.Web/connections/LANSCOPE",
                    "connectionName": "LANSCOPE"
                }
            }
        }
    }
}
```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/91bcbb1f-29f8-471d-940f-ad1b04e4699f>)

### Browser

Chrome

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hi @koichi-ozawa-motex thanks for raising this issue. By the screenshot I can tell that something is going up with the custom connector actions, it might be failing due to the connection, however the only case/scenario in which the promote button gets disabled its when the version that you are trying to promote its the same version as the latest version. Could you please let me know if thats the case? if you click in other versions does this still happening?

**Comment by koichi-ozawa-motex** [comment]
Hi, @ccastrotrejo thank you for checking my issue. and i am sorry for my misunderstanding.
if i choose other version, the "Promote" button works.
But due to custom connector error, saving the promoted logic app failed. ( "https://aka.ms/lafallback" does not works)

![Image](https://github.com/user-attachments/assets/2bd35bb5-5745-4701-a6cf-ec4b27d0a7e7)

**Comment by ccastrotrejo** [comment]
Hi @koichi-ozawa-motex all right that makes sense. Is there any chance you can share with use workflow schema from the code view from the version that you are trying to promote and can't be saved?
