### ISSUE TITLE
Unauthorized : Unauthorized access for 'Receive' operation on endpoint 'sb://servicebusibmi.servicebus.windows.net/connector_withoutsessionid'

### ISSUE THREAD

**Issue by SurajSurendranZeus88** [Azure/LogicAppsUX#6143]
### Describe the Bug with repro steps 

},

 "body": {

 "status": 401,

 "message": "40100: Unauthorized : Unauthorized access for 'Receive' operation on endpoint 'sb://servicebusibmi.servicebus.windows.net/connector\_withoutsessionid'. Tracking Id: 4c7f9bb5-9337-40b8-b652-39f6db79df56\_G9, Resource:sb://servicebusibmi.servicebus.windows.net/connector\_withoutsessionid. TrackingId:4c7f9bb5-9337-40b8-b652-39f6db79df56\_G9, SystemTracker:servicebusibmi.servicebus.windows.net:connector\_withoutsessionid, Timestamp:2024-11-19T13:39:15\r\nclientRequestId: 56407ef4-f7b4-4bfd-b47d-8c687e3afde9",

 "error": {

 "message": "40100: Unauthorized : Unauthorized access for 'Receive' operation on endpoint 'sb://servicebusibmi.servicebus.windows.net/connector\_withoutsessionid'. Tracking Id: 4c7f9bb5-9337-40b8-b652-39f6db79df56\_G9, Resource:sb://servicebusibmi.servicebus.windows.net/connector\_withoutsessionid. TrackingId:4c7f9bb5-9337-40b8-b652-39f6db79df56\_G9, SystemTracker:servicebusibmi.servicebus.windows.net:connector\_withoutsessionid, Timestamp:2024-11-19T13:39:15"

 },

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

chrome

### Additional context

*No response*

**Comment by hartra344** [comment]
There is no details here on what you were doing or where you saw this error. I'm not able to triage without that information. Please reopen if you're able to provide it.
