### ISSUE TITLE
Saving from CodeView failed to identify the associated integration account

### ISSUE THREAD

**Issue by devwagner** [Azure/LogicAppsUX#6144]
### Describe the Bug with repro steps 

1. Create a logic app with the Consumption model 
2. Associate an integration account 
3. Go to the ***Designer*** and add an action that requires an integration account (like JavaScriptCode) 
4. Save the logic app in the designer (it should work just fine) 
5. Now switch to ***Code View*** 
6. Make any change to the code and hit save 
7. The following error will be displayed

`An error occurred when trying to save workflow: 'The workflow must be associated with an integration account to use the workflow run action 'My_Action' of type 'JavaScriptCode'.'` 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/7aa79dee-ae16-42d4-afe4-7eeb70be4a5b>)

### Browser 

- Browser: Edge 

### Additional context 

When saving the logic app from the ***Code View*** it fails to identify the associated integration account. This issue does not happen when saving the logic app from the ***Designer***.

**Comment by hartra344** [comment]
This is a known issue that is being fixed in our next release. It's going to be a little slow to get out though because of deployment freezes related to the holidays. In the meantime feel free to use this link to force the new version with the fix: https://aka.ms/emastage1
