### ISSUE TITLE
Logic app "Save" operation doesn't take effect even the notifications show that "Successfully save the workflow". Furthermore, even we didn't change the workflow again, the Save operation will show and let us save again.

### ISSUE THREAD

**Issue by serenaliqing** [Azure/LogicAppsUX#6153]
### Describe the Bug with repro steps 

1. Go to the logic app designer 
2. Change the workflow's http action's endpoint 
3. Click "Save", it shows "Successfully Save" 
4. However, when we check the actual endpoint, it keeps the original version. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

*No response*

**Comment by hartra344** [comment]
When you save, can you verify in the code view(or hard refresh) that the changes did in fact not save. If you check the endpoint immediately after saving, you could be hitting a worker that hasn't picked up the change yet. It can take 10-20 seconds for the change to be picked up on the backend.

**Comment by serenaliqing** [comment]
> When you save, can you verify in the code view(or hard refresh) that the changes did in fact not save. If you check the endpoint immediately after saving, you could be hitting a worker that hasn't picked up the change yet. It can take 10-20 seconds for the change to be picked up on the backend.

Hi Experts, thank you for your response. Our observation is that the workflow can save the change and even execute with the change successfully for a while. However, after the first test, cx left the logic app for a while without any other change . Amazing, when cx opened it again, the workflow turns out to be the previous version. It seems that the workflow reverted the code back silently without any notifications.  We're looking forward to your insights here.

**Comment by hartra344** [comment]
So it happened 1 time but can't repro?
