### ISSUE TITLE
Existing Form Recognizer Actions issue

### ISSUE THREAD

**Issue by mvitoloaitana** [Azure/LogicAppsUX#6155]
### Describe the Bug with repro steps 

1, Access your Logic App Workflow

2. Click on a Form Recognizer action 
3. It is blocked 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
"Classifier_": {
                                "type": "ApiConnection",
                                "inputs": {
                                    "host": {
                                        "connection": {
                                            "referenceName": "formrecognizer"
                                        }
                                    },
                                    "method": "post",
                                    "body": "@outputs('Compose_JSON_to_create_file')",
                                    "path": "/documentClassifiers/@{encodeURIComponent('AutodocsTestClassification-S5-v2')}:analyze",
                                    "queries": {
                                        "api-version": "2023-07-31"
                                    }
                                },
                                "runAfter": {
                                    "Compose_JSON_to_create_file": [
                                        "SUCCEEDED"
                                    ]
                                }
                            },
```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/7e3fa5a9-8eff-42ac-98f5-776512de1aee>)

### Browser

Chrome

### Additional context

*No response*

**Comment by queoStefanWallimann** [comment]
Hi,

Same issue here with a logic app that was working fine until two days ago. Clicking on the component shows the loading circle only

![Image](https://github.com/user-attachments/assets/fd34b59a-3c97-45bf-adb0-f961b26fe979)

**Comment by mvitoloaitana** [comment]
@queoStefanWallimann The solution is: 

1. Go to code view;
2. Add  to the action path the following: /formrecognizer like this:
"path": "/formrecognizer/documentClassifiers/@{encodeURIComponent('AutodocsTestClassification-S5-v2')}:analyze".

It seems Microsoft changed the urls without guaranteeing the retro-compatibility.

**Comment by queoStefanWallimann** [comment]
Thanks @mvitoloaitana ... will do

**Comment by JulienVLC** [comment]
Hello,
The error is back, now you have to remove **/formrecognizer** from the path...
