### ISSUE TITLE
EnvironmentCredential is unavailable. No underlying credential could be used.

### ISSUE THREAD

**Issue by danielenriquez** [Azure/LogicAppsUX#6156]
Does this occur consistently? 

 Repro steps:

1. From Visual Studio Code, right-click on my LA project and try to deploy the Logic App to Azure resource group 

Action: azureLogicAppsStandard.deploy

 Error type: AggregateAuthenticationError

 Error Message: EnvironmentCredential is unavailable. No underlying credential could be used. To troubleshoot, visit redacted:URL

Version: 4.107.4

 OS: win32

 OS Release: 10.0.22621

 Product: Visual Studio Code

 Product Version: 1.95.3

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by hartra344** [comment]
duplicate, linked to parent
