### ISSUE TITLE
LogicApps workflow deployment fails with "Please provide below info when asking for support:"

### ISSUE THREAD

**Issue by yk2492** [Azure/LogicAppsUX#6162]
Does this occur consistently?: Yes

 Repro steps:

1. Under Azure > WORKSPACE, select the Azure Logic Apps icon. 
2. [Deploy to logic app…] Click. 
3. Under Select the folder to deploy, click Browse, and then click the folder for the workflow that you created. 
4. Under Select subscription, click the subscription in which LogicApps resides. 
5. After that, an error occurs. You will not be prompted to select LogicApps.

 Until last month, we were able to deploy, but I don't know what has changed. 

Action: azureLogicAppsStandard.deploy

 Error type: AccessDenied

 Error Message: Please provide below info when asking for support: timestamp = redacted:id21T02redacted:id1152979Z, correlationId = redacted:id.

Version: 4.107.4

 OS: win32

 OS Release: 10.0.22621

 Product: Visual Studio Code

 Product Version: 1.95.3

 Language: ja

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
Hi @yk2492 thanks for raising this issue. If this is blocking your deployment you can please downgrade the extension to version 4.107.3. 
Could you please let me know the correlationId that you are getting?

Also could you please try to sign in using the new "Azure: Sign In" command contributed by the Azure Resources extension. Note: make sure you don't mistake it for the old Azure Account "Azure: Sign In" command.

![Image](https://github.com/user-attachments/assets/3554d33e-fb31-41fc-b0b7-627b17d9ae69)

**Comment by yk2492** [comment]
@ccastrotrejo 
Thank you for your support. Improved by downgrading to version 4.107.3.
You used Azure: SignIn: for "azureResourceGroups".

**Comment by ccastrotrejo** [comment]
I will close this issue and set the parent issue  #6149.
