### ISSUE TITLE
Consumption: Encountering an error page when trying to create an integration account

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#6167]
### Describe the Bug with repro steps 

1\.Search for integration account in azure portal

 2\.Click on create button

**Expected:** Clicking on the create button above should open the Full screen create blade.

**Actual:** Clicking on the create button showing an error page

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/6ec30161-0dc7-4b22-910a-dec54c2a2def>)

### Browser

Edge

### Additional context

**Version:** 0\.2022.1.794

**Comment by Eric-B-Wu** [comment]
note this is a blocking issue, so let's not do any prod deployments before this is fixed

**Comment by Eric-B-Wu** [comment]
complete in portal repo
