### ISSUE TITLE
getting 400 error while deploying logic app

### ISSUE THREAD

**Issue by SarangRapid** [Azure/LogicAppsUX#6170]
Does this occur consistently? 

 Repro steps:

1\.

 2\.

Action: azureLogicAppsStandard.deploy

 Error type: 400

 Error Message: Unexpected status code: 400

Version: 4.107.4

 OS: win32

 OS Release: 10.0.22631

 Product: Visual Studio Code

 Product Version: 1.95.3

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
Hi @SarangRapid thanks for raising this issue. I have some followup questions about this.
- Does this happens consistently? 
- Is there any chance you can let us know the steps you took to get this issues?
- Are you trying to deploy to a logic app already created in Azure portal?

**Comment by ccastrotrejo** [comment]
Closing as it might be related to #6149
