### ISSUE TITLE
How To Switch Back To Old Designer

### ISSUE THREAD

**Issue by influential-eliot** [Azure/LogicAppsUX#6171]
### Describe the Bug with repro steps 

This new designer is basically unusable, and leaves half my screen unused, not to mention I cannot see everything on the screen at once.

Where is the link to switch back?

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by hartra344** [comment]
There is no option to switch back. We are in the process of fully removing the code for the legacy designer.

**Comment by influential-eliot** [comment]
This is multiplying the amount of work required for development exponentially due to the absolutely awful UX/UI, which increases business costs ... I'm just going to have to develop my own front end for this awfulness. Shame.

**Comment by hartra344** [comment]
If you have specific feedback items to what could make this better for you, we're happy to listen, please create issues on those. Legacy Designer however hasn't been updated in nearly 3 years and at this point it has to be removed for multiple reasons.
