### ISSUE TITLE
logic app standard extension error

### ISSUE THREAD

**Issue by practice-mm** [Azure/LogicAppsUX#6174]
Does this occur consistently? 

 Repro steps:

1\.

 2\.

Action: azureLogicAppsStandard.pickProcess

 Error type: Error

 Error Message: Failed to stop previous running Functions host within "30" seconds. Make sure the task has stopped before you debug again.

Version: 4.107.4

 OS: win32

 OS Release: 10.0.19045

 Product: Visual Studio Code

 Product Version: 1.95.3

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by hartra344** [comment]
not enough information
