### ISSUE TITLE
Logic app consumption designer blade crashes if we add multiple rows in condition action

### ISSUE THREAD

**Issue by JaganMSFTGitHub** [Azure/LogicAppsUX#6175]
### Describe the Bug with repro steps

1. Open a logic app consumption workflow.
2. Add a "Condition" action.
3. In the action configuration, click on "New Item".
4. Click "Add row" once. Nothing happens.

![Image](https://github.com/user-attachments/assets/154a68bb-0c1c-43bc-99ae-fb9e8703791c)

6. Click "Add row" once again. The designer will crash.

![Image](https://github.com/user-attachments/assets/0b531f50-06d9-403d-a96c-6b648753f9ec)

7. NOTE: This issue appears only if the first row is blank, and we try to add new rows. If the first row has some data already filled in and we click on "Add row", then the issue does not reproduce.

![Image](https://github.com/user-attachments/assets/381437b3-15a5-4612-8450-14f09729a9be)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Which operating system are you using?

Windows

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json

```

### Browser

Edge

**Comment by Eric-B-Wu** [comment]
This was fixed in https://github.com/Azure/LogicAppsUX/pull/5986, but due to deployment freeze it hasn't been deployed yet, please use https://portal.azure.com/?feature.canmodifystamps=true&Microsoft_Azure_EMA=stage1#home for mitigation
