### ISSUE TITLE
Unable to delete and ungroup rows in the condition action in logic app consumption

### ISSUE THREAD

**Issue by JaganMSFTGitHub** [Azure/LogicAppsUX#6176]
### Describe the Bug with repro steps

1. Open a logic app consumption workflow. 
2. Add a "Condition" action.
3. Add couple of rows.
4. Try to delete any row by clicking the "Delete" button. Nothing happens. The row does not get deleted.

 ![Image](https://github.com/user-attachments/assets/cc63d5b4-f76d-457b-bfc2-f9e9c6f8ca4a)

5. Similarly, we can't "Ungroup" the rows from a group. The "Ungroup" button also does not respond.

![Image](https://github.com/user-attachments/assets/9da50d1f-c13c-4a05-a278-73840ca4356c)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Which operating system are you using?

Windows

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json

```

### Browser

Edge

**Comment by Eric-B-Wu** [comment]
This was fixed in https://github.com/Azure/LogicAppsUX/pull/5986, but due to deployment freeze it hasn't been deployed yet, please use https://portal.azure.com/?feature.canmodifystamps=true&Microsoft_Azure_EMA=stage1#home for mitigation

**Comment by JaganMSFTGitHub** [comment]
Hello @Eric-B-Wu 

May I know when this fix will be deployed? Any timeline for the deployment freeze to get over?

**Comment by Eric-B-Wu** [comment]
Our next possible deployment due to the freeze will not be until the first half of January 2025, where the fix for this will be deployed
