### ISSUE TITLE
Missing delete, feedback and getting started options

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#6177]
### Describe the Bug with repro steps 

1. Create a standard logic app 
2. Create a stateful/stateless workflow 

**Expected:** Should able to see delete, feedback and getting started options 

**Actual:** Missing delete, feedback and getting started options

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/dee1708e-043a-456d-914c-c8b79adf243b>)

![Image](<https://github.com/user-attachments/assets/577c71f0-7754-4519-b944-756ae7b1f617>)

### Browser

Edge

### Additional context

*No response*

**Comment by hartra344** [comment]
This is a change by design that is going out in January. @Eric-B-Wu  can you work with the testers to make sure they are up to date on the new menu flow?
