### ISSUE TITLE
Save button is grayed out but still working in Settings blade

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#6181]
### Describe the Bug with repro steps 

1\.Create a standard logic app

 2\.Create a stateful/stateless workflow

3. Open the workflow 

**Expected:** Save button should not be enabled and work unless until there are changes made.

**Actual :** Save button is grayed out but still working in Settings blade under configuration blade

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/a98c853e-c8aa-4718-a8f7-63e425666a06>)

### Browser

Edge

### Additional context

**Version:** 0\.2022.1.796

**Comment by ccastrotrejo** [comment]
Issue is solved in Portal Repo
