### ISSUE TITLE
Consumption: Encountering an error page when trying to create a Logic Apps Custom Connector

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#6182]
### Describe the Bug with repro steps 

1\.Search for Logic Apps Custom Connector in azure portal

 2\.Click on create button

**Expected:** Clicking on the create button above should open the Full screen create blade for Logic Apps Custom Connector.

**Actual:** Clicking on the create button showing an error page

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/ae25de7b-3909-43cf-b43c-e0a3fafc196a>)

### Browser

Edge

### Additional context

**Version:**0\.2022.1.796

**Comment by Eric-B-Wu** [comment]
using https://github.com/Azure/LogicAppsUX/issues/6167 as tracking
