### ISSUE TITLE
new designer in logic app freezes and then fails to load content

### ISSUE THREAD

**Issue by ZedFarNl** [Azure/LogicAppsUX#6184]
### Describe the Bug with repro steps 

1- Go to logic app, one of the latest runs including a http call which expects json as output body. 

 2- View the run in the new design mode. 

 3- Click on the HTTP call to see the input and output of the run.

 4- UI freezes and after showing mesage"loading input" for a long time, it shows a failed emoji instead of loading the content.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/5be4eaaf-dde8-4a49-8ae8-4a22ba5da9fa>)

![Image](<https://github.com/user-attachments/assets/ed2daa2e-6177-4429-88cb-3f0fd9f2e6ae>)

### Browser

Chrome

### Additional context

*No response*

**Comment by hartra344** [comment]
@ZedFarNl are you able to open a support case for this? It's not a normal scenario we're seeing with anyone else and we're going to need some more information from you in order to triage.

**Comment by hartra344** [comment]
@ZedFarNl can you try https://aka.ms/emastage1 and see if that works for you. We have a fix for this issue but it's not fully rolled out to production yet as we're frozen for the holidays, but if the link above works (It forces you to use a region with a newer version of the portal) then you can continue using that until it's fully fixed in production.

**Comment by ccastrotrejo** [comment]
@ZedFarNl do you see any errors in the console or network tab?
Is there any chance we can get one HAR file when you use Edge and the designer freezes?
You can follow this guide to [collect the HAR file](https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file). Please send the file to my email: ccastrotrejo@microsoft.com The file might contain sensitive data
