### ISSUE TITLE
Filter Array Data Operation is not working

### ISSUE THREAD

**Issue by gschultz125** [Azure/LogicAppsUX#6187]
### Describe the Bug with repro steps 

Created an array.

{

 "type": "InitializeVariable",

 "inputs": {

 "variables": [

 {

 "name": "array",

 "type": "array",

 "value": [

 {

 "fieldId": "11145351652",

 "name": "templateUsageRestriction",

 "show": "false",

 "required": "false",

 "value": "advancedOptionOnly"

 },

 {

 "fieldId": "11145351653",

 "name": "NBPTS Approval",

 "show": "false",

 "required": "false",

 "value": ""

 },

 {

 "fieldId": "11145351649",

 "name": "New Hire Form",

 "show": "false",

 "required": "false",

 "value": "OnboardingAppropriateUseofTechnology"

 },

 {

 "fieldId": "11145351650",

 "name": "New Hire Folder",

 "show": "false",

 "required": "false",

 "value": "Gary\_GT\_Schultz"

 },

 {

 "fieldId": "11145351651",

 "name": "New Hire HR Creator Email",

 "show": "false",

 "required": "false",

 "value": "Gary.Schultz@dpi.wi.gov"

 }

 ]

 }

 ]

 },

 "runAfter": {

 "Compose": [

 "SUCCEEDED"

 ]

 }

 }

I added parse json action.

{

 "type": "ParseJson",

 "inputs": {

 "content": "@variables('array')",

 "schema": {

 "type": "array",

 "items": {

 "type": "object",

 "properties": {

 "fieldId": {

 "type": "string"

 },

 "name": {

 "type": "string"

 },

 "show": {

 "type": "string"

 },

 "required": {

 "type": "string"

 },

 "value": {

 "type": "string"

 }

 },

 "required": [

 "fieldId",

 "name",

 "show",

 "required",

 "value"

 ]

 }

 }

 },

 "runAfter": {

 "Initialize\_variable": [

 "SUCCEEDED"

 ]

 }

 }

I added a filter arrayr action.

{

 "type": "Query",

 "inputs": {

 "from": "@body('Parse\_JSON\_1')",

 "where": "@equals(item()['name'],'New Hire HR Creator Email')"

 },

 "runAfter": {

 "Parse\_JSON\_1": [

 "Succeeded"

 ]

 }

 }

Null is returned. I see that issue #5820 was repoerted for the same issue. Unlike #5820, I can no longer use the legacy designer test.

[https://github.com/Azure/LogicAppsUX/issues/5820](<https://github.com/Azure/LogicAppsUX/issues/5820>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
duplicate, linked to parent
