### ISSUE TITLE
'Set as default page' button also showing refreshing symbol when we click on refresh button.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#6193]
### Describe the Bug with repro steps 

1. Create a standard logic app 
2. Create a stateful/stateless workflow 
3. Make designer blade as default page to open when we open any workflow present in logic app by clicking on 'Set as default page' button in one workflow. 
4. Select run history blade 
5. Click on refresh button. 

**Expected:** Only refresh button should show refreshing symbol when we click on refresh button.

**Actual:** 'Set as default page' button also showing refreshing symbol when we click on refresh button along with refresh button.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

[https://github.com/user-attachments/assets/dc1d2f1e-45f4-4b3c-a05f-ac73918ad383](<https://github.com/user-attachments/assets/dc1d2f1e-45f4-4b3c-a05f-ac73918ad383>)

### Browser

Edge

### Additional context

**Version:**0\.2022.1.796

**Comment by ccastrotrejo** [comment]
Issue will be solved in next portal release. PR fix link: https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/11333358
