### ISSUE TITLE
Issue while migrating the Consumption Logic App to Standard Logic App.

### ISSUE THREAD

**Issue by gurupraneshkrishnan** [Azure/LogicAppsUX#6200]
Does this occur consistently? YES

 Repro steps:

1. We are trying to follow the instructions from the Azure Docs

*[https://learn.microsoft.com/en-us/azure/logic-apps/export-from-consumption-to-standard-logic-app](<https://learn.microsoft.com/en-us/azure/logic-apps/export-from-consumption-to-standard-logic-app>)* 
2. Exported the Consumption Logic App in to VS Code and modified all the connections. 
3. When Trying to Deploy the same to standard Logic App, we receive an error with Access Denied. 

Action: azureLogicAppsStandard.deploy

 Error type: AccessDenied

 Error Message: Please provide below info when asking for support: timestamp = redacted:id02T11redacted:id5526237Z, correlationId = redacted:id.

Version: 4.107.4

 OS: win32

 OS Release: 10.0.19045

 Product: Visual Studio Code

 Product Version: 1.95.3

 Language: en

<details><summary>Call Stack</summary> <p></p><precode language="" precodenum="0"></precode><p></p></details>

![Image](<https://github.com/user-attachments/assets/74c23eb2-832b-48d8-a326-dec28a3e3d54>)

**Comment by ccastrotrejo** [comment]
Hi @gurupraneshkrishnan thanks for raising this issue. It is related to some credentials access when trying to deploy.

- Are you trying to deploy to a Hybrid Logic App or a Standard Logic App?


As a workaround you can downgrade the vscode extension version to 4.107.3.

**Comment by gurupraneshkrishnan** [comment]
Thank you @ccastrotrejo ,

We are deploying a Standard Logic App. I was able to downgrade the Standard Logic App extension to 4.107.3 and deploy the Logic App. It was successful.

**Comment by ccastrotrejo** [comment]
I will close this issue as duplicated for the #6149 . Please use the workaround of downgrading to a previous vsix or use the provided private vsix on the parent GitHub Issue.
