### ISSUE TITLE
HTTP trigger logic app with array type as input prompts save without changes

### ISSUE THREAD

**Issue by nicholasdemos** [Azure/LogicAppsUX#6206]
### Describe the Bug with repro steps 

1. Create a new consumption logic app with a HTTP trigger 
2. In the Request Body JSON Schema, define an input property of type "array" 
3. Save and close the Logic App 
4. Click Edit to open the logic app in designer view 
5. Observe the Save button is enabled, prompting for save when no edits have been made 
6. Closing the designer without any editing also then prompts dialog "Your unsaved edits will be discarded." 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "schema": {
                        "properties": {
                            "p1": {
                                "type": "array"
                            }
                        },
                        "required": [
                            "p1"
                        ],
                        "type": "object"
                    }
                }
            }
        },
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "Http",
                "inputs": {
                    "statusCode": 200,
                    "body": "@triggerBody()"
                },
                "runAfter": {}
            }
        },
        "outputs": {},
        "parameters": {
            "$connections": {
                "type": "Object",
                "defaultValue": {}
            }
        }
    },
    "parameters": {
        "$connections": {
            "value": {}
        }
    }
}
```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hi @nicholasdemos thanks for raising this issue. I was able to repro it. I will come up with a fix for it

**Comment by ccastrotrejo** [comment]
Hi @nicholasdemos, I have made the necessary changes for the fix. This will be deployed to production by mid-January next year. However, it seems that the workflow functionality is not affected. The issue only causes the designer to appear as if it has been modified and enables the command bar buttons. Other than that, everything should work as expected. Please let us know if you encounter any issues.

**Comment by nicholasdemos** [comment]
Hi @ccastrotrejo , that's great news, thank you for the update.
