### ISSUE TITLE
Filter Array contains and starts with do not work

### ISSUE THREAD

**Issue by gschultz125** [Azure/LogicAppsUX#6211]
### Describe the Bug with repro steps 

Create an array using initialize array action.

Filter Array action using equals works.

{

 "type": "Query",

 "inputs": {

 "from": "@variables('some array')",

 "where": "@equals(item()?['value'],'some text')"

 },

 "runAfter": {

 "Initialize\_variable\_some\_array": [

 "Succeeded"

 ]

 }

 }

Filter Array using contains and starts with fails with the following message.

InvalidTemplate

 The execution of template action 'Filter\_array' failed: The evaluation of 'query' action 'where' expression '@contains(item()?['value'],'some text')' failed: 'The template language function 'contains' expects its first argument 'collection' to be a dictionary (object), an array or a string. The provided value is of type 'Null'.'.

Code

 {

 "type": "Query",

 "inputs": {

 "from": "@variables('some array')",

 "where": "@contains(item()?['value'],'some text')"

 },

 "runAfter": {

 "Initialize\_variable\_some\_array": [

 "Succeeded"

 ]

 }

 }

Starts with

{

 "type": "Query",

 "inputs": {

 "from": "@variables('some array')",

 "where": "@startsWith(item()?['value'],'some text')"

 },

 "runAfter": {

 "Initialize\_variable\_some\_array": [

 "Succeeded"

 ]

 }

 }

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by hartra344** [comment]
You opened the same issue last week which was closed as a duplicate. Feel free to follow the issue here: #5820

Per the issue pinned at the top of our issues, we are currently under a deployment freeze for the holidays, so the fix will not be in production until Mid January. In the meantime you can use the link in the issue above to use a newer version of designer.
