### ISSUE TITLE
If we go back and forth between the designer and code view, the action will not load properly.

### ISSUE THREAD

**Issue by metakahash1** [Azure/LogicAppsUX#6217]
### Describe the Bug with repro steps 

1. Add a managed connector to workflow

 This example uses the [Office 365 Outlook] connector.

![Image](<https://github.com/user-attachments/assets/4f3d0abf-0abc-43eb-91c0-9b6f76fc4444>)

 
2. Go to Code View without saving the workflow

![Image](<https://github.com/user-attachments/assets/e3b85bce-a203-48a0-b0f4-b74653f8ec70>)

 
3. Save on CodeView

 Save the workflow in the Code View screen without making any changes.

![Image](<https://github.com/user-attachments/assets/a1f409bb-80a3-451f-b19b-0727fd3c17aa>)

 
4. Back to Designer

 Press this button to return to the designer.

![Image](<https://github.com/user-attachments/assets/f879c9d7-1b3d-49ee-9392-2ac6f7dfbc61>)

 

The connector cannot be read properly and an error occurs.

![Image](<https://github.com/user-attachments/assets/4e8757ab-544a-4941-8513-5fc5d2b30f50>)

This also occurs with other managed connectors.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by hartra344** [comment]
Is this happening in China cloud or Public Azure? If it's happening in public azure can you try on the following link: https://aka.ms/emastaging

**Comment by metakahash1** [comment]
Hi @hartra344 , sorry for the late reply. This issue occurred in Public Azure.
