### ISSUE TITLE
Runs view prompts to confirm loosing changes when leaving current run view

### ISSUE THREAD

**Issue by james-seddon-paymentsense** [Azure/LogicAppsUX#6232]
### Describe the Bug with repro steps 

1. Go to the runs view of a logic app and open a run 
2. Click on another run, you will be prompted with "Your unsaved edits will be discarded." 

This behaviour was not present in the legacy designer, and seems pointless in the new designer given no changes can be made in the runs view.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/f1fd804f-0321-432a-a4de-a02d00148929>)

### Browser

Chrome

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hi @james-seddon-paymentsense thank you so much for raising this issue. We have noticed this issue and we have worked on a fix for it. The fix its in the following PR https://github.com/Azure/LogicAppsUX/pull/6224

This will be deployed to production by mid-January next year. However, it seems that the workflow functionality is not affected. The issue only causes the designer to appear as if it has been modified, therefore it shows the alert. Other than that, everything should work as expected.

I will be closing this issue as duplicated for the following issue https://github.com/Azure/LogicAppsUX/issues/6206. I also marked it as the parent of this.
