### ISSUE TITLE
Unable to write settings while installing binaries

### ISSUE THREAD

**Issue by B8nk1028** [Azure/LogicAppsUX#6240]
Does this occur consistently?

Repro steps:

1\.

2\.

Action: azureLogicAppsStandard.validateAndInstallBinaries

Error type: Error

Error Message: Unable to write into user settings because the file has unsaved changes. Please save the user settings file first and then try again.

Version: 4.107.4

OS: win32

OS Release: 10.0.26120

Product: Visual Studio Code

Product Version: 1.95.3

Language: en

<details><summary>Call Stack</summary>¨NBSP;<p>¨NBSP;</p><p> </p></details>

**Comment by ccastrotrejo** [comment]
Hi @B8nk1028 thanks for raising this issue. I took a look at the error message, and it seems that it doesn't come from our extension, rather it comes from the vscode itself about not saving the changes while updating the settings. When we install the binaries we do update the settings.

I have never seen this issue before. By any chance did you have the settings window from vscode opened while the binaries were installed? Did you updated manually any settings?

**Comment by B8nk1028** [comment]
so i believe azure broke... but now git is have a problem 
i believe i was hit with a root kit. so now ive bought win 11 usb. and am having unlucky success at finding another computer to download a new mbr and drivers 
so i will update after i reinstall everything 
but my git is now saying rebase error 
i got a lot going on here thats all bad it seems feel free to close this. thanks for your help tho
