### ISSUE TITLE
Now Logic app designer is not working properly. I am using a connector and it failed to load and not showing any error message

### ISSUE THREAD

**Issue by akshatgupta02** [Azure/LogicAppsUX#6246]
### Describe the Bug with repro steps 

1. go to logic apps 
2. add sftp-ssh action with list file folder option 
3. add all the details, it will make connection but give some wrong folder path 
4. save the logic app and refresh browser 
5. click on sftp-ssh connector again 
6. in designer you will get the error: 'Error fetching manifest' 
7. and nothing will open in right pop-up detail window. it just keep on loading 

![Image](<https://github.com/user-attachments/assets/feb937da-4732-413a-ba12-eb8f09d947c3>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/caaef385-0251-4c0b-b31a-619c992ea504>)

### Browser

Chrome

### Additional context

the new logic app designer has many bugs and many it's creating lot of problems in daily development and support activities. Classic designer was more robust

**Comment by takyyon** [comment]
Can you please share your workflow? Also, would you be able to elaborate on "new logic app designer has many bugs", what other issues are you seeing? It will be helpful if you could create github issue for ones you see.
