### ISSUE TITLE
Do Until action displays invalid condition after saving (VsCode)

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [Azure/LogicAppsUX#6250]
### Describe the Bug with repro steps 

This happens when using a "is not equal to" in basic mode. It may also happen with others.

> Before save:
> 
> ![Image](<https://github.com/user-attachments/assets/385c3ace-8189-4fa9-b69d-e7e004768b07>)

> After save:
> 
> ![Image](<https://github.com/user-attachments/assets/399406df-a76e-4ba9-980e-88ed9e82d2d5>)

> Code view is correct:
> 
> ![Image](<https://github.com/user-attachments/assets/587e2202-a3c1-4da2-8d67-d02c1b4b8d2e>)

So this appears to be a visual bug **except** if you touch the input after this bug has occurred the change will be recorded on save.

> After blur + save:
> 
> ![Image](<https://github.com/user-attachments/assets/8305d338-eec3-4f42-a3ed-1806fe64a187>)

**Repro**

1. Create new workflow 
2. Create until action 
3. Enter any values either side of condition 
4. Change condition to "is not equal to" 
5. Save (input should now be in advanced mode as in screenshots) 
6. Check code view to verify inconsistent view/model 
7. Click inside advanced mode input 
8. Hit save (if you can't, add another action or something and then save) 
9. Verify the model is now consistent with view (with an invalid condition) 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

VsCode

### Additional context

*No response*

**Comment by Eric-B-Wu** [comment]
Hi @Andrew-Lahikainen, this is a known issue, but unfortunately due to code freeze our [fix for it](https://github.com/Azure/LogicAppsUX/pull/5980) has not yet been deployed. If you are working on VSCode, I'd recommend reverting to a previous version for this issue until early/mid january once this fix goes in
