### ISSUE TITLE
Workflow action name can contain special characters in local designer

### ISSUE THREAD

**Issue by teunvandemerwe** [Azure/LogicAppsUX#6252]
### Describe the Bug with repro steps 

1. Create a workflow with a trigger and some actions in the designer locally 
2. Rename one of the actions with a ? in the name 
3. Save it in designer 
4. Do above in Azure portal to create a workflow 
5. Portal returns following error: 

"Workflow validation failed for the workflow 'ans-offramp-person'. {"error":{"code":"InvalidWorkflowTriggerName","message":"The provided workflow trigger name 'When\_messages\_for\_ans-offramp\_are\_available\_(peek-lock)?' has these invalid characters '?'. The name cannot contain any control characters or any of the following symbols: '\"\", \"%\", \"&\", \"\\", \"?\", \"/\"'."}}"

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

n.a.

### Browser

n.a.

### Additional context

What I expect is that local designer also returns the error:

"Workflow validation failed for the workflow 'ans-offramp-person'. {"error":{"code":"InvalidWorkflowTriggerName","message":"The provided workflow trigger name 'When\_messages\_for\_ans-offramp\_are\_available\_(peek-lock)?' has these invalid characters '?'. The name cannot contain any control characters or any of the following symbols: '\"\", \"%\", \"&\", \"\\", \"?\", \"/\"'."}}"

Already tried solving it using the workflowdefinition.json template as validation schema for my workflow though that still passes

**Comment by takyyon** [comment]
Just to confirm, do you mean vscode by "local" designer here?

**Comment by teunvandemerwe** [comment]
> Just to confirm, do you mean vscode by "local" designer here?

Yes

**Comment by ccastrotrejo** [comment]
Hi @teunvandemerwe thanks for raising this issue. 
There are two main issues here:
- Being able to rename the action with invalid char, or perform any other invalid action and save it: This is by design, the idea for the local development is to allow developers to save a work in progress even if its not valid.
- Save invalid workflow and not notify the user about it: For this there is an ongoing effort from the backend team to allow us to validate the workflow when saving it locally, this still allow users to save invalid work but will notify it. https://github.com/Azure/logicapps/issues/1224

**Comment by teunvandemerwe** [comment]
> Hi [@teunvandemerwe](https://github.com/teunvandemerwe) thanks for raising this issue. There are two main issues here:
> 
> * Being able to rename the action with invalid char, or perform any other invalid action and save it: This is by design, the idea for the local development is to allow developers to save a work in progress even if its not valid.
> * Save invalid workflow and not notify the user about it: For this there is an ongoing effort from the backend team to allow us to validate the workflow when saving it locally, this still allow users to save invalid work but will notify it. [It can deploy the illegal code via VSCode without validation error.  logicapps#1224](https://github.com/Azure/logicapps/issues/1224)

Hi @ccastrotrejo,

Thanks for the clarification. I will keep an eye notificatie solution.
