### ISSUE TITLE
New designer code view is broken when switching between designer and code

### ISSUE THREAD

**Issue by Xiaoyu-Huang** [Azure/LogicAppsUX#6257]
### Describe the Bug with repro steps 

1. Go to workflow using parameters in designer view 
2. Switch to code view without making any changes 
3. Switch back to designer view, it throws validation error. 

![Image](<https://github.com/user-attachments/assets/7511ba7f-3ad0-4700-8d30-2ab874e8d31b>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
contact me if you need this
```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

![Image](<https://github.com/user-attachments/assets/b5f055c3-0214-4987-b0a7-415503c84037>)

**Comment by Eric-B-Wu** [comment]
Created a PR on portal side
