### ISSUE TITLE
unable to create outlook connection

### ISSUE THREAD

**Issue by PrateekPrakkash** [Azure/LogicAppsUX#6279]
### Describe the Bug with repro steps 

when I try to add a task for "send an email(v2)" for Outlook connector and sign in using my email address, it fails and says the account doesnot exist.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by Elaina-Lee** [comment]
Hi @PrateekPrakkash, I tried reproducing this but was unable to. Were you able to try signing in with a different account by chance?

**Comment by ccastrotrejo** [comment]
Hi @PrateekPrakkash, we host 2 different outlook connectors. Just to make sure of what is going on here, are you using the `"send an email(v2)"` from the `Outlook` connector or from the `Office 365` connector? This will completely depend on the type of account that you are trying to sign in.

**Comment by PrateekPrakkash** [comment]
Hi @ccastrotrejo , I am using the "send an email(v2)" action of the outlook.com connector. It works well when we use the Outlook 365 connector. The issue only exists for outlook.com. Does this mean that the organisation account should only use outlook 365 connectors?

**Comment by ccastrotrejo** [comment]
Hi @PrateekPrakkash, that's correct. This means that your organization account has the appropriate tier and is part of Microsoft 365, unlike a regular free Outlook account. As a result, the connector's action will be different.
