### ISSUE TITLE
Logic app unable to load.

### ISSUE THREAD

**Issue by AlmienMG** [Azure/LogicAppsUX#6280]
Does this occur consistently? 

 Repro steps:

1\.

 2\.

Action: autoStartDesignTime

 Error type: TypeError

 Error Message: Cannot read properties of undefined (reading 'uri')

Version: 4.107.4

 OS: win32

 OS Release: 10.0.22621

 Product: Visual Studio Code

 Product Version: 1.96.1

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
Closing this one as duplicated of https://github.com/Azure/LogicAppsUX/issues/6274
