### ISSUE TITLE
Not able to displayed logic app designer menus/events-> want to send the email

### ISSUE THREAD

**Issue by amolapawar911** [Azure/LogicAppsUX#6283]
### Describe the Bug with repro steps 

1. go to azure portal 
2. create logic app -> select multi tenant 
3. go to logic app-> designer -> nothing is displayed 
4. go to developer -> version -> no event displayed 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

this options are not displayed 

![Image](<https://github.com/user-attachments/assets/3aa9db96-c71e-4ee5-a351-dd2288d2aaac>)

### Browser

chrome -> incognito mode

### Additional context

*No response*

**Comment by Eric-B-Wu** [comment]
It seems like you are using an older video for setting up your logic app, please refer to this guide for adding an action in Logic Apps Consumption: https://learn.microsoft.com/en-us/azure/logic-apps/create-workflow-with-trigger-or-action?tabs=consumption#add-action
