### ISSUE TITLE
VSCode error

### ISSUE THREAD

**Issue by nyannios** [Azure/LogicAppsUX#6284]
Does this occur consistently? YES

 Repro steps:

1. Logic Apps extension is enabled 
2. no error should appear. 

Action: autoStartDesignTime

 Error type: TypeError

 Error Message: Cannot read properties of undefined (reading 'uri')

Version: 4.107.4

 OS: darwin

 OS Release: 23.6.0

 Product: Visual Studio Code

 Product Version: 1.96.1

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
Closing this one as duplicated

**Comment by ccastrotrejo** [comment]
Closing this one as duplicated of https://github.com/Azure/LogicAppsUX/issues/6274
