### ISSUE TITLE
describe workflow not working

### ISSUE THREAD

**Issue by eva-shl** [Azure/LogicAppsUX#6288]
### Describe the Bug with repro steps 

workflow assistant not working![Image](<https://github.com/user-attachments/assets/4ced3563-28be-4a49-afe9-c05173485031>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hi @eva-shl thanks for raising this issue. I will close this issue as duplicated of https://github.com/Azure/LogicAppsUX/issues/6266. Can you verify if it's working here: https://aka.ms/emacanary?
