### ISSUE TITLE
When installing Azure Logic App (standard) extention in "remote"

### ISSUE THREAD

**Issue by orvarehn-EON** [Azure/LogicAppsUX#6289]
Does this occur consistently? 

 Repro steps:

1. No crash :-) 

Action: autoStartDesignTime

 Error type: TypeError

 Error Message: Cannot read properties of undefined (reading 'uri')

Version: 4.107.4

 OS: linux

 OS Release: 5.15.90.1-microsoft-standard-WSL2

 Product: Visual Studio Code

 Product Version: 1.96.2

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
Closing this one as duplicated of https://github.com/Azure/LogicAppsUX/issues/6274
