### ISSUE TITLE
Logic App Workflow Assistant is not working

### ISSUE THREAD

**Issue by MisbahAfreen** [Azure/LogicAppsUX#6290]
### Describe the Bug with repro steps 

Go to your Logic App workflow and click on Assistant. 

 Ask a query

 Error pops up with below:

**Sorry, something went wrong. Please try again.**

 chat-session-id:BB15EEC8-BC6E-4D57-8465-151B4DE50A58

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hi @MisbahAfreen thanks for raising this issue. I will close this issue as duplicated of https://github.com/Azure/LogicAppsUX/issues/6266. Can you verify if it's working here: https://aka.ms/emacanary?
